### ISSUE TITLE
PowerShell snap segfaults on Ubuntu 18.04 Azure VM

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10187]
# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none
7.0.0-preview.4
```

**Comment by SteveL-MSFT** [comment]
```none
Thread 25 "pwsh" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 32283]
0x00007ffff7de375c in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
(gdb) backtrace
#0  0x00007ffff7de375c in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7dec861 in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7de7574 in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7debdb9 in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
#4  0x00007ffff79b6f09 in ?? () from /snap/core/current/lib/x86_64-linux-gnu/libdl.so.2
#5  0x00007ffff7de7574 in ?? () from /snap/core/current/lib64/ld-linux-x86-64.so.2
#6  0x00007ffff79b7571 in ?? () from /snap/core/current/lib/x86_64-linux-gnu/libdl.so.2
#7  0x00007ffff79b6fa1 in dlopen () from /snap/core/current/lib/x86_64-linux-gnu/libdl.so.2
#8  0x00007ffff6586ec5 in PAL_LoadLibraryDirect () from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#9  0x00007ffff63c48a2 in NDirect::LoadLibraryModuleBySearch(Assembly*, int, unsigned int, LoadLibErrorTracker*, char16_t const*) () from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#10 0x00007ffff63c5c27 in NDirect::LoadLibraryModule(NDirectMethodDesc*, LoadLibErrorTracker*) ()
   from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#11 0x00007ffff63c3df9 in NDirect::NDirectLink(NDirectMethodDesc*) ()
   from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#12 0x00007ffff63c3d11 in NDirect::GetStubForILStub(NDirectMethodDesc*, MethodDesc**, unsigned int) ()
   from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#13 0x00007ffff63c408f in GetStubForInteropMethod(MethodDesc*, unsigned int, MethodDesc**) ()
   from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#14 0x00007ffff62582b5 in MethodDesc::DoPrestub(MethodTable*) ()
   from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#15 0x00007ffff6257c24 in PreStubWorker () from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#16 0x00007ffff637b95c in ThePreStub () from /snap/powershell-preview/32/opt/powershell/libcoreclr.so
#17 0x00007fff8294a3e6 in ?? ()
#18 0x0000000000000000 in ?? ()
```

**Comment by TravisEz13** [comment]
I think this only tell us it failed loading a library... We probably need to know what library.
