### ISSUE TITLE
CentOS 7 ZSH Powershell does not start

### ISSUE THREAD

**Issue by atiedemann** [PowerShell/PowerShell#10296]
# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

PowerShell does not start with ZSH Shell.

```

# Environment data

<!-- provide the output of $PSVersionTable -->
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by atiedemann** [comment]
Hello all together,
I install PowerShell Core 6.2.2 today on my Linux box with an ZSH Shell.
When I start the Shell I get this error:

VM-Linux01 :: ~ » pwsh
PowerShell 6.2.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

FailFast:
The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception.

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

Exception details:
System.TypeInitializationException: The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception. ---> System.ArgumentException: Item has already been added. Key in dictionary: 'SHELL'  Key being added: 'SHELL'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at System.Environment.GetEnvironmentVariables()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation..ctor()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformSingleton.get_Current()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()
   at Microsoft.PowerShell.ApplicationInsightsTelemetry..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ApplicationInsightsTelemetry.SendPSCoreStartupTelemetry()
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
[1]    71198 abort      pwsh

When I change the shell to BASH, PowerShell starts. I try to remove the ZSH profile .zshrc and try again, but this does also not work.

Does anyone have an idea?

**Comment by satorp** [comment]
As a workaround, have you tried disabling Powershell telemetry? You can disable it by setting the environment variable POWERSHELL_TELEMETRY_OPTOUT to 1.

**Comment by atiedemann** [comment]
Yes I do but I get the same error.

**Comment by iSazonov** [comment]
It seems you have some SHELL environment variables.

**Comment by atiedemann** [comment]
Yes I have some:

VM-Linux01 :: ~ » printenv | grep SHELL
SHELL=/bin/zsh
SHELL=/bin/zsh
POWERSHELL_TELEMETRY_OPTOUT=1

Have someone any idea why push is not starting?
Thanks
Arne

**Comment by DHowett-MSFT** [comment]
Is this another version of the duplicate environment variable bug? That really shouldn’t blow up powershell as hard as it does.

**Comment by iSazonov** [comment]
PowerShell doesn't track SHELL. It is a Microsoft.ApplicationInsights bug.

**Comment by satorp** [comment]
From the stack trace, the exception seems to be raised by  `System.Environment.GetEnvironmentVariables()`, probably when the telemetry object tries to check for the opt out variable. Is it possible that `System.Environment.GetEnvironmentVariables` in .NET Core does not support duplicate variables in zsh?

**Comment by iSazonov** [comment]
The issue should be moved to CoreClr repo.

**Comment by iSazonov** [comment]
Close as stale issue.
