### ISSUE TITLE
Inconsistent behavior between platforms when RedirectStandardOut is used and delayed data is received.

### ISSUE THREAD

**Issue by hpaul-osi** [PowerShell/PowerShell#10406]
# Steps to reproduce
This behavior was originally observed while doing batch copies of blob containers with the Az CLI, but a simple contrived example is below.  ReproduceIssue.ps1 is a minimal script that fires off a batch of tasks defined in DelayedStdOut.ps1 that do not receive data to standard out until after the parent process has exited.  If I run ReproduceIssue.ps1 in pwsh on Windows, there is no exception and the late output is not redirected to the text file.  When it is run on a Linux container, there is an unhandled exception.

**ReproduceIssue.ps1**
```powershell
$StdOutDelaySeconds = 5,
$RequestBatch = 5
@(1 .. $RequestBatch) | % {
    $processParameters = @{
        FilePath = 'pwsh'
        ArgumentList = @( '-file', "DelayedStdOut.ps1 $StdOutDelaySeconds")
        PassThru = $true
        RedirectStandardOut = Join-Path -Path (Get-Location) -ChildPath "$([System.Guid]::NewGuid().Guid).out.log"
    }
    Start-Process @processParameters
}
Start-Sleep (2*$StdOutDelaySeconds)
```

**DelayedStdOut.ps1**
```powershell
param(
    $StdOutDelaySeconds
)
Start-Process -FilePath pwsh -ArgumentList @('-c',"{Start-Sleep $StdOutDelaySeconds; Write-Output 'Test' }")
exit 0
```
# Expected behavior
On Windows, there is no exception and the standard output that was received after the process exited is not redirected to the file.

# Actual behavior
When executed on Unix (Linux Azure Container Instance), there is an unhandled exception because the object is disposed when the data is received.  Under less contrived circumstances, the issue only appears intermittently.  I saw [this comment](https://github.com/PowerShell/PowerShell/blob/8234fbb04b437748b6782e9c45b0026c374ef12d/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2192) in the if Unix region indicating that the ExitHandler waits for a second on another thread in hopes of avoiding a race condition whereas the non-Unix region has more involved logic.

```none
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.

Unhandled Exception: System.ObjectDisposedException: Cannot write to a closed TextWriter.
   at System.IO.StreamWriter.WriteLine(String value)
   at Microsoft.PowerShell.Commands.StartProcessCommand.StdOutputHandler(Object sendingProcess, DataReceivedEventArgs outLine)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__17_0(Object edi)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

# Environment data
Windows Environment
```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Unix Environment
```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@hpaul-osi Can you confirm the issue with latest 7.0 build?

**Comment by iSazonov** [comment]
@PaulHigin @daxian-dbw It is again redirections in Start-Process.
