### ISSUE TITLE
Start-Transcript causes skipped record when passing SqlDataReader object to another function

### ISSUE THREAD

**Issue by cameron-interactive** [PowerShell/PowerShell#10411]
Encountering an issue with Start-Transcript, SQLDataReader and Passing it to a function for processing. This occurs in Powershell 6, started in 5.1, was not present in Windows Powershell 3 (Windows Powershell 4 has issues passing the SqlDataReader object to a function anyway).

When you call a function within a Start-Transcript block, and that function then fills a SqlDataReader object, and then passes it onto another function, it increments the record a number of times, as if calling the read() method 7 or 8 times. This causes a number of issues, firstly, a lot of data is skipped for processing, secondly, you end up trying to read data which isn't available, resulting in an error.

This only occurs when Start-Transcript is called before running (and only while the transcript is actually running), and only when passing the SqlDataReader object to another function.

# Steps to reproduce

Run the following script. It will output 4 lots of values. The first one will error, the next 3 will not.

It attempts to run in the following manner - 

Pass 1 (Fail) - SqlDataReader passed to a function within a Start-Transcript block
Pass 2 (Success) - SqlDataReader passed to a function
Pass 3 (Success) - SqlDataReader processed inline within a Start-Transcript block
Pass 4 (Success) - SqlDataReader processed inline

Replace the $SQLConnectionString string with a real connection string, any SQL database should do (so long as it's SQL 2012+), no data needed in there. Also point the $transcriptPath to a file which can be saved to.

```powershell

$actualSql = "select top 25 cast(ROW_NUMBER() over(order by name) as nvarchar(255)) from sys.objects"
$SQLConnectionString = "<SQL Connection String Here>"
$transcriptPath = "<Transcript File Path Here>"
function get-Row{
    param(
        [System.Data.SqlClient.SqlDataReader] $TempReader
    )

    $row = @{}
    $row["FirstColumn"] = $TempReader.GetSqlValue(0)

    return $row
}

function test-SQL{
    param(
        [switch]$NoFunctionCall
    )
    $sqlConn = New-Object System.Data.SqlClient.SqlConnection
    $sqlConn.ConnectionString = $SQLConnectionString
    $sqlConn.Open()

    $sourcecmd = New-Object System.Data.SqlClient.SqlCommand
    $sourcecmd.Connection = $sqlConn
    $sourcecmd.CommandText = $actualSql
    $sourcecmd.CommandTimeout = 600
    [System.Data.SqlClient.SqlDataReader] $reader = $sourcecmd.ExecuteReader();

    try {
        if ($reader.HasRows -eq $true) {
            while ($reader.Read()) {
                if($NoFunctionCall){
                    write-output $reader.GetString(0)
                    $processed = @{}
                    $processed["FirstColumn"] = $reader.GetSqlValue(0)
                    write-output $reader.GetString(0)
                    Write-Output $processed.Value
                }
                else{
                    write-output $reader.GetString(0)
                    $processed = get-Row $reader
                    write-output $reader.GetString(0)
                    Write-Output $processed.Value
                }
            }
        }
    }
    catch{
        Write-Error $_.Exception | format-list -force
    }
}

Write-Output "Running With Transcript and Function"
Start-Transcript -Path $transcriptPath
test-SQL
Stop-Transcript

Write-Output "."
Write-Output "."
Write-Output "."
Write-Output "Running Without Transcript With Function"
test-SQL

Write-Output "."
Write-Output "."
Write-Output "."
Write-Output "Running With Transcript Without Function"
Start-Transcript -Path $transcriptPath
test-SQL -NoFunctionCall
Stop-Transcript

Write-Output "."
Write-Output "."
Write-Output "."
Write-Output "Running Without Transcript And Function"
test-SQL -NoFunctionCall

```

# Expected behavior

The expected output from this command would be as follows

```none
Running With Transcript and Function
Transcript started, output file is c:\Temp\PSTestLog.txt
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
Transcript stopped, output file is C:\Temp\PSTestLog.txt
.
.
.
Running Without Transcript With Function
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
.
.
.
Running With Transcript Without Function
Transcript started, output file is c:\Temp\PSTestLog.txt
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
Transcript stopped, output file is C:\Temp\PSTestLog.txt
.
.
.
Running Without Transcript And Function
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
```

# Actual behavior

We get the following error and odd iteration of data in the first test as shown in the output here.

```none
Running With Transcript and Function
Transcript started, output file is c:\Temp\PSTestLog.txt
1
8
9
16
17
24
25
test-SQL : System.Management.Automation.MethodInvocationException: Exception calling "GetSqlValue" with "1"
argument(s): "Invalid attempt to read when no data is present." ---> System.InvalidOperationException: Invalid attempt
to read when no data is present.
   at System.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn,
Boolean permitAsync, String methodName)
   at System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at System.Data.SqlClient.SqlDataReader.GetSqlValueInternal(Int32 i)
   at System.Data.SqlClient.SqlDataReader.GetSqlValue(Int32 i)
   at CallSite.Target(Closure , CallSite , SqlDataReader , Int32 )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At C:\temp\CommVault-Reporting\testReader.ps1:55 char:1
+ test-SQL
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,test-SQL

Transcript stopped, output file is C:\Temp\PSTestLog.txt
.
.
.
Runing Without Transcript With Function
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
.
.
.
Running With Transcript Without Function
Transcript started, output file is c:\Temp\PSTestLog.txt
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
Transcript stopped, output file is C:\Temp\PSTestLog.txt
.
.
.
Runing Without Transcript And Function
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
10
11
11
12
12
13
13
14
14
15
15
16
16
17
17
18
18
19
19
20
20
21
21
22
22
23
23
24
24
25
25
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Name                           Value
----                           -----
PSVersion                      5.1.16299.1004
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.1004
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
I guess the transcription is applied to parameters too. Perhaps @SeeminglyScience or @mklement0 could make more simple repo to help discover a root of the issue.
