### ISSUE TITLE
Formatter throws if property contains a default instance of ImmutableArray<>

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#10534]
# Steps to reproduce

```powershell
# Closest equivalent to C#'s "default" keyword
$defaultArray = [Activator]::CreateInstance(
    [System.Collections.Immutable.ImmutableArray[string]])

[PSCustomObject]@{
    SomeProperty = $defaultArray
}
```

# Expected behavior

The exception is expected (and by design), but I'd also expect that PowerShell would swallow it.  PowerShell already swallows exceptions thrown by `IEnumerator.MoveNext`, and all exceptions thrown by property get accessors.

```none
SomeProperty
------------

```

# Actual behavior

```none
format-default : Exception has been thrown by the target of an invocation.
+ CategoryInfo          : NotSpecified: (:) [format-default], TargetInvocationException
+ FullyQualifiedErrorId : System.Reflection.TargetInvocationException,Microsoft.PowerShell.Commands.FormatDefaultCommand
```

Full inner exception:

```
TargetSite     : Void ThrowInvalidOperationIfNotInitialized()
StackTrace     :    at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
                    at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
Message        : This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
Data           : {}
InnerException :
HelpLink       :
Source         : System.Collections.Immutable
HResult        : -2146233079
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Trace shows that PowerShell throws on GetEnumerator(). So it is .Net Core issue.

**Comment by SeeminglyScience** [comment]
@iSazonov Well the exception is by design.  I'm suggesting that PowerShell swallow it.  It already swallows exceptions thrown by the enumerator itself and any exceptions throw by property accessors.

**Comment by iSazonov** [comment]
@SeeminglyScience Please update the issue description.
