### ISSUE TITLE
Working directly with certain .NET types, such as Newtonsoft.Json's, is broken: output formatting

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10650]
Note: 

* I don't know whether / what other libraries are affected, or whether Newtonsoft.Json is an unusual one.

* The bug surfaces only if the input JSON text contains an _array_.

* The bug is a regression from Windows PowerShell, where it doesn't surface.

* The error is ultimately the same as in #10652: `Target type System.Collections.IEnumerator is not a value type or a non-abstract class. (Parameter 'targetType')`  - note how the type name is an _interface_, not a _class_.

# Steps to reproduce

```powershell
# Parse JSON text into a [JObject] instance.
# Note: To surface the bug, the text must contain an ARRAY
$obj = [Newtonsoft.Json.JsonConvert]::DeserializeObject('{ "foo": [ "bar" ] }')

# Apply default output formatting, which fails due to the bug:
{ $obj | Out-String } | Should -Not -Throw
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails, because the implicit output formatting threw an exception.

```none
Target type System.Collections.IEnumerator is not a value type or a non-abstract class. 
(Parameter 'targetType')
```

```none
PowerShell Core 7.0.0-preview.4
```

**Comment by iSazonov** [comment]
It seems it is not PowerShell issue:
```powershell
 $obj | Out-String
format-default: Target type System.Collections.IEnumerator is not a value type or a non-abstract class. (Parameter 'targetType')

Get-Error

Exception             :
    Type       : System.ArgumentException
    Message    : Target type System.Collections.IEnumerator is not a value type or a non-abstract class. (Para
meter 'targetType')
    ParamName  : targetType
    TargetSite :
        Name          : Convert
        DeclaringType : Newtonsoft.Json.Utilities.ConvertUtils, Newtonsoft.Json, Version=12.0.0.0, Culture=neu
tral, PublicKeyToken=30ad4fe6b2a6aeed
        MemberType    : Method
        Module        : Newtonsoft.Json.dll
    StackTrace :
   at Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(JValue instance, ConvertBinder binder, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.LanguagePrimitives.GetEnumerator(Object obj) in C:\Users\1\Documents\GitHub\iSazonov
\PowerShell\src\System.Management.Automation\engine\LanguagePrimitives.cs:line 556
   at System.Management.Automation.EnumerableOps.PropertyGetterWorker(CallSite`1 getMemberBinderSite, IEnumerator enume
rator, ExecutionContext context, List`1 result) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Managemen
t.Automation\engine\runtime\Operations\MiscOps.cs:line 3079
   at System.Management.Automation.EnumerableOps.PropertyGetter(PSGetMemberBinder binder, IEnumerator enumerator) in C:
\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:lin
e 3094
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValue(PSObject target, Boolean eatExceptions) in C:\Users\1
\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\Utilities\Mshexpression.c
s:line 339
   at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValues(PSObject target, Boolean expand, Boolean eatExceptio
ns) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\Utilitie
s\Mshexpression.cs:line 300
   at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValues(PSObject target) in C:\Users\1\Documents\GitHub\iSaz
onov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\Utilities\Mshexpression.cs:line 276
   at Microsoft.PowerShell.Commands.Internal.Format.PSObjectHelper.GetDisplayName(PSObject target, PSPropertyExpression
Factory expressionFactory) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAn
dOutput\common\Utilities\MshObjectUtil.cs:line 100
   at Microsoft.PowerShell.Commands.Internal.Format.PSObjectHelper.GetObjectName(Object x, PSPropertyExpressionFactory
expressionFactory) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\
common\Utilities\MshObjectUtil.cs:line 173
   at Microsoft.PowerShell.Commands.Internal.Format.PSObjectHelper.SmartToString(PSObject so, PSPropertyExpressionFacto
ry expressionFactory, Int32 enumerationLimit, StringFormatError formatErrorObject) in C:\Users\1\Documents\GitHub\iSazo
nov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\Utilities\MshObjectUtil.cs:line 279
   at Microsoft.PowerShell.Commands.Internal.Format.PSObjectHelper.FormatField(FieldFormattingDirective directive, Obje
ct val, Int32 enumerationLimit, StringFormatError formatErrorObject, PSPropertyExpressionFactory expressionFactory) in
C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\Utilities\MshOb
jectUtil.cs:line 363
   at Microsoft.PowerShell.Commands.Internal.Format.PSObjectHelper.GetExpressionDisplayValue(PSObject so, Int32 enumera
tionLimit, PSPropertyExpression ex, FieldFormattingDirective directive, StringFormatError formatErrorObject, PSProperty
ExpressionFactory expressionFactory, PSPropertyExpressionResult& result) in C:\Users\1\Documents\GitHub\iSazonov\PowerS
hell\src\System.Management.Automation\FormatAndOutput\common\Utilities\MshObjectUtil.cs:line 491
   at Microsoft.PowerShell.Commands.Internal.Format.ViewGenerator.GetExpressionDisplayValue(PSObject so, Int32 enumerat
ionLimit, PSPropertyExpression ex, FieldFormattingDirective directive, PSPropertyExpressionResult& expressionResult) in
 C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\FormatViewGene
rator.cs:line 374
   at Microsoft.PowerShell.Commands.Internal.Format.ViewGenerator.GetExpressionDisplayValue(PSObject so, Int32 enumerat
ionLimit, PSPropertyExpression ex, FieldFormattingDirective directive) in C:\Users\1\Documents\GitHub\iSazonov\PowerShe
ll\src\System.Management.Automation\FormatAndOutput\common\FormatViewGenerator.cs:line 360
   at Microsoft.PowerShell.Commands.Internal.Format.ListViewGenerator.GenerateListViewEntryFromProperties(PSObject so,
Int32 enumerationLimit) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOu
tput\common\FormatViewGenerator_List.cs:line 221
   at Microsoft.PowerShell.Commands.Internal.Format.ListViewGenerator.GeneratePayload(PSObject so, Int32 enumerationLim
it) in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\FormatVi
ewGenerator_List.cs:line 80
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.WritePayloadObject(PSObject so) in C:\Users
\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\BaseFormattingCommand.c
s:line 485
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so) in C:\Users\1\Do
cuments\GitHub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\BaseFormattingCommand.cs:lin
e 255
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessRecord() in C:\Users\1\Documents\Git
Hub\iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\BaseFormattingCommand.cs:line 118
   at Microsoft.PowerShell.Commands.Internal.Format.FrontEndCommandBase.ProcessRecord() in C:\Users\1\Documents\GitHub\
iSazonov\PowerShell\src\System.Management.Automation\FormatAndOutput\common\BaseCommand.cs:line 178
   at System.Management.Automation.Cmdlet.DoProcessRecord() in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\Syst
em.Management.Automation\engine\cmdlet.cs:line 173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in C:\Users\1\Documents\GitHub\iSazonov\PowerShell\
src\System.Management.Automation\engine\CommandProcessor.cs:line 387
    Source     : Newtonsoft.Json
    HResult    : -2147024809
CategoryInfo          : NotSpecified: (:) [format-default], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.FormatDefaultCommand
InvocationInfo        :
    MyCommand        : format-default
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 28
    Line             :  $obj | Out-String
    PositionMessage  : At line:1 char:2
                       +  $obj | Out-String
                       +  ~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

```

**Comment by mklement0** [comment]
What makes you conclude that, @iSazonov?
The problem is connected to PowerShell's output formatting system (even just outputting `$obj` by itself triggers the problem). By contrast, `$obj.ToString()` works just fine.

**Comment by mklement0** [comment]
I now see from your output that the call to `Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)` is where the problem lies - the question is whether we're passing the wrong `targetType` argument.

**Comment by mklement0** [comment]
But I haven't dug deeper, and perhaps resolving #10688 will also resolve this - and there we don't know yet whether the problem is in PowerShell or Json.Net.

**Comment by iSazonov** [comment]
The error message says that we send System.Collections.IEnumerator to Newtonsoft.Json.Utilities.ConvertUtils.Convert but $obj is JObject
I guess Out-String gets $obj as is. If so the issue comes from Json.NET limitations.

**Comment by iSazonov** [comment]
```powershell
$obj.GetTYpe().ImplementedInterfaces

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    IJEnumerable`1
True     False    IEnumerable`1
True     False    IEnumerable
True     False    IJsonLineInfo
True     False    ICloneable
True     False    IDynamicMetaObjectProvider
True     False    IList`1
True     False    ICollection`1
True     False    ITypedList
True     False    IBindingList
True     False    IList
True     False    ICollection
True     False    INotifyCollectionChanged
True     False    IDictionary`2
True     False    ICollection`1
True     False    IEnumerable`1
True     False    INotifyPropertyChanged
True     False    ICustomTypeDescriptor
True     False    INotifyPropertyChanging

```

**Comment by mklement0** [comment]
If I understand the error message correctly, Json.NET is saying that `System.Collections.IEnumerator` isn't acceptable as a `type` argument, so the question is: Why we are sending that type, given that we shouldn't?

So my _guess_ is that this is connected to #10688 in the sense that PowerShell may be delegating determining the target type to the Json.NET `IDynamicMetaDataProvider` implementation, which then reports the wrong type.

**Comment by iSazonov** [comment]
PropertyGetterWorker method enumerates recursively and it is called for a value making conversion to enumerator with  JValue.JValueDynamicProxy.TryConvert - the last method throw. I think only debug shows that happens in PropertyGetterWorker.

**Comment by iSazonov** [comment]
@mklement0 I found https://stackoverflow.com/questions/13968004/how-do-i-use-json-net-to-parse-json-in-powershell and this does not work neither PowerShell Core nor Windows PowerShell. I guess it is specific for  latest Newtonsoft lib.

**Comment by mklement0** [comment]
@iSazonov, the linked post is unrelated to the _output-formatting_ problem we're discussing here while the _parsing_ part (`$obj = [Newtonsoft.Json.JsonConvert]::DeserializeObject('{ "foo": [ "bar" ] }')` still works fine (just call `$obj.ToString()` to verify).

**Comment by mklement0** [comment]
My bad: that was only half the story: while parsing works in principle, there are display problems with _property access_:

While `$obj.foo[0]` _seemingly_ returns nothing, you need to use the `.Value` property to get the actual value: `$obj.foo[0].Value` returns `bar`.

`$obj.foo[0]` actually does return a `[Newtonsoft.Json.Linq.JValue]` instance, but by itself it again produces no visible output via the formatting system (while `.ToString()` again works).

Thus, ultimately the root cause _may_ be the same, related to how most Json.NET types are _enumerables.

**Comment by iSazonov** [comment]
Since no regression is from Windows PowerShell I think it makes no sense to invest to NewtonSoft Json.NET. If there are other similar scenarios, then we can consider improving this PropertyGetterWorker method.
