### ISSUE TITLE
Could not load file or assembly 'System.IdentityModel Version=4.0.0.0

### ISSUE THREAD

**Issue by danilo-lopes** [PowerShell/PowerShell#10818]
I'm trying to connect to Office365 environment through Powershell Core but seems to missing some Assembly libraries

I've installed Powershell core through Microsoft's Linux repository:

```
https://packages.microsoft.com/config/rhel/7/prod.repo
```

# Steps to reproduce

```
$username = 'foobar@domain'
$password = ConvertTo-SecureString -String 'XXXXXX' -AsPlainText -Force
Import-Module MSOnline
$credential = New-Object System.Management.Automation.PSCredential $username, $password
$session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid -Credential $credential -Authentication Basic -AllowRedirection
Import-PSSession $session
Connect-MsolService -Credential $credential
Get-MsolUser -UserPrincipalName USRLOGIN@domain | Format-List UserPrincipalName
```

# Expected behavior

```
This connection and Get-MsolUser must to happen

```

# Actual behavior

**Connect-MsolService -Credential $credential** command results:

```
Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
At line:1 char:1
+ Connect-MsolService -Credential $credential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.Online.Ad\u2026.ConnectMsolService:ConnectMsolService) [Connect-MsolService], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Online.Administration.Automation.ConnectMsolService.MsolCmdletProcessRecord()
   at Microsoft.Online.Administration.Automation.MsolCmdlet.ProcessRecord()
,Microsoft.Online.Administration.Automation.ConnectMsolService

Connect-MsolService : Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
At line:1 char:1
+ Connect-MsolService -Credential $credential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-MsolService], FileLoadException
+ FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.Online.Administration.Automation.ConnectMsolService
```

# Environment data

```
PowerShell 6.2.3

Linux CentOs 7 - 3.10.0-957.27.2.el7.x86_64
```

**Comment by SteveL-MSFT** [comment]
System.IdentityModel is not part of CoreFx so it can't be used with PSCore.  https://github.com/dotnet/corefx/issues/12623
