### ISSUE TITLE
Snap fails to run on Ubuntu 19.10 Eoan Ermine: Couldn't find a valid ICU package installed on the system.

### ISSUE THREAD

**Issue by rwh86** [PowerShell/PowerShell#10868]
On a freshly upgraded Ubuntu 19.10 system, I installed the powershell snap (version 6.2.3) through Software & Updates.  I am unable to launch powershell core with the "pwsh" command.  Instead, an error is thrown:

```FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted (core dumped)
```

I tried adding this configuration to ~/.config/powershell/profile.ps1:

`{ "runtimeOptions": { "configProperties": { "System.Globalization.Invariant": true } } }`

But this doesn't make a difference.

```snap info powershell
name:      powershell
summary:   PowerShell for every system!
publisher: Microsoft PowerShell✓
contact:   https://github.com/powershell/powershell
license:   unset
description: |
  PowerShell is an automation and configuration management platform.
  It consists of a cross-platform (Windows, Linux, and macOS)
  command-line shell and associated scripting language.
  
  See https://docs.microsoft.com/en-us/powershell/scripting/powershell-core-support for support
  details.
commands:
  - powershell
snap-id:      JSNnoJl3EqkMuWoy5Dgq8PMqZ0uNcpie
tracking:     stable
refresh-date: today at 11:56 AEDT
channels:
  stable:    6.2.3 2019-09-13 (39) 59MB classic
  candidate: 6.2.3 2019-09-13 (39) 59MB classic
  beta:      6.2.3 2019-09-13 (39) 59MB classic
  edge:      6.2.3 2019-10-23 (47) 59MB classic
installed:   6.2.3            (39) 59MB classic
```

```cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
```

**Comment by iSazonov** [comment]
@rwh86 Please move your report to https://github.com/PowerShell/PowerShell-Snap

**Comment by somabc** [comment]
You can fix this by running 

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 

in your shell first.
