### ISSUE TITLE
Get-Error situationally places other InnerException information before the Message output line

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11121]
_Update_: The issue is not one of _missing_ InnerException information, but one of situationally different _ordering_.

# Steps to reproduce

```powershell
# OK: The "InnerException :" line is followed by a "Message: " line for the inner exception.
try { 1/0 } catch {}; (Get-Error | Out-String -Stream) -replace '\e[^m]*m' | Select-String -context 0,1 '\bInnerException\b' | % { $_.Context.PostContext } | Should -Match 'Attempted to divide by zero'

# FAILS: The "InnerException :" line is followed by no fields describing the inner exception.
try { [int]::parse('foo') } catch {}; (Get-Error | Out-String -Stream) -replace '\e[^m]*m' | Select-String -context 0,1 '\bInnerException\b' | % { $_.Context.PostContext } | Should -Match 'not in a correct format'
```

# Expected behavior

Both tests should succeed.

# Actual behavior

The 2nd test fails:

```none
Expected regular expression 'not in a correct format' to match '        TargetSite : ', but it did not match.
```

That is, the `InnerException: ` line wasn't followed by the `Message: ` line.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by SteveL-MSFT** [comment]
@mklement0 I think your test is flawed, your query returns `TargetSite` which itself is an object and only one member of the InnerException.  Here's what I see running it manually:

```powershell
PS> [int]::Parse('foo')
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
[30.08ms] /Users/steve/repos/PowerShell [origin/get-error-exception-type]
PS> gerr

Exception             :
    ErrorRecord    :
        Exception             :
            Message : Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : FormatException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : [int]::Parse('foo')
            PositionMessage  : At line:1 char:1
                               + [int]::Parse('foo')
                               + ~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type
typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Type , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        TargetSite :
            Name          : ThrowOverflowOrFormatException
            DeclaringType : System.Number
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        StackTrace :
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at CallSite.Target(Closure , CallSite , Type , String )
        Message    : Input string was not in a correct format.
        Source     : System.Private.CoreLib
        HResult    : -2146233033
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : FormatException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [int]::Parse('foo')
    PositionMessage  : At line:1 char:1
                       + [int]::Parse('foo')
                       + ~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

The InnerException is there and expanded.  It just happens that the colons align but the indentation shows the members.

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT  - indeed I missed that the information is there.

What caused the confusion is that `TargetSite: ` information _comes first_, which I didn't expect.

How do you feel about making sure that at least the `Message :` line comes first?

**Comment by mklement0** [comment]
Thinking about pending PR, #11076, I suggest making at least the following two lines (properties) _always_ come first:

 * `Type: ` (full exception type name)

* `Message :`

If there are additional properties that are _always_ populated, I suggest listing them before those that are situationally missing.

**Comment by SteveL-MSFT** [comment]
@mklement0 the current order of the properties is what `$_.psobject.properties` returns.  We can certainly change the ordering.  It's hard to rely on properties that are *always* populated as I don't think any of it is enforced and Exceptions and ErrorRecords (particularly nested objects) can be any form.

**Comment by mklement0** [comment]
I think it definitely makes sense to put type and message first - they are always available and the most important properties.

I suggest putting the non-primitive properties (the ones with properties of their own or  "noisy" multi-line values) _last_, in that order:

* `Data`
* `TargetSite`
* `StackTrace`

Then follow that by a nested, indented `InnerException` block, as suggested in #11123 

My suggestion for the ordering of the remaining standard `System.Exception` properties - to go between type + message and the  non-primitive ones - is this:

* `Source`
* `HResult`
* `HelpLink`
