### ISSUE TITLE
System.AccessViolationException running AttackSurfaceAnalyzer v.2.1.34-beta+fc82c7bde8  FileSystemCollector

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#11149]
# Steps to reproduce
install latest version from https://github.com/microsoft/AttackSurfaceAnalyzer/releases

```powershell

cd \Asa-win-2.1.34-beta\res> 
.\asa.exe gui

```

# Expected behavior

FileSystemCollector should finish as it does when run from cmd.exe

```
[21:29:22 INF] AttackSurfaceAnalyzer v.2.1.34-beta+fc82c7bde8
Hosting environment: Production
Content root path: C:\Users\user\Downloads\Asa-win-2.1.34-beta\res
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
[21:30:31 INF] Loaded filters: Embedded
[21:30:31 INF] Begin 11/21/19, 09:29:54 PM.
[21:30:31 INF] Starting 1 Collectors.
[21:30:31 INF] Starting FileSystemCollector.
[21:30:31 INF] Scanning root C:\
[22:17:47 INF] Completed FileSystemCollector in 00h:47m:16s:437ms.
```
# Actual behavior

```
[22:58:03 INF] AttackSurfaceAnalyzer v.2.1.34-beta+fc82c7bde8
Hosting environment: Production
Content root path: C:\Users\user\Downloads\Asa-win-2.1.34-beta\res
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
[22:58:31 INF] Loaded filters: Embedded
[22:58:31 INF] Begin 11/21/19, 10:58:15 PM.
[22:58:31 INF] Starting 1 Collectors.
[22:58:31 INF] Starting FileSystemCollector.
[22:58:31 INF] Scanning root C:\
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at AttackSurfaceAnalyzer.Utils.NativeMethods.WinVerifyTrust(IntPtr, System.Guid, WinTrustData)
   at AttackSurfaceAnalyzer.Utils.NativeMethods.WinVerifyTrust(IntPtr, System.Guid, WinTrustData)
   at AttackSurfaceAnalyzer.Utils.NativeMethods.VerifyEmbeddedSignature(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.FileSystemInfoToFileSystemObject(System.IO.FileSystemInfo, Boolean, Boolean)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>b__7_0(System.IO.FileSystemInfo)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<PartitionerForEachWorker>b__1(System.Collections.IEnumerator ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.19018
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
https://github.com/microsoft/AttackSurfaceAnalyzer/issues/317#issuecomment-557244023

**Comment by mi-hol** [comment]
confirmed to still exist in newest pwsh preview 6

**Comment by iSazonov** [comment]
Perhaps ASA tries to read a file locked by pwsh.
