### ISSUE TITLE
Inconsistent in FileSystemProviderStrings.CannotRemoveItem usage and definition

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#11442]
Definition of `FileSystemProviderStrings.CannotRemoveItem`: `Cannot remove item {0}: {1}`

https://github.com/PowerShell/PowerShell/blob/0667e9620054dbe552c6302403dc4181c7309505/src/System.Management.Automation/resources/FileSystemProviderStrings.resx#L196
Usage:
https://github.com/PowerShell/PowerShell/blob/0667e9620054dbe552c6302403dc4181c7309505/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3056

This blows up with a 
```text
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Management.Automation.Internal.StringUtil.Format(String formatSpec, Object o)
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval)
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)
   at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean recurse, CmdletProviderContext context)
    Message    : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
```

```

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by powercode** [comment]
I suppose we should add the exception message:
```csharp
string error = StringUtil.Format(FileSystemProviderStrings.CannotRemoveItem, directory.FullName, e.Message);
```
