### ISSUE TITLE
"Invalid directory on URL" while trying to use path created using New-PSDrive in Powershell

### ISSUE THREAD

**Issue by Shridharfly** [PowerShell/PowerShell#11484]
I have written a function to get authentication token. I have used `New-PSDrive` because `PathTooLongException` was thrown. `Write-Host $adal, (Test-Path $adal)` returns `True` while testing if path exists. But throws exception in `LoadFrom()`. Could someone help me get rid of the error?

Code:

    function GetAuthToken {
        try{
            Write-Host "GetAuthToken-Start"
            If (!(Test-Path CustomDrive:)){
                $adalPath = Get-Module -Name "AzureRM.Profile" -ListAvailable -All | Select -First 1 | Select -ExpandProperty ModuleBase
                New-PSDrive -Name "CustomDrive" -PSProvider filesystem -Root $adalPath
                Write-Host "Created CustomDrive."
            }
            
            $adal = "CustomDrive:\Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
            $adalforms = "CustomDrive:\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll"
                
            Write-Host $adal, (Test-Path $adal) #Test-Path returns True
            Write-Host $adalforms, (Test-Path $adalforms)
            
            Write-Host "Loading required DLLs..."
            [System.Reflection.Assembly]::LoadFrom($adal) | Out-Null #This line throws exception
            [System.Reflection.Assembly]::LoadFrom($adalforms) | Out-Null
            Write-Host "Loaded required DLLs successfully."
    
            Write-Host "Trying to acquire token..."
            $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authorityUri
            $authResult = $authContext.AcquireToken($resourceUri, $clientId, $redirectUri, "Always") 
            Write-Host "Acquired token successfully."
    
            Write-Host $authResult
            Write-Host "GetAuthToken-End"
            return $authResult
        }
        catch{
            Write-Error -Message $_.Exception
            throw $_.Exception
        }
        finally{
            Remove-PSDrive -Name "CustomDrive"
            Write-Host "Removed CustomDrive."
        }
    }

Exception:

    GetAuthToken : System.Management.Automation.MethodInvocationException: Exception calling "LoadFrom" with "1" argument(s): "Invalid directory on 
    URL." ---> System.ArgumentException: Invalid directory on URL.
       at System.Security.Util.DirectoryString.CreateSeparatedString(String directory)
       at System.Security.Util.URLString.ParseFileURL(String url)
       at System.Security.Util.URLString.GetFileName()
       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly 
    reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean 
    suppressSecurityChecks)
       at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm 
    hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
       at System.Reflection.Assembly.LoadFrom(String assemblyFile)
       at CallSite.Target(Closure , CallSite , Type , Object )
       --- End of inner exception stack trace ---
       at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
       at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
       at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by iSazonov** [comment]
>  [System.Reflection.Assembly]::LoadFrom($adal) | Out-Null #This line throws exception

Perhaps `Add-Type -Path $adal` will works for you.

**Comment by Shridharfly** [comment]
Worked with `Add-Type`

https://stackoverflow.com/questions/59583133/invalid-directory-on-url-while-trying-to-use-path-created-using-new-psdrive-in?noredirect=1#comment105341319_59583133
