### ISSUE TITLE
Strange issue with console

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#11535]
# Steps to reproduce

Not really sure, I just tried to type into a console prompt

# Expected behavior

The console got the typed data

# Actual behavior

```powershell
Unhandled Exception: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: leftcommand pipeline position 1
Actual value was -1.e following parameters:
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine()
   at Microsoft.PowerShell.ConsoleHostUserInterface.PromptReadInput(String fieldPrompt, FieldDescription desc, Boolean fieldEchoOnPrompt, Boolean listInput, Boolean& endListInput, Boolean& cancelled)
   at Microsoft.PowerShell.ConsoleHostUserInterface.PromptForSingleItem(Type fieldType, String printFieldPrompt, String fieldPrompt, String caption, String message, FieldDescription desc, Boolean fieldEchoOnPrompt, Boolean listInput, Boolean& endListInput, Boolean& cancelInput, Object& convertedObj)
   at Microsoft.PowerShell.ConsoleHostUserInterface.Prompt(String caption, String message, Collection`1 descriptions)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.Prompt(String caption, String message, Collection`1 descriptions)
   at System.Management.Automation.CmdletParameterBinderController.PromptForMissingMandatoryParameters(Collection`1 fieldDescriptionList, Collection`1 missingMandatoryParameters)
   at System.Management.Automation.CmdletParameterBinderController.HandleUnboundMandatoryParameters(Int32 validParameterSetCount, Boolean processMissingMandatory, Boolean promptForMandatory, Boolean isPipelineInputExpected, Collection`1& missingMandatoryParameters)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Aborted (core dumped)
```

# Environment data

```powershell
PSVersion                      6.2.3
PSEdition                      Core
;2BCommitId                    6.2.3
OS                             Linux 4.14.145+ #1 SMP Tue Oct 8 03:03:11 PDT 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Will need some repro to figure this out.

**Comment by RDIL** [comment]
Okay, you can head to https://gitpod.io/#https://github.com/RDIL/PowerShell-Docker/tree/work , let it build, and then type `./build.ps1 -Build -All` and you will see.

**Comment by SteveL-MSFT** [comment]
@RDIL I just tried it and although I got some bad behavior, I didn't get the exception.  On the prompt for `Channel`, the cursor moved to the top left of the terminal.  Was able to type `preview` and get the build going.

**Comment by RDIL** [comment]
Strange.

**Comment by SteveL-MSFT** [comment]
When I checked $psversion, it showed 6.2.3

**Comment by iSazonov** [comment]
@RDIL Perhaps you resize console window?

**Comment by iSazonov** [comment]
Use latest PSReadline version.
