### ISSUE TITLE
Set vim shell to powershell

### ISSUE THREAD

**Issue by ChenWeird** [PowerShell/PowerShell#11631]
Detail: 
https://github.com/skywind3000/vim-terminal-help/issues/5

**Comment by iSazonov** [comment]
@ChenWeird Please add more info on English as our template for new issues requests.

**Comment by ChenWeird** [comment]
# Steps to reproduce

1. Win 10 x64
2. PowerShell Core 6.2.3
3. gVim 8.2 and Plug 'skywind3000/vim-terminal-help'
4. set vim shell to  PowerShell Core
 `let g:terminal_shell='pwsh'` 
or `let g:terminal_shell='C:\\Program Files\\PowerShell\\6\\pwsh.exe'`

# Expected behavior

1. Use vim-terminal-help's keymap to open PowerShell: `Alt =`
2. Vim window "PowerShell Core" open

# Actual behavior

but there have lots of failure messages

```none
PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

FailFast:
The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception.

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

Exception details:
System.TypeInitializationException: The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception. ---> System.ArgumentException: Item has already been added.
 Key in dictionary: 'VIM_SERVERNAME'  Key being added: 'VIM_SERVERNAME'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at System.Environment.GetEnvironmentVariables()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation..ctor()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformSingleton.get_Current()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()
   at Microsoft.PowerShell.ApplicationInsightsTelemetry..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ApplicationInsightsTelemetry.SendPSCoreStartupTelemetry()
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
```

# Environment data



```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KalleOlaviNiemitalo** [comment]
Could be a duplicate of <https://github.com/dotnet/corefx/issues/30341>.

**Comment by iSazonov** [comment]
@KalleOlaviNiemitalo Thanks! In the case it is already fixed.
@ChenWeird Can you repo with latest PowerShell 7.0 build?

**Comment by ChenWeird** [comment]
Thanks! It's fixed!

```
PowerShell 7.0.0-rc.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\chenw> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
