### ISSUE TITLE
ForEach-Object Parallel errors when executing from within the context of a custom PSDrive

### ISSUE THREAD

**Issue by duk3ofed** [PowerShell/PowerShell#11745]
# Steps to reproduce

```powershell
New-PSDrive -Name "foobar" -PSProvider FileSystem -Root C:\myFolder\
cd foobar:
1..10 | ForEach-Object -Parallel {write-host $_}
```

# Expected behavior

```none
To write numbers 1 through 10, to the host.
```

# Actual behavior

```none
ForEach-Object: An unexpected error has occurred while processing ForEach-Object -Parallel input. This may mean that some of the piped input did not get processed. Error: System.Management.Automation.DriveNotFoundException: Cannot find drive. A drive with the name 'foobar' does not exist.
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at System.Management.Automation.SessionStateInternal.AutomountBuiltInDrive(String name)
   at System.Management.Automation.SessionStateInternal.GetDrive(String name, Boolean automount)
   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context, Boolean literalPath)
   at System.Management.Automation.PSTasks.PSTaskBase.Start()
   at System.Management.Automation.PSTasks.PSTaskPool.Add(PSTaskBase task)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.<InitParallelParameterSet>b__63_2(Object _).
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by bpayette** [comment]
@duk3ofed  Drives are a per-runspace concept so I would expect this to fail. Each parallel task runs in it's own runspace and these runspaces do not have that drive resulting in the error. That said, there should be a better way to handle this.

**Comment by iSazonov** [comment]
Dup #11033.
