### ISSUE TITLE
Casting to a COM interface fails but `-is` returns `$true`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#11904]
# Steps to reproduce

```powershell
using namespace Windows.Devices.Enumeration
using namespace Windows.Foundation

$null = [Windows.Devices.Enumeration.DeviceInformation, Windows.Devices.Enumeration, ContentType = WindowsRuntime]
$asyncResult = [DeviceInformation]::FindAllAsync()
$asyncResult -is [IAsyncOperation[DeviceInformationCollection]]
# $true

[IAsyncOperation[DeviceInformationCollection]]$asyncResult
```

# Expected behavior

The same object is returned without any differences.

```none
System.__ComObject
```

# Actual behavior

```none
InvalidArgument:
Line |
   9 |  [IAsyncOperation[DeviceInformationCollection]]$asyncResult
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert the "System.__ComObject" value of type "System.__ComObject" to type "Windows.Foundation.IAsyncOperation`1[Windows.Devices.Enumeration.DeviceInformationCollection]".
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes

This happens mainly because the method that returns the object is typed as an interface and there isn't really a concrete implementation in the same way that there would be for non-COM objects.

If this worked it would be very useful due to the method binders behavior of selecting an overload based on explicit casting.  Fixing this would enable the use of methods like this without the mountains of reflection it currently requires.

For example, fixing this (possibly also conversions in the method binder) would enable this:

```powershell
$devices = [WindowsRuntimeSystemExtensions]::AsTask(
    [IAsyncOperation[DeviceInformationCollection]]$asyncResult).
    GetAwaiter().GetResult()
```

Also related: #9816

<details>

<summary>Full Get-Error output (click to expand)</summary>

```raw
Exception             :
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert the "System.__ComObject" value of type "System.__ComObject" to type "Windows.Foundation.IAsyncOperation`1[Windows.Devices.Enumeration.DeviceInformationCollection]".
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ConvertToFinalInvalidCastException
        InvocationInfo        :
            ScriptLineNumber : 9
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : [IAsyncOperation[DeviceInformationCollection]]$asyncResult

            PositionMessage  : At line:9 char:1
                               + [IAsyncOperation[DeviceInformationCollection]]$asyncResult
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 9
    Message        : Cannot convert the "System.__ComObject" value of type "System.__ComObject" to type "Windows.Foundation.IAsyncOperation`1[Windows.Devices.Enumeration.DeviceInformationCollection]".
    InnerException :
        Type        : System.Management.Automation.PSInvalidCastException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert the "System.__ComObject" value of type "System.__ComObject" to type "Windows.Foundation.IAsyncOperation`1[Windows.Devices.Enumeration.DeviceInformationCollection]".
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ConvertToFinalInvalidCastException
            InvocationInfo        :
                ScriptLineNumber : 9
                OffsetInLine     : 1
                HistoryId        : -1
                Line             : [IAsyncOperation[DeviceInformationCollection]]$asyncResult

                PositionMessage  : At line:9 char:1
                                   + [IAsyncOperation[DeviceInformationCollection]]$asyncResult
                                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, <No file>: line 9
        TargetSite  :
            Name          : ThrowInvalidCastException
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  :
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
        Message     : Cannot convert the "System.__ComObject" value of type "System.__ComObject" to type "Windows.Foundation.IAsyncOperation`1[Windows.Devices.Enumeration.DeviceInformationCollection]".
        Data        : System.Collections.ListDictionaryInternal
        Source      : System.Management.Automation
        HResult     : -2147467262
    HResult        : -2146233087
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : ConvertToFinalInvalidCastException
InvocationInfo        :
    ScriptLineNumber : 9
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [IAsyncOperation[DeviceInformationCollection]]$asyncResult

    PositionMessage  : At line:9 char:1
                       + [IAsyncOperation[DeviceInformationCollection]]$asyncResult
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 9
```

</details>

**Comment by SeeminglyScience** [comment]
This would also help with scenarios where a COM object implements multiple interfaces but `IDispatch` only reports the members of the "main" interface.

See [this StackOverflow](https://stackoverflow.com/q/63501159/1930135) for a real world example.  PowerShell's method binder lets you specify explicit interface implementations by casting the expression e.g. `([IList[string]]$obj).Add($item)`.  Assuming this logic will apply to COM objects, this would be a potentially easy way to enable calling COM interfaces like `Process2`.

cc @daxian-dbw

**Comment by daxian-dbw** [comment]
@SeeminglyScience Give that .NET 5 doesn't consume Windows metadata files anymore, the line `[Windows.Devices.Enumeration.DeviceInformation, ... , ContentType = WindowsRuntime]` doesn't work in 7.1-preview. Can you please maybe provide a new repro without involving the a WinRT object?

**Comment by SeeminglyScience** [comment]
@daxian-dbw Yeah it'll take me a minute though.  I don't use built in COM objects much so I don't know one off the top of my head, in the mean time the SO above has a non-winrt example.

If anyone happens to know a default COM object that implements `IUnknown` but not `IDispatch`, drop it here please ❤️
