### ISSUE TITLE
Jobs failed in Start-Job with an SecureString argument.

### ISSUE THREAD

**Issue by 0x6797** [PowerShell/PowerShell#12109]
# Steps to reproduce

```powershell
$job = (Start-Job -Name 'a job' -FilePath .\Exec-Job.ps1 -ArgumentList (ConvertTo-SecureString -String 'aaa' -AsPlainText -Force))
$job
```

My repository is :
https://github.com/0x6797/azure-powershell-jobs

And I has executed ./Exec-Parallel-Jobs.ps1

It is similar to this issue.
https://github.com/PowerShell/PowerShell/issues/7172

# Expected behavior

```none
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
9      a job           BackgroundJob   Completed     True            localhost            [CmdletBinding()]…
```

# Actual behavior

It failed on Linux, but it succeed on Windows PowerShell 7

```none
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
9      a job           BackgroundJob   Failed        False           localhost            [CmdletBinding()]…
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Why do you use AsPlainText ?

**Comment by 0x6797** [comment]
```powershell
$job = (Start-Job -Name 'a job' -FilePath .\Exec-Job.ps1 -ArgumentList (ConvertTo-SecureString -String 'aaa'  -Force))            

ConvertTo-SecureString: The parameter value "aaa" is not a valid encrypted string.
```

I'm using a SecureString to specify a machine password in Azure PowerShell.

**Comment by iSazonov** [comment]
Sorry, I skipped that you use plain text.

Could you share an error from failed job?

**Comment by 0x6797** [comment]
Never mind.
It occurs no error in a failed job.

```powershell
$job = Start-Job -Name "a job" -FilePath ./Exec-Job.ps1 -ArgumentList (ConvertTo-SecureString -String 'aaa' -AsPlainText -Force)                                                          
$job | ConvertTo-Json
````

```json
{
  "HasMoreData": false,
  "StatusMessage": null,
  "Location": "localhost",
  "Command": "[CmdletBinding()]\nparam (\n    [Parameter(Mandatory=$true, HelpMessage=\"The admin password for the VM\")]\n    [System.Security.SecureString] $Password\n)\n\n\n$DebugPreference = \"Continue\" \nSet-StrictMode -Version Latest\n\nreturn \"Succeeded\"",
  "JobStateInfo": {
    "State": 3,
    "Reason": null
  },
  "Finished": {
    "Handle": {
      "value": 5700
    },
    "SafeWaitHandle": {
      "IsInvalid": false,
      "IsClosed": false
    }
  },
  "InstanceId": "fb2d01c8-b861-4563-bd58-18d0e3cb345e",
  "Id": 3,
  "Name": "a job",
  "ChildJobs": [
    {
      "StatusMessage": "",
      "HasMoreData": false,
      "Location": "localhost",
      "Runspace": "System.Management.Automation.RemoteRunspace",
      "Debugger": "System.Management.Automation.RemotingJobDebugger",
      "IsAsync": true,
      "Command": "[CmdletBinding()]\nparam (\n    [Parameter(Mandatory=$true, HelpMessage=\"The admin password for the VM\")]\n    [System.Security.SecureString] $Password\n)\n\n\n$DebugPreference = \"Continue\" \nSet-StrictMode -Version Latest\n\nreturn \"Succeeded\"",
      "JobStateInfo": "Failed",
      "Finished": "System.Threading.ManualResetEvent",
      "InstanceId": "0371e42b-eb2e-4b26-9787-77c9afeb94bf",
      "Id": 4,
      "Name": "Job4",
      "ChildJobs": "",
      "PSBeginTime": null,
      "PSEndTime": "2020-03-13T02:05:22.3741521+00:00",
      "PSJobTypeName": "",
      "Output": "",
      "Error": "",
      "Progress": "",
      "Verbose": "",
      "Debug": "",
      "Warning": "",
      "Information": ""
    }
  ],
  "PSBeginTime": "2020-03-13T02:05:21.5682664+00:00",
  "PSEndTime": "2020-03-13T02:05:22.3741626+00:00",
  "PSJobTypeName": "BackgroundJob",
  "Output": [],
  "Error": [],
  "Progress": [],
  "Verbose": [],
  "Debug": [],
  "Warning": [],
  "Information": [],
  "State": "Failed"
}
```

**Comment by 0x6797** [comment]
Should I avoid to use SecureString?
https://github.com/PowerShell/PowerShell/issues/12114#issuecomment-598192488

If so, Could I see a warning or a 'deprecated' message when I would use ConvertTo-SecureString.

**Comment by iSazonov** [comment]
I ask about error because I guess there is the same error as in https://github.com/PowerShell/PowerShell/issues/4952. I guess it is an issue with libme on Unix/MacOs.
Perhaps @PaulHigin have thoughts.

**Comment by 0x6797** [comment]
Thank you for your response.
Could you tell me how to get errors in my environment?

**Comment by iSazonov** [comment]
If Get-Error show nothing you could build and debug.

**Comment by 0x6797** [comment]
Is here what you want?

```yaml
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    : 
    Exception             : 
        Type        : System.Management.Automation.PSArgumentOutOfRangeException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                          Actual value was 1.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ArgumentOutOfRange
        Message     : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                      Actual value was 1.
        ActualValue : 1
        ParamName   : Scope
        TargetSite  : 
            Name          : GetScopeByID
            DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  : 
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Source      : System.Management.Automation
        HResult     : -2146233086
    CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentOutOfRangeException
    FullyQualifiedErrorId : ArgumentOutOfRange,Microsoft.PowerShell.Commands.GetVariableCommand
    InvocationInfo        : 
        MyCommand       : Get-Variable
        HistoryId       : 24
        InvocationName  : Get-Variable
        CommandOrigin   : Internal
    ScriptStackTrace      : at <ScriptBlock>, /home/hayashi_toshiki/Documents/azure-powershell-jobs/Exec-Parallel-Jobs.ps1: line 22
                            at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     : 
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     : 
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 760
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 809
Message        : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                 Actual value was 1.
InnerException : 
    Type        : System.Management.Automation.PSArgumentOutOfRangeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                      Actual value was 1.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ArgumentOutOfRange
    Message     : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                  Actual value was 1.
    ActualValue : 1
    ParamName   : Scope
    TargetSite  : 
        Name          : GetScopeByID
        DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace  : 
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source      : System.Management.Automation
    HResult     : -2146233086
Source         : System.Management.Automation
HResult        : -2146233087
```

> Also direct call Exec-Job.ps1 works well?

I called Exec-Job.ps1 directly, and it completed normally.
But, I could see System.Management.Automation.CmdletInvocationException in invoking that script.

Here is.

```yaml
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    : 
    Exception             : 
        Type        : System.Management.Automation.PSArgumentOutOfRangeException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                          Actual value was 1.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ArgumentOutOfRange
        Message     : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                      Actual value was 1.
        ActualValue : 1
        ParamName   : Scope
        TargetSite  : 
            Name          : GetScopeByID
            DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  : 
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Source      : System.Management.Automation
        HResult     : -2146233086
    CategoryInfo          : InvalidArgument: (:) [Get-Variable], PSArgumentOutOfRangeException
    FullyQualifiedErrorId : ArgumentOutOfRange,Microsoft.PowerShell.Commands.GetVariableCommand
    InvocationInfo        : 
        MyCommand       : Get-Variable
        HistoryId       : 32
        InvocationName  : Get-Variable
        CommandOrigin   : Internal
    ScriptStackTrace      : at <ScriptBlock>, /home/hayashi_toshiki/Documents/azure-powershell-jobs/Exec-Job.ps1: line 8
                            at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo : 



TargetSite     : 
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     : 
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 908
   at Microsoft.PowerShell.EditorServices.Services.PowerShellContextService.ExecuteCommandAsync[TResult](PSCommand psCommand, StringBuilder errorMessages, ExecutionOptions executionOptions) in D:\a\1\s\src\PowerShellEditorServices\Services\PowerShellContext\PowerShellContextService.cs:line 908
Message        : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                 Actual value was 1.
InnerException : 
    Type        : System.Management.Automation.PSArgumentOutOfRangeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                      Actual value was 1.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ArgumentOutOfRange
    Message     : The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
                  Actual value was 1.
    ActualValue : 1
    ParamName   : Scope
    TargetSite  : 
        Name          : GetScopeByID
        DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace  : 
   at System.Management.Automation.SessionStateInternal.GetScopeByID(Int32 scopeID)
   at System.Management.Automation.SessionStateInternal.GetScopeByID(String scopeID)
   at System.Management.Automation.SessionStateInternal.GetVariableTableAtScope(String scopeID)
   at Microsoft.PowerShell.Commands.VariableCommandBase.GetMatchingVariables(String name, String lookupScope, Boolean& wasFiltered, Boolean quiet)
   at Microsoft.PowerShell.Commands.GetVariableCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source      : System.Management.Automation
    HResult     : -2146233086
Source         : System.Management.Automation
HResult        : -2146233087
```

**Comment by mklement0** [comment]
I think the error is unrelated to `SecureString`, and instead relates to scoping:

The problem is that by using `Start-Job -FilePath`, the _content_ of the referenced script file executes _directly in the global scope_, and if your script contains attempts  to reference any scope _above_ the current scope - notably via `Get-Variable -Scope 1` - an error occurs, because the global scope is the topmost scope.

Here's a simple demonstration:

```powershell
@'
'in'
Get-Variable HOME -Scope 1 -ValueOnly
'out'
'@ > t.ps1

Start-Job -FilePath ./t.ps1 | Receive-Job -Wait -AutoRemove
```

If you run `./t.ps1` directly, it'll work as expected and report the value of the automatic `$HOME` variable.

By contrast, the invocation via `Start-Job -FilePath` above yields the following:

```none
in
Get-Variable: The scope number '1' exceeds the number of active scopes. (Parameter 'Scope')
Actual value was 1.
out
```
