### ISSUE TITLE
LocalAccounts module not working with PS7

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#12478]
The `Microsoft.PowerShell.LocalAccounts` module is marked as `Core` compatible.  If you import the dll directly, it does work.  But if you import the psd1, it complains that an assembly with the same name is already loaded.

# Steps to reproduce

```powershell
Get-LocalUser
```

# Expected behavior

```none
Get-LocalUser should return user objects
```

# Actual behavior

```none
PS> Get-Localuser
Get-Localuser: The 'Get-Localuser' command was found in the module 'Microsoft.PowerShell.LocalAccounts', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.LocalAccounts'.
[316.11ms] C:\Users\slee
PS> ipmo Microsoft.PowerShell.LocalAccounts
Import-Module: Assembly with same name is already loaded
[67.92ms] C:\Users\slee
PS> get-error

Exception             :
    Type       : System.IO.FileLoadException
    Message    : Assembly with same name is already loaded
    TargetSite :
        Name          : LoadBinaryModule
        DeclaringType : Microsoft.PowerShell.Commands.ModuleCmdletBase
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace :
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean
trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss,
ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes,
Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String
moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags
manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName,
String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options,
ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule,
ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss,
ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean
loadFormatFiles, Object privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo
manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version
minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions&
options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String
moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags
manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName,
String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options,
ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(String moduleBase,
ManifestProcessingFlags manifestProcessingFlags, ImportModuleOptions importModuleOptions, Boolean& found)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, Boolean found,
IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags
manifestProcessingFlags, PSModuleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions
importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions
importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.Management.Automation
    HResult    : -2146232799
CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not repo on latest build:
```
 Get-Localuser

Name               Enabled Description
----               ------- -----------
1                  True
Administrator      False   Built-in account for administering the computer/domain
DefaultAccount     False   A user account managed by the system.
defaultuser0       False
Guest              False   Built-in account for guest access to the computer/domain
test               False
test1              True
TestUser1          True
TestUserGet3       False   Describe
TestUserRemove1    True
TestUserRemove2    True
TestUserSet2       True
WDAGUtilityAccount False   A user account managed and used by the system for Windows Defender Application Guard scenar…

PS C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp5.0\win7-x64\publish> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0                   International                       {Get-WinAcceptLanguageFromLanguageListOptOut, Get…
Manifest   7.0.0.0               Microsoft.PowerShell.Host           {Start-Transcript, Stop-Transcript}
Binary     1.0.0.0               Microsoft.PowerShell.LocalAccounts  {Add-LocalGroupMember, Disable-LocalUser, Enable-…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Manifest   7.0.0.0               Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-…
Script     1.4.6                 PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package,…
Script     1.0                   PKI                                 {Add-CertificateEnrollmentPolicyServer, Export-Ce…
Script     2.0.1                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

PS C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp5.0\win7-x64\publish> Get-Module Microsoft.PowerShell.LocalAccounts | fl

Name              : Microsoft.PowerShell.LocalAccounts
Path              : C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.LocalAccounts\1.0.0.0\Micro
                    soft.Powershell.LocalAccounts.dll
Description       : Provides cmdlets to work with local users and local groups
ModuleType        : Binary
Version           : 1.0.0.0
PreRelease        :
NestedModules     : {}
ExportedFunctions :
ExportedCmdlets   : {Add-LocalGroupMember, Disable-LocalUser, Enable-LocalUser, Get-LocalGroup…}
ExportedVariables :
ExportedAliases   : {algm, dlu, elu, glg…}
```

**Comment by doctordns** [comment]
Works here:
```powershell
PS C:\foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.19608
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0-preview.2}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\foo> get-localuser

Name               Enabled Description
----               ------- -----------
Administrator      False   Built-in account for administering the computer/domain
DefaultAccount     False   A user account managed by the system.
Guest              False   Built-in account for guest access to the computer/domain
tfl                True
WDAGUtilityAccount False   A user account managed and used by the system for Windows Defender Application Guard scenar…

**Comment by SteveL-MSFT** [comment]
Interesting, need to figure out why it's not working on my system.

**Comment by iSazonov** [comment]
I only guess WinCompat loaded the assembly first.

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

It's working on both of my Windows 10 April 2020 and Windows Insider edition too. Of course, last few days I did the service updates that were pending. And, I try them in both PowerShell 7 and Preview.2.

![localGrp3_2020-04-27_15-28-01](https://user-images.githubusercontent.com/19892435/80416751-a6a2fb80-88a2-11ea-88c3-a15b0275f282.png)

![localGrp_2020-04-27_15-28-01](https://user-images.githubusercontent.com/19892435/80416775-adca0980-88a2-11ea-99a7-87a3fa1563f1.png)

![localGrp2_2020-04-27_15-28-01](https://user-images.githubusercontent.com/19892435/80417929-968c1b80-88a4-11ea-8cf9-911b00a553b8.png)
