### ISSUE TITLE
Progress rendering may cause PowerShell to crash

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#12485]
# Steps to reproduce

Not sure exactly how I encountered this but I was running in WT and I had this process in the top half of a split pane setup. I had just run a command to display progress. But I had done this several times with no crash.  This is the command that I was running to display the progress bar:

```powershell
1..100 | % {Write-Progress -Activity Demo -PercentComplete $_; Start-Sleep -Milliseconds 500}
```

# Expected behavior

PowerShell should not crash.

# Actual behavior

PowerShell crashed.

```none
Actual value was 39.
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.CheckCoordinateWithinBuffer(Coordinates& c, CONSOLE_SCREEN_BUFFER_INFO& bufferInfo, String paramName)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ConsoleHostUserInterface.ResetProgress()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
[process exited with code 2148734499]
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Did you change Windows Terminal position or size?

**Comment by rkeithhill** [comment]
I didn't change the outer frame but this pane's size changed when I opened another split pane below it.

**Comment by iSazonov** [comment]
For reference #11913

**Comment by rkeithhill** [comment]
OK I can repro this.  Open a PowerShell 7 tab in WT.  Execute this:
```
1..100 | %{Write-Progress -Activity 'Progress in PSIC' -PercentComplete $_; Sleep -m 500}
```
Then open up a horizontal split-pane and then just wait for the progress bar to finish and remove itself.  That's when it crashes:
![image](https://user-images.githubusercontent.com/5177512/80444336-bafced80-88ce-11ea-872a-5d620f4671a1.png)

**Comment by DHowett-MSFT** [comment]
This will happen on all console hosts where the buffer size is equal to the screen size and the buffer/screen size change during the progress operation. This is not a reasonable state in which to fail. :smile:

**Comment by DHowett-MSFT** [comment]
When writing back the output cells, PowerShell needs to _not instantly beef it_ when it fails to do so. The data that's lost isn't worth destroying the user's session over.

**Comment by KalleOlaviNiemitalo** [comment]
I think I hit the same error on PowerShell 7.1.3 in Windows Terminal, when I resized the window (moved it to a different monitor) during an operation that was displaying progress.  The process however did not terminate, and the operation continued after the error. There are currently no try…catch statements in the script; if there had been one, I fear that it might have unnecessarily escalated the error.

```
Write-Progress: C:\REDACTED\REDACTED.ps1:364
Line |
 364 |              Write-Progress -Activity $Activity `
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of
     | 140,49. (Parameter 'value.Y') Actual value was 51.

PS C:\REDACTED> get-error

Exception             :
    Type        : System.Management.Automation.PSArgumentOutOfRangeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 140,49. (Parameter 'value.Y')
                      Actual value was 51.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ArgumentOutOfRange
    Message     : Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 140,49. (Parameter 'value.Y')
                  Actual value was 51.
    ActualValue : 51
    ParamName   : value.Y
    TargetSite  :
        Name          : CheckCoordinateWithinBuffer
        DeclaringType : Microsoft.PowerShell.ConsoleHostRawUserInterface, Microsoft.PowerShell.ConsoleHost, Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : Microsoft.PowerShell.ConsoleHost.dll
    StackTrace  :
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.CheckCoordinateWithinBuffer(Coordinates& c, CONSOLE_SCREEN_BUFFER_INFO& bufferInfo,
String paramName)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ProgressPane.Show(PendingProgress pendingProgress)
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(Int64 sourceId, ProgressRecord progressRecord, Boolean overrideInquire)
   at Microsoft.PowerShell.Commands.WriteProgressCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source      : Microsoft.PowerShell.ConsoleHost
    HResult     : -2146233086
CategoryInfo          : InvalidArgument: (:) [Write-Progress], PSArgumentOutOfRangeException
FullyQualifiedErrorId : ArgumentOutOfRange,Microsoft.PowerShell.Commands.WriteProgressCommand
InvocationInfo        :
    MyCommand        : Write-Progress
    ScriptLineNumber : 364
    OffsetInLine     : 13
    HistoryId        : 4
    ScriptName       : C:\REDACTED\REDACTED.ps1
    Line             : Write-Progress -Activity $Activity `

    PositionMessage  : At C:\REDACTED\\REDACTED.ps1:364 char:13
                       +             Write-Progress -Activity $Activity `
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\REDACTED
    PSCommandPath    : C:\REDACTED\REDACTED.ps1
    InvocationName   : Write-Progress
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\REDACTED\REDACTED.ps1: line 364
                        at <ScriptBlock>, C:\REDACTED\REDACTED.ps1: line 359
                        at <ScriptBlock>, <No file>: line 1

PS C:\REDACTED> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by robinmalik** [comment]
I just hit a similar issue with PowerShell 7.1.3 within Windows Terminal, whilst using PowerCLI to run the following line: `Set-VMhost -VMHost 'REDACTED' -State connected`. No additional tabs open, single monitor.

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Error

   ErrorIndex: 1

[92mException             : [0m
    [92mType              : [0mVMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.VimException
    [92mErrorId           : [0mCore_BaseCmdlet_UnknownError
    [92mRecommendedAction : [0mError occured while executing cmdlet: Set-VMHost. Check inner exception for more details.
    [92mSeverity          : [0mError
    [92mTargetSite        : [0m
        [92mName          : [0mThrowTerminatingError
        [92mDeclaringType : [0mSystem.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        [92mMemberType    : [0mMethod
        [92mModule        : [0mSystem.Management.Automation.dll
    [92mStackTrace        : [0m
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    [92mMessage           : [0m21/05/2021 10:11:48	Set-VMHost		Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 168,27. (Parameter 'value.Y')
                        Actual value was 43.
    [92mData              : [0mSystem.Collections.ListDictionaryInternal
    [92mInnerException    : [0m
        [92mType        : [0mSystem.Management.Automation.PSArgumentOutOfRangeException
        [92mErrorRecord : [0m
            [92mException             : [0m
                [92mType    : [0mSystem.Management.Automation.ParentContainsErrorRecordException
                [92mMessage : [0mCannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 168,27. (Parameter 'value.Y')
                          Actual value was 43.
                [92mHResult : [0m-2146233087
            [92mCategoryInfo          : [0mInvalidArgument: (:) [], ParentContainsErrorRecordException
            [92mFullyQualifiedErrorId : [0mArgumentOutOfRange
        [92mMessage     : [0mCannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 168,27. (Parameter 'value.Y')
                      Actual value was 43.
        [92mActualValue : [0m43
        [92mParamName   : [0mvalue.Y
        [92mTargetSite  : [0m
            [92mName          : [0mCheckCoordinateWithinBuffer
            [92mDeclaringType : [0mMicrosoft.PowerShell.ConsoleHostRawUserInterface, Microsoft.PowerShell.ConsoleHost, Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            [92mMemberType    : [0mMethod
            [92mModule        : [0mMicrosoft.PowerShell.ConsoleHost.dll
        [92mStackTrace  : [0m
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.CheckCoordinateWithinBuffer(Coordinates& c, CONSOLE_SCREEN_BUFFER_INFO& bufferInfo, String paramName)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ProgressPane.Show(PendingProgress pendingProgress)
   at Microsoft.PowerShell.ConsoleHostUserInterface.HandleIncomingProgressRecord(Int64 sourceId, ProgressRecord record)
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(Int64 sourceId, ProgressRecord progressRecord, Boolean overrideInquire)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(ProgressRecord progressRecord, Boolean overrideInquire)
   at System.Management.Automation.MshCommandRuntime.WriteProgress(ProgressRecord progressRecord)
   at System.Management.Automation.Cmdlet.WriteProgress(ProgressRecord progressRecord)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.ProgressCallback(Task task, Object result, Boolean writeResultToScreen)
   at VMware.VimAutomation.Sdk.Impl.V1.Task.ClientSideTaskCoreServiceProvider.CheckTaskCompletion(List`1 remainingTaskList, List`1& completedTaskList, ProgressCallback progressCallback)
   at VMware.VimAutomation.Sdk.Impl.V1.Task.CoreTaskServiceImpl.WaitForTask(IEnumerable`1 taskList, ProgressCallback progressCallback)
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.BaseCmdlet.EndProcessingErrorHandled()
   at VMware.VimAutomation.ViCore.Util10Ps.BaseCmdlet.BaseCmdlet.EndProcessingErrorHandled()
        [92mSource      : [0mMicrosoft.PowerShell.ConsoleHost
        [92mHResult     : [0m-2146233086
    [92mSource            : [0mSystem.Management.Automation
    [92mHResult           : [0m-2146232832
[92mCategoryInfo          : [0mNotSpecified: (:) [Set-VMHost], VimException
[92mFullyQualifiedErrorId : [0mCore_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.SetVMHost
[92mInvocationInfo        : [0m
    [92mMyCommand        : [0mSet-VMHost
    [92mScriptLineNumber : [0m1
    [92mOffsetInLine     : [0m1
    [92mHistoryId        : [0m26
    [92mLine             : [0mset-vmhost -VMHost 'REDACTED' -State connected
    [92mPositionMessage  : [0mAt line:1 char:1
                       + set-vmhost -VMHost 'REDACTED' -State connected
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [92mInvocationName   : [0mset-vmhost
    [92mCommandOrigin    : [0mInternal
[92mScriptStackTrace      : [0mat <ScriptBlock>, <No file>: line 1
	
```

Funky characters are the result of piping the command to `clip` and pasting here.

**Comment by KalleOlaviNiemitalo** [comment]
Saving the text behind the progress bar and restoring it later is not compatible with supplementary characters either, as [ReadConsoleOutput](https://docs.microsoft.com/windows/console/readconsoleoutput) cannot fit them in [CHAR_INFO](https://docs.microsoft.com/windows/console/char-info-str).

```PowerShell
Clear-Host; "`n`n`u{1F600}`n`n`n`n`n"; Start-Sleep -Seconds 1; Write-Progress -Activity "Make some progress" -PercentComplete 50; Start-Sleep -Seconds 1; Write-Progress -Activity "Make some progress" -Completed
```

If minimal progress rendering <https://github.com/PowerShell/PowerShell/issues/14426> eventually becomes the default, then it will fix these problems for good, I hope.

**Comment by mladedav** [comment]
This happened to me too just now. Splitting a pane while downloading a large file to keep working. Powershell instead gave up on the download.

**Comment by yumaikas** [comment]
I've hit something similar on OSX, with a much smaller repro in #16174. Maybe a SIGWINCH is getting dropped somewhere, if WinTerminal is generating one?
