### ISSUE TITLE
parallel process does not keep default encoding (active code page)

### ISSUE THREAD

**Issue by hdformat** [PowerShell/PowerShell#12622]
I 

# Steps to reproduce

```powershell
PS > 1..3 | foreach { iex "python -c `"print('🤡')`"" }
PS > 1..3 | foreach -parallel { iex "python -c `"print('🤡')`"" } 
```

# Expected behavior

```powershell
PS > 1..3 | foreach { iex "python -c `"print('🤡')`"" }
🤡
🤡
🤡
PS > 1..3 | foreach -parallel { iex "python -c `"print('🤡')`"" } 
🤡
🤡
🤡
```

# Actual behavior

```powershell
PS > 1..3 | foreach { iex "python -c `"print('🤡')`"" }
🤡
🤡
🤡
PS > 1..3 | foreach -parallel { iex "python -c `"print('🤡')`"" } 
Traceback (most recent call last):   
File "<string>", line 1, in <module> UnicodeEncodeError: 'cp949' codec can't encode character '\u2728' in position 0: illegal multibyte sequence
 Traceback (most recent call last):
 Traceback (most recent call last):   File "<string>", line 1, in <module> UnicodeEncodeError: 'cp949' codec can't encode character '\u2728' in position 0: illegal multibyte sequence   File "<string>", line 1, in <module> 
UnicodeEncodeError: 'cp949' codec can't encode character '\u2728' in position 0: illegal multibyte sequence â¨¯ 

```

# Environment data

```powershell
PS > chcp 
Active code page: 65001

PS > $PSVersionTable  
Name                           Value
 ----                           ----- 
PSVersion                      7.1.0-preview.2
 PSEdition                      Core
 GitCommitId                    7.1.0-preview.2 
OS                             Microsoft Windows 10.0.19041 
Platform                       Win32NT 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0â€¦}
 PSRemotingProtocolVersion      2.3 
SerializationVersion           1.1.0.1
 WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
This is probably related to #12240.

**Comment by hdformat** [comment]
This can be seen also `Start-Job`

```powershell
PS > 1..3 | foreach { start-job -scriptblock { python -c "print('🤡')"} }   

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
7      Job7            BackgroundJob   Running       True            localhost             python -c "print('🤡')"
9      Job9            BackgroundJob   Running       True            localhost             python -c "print('🤡')"
11     Job11           BackgroundJob   Running       True            localhost             python -c "print('🤡')"

PS > job | foreach { Receive-Job $_.id }

Traceback (most recent call last):   File "<string>", line 1, in <module> UnicodeEncodeError: 'cp949' codec can't encode character '\U0001f921' in position 0: illegal multibyte sequence Traceback (most recent call last):   File "<string>", line 1, in <module> UnicodeEncodeError: 'cp949' codec can't encode character '\U0001f921' in position 0: illegal multibyte sequence Traceback (most recent call last):   File "<string>", line 1, in <module> UnicodeEncodeError: 'cp949' codec can't encode character '\U0001f921' in position 0: illegal multibyte sequence
```

**Comment by hdformat** [comment]
This can be seen where `Start-Job`

```powershell
PS > $j = start-job -scriptblock { python -c "print('🤡')"}

PS > Receive-Job $j
Traceback (most recent call last):   
File "<string>", line 1, in <module> 
UnicodeEncodeError: 'cp949' codec can't encode character '\U0001f921' in position 0: illegal multibyte sequence
```
