### ISSUE TITLE
InvalidCastException when trying to assign object[] to SAFEARRAY(Variant)

### ISSUE THREAD

**Issue by MattKotsenas** [PowerShell/PowerShell#12672]
# Steps to reproduce

```powershell
# Step 1. Create an object array to hold our streams
[object[]]$BootOptions = @()

#Step 2. Add a COM object to the array
$BootOptions += (New-Object -ComObject IMAPI2FS.BootOptions)

# Step 3. Create another COM object who's property `BootImageOptionsArray`
# is a `SAFEARRAY(Variant)`
$Image = New-Object -ComObject IMAPI2FS.MsftFileSystemImage

# Step 4. Create a copy of the array by iterating and calling `SetValue`
$copySetValue = [array]::CreateInstance([object], $BootOptions.Count)
for ($i = 0; $i -lt $BootOptions.Count; $i++)
{
    $copySetValue.SetValue($BootOptions[$i], $i)
}

# Step 5. Create another copy of the array using indexers
$copyIndexer = [array]::CreateInstance([object], $BootOptions.Count)
for ($i = 0; $i -lt $BootOptions.Count; $i++)
{
    $copyIndexer[$i] = $BootOptions[$i]
}

# Step 6. Try to assign the array
$Image.BootImageOptionsArray = $copySetValue # works
$Image.BootImageOptionsArray = $BootOptions # throws exception
$Image.BootImageOptionsArray = $copyIndexer # throws exception
```

# Expected behavior

```none
Assignment to BootImageOptionsArray works in all three cases.

I can't explain how these three arrays are different (all appear as System.Object[] to me).
I don't believe that this issue is unique to the particular COM objects I'm using in the repro, though I can't be sure.
```

# Actual behavior

```none
Assignment works when using $copySetValue, but in the other two cases fails with the following exception:

ErrorRecord                 : Exception setting "BootImageOptionsArray": "Specified cast is not valid."
WasThrownFromThrowStatement : False
TargetSite                  : Void BasePropertySet(System.Management.Automation.PSProperty, System.Object, Boolean)
StackTrace                  :    at System.Management.Automation.Adapter.BasePropertySet(PSProperty property, Object setValue, Boolean convert)
                                 at System.Management.Automation.PSProperty.set_Value(Object value)
                                 at System.Management.Automation.Language.PSSetMemberBinder.SetAdaptedValue(Object obj, String member, Object value)
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Message                     : Exception setting "BootImageOptionsArray": "Specified cast is not valid."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.InvalidCastException: Specified cast is not valid.
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by MattKotsenas** [comment]
Any update here? Anything else I can provide to help troubleshoot this issue? Thanks!

**Comment by SeeminglyScience** [comment]
The result of `New-Object -ComObject etc` is wrapped in a `PSObject`.  These wrappers are usually invisible, but that's not always feasible. Passing an array to an interop API (like COM or .NET) is one of those scenarios.

The middle one works because if a .NET method takes `object`, the method binder will unwrap the `PSObject` before passing it to the API.

The easiest fix is to change the `$BootOptions` assignment to this:

```powershell
$BootOptions += (New-Object -ComObject IMAPI2FS.BootOptions).psobject.BaseObject
```
