### ISSUE TITLE
emoji raises System.Text.EncoderFallbackException 

### ISSUE THREAD

**Issue by hdformat** [PowerShell/PowerShell#12793]
# Steps to reproduce

1. open powershell 7.0.1 a terminal (i've tried this both of windows terminal and vs code integrated terminal)
2. typing `write-host "`
3. input an emoji via the emoji keyboard in windows 10 (`win`+`.`)
4. (seeing a strange characters instead of an emoji) tyring closing double quote `"` and enter
[
![output](https://user-images.githubusercontent.com/869339/82872134-93508200-9f6d-11ea-98b2-d5691f14efc5.gif)
](url)

# Expected behavior

```powershell
PS > write-host "😀"
😀
```

# Actual behavior

```powershell
PS ��> ��write-host�"�"��
�
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
�### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.1
OS: Microsoft Windows 10.0.19041
Last 57 Keys
"""
 w r i t e - h o s t Spacebar " 한 글 " Enter
 g e t - c Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Bac�kspace o n Tab Spacebar e m Tab Enter
 w r i t e - h o s t Spacebar " � " Enter

"""

### Exception
"""
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 12 to specified code page.
   at System.Text.EncoderE�xceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsL�ength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenS�oFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byte�Index, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayCl�ass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft�.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSC�onsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
"""

PS C:\Users\hdformat> write-host "�"
```

# Environment data

```none
PS C:\Users\hdformat> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is PSReadline issue. Please look issues in PSReadline repo - it seems there is already such issue.

**Comment by hdformat** [comment]
@iSazonov Thank you! I've found the [issue](https://github.com/PowerShell/PSReadLine/issues/949)
