### ISSUE TITLE
Install-Module Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.

### ISSUE THREAD

**Issue by dburtsev** [PowerShell/PowerShell#12952]
## Steps to reproduce

```powershell
[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebRequest]::GetSystemWebProxy()
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-Module -Name PowerShellGet -Force -Verbose -Debug -Scope AllUsers
```

## Expected behavior
Performing the operation "Install-Module" on target "Version '2.2.4.1' of module 'PowerShellGet'".
```none

```

## Actual behavior
DEBUG: 00:00:00.0000143 Trying provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0000221 Trying provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0000094 Trying provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0000123 Trying provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0051011 Attempting loading of assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0052686 Attempting loading of assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0053708 Attempting loading of assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0056743 Attempting loading of assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.1363038 Registering providers via metaproviders for assembly Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
DEBUG: 00:00:00.4200363 Initializing provider 'Bootstrap'
DEBUG: 00:00:00.4200667 Initializing provider 'WebDownloader'
DEBUG: 00:00:00.4200699 Initializing provider 'zipfile'
DEBUG: 00:00:00.4205401 Initializing provider 'NuGet'
DEBUG: 00:00:00.4428452 Provider 'WebDownloader' Initialized
DEBUG: 00:00:00.4428551 Provider 'zipfile' Initialized
DEBUG: 00:00:00.4429310 Using Archiver Provider zipfile
DEBUG: 00:00:00.4429503 Using Downloader Provider WebDownloader
DEBUG: 00:00:00.4935293 Initialize Bootstrapper
DEBUG: 00:00:00.4941908 Provider 'Bootstrap' Initialized
DEBUG: 00:00:00.4942540 Using Package Provider Bootstrap
DEBUG: 00:00:00.4958023 Trying to register metaprovider
DEBUG: 00:00:00.5078662 Initializing PowerShell MetaProvider
DEBUG: 00:00:00.5267483 Calling 'NuGet'::'InitializeProvider'.
DEBUG: 00:00:00.5268792 Provider 'NuGet' Initialized
DEBUG: 00:00:00.5269195 Using Package Provider NuGet
DEBUG: 00:00:00.5329732 Calling 'zipfile::GetFeatures'
DEBUG: 00:00:00.5332536 Calling 'WebDownloader::GetFeatures'
DEBUG: 00:00:00.5335480 Calling 'Bootstrap::GetFeatures'
DEBUG: 00:00:00.5355467 The provider 'Bootstrap' is imported
DEBUG: 00:00:00.5363063 SUCCESS provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.5364274 SUCCESS provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.5406852 Calling 'NuGet'::'GetFeatures'.
DEBUG: 00:00:00.5426725 The provider 'NuGet' is imported
DEBUG: 00:00:00.5428006 SUCCESS provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.8184429 Attempting to load PowerShell Provider Module [C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1]
DEBUG: 00:00:00.9807024 Loaded PowerShell package provider: '[C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1]'.
DEBUG: 00:00:00.9911066 Loaded PowerShell Provider: PowerShellGet
DEBUG: 00:00:00.9939187 Initializing provider 'PowerShellGet'
DEBUG: 00:00:01.0039568 Calling New() : MethodName = 'InitializeProvider'
DEBUG: 00:00:01.0040467 WarningAction: SilentlyContinue
DEBUG: 00:00:01.0040800 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.0102511 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
DEBUG: 00:00:01.0302229 In PowerShellGet Provider - 'Initialize-Provider'.
DEBUG: 00:00:01.0306527 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
DEBUG: 00:00:01.0335293 Done calling powershell «Initialize-Provider» «PSModule»
DEBUG: 00:00:01.0336307 Provider 'PowerShellGet' Initialized
DEBUG: 00:00:01.0336664 Using Package Provider PowerShellGet
DEBUG: 00:00:01.0746073 Calling New() : MethodName = 'GetFeatures'
DEBUG: 00:00:01.0746985 WarningAction: SilentlyContinue
DEBUG: 00:00:01.0747391 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.0781786 INVOKING PowerShell Fn Get-Feature with args  that has length 0
DEBUG: 00:00:01.0840484 In PowerShellGet Provider - 'Get-Feature'.
DEBUG: 00:00:01.0932127 Done calling powershell «Get-Feature» «PSModule»
DEBUG: 00:00:01.0933945 The provider 'PowerShellGet' is imported
DEBUG: 00:00:01.0953112 SUCCESS provider assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0002853 Debug: True
DEBUG: 00:00:00.0003416 Force: True
DEBUG: 00:00:00.0003802 Name: PowerShellGet
DEBUG: 00:00:00.0004159 Verbose: True
DEBUG: 00:00:00.0019474 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0152430 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0299317 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0380298 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0380811 Debug: True
DEBUG: 00:00:00.0381184 Force: True
DEBUG: 00:00:00.0381509 Name: PowerShellGet
DEBUG: 00:00:00.0381862 Verbose: True
DEBUG: 00:00:00.0392710 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0403524 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0445158 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0508339 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0508803 Debug: True
DEBUG: 00:00:00.0509156 Force: True
DEBUG: 00:00:00.0509468 Name: PowerShellGet
DEBUG: 00:00:00.0509809 Verbose: True
DEBUG: 00:00:00.0520607 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0530946 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0668509 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0731982 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0732520 Debug: True
DEBUG: 00:00:00.0732902 Force: True
DEBUG: 00:00:00.0733218 Name: PowerShellGet
DEBUG: 00:00:00.0733567 Verbose: True
DEBUG: 00:00:00.0744295 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0755159 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0823136 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.1874239 Calling SearchForPackages. Name='PowerShellGet'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:00.1979879 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:00.2110154 Calling SearchForPackages After Select 1
DEBUG: 00:00:00.2399815 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:00.2452847 Scope: AllUsers
DEBUG: 00:00:00.2483062 Force: True
DEBUG: 00:00:00.2513400 ProviderName: PowerShellGet
DEBUG: 00:00:00.2539579 Type: Module
DEBUG: 00:00:00.2571038 Name: PowerShellGet
DEBUG: 00:00:00.2626899 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.2654675 Verbose: True
DEBUG: 00:00:00.2688162 Debug: True
DEBUG: 00:00:00.2728244 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:00.3493746 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:00.4165401 OPTION: Scope => AllUsers
DEBUG: 00:00:00.4216043 OPTION: Force => True
DEBUG: 00:00:00.4241356 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:00.4266673 OPTION: Type => Module
DEBUG: 00:00:00.4291373 OPTION: Name => PowerShellGet
DEBUG: 00:00:00.4339593 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.4365661 OPTION: Verbose => True
DEBUG: 00:00:00.4394238 OPTION: Debug => True
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:00.5212279 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:00.5338506 Calling 'NuGet'::'FindPackage' - name='PowerShellGet', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:00.6444907 Iterating 'PowerShellGet'.
DEBUG: 00:00:00.6617267 Calling 'NuGetRequest'::'RegisteredPackageSources', 'C:\Users\dburtsev\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:00.6662694 Loading a configuration from file 'C:\Users\dburtsev\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:00.6701618 Loaded a configuration from file 'C:\Users\dburtsev\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:00.6743950 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:00.6772760 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.
VERBOSE: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
DEBUG: 00:00:22.4657120    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '2' more times
VERBOSE: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
DEBUG: 00:00:43.5080596    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '1' more times
VERBOSE: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
DEBUG: 00:01:04.5969726    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '0' more times
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
```none

```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```none

```

**Comment by daxian-dbw** [comment]
@alerickson Can you please take a look?

**Comment by Stephanevg** [comment]
Anything on this? I do have the same behaviour on ps5.1
