### ISSUE TITLE
Test-Connection in CoreCLR OSPS doesn't work on "Windows 10 Home"

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1303]
This is on my surface 3, which is running "Windows 10 Home":
Steps to reproduce
------------------
```
Test-Connection .
```
Expected behavior
-----------------
```
PS C:\> Test-Connection .                                                                                               
Source        Destination     IPV4Address      IPV6Address                              Bytes    Time(ms)
------        -----------     -----------      -----------                              -----    --------
DONGBO-SUF    localhost                                                                 32       0
DONGBO-SUF    localhost                                                                 32       0
DONGBO-SUF    localhost                                                                 32       0
DONGBO-SUF    localhost                                                                 32       0
```
Actual behavior
---------------
```
Test-Connection : The client cannot connect to the destination specified in the request. Verify that the
service on the destination is running and is accepting requests. Consult the logs and documentation for the
WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM
service, run the following command on the destination to analyze and configure the WinRM service: "winrm
quickconfig".
At line:1 char:1
+ Test-Connection .
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Connection], CimException
    + FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand


> $Error[0].Exception.StackTrace
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PowerShell.Commands.TestConnectionCommand.ProcessWSManProtocolForTestConnection() in C:\Users\rocky\Repos\PowerShell\src\Microsoft.PowerShell.Commands.Management\commands\management\Computer.cs:line 696
```
Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
GitCommitId                    v0.5.0-299-g75c0c3cb4d5a51232199d7320d501a6c7adeb5ec
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
CLRVersion

> Get-ComputerInfo
WindowsBuildLabEx                                       : 10586.420.amd64fre.th2_release_sec.160527-1834
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Core
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 4/1/2016 4:41:25 AM
WindowsProductId                                        : 00342-24220-07471-AAOEM
WindowsProductName                                      : Windows 10 Home
WindowsSystemRoot                                       : C:\WINDOWS
```

Please Note
----------------
`Test-Connection` works fine in CoreCLR OSPS on my dev machine, which is running "Windows 10 Enterprise" (see below), so this issue might be due to incompatibilities between OS.
```
> Test-Connection .
Source        Destination     IPV4Address      IPV6Address                              Bytes    Time(ms)
------        -----------     -----------      -----------                              -----    --------
DONGBO-DEV    localhost                                                                 32       0
DONGBO-DEV    localhost                                                                 32       0
DONGBO-DEV    localhost                                                                 32       0
DONGBO-DEV    localhost                                                                 32       0

> $PSVersionTable
Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
GitCommitId                    v0.5.0-297-g2f9be46eac39cb987edd045fb3884a1ed4ba2acf
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSVersion                      5.1.10032.0
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion

> Get-ComputerInfo 
WindowsBuildLabEx                                       : 10586.420.amd64fre.th2_release_sec.160527-1834
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Enterprise
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 1/21/2016 7:55:51 AM
WindowsProductId                                        : 00329-00000-00003-AA197
WindowsProductName                                      : Windows 10 Enterprise
WindowsRegisteredOrganization                           : Microsoft IT
WindowsRegisteredOwner                                  : Microsoft Corp.
WindowsSystemRoot                                       : C:\WINDOWS
```

**Comment by adityapatwardhan** [comment]
@PaulHigin. Could this be because on "Windows 10 Home" remoting is not enabled by default? What is the Enable-PSRemoting equivalent?

**Comment by adityapatwardhan** [comment]
@daxian-dbw On a Windows 10 Home machine on Powershell 5.1, Test-Connection uses DCOM protocol by default, hence it works fine. On Powershell 6.0, the default protocol is WSMan as DCOM is not supported. 

On Powershell 5.1, if we do Test-Connection . -Protocol WSMan, we get the same error as Powershell 6.0. If we execute 'winrm quickconfig' as suggested by the error message then Test-Connection . works as expected on both versions. 

With this, I am marking this as "By Design", please remove the label if you do not agree, otherwise close the issue.

**Comment by daxian-dbw** [comment]
Sounds good! Thanks @adityapatwardhan
