### ISSUE TITLE
out-gridview crashes on ARM64 Windows because of lack of WPF support

### ISSUE THREAD

**Issue by anaisbetts** [PowerShell/PowerShell#13119]
## Steps to reproduce

1. Install the ARM64 version of PowerShell

```powershell
ls | out-gridview
```

## Actual behavior

```none
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Management.UI.Internal.OutGridViewWindow.<>c__DisplayClass16_0.<StartWindow>b__0(Object <p0>)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Out-GridView: Exception has been thrown by the target of an invocation.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.20161
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

ARM64 .NET Framework doesn't have support for WPF. It will eventually get it as part of .NET 5, but in the meantime Powershell should make the pipeline fail rather than blowing up completely

**Comment by iSazonov** [comment]
Makes no sense to add an workaround if we expect to get fix in follow .Net 5 Preview.

**Comment by anaisbetts** [comment]
@iSazonov Will PowerShell use .NET 5 any time soon? I understood it that it'd be using the .NET Framework Proper for at least awhile, which will never get ARM64 WPF

**Comment by KalleOlaviNiemitalo** [comment]
@anaisbetts PowerShell 7.1 previews are already using .NET 5 previews.

[PowerShell 7.1.0-preview.5](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.5):

```
PS Temp:\> [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
.NET 5.0.0-preview.6.20305.6
```

[PowerShell 7.0.2](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2):

```
PS Temp:\> [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
.NET Core 3.1.5
```

**Comment by iSazonov** [comment]
@anaisbetts All PowerShell 7.1 previews are on .Net 5.0 latest preview. I see .Net team actively works on ARM support but I don't know about WPF support. You could ask in .Net Runtime repo.

I believe @SteveL-MSFT tracking such issues.
