### ISSUE TITLE
"get-service myservice | select-object *" works differently for different "myservice"

### ISSUE THREAD

**Issue by LqkUWp** [PowerShell/PowerShell#13124]
### Steps to reproduce

```powershell
Get-Service w32time | Select-Object *
```

### Expected behavior

```none
print all properties of w32time service object
```

### Actual behavior

```none
UserName            : NT AUTHORITY\LocalService
out-lineoutput: startIndex cannot be larger than length of string. (Parameter 'startIndex')
```

### Steps to reproduce

```powershell
Get-Service shpamsvc | Select-Object *
```

### Expected behavior

```none
print all properties of shpamsvc service object
```

### Actual behavior

```none
UserName            : LocalSystem
Description         : Manages profiles and accounts on a SharedPC configured device
DelayedAutoStart    : False
BinaryPathName      : C:\WINDOWS\System32\svchost.exe -k netsvcs -p
StartupType         : Disabled
Name                : shpamsvc
RequiredServices    : {RpcSs, ProfSvc}
CanPauseAndContinue : False
CanShutdown         : False
CanStop             : False
DisplayName         : Shared PC Account Manager
DependentServices   : {}
MachineName         : .
ServiceName         : shpamsvc
ServicesDependedOn  : {RpcSs, ProfSvc}
StartType           : Disabled
ServiceHandle       :
Status              : Stopped
ServiceType         : Win32ShareProcess
Site                :
Container           :
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Just as a data point: on my Windows 10.0.18363 with `en-US` as the current culture, I don't see the problem.
What is your current culture (`$PSCulture`)?

**Comment by daxian-dbw** [comment]
> out-lineoutput: startIndex cannot be larger than length of string. (Parameter 'startIndex')

Something was wrong when printing the properties of the `w32time` service object. Can you run `Get-Service w32time | Select-Object *` again, then run `Get-Error` and paster the output here?

**Comment by LqkUWp** [comment]
> Just as a data point: on my Windows 10.0.18363 with `en-US` as the current culture, I don't see the problem.
> What is your current culture (`$PSCulture`)?

```
zh-CN
```

**Comment by LqkUWp** [comment]
@daxian-dbw 

```
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type       : System.ArgumentOutOfRangeException
        Message    : startIndex cannot be larger than length of string. (Paramet
er 'startIndex')
        ParamName  : startIndex
        TargetSite :
            Name          : Substring
            DeclaringType : string
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        StackTrace :
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.Commands.Internal.Format.StringManipulationHelper.GenerateLine
sWithoutWordWrap(DisplayCells displayCells, String val, Int32 firstLineLen, Int32 followi
ngLinesLen)
   at Microsoft.PowerShell.Commands.Internal.Format.StringManipulationHelper.GenerateLine
s(DisplayCells displayCells, String val, Int32 firstLineLen, Int32 followingLinesLen)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteSingleLineHelper(Stri
ng prependString, String line, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperty(Int32 k, Str
ing propertyValue, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperties(String[] v
alues, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ListOutputContext.Pro
cessPayload(FormatEntryData fed)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessPayload(Format
EntryData fed, OutputContext c)
   at Microsoft.PowerShell.Commands.Internal.Format.FormatMessagesContextManager.Process(
Object o)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessObject(PSObjec
t so)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
   at Microsoft.PowerShell.Commands.Internal.Format.FrontEndCommandBase.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Source     : System.Private.CoreLib
        HResult    : -2146233086
    CategoryInfo          : NotSpecified: (:) [out-lineoutput], ArgumentOutOfRan
geException
    FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.PowerSh
ell.Commands.OutLineOutputCommand
    InvocationInfo        :
        MyCommand       : out-lineoutput
        HistoryId       : 1
        CommandOrigin   : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.
Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception
& exceptionThrown, ExecutionOptions options)
Message        : startIndex cannot be larger than length of string. (Parameter '
startIndex')
InnerException :
    Type       : System.ArgumentOutOfRangeException
    Message    : startIndex cannot be larger than length of string. (Parameter '
startIndex')
    ParamName  : startIndex
    TargetSite :
        Name          : Substring
        DeclaringType : string
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.Commands.Internal.Format.StringManipulationHelper.GenerateLine
sWithoutWordWrap(DisplayCells displayCells, String val, Int32 firstLineLen, Int32 followi
ngLinesLen)
   at Microsoft.PowerShell.Commands.Internal.Format.StringManipulationHelper.GenerateLine
s(DisplayCells displayCells, String val, Int32 firstLineLen, Int32 followingLinesLen)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteSingleLineHelper(Stri
ng prependString, String line, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperty(Int32 k, Str
ing propertyValue, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.ListWriter.WriteProperties(String[] v
alues, LineOutput lo)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ListOutputContext.Pro
cessPayload(FormatEntryData fed)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessPayload(Format
EntryData fed, OutputContext c)
   at Microsoft.PowerShell.Commands.Internal.Format.FormatMessagesContextManager.Process(
Object o)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessObject(PSObjec
t so)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
   at Microsoft.PowerShell.Commands.Internal.Format.FrontEndCommandBase.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.Private.CoreLib
    HResult    : -2146233086
Source         : System.Management.Automation
HResult        : -2146233087
```

**Comment by LqkUWp** [comment]
@mklement0 

```
zh-CN
```

**Comment by daxian-dbw** [comment]
@LqkUWp Thanks for sharing the error! Can you please also run the following and share the results?
```
## this may result in the same failure
Get-Service w32time | Format-List *
```
and
```
Get-Service w32time | % Description
```
Also, the windows size and buffer size when you run into this exception:
```
"Window width: $([System.Console]::WindowWidth)"
"Window height: $([System.Console]::WindowWidth)"
"Buffer width: $([System.Console]::BufferWidth)"
"Buffer width: $([System.Console]::BufferHeight)"
```

**Comment by LqkUWp** [comment]
@daxian-dbw 

* `Get-Service w32time | Format-List *`

the result is 

```
UserName            : NT AUTHORITY\LocalService
out-lineoutput: startIndex cannot be larger than length of string. (Parameter 'startIndex')
```

* `Get-Service w32time | % Description`

the result is 

···
维护在网络上的所有客户端和服务器的时间和日期同步。如果此服务被停止，时间和日期的同步将不可用。如果此服务被禁用，任何明确依赖它的服务都将不能启动。
···

* windows size and buffer size

```
~> "Window width: $([System.Console]::WindowWidth)"
~> Window width: 90
~> "Window height: $([System.Console]::WindowHeight)"
~> Window height: 27
~> "Buffer width: $([System.Console]::BufferWidth)"
~> Buffer width: 90
~> "Buffer height: $([System.Console]::BufferHeight)"
~> Buffer height: 27
```

**Comment by daxian-dbw** [comment]
Thanks @LqkUWp, we should be able to repro the issue with the provided information.
