### ISSUE TITLE
Custom cmdlet: cannot bind parameter ... expression must be writeable

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13293]
## Steps to reproduce

I've implemented a small cmdlet like this:

```csharp
    [Cmdlet(VerbsCommon.Get, "RefilAssemblyMetadata")]
    public class GetRefilAssemblyMetadataCommand : PSCmdlet
    {
        [Parameter(Mandatory = true)]
        public string[] Path { get; }

        protected override void ProcessRecord()
        {
            foreach (string path in Path)
            {
                WriteObject(MetadataAssemblyDefinition.ReadFromFile(path));
            }
        }
    }
```

And go to run it like this:

```powershell
$a = Get-RefilAssemblyMetadata -Path "$PSHOME/System.Management.Automation"
```

## Expected behavior

`$a` should be set, or my cmdlet implementation should fail if I've done something wrong.

## Actual behavior

```none
> $a = Get-RefilAssemblyMetadata -Path "$PSHOME/System.Management.Automation"
Get-RefilAssemblyMetadata: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Expression must be writeable (Parameter 'left')"
C:\Users\Robert Holt\Documents\Dev\Projects\RefIL [master ≡ +10 ~4 -2 !]
> Get-error

Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Cannot bind parameter 'Path' to the target. Exception setting "Path":
"Expression must be writeable (Parameter 'left')"
    ParameterName     : Path
    ParameterType     : string[]
    TypeSpecified     : string[]
    ErrorId           : ParameterBindingFailed
    Line              : 1
    Offset            : 38
    CommandInvocation :
        MyCommand        : Get-RefilAssemblyMetadata
        ScriptLineNumber : 1
        OffsetInLine     : 6
        HistoryId        : 6
        Line             : $a = Get-RefilAssemblyMetadata -Path
"$PSHOME/System.Management.Automation"
        PositionMessage  : At line:1 char:6
                           + $a = Get-RefilAssemblyMetadata -Path "$PSHOME/System.Management.Autom …
                           +      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Get-RefilAssemblyMetadata
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind parameter 'Path' to the target. Exception setting "Path":
"Expression must be writeable (Parameter 'left')"
            HResult : -2146233087
        CategoryInfo          : WriteError: (:) [Get-RefilAssemblyMetadata],
ParentContainsErrorRecordException
        FullyQualifiedErrorId :
ParameterBindingFailed,RefIL.PowerShell.GetRefilAssemblyMetadataCommand
        InvocationInfo        :
            MyCommand        : Get-RefilAssemblyMetadata
            ScriptLineNumber : 1
            OffsetInLine     : 38
            HistoryId        : 6
            Line             : $a = Get-RefilAssemblyMetadata -Path
"$PSHOME/System.Management.Automation"
            PositionMessage  : At line:1 char:38
                               + … et-RefilAssemblyMetadata -Path
"$PSHOME/System.Management.Automation"
                               +
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : BindParameter
        DeclaringType : System.Management.Automation.ParameterBinderBase,
System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace        :
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at
System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal
argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32
parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidat
ion(Collection`1 arguments)
   at
System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
frame)
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type           : System.Management.Automation.SetValueInvocationException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Exception setting "Path": "Expression must be writeable (Parameter 'left')"
                HResult : -2146233087
            CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : CatchFromBaseAdapterSetValue
        TargetSite     :
            Name          : BindParameter
            DeclaringType : System.Management.Automation.ReflectionParameterBinder,
System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace     :
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object
value, CompiledCommandParameter parameterMetadata)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
        Message        : Exception setting "Path": "Expression must be writeable (Parameter 'left')"
        InnerException :
            Type       : System.ArgumentException
            Message    : Expression must be writeable (Parameter 'left')
            ParamName  : left
            TargetSite :
                Name          : RequiresCanWrite
                DeclaringType : System.Linq.Expressions.Expression
                MemberType    : Method
                Module        : System.Linq.Expressions.dll
            StackTrace :
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at
System.Management.Automation.ReflectionParameterBinder.<>c__DisplayClass8_0.<GetSetter>b__0(Tuple`2
_)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object
value, CompiledCommandParameter parameterMetadata)
            Source     : System.Linq.Expressions
            HResult    : -2147024809
        Source         : System.Management.Automation
        HResult        : -2146233087
    Source            : System.Management.Automation
    HResult           : -2146233087
CategoryInfo          : WriteError: (:) [Get-RefilAssemblyMetadata], ParameterBindingException
FullyQualifiedErrorId : ParameterBindingFailed,RefIL.PowerShell.GetRefilAssemblyMetadataCommand
InvocationInfo        :
    MyCommand        : Get-RefilAssemblyMetadata
    ScriptLineNumber : 1
    OffsetInLine     : 38
    HistoryId        : 6
    Line             : $a = Get-RefilAssemblyMetadata -Path "$PSHOME/System.Management.Automation"
    PositionMessage  : At line:1 char:38
                       + … et-RefilAssemblyMetadata -Path "$PSHOME/System.Management.Automation"
                       +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

## Environment data

This is using the following PowerShell version:

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

And compiling against Microsoft.PowerShell.SDK version 7.1.0-preview.5.

**Comment by vexx32** [comment]
Isn't that expected? I was under the expression parameters always needed to have both getters and setters.

**Comment by rjmholt** [comment]
Oh wow, now I see that it's missing the setter.

Hmmm, I would love to have a better error message for that

**Comment by vexx32** [comment]
Yeah it would be good to maybe catch this error in the parameter binder specifically and issue a more direct error message to avoid confusion.
