### ISSUE TITLE
Invoke-Webrequest The response ended prematurely. with unencrypted credentials to localhost

### ISSUE THREAD

**Issue by Willem-J-an** [PowerShell/PowerShell#13471]
Running into this issue on 9 out of 10 requests to localhost python API. At first I thought the issue was in the API, but the issue does not occur in Powershell 5.1, or when using postman. Powershell 7 does not allow to send credentials for basic authentication in plaintext when the api is running on localhost without https, without -AllowUnencryptedAuthentication, but when I add it, this issue occurs. The issue does not occur when I disable the authentication requirement on the API. The API simply denies the request as unauthenticated 401.
## Steps to reproduce

```powershell
invoke-webrequest `
  -uri http://127.0.0.1:5000/predict `
  -method post `
  -Credential $Cred 
  -body '{"test":"stuff"}' 
  -AllowUnencryptedAuthentication `
  -ContentType application/json
```

## Expected behavior
Successful request.
```
StatusCode        : 200
StatusDescription : OK
Content           : {"HI": [{"Running": true}]}

```

## Actual behavior

```none
Invoke-WebRequest: The response ended prematurely.
$error[1].exception

TargetSite     : Void MoveNext()
StackTrace     :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
                    at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean
                 isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean
                 doRequestAuth, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken
                 cancellationToken)
                    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean
                 preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
                    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean
                 disposeCts)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Message        : An error occurred while sending the request.
Data           : {}
InnerException : System.IO.IOException: The response ended prematurely.
                    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
HelpLink       :
Source         : System.Net.Http
HResult        : -2146232800
```

## Environment data

```none

```

**Comment by iSazonov** [comment]
I guess you need to add `-Authentication Basic`.

**Comment by haidouks** [comment]
I ran into this issue after upgrading  powershell docker base image from 7.0.0 alpine 3.10 to 7.0.3 alpine 3.10.

```
WARNING: 20200828155430291 routes/pcf/stats __
class ErrorRecord
{
  PSMessageDetails =
  Exception =
    class HttpRequestException
    {
      TargetSite = Void MoveNext()
      StackTrace =    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task"1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1349
         at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1506
      Message = An error occurred while sending the request.
      Data =
        [
        ]

      InnerException = System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
      HelpLink =
      Source = System.Net.Http
      HResult = -2146232800
    }
  TargetObject =
    class HttpRequestMessage
    {
      Version = 1.1
      Content = System.Net.Http.StringContent
      Method = GET
      RequestUri = https://*****************
      Headers =
        [
          [User-Agent, System.String[]]
          [Connection, System.String[]]
        ]

      Properties =
        [
        ]

    }
  CategoryInfo =
    class ErrorCategoryInfo
    {
      Category = InvalidOperation
      Activity = Invoke-RestMethod
      Reason = HttpRequestException
      TargetName = Method: GET, RequestUri: 'https://*****************', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
      {
        User-Agent: Mozilla/5.0
        User-Agent: (Linux; Linux 4.4.0-138-generic #164~14.04.1-Ubuntu SMP Fri Oct 5 08:56:16 UTC 2018; en-US)
        User-Agent: PowerShell/7.0.3
        Connection: Close
        Content-Length: 0
      }
      TargetType = HttpRequestMessage
    }
  FullyQualifiedErrorId = WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
  ErrorDetails =
    class ErrorDetails
    {
      Message = The response ended prematurely.
      RecommendedAction =
    }
  InvocationInfo =
    class InvocationInfo
    {
      MyCommand = Invoke-RestMethod
      BoundParameters =
        [
        ]

      UnboundArguments =
        [
        ]

      ScriptLineNumber = 64
      OffsetInLine = 17
      HistoryId = 1
      ScriptName = /usr/src/app/routes/pcf/stats.ps1
      Line =         $null = Invoke-RestMethod -Uri "$appMetricsBaseURI/apps/$($app.guid)" -webSession $uaa -SkipCertificateCheck -DisableKeepAlive -RetryIntervalSec 2 -MaximumRetryCount 3 -TimeoutSec 60

      PositionMessage = At /usr/src/app/routes/pcf/stats.ps1:64 char:17
      + …     $null = Invoke-RestMethod -Uri "$appMetricsBaseURI/apps/$($app.gu …
      +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      PSScriptRoot = /usr/src/app/routes/pcf
      PSCommandPath = /usr/src/app/routes/pcf/stats.ps1
      InvocationName = Invoke-RestMethod
      PipelineLength = 0
      PipelinePosition = 0
      ExpectingInput = False
      CommandOrigin = Internal
      DisplayScriptPosition =
    }
  ScriptStackTrace = at <ScriptBlock>, /usr/src/app/routes/pcf/stats.ps1: line 64
  at Invoke-PodeScriptBlock, /root/.local/share/powershell/Modules/Pode/1.8.0/Public/Utilities.ps1: line 664
  at <ScriptBlock>, <No file>: line 71
  PipelineIterationInfo =
    [
    ]

}



Date: 2020-08-28 15:54:30
Level: Error
ThreadId: 9
Server:
Category: InvalidData: (:) [Invoke-PodeScriptBlock], ParameterBindingValidationException
Message: Cannot bind argument to parameter 'Value' because it is null.
StackTrace: at <ScriptBlock>, /usr/src/app/routes/pcf/stats.ps1: line 104
at Invoke-PodeScriptBlock, /root/.local/share/powershell/Modules/Pode/1.8.0/Public/Utilities.ps1: line 664
at <ScriptBlock>, <No file>: line 71

Date: 2020-08-28 15:54:30
Level: Error
ThreadId: 9
Server:
Category: System.Management.Automation
Message: Cannot bind argument to parameter 'Value' because it is null.
StackTrace:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) in /PowerShell/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:line 1644
   at Invoke-PodeScriptBlock(Closure , FunctionContext )
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in /PowerShell/src/System.Management.Automation/engine/interpreter/LightLambda.Generated.cs:line 74
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action"1 clause, Object dollarUnderbar, Object inputToProcess) in /PowerShell/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs:line 2335
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing() in /PowerShell/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs:line 2272
   at System.Management.Automation.CommandProcessorBase.Complete() in /PowerShell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 590

```
