### ISSUE TITLE
Duplicate using namespace statements cause all type refs to throw AmbigiousTypeReference

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#13525]
## Steps to reproduce

```powershell
using namespace System.Text
using namespace System.Text

[StringBuilder]
```

## Expected behavior

Either ignore the second `using namespace` or throw parse error

## Actual behavior

```none
InvalidArgument:
Line |
   5 |  [StringBuilder]
     |  ~~~~~~~~~~~~~~~
     | Type name 'StringBuilder' is ambiguous, it could be 'System.Text.StringBuilder' or 'System.Text.StringBuilder'.
```

^ is thrown at runtime.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Notes

<details>

<summary>Full Get-Error output (click to expand)</summary>

```raw
Exception             :
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Type name 'StringBuilder' is ambiguous, it could be 'System.Text.StringBuilder' or 'System.Text.StringBuilder'.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AmbiguousTypeReference
        InvocationInfo        :
            ScriptLineNumber : 5
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : [StringBuilder]
            PositionMessage  : At line:5 char:1
                               + [StringBuilder]
                               + ~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
    Message        : Type name 'StringBuilder' is ambiguous, it could be 'System.Text.StringBuilder' or 'System.Text.StringBuilder'.
    InnerException :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Type name 'StringBuilder' is ambiguous, it could be 'System.Text.StringBuilder' or 'System.Text.StringBuilder'.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : AmbiguousTypeReference
            InvocationInfo        :
                ScriptLineNumber : 5
                OffsetInLine     : 1
                HistoryId        : -1
                Line             : [StringBuilder]
                PositionMessage  : At line:5 char:1
                                   + [StringBuilder]
                                   + ~~~~~~~~~~~~~~~
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
        TargetSite     :
            Name          : ResolveTypeName
            DeclaringType : System.Management.Automation.TypeOps, System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace     :
   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
        Message        : Type name 'StringBuilder' is ambiguous, it could be 'System.Text.StringBuilder' or 'System.Text.StringBuilder'.
        Data           : System.Collections.ListDictionaryInternal
        InnerException :
            Type       : System.Management.Automation.Language.TypeResolver+AmbiguousTypeException
            Candidates :
                Length : 25

                Length : 25
            TypeName   : StringBuilder
            Message    : Specified cast is not valid.
            HResult    : -2147467262
        Source         : System.Management.Automation
        HResult        : -2147467262
    HResult        : -2146233087
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : AmbiguousTypeReference
InvocationInfo        :
    ScriptLineNumber : 5
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [StringBuilder]
    PositionMessage  : At line:5 char:1
                       + [StringBuilder]
                       + ~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
```

</details>

Side note, I found this because I had duplicated `using namespace System` in a script I dot sourced.  `System` is a real bad one to do that with since it breaks concise view *for the rest of the session*.  Took me awhile to figure out what was happening, thought I broke `Out-Default` somehow.  Might be a good idea to use the fully qualified name for `Environment` in concise view (/cc @SteveL-MSFT).

**Comment by echalone** [comment]
I found this behaviour to be consistent with Powershell 5.1, but would still argue for fixing it

**Comment by JustinGrote** [comment]
+1 to fix, took me a bit to figure out what was happening for me today.

**Comment by JustinGrote** [comment]
@SeeminglyScience @SteveL-MSFT can you flag this as keep-open, thanks.
