### ISSUE TITLE
PowerShell 7.1 preview Invoke-RestMethod / Invoke-WebRequest fail: "The token that was passed is invalid."

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#13611]
## Steps to reproduce

This probably affects different APIs, but I only encountered it with our local instance of a product called [ScriptRunner](https://www.scriptrunner.com/en/) so I apologize if this is hard to reproduce, I will try my best though to provide additional data whenever needed.

ScriptRunner provides a Web UI and delegation capabilities to run PowerShell scripts, but you can also invoke scripts via a Web API that is documented here: https://kb.scriptrunner.com/connectors/use-web-service-connector

This web API call fails in PowerShell 7.1.0-preview.7, but works in PowerShell 7.0.3 and Windows PowerShell 5.1.19041.1.

Assuming there is an Action/Script defined in ScriptRunner that is called "LAPS Health Check" with a Parameter "EmailTo" an example API call would be:

```powershell
$Params = @{
    'Method' = 'Post'
    'UseDefaultCredentials' = $true
    'ContentType' = 'application/json; charset=utf-8'
}

Invoke-RestMethod -Uri "https://SCRIPTRUNNERSERVER:8091/ScriptRunner/ActionContextItem/StartASRNamedAction" @Params -Body @'
{
    "Options": [
        "",
        "A reason or tag for the script execution."
    ],
    "ActionName": "LAPS Health Check",
    "ParamNames": [
        "EmailTo"
    ],
    "ParamValues": [
        "myemail@mydomain.tld"
    ],
    "RunFlags": [
        2,
        0
    ]
}
'@

```

## Expected behavior

```none
A JSON object with data about the running job is returned.
```

## Actual behavior

Invoke-WebRequest and Invoke-RestMethod both fail with:

```none
Invoke-RestMethod : Das Token, das der Funktion übergeben wurde, ist ungültig.
```

Again, I am terribly sorry for the localized german error messages but that is a catastrophe that Microsoft brought upon themselves, it was not my idea. It translates to: "The token that was passed to the function is invalid." The detailed error data is:

```none
PSMessageDetails      :
Exception             : System.ComponentModel.Win32Exception (0x80090308): Das Token, das der Funktion übergeben wurde, ist ungültig.
                           at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
                           at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
                           at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean
                        isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
                           at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                           at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean
                        preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
                           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                           at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean
                        buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Since this is a regression affecting only PowerShell 7.1 preview builds, I hope we can get it fixed before 7.1 hits a stable release

Thanks, and once again since I know ScriptRunner is a paid software this isn't that comfy to reproduce - I'll gladly provide more data where possible, though some of it would possibly need to be redacted as this software is used at my workplace.

**Comment by iSazonov** [comment]
Please check with latest 7.1.0-preview.8.

**Comment by jantari** [comment]
There is no preview 8 yet: https://github.com/PowerShell/PowerShell/releases

I am using the latest version publicly available.

**Comment by iSazonov** [comment]
You can load daily build from main page.

**Comment by iSazonov** [comment]
It is dup #13609

**Comment by jantari** [comment]
True, it is. Will subscribe there, thanks.
