### ISSUE TITLE
PowerShell Core crashing on RHEL/CentOS when using Azure Serial Console

### ISSUE THREAD

**Issue by hbouzieh** [PowerShell/PowerShell#13853]
## Steps to reproduce

•	Install PowerShell Core on an Azure RedHat 7 Virtual Machine. (able to repro on different versions of rhel/CentOS)
•	Login to the guest OS from Azure Serial Console.
•	Type “pwsh” to start a PowerShell session, and press enter.
•	Type in any letter, then the PowerShell session will crash with the below error: 
o	Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')

---------------------------------------------------------
## Expected behavior

•	To be able to able to use PowerShell from Azure Serial Console with no issues. 
 
---------------------------------------------------------

## Actual behavior

•	We are able to use the PowerShell Module through “Putty, Luminate, etc.. ” with no issues.
•	However, Over the Serial Console, when trying to use the PowerShell Module, it crashes with the below error: 
o	Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
•	No other modules are facing any issues while using the Serial console, on the PowerShell. 
•	The behavior was reproduced using the latest PowerShell Module version: “7.0.3”, and also using the latest Preview version: “7.1.0-rc.1”. 
•	So far we could reproduce the same behavior only on RHEL and CentOS images. As the PowerShell works fine over the serial console on other distros such as Ubuntu. 
•	If we look at the complete error we are getting, we can see that PowerShell Module was to query the cursor position, and getting “-1” from the terminal session. 

---------------------------------------------------------

## Full Error: 
Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter
'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 't
op')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfL
ine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Bo
olean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String
configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)

---------------------------------------------------------

## Environment data

Name                           		Value
----                           		-----
PSVersion                     		7.0.3
PSEdition                     		Core
GitCommitId                    		7.0.3
OS                             		Linux 3.10.0-1062.31.2.el7.x86_64 #1 SMP Tue Ju…
Platform                       		Unix
PSCompatibleVersions           	{1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      	2.3
SerializationVersion           	1.1.0.1
WSManStackVersion              	3.0

**Comment by iSazonov** [comment]
@DHowett Have you any thoughts about the issue? Does System.Console API work correctly in the console?

**Comment by DHowett** [comment]
This looks like the same root cause as https://github.com/PowerShell/PSReadLine/issues/1376 but happening somewhere else in the stack. `System.Console` cannot handle terminals on Linux/Mac that do not respond to a cursor position report request.

**Comment by DHowett** [comment]
This is just one victim of a leaky abstraction, where `System.Console` was made to model the Win32 console API and then "ported" to non-Windows. Cursor reporting is not guaranteed, but the `System.Console` port requires it.

**Comment by iSazonov** [comment]
@DHowett Thanks!

/cc @daxian-dbw @SteveL-MSFT for information.

**Comment by SteveL-MSFT** [comment]
Looks like we need to check if cursorLeft is <= 0 and handle that accordingly

**Comment by iSazonov** [comment]
Perhaps we could use a code from PSReadline.

**Comment by adityapatwardhan** [comment]
Checked the repo on Ubuntu 18 and RHEL 7. The difference between console settings is that on RHEL 7, the Console.BufferWidth is set to 0, where are on Ubuntu 18 it is set as 80. Next step is to create a small .NET app to create a repro.

**Comment by hbouzieh** [comment]
@adityapatwardhan, thanks for the update, really important findings. 
Is there any way we can adjust the Console.BufferWidth on RHEL manually as a temp workaround ?

**Comment by iSazonov** [comment]
@hbouzieh You could try to set TERM = vt100.

**Comment by JBalhatchet** [comment]
This is still an issue
