### ISSUE TITLE
Failure to launch PowerShell in some locales

### ISSUE THREAD

**Issue by BillyONeal** [PowerShell/PowerShell#13859]
Hi there folks! We are experiencing a failure that seems to occur only in some locales on PowerShell 7.0.3, but we have similar failures at least as far back as PowerShell 5.1.

Effectively, something blows up while PowerShell is starting (in `AppDomain.Setup`) which tries to throw an exception, which needs an `AppDomain` for the exception type, which fails again, etc.

We aren't sure if this is actually a PowerShell bug or something that might be .NET or .NET Core's fault, but we know it isn't getting to our script, that it only occurs in some locales, and none of us have been able to repro the problem ourselves. Has anyone on the PowerShell team seen similar call stacks and/or do you all have further troubleshooting ideas?

Thanks!

See https://github.com/microsoft/vcpkg/issues/12849

```
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: Arg_AccessViolationException

at System.Environment.FailFast(System.String)
at System.SR.InternalGetResourceString(System.String)
at System.SR.GetResourceString(System.String, System.String)
at System.AccessViolationException..ctor()
at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
at System.Globalization.CultureData.InitCultureData()
at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
at System.Globalization.CultureInfo..ctor(System.String, Boolean)
at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
at System.Globalization.CultureInfo.GetCultureInfo(System.String)
at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
at System.Resources.ResourceManager.CommonAssemblyInit()
at System.Resources.ResourceManager..ctor(System.Type)
at System.SR.InternalGetResourceString(System.String)
at System.SR.GetResourceString(System.String, System.String)
at System.AccessViolationException..ctor()
at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
at System.String.Equals(System.String, System.String)
at System.AppDomain.Setup(System.Object)
FailFast:
Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: Arg_AccessViolationException

at System.Environment.FailFast(System.String)
at System.SR.InternalGetResourceString(System.String)
at System.SR.GetResourceString(System.String, System.String)
at System.AccessViolationException..ctor()
at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)
at System.Globalization.CultureData.InitCultureData()
at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
at System.Globalization.CultureInfo..ctor(System.String, Boolean)
at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
at System.Globalization.CultureInfo.GetCultureInfo(System.String)
at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
at System.Resources.ResourceManager.CommonAssemblyInit()
at System.Resources.ResourceManager..ctor(System.Type)
at System.SR.InternalGetResourceString(System.String)
at System.SR.GetResourceString(System.String, System.String)
at System.AccessViolationException..ctor()
at System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UInt32)
at System.String.Equals(System.String, System.String)
at System.AppDomain.Setup(System.Object)
```

**Comment by iSazonov** [comment]
> at System.AppDomain.Setup(System.Object)

The API presents only .Net Framework so the callstack comes from **Windows PowerShell**. The repository is only for developing of PowerShell Core. I suggest to continue a discussion in https://github.com/microsoft/vcpkg/issues/12849. If the problem is really with Windows PowerShell @BillyONeal you could communicate with MSFT PowerShell team internally.

**Comment by BillyONeal** [comment]
Interesting, we attempt to make sure powershell core is used rather than powershell from the system but apparently something somewhere isn't cooperating. Sorry for bothering you :)

**Comment by iSazonov** [comment]
I set `Resolution-External` until we get a confirmation that the issue can be reproduced on latest PowerShell 7.1 build.

**Comment by BillyONeal** [comment]
@iSazonov Sounds good, thanks!
