### ISSUE TITLE
Setting `MergeUnclaimedPreviousCommandResults` without `MergeMyResults` throws ScriptCallDepthException

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#14351]
## Steps to reproduce

```powershell
using namespace System.Management.Automation.Runspaces

$ps = $res = $null
try {
    $ps = [powershell]::Create()
    $null = $ps.AddScript("Write-Error 'test'")
    $cmd = [Command]::new(
        'process { Write-Error -ErrorRecord $_ }',
        <# isScript: #> $true)

    # Works if you uncomment this.
    # $cmd.MergeMyResults('All', 'Output')

    $cmd.MergeUnclaimedPreviousCommandResults = 'Error, Output'
    $null = $ps.Commands.AddCommand($cmd)
    $res = $ps.Invoke()
} finally {
    ($ps)?.Dispose()
}

$res
```

## Expected behavior

No output, and does not throw ScriptCallDepthException.

## Actual behavior

After ~10 minutes it throws ScriptCallDepthException.

```python
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Invoke" with "0" argument(s): "The script failed due to call depth overflow."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ScriptCallDepthException
        InvocationInfo        :
            ScriptLineNumber : 9
            OffsetInLine     : 5
            HistoryId        : -1
            Line             :     $res = $ps.Invoke()

            PositionMessage  : At line:9 char:5
                               +     $res = $ps.Invoke()
                               +     ~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 9
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.1.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Exception calling "Invoke" with "0" argument(s): "The script failed due to call depth overflow."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type        : System.Management.Automation.ScriptCallDepthException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The script failed due to call depth overflow.
                HResult : -2146233087
            CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : CallDepthOverflow
        TargetSite  :
            Name          : Invoke
            DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.1.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output,
PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output,
PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings
settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at CallSite.Target(Closure , CallSite , Object )
        Message     : The script failed due to call depth overflow.
        Source      : System.Management.Automation
        HResult     : -2146233087
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ScriptCallDepthException
InvocationInfo        :
    ScriptLineNumber : 9
    OffsetInLine     : 5
    HistoryId        : -1
    Line             :     $res = $ps.Invoke()

    PositionMessage  : At line:9 char:5
                       +     $res = $ps.Invoke()
                       +     ~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 9
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Notes

Credit to @jborean93 for finding this one. Seems like the error pipe is being set to the same pipe as input.

**Comment by jborean93** [comment]
Also would be great to expand the docs on `MergeUnclaimedPreviousCommandResults` could be expanded as well, not very intuitive when trying to understand what it does exactly.

**Comment by JamesWTruher** [comment]
i think this boils down to an error in the declaration of the enum. It's marked with flags, but there are no values associated with the enum members, so they're just sequential values.

**Comment by jborean93** [comment]
The enum is a weird one. It looks like it was originally written for PowerShell v2 where you could only redirect the error or output pipe so having a flag to indicate `Error | Output` made sense in some situations. When the other streams were added they were added as an enum like value and the methods were updated to treat them as such. There’s a few instances where I found this enum type being used in different ways and it’s ultimately typically because the methods were designed for different PowerShell versions.

**Comment by SeeminglyScience** [comment]
> i think this boils down to an error in the declaration of the enum. It's marked with flags, but there are no values associated with the enum members, so they're just sequential values.

That's definitely a problem, though I don't think it's related to this bug.  `Output` and `Error` are low enough to work like bit flags as long as that's all you use, and that API throws if you pass it anything other than `None` or `Output | Error` anyway.

It's functionally a `bool` property that some folks presumably meant to expand at some point.  Makes me wonder if they gave up on that once they noticed they declared the enum wrong 🤷
