### ISSUE TITLE
Question Request

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#14678]
## Summary of the new feature/enhancement

Test-Connection cmdlet in linux works only when pwsh is elevated by sudo 
It would be better to use Test-Connection as ordinary user. Like /usr/bin/ping, for example.

**Comment by daxian-dbw** [comment]
I cannot repro this on Ubuntu 18.04, where I'm able to run `Test-Connect` as a regular user:
```
PS:44> whoami
daxian
PS:45> Test-Connection www.bing.com

   Destination: www.bing.com

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 dongbo-pro7      204.79.197.200                  3         32 Success
   2 dongbo-pro7      204.79.197.200                  3         32 Success
   3 dongbo-pro7      204.79.197.200                  3         32 Success
   4 dongbo-pro7      204.79.197.200                  3         32 Success
```

**Comment by 237dmitry** [comment]
I have been trying pwsh snap. The same result:

```
────────────────────────────────────────────────────────────────────────────[~]─[0]─[123]─[00:00.008]─[114,34]
 > uname -r                      
5.10.9-169.current
────────────────────────────────────────────────────────────────────────────[~]─[0]─[124]─[00:00.008]─[114,34]
 > lsb_release -a                
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	4.1
Codename:	fortitude
────────────────────────────────────────────────────────────────────────────[~]─[0]─[125]─[00:00.018]─[114,34]
 > $Env:USER                     
herz
────────────────────────────────────────────────────────────────────────────[~]─[0]─[126]─[00:00.003]─[114,34]
 > Test-Connection bing.com
Test-Connection: Testing connection to computer 'bing.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'bing.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'bing.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'bing.com' failed: An exception occurred during a Ping request.
────────────────────────────────────────────────────────────────────────────[~]─[0]─[127]─[00:00.056]─[114,34]
 > pwsh-root                     
Password:     
───────────────────────────────────────────────────────────────────[/home/herz]─[0]─[001]─[00:00.177]─[114,34]
 > $Env:USER                     
root
───────────────────────────────────────────────────────────────────[/home/herz]─[0]─[002]─[00:00.006]─[114,34]
 > Test-Connection bing.com      

   Destination: bing.com

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 mymsi            2620:1ec:c11::200              83         32 Success
   2 mymsi            2620:1ec:c11::200              50         32 Success
   3 mymsi            2620:1ec:c11::200              50         32 Success
   4 mymsi            2620:1ec:c11::200              49         32 Success

───────────────────────────────────────────────────────────────────[/home/herz]─[0]─[003]─[00:03.301]─[114,34]
 > exit                    
────────────────────────────────────────────────────────────────────────────[~]─[0]─[128]─[00:34.583]─[114,34]
 >    


```
PS. `pwsh-root` is the script for user's environment after `sudo`

**Comment by 237dmitry** [comment]
Get-Error output:

```
 > Get-Error

Exception             : 
    Type           : System.Net.NetworkInformation.PingException
    Message        : Testing connection to computer 'bing.com' failed: An exception occurred during a Ping request.
    InnerException : 
        Type       : System.Net.NetworkInformation.PingException
        TargetSite : 
            Name          : MoveNext
            DeclaringType : System.Net.NetworkInformation.Ping+<SendWithPingUtilityAsync>d__76, System.Net.Ping, Version=5.0.0.0, Cu
lture=neutral, PublicKeyToken=b03f5f7f11d50a3a
            MemberType    : Method
            Module        : System.Net.Ping.dll
        StackTrace : 
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
        Message    : An exception occurred during a Ping request.
        Source     : System.Net.Ping
        HResult    : -2146233079
    HResult        : -2146233079
TargetObject          : bing.com
CategoryInfo          : ResourceUnavailable: (bing.com:String) [Test-Connection], PingException
FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand
InvocationInfo        : 
    MyCommand        : Test-Connection
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 127
    Line             : Test-Connection bing.com
    PositionMessage  : At line:1 char:1
                       + Test-Connection bing.com
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Test-Connection
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : 

```

**Comment by 237dmitry** [comment]
I'm solved the problem. By setting suid bit for pwsh.

```
sudo chmod 4755 /opt/microsoft/powershell/7/pwsh
```
