### ISSUE TITLE
Test-Connection is related to /usr/bin/ping?

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#14966]
`is depends on`  Can't change.

`Test-Connection` does not work at all if in linux distribution `/usr/bin/ping` or `/bin/ping` has suid.

## Steps to reproduce

```powershell

stat -c %a /usr/bin/ping    # test stat of ping
Test-Connection localhost   # Status is Timeout
ping -c 4 localhost         # Fine
```

## Expected behavior

Working `Test-Connection`

## Actual behavior

```none
 > Test-Connection localhost

   Destination: localhost

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 mymsi            *                               *          * TimedOut
   2 mymsi            *                               *          * TimedOut
   3 mymsi            *                               *          * TimedOut
   4 mymsi            *                               *          * TimedOut


 > Test-Connection google.com         
Test-Connection: Testing connection to computer 'google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'google.com' failed: An exception occurred during a Ping request.
Test-Connection: Testing connection to computer 'google.com' failed: An exception occurred during a Ping request.

 > Get-Error   

Exception             : 
    Type           : System.Net.NetworkInformation.PingException
    Message        : Testing connection to computer 'google.com' failed: An exception occurred during a Ping request.
    InnerException : 
        Type       : System.Net.NetworkInformation.PingException
        TargetSite : 
            Name          : MoveNext
            DeclaringType : System.Net.NetworkInformation.Ping+<SendWithPingUtilityAsync>d__76, System.Net.Ping, Version=5.0.0.0, Culture=neutral, PublicKeyToke
n=b03f5f7f11d50a3a
            MemberType    : Method
            Module        : System.Net.Ping.dll
        StackTrace : 
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
        Message    : An exception occurred during a Ping request.
        Source     : System.Net.Ping
        HResult    : -2146233079
    HResult        : -2146233079
TargetObject          : google.com
CategoryInfo          : ResourceUnavailable: (google.com:String) [Test-Connection], PingException
FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand
InvocationInfo        : 
    MyCommand        : Test-Connection
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 49
    Line             : Test-Connection google.com
    PositionMessage  : At line:1 char:1
                       + Test-Connection google.com
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Test-Connection
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : 


```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Linux 5.10.15-172.current #1 SMP PREEMPT Fri Feb 12 16:35:57 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


# Any Linux distribution there `*bin/ping` has suid (4755)

```
![ping](https://user-images.githubusercontent.com/78153320/110301033-ab7b2480-8008-11eb-91d7-4758273dd235.png)

**Comment by vexx32** [comment]
Test-Connection utilizes the .NET class `System.NetNetworkInformation.Ping` to send requests.

If .NET has a dependency on the builtin `ping` utility, there's not really a way for us to avoid that.

**Comment by mklement0** [comment]
Good point, @vexx32; specifically, it looks for the `ping` / `ping6` utilities in the following folders, in order: `/bin/`, `/sbin/`, `/usr/bin/`


https://github.com/dotnet/runtime/blob/9a70e7a68889f4c593479f4c20495a7f8c4528e8/src/libraries/Common/src/System/Net/NetworkInformation/UnixCommandLinePing.cs#L13-L33

**Comment by vexx32** [comment]
That makes a lot of sense as to why pings on Unix are so tricky to work with. Sigh. Would have been a lot more usable in a number of respects if they'd written a proper ping util into .NET instead of trying to reuse an on-box utility like that. 😔

**Comment by 237dmitry** [comment]
> Test-Connection utilizes the .NET class System.NetNetworkInformation.Ping to send requests.

Is this really true? I don't know how else I would have known about it... My question is WHY the Test-Connection not working in such environment?

Here are my observations:
```
> sudo chmod 775 /usr/bin/ping            # not pinging
> sudo chmod 4755 /opt/powershell/7/pwsh  # Test-Connection working. But in this case there are errors in other different tasks.
```
If I run elevated pwsh then Test-Connection is working. I can certainly use native ping, but I would like to use the capabilities of pwsh.

**Comment by mklement0** [comment]
@237dmitry, does the symptom only occur when the `System.NetNetworkInformation.Ping` class is used _by `Test-Connection`_, from PowerShell?

If not, you should raise the issue at https://github.com/dotnet/runtime/issues

**Comment by 237dmitry** [comment]
> does the symptom only occur when the `System.NetNetworkInformation.Ping` class is used _by `Test-Connection`_, from PowerShell?

It's a double impression, maybe I'm doing something wrong. But the ip address is pinged, I get a Success response. But if I ping the hostname I get errors:

```
> using assembly /opt/microsoft/powershell/7/System.Net.Ping.dll
> $ping = [System.Net.NetworkInformation.Ping]::new()
> $ping.Send('google.com') 
MethodInvocationException: Exception calling "Send" with "1" argument(s): "An exception occurred during a Ping request."

> $ping.Send("8.8.8.8")   

Status        : Success
Address       : 8.8.8.8
RoundtripTime : 19
Options       : 
Buffer        : {}

 > $options = [System.Net.NetworkInformation.PingOptions]::new()
 > $options.DontFragment = $true                                
 > $ping.Send('google.com',255,255,$options)
MethodInvocationException: Exception calling "Send" with "4" argument(s): "An exception occurred during a Ping request."

```

**Comment by 237dmitry** [comment]
Via sudo:
```
> sudo pwsh
......
 > $env:USER
root

 > using assembly /opt/microsoft/powershell/7/System.Net.Ping.dll  
 > $ping = [System.Net.NetworkInformation.Ping]::new()
 > $ping.Send('google.com')

Status        : TimedOut
Address       : 0.0.0.0
RoundtripTime : 0
Options       : 
Buffer        : {}

 > $ping.Send('https://google.com')
MethodInvocationException: Exception calling "Send" with "1" argument(s): "An exception occurred during a Ping request."

 > $ping.Send("google.com")        

Status        : TimedOut
Address       : 0.0.0.0
RoundtripTime : 0
Options       : 
Buffer        : {}

 > $options = [System.Net.NetworkInformation.PingOptions]::new()
 > $options.DontFragment = $true
 > $ping.Send('google.com',255,255,$options)

Status        : TimedOut
Address       : 0.0.0.0
RoundtripTime : 0
Options       : 
Buffer        : {}

# Test-Connection from sudo not working.... I'am shoked
 > Test-Connection 'google.com'

   Destination: google.com

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 mymsi            *                               *          * TimedOut
   2 mymsi            *                               *          * TimedOut
   3 mymsi            *                               *          * TimedOut
   4 mymsi            *                               *          * TimedOut

```

**Comment by 237dmitry** [comment]
PS. Iam tryed with linux. One not working, another, the fifth, the tenth and so on. Liked distribution, not working Test-Connection, working Test-Connection, unliked distribution. Horror. I suspect that it is necessary to use only what is officially supported

I close this issue. This was the second attempt.
