### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by stwolfe** [PowerShell/PowerShell#15040]
I have a C# application that instantiates a remote powershell and invokes some small scripts on over the remote connection.  All of this work great when I am referencing a shared instance of .NET 5.   But when I run that application when it is published standalone, I get a missing dll issue.

```
PS > aseutil tiering egressperf 

One or more errors occurred. (Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.)

Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

   at System.Management.Automation.CimClassDeserializationCache`1..ctor()
   at System.Management.Automation.DeserializationContext..ctor(DeserializationOptions options, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.Fragmentor..ctor(Int32 fragmentSize, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.BaseTransportManager..ctor(PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager..ctor(Guid runspaceId, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.Client.BaseClientSessionTransportManager..ctor(Guid runspaceId, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager..ctor(Guid runspacePoolInstanceId, WSManConnectionInfo connectionInfo, PSRemotingCryptoHelper cryptoHelper, String sessionName)
   at System.Management.Automation.Runspaces.WSManConnectionInfo.CreateClientSessionTransportManager(Guid instanceId, String sessionName, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl..ctor(ClientRemoteSession session, PSRemotingCryptoHelper cryptoHelper, RunspaceConnectionInfo connectionInfo, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspacePoolInternal rsPool, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreateClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDSHandler(TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.RemoteRunspace..ctor(TypeTable typeTable, RunspaceConnectionInfo connectionInfo, PSHost host, PSPrimitiveDictionary applicationArguments, String name, Int32 id)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable, PSPrimitiveDictionary applicationArguments, String name)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host, RunspaceConnectionInfo connectionInfo)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo)
   at Utility.Windows.Management.Automation.RemoteSession.OpenRunspace(Boolean ssh) in C:\Repos\EdgeOne.Developer\Developer\stwolfe\src\Libraries\Utility\Management\Automation\RemoteSession.cs:line 122
   at Utility.Windows.Management.Automation.RemoteSession.InvokeScript(String script, IDictionary`2 args, CancellationToken cancelToken, String callerName) in C:\Repos\EdgeOne.Developer\Developer\stwolfe\src\Libraries\Utility\Management\Automation\RemoteSession.cs:line 44
   at Utility.AzureStackEdge.ApplianceModel.AseNode.SetTestStage(Int32 stage) in C:\Repos\EdgeOne.Developer\Developer\stwolfe\src\Libraries\Utility.Windows\AzureStackEdge\ApplianceModel\AseNode.cs:line 568
   at Utility.AzureStackEdge.ApplianceModel.AseAppliance.<>c__DisplayClass20_0.<SetTestStage>b__0(AseNode d) in C:\Repos\EdgeOne.Developer\Developer\stwolfe\src\Libraries\Utility.Windows\AzureStackEdge\ApplianceModel\AseAppliance.cs:line 156
   at Utility.AzureStackEdge.ApplianceModel.AseAppliance.<>c__DisplayClass12_0.<ProcessOnAllNodes>b__0(AseNode d) in C:\Repos\EdgeOne.Developer\Developer\stwolfe\src\Libraries\Utility.Windows\AzureStackEdge\ApplianceModel\AseAppliance.cs:line 88
ASE Development Utility 0.0.1-preview
```

**Comment by stwolfe** [comment]
Here are the packages I am referencing.

![image](https://user-images.githubusercontent.com/27844532/111324127-7db16380-8638-11eb-9664-a1127dfd2e8a.png)

**Comment by stwolfe** [comment]
I think I found at least a work around.  I was publishing with win-x64, and NOT win10-x64.  

With win10-x64 standalone works.
