### ISSUE TITLE
Not enough memory resources are available to complete this operation 

### ISSUE THREAD

**Issue by aryalrabin** [PowerShell/PowerShell#15049]
Getting "Not enough memory resources are available to complete this operation" while creating a Runspace with System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace. This error happens only in one of the environments. 

 System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLogProvider' threw an exception. ---> System.ComponentModel.Win32Exception: Not enough memory resources are available to complete this operation
   at System.Diagnostics.Eventing.EventProvider.EtwRegister()
   at System.Diagnostics.Eventing.EventProvider..ctor(Guid providerGuid)
   at System.Management.Automation.Tracing.PSEtwLogProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSEtwLogProvider..ctor()
   at System.Management.Automation.Tracing.PSEtwLog..cctor()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Management.Automation.RemoteRunspace..ctor(TypeTable typeTable, RunspaceConnectionInfo connectionInfo, PSHost host, PSPrimitiveDictionary applicationArguments, String name, Int32 id)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable, PSPrimitiveDictionary applicationArguments, String name)

-->

## Steps to reproduce

``` 
call System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(RunspaceConnectionInfo connectionInfo, PSHost host, TypeTable typeTable, PSPrimitiveDictionary applicationArguments, String name)
```

## Expected behavior

``` 
The runspace should not throw memory exception

```

## Actual behavior

```
Works for some time and then it throws the memory error.
```

## Environment data

```
.Net Version: 4.7
PSVersion: 5.1.17763.1490

The Memory usage at the time of the error is 1.2 GB. 

```

Any idea or suggestion to solve this issue is appreciated.

**Comment by iSazonov** [comment]
@aryalrabin Please use our issue templates to create an issue and fill all fields as requested.

**Comment by joeyaiello** [comment]
For Windows PowerShell (including 5.1) issues, you should escalate through your standard Windows support channels. 

That being said, I would suspect that you might actually be running out of memory here for some reason. I'd also make sure your .NET framework and Windows install are fully updated

**Comment by aryalrabin** [comment]
The .NET and Windows are on the latest update. Remember, it does works initially and then blows.  The load is not an issue here as it is happening for a single connection.    

Thanks for replying.
