### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by Pluriscient** [PowerShell/PowerShell#15071]
## Steps to reproduce
- Using Windows Terminal with FiraMono NF
- On WSL copy over an emoji (🐍 in my case) 
- `echo 🐍` (though the 🐍shows up as �)
- First time I tried it I got the error below and a call to report, next few times just printed �

## Expected behavior
Preferably I would see the 🐍, I know my terminal is capable of printing it

## Actual behavior

` echo �`

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 30

Last 200 Keys
```
 d Spacebar l e Tab Enter
 l o c a l e Enter
 l o c a l Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace e Tab Tab Tab Tab Tab Ctrl+Backspace e c h o Spacebar Ctrl+Backspace e c h o Spacebar - e Spacebar " \ x e e \ x 8 2 \ x a 0 " Enter
 e c h o Spacebar Ctrl+Backspace [ c h a r ] 0 x e e Enter
 UpArrow 0 x 8 2 0 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace \ x Backspace Backspace \ x e e \ x 8 2 \ x a 0 Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Backspace 0 Enter
 " Backspace UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace RightArrow RightArrow RightArrow LeftArrow LeftArrow ` u { RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow LeftArrow } Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Backspace Backspace RightArrow RightArrow RightArrow RightArrow Backspace Backspace RightArrow RightArrow RightArrow RightArrow Backspace Backspace Enter
 e c h o Spacebar � Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 5 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by vexx32** [comment]
As the error message states, please report this in the [PSReadLine](/PowerShell/PSReadLine) repo. 🙂

**Comment by Pluriscient** [comment]
apologies
