### ISSUE TITLE
PowerShell process occasionally terminates due to Win32 internal error at SetConsoleCursorPosition

### ISSUE THREAD

**Issue by masaru-iritani** [PowerShell/PowerShell#15254]
I'm seeing an exception terminating PowerShell when I run a script calling devenv.com inside. Because that happens occasionally, I want to understand if there is a similar known issue or how I can collect actionable logs.

## Steps to reproduce

Run a PowerShell script invoking DevEnv.com (v16.9.2) in Windows Terminal Preview 1.7.572.0. The script also calls `Write-Progress` as well as `Write-Information` before that.

## Expected behavior

The script always completes without terminating PowerShell process.

## Actual behavior

PowerShell process terminates. This happens once out of 10-20 times. An error message is output as follows. I must close the window and start a new PowerShell window.

```none
Process terminated. The Win32 internal error "The parameter is incorrect." 0x57 occurred while trying to set the cursor position. Contact Microsoft Customer Support Services.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.Management.Automation.Host.HostException: The Win32 internal error "The parameter is incorrect." 0x57 occurred while trying to set the cursor position. Contact Microsoft Customer Support Services.
 ---> System.ComponentModel.Win32Exception (87): The parameter is incorrect.
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ConsoleControl.SetConsoleCursorPosition(SafeFileHandle consoleHandle, Coordinates cursorPosition)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ConsoleHostUserInterface.ResetProgress()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.Executor.ExecuteCommand(String command, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[process exited with code 2148734499]
```

The exception is thrown on executing the following line.

```powershell
& DevEnv.com $sln /$Target "$Configuration|$Platform" /Project $Project | Tee-Object -Variable 'output'
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please try latest 7.2.0-preview.5 , and 7.1 too. Do you see the issue?

**Comment by masaru-iritani** [comment]
I got a repro with 7.2.0-preview.5. The message format looks slightly different from 7.2.0-preview.4. I'll keep using the same script with PowerShell 7.1.3 to see if I get another repro with it.

```
Process terminated. Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 49,14. (Parameter 'value.Y')
Actual value was 29.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.Management.Automation.PSArgumentOutOfRangeException: Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 49,14. (Parameter 'value.Y')
Actual value was 29.
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.CheckCoordinateWithinBuffer(Coordinates& c, CONSOLE_SCREEN_BUFFER_INFO& bufferInfo, String paramName)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ConsoleHostUserInterface.ResetProgress()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.Executor.ExecuteCommand(String command, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[process exited with code 2148734499
```

**Comment by iSazonov** [comment]
@masaru-iritani Thanks! Can you create and share simple script to reproduce the issue?
What is a terminal you use? Windows Terminal?

**Comment by Sidneys1** [comment]
Got something similar just now on 7.2.0-preview.5:

```
Start-BitsTransfer -Source .\confine_tachyon\confine_tachyon-master-cea846c.zip -Destination \\192.168.1.132\confine-core\
Process terminated. The Win32 internal error "The parameter is incorrect." 0x57 occurred while trying to set the cursor position. Contact Microsoft Customer Support Services.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.Management.Automation.Host.HostException: The Win32 internal error "The parameter is incorrect." 0x57 occurred while trying to set the cursor position. Contact Microsoft Customer Support Services.
 ---> System.ComponentModel.Win32Exception (87): The parameter is incorrect.
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ConsoleControl.SetConsoleCursorPosition(SafeFileHandle consoleHandle, Coordinates cursorPosition)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ConsoleHostUserInterface.ResetProgress()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.Executor.ExecuteCommand(String command, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[process exited with code 2148734499]
```

Steps taken (not sure if this will reproduce it:

1. Terminal in "Focus mode" (tabs hidden), `[Console]::BufferWidth/Height` are 220x62
3. `$PSStyle.Progress` is:
   ```
   Style           : `e[33;1m
   MaxWidth        : 120
   View            : Minimal
   UseOSCIndicator : True
   ```
2. Buffer was scrolled to the bottom (window was scrolling to new output)
3. Used `Start-BitsTransfer` to copy a file to a remote machine
4. While the file was transferring (and thus progress was being displayed) switched off "Focus mode" (tabs appeared). This changed the `[Console]::BufferHeight` to 60 and on the next progress update the terminal crashed with the above error.

**Comment by SteveL-MSFT** [comment]
So it seems like the problem might be when screen buffer height changes so the Y value becomes out of bounds?

**Comment by Sidneys1** [comment]
Yeah, maybe some TOCTOU between checking where the progress pane should be placed and then attempting to draw it with direct win32 calls.
