### ISSUE TITLE
PackageProvider and PSRepository Broken - Ubuntu 20.04

### ISSUE THREAD

**Issue by AjKundnani** [PowerShell/PowerShell#15330]
## Steps to reproduce

```powershell
Get-PackageProvider
Get-PSRepository
```

## Expected behavior

```
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate
PowerShellGet            2.2.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Filter, Tag, Includes, DscR

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
```

## Actual behavior

```
Get-PackageProvider: Unhandled Exception - Message:'The type initializer for 'Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensions' threw an exception.' Name
:'TypeInitializationException' Stack Trace:'   at Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensions.MakeSafeFileName(String input)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType.DefineDynamicType(Type interfaceType)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType..ctor(Type interfaceType, OrderedDictionary`2 methods, List`2 delegates, List`1 stubs)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType.<>c__DisplayClass9_0.<Create>b__3()
   at Microsoft.PackageManagement.Internal.Utility.Extensions.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 valueFunction)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType.Create(Type tInterface, OrderedDictionary`2 instanceMethods, List`2 delegateMethods, List`1 stubMethods, List`2
usedInstances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.CreateProxy(Type tInterface, Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.DynamicCast(Type tInterface, Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.DynamicCast[TInterface](Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterfaceExtensions.As[TInterface](Object instance)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletBase.get_PackageManagementHost()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletBase.SelectProviders(String[] names)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageProvider.ProcessRecordAsync()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.AsyncCmdlet.<>c__DisplayClass83_0.<AsyncRun>b__0()'

DEBUG: 00:00:00.0000001 Calling ImportPackageProvider. providerName = 'PowerShellGet', requiredVersion='', minimumVersion = '', maximumVersion=''
DEBUG: 00:00:00.0001182 Calling ImportPackageProviderViaName. providerName = 'PowerShellGet', requiredVersion='', minimumVersion = '', maximumVersion=''
VERBOSE: PowerShell meta provider initialization failed.
VERBOSE: No match was found for the specified search criteria and provider name 'PowerShellGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exists on the system
.
Get-PackageSource: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9539
Line |
9539 |  … ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
     |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find module providers (PowerShellGet).

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-1046-azure #48-Ubuntu SMP Tue Apr 1…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Network Connectivity to powershellgallery.com
I am able to connect https://www.powershellgallery.com/api/v2 successfully, proxy is bypassed for this connection, on same network PowerShell 7.1.3 works fine with Ubuntu 18.04 distribution

```
*   Trying 168.61.186.235:443...
* TCP_NODELAY set
* Connected to www.powershellgallery.com (168.61.186.235) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
```

**Comment by rjmholt** [comment]
[Here](https://github.com/OneGet/oneget/blob/08ae6e82df2230a601ed09191b26712b213afbc5/src/Microsoft.PackageManagement/Utility/Extensions/FilesystemExtensions.cs#L252)'s where your stack trace points to.

However, given the type of exception, I'm guessing the actual issue lies with [this method](https://github.com/OneGet/oneget/blob/08ae6e82df2230a601ed09191b26712b213afbc5/src/Microsoft.PackageManagement/Utility/Extensions/FilesystemExtensions.cs#L121).

We'd probably get a better stack trace if we could call that method directly. All we need to do is use some reflection to get the type. I can provide code in a bit.

**Comment by rjmholt** [comment]
```powershell
# Ensure the PackageManagement module is loaded so we have the assembly loaded
Import-Module PackageManagement

# Get the needed internal type
$type = [Microsoft.PackageManagement.Internal.Utility.Versions.FourPartVersion].Assembly.GetType('Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensions')

# Now call the method
$type::ResetTempFolder()

# If there's an error, use this to display it fully
Get-Error
```

**Comment by AjKundnani** [comment]
> ```powershell
> # Ensure the PackageManagement module is loaded so we have the assembly loaded
> Import-Module PackageManagement
> 
> # Get the needed internal type
> $type = [Microsoft.PackageManagement.Internal.Utility.Versions.FourPartVersion].Assembly.GetType('Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensions')
> 
> # Now call the method
> $type::ResetTempFolder()
> 
> # If there's an error, use this to display it fully
> Get-Error
> ```

Thanks Rob

### PSHome
/opt/microsoft/powershell/7

### Error for $type::ResetTempFolder()
```
MethodInvocationException: Exception calling "ResetTempFolder" with "0" argument(s): "The type initializer for 'Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExt
ensions' threw an exception."
```

### Output for Get-Error
```
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsError
RecordException
            Message : Exception calling "ResetTempFolder" with "0" arg
ument(s): "The type initializer for 'Microsoft.PackageManagement.Internal.Utili
ty.Extensions.FilesystemExtensions' threw an exception."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsEr
rorRecordException
        FullyQualifiedErrorId : TypeInitializationException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $type::ResetTempFolder()
            PositionMessage  : At line:1 char:1
                               + $type::ResetTempFolder()
                               + ~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandling
Ops, System.Management.Automation, Version=7.1.3.0, Culture=neutral, PublicKeyT
oken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocati
onException(Exception exception, Type typeToThrow, String methodName, Int32 num
Args, MemberInfo memberInfo) in /PowerShell/src/System.Management.Automation/en
gine/runtime/Operations/MiscOps.cs:line 2068
   at CallSite.Target(Closure , CallSite , Object )
  at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site,
T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(Interpr
etedFrame frame) in /PowerShell/src/System.Management.Automation/engine/interpr
eter/DynamicInstructions.Generated.cs:line 141
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.
Run(InterpretedFrame frame) in /PowerShell/src/System.Management.Automation/eng
ine/interpreter/ControlFlowInstructions.cs:line 358
    Message        : Exception calling "ResetTempFolder" with "0" argu
ment(s): "The type initializer for 'Microsoft.PackageManagement.Internal.Utilit
y.Extensions.FilesystemExtensions' threw an exception."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type           : System.TypeInitializationException
        TypeName       : Microsoft.PackageManagement.Internal.Utility.
Extensions.FilesystemExtensions
        TargetSite     :
            Name          : ResetTempFolder
            DeclaringType : Microsoft.PackageManagement.Internal.Utili
ty.Extensions.FilesystemExtensions, Microsoft.PackageManagement, Version=3.0.0.
1, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : Microsoft.PackageManagement.dll
        StackTrace     :
   at Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensi
ons.ResetTempFolder()
   at CallSite.Target(Closure , CallSite , Object )
        Message        : The type initializer for 'Microsoft.PackageMa
nagement.Internal.Utility.Extensions.FilesystemExtensions' threw an exception.
        InnerException :
            Type           : System.UnauthorizedAccessException
            TargetSite     :
                Name          : CreateDirectoryHandle
                DeclaringType : System.IO.Enumeration.FileSystemEnumer
ator`1[TResult]
                MemberType    : Method
                Module        : System.IO.FileSystem.dll
            StackTrace     :
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String
path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Bool
ean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, Find
Transform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String
directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPatt
ern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensi
ons.ResetTempFolder()
   at Microsoft.PackageManagement.Internal.Utility.Extensions.FilesystemExtensi
ons..cctor()
            Message        : Access to the path '/tmp/Microsoft.Packag
eManagement' is denied.
            InnerException :
                Type    : System.IO.IOException
                Message : Permission denied
                HResult : 13
            Source         : System.IO.FileSystem
            HResult        : -2147024891
        Source         : Microsoft.PackageManagement
        HResult        : -2146233036
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : TypeInitializationException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $type::ResetTempFolder()
    PositionMessage  : At line:1 char:1
                       + $type::ResetTempFolder()
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by rjmholt** [comment]
Ah looks like it might be a permissions issue on `/tmp`

**Comment by rjmholt** [comment]
Just for fuller context in case anyone hits issues here:

- Modules were initially installed as root by an agent on the system
- Later, commands were run by a non-root user and the permissions on `/tmp/Microsoft.PackageManagement` didn't allow for reading
- This was solved with `chmod o+r /tmp/Microsoft.PackageManagement` (or a similar addition of permissions on the directory for other users)
- An issue remains with modules installed to the `AllUsers` directory only being available to `root`

**Comment by AjKundnani** [comment]
> Just for fuller context in case anyone hits issues here:
> 
> * Modules were initially installed as root by an agent on the system
> * Later, commands were run by a non-root user and the permissions on `/tmp/Microsoft.PackageManagement` didn't allow for reading
> * This was solved with `chmod o+r /tmp/Microsoft.PackageManagement` (or a similar addition of permissions on the directory for other users)
> * An issue remains with modules installed to the `AllUsers` directory only being available to `root`

Thanks Rob:

- `umask` = `0027` (For both Ubuntu 18.04 and Ubuntu 20.04)
- Permissions on /tmp/Microsoft.PackageManagement is `1750` (For Ubuntu 20.04) and `1755` (For Ubuntu 18.04) sharing same umask.
- Both Ubuntu 18.04 & 20.04 are initiated using **Cloud Init Extension** with same code. However former allows to run modules for all users, latter after modifying permission only allows module to be used / installed by `root` user.
- Command used to install module in CloudInit = `Install-Module Az -Scope AllUsers -Confirm:$false -Force`

**Comment by rjmholt** [comment]
Trying to install a module to `AllUsers` as `root` on a fresh 20.04 VM gave me permissions of `755` on a newly installed module there (and the module directory itself), so this may be something idiosyncratic to CloudInit.

**Comment by daxian-dbw** [comment]
@rjmholt It looks the problem is resolved, so I marked `Resolution-Answered`. Feel free to change the label if there is remaining issues to be looked into.
