### ISSUE TITLE
Testing `HelpSystem.Tests.ps1` fails using local built PS because of Empty GUID

### ISSUE THREAD

**Issue by davidBar-On** [PowerShell/PowerShell#15353]
## Steps to reproduce

Under WSL2 Ubuntu or Windows install PS for build per the [instructions for Linux](https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md).  After successful `Start-PSBuild`, run:
```powershell
Start-PSPester ./test/powershell/engine/Help/HelpSystem.Tests.ps1
```

## Expected behavior

Successful tests.

## Actual behavior
From WSL:

PS crashes because of [this assertion checking for empty GUID](https://github.com/PowerShell/PowerShell/blob/a95b2cb17fecc8640533420b3baa9aec0f3749cb/src/System.Management.Automation/help/UpdatableHelpModuleInfo.cs#L31) (00000000-0000-0000-0000-000000000000):
```none
Process terminated. Assertion failed.
   at System.Management.Automation.Help.UpdatableHelpModuleInfo..ctor(String name, Guid guid, String path, String uri) in /home/dbo/Tools/PowerShell/src/System.Management.Automation/help/UpdatableHelpModuleInfo.cs:line 31
   at Microsoft.PowerShell.Commands.UpdatableHelpCommandBase.GetModuleInfo(ExecutionContext context, String pattern, ModuleSpecification fullyQualifiedName, Boolean noErrors) in /home/dbo/Tools/PowerShell/src/System.Management.Automation/help/UpdatableHelpCommandBase.cs:line 338
   at Microsoft.PowerShell.Commands.UpdatableHelpCommandBase.GetModuleInfo(String pattern, ModuleSpecification fullyQualifiedName, Boolean noErrors) in /home/dbo/Tools/PowerShell/src/System.Management.Automation/help/UpdatableHelpCommandBase.cs:line 617
   at Microsoft.PowerShell.Commands.UpdatableHelpCommandBase.ProcessModuleWithGlobbing(String name) in /home/dbo/Tools/PowerShell/src/System.Management.Automation/help/UpdatableHelpCommandBase.cs:line 474
   at Microsoft.PowerShell.Commands.UpdatableHelpCommandBase.Process(IEnumerable`1 moduleNames, IEnumerable`1 fullyQualifiedNames) in /home/dbo/Tools/PowerShell/src/System
.......
```

The problem happened in [HelpSystem.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/a95b2cb17fecc8640533420b3baa9aec0f3749cb/test/powershell/engine/Help/HelpSystem.Tests.ps1#L32) that executed:
```powershell
Update-Help -Module Microsoft.PowerShell.Core -SourcePath .../test/powershell/engine/Help/assets -Force -ErrorAction Stop -Scope CurrentUser
```

Following is the list of files in `test/powershell/engine/Help/assets` folder, which includes `Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000...` files:
```None
CimCmdlets_fb6cc51d-c096-4b38-b78d-0fed6277096a_en-US_HelpContent.cab
HelpURI
Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_HelpInfo.xml
Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_en-US_HelpContent.cab
Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_en-US_HelpContent.zip
Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_HelpInfo.xml
Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.cab
Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.zip
Microsoft.PowerShell.Diagnostics_ca046f10-ca64-4740-8ff9-2565dba61a4f_HelpInfo.xml
Microsoft.PowerShell.Diagnostics_ca046f10-ca64-4740-8ff9-2565dba61a4f_en-US_helpcontent.cab
Microsoft.PowerShell.Diagnostics_ca046f10-ca64-4740-8ff9-2565dba61a4f_en-US_helpcontent.zip
Microsoft.PowerShell.Host_56d66100-99a0-4ffc-a12d-eee9a6718aef_HelpInfo.xml
Microsoft.PowerShell.Host_56d66100-99a0-4ffc-a12d-eee9a6718aef_en-US_helpcontent.cab
Microsoft.PowerShell.Host_56d66100-99a0-4ffc-a12d-eee9a6718aef_en-US_helpcontent.zip
Microsoft.PowerShell.LocalAccounts_8e362604-2c0b-448f-a414-a6a690a644e2_HelpInfo.xml
Microsoft.PowerShell.LocalAccounts_8e362604-2c0b-448f-a414-a6a690a644e2_en-US_HelpContent.cab
Microsoft.PowerShell.Management_eefcb906-b326-4e99-9f54-8b4bb6ef3c6d_HelpInfo.xml
Microsoft.PowerShell.Management_eefcb906-b326-4e99-9f54-8b4bb6ef3c6d_en-US_helpcontent.cab
Microsoft.PowerShell.Management_eefcb906-b326-4e99-9f54-8b4bb6ef3c6d_en-US_helpcontent.zip
Microsoft.PowerShell.Security_A94C8C7E-9810-47C0-B8AF-65089C13A35A_HelpInfo.xml
Microsoft.PowerShell.Security_A94C8C7E-9810-47C0-B8AF-65089C13A35A_en-US_HelpContent.cab
Microsoft.PowerShell.Security_a94c8c7e-9810-47c0-b8af-65089c13a35a_en-US_helpcontent.zip
Microsoft.PowerShell.Utility_1da87e53-152b-403e-98dc-74d7b4d63d59_HelpInfo.xml
Microsoft.PowerShell.Utility_1da87e53-152b-403e-98dc-74d7b4d63d59_en-US_helpcontent.cab
Microsoft.PowerShell.Utility_1da87e53-152b-403e-98dc-74d7b4d63d59_en-US_helpcontent.zip
Microsoft.WSMan.Management_766204A6-330E-4263-A7AB-46C87AFC366C_HelpInfo.xml
Microsoft.WSMan.Management_766204A6-330E-4263-A7AB-46C87AFC366C_en-US_HelpContent.cab
Microsoft.WsMan.Management_766204A6-330E-4263-A7AB-46C87AFC366C_en-US_helpcontent.zip
PackageManagement_4ae9fd46-338a-459c-8186-07f910774cb8_HelpInfo.xml
PackageManagement_4ae9fd46-338a-459c-8186-07f910774cb8_en-US_helpcontent.cab
PackageManagement_4ae9fd46-338a-459c-8186-07f910774cb8_en-US_helpcontent.zip
PowershellGet_1d73a601-4a6c-43c5-ba3f-619b18bbb404_HelpInfo.xml
PowershellGet_1d73a601-4a6c-43c5-ba3f-619b18bbb404_en-US_helpcontent.cab
PowershellGet_1d73a601-4a6c-43c5-ba3f-619b18bbb404_en-US_helpcontent.zip
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by daxian-dbw** [comment]
@adityapatwardhan Can you please take a look?

**Comment by davidBar-On** [comment]
Found the root cause.  Submitted PR #15551 with a suggested change.
