### ISSUE TITLE
Get-FormatData breaks after importing view using common customcontrol

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#15413]
After importing a custom format.ps1xml using common custom control inside a view `Get-FormatData` breaks. The viewdefinition itself works, but `Get-FormatData` doesn't like the new viewdefinition.

This only affects the scenario when you reference a custom control in the view-body. Using a custom control in GroupBy or included it directly in the view works as expected.

Errors after importing the custom formatting data.

**Get all formatdata fails**
![image](https://user-images.githubusercontent.com/3436158/118531250-ec4c9380-b745-11eb-9ef7-ef37557cc9e6.png)

**... because getting formatdata for custom class fails**
![image](https://user-images.githubusercontent.com/3436158/118531298-f8d0ec00-b745-11eb-891f-e9af05173f7a.png)

**but getting pre-existing formatting data works**
![image](https://user-images.githubusercontent.com/3436158/118531279-f4a4ce80-b745-11eb-9dd1-7c8e07dbd21f.png)

## Steps to reproduce

Execute the three repro-scripts below in separate powershell-sessions.

<details>
<summary>fails-with-common-control.ps1</summary>

```powershell
Write-Host 'Get-FormatData BEFORE = WORKS' -ForegroundColor Green
$before = Get-FormatData

$tempPath = "$([System.IO.Path]::GetTempFileName()).ps1xml"

# Repro is basically MamlCommandExamples-view + simplified ExamplesControlcontrol from Help.format.ps1xml in PS5.1 (as PS7 formats are built-in now)
@'
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <ViewDefinitions>
    <View>
      <Name>Demo</Name>
      <ViewSelectedBy>
        <TypeName>DemoClass</TypeName>
      </ViewSelectedBy>
      <CustomControl>
        <CustomEntries>
          <CustomEntry>
            <CustomItem>
              <ExpressionBinding>
                <ScriptBlock>$_</ScriptBlock>
                <CustomControlName>DemoControl</CustomControlName>
              </ExpressionBinding>
            </CustomItem>
          </CustomEntry>
        </CustomEntries>
      </CustomControl>
    </View>
  </ViewDefinitions>
  <Controls>
    <Control>
      <Name>DemoControl</Name>
      <CustomControl>
        <CustomEntries>
          <CustomEntry>
            <CustomItem>
              <Text>Demo time!</Text>
            </CustomItem>
          </CustomEntry>
        </CustomEntries>
      </CustomControl>
    </Control>
  </Controls>
</Configuration>
'@ | Set-Content -Path $tempPath -Verbose
Update-FormatData -PrependPath $tempPath -Verbose

Write-Host 'Get-FormatData AFTER importing custom format using common control = FAILS' -ForegroundColor Red
$after = Get-FormatData

# Should throw exception. Get-FormatData is broken.

Write-Host 'Testing custom viewdefinition = WORKS (shows "Demo Time!")' -ForegroundColor Green
[pscustomobject]@{PSTypeName='DemoClass'; Some='value'}

# ViewDefinition works as expected. Just Get-FormatData that breaks.

Remove-Item -Path $tempPath -Verbose
```
</details>

<details>
<summary>works-with-included-control.ps1</summary>

```powershell
Write-Host 'Get-FormatData BEFORE = WORKS' -ForegroundColor Green
$before = Get-FormatData

$tempPath = "$([System.IO.Path]::GetTempFileName()).ps1xml"

# Repro is basically MamlCommandExamples-view + simplified ExamplesControlcontrol from Help.format.ps1xml in PS5.1 (as PS7 formats are built-in now)
@'
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <ViewDefinitions>
    <View>
      <Name>Demo</Name>
      <ViewSelectedBy>
        <TypeName>DemoClass</TypeName>
      </ViewSelectedBy>
      <CustomControl>
        <CustomEntries>
          <CustomEntry>
            <CustomItem>
              <ExpressionBinding>
                <ScriptBlock>$_</ScriptBlock>
                <CustomControl>
                  <CustomEntries>
                    <CustomEntry>
                      <CustomItem>
                        <Text>Demo time!</Text>
                      </CustomItem>
                    </CustomEntry>
                  </CustomEntries>
                </CustomControl>
              </ExpressionBinding>
            </CustomItem>
          </CustomEntry>
        </CustomEntries>
      </CustomControl>
    </View>
  </ViewDefinitions>
</Configuration>
'@ | Set-Content -Path $tempPath -Verbose
Update-FormatData -PrependPath $tempPath -Verbose

Write-Host 'Get-FormatData AFTER importing custom format with built-in/included custom control = WORKS' -ForegroundColor Green
$after = Get-FormatData

Write-Host 'Testing custom viewdefinition = WORKS (shows "Demo Time!")' -ForegroundColor Green
[pscustomobject]@{PSTypeName='DemoClass'; Some='value'}

# ViewDefinition works as expected. Just Get-FormatData that breaks.

Remove-Item -Path $tempPath -Verbose
```
</details>

<details>
<summary>works-when-used-in-groupby.ps1</summary>

```powershell
Write-Host 'Get-FormatData BEFORE = WORKS' -ForegroundColor Green
$before = Get-FormatData

$tempPath = "$([System.IO.Path]::GetTempFileName()).ps1xml"

# Repro is basically MamlCommandExamples-view + simplified ExamplesControlcontrol from Help.format.ps1xml in PS5.1 (as PS7 formats are built-in now)
@'
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <ViewDefinitions>
    <View>
      <Name>Demo</Name>
      <ViewSelectedBy>
        <TypeName>DemoClass</TypeName>
      </ViewSelectedBy>
      <GroupBy>
        <PropertyName>Some</PropertyName>
        <CustomControlName>DemoControl</CustomControlName>
      </GroupBy>
      <CustomControl>
        <CustomEntries>
          <CustomEntry>
            <CustomItem>
              <Text>Hello world!</Text>
            </CustomItem>
          </CustomEntry>
        </CustomEntries>
      </CustomControl>
    </View>
  </ViewDefinitions>
  <Controls>
    <Control>
      <Name>DemoControl</Name>
      <CustomControl>
        <CustomEntries>
          <CustomEntry>
            <CustomItem>
              <Text>GROUPED BY: Demo</Text>
            </CustomItem>
          </CustomEntry>
        </CustomEntries>
      </CustomControl>
    </Control>
  </Controls>
</Configuration>
'@ | Set-Content -Path $tempPath -Verbose
Update-FormatData -PrependPath $tempPath -Verbose

Write-Host 'Get-FormatData AFTER importing custom format using common custom control in groupby = WORKS' -ForegroundColor Green
$after = Get-FormatData

Write-Host 'Testing custom viewdefinition = WORKS (shows "GROUPED BY: Demo" and "Hello world!")' -ForegroundColor Green
[pscustomobject]@{PSTypeName='DemoClass'; Some='value'}

# ViewDefinition works as expected. Just Get-FormatData that breaks.

Remove-Item -Path $tempPath -Verbose
```
</details>

This isn't because of `Update-FormatData`. Same issue when loading formatdata using `FormatsToProcess = @('test.Format.ps1xml')` in module manifest.

## Expected behavior

`Get-FormatData` should never throw error and always return registered formatting data as expected.

## Actual behavior

Works as expected when common control is used in GroupBy, but `Get-FormatData` breaks when using common control in view body.

#### FAILS with common control in body
![image](https://user-images.githubusercontent.com/3436158/118530856-6deff180-b745-11eb-81b2-b09deb32a53c.png)

#### Works with builtin custom control
![image](https://user-images.githubusercontent.com/3436158/118530897-7ba57700-b745-11eb-9ff7-9f2ae5c1c747.png)

#### Works with common custom control in groupby:
![image](https://user-images.githubusercontent.com/3436158/118530931-85c77580-b745-11eb-8dd9-eb483d7cb2e2.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Same issue with Windows PowerShell 5.1

**Comment by fflaten** [comment]
I'd say this is related to #11202, #12427 and maybe more issues. It seems the focus has been to much on the WinPSCompat-layer while ignoring the fact that `Get-FormatData` might have been broken for years when using third-party custom controls - even in Windows PowerShell as shown in https://github.com/PowerShell/PowerShell/issues/11202#issuecomment-558830772 also

**Comment by rjmholt** [comment]
Full stack trace (from `Get-Error`):

```
Exception             :
    Type       : System.InvalidCastException
    TargetSite :
        Name          : ChkCast_Helper
        DeclaringType : System.Runtime.CompilerServices.CastHelpers, System.Private.CoreLib,
Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.Management.Automation.CustomItemBase.Create(FormatToken token)
   at System.Management.Automation.CustomControlEntry..ctor(ComplexControlEntryDefinition entry)
   at System.Management.Automation.CustomControl..ctor(ComplexControlBody body, ViewDefinition
viewDefinition)
   at Microsoft.PowerShell.Commands.GetFormatDataCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message    : Unable to cast object of type
'Microsoft.PowerShell.Commands.Internal.Format.ControlReference' to type
'Microsoft.PowerShell.Commands.Internal.Format.ComplexControlBody'.
    Source     : System.Private.CoreLib
    HResult    : -2147467262
CategoryInfo          : NotSpecified: (:) [Get-FormatData], InvalidCastException
FullyQualifiedErrorId :
System.InvalidCastException,Microsoft.PowerShell.Commands.GetFormatDataCommand
InvocationInfo        :
    MyCommand        : Get-FormatData
    ScriptLineNumber : 1
    OffsetInLine     : 10
    HistoryId        : 8
    Line             : $after = Get-FormatData
    PositionMessage  : At line:1 char:10
                       + $after = Get-FormatData
                       +          ~~~~~~~~~~~~~~
    InvocationName   : Get-FormatData
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

That's this method:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs#L175-L246

Specifically, when debugging it, we hit this line:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs#L231

On that line in this instance, `cpt.control` is of type `Microsoft.PowerShell.Commands.Internal.Format.ControlReference`, which has no cast to `Microsoft.PowerShell.Commands.Internal.Format.ControlBody`. Instead it looks like it might want to use this method:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs#L643-L654

I have no experience with that code unfortunately, so I'm not sure to what extent those changes would fix things.

**Comment by fflaten** [comment]
Thanks for the triage and acknowledgement of the bug :) I should probably add that all formatdata using CustomControl are never shown in `Get-FormatData`. Even when controls are embedded so it doesn't throw the error, it will actually never show the ExtendedTypeDefinition that I imported. Using any of the other PSControl-classes in the view behaves as it should.

Not sure if this is caused by the same part of if it should be a different issue.
