### ISSUE TITLE
Get-ChildItem -path '/' breaks -exclude or -include parameters

### ISSUE THREAD

**Issue by tsmarvin** [PowerShell/PowerShell#15497]
I believe there is a bug with `Get-ChildItem` for pwsh v7.1.3 on Ubuntu 20.04 (WSL2) when using the  `-exclude` and `-include` parameters in conjunction with the ` -Path '/'` parameter/argument combo.

This seems primarily be limited to `Get-ChildItem -Path '/'` as both `-LiteralPath '/'` and `-PSPath (Get-Item -Path '/').PSPath` return the data as expected when used with either `-exclude` or `-include`.

Additionally using `-exclude` and `-path` together works for directories outside `/`. However, I believe there may be another bug when using `-Path` and `-Include` other places as well.

### Get-ChildItem -Path '/' -Exclude 'mnt'
```powershell
# Bad:
Get-ChildItem -Path '/' -Exclude 'mnt'

# Aligns with expected behavior:
Get-ChildItem -Path '/mnt' -Exclude 'c'
Get-ChildItem -LiteralPath '/' -Exclude 'mnt'
Get-ChildItem -PSPath (Get-Item -Path '/').PSPath -Exclude 'mnt'
```
![image](https://user-images.githubusercontent.com/57049894/120273996-159c1200-c264-11eb-8cdd-4b9e197159bb.png)

### Get-ChildItem -Path '/' -Include 'mnt'
```powershell
# Bad:
Get-ChildItem -Path '/' -Include 'mnt'
Get-ChildItem -Path '/mnt' -Include 'c'

# Aligns with expected behavior:
Get-ChildItem -LiteralPath '/' -Include 'mnt'
Get-ChildItem -LiteralPath '/mnt' -Include 'c'
Get-ChildItem -PSPath (Get-Item -Path '/').PSPath -Include 'mnt'
Get-ChildItem -PSPath (Get-Item -Path '/mnt').PSPath -Include 'c'
```
![image](https://user-images.githubusercontent.com/57049894/120274513-d0c4ab00-c264-11eb-9226-be96d91de85b.png)

I'm unsure if the behavior of `-Include` deserves its own bug report but would be happy to split it up if needed.

## Environment data
![image](https://user-images.githubusercontent.com/57049894/120271372-1468e600-c260-11eb-8ae7-ede2bb105b9d.png)

```plaintext
StackTrace:
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetChildName(String path) in /PowerShell/src/System.Management.Automation/namespaces/FileSystemProvider.cs:line 5683
   at System.Management.Automation.Provider.NavigationCmdletProvider.GetChildName(String path, CmdletProviderContext context) in /PowerShell/src/System.Management.Automation/namespaces/NavigationProviderBase.cs:line 174
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context) in /PowerShell/src/System.Management.Automation/namespaces/LocationGlobber.cs:line 2763
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance) in /PowerShell/src/System.Management.Automation/namespaces/LocationGlobber.cs:line 516
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance) in /PowerShell/src/System.Management.Automation/namespaces/LocationGlobber.cs:line 218
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance) in /PowerShell/src/System.Management.Automation/namespaces/LocationGlobber.cs:line 779
   at System.Management.Automation.SessionStateInternal.GetChildItems(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context) in /PowerShell/src/System.Management.Automation/engine/SessionStateContainer.cs:line 1393
   at System.Management.Automation.ChildItemCmdletProviderIntrinsics.Get(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context) in /PowerShell/src/System.Management.Automation/engine/ChildrenCmdletProviderInterfaces.cs:line 278
   at Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord() in /PowerShell/src/Microsoft.PowerShell.Commands.Management/commands/management/GetChildrenCommand.cs:line 318
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in /PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 388
```

**Comment by iSazonov** [comment]
I guess it is dup #3304

**Comment by ninmonkey** [comment]
@tsmarvin What do you get running these?

```ps1
> Resolve-Path /

# and
> set-location -LiteralPath '/'
> Get-ChildItem -path '/'
```

Maybe it's related to to windows root paths

the syntax `c:` refers to the root directory

- If I use `c:` it does not search the root path, it uses my `cwd` some reason.
- if I use `c:\` then it does. 

```ps1
'current path: '
Set-Location cd 'D:\test\'
Get-Item . | ForEach-Object FullName

$paths = '.', 'c:', 'c:\', 'd:','d:\'
$paths | ForEach-Object {
    $p = Get-ChildItem -File -Path $_ | Select-Object -First 1 | ForEach-Object FullName
    [pscustomobject]@{
       'PathParam' = $_
       'FullName' = $p
    }
}
```
```
current path:                                          
D:\test                                                
                                                       
PathParam FullName                                     
--------- --------                                     
.         D:\test\image.png                        
c:        C:\Temp\export.tsv                    
c:\       C:\a.log
d:        D:\test\image.png                        
d:\       D:\stuff.md     
```

**Comment by tsmarvin** [comment]
Apologies - its been a busy week and I haven't had time to get back to this until now. 

@ninmonkey The behavior seems to be consistent between both windows and linux. The main difference is that linux returns an error for `Get-ChildItem -Path '/' -exclude 'mnt'` but windows does not.

Windows: 
![image](https://user-images.githubusercontent.com/57049894/120938089-0c78ce00-c6c6-11eb-8f31-afa3923702f7.png)

Linux: 
![image](https://user-images.githubusercontent.com/57049894/120938340-0b946c00-c6c7-11eb-9498-6c8848eb04f6.png)


@iSazonov I'm unsure if this issue is the same as [#3304](https://github.com/PowerShell/PowerShell/issues/3304) as the exclude/include behavior for this issue is inconsistent between the root directories and non-root directories but 3304 seems to be more about the implicit wildcard for include/exclude.
Also - for this particular issue Linux now throws an error where Windows does not.

**Comment by mklement0** [comment]
@iSazonov, it isn't a duplicate of #3304, but the _workaround_ for the latter works here too:

```powershell
# Note the "*"
Get-Item -Path /* -Exclude mnt
```
