### ISSUE TITLE
Invoke-RestMethod parallel problem

### ISSUE THREAD

**Issue by dperez83** [PowerShell/PowerShell#15513]
## Steps to reproduce

It happens randomly. Most of the time it works. Sometimes it fails and no other Invoke-RestMethod is possible after.

```powershell
1..10 | ForEach-Object -Parallel { Invoke-RestMethod -Uri "www.google.com" -Headers @{
                 "method"="GET"
                 "scheme"="https"
                  } 
 } -ThrottleLimit 3


```

## Expected behavior

```
To work everytime without the concurrent update error.
```

## Actual behavior

```
Sometimes it returns the error bellow, and no further Invoke-RestMethod is possible in the session (it always returns the very same error) :

Invoke-RestMethod: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
//cc @PaulHigin

**Comment by vexx32** [comment]
This is the stack trace when this error turns up:
```
StackTrace     :    at System.Collections.Generic.HashSet`1.FindItemIndex(T item)
                    at System.Collections.Generic.HashSet`1.Contains(T item)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetRequest(Uri uri)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by vexx32** [comment]
Looks like it's most likely occurring here:

https://github.com/PowerShell/PowerShell/blob/1ba2960f5c5df9de4c079c97644e9af7bf34385b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1090

This KnownHttpHeaderNames is using a static property hashset to handle things; we may need to make that an instance class or threadstatic.

**Comment by iSazonov** [comment]
I guess it is in WebRequestSession.ContentHeaders.

**Comment by dperez83** [comment]
Hello, thank you all for the quick response to my issue. Here are the details of the error I managed capture :

**With $Error[0] | Select-Object**

```
Invoke-RestMethod: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
PS C:\Users\dpz83>  $Error[0] | Select-Object *


PSMessageDetails      : 
Exception             : System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
                           at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
                           at System.Collections.Generic.HashSet`1.Add(T item)
                           at Microsoft.PowerShell.Commands.HttpKnownHeaderNames.get_ContentHeaders()
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetRequest(Uri uri)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                           at System.Management.Automation.Cmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

**And with Get-Error**

```
PS C:\Users\dpz83> Get-Error


Exception             : 
    Type       : System.InvalidOperationException
    TargetSite : 
        Name          : ThrowInvalidOperationException_ConcurrentOperationsNotSupported
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace : 
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Microsoft.PowerShell.Commands.HttpKnownHeaderNames.get_ContentHeaders()
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetRequest(Uri uri)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message    : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    Source     : System.Private.CoreLib
    HResult    : -2146233079
CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
InvocationInfo        : 
    MyCommand        : Invoke-RestMethod
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 1
    Line             : Invoke-RestMethod -Uri "www.google.com.br" -Headers @{

    PositionMessage  : At line:1 char:2
                       +  Invoke-RestMethod -Uri "www.google.com.br" -Headers @{
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-RestMethod
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```
