### ISSUE TITLE
Unspecified Error when running Get-ADPrincipalGroupMembership using Non-delegated Account

### ISSUE THREAD

**Issue by Jessuhs** [PowerShell/PowerShell#15788]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running `Get-ADPrincipalGroupMembership` using an admin account that is marked as "sensitive and cannot be delegated", an unspecified error occurs. This is happening on an admin workstation, not on the DC.

The exact command I'm attempting to run is:
`Get-ADPrincipalGroupMembership -Identity "adtest"`

This error does not occur when using a standard user account. We use admin accounts for various tasks and it seems to be **only** this command that causes an error.

Strangely on this account I can run `Get-ADUser`, `Get-ADGroupMember`, `Get-ADObject`, etc. I can even run `Add-ADPrincipalGroupMembership` and `Remove-ADPrincipalGroupMembership` while using this non-delegated admin account without issue. I'm also able to view the contents of the **Member Of** tab in ADUC with both accounts.

I believe this is a bug with this particular command in the ActiveDirectory module.

For now my workaround is to just use my regular account for these lookups or to use `(Get-ADUser -Identity adtest -Properties MemberOf).MemberOf`

### Expected behavior

```console
PS C:\> Get-ADPrincipalGroupMembership -Identity adtest

distinguishedName : CN=Domain Users,CN=Users,DC=contoso,DC=com
GroupCategory     : Security
GroupScope        : Global
name              : Domain Users
objectClass       : group
objectGUID        : c48b2114-2fe7-4282-b296-a0d3b4c80141
SamAccountName    : Domain Users
SID               : S-1-5-21-1444237352-1323246715-1848914655-513
```

### Actual behavior

```console
PS C:\> Get-ADPrincipalGroupMembership -Identity adtest
Get-ADPrincipalGroupMembership: An unspecified error has occurred
```

### Error details

```console
Exception             :
    Type               : Microsoft.ActiveDirectory.Management.ADException
    ServerErrorMessage : An operations error occurred.

    TargetSite         :
        Name          : GetExceptionFromErrorCode
        DeclaringType : Microsoft.ActiveDirectory.Management.ExceptionHelper, Microsoft.ActiveDirectory.Management, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : Microsoft.ActiveDirectory.Management.dll
    StackTrace         :
   at Microsoft.ActiveDirectory.Management.ExceptionHelper.GetExceptionFromErrorCode(Int32 errorCode, String errorMessage, String serverErrorMessage, Exception innerException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForErrorCode(String message, String errorCode, String extendedErrorMessage, Exception innerException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowException(CustomActionFault caFault, FaultException faultException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.GetADPrincipalGroupMembership(GetADPrincipalGroupMembershipRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADAccountManagement.GetADPrincipalGroupMembership(ADSessionHandle handle, GetADPrincipalGroupMembershipRequest request)
   at Microsoft.ActiveDirectory.Management.ADAccountManagement.GetPrincipalGroupMembership(String partitionDN, String principalDN, String resourceContextServer, String resourceContextPartition)
   at Microsoft.ActiveDirectory.Management.Commands.GetADPrincipalGroupMembership.GetGroupMembershipProcessCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()
    Message            : An unspecified error has occurred
    InnerException     :
        Type       : System.ServiceModel.FaultException`1[[schemas.microsoft.com._2008._1.ActiveDirectory.CustomActions.GetADPrincipalGroupMembershipFault, Microsoft.ActiveDirectory.Management, Version=10.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35]]
        Detail     : schemas.microsoft.com._2008._1.ActiveDirectory.CustomActions.GetADPrincipalGroupMembershipFault
        Action     : http://schemas.microsoft.com/2008/1/ActiveDirectory/Data/fault
        Code       : System.ServiceModel.FaultCode
        Message    : Active Directory returned an error processing the operation.
        Reason     : Active Directory returned an error processing the operation.
        TargetSite :
            Name          : HandleReply
            DeclaringType : System.ServiceModel.Channels.ServiceChannel, System.Private.ServiceModel, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
            MemberType    : Method
            Module        : System.Private.ServiceModel.dll
        StackTrace :
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_3.GetADPrincipalGroupMembership(GetADPrincipalGroupMembershipRequest )
   at Microsoft.ActiveDirectory.Management.AdwsConnection.GetADPrincipalGroupMembership(GetADPrincipalGroupMembershipRequest request)
        Source     : System.Private.ServiceModel
        HResult    : -2146233088
    Source             : Microsoft.ActiveDirectory.Management
    HResult            : -2146233088
CategoryInfo          : NotSpecified: (adtest:ADPrincipal) [Get-ADPrincipalGroupMembership], ADException
FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.GetADPrincipalGroupMembership
InvocationInfo        :
    MyCommand        : Get-ADPrincipalGroupMembership
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 12
    Line             : Get-ADPrincipalGroupMembership -Identity adtest
    PositionMessage  : At line:1 char:1
                       + Get-ADPrincipalGroupMembership -Identity adtest
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-ADPrincipalGroupMembership
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
PS C:\> Get-WindowsCapability -Online | ? {$_.State -eq "Installed" -and $_.Name -like "Rsat*"}

Name  : Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0
State : Installed
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please use Windows Feedback tool to report the issue.
