### ISSUE TITLE
Get-CimInstance -NameSpace root/wmi -ClassName "BatteryStaticData" throws generic failure

### ISSUE THREAD

**Issue by hkystar35** [PowerShell/PowerShell#15799]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In Pwsh 7.1.3 (and Windows PowerShell 5.1), the **BatteryStaticData** WMI class data cannot be called with CIM cmdlets.

Verify Class exists:
```ps
PS C:\> Get-CimClass -Namespace root/wmi -ClassName BatteryStaticData | Select-Object -Property *

CimClassName        : BatteryStaticData
CimSuperClassName   : MSBatteryClass
CimSuperClass       : ROOT/wmi:MSBatteryClass
CimClassProperties  : {Caption, Description, Name, Frequency_Object…}
CimClassQualifiers  : {dynamic, guid, localeid, provider…}
CimClassMethods     : {}
CimSystemProperties : Microsoft.Management.Infrastructure.CimSystemProperties
```

I can also reproduce this error in Windows PowerShell 5.1

____________________________________________________________

Additionally, in PowerShell 5.1, using the older `Get-WMIObject` command works as expected:
```ps
PS C:\> Get-WmiObject -Namespace root/wmi -Class BatteryStaticData | select *

PSComputerName     : REDACTED
__GENUS            : 2
__CLASS            : BatteryStaticData
__SUPERCLASS       : MSBatteryClass
__DYNASTY          : CIM_StatisticalInformation
__RELPATH          : BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
__PROPERTY_COUNT   : 28
__DERIVATION       : {MSBatteryClass, Win32_PerfRawData, Win32_Perf, CIM_StatisticalInformation}
__SERVER           : REDACTED
__NAMESPACE        : root\wmi
__PATH             : \\REDACTED\root\wmi:BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
Active             : True
Capabilities       : 2147483648
Caption            :
Chemistry          : 5269836
CriticalBias       : 0
DefaultAlert1      : 2060
DefaultAlert2      : 6794
Description        :
DesignedCapacity   : 68005
DeviceName         : DELL REDACTED
Frequency_Object   :
Frequency_PerfTime :
Frequency_Sys100NS :
Granularity0       : 8847632630436
Granularity1       : 292079250965156
Granularity2       : 0
Granularity3       : 0
InstanceName       : ACPI\PNP0C0A\1_0
ManufactureDate    : **************.**********
ManufactureName    : SMP
Name               :
SerialNumber       : 156
Tag                : 1
Technology         : 1
Timestamp_Object   :
Timestamp_PerfTime :
Timestamp_Sys100NS :
UniqueID           : 156SMPDELL REDACTED
Scope              : System.Management.ManagementScope
Path               : \\REDACTED\root\wmi:BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
Options            : System.Management.ObjectGetOptions
ClassPath          : \\REDACTED\root\wmi:BatteryStaticData
Properties         : {Active, Capabilities, Caption, Chemistry...}
SystemProperties   : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers         : {dynamic}
Site               :
Container          :
```

### Expected behavior

```console
PS C:\> Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData | select *

PSComputerName     : REDACTED
__GENUS            : 2
__CLASS            : BatteryStaticData
__SUPERCLASS       : MSBatteryClass
__DYNASTY          : CIM_StatisticalInformation
__RELPATH          : BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
__PROPERTY_COUNT   : 28
__DERIVATION       : {MSBatteryClass, Win32_PerfRawData, Win32_Perf, CIM_StatisticalInformation}
__SERVER           : REDACTED
__NAMESPACE        : root\wmi
__PATH             : \\REDACTED\root\wmi:BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
Active             : True
Capabilities       : 2147483648
Caption            :
Chemistry          : 5269836
CriticalBias       : 0
DefaultAlert1      : 2060
DefaultAlert2      : 6794
Description        :
DesignedCapacity   : 68005
DeviceName         : DELL REDACTED
Frequency_Object   :
Frequency_PerfTime :
Frequency_Sys100NS :
Granularity0       : 8847632630436
Granularity1       : 292079250965156
Granularity2       : 0
Granularity3       : 0
InstanceName       : ACPI\PNP0C0A\1_0
ManufactureDate    : **************.**********
ManufactureName    : SMP
Name               :
SerialNumber       : 156
Tag                : 1
Technology         : 1
Timestamp_Object   :
Timestamp_PerfTime :
Timestamp_Sys100NS :
UniqueID           : 156SMPDELL REDACTED
Scope              : System.Management.ManagementScope
Path               : \\REDACTED\root\wmi:BatteryStaticData.InstanceName="ACPI\\PNP0C0A\\1_0"
Options            : System.Management.ObjectGetOptions
ClassPath          : \\REDACTED\root\wmi:BatteryStaticData
Properties         : {Active, Capabilities, Caption, Chemistry...}
SystemProperties   : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers         : {dynamic}
Site               :
Container          :
```

### Actual behavior

```console
PS C:\> Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -Verbose | Select-Object -Property *
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root/wmi,'className' = BatteryStaticData'.
Get-CimInstance: Generic failure
VERBOSE: Operation 'Enumerate CimInstances' complete.
```

### Error details

```console
OriginInfo            :
Exception             :
    Type            : Microsoft.Management.Infrastructure.CimException
    NativeErrorCode : Failed
    ErrorData       : MSFT_WmiError
    MessageId       : HRESULT 0x80041001
    StatusCode      : 1
    TargetSite      :
        Name          : ProcessNativeCallback
        DeclaringType : Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1[T]
        MemberType    : Method
        Module        : Microsoft.Management.Infrastructure.dll
    StackTrace      :
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(Operati
onCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult,
String errorMessage, InstanceHandle errorDetailsHandle)
    Message         : Generic failure
    Source          : Microsoft.Management.Infrastructure
    HResult         : -2146233088
TargetObject          : root/wmi:BatteryStaticData
CategoryInfo          : NotSpecified: (root/wmi:BatteryStaticData:String) [Get-CimInstance], CimException
FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
InvocationInfo        :
    MyCommand        : Get-CimInstance
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 13
    Line             : Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -Verbose | Select-Object
-Property *
    PositionMessage  : At line:1 char:1
                       + Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -Ver …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-CimInstance
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Trying to enumerate manually gives a more specific error message:

```powershell
$cim = [CimSession]::Create('.')
$cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
# InvalidOperation: An error occurred while enumerating through a collection: The WS-Management service cannot process the request. The request contains an invalid datetime. The string **************.********** does not represent any of these types: xs:dateTime, xs:date, or xs:time..
```

<details>

<summary>Get-Error output</summary>

```powershell
$Error[0].Exception.InnerException|Get-Error

Type            : Microsoft.Management.Infrastructure.CimException
NativeErrorCode : Failed
ErrorData       : MSFT_WmiError
MessageId       : HRESULT 0x80338041
StatusCode      : 1
TargetSite      :
    Name          : MoveNext
    DeclaringType : Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1[T]
    MemberType    : Method
    Module        : Microsoft.Management.Infrastructure.dll
StackTrace      :
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at System.Management.Automation.EnumerableOps.MoveNext(ExecutionContext context, IEnumerator enumerator)
Message         : The WS-Management service cannot process the request. The request contains an invalid datetime. The string
**************.********** does not represent any of these types: xs:dateTime, xs:date, or xs:time.
Source          : Microsoft.Management.Infrastructure
HResult         : -2146233088
```

</details>

**Comment by hkystar35** [comment]
Great addition, thank you @SeeminglyScience !

Verified the same additional output:
```ps
PS C:\> $cim = [CimSession]::Create('.')
PS C:\> $cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
InvalidOperation: An error occurred while enumerating through a collection: The WS-Management service cannot process the request. The request contains an invalid datetime. The string **************.********** does not represent any of these types: xs:dateTime, xs:date, or xs:time..
PS C:\> Get-Error

Exception             :
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : An error occurred while enumerating through a collection: The WS-Management service cannot
process the request. The request contains an invalid datetime. The string **************.********** does not represent
any of these types: xs:dateTime, xs:date, or xs:time..
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (Microsoft.Managemen…cInstanceEnumerator:CimSyncInstanceEnumerator)
[], ParentContainsErrorRecordException
        FullyQualifiedErrorId : BadEnumeration
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
            PositionMessage  : At line:1 char:1
                               + $cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : MoveNext
        DeclaringType : System.Management.Automation.EnumerableOps, System.Management.Automation, Version=7.1.3.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.EnumerableOps.MoveNext(ExecutionContext context, IEnumerator enumerator)
   at System.Management.Automation.EnumerableOps.WriteEnumerableToPipe(IEnumerator enumerator, Pipe pipe,
ExecutionContext context, Boolean dispose)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.ActionCallInstruction`5.Invoke(Object arg0, Object arg1, Object arg2,
Object arg3, Object arg4)
   at System.Management.Automation.Interpreter.CallInstruction.InvokeInstance(Object instance, Object[] args)
   at System.Management.Automation.Interpreter.DynamicInstructionN.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : An error occurred while enumerating through a collection: The WS-Management service cannot
process the request. The request contains an invalid datetime. The string **************.********** does not represent
any of these types: xs:dateTime, xs:date, or xs:time..
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type            : Microsoft.Management.Infrastructure.CimException
        NativeErrorCode : Failed
        ErrorData       : MSFT_WmiError
        MessageId       : HRESULT 0x80338041
        StatusCode      : 1
        TargetSite      :
            Name          : MoveNext
            DeclaringType : Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1[T]
            MemberType    : Method
            Module        : Microsoft.Management.Infrastructure.dll
        StackTrace      :
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at System.Management.Automation.EnumerableOps.MoveNext(ExecutionContext context, IEnumerator enumerator)
        Message         : The WS-Management service cannot process the request. The request contains an invalid
datetime. The string **************.********** does not represent any of these types: xs:dateTime, xs:date, or xs:time.
        Source          : Microsoft.Management.Infrastructure
        HResult         : -2146233088
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : InvalidOperation: (Microsoft.Managemen…cInstanceEnumerator:CimSyncInstanceEnumerator) [],
RuntimeException
FullyQualifiedErrorId : BadEnumeration
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
    PositionMessage  : At line:1 char:1
                       + $cim.EnumerateInstances('root/wmi', 'BatteryStaticData')
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by fMichaleczek** [comment]
A little code, to determinate which property is failed.

```
Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -KeyOnly | 
Get-Member -MemberType Properties | 
Where-Object Name -ne PSComputerName | 
ForEach-Object { $_.Name ; Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -Property $_.Name | Out-Null }
```

So it's ManufactureDate

I exclude it.
```
Get-CimInstance -Namespace root/wmi -ClassName BatteryStaticData -Property 'Active', 'Capabilities', 'Caption', 'Chemistry', 'CriticalBias', 'DefaultAlert1', 'DefaultAlert2', 'Description', 'DesignedCapacity', 'DeviceName', 'Frequency_Object', 'Frequency_PerfTime', 'Frequency_Sys100NS', 'Granularity0', 'Granularity1', 'Granularity2', 'Granularity3', 'InstanceName', 'ManufactureName', 'Name', 'SerialNumber', 'Tag', 'Technology', 'Timestamp_Object', 'Timestamp_PerfTime', 'Timestamp_Sys100NS', 'UniqueID'
```

Workaround is working :)

The WMI command shows the same value as you for my old Dell. 
`ManufactureDate    : **************.**********`

I will test on another computer later.

**Comment by 237dmitry** [comment]
СIM is much poorer than WMI in terms of functionality. But what we have, we use. A tribute to modern technologies at the expense of existing ones.

**Comment by vexx32** [comment]
The reason CIM fails here is essentially because it tries to be helpful and convert the wmi/cim datetime value to a usable DateTime object in .NET. Arguably, an improvement more than anything.

It would be a good idea to have a fallback to return the raw value, for cases like this where the raw value is unusable.

**Comment by fMichaleczek** [comment]
> The reason CIM fails here is essentially because it tries to be helpful and convert the wmi/cim datetime value to a usable DateTime object in .NET. Arguably, an improvement more than anything.
> 
> It would be a good idea to have a fallback to return the raw value (or just nothing), for cases like this where the property's value is unusable.

This issue should be moved to this repository https://github.com/PowerShell/MMI
