### ISSUE TITLE
Pasting from clipboard to PWSH console sometimes omits hyphen

### ISSUE THREAD

**Issue by dennisl68-castra** [PowerShell/PowerShell#15847]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When pasting a command to the console, hyphens is sometimes missing.

Please use the code below to generate a sample string for pasting into a PowerShell 7 console...

```
$step = [System.Convert]::FromBase64String(
    'IyAxLiBUbyBkaXNwbGF5IGEgbGlzdCBvZiBzZXJ2aWNlcyB0aGF0IHNob3dzIH' +
    'N0b3BwZWQgc2VydmljZXMgbGFzdCwgcnVuOgogICAgCkdldC1TZXJ2aWNlIHwg' +
    'ClNvcnQgU3RhdHVzIOKAk0Rlc2NlbmRpbmc='
)
[System.Text.Encoding]::UTF8.GetString($step)
```

### Expected behavior

```console
Get-Service |
Sort Status –Descending

<Mark, Ctrl-C, Ctrl-V>

Get-Service |
Sort Status –Descending
```

### Actual behavior

```console
Get-Service |
Sort Status –Descending

<Mark, Ctrl-C, Ctrl-V>

Get-Service |
Sort Status Descending
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : A positional parameter cannot be found that accepts argument 'Descending'.
    ParameterName     : Descending
    TypeSpecified     : string
    ErrorId           : PositionalParameterNotFound
    Line              : 2
    Offset            : 1
    CommandInvocation :
        MyCommand        : Sort-Object
        BoundParameters  :
            BoundPositionally :
                Length : 8
            Comparer          : System.OrdinalIgnoreCaseComparer
            Count             : 1
            Keys              :
                Length : 8
            Values            :
                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                    Length : 6
                IsFixedSize : True
                Count       : 1
            SyncRoot          :
                BoundPositionally :
                    Length : 8
                Comparer          : System.OrdinalIgnoreCaseComparer
                Count             : 1
                Keys              :
                    Length : 8
                Values            :
                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                        Length : 6
                    IsFixedSize : True
                    Count       : 1
                SyncRoot          :
                    BoundPositionally :
                        Length : 8
                    Comparer          : System.OrdinalIgnoreCaseComparer
                    Count             : 1
                    Keys              :
                        Length : 8
                    Values            :
                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                            Length : 6
                        IsFixedSize : True
                        Count       : 1
                    SyncRoot          :
                        BoundPositionally :
                            Length : 8
                        Comparer          : System.OrdinalIgnoreCaseComparer
                        Count             : 1
                        Keys              :
                            Length : 8
                        Values            :
                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                Length : 6
                            IsFixedSize : True
                            Count       : 1
                        SyncRoot          :
                            BoundPositionally :
                                Length : 8
                            Comparer          : System.OrdinalIgnoreCaseComparer
                            Count             : 1
                            Keys              :
                                Length : 8
                            Values            :
                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                    Length : 6
                                IsFixedSize : True
                                Count       : 1
                            SyncRoot          :
                                BoundPositionally :
                                    Length : 8
                                Comparer          : System.OrdinalIgnoreCaseComparer
                                Count             : 1
                                Keys              :
                                    Length : 8
                                Values            :
                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1
                                SyncRoot          :
                                    BoundPositionally : …
                                    Comparer          : System.OrdinalIgnoreCaseComparer
                                    Count             : 1
                                    Keys              : …
                                    Values            : …
                                    SyncRoot          : …
        ScriptLineNumber : 2
        OffsetInLine     : 1
        HistoryId        : 3
        Line             : Sort Status Descending
        PositionMessage  : At line:2 char:1
                           + Sort Status Descending
                           + ~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Sort
        PipelineLength   : 2
        PipelinePosition : 2
        ExpectingInput   : True
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : A positional parameter cannot be found that accepts argument 'Descending'.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Sort-Object], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SortObjectCommand
        InvocationInfo        :
            MyCommand        : Sort-Object
            ScriptLineNumber : 2
            OffsetInLine     : 1
            HistoryId        : 3
            Line             : Sort Status Descending
            PositionMessage  : At line:2 char:1
                               + Sort Status Descending
                               + ~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : VerifyArgumentsProcessed
        DeclaringType : System.Management.Automation.CmdletParameterBinderController, System.Management.Automation,
Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException
originalBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
CategoryInfo          : InvalidArgument: (:) [Sort-Object], ParameterBindingException
FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SortObjectCommand
InvocationInfo        :
    MyCommand        : Sort-Object
    ScriptLineNumber : 2
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Sort Status Descending
    PositionMessage  : At line:2 char:1
                       + Sort Status Descending
                       + ~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/49750419/127619575-169f93d6-507c-4f70-ba4d-b9567577fd5e.png)

**Comment by iSazonov** [comment]
Does the issue exists if PSReadline module unloaded?

**Comment by dennisl68-castra** [comment]
If I remove PSReadline using 
`Remove-Module PSReadLine`
the issue goes away.

**Comment by iSazonov** [comment]
I suggest you update to latest PSReadline (preview) and report this issue to PSReadline repository if the issue will still persist.

**Comment by dennisl68-castra** [comment]
Tried updating to latest available on PSGallery (2.2.0, beta3) using
`Install-Module psreadline -AllowClobber -AllowPrerelease -Scope AllUsers -Force`
The console still misses out on hyphens with PSReadline present.

I will report an issue in the PSReadline repo...

**Comment by dennisl68-castra** [comment]
Ok, removed all versions of PSReadLine from my system except the one that came with WindowsPowerShell 5.1 (2.0.0, beta 2) and now I can work again :)

I did try the "stable" version of 2.0.0 and that has the same issue :/

**Comment by iSazonov** [comment]
Please share your investigations in PSReadline repo.

**Comment by dennisl68-castra** [comment]
Yes, did that yesterday. 

No response as of yet. 

[#2175](https://github.com/PowerShell/PSReadLine/issues/2715)
