### ISSUE TITLE
Get-CsOnlineUser with -Filter on boolean sporadically fails

### ISSUE THREAD

**Issue by amonzerol** [PowerShell/PowerShell#15850]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We are currently running Linux Powershell with Snap on LTS (7.0.6), but I've been able to reproduce this issue on 7.1.3.

We used to be able to run `Get-CsOnlineUser` with filters on boolean values so it doesn't return the whole directory, but that **sporadically** doesn't work anymore. Sometimes when we kill the Powershell process and restart it + connect to Microsoft Teams it works, sometimes it doesn't.

This is what we've been running:

```
PS /home/antoine/dev/projects/smacs> Get-CsOnlineUser -Filter {Enabled -eq $True}
Get-CsOnlineUser: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
```
or

```
PS /home/antoine/dev/projects/smacs> Get-CsOnlineUser -Filter {EnterpriseVoiceEnabled -eq $True}                              
Get-CsOnlineUser: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
```

### Expected behavior

```console
PS /home/antoine/dev/projects/smacs> Get-CsOnlineUser -Filter {Enabled -eq $True}

Returns a list of Enabled SfB users.
```

### Actual behavior

```console
PS /home/antoine/dev/projects/smacs> Get-CsOnlineUser -Filter {Enabled -eq $True}
Get-CsOnlineUser: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
```

### Error details

```console
PS /home/antoine/dev/projects/smacs> Get-Error

OriginInfo            : api.interfaces.records.teams.microsoft.com
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> 
System.Management.Automation.SetValueInvocationException: Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.String'.
                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.<>c__DisplayClass17_0.<CreateFilter>b__0(ComparisonOperator op, PropertyDefinition propDef, Object val, Boolean useWildchars)
                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.CreateRelationalExpression(ComparisonOperator op, String prop, Object val, Boolean useWildchars)
                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.yyparse()
                                     at Microsoft.Rtc.Management.ADConnect.Filter.MonadFilter..ctor(String filterText, PSCmdlet cmdlet, ObjectSchema schema, CreateRelationalExpressionDelegate expressionDelegate, Capabilities capabilities)
                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.CreateFilter(String filterText, PSCmdlet cmdlet, ObjectSchema schema, HashSet`1& returnMentionedTenants)
                                     at Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet.set_Filter(String value)
                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                     --- End of inner exception stack trace ---
                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                     --- End of inner exception stack trace ---
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> 
System.Management.Automation.SetValueInvocationException: Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.String'.
                                             at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.<>c__DisplayClass17_0.<CreateFilter>b__0(ComparisonOperator op, PropertyDefinition propDef, Object val, Boolean useWildchars)
                                             at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.CreateRelationalExpression(ComparisonOperator op, String prop, Object val, Boolean useWildchars)
                                             at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.yyparse()
                                             at Microsoft.Rtc.Management.ADConnect.Filter.MonadFilter..ctor(String filterText, PSCmdlet cmdlet, ObjectSchema schema, CreateRelationalExpressionDelegate expressionDelegate, Capabilities capabilities)
                                             at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.CreateFilter(String filterText, PSCmdlet cmdlet, ObjectSchema schema, HashSet`1& returnMentionedTenants)
                                             at Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet.set_Filter(String value)
                                             at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                             --- End of inner exception stack trace ---
                                             at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                             --- End of inner exception stack trace ---
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             --- End of stack trace from previous location where exception was thrown ---
                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> 
System.Management.Automation.SetValueInvocationException: Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.String'.
                                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.<>c__DisplayClass17_0.<CreateFilter>b__0(ComparisonOperator op, PropertyDefinition propDef, Object val, Boolean useWildchars)
                                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.CreateRelationalExpression(ComparisonOperator op, String prop, Object val, Boolean useWildchars)
                                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.yyparse()
                                                     at Microsoft.Rtc.Management.ADConnect.Filter.MonadFilter..ctor(String filterText, PSCmdlet cmdlet, ObjectSchema schema, CreateRelationalExpressionDelegate expressionDelegate, Capabilities capabilities)
                                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.CreateFilter(String filterText, PSCmdlet cmdlet, ObjectSchema schema, HashSet`1& returnMentionedTenants)
                                                     at Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet.set_Filter(String value)
                                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                     --- End of inner exception stack trace ---
                                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                     --- End of inner exception stack trace ---
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     --- End of stack trace from previous location where exception was thrown ---
                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> 
System.Management.Automation.SetValueInvocationException: Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.String'.
                                                             at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.<>c__DisplayClass17_0.<CreateFilter>b__0(ComparisonOperator op, PropertyDefinition propDef, Object val, Boolean useWildchars)
                                                             at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.CreateRelationalExpression(ComparisonOperator op, String prop, Object val, Boolean useWildchars)
                                                             at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.yyparse()
                                                             at Microsoft.Rtc.Management.ADConnect.Filter.MonadFilter..ctor(String filterText, PSCmdlet cmdlet, ObjectSchema schema, CreateRelationalExpressionDelegate expressionDelegate, Capabilities capabilities)
                                                             at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.CreateFilter(String filterText, PSCmdlet cmdlet, ObjectSchema schema, HashSet`1& returnMentionedTenants)
                                                             at Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet.set_Filter(String value)
                                                             at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                             --- End of inner exception stack trace ---
                                                             at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                             --- End of inner exception stack trace ---
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             --- End of stack trace from previous location where exception was thrown ---
                                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." 
---> System.Management.Automation.SetValueInvocationException: Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'." ---> System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.String'.
                                                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.<>c__DisplayClass17_0.<CreateFilter>b__0(ComparisonOperator op, PropertyDefinition propDef, Object val, Boolean useWildchars)
                                                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.CreateRelationalExpression(ComparisonOperator op, String prop, Object val, Boolean useWildchars)
                                                                     at Microsoft.Rtc.Management.ADConnect.Filter.QueryParser.yyparse()
                                                                     at Microsoft.Rtc.Management.ADConnect.Filter.MonadFilter..ctor(String filterText, PSCmdlet cmdlet, ObjectSchema schema, CreateRelationalExpressionDelegate expressionDelegate, Capabilities capabilities)
                                                                     at Microsoft.Rtc.Management.AD.GetADObjectWithIdentityTask`2.CreateFilter(String filterText, PSCmdlet cmdlet, ObjectSchema schema, HashSet`1& returnMentionedTenants)
                                                                     at Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet.set_Filter(String value)
                                                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                                     --- End of inner exception stack trace ---
                                                                     at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                                     --- End of inner exception stack trace ---
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     --- End of stack trace from previous location where exception was thrown ---
                                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
                                    HResult                        : -2146233087
                                CategoryInfo          : WriteError: (:) [Get-CsOnlineUser], ParameterBindingException
                                FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet
                            Message                        : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
                            HResult                        : -2146233087
                        CategoryInfo          : WriteError: (:) [Get-CsOnlineUser], ParameterBindingException
                        FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet
                    Message                        : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
                    HResult                        : -2146233087
                CategoryInfo          : WriteError: (:) [Get-CsOnlineUser], ParameterBindingException
                FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet
            Message                        : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
            HResult                        : -2146233087
        CategoryInfo          : WriteError: (:) [Get-CsOnlineUser], ParameterBindingException
        FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet
    Message                        : Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."
    HResult                        : -2146233087
CategoryInfo          : WriteError: (:) [Get-CsOnlineUser], ParameterBindingException
FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Rtc.Management.AD.Cmdlets.GetOcsUserCmdlet
```

### Environment data

```powershell
PS /home/antoine/dev/projects/smacs> $PSVersionTable                             

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Linux 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

```
**********************
PowerShell transcript start
Start time: 20210730155116
Username: antoine-ThinkPad-T480s\antoine
RunAs User: antoine-ThinkPad-T480s\antoine
Configuration Name: 
Machine: antoine-ThinkPad-T480s (Unix 5.4.0.80)
Host Application: /snap/powershell/161/opt/powershell/pwsh.dll
Process ID: 23116
PSVersion: 7.0.6
PSEdition: Core
GitCommitId: 7.0.6
OS: Linux 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021
Platform: Unix
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.6
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is /home/antoine/PowerShell_transcript.antoine-ThinkPad-T480s.GKliE+qs.20210730155116.txt
PS /home/antoine/dev/projects/smacs> $creds = Get-Credential
PS /home/antoine/dev/projects/smacs> Connect-MicrosoftTeams -Credential $creds

Account                  Environment Tenant                               TenantId
-------                  ----------- ------                               --------
amonzerol@dev-stack8.com AzureCloud  0d64725c-6eea-4ee0-a981-538ef9a5a0b4 0d64725c-6eea-4ee0-a981-538ef9a5a0b4

PS /home/antoine/dev/projects/smacs> Get-CsOnlineUser -Filter {Enabled -eq $True}

Get-CsOnlineUser: Cannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."

[91mGet-CsOnlineUser: [91mCannot bind parameter 'Filter' to the target. Exception setting "Filter": "Unable to cast object of type 'System.Boolean' to type 'System.String'."[0m
PS /home/antoine/dev/projects/smacs> Stop-Transcript
**********************
PowerShell transcript end
End time: 20210730155153
**********************
```

**Comment by amonzerol** [comment]
It seems like the filter does work on some booleans and some dosen't:

![image](https://user-images.githubusercontent.com/39344707/127707479-a922fd83-9ba9-4c31-9b5a-12f420edb162.png)

**Comment by iSazonov** [comment]
The cmdlet is not in the repository and we can do nothing here.

Please use Teams feedback channels to report the issue.
