### ISSUE TITLE
REGRESSION: Format-Wide with missing property crashes

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#15964]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Basically, ask `Format-Wide` for a property that doesn't exist, or more confusingly, ask it for a property that only exists on a few of the output objects.

```PowerShell
Get-ChildItem $Home | Format-Wide Parent -Auto
```
Since "Parent" is only set on directory items, you'll see $Home printed out for each directory, but when it gets to the files, it crashes unceremoniously with the message: **out-lineoutput : Object reference not set to an instance of an object.**

![image](https://user-images.githubusercontent.com/192942/130306187-d16205e2-5610-4549-8843-56d0dac50d07.png)

Note that if the property you specify is missing on the _first_ item, you get no output at all (except the error message).

![image](https://user-images.githubusercontent.com/192942/130306319-c5bd66fb-4f26-49ec-9615-b1482a54e5a2.png)

### Expected behavior

```console
It should output an empty string when there's no property, the way it does on PowerShell 5.1
```
![image](https://user-images.githubusercontent.com/192942/130306217-da3210c3-6069-4db0-ab05-9286e738e0d1.png)

```console
**Even** when the first few object don't have the property:
```
![image](https://user-images.githubusercontent.com/192942/130306341-b06dd5db-1c4d-433e-a8e0-35d410e8dceb.png)

I'm not talking about the fact that in PowerShell 5.1 the "Parent" is rendered as just the name (instead of the whole path), but about the fact that for items with no value you just get an empty string. 

I would accept no output without stopping (or, just skip over it)

### Actual behavior

```console
Stops outputting on the first object with a missing property and prints:

out-lineoutput : Object reference not set to an instance of an object.
```

### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type       : System.NullReferenceException
        TargetSite :
            Name          : GenerateRow
            DeclaringType : Microsoft.PowerShell.Commands.Internal.Format.TableWriter, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace :
   at Microsoft.PowerShell.Commands.Internal.Format.TableWriter.GenerateRow(String[] values, ReadOnlySpan`1 alignment, DisplayCells dc)
   at Microsoft.PowerShell.Commands.Internal.Format.TableWriter.GenerateRow(String[] values, LineOutput lo, Boolean multiLine, ReadOnlySpan`1 alignment, DisplayCells dc, List`1 generatedRows)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.WideOutputContext.WriteStringBuffer()
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessPayload(FormatEntryData fed, OutputContext c)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessObject(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Message    : Object reference not set to an instance of an object.
        Source     : System.Management.Automation
        HResult    : -2147467261
    CategoryInfo          : NotSpecified: (:) [out-lineoutput], NullReferenceException
    FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.OutLineOutputCommand
    InvocationInfo        :
        MyCommand       : out-lineoutput
        HistoryId       : 15
        CommandOrigin   : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
Message        : Object reference not set to an instance of an object.
InnerException :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : GenerateRow
        DeclaringType : Microsoft.PowerShell.Commands.Internal.Format.TableWriter, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace :
   at Microsoft.PowerShell.Commands.Internal.Format.TableWriter.GenerateRow(String[] values, ReadOnlySpan`1 alignment, DisplayCells dc)
   at Microsoft.PowerShell.Commands.Internal.Format.TableWriter.GenerateRow(String[] values, LineOutput lo, Boolean multiLine, ReadOnlySpan`1 alignment, DisplayCells dc, List`1 generatedRows)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.WideOutputContext.WriteStringBuffer()
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessPayload(FormatEntryData fed, OutputContext c)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessObject(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message    : Object reference not set to an instance of an object.
    Source     : System.Management.Automation
    HResult    : -2147467261
Source         : System.Management.Automation
HResult        : -2146233087
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The NRE is in 6.2.
Error is in the line https://github.com/PowerShell/PowerShell/blob/e70ad6ce251d2e1d4ef79e31756cededde7ccc91/src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs#L461

**Comment by DarylGraves** [comment]
Please could this be assigned to me?
