### ISSUE TITLE
Linux "Access Denied" when writing to CIFS mount

### ISSUE THREAD

**Issue by jdkang** [PowerShell/PowerShell#16056]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Starting with an empty directory in a mounted CIFS share
```
root@cubo:/mnt/backups/testing# ls -la
total 0
drwxrwxrwx 2 root root 0 Sep  5 20:21 .
drwxrwxrwx 2 root root 0 Sep  5 20:20 ..
```

First try with Python3 `pathlib`
```
root@cubo:/mnt/backups/testing# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> p = pathlib.Path("/mnt/backups/testing/from_python")
>>> p.write_text("from python")
11
>>> exit()
root@cubo:/mnt/backups/testing# cat ./from_python
from python
```

try bash redirect
```
root@cubo:/mnt/backups/testing# echo "from bash" > ./from_bash
root@cubo:/mnt/backups/testing# cat ./from_bash
from bash
```

try in powershell 7
```
PS /mnt/backups/testing> 'from powershell' | Out-File -Path './from_powershell' -Force
Out-File: Access to the path '/mnt/backups/testing/from_powershell' is denied.
PS /mnt/backups/testing> $Error[0] | select *

PSMessageDetails      :
Exception             : System.UnauthorizedAccessException: Access to the path
                        '/mnt/backups/testing/from_powershell' is denied.
                         ---> System.IO.IOException: Permission denied
                           --- End of inner exception stack trace ---
                           at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
                           at System.IO.FileStream.FlushWriteBuffer()
                           at System.IO.FileStream.FlushInternalBuffer()
                           at System.IO.FileStream.Flush(Boolean flushToDisk)
                           at System.IO.FileStream.Flush()
                           at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
                           at System.IO.StreamWriter.Flush()
                           at Microsoft.PowerShell.Commands.OutFileCommand.ProcessRecord() in /PowerShell/src
                        /Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-
                        File.cs:line 252
                           at System.Management.Automation.Cmdlet.DoProcessRecord() in
                        /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 173
                           at System.Management.Automation.CommandProcessor.ProcessRecord() in
                        /PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 388
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Out-File], UnauthorizedAccessException
FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.OutFileCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PS /mnt/backups/testing> ls -la
total 8
drwxrwxrwx 2 root root  0 Sep  5 20:23 .
drwxrwxrwx 2 root root  0 Sep  5 20:20 ..
-rwxrwxrwx 1 root root 10 Sep  5 20:22 from_bash
-rwxrwxrwx 1 root root  0 Sep  5 20:32 from_powershell
-rwxrwxrwx 1 root root 11 Sep  5 20:22 from_python
PS /mnt/backups/testing> cat ./from_powershell
PS /mnt/backups/testing> get-item ./from_powershell | select Length

Length
------
     0
```

### Expected behavior

```console
To write a file similar to python and bash.
```

### Actual behavior

```console
Permission Denied error. Seems to write a 0-byte file.
```

### Error details

```console
Exception             :
    Type           : System.UnauthorizedAccessException
    TargetSite     :
        Name          : WriteNative
        DeclaringType : System.IO.FileStream
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace     :
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.FlushInternalBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.FileStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Microsoft.PowerShell.Commands.OutFileCommand.ProcessRecord() in
/PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs:line 252
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in
/PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 388
    Message        : Access to the path '/mnt/backups/testing/from_powershell' is denied.
    InnerException :
        Type    : System.IO.IOException
        Message : Permission denied
        HResult : 13
    Source         : System.Private.CoreLib
    HResult        : -2147024891
CategoryInfo          : NotSpecified: (:) [Out-File], UnauthorizedAccessException
FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.OutFileCommand
InvocationInfo        :
    MyCommand        : Out-File
    ScriptLineNumber : 1
    OffsetInLine     : 21
    HistoryId        : 11
    Line             : 'from powershell' | Out-File -Path './from_powershell' -Force
    PositionMessage  : At line:1 char:21
                       + 'from powershell' | Out-File -Path './from_powershell' -Force
                       +                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Out-File
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
I believe this is a duplicate of https://github.com/PowerShell/PowerShell/issues/15339

**Comment by iSazonov** [comment]
Can you check using only .Net API? E.g. [FileStream]::new() and write to the stream.

**Comment by 237dmitry** [comment]
> Permission Denied error. Seems to write a 0-byte file.

Python and bash you run from root? Run pwsh from root (sudo) too.

**Comment by jdkang** [comment]
> > Permission Denied error. Seems to write a 0-byte file.
> 
> Python and bash you run from root? Run pwsh from root (sudo) too.

The mounts are mounted as 777 in fstab.

**Comment by jdkang** [comment]
> I believe this is a duplicate of #15339

Ah yes after reading the issue and the dotnet PR to fix the issue,
