### ISSUE TITLE
Get-DNSServerResoruceRecord Fails

### ISSUE THREAD

**Issue by markdomansky** [PowerShell/PowerShell#16094]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to use the DNSServer module, in either native or Windows PowerShell compat mode, saving the results to a variable generates an error.
This occurs when remote to the DNS Server itself.  (restricted from testing locally on the server)
This does NOT occur in Windows PowerShell 5.1.  The expected behavior is produced

### Expected behavior

```console
PS> $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname
PS> $a
HostName                  RecordType Type       Timestamp            TimeToLive      RecordData
--------                  ---------- ----       ---------            ----------      ----------
<data>

PS> Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname -ov a
PS> $a
HostName                  RecordType Type       Timestamp            TimeToLive      RecordData
--------                  ---------- ----       ---------            ----------      ----------
<data>
```

### Actual behavior

```console
PS> $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname
MetadataError: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".

PS> Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname -ov a
MetadataError: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type "System.Net.IPAddress".
```

### Error details

```console
PS> Get-Error #output sanitized
Exception             : 
    Type           : System.Management.Automation.ArgumentTransformationMetadataException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".
            HResult : -2146233087
        CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : RuntimeException
        InvocationInfo        : 
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname
            PositionMessage  : At line:1 char:1
                               + $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName …
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : Transform
        DeclaringType : System.Management.Automation.ArgumentTypeConverterAttribute, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     : 
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
   at System.Management.Automation.PSVariable.TransformValue(IEnumerable`1 attributes, Object value)
   at System.Management.Automation.PSVariable.SetValue(Object value)
   at System.Management.Automation.VariableOps.SetVariableValue(VariablePath variablePath, Object value, ExecutionContext executionContext, AttributeBaseAst[] attributeAsts)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type        : System.Management.Automation.PSInvalidCastException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ConvertToFinalInvalidCastException
        TargetSite  : 
            Name          : ThrowInvalidCastException
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace  : 
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable
backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable     
backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
        Message     : Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".
        Source      : System.Management.Automation
        HResult     : -2147467262
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
FullyQualifiedErrorId : RuntimeException
InvocationInfo        : 
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName domain.local -name hostname
    PositionMessage  : At line:1 char:1
                       + $a = Get-DnsServerResourceRecord -ComputerName server.domain.local -ZoneName …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/4317290/133321431-0f46b334-edab-41a2-8596-f34268f8475c.png)

**Comment by iSazonov** [comment]
Can you reproduce with latest PowerShell 7.2 preview?

**Comment by daxian-dbw** [comment]
@markdomansky For the script and results shown in the "Actual Behavior" section, did you have the module imported with Windows PowerShell compat mode (`-UseWindowsPowerShell`)? If so, can you also share the results when loading the module natively in pwsh with `-SkipEditionCheck`?

**Comment by markdomansky** [comment]
I'm unable to reproduce on 7.1.4 or 7.2.0-p9.
Patches, reboots, or something else must have resolved.  Closing.
Thanks.
