### ISSUE TITLE
Trouble opening MS Sticky Notes from Powershell

### ISSUE THREAD

**Issue by zxskyyy** [PowerShell/PowerShell#16188]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
PS C:\Users\cfuen\Desktop> cd "C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_4.1.6.0_x64__8wekyb3d8bbwe"
PS C:\Program Files\WindowsApps\Microsoft.MicrosoftStickyNotes_4.1.6.0_x64__8wekyb3d8bbwe> .\Microsoft.Notes.exe
```

### Expected behavior

```console
MS Sticky Notes should launch
```

### Actual behavior

```console
ResourceUnavailable: Program 'Microsoft.Notes.exe' failed to run: Acceso denegado.At line:1 char:1
+ .\Microsoft.Notes.exe
+ ~~~~~~~~~~~~~~~~~~~~~.
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.ApplicationFailedException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Program 'Microsoft.Notes.exe' failed to run: Acceso denegado.At line:1 char:1
                      + .\Microsoft.Notes.exe
                      + ~~~~~~~~~~~~~~~~~~~~~.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NativeCommandFailed
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : .\Microsoft.Notes.exe
            PositionMessage  : At line:1 char:1
                               + .\Microsoft.Notes.exe
                               + ~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : InitNativeProcess
        DeclaringType : System.Management.Automation.NativeCommandProcessor, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.NativeCommandProcessor.InitNativeProcess()
   at System.Management.Automation.NativeCommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Program 'Microsoft.Notes.exe' failed to run: Acceso denegado.At line:1 char:1
                     + .\Microsoft.Notes.exe
                     + ~~~~~~~~~~~~~~~~~~~~~.
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type            : System.ComponentModel.Win32Exception
        NativeErrorCode : 5
        ErrorCode       : -2147467259
        TargetSite      :
            Name          : StartWithShellExecuteEx
            DeclaringType : System.Diagnostics.Process
            MemberType    : Method
            Module        : System.Diagnostics.Process.dll
        StackTrace      :
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Management.Automation.NativeCommandProcessor.InitNativeProcess()
        Message         : Acceso denegado.
        Source          : System.Diagnostics.Process
        HResult         : -2147467259
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
FullyQualifiedErrorId : NativeCommandFailed
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : .\Microsoft.Notes.exe
    PositionMessage  : At line:1 char:1
                       + .\Microsoft.Notes.exe
                       + ~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/65634520/135739564-2057b321-ef3c-4296-aa54-c367b8d1ffef.png)

**Comment by jborean93** [comment]
You’re not meant to be running executables from `C:\Program Files\WindowsApps` directly but rather through an AppExecLink usually stored in your user profile. The reason the link is required is because Windows applies special logic to the user token to allow it to run sandboxed applications.

**Comment by rkeithhill** [comment]
I was able to open the Sticky Notes app using:
```
explorer.exe shell:AppsFolder\Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App
```
See this post on how to open store apps from the command line: https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675
