### ISSUE TITLE
Exception thrown when using `Register-CimIndicationEvent`

### ISSUE THREAD

**Issue by CrendKing** [PowerShell/PowerShell#16191]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In a fresh session, run `Register-CimIndicationEvent -Class Win32_ProcessStartTrace -SourceIdentifier $notAVariable`

### Expected behavior

Getting an error like this, because `$notAVariable` does not exist:
```console
Register-CimIndicationEvent: Missing an argument for parameter 'SourceIdentifier'. Specify a parameter of type 'System.String' and try again.
```

### Actual behavior

In v7.1.4, getting this output in a loop:
```console
PS <redacted> >
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.4
OS: Microsoft Windows 10.0.19043
BufferWidth: 316
BufferHeight: 75

Last 26 Keys
 UpArrow UpArrow RightArrow Home Ctrl+Delete Ctrl+Delete Ctrl+Delete Ctrl+Delete Ctrl+Delete l s Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Enter
 UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow Enter


### Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
In the Windows built-in PowerShell v5.1, this output:
```
PS <redacted> >
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 - v Enter
 UpArrow Backspace - Backspace v e r s i o n Enter
 UpArrow Ctrl+Backspace Ctrl+Backspace h e l p Space p o w e r s h e l l Enter
 UpArrow UpArrow Ctrl+Backspace Backspace Backspace Enter
 g e t - v e r s i o n Enter
 s h o w - g e t Tab Tab Ctrl+c g e t - c o m m a n d Space | Space f Space v e r s i o n Enter
 g e t Space Backspace - c o m m a n d Enter
 UpArrow Space | Space s e l e c t - s t r i n g Space v e r s i o n Enter
 g Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace p o w e r Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace s h e Tab Space - Tab Tab Tab Tab Backspace Backspace Tab Tab Tab Space - - Backspace v e r s i o n Enter
 UpArrow Space 1 Enter
 UpArrow Backspace 2 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter


Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
Note that this is reproducible event if Profile.ps1 is completely empty.

### Error details

`Get-Error` doesn't print any output

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> PSReadLine: 2.1.0

Please update to latest version and if the issue persists open new issue in PSReadline repository https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md

**Comment by doctordns** [comment]
I can duplicate this behaviour in 7.1.4 and 7.2.0-preview.10. It also repeats using "Windows Powershell 5.1 (viat Win Terminal).
