### ISSUE TITLE
`Enable-RunspaceDebug -ProcessName` fails on Windows and Unix platforms

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#16270]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open `pwsh`
2. Run the following code
    ```
    Enable-RunspaceDebug -ProcessName powershell
    ```
3. The value to `-ProcessName` could be the name of any process that hosting PowerShell in it.

--------------------------

This is because the debug preference cache file is set to be under the `ProgramFiles` folder, which requires administrator privilege to create and write to the file.
On Unix platforms, the file is set to be under `/bin`, and thus root privilege is required.

https://github.com/PowerShell/PowerShell/blob/b4c5c29dff70f4cf06e60aa0f343a47123f34b37/src/System.Management.Automation/engine/hostifaces/LocalConnection.cs#L366-L367

So now, `Enable-RunspaceDebug -ProcessName powershell` has to be invoked with admin privilege on all platforms in order for it to work. It's not clear to me why the cache file is set to be under the `ProgramFiles` folder, and whether it's really needed.

### Expected behavior

```console
Command ran successful.
```

### Actual behavior

```console
PS:1> Enable-RunspaceDebug -ProcessName powershell
Enable-RunspaceDebug: Failed to persist debug options for Process powershell.


InnerException :
    Type       : System.UnauthorizedAccessException
    Message    : Access to the path 'C:\Program Files\WindowsPowerShell\DebugPreference.clixml' is denied.
```

### Error details

```console
PS:2> Get-Error

Exception             :
    Type           : System.Management.Automation.PSInvalidOperationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Failed to persist debug options for Process powershell.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    Message        : Failed to persist debug options for Process powershell.
    InnerException :
        Type           : System.Management.Automation.CmdletInvocationException
        ErrorRecord    :
            Exception             :
                Type       : System.UnauthorizedAccessException
                TargetSite :
                    Name          : CreateFile
                    DeclaringType : Microsoft.Win32.SafeHandles.SafeFileHandle
                    MemberType    : Method
                    Module        : System.Private.CoreLib.dll
                Message    : Access to the path 'C:\Program Files\WindowsPowerShell\DebugPreference.clixml' is denied.
                Source     : System.Private.CoreLib
                HResult    : -2147024891
                StackTrace :
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
in System.Private.CoreLib.dll:token 0x600011b+0xa1
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64
preallocationSize) in System.Private.CoreLib.dll:token 0x600011a+0x6
   at System.IO.Strategies.WindowsFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options,
Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6005e2a+0x2b
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6005d8c+0x28
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in System.Private.CoreLib.dll:token 0x60059c8+0x0
   at System.Management.Automation.PathUtils.MasterStreamOpen(PSCmdlet cmdlet, String filePath, Encoding resolvedEncoding, Boolean defaultEncoding,
Boolean Append, Boolean Force, Boolean NoClobber, FileStream& fileStream, StreamWriter& streamWriter, FileInfo& readOnlyFileInfo, Boolean
isLiteralPath) in System.Management.Automation.dll:token 0x6004241+0x68
            CategoryInfo          : OpenError: (:) [Export-Clixml], UnauthorizedAccessException
            FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ExportClixmlCommand
            InvocationInfo        :
                MyCommand       : Export-Clixml
                HistoryId       : 1
                InvocationName  : Export-Clixml
                CommandOrigin   : Internal
        TargetSite     :
            Name          : Invoke
            DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.2.0.9, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Access to the path 'C:\Program Files\WindowsPowerShell\DebugPreference.clixml' is denied.
        InnerException :
            Type       : System.UnauthorizedAccessException
            TargetSite :
                Name          : CreateFile
                DeclaringType : Microsoft.Win32.SafeHandles.SafeFileHandle
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : Access to the path 'C:\Program Files\WindowsPowerShell\DebugPreference.clixml' is denied.
            Source     : System.Private.CoreLib
            HResult    : -2147024891
            StackTrace :
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
in System.Private.CoreLib.dll:token 0x600011b+0xa1
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64
preallocationSize) in System.Private.CoreLib.dll:token 0x600011a+0x6
   at System.IO.Strategies.WindowsFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options,
Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6005e2a+0x2b
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6005d8c+0x28
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in System.Private.CoreLib.dll:token 0x60059c8+0x0
   at System.Management.Automation.PathUtils.MasterStreamOpen(PSCmdlet cmdlet, String filePath, Encoding resolvedEncoding, Boolean defaultEncoding,
Boolean Append, Boolean Force, Boolean NoClobber, FileStream& fileStream, StreamWriter& streamWriter, FileInfo& readOnlyFileInfo, Boolean
isLiteralPath) in System.Management.Automation.dll:token 0x6004241+0x68
        Source         : System.Management.Automation
        HResult        : -2146233087
        StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input) in System.Management.Automation.dll:token 0x600537f+0xb0
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke) in
System.Management.Automation.dll:token 0x6006cf2+0x129
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync) in
System.Management.Automation.dll:token 0x6006cf0+0x94
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output,
PSInvocationSettings settings) in System.Management.Automation.dll:token 0x6002821+0xd8
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings
settings) in System.Management.Automation.dll:token 0x6002823+0x1ae
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings) in
System.Management.Automation.dll:token 0x6002820+0x43
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings) in System.Management.Automation.dll:token
0x60027e6+0x5
   at System.Management.Automation.Runspaces.LocalRunspace.SetDebugPreference(String processName, List`1 appDomainName, Boolean enable) in
System.Management.Automation.dll:token 0x60052cb+0x20b
   at Microsoft.PowerShell.Commands.CommonRunspaceCommandBase.SetDebugPreferenceHelper(String processName, String[] appDomainName, Boolean enable,
String fullyQualifiedErrorId) in Microsoft.PowerShell.Commands.Utility.dll:token 0x6000355+0x37
    HResult        : -2146233079
TargetObject          : Microsoft.PowerShell.Commands.EnableRunspaceDebugCommand
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…unspaceDebugCommand:EnableRunspaceDebugCommand) [Enable-RunspaceDebug],
PSInvalidOperationException
FullyQualifiedErrorId : EnableRunspaceDebugCommandPersistDebugPreferenceFailure,Microsoft.PowerShell.Commands.EnableRunspaceDebugCommand
InvocationInfo        :
    MyCommand        : Enable-RunspaceDebug
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Enable-RunspaceDebug -ProcessName powershell
    PositionMessage  : At line:1 char:1
                       + Enable-RunspaceDebug -ProcessName powershell
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Enable-RunspaceDebug
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Animation](https://user-images.githubusercontent.com/127450/137822425-3c2eb993-85c1-4b32-808b-09ae437f6907.gif)

**Comment by daxian-dbw** [comment]
@PaulHigin can you please take a look? Thanks!

**Comment by PaulHigin** [comment]
I am unable to repro this on Windows as the repro steps show.  $env:ProgramFiles is accessible for non-admin users.  I don't recall being involved in writing this code and don't know why programfiles location was chosen for persistence.

**Comment by iSazonov** [comment]
I can confirm original repro. Perhaps @PaulHigin already has the file enabled for writing.
