### ISSUE TITLE
OperationStopped: Incorrect function when running an exe from a mounted ISO

### ISSUE THREAD

**Issue by jeanga** [PowerShell/PowerShell#16293]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

My repro steps:
- Download the Enterprise WDK: https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads
- Mount the ISO (Mount-DiskImage -ImagePath S:\iso\dev\EWDK_fe_release_20348_210507-1500.iso).
- From a "cmd.exe" prompt, run LaunchBuildEnv.cmd amd64
- Start Powershell 7.2 RC1: "c:\Program Files\PowerShell\7-preview\pwsh.exe"
- Run MSBuild.exe

But I do _not_ think this is linked to the EWDK but the fact I'm running a exe from a mounted iso.
(was running just fine with 7.1.5 or the previous 7.2 preview)

### Expected behavior

```console
Successfully run msbuild.exe
```

### Actual behavior

```console
OperationStopped: Incorrect function. : 'E:\Program Files\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin\MSBuild.exe'
```

### Error details

```console
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : GetImmediateLinkTarget
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Incorrect function. : 'E:\Program Files\Microsoft Visual
Studio\2019\BuildTools\\MSBuild\Current\Bin\MSBuild.exe'
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2147024895
    StackTrace :
   at System.IO.FileSystem.GetImmediateLinkTarget(String linkPath, Boolean isDirectory, Boolean throwOnError, Boolean
returnFullPath)
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory)
   at System.IO.File.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget)
   at System.Management.Automation.NativeCommandProcessor.IsWindowsApplication(String fileName)
   at System.Management.Automation.NativeCommandProcessor.InitNativeProcess()
   at System.Management.Automation.NativeCommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections,
FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], IOException
FullyQualifiedErrorId : System.IO.IOException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : msbuild.exe
    PositionMessage  : At line:1 char:1
                       + msbuild.exe
                       + ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-rc.1
PSEdition                      Core
GitCommitId                    7.2.0-rc.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/7120091/138485846-43319be4-5350-4fd2-80bc-28c434fee32d.png)

**Comment by jeanga** [comment]
Verified fixed! Thanks!
