### ISSUE TITLE
Start-PSBootstrap fails on PowerShell 5.1

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#16330]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

*Start-PSBootstrap* fails on PowerShell 5.1 due to use of unsupported type `[System.Management.Automation.SemanticVersion]` in *build.psm1* therefore it is not possible to build latest versions of PowerShell 7 on PowerShell 5.1 anymore.

### Expected behavior

```console
*Start-PSBootstrap* should work on PowerShell 5.1
```

### Actual behavior

```console
*Start-PSBootstrap* throws error on PowerShell 5.1
```

### Error details

```console
Import-Module .\build.psm1
Start-PSBootstrap
Installing PowerShell build dependencies
VERBOSE: Calling Find-Dotnet from Start-PSBootstrap
VERBOSE: In Find-DotNet
ForEach-Object : Unable to find type [System.Management.Automation.SemanticVersion].
At D:\DEVELOPMENT\PowerShellCore\build.psm1:2106 char:81
+ ... *\.\d*)?' | ForEach-Object { [System.Management.Automation.SemanticVe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...SemanticVersion:TypeName) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand

$error[0]|fl * -force


PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: Unable to find type [System.Management.Automation.SemanticVersion].
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
                        variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                        Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object
                        input, Object scriptThis, Object[] args)
                           at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : System.Management.Automation.SemanticVersion
CategoryInfo          : InvalidOperation: (System.Manageme...SemanticVersion:TypeName) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2106
                        at <ScriptBlock>, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2106
                        at script:Start-NativeExecution, D:\DEVELOPMENT\PowerShellCore\tools\buildCommon\startNativeExecution.ps1: line 22
                        at Get-LatestInstalledSDK, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2105
                        at Find-Dotnet, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2259
                        at Start-PSBootstrap, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2054
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![image](https://user-images.githubusercontent.com/16168755/139390916-5cd1816c-28bb-47dd-8c8a-08c68f234815.png)

**Comment by TravisEz13** [comment]
Personally, I think the minimum for development should be the last LTS.  5.1 is just not viable feature wise.  rewriting this functionality in 5.1 is a duplication of effort.    I think the other option is for start-psbootstrap to tell you, move to PowerShell 7 or bootstrap manually (possibly only that portion).  But I just wrote something that will be required and requires the same semanticVersion sorting which didn't exist in 5.1.

Marking for maintainer review.

**Comment by iSazonov** [comment]
It was too unexpected to find that the module did not work. I personally do not ready to switch completely to pwsh in my work (there are still many places where powershell has no alternative to pwsh).

**Comment by TravisEz13** [comment]
adding @SteveL-MSFT

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-maintainers have a consensus that PowerShell 7 is stable enough to be used for development of PowerShell. It would require a lot of effort to ensure Windows PowerShell 5.1 compatibility, which we think is unnecessary. We propose to add `#requires -version 7` to build.psm1.
