### ISSUE TITLE
Unable to load binary module in 7.2.0

### ISSUE THREAD

**Issue by chscott** [PowerShell/PowerShell#16474]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
C:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

C:\Temp> Import-Module -Name '.\MyModule.dll' -Verbose
VERBOSE: Loading module from path 'C:\Temp\MyModule.dll'.
```

```
C:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

C:\Temp> Import-Module -Name '.\MyModule.dll' -Verbose
VERBOSE: Loading module from path 'C:\Temp\MyModule.dll'.
Import-Module: The type initializer for '<Module>' threw an exception.
```

[MyModule.zip](https://github.com/PowerShell/PowerShell/files/7540667/MyModule.zip)

### Expected behavior

```console
The module should load in 7.2.0.
```

### Actual behavior

```console
Import-Module: The type initializer for '<Module>' threw an exception.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Can you post the full error (e.g. `Get-Error`) and what `MyModule` is?

**Comment by chscott** [comment]
> Can you post the full error (e.g. `Get-Error`) and what `MyModule` is?

Get-Error output is below. This is a proprietary module my company markets, though this is a reduced version for demonstration purposes. The full version has the same problem.

We write the code in PowerShell syntax and then use a product called [PSProtector](https://www.psprotector.com/) to compile that down into a DLL. This has always worked great, but it breaks in 7.2.0. I'm not sure if the problem is on their side or here, so I've reported it in both places.

```
C:\Temp> Get-Error

Exception             :
    Type           : System.TypeInitializationException
    TypeName       : <Module>
    TargetSite     :
        Name          : GetActivationInfo
        DeclaringType : System.RuntimeTypeHandle
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message        : The type initializer for '<Module>' threw an exception.
    InnerException :
        Type           : System.TypeInitializationException
        TypeName       : TMCTools.BitmapDictionary
        TargetSite     :
            Name          : ClearTemplate
            DeclaringType : TMCTools.BitmapDictionary, TMCTools, Version=1.0.828.0, Culture=neutral, PublicKeyToken=null
            MemberType    : Method
            Module        : TMCTools.dll
        Message        : The type initializer for 'TMCTools.BitmapDictionary' threw an exception.
        InnerException :
            Type           : System.BadImageFormatException
            Message        : Could not load file or assembly 'TMCTools&, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect
format.
            FileName       : TMCTools&, Culture=neutral, PublicKeyToken=null
            TargetSite     :
                Name          : InternalLoad
                DeclaringType : System.Reflection.RuntimeAssembly, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            InnerException :
                Type       : System.BadImageFormatException
                Message    : Bad IL format.
                TargetSite :
                    Name          : InternalLoad
                    DeclaringType : System.Runtime.Loader.AssemblyLoadContext
                    MemberType    : Method
                    Module        : System.Private.CoreLib.dll
                Source     : System.Private.CoreLib
                HResult    : -2147024885
                StackTrace :
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at TMCTools.BitmapDictionary.ClearTemplate(Object rootValues, ResolveEventArgs lastQuery)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
            Source         : System.Private.CoreLib
            HResult        : -2147024885
            StackTrace     :
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean
throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean
throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at TMCTools.BitmapDictionary..cctor()
        Source         : TMCTools
        HResult        : -2146233036
        StackTrace     :
   at TMCTools.BitmapDictionary.ClearTemplate()
   at .cctor()
    Source         : System.Private.CoreLib
    HResult        : -2146233036
    StackTrace     :
   at System.RuntimeTypeHandle.GetActivationInfo(ObjectHandleOnStack pRuntimeType, (fnptr)* ppfnAllocator, Void** pvAllocatorFirstArg, (fnptr)* ppfnCtor, BOOL*
pfCtorIsPublic)
   at System.RuntimeTypeHandle.GetActivationInfo(RuntimeType rt, (fnptr)& pfnAllocator, Void*& vAllocatorFirstArg, (fnptr)& pfnCtor, Boolean& ctorIsPublic)
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, IEnumerable`1 assemblyTypes)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo
moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo,
Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String
moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean&
found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object
privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Import-Module], TypeInitializationException
FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Import-Module -Name '.\MyModule.dll' -Verbose
    PositionMessage  : At line:1 char:1
                       + Import-Module -Name '.\MyModule.dll' -Verbose
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by SeeminglyScience** [comment]
> `Could not load file or assembly 'TMCTools&, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect
format.`

Looks like it's trying to load a native lib with the wrong target architecture.  Can you verify that you installed 7.2 with the same bitness you installed 7.1.5?

**Comment by chscott** [comment]
> Looks like it's trying to load a native lib with the wrong target architecture (well, the error can mean other things but it's commonly this). Can you verify that you installed 7.2 with the same bitness you installed 7.1.5?

I'm alternating between installing these:

- PowerShell-7.2.0-win-x64.msi
- PowerShell-7.1.5-win-x64.msi

**Comment by SeeminglyScience** [comment]
Then it's probably something they need to fix. It's likely that their obfuscation relies on an implementation detail in how CLI metadata is loaded which may have changed.  Ah especially with a `Bad IL format.` error I didn't see at first glance.

**Comment by daxian-dbw** [comment]
By looking at the code within ILSpy, the failure happens when the code tries to load a resource satellite assembly (TMCTools&) from the imbedded resource stream of the module dll. The relevant code snippet is as follows:

```c#
// From BitmapDictionary.ClearTemplate()
Stream manifestResourceStream = executingAssembly.GetManifestResourceStream(text);
byte[] rawAssembly = ResourceTable.ClearTemplate(97L, manifestResourceStream);
return Assembly.Load(rawAssembly);
```
So yeah, it's likely the code depends on an implementation detail that may have changed in .NET 6, and the tool owner need to investigate further. The weird thing is, `97L` is passed to `ResourceTable.ClearTemplate` but is never used anywhere in the actual implementation of that method.
