### ISSUE TITLE
Update-Help error PowerShell 7.2.0

### ISSUE THREAD

**Issue by guidovbrakel** [PowerShell/PowerShell#16499]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running Update-Help

### Expected behavior

```console
Running update-help
```

### Actual behavior

```console
Error
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.PowerShell.Common.Share, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Azure.PowerShell.Common.Share, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictor.OnCommandLineAccepted(PredictionClient client, IReadOnlyList`1 history)
   at System.Management.Automation.Subsystem.Prediction.CommandPrediction.<>c__DisplayClass2_0.<OnCommandLineAccepted>b__1(ICommandPredictor predictor)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[process exited with code 3762504530]
```

### Error details

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.PowerShell.Common.Share, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Azure.PowerShell.Common.Share, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictor.OnCommandLineAccepted(PredictionClient client, IReadOnlyList`1 history)
   at System.Management.Automation.Subsystem.Prediction.CommandPrediction.<>c__DisplayClass2_0.<OnCommandLineAccepted>b__1(ICommandPredictor predictor)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[process exited with code 3762504530]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22504
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by guidovbrakel** [comment]
I fixed it myself, by saving all the Az modules in C:\Program Files\PowerShell\7\Modules
