### ISSUE TITLE
Pwsh crashing with Not enough quota is available to process this command

### ISSUE THREAD

**Issue by stej** [PowerShell/PowerShell#16518]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Pwsh crashes with this error:

```
Application: pwsh.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception (1816): Not enough quota is available to process this command.
   at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

It happens mainly when I call some external native commands (Julia script), but I'm not sure whether it's related.

How it behaves:
 - In ConEmu: the tab simply disappears
 - In Windows terminal: the message about the quota is shown in the window and the promp disappears. I can only close the tab munually. Nothing else.
The pwsh in 

### Expected behavior

```console
No crash..
```

### Actual behavior

```console
Crashing.
```

### Error details

```console
I experienced this problem in Windows Terminal, so I switched to ConEmu and it's still happening.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/253560/143466956-471fe723-cb5e-4777-bdf0-650a269dd533.png)

**Comment by daxian-dbw** [comment]
@stej Can you please share the specific script/command you ran that triggered this crash?
The event and the call stacks suggest the exception was thrown from the .NET runtime.

If you are able to consistently reproduce the issue, can you please collect a crash dump by following the instructions from https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps#collect-dumps-on-crash?
Please use `MiniDumpWithFullMemory` as the dump type, by setting `DOTNET_DbgMiniDumpType` to `4`.

**Comment by stej** [comment]
Sure, I'll try. Meanwhile the command line looks like this:

```
cls; $f='c:\temp\values.csv';$pre=[float](Import-Csv $f)[-1].Total; C:\util-setdateToCurrent.ps1 ; C:\temp\runDownloadsAndAnalysis.bat; $post=[float](Import-Csv $f)[-1].Total; $diff="Difference: $([int]($post-$pre))`$"; if ($diff -match ' -') { Show-Warning $diff } else { Show-Info $diff }
```
(one line). 
Where 
- `util-setdateToCurrent.ps1` calls Set-Date with some time
- `runDownloadsAndAnalysis.bat` - calling pwsh (creates new process), so I don't think it's causing the problem
- `Show-Warning` and `Show-Info` - this is my bet.

The body:
```
function Show-WpfMessage($title, $str, $headingBackColor, $messageBackColor, $messageColor, $height, $width)
{
  Add-Type -Assembly PresentationFramework
  Add-Type -Assembly PresentationCore
  $xaml = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  Title="$title" Height="$height" Width="$width"
  Opacity="10" OpacityMask="Green" 
  Topmost="True" WindowStyle="None" AllowsTransparency="True" Background="Transparent" Padding="20" Top="10" Left="10">
  <DockPanel>
    <Border DockPanel.Dock="Top" CornerRadius="10" BorderThickness="2" BorderBrush="Black" Background="$headingBackColor"
      Padding="8" Margin="10">
      <TextBlock FontSize="52" TextWrapping="Wrap" Margin="20" HorizontalAlignment="Center">$title</TextBlock>
    </Border>
    <Border DockPanel.Dock="Bottom" CornerRadius="10" BorderThickness="1" BorderBrush="Black"
      Padding="8" Margin="10" Background="$messageBackColor">
      <TextBlock Foreground="$messageColor" FontSize="42" Padding="60" TextWrapping="Wrap" HorizontalAlignment="Center">$str</TextBlock>
    </Border>
  </DockPanel>
</Window>
"@

  $global:window = [Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader ([Xml]$xaml ) ) )
  $window.Add_MouseLeftButtonDown(  { $_.Handled = $true; $window.DragMove() } )
  $window.Add_MouseRightButtonDown( { $_.Handled = $true; $window.Close()   } )
  $window.ShowDialog()
}

function Show-Info($str) {
  Show-WpfMessage "Information" $str -headingBackColor LightBlue -messageBackColor White -messageColor Black 400 800
}
function Show-Warning($str) {
  Show-WpfMessage "Warning" $str -headingBackColor Yellow -messageBackColor Red -messageColor Black 600 1200
}

```
