### ISSUE TITLE
`Object[]` should cast to `IEnumerable[<>]`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16538]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am not quiet sure about this, but I would expect PowerShell to cast an object array (`Object[]`) automatically to a specific `IEnumerable`. The issue occurred to me when I was trying the **`InvariantCultureIgnoreCase`** [`HashSet`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1) and immediately populate it in a single statement:

```PowerShell
[System.Collections.Generic.HashSet[String]]::new(@('a', 'b', 'c', 'A', 'b'), [StringComparer]::InvariantCultureIgnoreCase)
```

To workaround this you will need specify the array item type (`[string[]]`):
```PowerShell
[System.Collections.Generic.HashSet[String]]::new([String[]]@('a', 'b', 'c', 'A', 'b'), [StringComparer]::InvariantCultureIgnoreCase)
```

This is probably related to the fact that I can't directly cast to a specific enumerable either:
```PowerShell
[System.Collections.Generic.IEnumerable[String]]@('a', 'b', 'c', 'A', 'b')
InvalidArgument: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Collections.Generic.IEnumerable`1[System.String]".
```

But this works:
```PowerShell
[System.Collections.Generic.IEnumerable[String]][String[]]@('a', 'b', 'c', 'A', 'b')
a
b
c
A
b
```

Related:
* [`#16002` IEnumerable -property values should enumerate](https://github.com/PowerShell/PowerShell/issues/16002)
* [`#16003` Accelerate HashSet](https://github.com/PowerShell/PowerShell/issues/16003)

### Expected behavior

```console
a
b
c
```

### Actual behavior

```console
MethodException: Cannot find an overload for "new" and the argument count: "2".
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.MethodException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find an overload for "new" and the argument count: "2".
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodCountCouldNotFindBest
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : [System.Collections.Generic.HashSet[String]]::new(@('a', 'b', 'c', 'A', 'b'), [StringComparer]::InvariantCultureIgnoreCase)
            PositionMessage  : At line:1 char:1
                               + [System.Collections.Generic.HashSet[String]]::new(@('a', 'b', 'c', 'A …
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Object[], System.StringComparer)
    Message     : Cannot find an overload for "new" and the argument count: "2".
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure , CallSite , Type , Object[] , StringComparer )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [System.Collections.Generic.HashSet[String]]::new(@('a', 'b', 'c', 'A', 'b'), [StringComparer]::InvariantCultureIgnoreCase)
    PositionMessage  : At line:1 char:1
                       + [System.Collections.Generic.HashSet[String]]::new(@('a', 'b', 'c', 'A …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Also related: #7651

**Comment by SeeminglyScience** [comment]
The Engine-WG discussed this last night and we agree that casting should be aware of a few key interfaces and how to translate them.

The big ones I can see being necessary for a first round is:
| Interface | Fallback |
|---|---|
|`IList<T>`|`T[]`|
|`ICollection<T>`|`T[]`|
|`IEnumerable<T>`|`T[]`|
|`IReadOnlyList<T>`|`T[]`|
|`IReadOnlyCollection<T>`|`T[]`|
| Less important |
|`IList`|`object[]`|
|`ICollection`|`object[]`|
|`IEnumerable`|`object[]`|
|`IDictionary`|`Hashtable`|
|`IDictionary<TKey, TValue>`|`Dictionary<TKey, TValue>`|

Marking up for grabs.

**Comment by iRon7** [comment]
This is already labeled <kbd>Up-for-Graps</kbd> and therefore shouldn't be closed.

**Comment by iRon7** [comment]
This is already labeled <kbd>Up-for-Graps</kbd> and therefore shouldn't be closed. Or???

**Comment by iRon7** [comment]
The issue still exist in:

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Besides the issue is already defined as <kbd>Up-for-Grabs</kbd>

**Comment by iRon7** [comment]
This bug was already qualified for <kbd>Up-for-Grabs</kbd> and still exist on PowerShell version: `7.5.1`

**Comment by iRon7** [comment]
The issue still exists in PowerShell `7.6.2`
