### ISSUE TITLE
System.Data.SqlClient.SqlCommand crashes Powershell session using "Integrated Security=True" on Linux-Container (not joined to a domain)

### ISSUE THREAD

**Issue by danubie** [PowerShell/PowerShell#16567]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm running PS Core on a Ubuntu container which is not domain joined.
When (accidentally) configuring a connection string having "...;Integrated Security=True" the PS-session crashes.

```
	$SqlCmd = New-Object  System.Data.SqlClient.SqlCommand
	$SqlCmd.CommandType = [System.Data.CommandType]::Text
	$SqlCmd.Connection = "server=**servername**;database=**database**;Integrated Security=True"
	$SqlCmd.CommandText = "select 1"
	$SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter($SqlCmd)
	$DataSet = New-Object System.Data.DataSet
	[Void] $SqlAdapter.Fill($DataSet)
	$SqlCmd.Connection.Close()
	$DataSet
```

### Expected behavior

```console
Thowing an exception like when user is unknown

MethodInvocationException: /workspace/test/bugreport.ps1:7:2
Line |
   7 |      [Void] $SqlAdapter.Fill($DataSet)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Fill" with "1" argument(s): "Login failed for user 'unknown'."
```
```


### Actual behavior

```console
The PS-Session crashes immediately
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Image: mcr.microsoft.com/powershell:ubuntu-18.04
```

**Comment by iSazonov** [comment]
@danubie Can you create simple C# app to test the scenario? If you could catch the exception this.

**Comment by daxian-dbw** [comment]
@danubie What error message or exit code did you get when pwsh crashed?

If you are able to consistently reproduce the issue, can you please collect a crash dump by following the instructions from https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps#collect-dumps-on-crash?
Please use `MiniDumpWithFullMemory` as the dump type, by setting `DOTNET_DbgMiniDumpType` to `4`.

**Comment by danubie** [comment]
@iSazonov 
I narrowed it down a bit. The error is on opening the SQLConnection. The exception can not be caught in Powershell.
```
$SqlConnection = New-Object  System.Data.SqlClient.SqlConnection
$SqlConnection.Connectionstring = "server=***server***;database=***database***;Integrated Security=True"
$SqlConnection.Open()   # <<< kills the session
```
Here ist the corresponding C# program I've done. The exception can be caught. This is the version without try/catch.
BTW: This was my first experience with C# on Linux :-)
```
namespace BugReport
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            SqlConnection sqlConnection = new SqlConnection();
            sqlConnection.ConnectionString = "server=***server***;database=***database***;Integrated Security=True";
            sqlConnection.Open();
            sqlConnection.Close();
            Console.WriteLine("We are done!");
        }
    }
}
```
Output:
```
root@7fb3e1fffd2a:/workspace/hello# dotnet BugReport.dll console -o
Hello World!
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, ChannelBinding channelBinding, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Boolean& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, ChannelBinding channelBinding, String targetName, ContextFlagsPal inFlags, Byte[] incomingBlob, Byte[]& resultBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at BugReport.Program.Main(String[] args) in C:\Users\WagnerW\source\repos\BugReport\BugReport\Program.cs:line 14
ClientConnectionId:32487f75-f6ac-414a-8724-fb0cda06a0dd
Aborted
```
@daxian-dbw : I'll try to mange the dump within the next days

**Comment by iSazonov** [comment]
> The exception can not be caught in Powershell.

@danubie Thanks for your investigations! Have you tried try-catch in the script?

**Comment by danubie** [comment]
Yes, but it does not catch. It still Crashs.

**Comment by ajansveld** [comment]
@danubie Does the following show a 139 exit code when run from bash or pwsh (substituting your server name)?

```
pwsh -NoProfile -Command "[System.Data.SqlClient.SqlConnection]::new('server=***server***;database=***database***;Integrated Security=True').Open()"

echo $? $LASTEXITCODE
```

**Comment by danubie** [comment]
Your estimation is correct
```
root@7fb3e1fffd2a:/workspace# pwsh -NoProfile -Command "[System.Data.SqlClient.SqlConnection]::new('server=***;database=***;Integrated Security=True').Open()"
Segmentation fault

root@7fb3e1fffd2a:/workspace# echo $? $LASTEXITCODE
139
```

**Comment by ajansveld** [comment]
Ok, then I think we are dealing with this issue: https://github.com/dotnet/SqlClient/issues/1390.

**Comment by daxian-dbw** [comment]
I think we may need to do a servicing release for 7.2.0 when .NET 6.0.2 comes out in Feb 2022. /cc @TravisEz13 @adityapatwardhan @anmenaga @PaulHigin
