### ISSUE TITLE
PWSH 7.2.1: System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'Provider'.

### ISSUE THREAD

**Issue by penalvch** [PowerShell/PowerShell#16670]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running $test.ps1 as part of a scheduled task via an administrative user intermittently shows the below error.
I've never been able to reproduce the problem by executing the $test.ps1 script in Visual Studio Code, opening PWSH from Start > Run As Administrator, etc.
It seems correlated to when the computer is under heavy usage of memory and CPU, which may be part of the perceived non-deterministism.
Computer has latest drivers, BIOS, firmware, and updates applied, with AV turned off.

$test.ps1
```
. c:\scripts\check.ps1
```

check.ps1
```
try{
    $null=import-module -name PackageManagement,powershellget
    if((get-installedmodule -name simplysql -ea 0).count -eq 0){
        $null=(install-module -acceptlicense -name SimplySql -scope currentuser)
    }
}catch{
    $ei_h=$_
    $ge_h=get-error
    $exception_h=$ei_h.Exception
    $line_h=$ei_h.InvocationInfo.ScriptLineNumber
    $msg_h=$ei_h.Message 
    $stringerr_h=-join('Error. Investigate.',"`n",'$line_h=',$line_h,"`n",'$exception_h=',"`n",$exception_h,"`n",'$msg_h=',"`n",$msg_h,"`n",'get-error=',"`n",$ge_h)
    $mtoday_h=get-date -uformat '%Y%m%d%H%M'
    $problem_h="$env:userprofile\$mtoday_h-problem.txt"
    $streamp_h=[System.IO.StreamWriter]$problem_h
    $streamp_h.write($stringerr_h)
    $streamp_h.close()
    exit 1
}
```

test.xml
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2021-12-22T16:06:10.889206</Date>
    <Author>TEST\admin</Author>
    <URI>\test\test</URI>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2021-12-23T04:01:00-05:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-4026033148-167229773-3407019803-1001</UserId>
      <LogonType>Password</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>pwsh.exe</Command>
      <Arguments>-nologo -windowstyle hidden -ExecutionPolicy Bypass -command ". c:\scripts\test.ps1; exit $LASTEXITCODE"</Arguments>
      <WorkingDirectory>c:\scripts</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
```

### Expected behavior

```console
$null=import-module -name PackageManagement,powershellget
>> if((get-installedmodule -name simplysql -ea 0).count -eq 0){
>>     $null=(install-module -acceptlicense -name SimplySql -scope currentuser)
>> }
PS C:\Windows\System32>
```

### Actual behavior

```console
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'Provider'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Get-InstalledModule<Process>(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

### Error details

```console
A parameter cannot be found that matches parameter name 'Provider'.
```

### Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@penalvch Get-InstalledModule cmdlet is in PowerShellGet repository. So please open new issue there to start investigations.

**Comment by penalvch** [comment]
@iSazonov, thanks for the info!
