### ISSUE TITLE
PowerShell: 7.2.1 can't run 

### ISSUE THREAD

**Issue by lovekyrie** [PowerShell/PowerShell#16687]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell: 7.2.1 can't use

### Expected behavior

```console
see Error and Environment
```

### Actual behavior

```console
see Error and Environment
```

### Error details

```console
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Environment data

```powershell
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

**Comment by iSazonov** [comment]
You should install latest PSReadLine beta.
