### ISSUE TITLE
Remoting over SSH: Multiple issues with the SSHConnection parameter

### ISSUE THREAD

**Issue by anttiah** [PowerShell/PowerShell#16684]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Remoting cmdlets that support the SSHConnection hash table parameter fail to create session if in the hash table:
`KeyFilePath` is specified using tilde syntax, e.g. `~/.ssh/id_myidentity` instead of full path of the file.
or
`ConnectingTimeout` is not specified.

Steps to reproduce using tilde syntax in the `KeyFilePath`, regardless of `ConnectingTimeout` existence or value:
```
PS /home/user> New-PSSession -SSHConnection @{
    HostName    = 'x.x.x.x'
    Port        = yyyyy
    UserName    = 'administrator'
    KeyFilePath = '~/.ssh/id_myidentity'
}
New-PSSession: [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.
```

Steps to reproduce using full path syntax in the `KeyFilePath` and without specifying `ConnectingTimeout`:
```
PS /home/user> New-PSSession -SSHConnection @{
    HostName    = 'x.x.x.x'
    Port        = yyyyy
    UserName    = 'administrator'
    KeyFilePath = '/home/user/.ssh/id_myidentity'
}
New-PSSession: [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.
```

Command works only when using both full path syntax in the `KeyFilePath` and `ConnectingTimeout` value of `-1` (or something large enough): 
```
PS /home/user> New-PSSession -SSHConnection @{
    HostName          = 'x.x.x.x'
    Port              = yyyyy
    UserName          = 'administrator'
    KeyFilePath       = '/home/user/.ssh/id_myidentity'
    ConnectingTimeout = -1
}
 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
 39 Runspace38      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available
```

Splatting the hash table also seem to work regardless of the `KeyFilePath` syntax or `ConnectingTimeout` value:
```
PS /home/user1> $sshparams = @{
    HostName    = 'x.x.x.x'
    Port        = yyyyy
    UserName    = 'administrator'
    KeyFilePath = '~/.ssh/id_myidentity'
}
PS /home/user1> New-PSSession @sshparams

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
 47 Runspace46      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available
```

### Expected behavior

```console
Connection succeeds with KeyFilePath tilde syntax and without specifying ConnectingTimeout.
```

### Actual behavior

```console
New-PSSession: [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.

# Or

New-PSSession: [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.
```

### Error details

```console
###############################################################################
# Error when using tilde syntax in the KeyFilePath, regardless of ConnectingTimeout existence or value:

Exception             :
    Type           : System.Management.Automation.Remoting.PSRemotingDataStructureException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : An error has occurred which PowerShell cannot handle. A remote session might have ended.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
    Message        : An error has occurred which PowerShell cannot handle. A remote session might have ended.
    InnerException :
        Type       : System.IO.FileNotFoundException
        Message    : The specified key file ~/.ssh/id_myidentity was not found.
        TargetSite :
            Name          : StartSSHProcess
            DeclaringType : System.Management.Automation.Runspaces.SSHConnectionInfo
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Source     : System.Management.Automation
        HResult    : -2147024894
        StackTrace :
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
    HResult        : -2146233087
TargetObject          : System.Management.Automation.RemoteRunspace
CategoryInfo          : OpenError: (System.Management.A…tion.RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingDataStructureException
FullyQualifiedErrorId : PSSessionOpenFailed
ErrorDetails          : [x.x.x.x] An error has occurred which PowerShell cannot handle. A remote session might have ended.
InvocationInfo        :
    MyCommand        : New-PSSession
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 61
    Line             : New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyy; UserName = 'administrator'; KeyFilePath =
'~/.ssh/id_myidentity'; ConnectingTimeout = -1}
    PositionMessage  : At line:1 char:1
                       + New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yy …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-PSSession
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :



###############################################################################
# Error when using full path syntax in the KeyFilePath and without specifying ConnectingTimeout:

Exception             :
    Type        : System.Management.Automation.Remoting.PSRemotingTransportException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : SSH connection attempt failed after time out: 0 seconds.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
    Message     : SSH connection attempt failed after time out: 0 seconds.
    HResult     : -2146233087
TargetObject          : System.Management.Automation.RemoteRunspace
CategoryInfo          : OpenError: (System.Management.A…tion.RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
FullyQualifiedErrorId : PSSessionOpenFailed
ErrorDetails          : [x.x.x.x] SSH connection attempt failed after time out: 0 seconds.
InvocationInfo        :
    MyCommand        : New-PSSession
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 63
    Line             : New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath =
'/home/user/.ssh/id_myidentity'}
    PositionMessage  : At line:1 char:1
                       + New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yy …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-PSSession
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
```
Get-Content -ReadCount 0 @{
	LiteralPath = 'd:\h.txt'
} # error
Get-Content -ReadCount 0 -LiteralPath 'd:\h.txt' #normal

Get-FileHash -Algorithm sha1 @{
	LiteralPath = 'd:\h.txt'
} #error
Get-FileHash -Algorithm sha1 -LiteralPath 'd:\h.txt' #normal
```
**Obviously, the powershell parsing engine is not designed in the way you understand the grammar.**
You should not expect powershell to parse the "~" in the string. If you want to do this, use Resolve-Path,eg: 
KeyFilePath = Resolve-Path -path '~/.ssh/id_myidentity'

**Comment by anttiah** [comment]
Just noticed that result depens on the order the hash table keys are processed.
Unordered hash table fails:
```
New-PSSession -SSHConnection @{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath = '/home/user/.ssh/id_myidentity'; ConnectingTimeout = -1}
New-PSSession: [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to host x.x.x.x port 22: Connection timed out.
```

While ordered works:
```
New-PSSession -SSHConnection ([ordered]@{HostName = 'x.x.x.x'; Port = yyyyy; UserName = 'administrator'; KeyFilePath = '/home/user/.ssh/id_myidentity'; ConnectingTimeout = -1})

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
 77 Runspace76      SSH       x.x.x.x         RemoteMachine   Opened        DefaultShell             Available
```

No wonder this was so hard to investigate. Root cause has probably been around for a while because this is not the first bug report on the `-SSHConnection` hash table.

**Comment by anttiah** [comment]
Ok, did more tests and there is definitely something wrong with how the hash table is processed.

This is my test setup. First I created a simple PowerShell script:
```
# sessiontest.ps1
New-PSSession -SSHConnection @{
    Port              = 2222
    UserName          = 'administrator'
    HostName          = 'x.x.x.x'
    KeyFilePath       = '/home/user/.ssh/id_myidentity'
    ConnectingTimeout = 30000    # 30 seconds
} -PipelineVariable session | Write-Verbose -Message {"We got session $_"} -Verbose | Remove-PSSession -Session {$session}
```
Then I ran the script 10 times from Bash command line:
`for i in {1..10}; do echo "Loop ${i}:"; pwsh -file ~/sessiontest.ps1; done`

**Expected result**
`New-PSSession` command succeeds every time.
```
Loop 1:
VERBOSE: We got session [PSSession]Runspace1
...
Loop 10:
VERBOSE: We got session [PSSession]Runspace1
```

**Actual result**
`New-PSSession` command fails randomly. Based on the error message some of the hash table keys had no effect or got replaced with default value. In this sample, only loop 3 successfully connected, while loops 1,2,4,5,6,7,8,10 failed due to wrong port, and loop 9 failed due to wrong identity. Repeated executions of the bash command gave similar results but with different loops failing every time.
```
Loop 1:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 2:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 3:
VERBOSE: We got session [PSSession]Runspace1
Loop 4:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 5:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 6:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 7:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 8:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.

Loop 9:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message:
     | user@x.x.x.x: Permission denied (publickey)..

Loop 10:
New-PSSession: /home/user/sessiontest.ps1:1
Line |
   1 |  New-PSSession -SSHConnection @{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [x.x.x.x] The background process reported an error with the following message: The SSH client session has ended with error message: ssh: connect to
     | host x.x.x.x port 22: Connection timed out.
```
Finally, I ran the same setup from my WSL2 Ubuntu w/ PowerShell 7.2.1 against another server and results were just as random as with the original system.

**Comment by E3V3A** [comment]
Looks to me like the `Port = 2222` is ignored. 
Alternatively I suggest you to change the port for each connection, or restart your sshd after each connection, or close the connection, depending on how many sessions you allow in your sshd.

**Comment by anttiah** [comment]
> Looks to me like the `Port = 2222` is ignored. Alternatively I suggest you to change the port for each connection, or restart your sshd after each connection, or close the connection, depending on how many sessions you allow in your sshd. Also put a 3 sec sleep in your loop.

As you can see from my previous comment, https://github.com/PowerShell/PowerShell/issues/16684#issuecomment-1004209585, failure is random. Based on my small sample, it seems to be weighted towards `Port` being ignored but there is also one failure caused by ignored `KeyFilePath`.

The test was run from outside `pwsh` using `bash`'s loop syntax. Thus, new `pwsh` process was started for each iteration and exited immediately after. The PowerShell portion of the test also removed each successfull connection before exiting.

The server I'm testing this on can handle 100+ outbound ssh connections without issues. I've ran lots of PowerShell commands against large groups of servers simultaneously using splatting syntax with the same hash table and it works just fine.

And let's not forget the timeout issue. In the hash table the `ConnectingTimeout` must be explicitly defined to be non-zero or the connection will fail immediately due to default timeout being 0 milliseconds.

**Comment by E3V3A** [comment]
What if you use: 
`for i in {1..10}; do echo "Loop ${i}:"; $(pwsh -nop -nol -file ~/sessiontest.ps1); sleep 2; done`

**Comment by anttiah** [comment]
If it were about concurrent ssh sessions, then the first iteration should succeed. But it doesn't. It fails randomly. Please note that the bash loop in my example is for demonstration purposes only. I originally discovered this issue when trying to manage multiple servers (one ssh connection per server) and the `New-PSSession -SSHConnection $arrayofhashtables` command kept failing while the same commad with splatting syntax never failed even when there were dozens of active connections.

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group agrees that the KeyFilePath parameter should try PowerShell path resolution before throwing the 'not found' error.
