### ISSUE TITLE
Unhandled exception. System.Management.Automation.Runspaces.PSSnapInException: System error.

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [PowerShell/PowerShell#16694]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```c#
using System;
using System.Management.Automation;

namespace TestCore
{
    class Program
    {
        static void Main(string[] args)
        {
            using (PowerShell ps = PowerShell.Create())
            {
                var results = ps.AddScript("Get-NetTCPConnection").Invoke();
                Console.WriteLine(results[0].ToString());
                Console.WriteLine(ps.Streams.Error);
                ps.Commands.Clear();
            }
        }
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System">
      <HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Management.Automation">
      <HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Management.Automation.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

```powershell
&"$env:localappdata\microsoft\dotnet\dotnet" publish -r win10-x64 --self-contained=true /p:PublishSingleFile=true --configuration Debug
TestCore\bin\Debug\net6.0\win10-x64\publish\TestCore.exe
```

I am pretty sure that this initial error may be related to missing library references? 
I also read https://github.com/PowerShell/PowerShell/issues/13013 where @iSazonov said
> Get-NetTCPConnection is not in the repository. Use UserVoice site to send your request to MSFT owner team.

Okay, doing the same in `..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\pwsh -ep bypass`:
```powershell
Get-NetTCPConnection

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
...
```

What is the problem here?

### Expected behavior

```console
something like

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
...
```

### Actual behavior
with 2 libs
```console
Unhandled exception. System.Management.Automation.Runspaces.PSSnapInException: System error.
   at System.Management.Automation.Runspaces.PSSnapInHelpers.LoadPSSnapInAssembly(PSSnapInInfo psSnapInInfo) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\InitialSessionState.cs:line 5014
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\InitialSessionState.cs:line 3877
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault() in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\InitialSessionState.cs:line 1512
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\ConnectionFactory.cs:line 68
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace() in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\ConnectionFactory.cs:line 45
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 5466
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 4596
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 4788
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 4536
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings) in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 2431
   at System.Management.Automation.PowerShell.Invoke() in C:\Users\test\source\repos\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs:line 2308
   at TestCore.Program.Main(String[] args) in C:\users\test\source\repos\TestCore\TestCore\Program.cs:line 12
```

With the following additional libs (wild guesses - basically randomly chosen)
```csproj
		<Reference Include="Microsoft.Management.Infrastructure">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.Management.Infrastructure.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.WSMan.Management">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.WSMan.Management.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.CodeAnalysis.CSharp">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.CodeAnalysis">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.CodeAnalysis.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.Commands.Diagnostics">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.Commands.Diagnostics.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.Commands.Management">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.Commands.Management.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.Commands.Utility">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.Commands.Utility.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.ConsoleHost">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.ConsoleHost.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.CoreCLR.Eventing">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.CoreCLR.Eventing.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.MarkdownRender">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.MarkdownRender.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.PowerShell.Security">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.PowerShell.Security.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Win32.Registry">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.Win32.Registry.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.WSMan.Runtime">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Microsoft.WSMan.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="NJsonSchema">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\NJsonSchema.dll</HintPath>
		</Reference>
		<Reference Include="System.Diagnostics.EventLog">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Diagnostics.EventLog.dll</HintPath>
		</Reference>
		<Reference Include="System.Drawing.Common">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Drawing.Common.dll</HintPath>
		</Reference>
		<Reference Include="System.IO.FileSystem.AccessControl">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.IO.FileSystem.AccessControl.dll</HintPath>
		</Reference>
		<Reference Include="System.Security.AccessControl">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Security.AccessControl.dll</HintPath>
		</Reference>
		<Reference Include="System.Security.Principal.Windows">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Security.Principal.Windows.dll</HintPath>
		</Reference>
		<Reference Include="System.ServiceProcess.ServiceController">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.ServiceProcess.ServiceController.dll</HintPath>
		</Reference>
		<Reference Include="System.Text.Encoding">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Text.Encoding.dll</HintPath>
		</Reference>
		<Reference Include="System.Text.Encoding.CodePages">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Text.Encoding.CodePages.dll</HintPath>
		</Reference>
		<Reference Include="System.Threading.AccessControl">
			<HintPath>..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Threading.AccessControl.dll</HintPath>
		</Reference>
```

```
MSFT_NetTCPConnection (InstanceID = "::??49670??::??0")
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10-192-g6c22065d77f0d150484ac0234938b0afb7ee11f1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

system: 10.0.19044

**Comment by T35R6braPwgDJKq** [comment]
Lets assume I get that worked out and the weird `MSFT_NetTCPConnection (InstanceID = "::??49670??::??0")` can be transformed to actual useful information, the next step is to copy the binary to another computer.

Executing it there, I get:
```
Err:    at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at TestCore.Program.Main(String[] args)
```

That is acutally the initial reason why I wanted to report a bug, but my MWE above didn't yield the same results as my actual project, so I'm asking for help twice.

**Comment by iSazonov** [comment]
I wonder why do you create and build your project in so weird way? Why don't you read and follow docs?

**Comment by daxian-dbw** [comment]
@T35R6braPwgDJKq Please directly use `Microsoft.PowerShell.SDK` with the `PackageReference` tag in your project file.

**Comment by iSazonov** [comment]
> /p:PublishSingleFile=true

This is not supported too.

**Comment by T35R6braPwgDJKq** [comment]
> I wonder why do you create and build your project in so weird way? Why don't you read and follow docs?
what do you mean exactly? The project is an update to an existing project (which was built against ~netcore 2 or so)
Also, i'm using VS2019 which does not support .net6; i also guess that this does not really relate to the problem
> `/p:PublishSingleFile=true` is not supported too.
May be, but that does not seem the problem here either

@daxian-dbw uhm, I installed the nuget package and set the reference - Do we expect another/more detailed error message here? If so, its not the case.

**Comment by daxian-dbw** [comment]
@T35R6braPwgDJKq I gave it a try with `<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.1" />` to reference the PowerShell SDK package and it works fine. Here are the details:

```c#
using System;
using System.Management.Automation;

namespace TestCore
{
    class Program
    {
        static void Main(string[] args)
        {
            using (PowerShell ps = PowerShell.Create())
            {
                ps.AddCommand("Set-ExecutionPolicy")
                    .AddParameter("ExecutionPolicy", "RemoteSigned")
                    .AddParameter("Scope", "Process")
                    .Invoke();

                var results = ps.AddScript("Get-NetTCPConnection").Invoke();
                Console.WriteLine(results[0].ToString());
                ps.Commands.Clear();
            }
        }
    }
}
```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.1" />
  </ItemGroup>

</Project>
```
![image](https://user-images.githubusercontent.com/127450/148620299-14e443f2-c05f-4601-bbd3-fe7be5124bcf.png)

------------

`results[0].ToString()` won't get you the formatting output like in PowerShell because doing that in C# application doesn't go through the PowerShell formatting system. But you will get back the object and thus you can access its properties/fields as you need.

**Comment by T35R6braPwgDJKq** [comment]
But how would I reference my `..\..\PowerShell\src\powershell-win-core\bin\Release\net6.0\win7-x64\publish\System.Management.Automation.dll`? 
If I use the nuget package, the reference to my version is completely lost, isnt it?

**Comment by daxian-dbw** [comment]
Referencing local files in your .csproj for hosting PowerShell is not supported scenario. You can pick the nuget package with the same version as the powershell you installed, and that will make sure they are in sync.

**Comment by T35R6braPwgDJKq** [comment]
Well, I made changes to the pwsh code so it is required that my version is taken into consideration. I dont see neither why it should not work?
Is there a way to build the Microsoft.PowerShell.SDK based on my pwsh?

**Comment by daxian-dbw** [comment]
To build nuget packages, use `New-ILNugetPackage` from the `tools/packaging` module. Example:
```
New-ILNugetPackage -PackagePath <path-to-save-nuget-packages> -PackageVersion <version, ex: 7.2.0-preview.1> -WinFxdBinPath <path-to-publish-folder-of-the-fxdep-build-for-windows> -LinuxFxdBinPath <path-to-publish-folder-of-the-fxdep-build-for-Linux> -GenAPIToolPath <path-to-genapi>
```
1. This command needs to run on Windows. But you need to first build pwsh with `-Runtime fxdependent`.
1. You can get `genAPI` from https://www.nuget.org/packages/Microsoft.DotNet.BuildTools.GenAPI/1.0.0-beta-00081. You will need to unzip the package and copy the `genAPI.exe` and related dlls to `<path-to-genapi>`.
1. Your `PATH` env variable need to contain path to `nuget.exe`.

**Comment by T35R6braPwgDJKq** [comment]
I will give that a try, but I do not understand why it isnt enough to reference the generated pwsh libs
When I use the systems System.Management.Automation.dll it works flawlessly

**Comment by daxian-dbw** [comment]
I'm not sure why that's not working, but it's not a supported scenario, so we will not investigate into it.

**Comment by iSazonov** [comment]
At least pwsh SMA has additional dependencies vs WinPS SMA.
