### ISSUE TITLE
PowerShell ps1 script to manage bluetooth status stopped working

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#16731]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run this script in PowerShell 7.2.1:
https://superuser.com/a/1293303/298707

````
[CmdletBinding()] Param (
    [Parameter(Mandatory=$true)][ValidateSet('Off', 'On')][string]$BluetoothStatus
)
If ((Get-Service bthserv).Status -eq 'Stopped') { Start-Service bthserv }
Add-Type -AssemblyName System.Runtime.WindowsRuntime
$asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]
Function Await($WinRtTask, $ResultType) {
    $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)
    $netTask = $asTask.Invoke($null, @($WinRtTask))
    $netTask.Wait(-1) | Out-Null
    $netTask.Result
}
[Windows.Devices.Radios.Radio,Windows.System.Devices,ContentType=WindowsRuntime] | Out-Null
[Windows.Devices.Radios.RadioAccessStatus,Windows.System.Devices,ContentType=WindowsRuntime] | Out-Null
Await ([Windows.Devices.Radios.Radio]::RequestAccessAsync()) ([Windows.Devices.Radios.RadioAccessStatus]) | Out-Null
$radios = Await ([Windows.Devices.Radios.Radio]::GetRadiosAsync()) ([System.Collections.Generic.IReadOnlyList[Windows.Devices.Radios.Radio]])
$bluetooth = $radios | ? { $_.Kind -eq 'Bluetooth' }
[Windows.Devices.Radios.RadioState,Windows.System.Devices,ContentType=WindowsRuntime] | Out-Null
Await ($bluetooth.SetStateAsync($BluetoothStatus)) ([Windows.Devices.Radios.RadioAccessStatus]) | Out-Null
````

With either option `.\bluetooth.ps1 -BluetoothStatus On` or `.\bluetooth.ps1 -BluetoothStatus Off`.

### Expected behavior

```console
Run like in older PowerShell versions.
```

### Actual behavior

```console
Does not work.
```

### Error details

```console
Get-Error

Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : You cannot call a method on a null-valued expression.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvokeMethodOnNull
        InvocationInfo        :
            ScriptLineNumber : 19
            OffsetInLine     : 1
            HistoryId        : -1
            ScriptName       : C:\bin\bluetooth.ps1
            Line             : Await ($bluetooth.SetStateAsync($BluetoothStatus))
([Windows.Devices.Radios.RadioAccessStatus]) | Out-Null

            PositionMessage  : At C:\bin\bluetooth.ps1:19 char:1
                               + Await ($bluetooth.SetStateAsync($BluetoothStatus))
([Windows.Devices. …
                               +
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\bin
            PSCommandPath    : C:\bin\bluetooth.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\bin\bluetooth.ps1: line 19
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure,
System.Runtime.CompilerServices.CallSite, System.Object, System.Object)
    Message     : You cannot call a method on a null-valued expression.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
InvocationInfo        :
    ScriptLineNumber : 19
    OffsetInLine     : 1
    HistoryId        : -1
    ScriptName       : C:\bin\bluetooth.ps1
    Line             : Await ($bluetooth.SetStateAsync($BluetoothStatus))
([Windows.Devices.Radios.RadioAccessStatus]) | Out-Null

    PositionMessage  : At C:\bin\bluetooth.ps1:19 char:1
                       + Await ($bluetooth.SetStateAsync($BluetoothStatus)) ([Windows.Devices. …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\bin
    PSCommandPath    : C:\bin\bluetooth.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\bin\bluetooth.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
This 
```
>  Add-Type -AssemblyName System.Runtime.WindowsRuntime
> $asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]

MethodInvocationException: Exception calling "GetParameters" with "0" argument(s): "Operation is not supported on this 
platform. (0x80131539)"
```

suggests you've cut and pasted something tied to .NET Framework 4 into the .NET 6. version of PowerShell. 

It simplifies to 
```
> $asTaskMethods = [System.WindowsRuntimeSystemExtensions].GetMethods()  | where-object name -eq 'AsTask'                                                                                                         > $asTaskMethods[0].GetParameters()
MethodInvocationException: Exception calling "GetParameters" with "0" argument(s): "Operation is not supported on this platform. (0x80131539)"
``` 

And the equivalent in C# would give the same error if compiled with the current .NET.

**Comment by superbonaci** [comment]
> 
> $asTaskMethods = [System.WindowsRuntimeSystemExtensions].GetMethods()  | where-object name -eq 'AsTask'

Lines
````
Add-Type -AssemblyName System.Runtime.WindowsRuntime
$asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]
````
and
````
$asTaskMethods = [System.WindowsRuntimeSystemExtensions].GetMethods()  | where-object name -eq 'AsTask'
````

are not equivalent:
````
.\Set-bluetooth.ps1

cmdlet Set-bluetooth.ps1 at command pipeline position 1
Supply values for the following parameters:
BluetoothStatus: On
You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:7 char:5
+     $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:8 char:5
+     $netTask = $asTask.Invoke($null, @($WinRtTask))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:9 char:5
+     $netTask.Wait(-1) | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:7 char:5
+     $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:8 char:5
+     $netTask = $asTask.Invoke($null, @($WinRtTask))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:9 char:5
+     $netTask.Wait(-1) | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\bin\Set-bluetooth.ps1:18 char:1
+ Await ($bluetooth.SetStateAsync($BluetoothStatus)) ([Windows.Devices. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
````
Please make tests before reporting invalid bugs.

**Comment by iSazonov** [comment]
It is know issue. WinRT support was removed from .Net 6.0 and as result from PowerShell 7.2 too.

**Comment by superbonaci** [comment]
How can I tell PowerShell to use .NET 4.x from inside the script instead of "default" 6.x?

**Comment by superbonaci** [comment]
Can I run Windows PowerShell from inside the ps1 script?
So when I call `.\Set-bluetooth.ps1` it autodetects if must run Windows Powershell or Powershell Core.

**Comment by jhoneill** [comment]
> Please make tests before reporting invalid bugs.
@superbonaci  you might want to heed your own advice

Here is your error
```
$asTask = $asTaskGeneric.MakeGenericMethod($ResultType)

You cannot call a method on a null-valued expression.
```

What method is being called, and what expression is null-valued ?   It's `$asTaskGeneric`.    
So where is `$asTaskGeneric`  set ? 

```
ps >   Add-Type -AssemblyName System.Runtime.WindowsRuntime
ps >    $asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]
```
If I paste those into PowerShell 7.2.1 I get multiple instances of 

```
MethodInvocationException: Exception calling "GetParameters" with "0" argument(s): "Operation is not supported on this 
platform. (0x80131539)"
``` 

OK. 
So lets see where the second line breaks, 
```
ps >   $one = [System.WindowsRuntimeSystemExtensions].GetMethods()  
```
OK
```
ps >  $two =  $one | ? { $_.Name -eq 'AsTask'}
```
OK
```
ps > $three = $two | ? {$_.GetParameters().Count -eq 1}

MethodInvocationException: Exception calling "GetParameters" with "0" argument(s): "Operation is not supported on this platform. (0x80131539)"
```


> How can I tell PowerShell to use .NET 4.x from inside the script instead of "default" 6.x?

.NET 6 is hard wired into PowerShell 7.2 , just as Dot net framework 4 is hardwired into Windows PowerShell 5.1

I can't find where I used it but somewhere I have some code like this 

```
if ($PSVersionTable.PSVersion -ge "6.0.0") {
    powershell.exe $MyInvocation.Line  
    return
}
``` 
Which will run the same ps1 with the same parameters in the other version of PowerShell.

**Comment by SeeminglyScience** [comment]
You may be able to do this:

```powershell
$session = New-PSSession -UseWindowsPowerShell
Invoke-Command -Session $session {
    code here
}
```

**Comment by superbonaci** [comment]
@SeeminglyScience what happens if I am running that script inside PowerShell 7.x and `Windows PowerShell` is removed in a future Windows 11 update? Would that script fail?

**Comment by kilasuit** [comment]
> what happens if I am running that script inside PowerShell 7.x and Windows PowerShell is removed in a future Windows 11 update? Would that script fail?

@superbonaci  - that is almost never going to happen as it is part of the OS and whilst **may** become an optional feature, will be supported for at least another 10 years due to the Windows support lifecycle

**Comment by superbonaci** [comment]
> You may be able to do this:
> 
> ```powershell
> $session = New-PSSession -UseWindowsPowerShell
> Invoke-Command -Session $session {
>     code here
> }
> ```

Your code works now if the script is run inside PowerShell Core 7.x, however is not backwards compatible with Windows PowerShell. It must be backward compatible:
````
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
````
````
 .\bluetooth.ps1
New-PSSession : A parameter cannot be found that matches parameter name 'UseWindowsPowerShell'.
At C:\bin\bluetooth.ps1:1 char:26
+ $session = New-PSSession -UseWindowsPowerShell
+                          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PSSession], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.NewPSSessionCommand

Invoke-Command : Cannot validate argument on parameter 'Session'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\bin\bluetooth.ps1:2 char:25
+ Invoke-Command -Session $session {
+                         ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand
````

**Comment by SeeminglyScience** [comment]
> Your code works now if the script is run inside PowerShell Core 7.x, however is not backwards compatible with Windows PowerShell. It must be backward compatible:

Yeah for sure, I'm just offering a work around. You'll need to apply it selectively with version checks if you want it to run no matter what executable it's invoked in.

The main issue of WinRT support being dropped is discussed in more detail in #13138.

**Comment by 237dmitry** [comment]
> How can I convert all existing code to a function?

Just insert this checking after param block.

**Comment by superbonaci** [comment]
> > How can I convert all existing code to a function?
> 
> Just insert this checking after param block.

How would the code look like?

**Comment by 237dmitry** [comment]
> How would the code look like?
```
[CmdletBinding()] Param (
    [Parameter(Mandatory=$true)][ValidateSet('Off', 'On')][string]$BluetoothStatus
)

if ($PSEdition -eq 'Core') {
    powershell.exe $MyInvocation.Line
    return
}
...
```

**Comment by superbonaci** [comment]
> > How would the code look like?
> 
> ```
> [CmdletBinding()] Param (
>     [Parameter(Mandatory=$true)][ValidateSet('Off', 'On')][string]$BluetoothStatus
> )
> 
> if ($PSEdition -eq 'Core') {
>     powershell.exe $MyInvocation.Line
>     return
> }
> ...
> ```

That code asks twice for parameter, and the second time is when it's applied. Could you post the entire code please?

**Comment by iSazonov** [comment]
Close as dup #13138.

**Comment by Threepwood-7** [comment]
Not sure if it did work or not for you, it did not for me on Windows 10, so I made my own .cs version of it. [Win form and command line here with binary release](https://github.com/Threepwood-7/BTRadioControl) (no windows store needed)
