### ISSUE TITLE
PredictionResult Type Load Exception on starting PS in Windows Terminal

### ISSUE THREAD

**Issue by sebandraos** [PowerShell/PowerShell#16748]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- [ ] Open Windows Terminal with Powershell 7.2.1 set as the default profile
- [ ] As it loads the exception occurs and prints the above error message(s)

### Expected behavior

```console
The console should allow me to run commands without throwing exceptions. (Not very helpful, I know but as mentioned below it is otherwise pretty much functional)
```

### Actual behavior

```console
The terminal is still functional but the exception occurs and prints an error message every time a new line is ready to be typed into. See image 2 below. The exception also occurs if I press tab whilst typing a line. Continuation of the previous screenshot with input "cd s[tab].
```

### Error details

```console
Get-Error

Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "ReadLine" with "2" argument(s): "Could not load type
'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : TypeLoadException
        InvocationInfo        :
            ScriptLineNumber : 4
            OffsetInLine     : 5
            HistoryId        : -1
            ScriptName       : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1
            Line             : [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)

            PositionMessage  : At C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1:4 char:5
                               +     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace …
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0
            PSCommandPath    : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at PSConsoleHostReadLine,
C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1: line 4
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation,
Version=7.2.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "ReadLine" with "2" argument(s): "Could not load type
'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type       : System.TypeLoadException
        Message    : Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly
'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
        TypeName   : System.Management.Automation.Subsystem.PredictionResult
        TargetSite :
            Name          : Reset
            DeclaringType : Microsoft.PowerShell.PSConsoleReadLine+PredictionViewBase,
Microsoft.PowerShell.PSReadLine2, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null
            MemberType    : Method
            Module        : Microsoft.PowerShell.PSReadLine2.dll
        Source     : Microsoft.PowerShell.PSReadLine2
        HResult    : -2146233054
        StackTrace :
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics,
CancellationToken cancellationToken)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type
typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : TypeLoadException
InvocationInfo        :
    ScriptLineNumber : 4
    OffsetInLine     : 5
    HistoryId        : -1
    ScriptName       : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1
    Line             : [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)

    PositionMessage  : At C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1:4 char:5
                       +     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace …
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0
    PSCommandPath    : C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at PSConsoleHostReadLine,
C:\Users\seban\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1: line 4


_________________________________________________

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PSReadLine: 2.2.0-beta1
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.22000
BufferWidth: 120
BufferHeight: 30
```

### Visuals

1. Upon Opening
![image](https://user-images.githubusercontent.com/6084391/149505195-da896d5a-b6f2-4539-8aca-2addf3c062a8.png)

2. After "cd .."
![image](https://user-images.githubusercontent.com/6084391/149506061-55ec343a-c838-42a3-b377-55dbb2e8b9cc.png)

3. After "cd s[tab]"
![image](https://user-images.githubusercontent.com/6084391/149506358-2717c40d-2b7c-42e9-ba80-88efa418cc8e.png)

**Comment by iSazonov** [comment]
@sebandraos Please install latest PSReadline version.

**Comment by sebandraos** [comment]
Thank you @iSazonov , I actually downgraded PSReadLine to latest stable 2.1.0 and it's all good again. I don't recall upgrading PSReadLine to the prerelease version manually so maybe it's included in the 7.2.1 release of PowerShell. Either way, I'm back up and running so thanks again.
