### ISSUE TITLE
PowerShell Write-SqlTableData : Execution Timeout Expired

### ISSUE THREAD

**Issue by marmar1020** [PowerShell/PowerShell#16759]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello All,

I am experiencing a error when writing csv data to an sql table with PowerShell.  The data will start to write and display an increasing percentage but it will stop abruptly and return:

Write-SqlTableData:
Line |
  21 |  Write-SqlTableData -InputData $b -DatabaseName DATABASE -TableName  …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

The csv is just under 1,000,000 rows.

### Expected behavior

```console
I am using the connection below:

$ServerName = "SERVER"
$DatabaseName = "DATABASE"
$Query = ""
$QueryTimeout = 0
$ConnectionTimeout = 0
$conn=New-Object System.Data.SqlClient.SQLConnection
$ConnectionString = "Server={0};Database={1};Integrated Security=True;Connect Timeout={2}" -f $ServerName,$DatabaseName,$ConnectionTimeout
$conn.ConnectionString=$ConnectionString
$conn.Open()
$cmd=New-Object system.Data.SqlClient.SqlCommand($Query,$conn)
$cmd.CommandTimeout=$QueryTimeout
$ds=New-Object system.Data.DataSet
Clear-Host;
$da=New-Object system.Data.SqlClient.SqlDataAdapter($cmd)
[void]$da.fill($ds)
$conn.Close()

Both $QueryTimeout = 0 and $ConnectionTimeout = 0 are set to zero. Also, SSMS Execution time out is set to zero.
```

### Actual behavior

```console
It will attempt to write the csv file but will end up producing error: Write-SqlTableData : Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
```

### Error details

```console
Exception             :
    Type               : System.Data.SqlClient.SqlException
    Errors             :
        Source  : Core .Net SqlClient Data Provider
        Number  : -2
        Class   : 11
        Server  : enxlprosqld1
        Message : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
    ClientConnectionId : dee4fde0-806d-48e5-bb45-8908d78e7642
    Class              : 11
    Number             : -2
    Server             : SERVER
    Source             : Core .Net SqlClient Data Provider
    ErrorCode          : -2146232060
    TargetSite         :
        Name          : OnError
        DeclaringType : System.Data.SqlClient.SqlConnection
        MemberType    : Method
        Module        : System.Data.SqlClient.dll
    Message            : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
    Data               : System.Collections.ListDictionaryInternal
    InnerException     :
        Type            : System.ComponentModel.Win32Exception
        NativeErrorCode : 258
        ErrorCode       : -2147467259
        Message         : The wait operation timed out.
        HResult         : -2147467259
    HResult            : -2146232060
    StackTrace         :
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at System.Data.SqlClient.TdsParserStateObject.WriteBytes(ReadOnlySpan`1 b, Int32 len, Int32 offsetBuffer, Boolean canAccumulate, TaskCompletionSource`1 completion,
Byte[] array)
   at System.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset,
TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at System.Data.SqlClient.TdsParser.WriteBulkCopyValue(Object value, SqlMetaDataPriv metadata, TdsParserStateObject stateObj, Boolean isSqlType, Boolean isDataFeed,
Boolean isNull)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts,
TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts,
TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1
source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table)
   at Microsoft.SqlServer.Management.PowerShell.WriteSqlTableData.ProcessTarget(Table table, SmoRecordContext context)
TargetObject          : [dbo].[TABLE]
CategoryInfo          : WriteError: ([dbo].[TABLE]:Table) [Write-SqlTableData], SqlException
FullyQualifiedErrorId : WriteToTableFailure,Microsoft.SqlServer.Management.PowerShell.WriteSqlTableData
InvocationInfo        :
    MyCommand        : Write-SqlTableData
    ScriptLineNumber : 21
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Write-SqlTableData -InputData $b -DatabaseName DATABASE -TableName TABLE -ServerInstance SERVER -SchemaName dbo
    PositionMessage  : At line:21 char:1
                       + Write-SqlTableData -InputData $b -DatabaseName DATABASE -TableName  …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Write-SqlTableData
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 21
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use other channels to discuss/report the issue.

**Comment by marmar1020** [comment]
ISazonov, thanks for the follow up. Can you elaborate on "The cmdlet is not in the repository". I was able to use the Write-SqlTableData cmdlet with other SQL Server tables, without a time out issue.

My apologies, but can someone point me to another channel. I followed the guide and was prompted to post here.

Thanks,

**Comment by iSazonov** [comment]
> Can you elaborate on "The cmdlet is not in the repository"

The repository is for pwsh developers and contains PowerShell Engine and some builtin modules.
Most of PowerShell modules is not in the repository and supported other (MSFT or community) teams.

Today you can find a lot of MSFT and community forums/chats and so on where you can discuss any PowerShell related issues. https://github.com/PowerShell/PowerShell#chat

**Comment by marmar1020** [comment]
Thank you for the clarification!
