### ISSUE TITLE
Getting error "Unable to find type" when using IValidateSetValuesGenerator in a PowerShell manifest module 

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#16774]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a follow-up issue to issue #5661 I reported a few years back and I would like some insight into how this setup is different.

My new code has been following the "manifest module" pattern as laid out in the Pester documentation here:
https://github.com/pester/Pester/wiki/Testing-different-module-types#usage-and-workarounds

Here is their snippet for reference:
```powershell
@{
ModuleVersion     = '1.0'

RootModule        = "MyModule.psm1"

NestedModules     = @( "Invoke-PrivateManifestMethod.ps1", "Invoke-PublicManifestMethod.ps1" )
FunctionsToExport = @( "Invoke-PublicManifestMethod" )
}
```

This pattern works well for private and public PowerShell functions, it also works decently well for classes, except those that need to be exposed in the `ValidateSet` attribute. If I were to publish this I would likely merge the files, as I've heard dot-sourcing (which I assume is similar to `NestedModules`) can have performance issues, but I would still expect this to work locally.

To produce the issue, create the following folder structure and files:

```
\--PSTest
   |--Classes
      |--ValidateSet.ps1
   |--Public
      |--Test-ValidateSet.ps1
   |--PSTest.psd1
   |--PSTest.psm1
```

**ValidateSet.ps1**:
```powershell
using namespace System.Management.Automation

class TestValuesGenerator :  IValidateSetValuesGenerator {

    [string[]] GetValidValues() {
        return 1, 2, 3
    }

}
```

**Test-ValidateSet.ps1**:
```powershell
# Also does not work.
# . $PSScriptRoot/../Classes/ValidateSet.ps1

function Test-ValidateSet {
    param (
        [ValidateSet([TestValuesGenerator])]
        [string] $IWantValidValues
    )
}
```

**PSTest.psd1**:
```powershell
...

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Classes/ValidateSet.ps1', 'Public/Test-ValidateSet.ps1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Test-ValidateSet', 'Test-ValidateSetInModule')

...
```

**PSTest.psm1**:
```powershell
# Also does not work.
# . $PSScriptRoot/Classes/ValidateSet.ps1

function Test-ValidateSetInModule {
    param (
        [ValidateSet([TestValuesGenerator])]
        [string] $IWantValidValues
    )
}
```

At the moment, the only workaround I've found is literally putting a copy of the class in any file that needs it or putting all the classes for `ValidateSet` exposure into their own module and using the `using module` expression. Neither is overly convenient. 

**Edit:
I can also use the `ScriptsToProcess` attribute, that brings the class into session scope which may or may not be a good idea and would open the door to type collisions.**

@iSazonov worked on the previous fix, maybe they have some insight into how this behavior is different. My current assumption is the classes are only visible to module scope, but the same is also true for classes defined inside a module, so I'm not 100% sure what the actual underlying differences are.

### Expected behavior

```console
No errors occur and validate set operations work.
```

### Actual behavior

```console
PS> Test-ValidateSet
InvalidOperation: C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1:6
Line |
   6 |          [ValidateSet([TestValuesGenerator])]
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [TestValuesGenerator].
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to find type [TestValuesGenerator].
            HResult : -2146233087
        TargetObject          : [ValidateSet([TestValuesGenerator])]
        CategoryInfo          : InvalidOperation: ([ValidateSet([TestValuesGenerator])]:AttributeAst) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : TypeNotFound
        InvocationInfo        :
            ScriptLineNumber : 6
            OffsetInLine     : 9
            HistoryId        : -1
            ScriptName       : C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1
            Line             : [ValidateSet([TestValuesGenerator])]

            PositionMessage  : At C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1:6 char:9
                               +         [ValidateSet([TestValuesGenerator])]
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\<path-to-modules>\Modules\PSTest\Public
            PSCommandPath    : C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : NewValidateSetAttribute
        DeclaringType : System.Management.Automation.Language.Compiler, System.Management.Automation, Version=7.2.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Unable to find type [TestValuesGenerator].
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.Language.Compiler.NewValidateSetAttribute(AttributeAst ast)
   at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst)
   at System.Management.Automation.Language.AttributeAst.GetAttribute()
   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
   at System.Management.Automation.Language.FunctionDefinitionAst.System.Management.Automation.Language.IParameterMetadataProvider.GetParameterMetadata(Boolean automaticPositions, Boolean& usesCmdletBinding)
   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
   at System.Management.Automation.CompiledScriptBlockData.get_ObsoleteAttribute()
   at System.Management.Automation.DlrScriptCommandProcessor.Init()
   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : [ValidateSet([TestValuesGenerator])]
CategoryInfo          : InvalidOperation: ([ValidateSet([TestValuesGenerator])]:AttributeAst) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
InvocationInfo        :
    ScriptLineNumber : 6
    OffsetInLine     : 9
    HistoryId        : -1
    ScriptName       : C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1
    Line             : [ValidateSet([TestValuesGenerator])]

    PositionMessage  : At C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1:6 char:9
                       +         [ValidateSet([TestValuesGenerator])]
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\<path-to-modules>\Modules\PSTest\Public
    PSCommandPath    : C:\<path-to-modules>\Modules\PSTest\Public\Test-ValidateSet.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@LethiferousMoose Please look #6652 where we are tracking class issues. Perhaps we already have an issue like this.

**Comment by LethiferousMoose** [comment]
@iSazonov Dang, that's a big list... I think I was happier being ignorant to all this... I'll read over them when I have some time tomorrow.

**Comment by jhoneill** [comment]
@LethiferousMoose   I've been through this pain :-) 

Script Classes loaded in modules can end up being invisible _outside_ the module. So if one is linked to a parameter it isn't available when you run the command at the prompt.  

This is what I have in the .psd1 for a module I am working on at the moment. 
```
    ScriptsToProcess    = @('OctopusUtilityClasses.ps1')
    RootModule          =   'Octopus.psm1'

    FunctionsToExport   = @(  ...
```

(my PSM1 file dot sources all .ps1 files in specific folders - I have 1 per function about 60 in all!) 

This behaves as if I run 
```
.  OctopusUtilityClasses.ps1 
import-module  <something without classes>
```

IIRC Classes are also OK if they are defined in the .PSM1 file itself, but not if they are in a file which the PSM1 loads.

**Comment by tim-biggin-by** [comment]
@jhoneill That's what I ended up doing, it just seems odd to my that a class defined within a .psm1 (which is only visible to the module) can be used for a `ValidateSet` attribute, but a class defined in a separate file (also only visible to things internal to the module) is not.

**Comment by LethiferousMoose** [comment]
@jhoneill That's what I ended up doing, it just seems odd to me that a class defined within a .psm1 (which is only visible to the module) can be used for a `ValidateSet` attribute, but a class defined in a separate file (also only visible to things internal to the module) is not. It seems kind of jank to have to expose the class publicly in order to make this combination work.

**Comment by jhoneill** [comment]
@LethiferousMoose       "Seems a bit odd" is an understatement :-)   
 It's known and the stuff in #6652  is trying to round these issues up and do something about them but the lack of progress. makes me wonder if the cause isn't easy to solve. For now it's - just something one needs to work round.

**Comment by iSazonov** [comment]
Dup #6652 #6293
