### ISSUE TITLE
Get-Error unexpected behavior when error information is saved inside variable

### ISSUE THREAD

**Issue by ClarkRSD** [PowerShell/PowerShell#16839]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Simply take anything that produces an error and save the information into a variable. After recalling this variable more than once in the console, it simply returns the error itself, **not** the information that was intended to be saved via `Get-Error`.

### Expected behavior

```console
PS C:\Windows\System32> Do-Something
Do-Something: The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> $ErrorInformation = $error[0] | Get-Error
PS C:\Windows\System32> $ErrorInformation

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : Do-Something
        CategoryInfo          : ObjectNotFound: (Do-Something:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 10
            Line             : Do-Something
            PositionMessage  : At line:1 char:1
                               + Do-Something
                               + ~~~~~~~~~~~~
            InvocationName   : Do-Something
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : Do-Something
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.3.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions,
CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Do-Something
CategoryInfo          : ObjectNotFound: (Do-Something:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : Do-Something
    PositionMessage  : At line:1 char:1
                       + Do-Something
                       + ~~~~~~~~~~~~
    InvocationName   : Do-Something
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PS C:\Windows\System32> $ErrorInformation

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : Do-Something
        CategoryInfo          : ObjectNotFound: (Do-Something:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 10
            Line             : Do-Something
            PositionMessage  : At line:1 char:1
                               + Do-Something
                               + ~~~~~~~~~~~~
            InvocationName   : Do-Something
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : Do-Something
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.3.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions,
CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Do-Something
CategoryInfo          : ObjectNotFound: (Do-Something:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : Do-Something
    PositionMessage  : At line:1 char:1
                       + Do-Something
                       + ~~~~~~~~~~~~
    InvocationName   : Do-Something
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Actual behavior

```console
PS C:\Windows\System32> Do-Something
Do-Something: The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> $ErrorInformation = $error[0] | Get-Error
PS C:\Windows\System32> $ErrorInformation

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : Do-Something
        CategoryInfo          : ObjectNotFound: (Do-Something:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 10
            Line             : Do-Something
            PositionMessage  : At line:1 char:1
                               + Do-Something
                               + ~~~~~~~~~~~~
            InvocationName   : Do-Something
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : Do-Something
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.3.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions,
CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Do-Something
CategoryInfo          : ObjectNotFound: (Do-Something:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : Do-Something
    PositionMessage  : At line:1 char:1
                       + Do-Something
                       + ~~~~~~~~~~~~
    InvocationName   : Do-Something
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

PS C:\Windows\System32> $ErrorInformation

Do-Something: The term 'Do-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It's the formatting script, 

Get-Error returns an object with a type which triggers special formatting. 
```
$ErrorInformation = $error[0] | Get-Error
$ErrorInformation $e | gm

   TypeName: System.Management.Automation.ErrorRecord#PSExtendedError
```

This shows the script 
```
(Get-FormatData System.Management.Automation.ErrorRecord#PSExtendedError).FormatViewDefinition.Control.entries.customitems.expression.value
```

There's code at the end specifically to remove it that type, so the next time it won't format.  I don't know why.  There are number of things looking at that code where I don't know why things have been done as they have (TBH it doesn't look to have been properly reviewed)

**Comment by 237dmitry** [comment]
If the goal is to save to variable the full output of `Get-Error`, not the ErrorRecord object, then it can be saved as a string.
```powershell
> 1/0
RuntimeException: Attempted to divide by zero.

> $err = Get-Error | Out-String
```

**Comment by jhoneill** [comment]
> If the goal is to save to variable the full output of `Get-Error`, not the ErrorRecord object, then it can be saved as a string.
> 
> ```powershell
> > 1/0
> RuntimeException: Attempted to divide by zero.
> 
> > $err = Get-Error | Out-String
> ```

Yes, or the OP  could replace 
````
> $ErrorInformation = $error[0] | Get-Error 
> $ErrorInformation 
...
> $ErrorInformation 
```

with 
````
> $MyError = $error[0] 
> $MyError  | Get-Error 
...
>$MyError  | Get-Error 
```

But, **as a general principle , formatting code should not change the object being formatted** . Code which does so really needs to be classed as **a bug.**   
I think  @theJasonHelmick   was involved in this initially, and might be able to shed some light on whether this was done for good reason or if something crept into the the release that shouldn't be there : it looks like the latter to me.

**Comment by iSazonov** [comment]
`Get-Error` temporary removes `System.Management.Automation.ErrorRecord` from TypeNames property and add `System.Management.Automation.ErrorRecord#PSExtendedError`. But in second call of the variable PowerShell Engine evaluate properties of the psobject and as result reset TypeNames property to "right" value.

I think we have no need to fix something since workarounds exist.

**Comment by ClarkRSD** [comment]
Yes, there is a workaround to format the error into a string.

I should have clarified in my OP that I know how to workaround this by doing what's outlined above and putting the error into a string or whatever item that I'm needing specifically in the error into a string, but I figured I would report this as I wasn't sure if this is something that would be something that would want to even be fixed or not, as you have mentioned, @iSazonov.

**Comment by jhoneill** [comment]
My 0.02... the act of formatting something for output should not change it. 

This is a badly behaved bit of code which should all be in one lump.

```
ps> $error[2]

InvalidOperation: Method invocation failed because [System.Management.Automation.ErrorRecord] does not ...

ps> $e = $error[2] | get-error

ps> $error[2]

Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Method invocation failed because [System.Management.Automation.ErrorRecord] does not ....
```


This looks like it was written as  one big script to print an error, and then it was split into return an object, and formatting to print it.  So if you don't format the what is returned by `Get-Error` you are left with `$error[i]` having its `PSTypeNames` modified. 
```
ps> $error[2].pstypenames
System.Object
System.Management.Automation.ErrorRecord

ps> $e = $Error[2] | get-error

ps> $error[2].pstypenames
System.Management.Automation.ErrorRecord#PSExtendedError
System.Object
```
 Which is the first wrong, the cmdlet should make a copy, to preserve the original.  $e and $error[2] point to the same bytes.  so when the formatting runs it reverts them that's the second wrong. Get-Error only works properly if the output is immediately formatted which as we see here isn't always the case. There is a much better way to do this

**Comment by iSazonov** [comment]
For information, Get-Error cmdlet was designed exclusively as helper for _interactive_ scenarios, it makes no sense to use it scripts.

**Comment by jhoneill** [comment]
> For information, Get-Error cmdlet was designed exclusively as helper for _interactive_ scenarios, it makes no sense to use it scripts.

Even so it doesn't need to screw up the error objects and fix them during the output process. 

I've created a function based on the `Get-Error` c#  and the script embedded in the formatting to do it all in one place so what the OP complained about doesn't happen any more. It also allows the colors to be specified, sorts out the colons for nested items being less indented and and handles long lines better. 

https://gist.github.com/jhoneill/6e79c210f78eda01f72426c173fa2bf4
