### ISSUE TITLE
"Unable to cast PathInfo to String" when assigning to shell shortcut property

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#16926]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following function creates a new shortcut (.lnk) using a Shell COM object, and then attempts to set the working directory property (without saving the shortcut).
```
function fn([switch]$Resolve) {
    $WorkingDirectory = if ($Resolve) {Resolve-Path "."} else {"."}
    $Shell = (New-Object -ComObject "WScript.Shell")
    # the shortcut is not actually created
    $Shortcut = $Shell.CreateShortcut("C:\shortcut.lnk")
    $Shortcut.WorkingDirectory = $WorkingDirectory
}
```

If you add this function **into a fresh `pwsh` session**, and then run the following 2 invocations, everything works correctly:
```
> fn -Resolve
> fn
```

However, if you run the commands in the opposite order (**again in a fresh `pwsh` session**), a type error is thrown:
```
> fn
> fn -Resolve
OperationStopped:
Line |
   6 |      $Shortcut.WorkingDirectory = $WorkingDirectory
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to cast object of type 'System.Management.Automation.PathInfo' to type 'System.String'.
```

My hypothesis: PowerShell somehow remembers the first type that is assigned into a property of a COM object, and then refuses any other type (even if the second type can be normally implicitly casted to the first type). However, this only works in one direction (when the first type is a String, which matches the expected type of the property), but not in the other (when the first type is something that can be implicitly casted to the correct type (String in this case)). No idea why, quite curious. :)

### Expected behavior

```console
Both invocations should succeed, independent of the order.
```

### Actual behavior

```console
A type error is thrown if the first assignment assigns a String, and the second assignment assigns a different type, even if has an implicit cast to String.
```

### Error details

```console
Exception             :
    Type       : System.InvalidCastException
    TargetSite :
        Name          : ChkCast_Helper
        DeclaringType : System.Runtime.CompilerServices.CastHelpers, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Unable to cast object of type 'System.Management.Automation.PathInfo' to type 'System.String'.
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2147467262
    StackTrace :
   at CallSite.Target(Closure , CallSite , ComObject , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], InvalidCastException
FullyQualifiedErrorId : System.InvalidCastException
InvocationInfo        :
    ScriptLineNumber : 6
    OffsetInLine     : 5
    HistoryId        : -1
    Line             :     $Shortcut.WorkingDirectory = $WorkingDirectory

    PositionMessage  : At line:6 char:5
                       +     $Shortcut.WorkingDirectory = $WorkingDirectory
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at fn, <No file>: line 6
                        at <ScriptBlock>, <No file>: line 1
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/6414091/155817280-6ec885bd-c243-45e4-8cc0-ff16e73ab42f.png)

**Comment by SeeminglyScience** [comment]
Yeah seems like an issue with the COM binder. It's probably not setting a binding restriction based on argument type. /cc @daxian-dbw

**Comment by daxian-dbw** [comment]
PowerShell uses the same COM binder from C#, so this is likely an issue with the C# COM binder. It would be nice to reproduce the issue in C# with `dynamic` keyword, and then open an issue in dotnet/runtime repo.

FWIW, it's not a regression -- Windows PowerShell 5.1 has the same failure because it also uses the C# COM binder.
PowerShell's COM adapter seems working fine in this case:
```
function fn([switch]$Resolve) {
    $WorkingDirectory = if ($Resolve) {Resolve-Path "."} else {"."}
    $Shell = (New-Object -ComObject "WScript.Shell")
    # the shortcut is not actually created
    $Shortcut = $Shell.CreateShortcut("C:\shortcut.lnk")

    ## setting the property through COM adapter.
    $Shortcut.psobject.properties["WorkingDirectory"].Value = $WorkingDirectory
}
```

**Comment by iSazonov** [comment]
Set Issue-Bug so that we don't lost this.

**Comment by SeeminglyScience** [comment]
@daxian-dbw I think we just need to add the argument type to binding restrictions. Here's the code generated by the binder for when the argument is string. Note, the `if` statement around it is the binding restrictions:

```csharp
if ((instance is IDispatchComObject) &&
    (((IDispatchComObject)instance).ComTypeDesc == Fake.Const<ComTypeDesc>("_defaultToString<ComTypeDesc>")))
{
    return 
    {
        int dispId = DispId;
        dispParams.rgvarg = UnsafeMethods.ConvertVariantByrefToPtr(ref paramVariants.Element0);
        dispParams.cArgs = 1;
        dispParams.cNamedArgs = 1;
        int propertyPutDispId = -3;
        dispParams.rgdispidNamedArgs = UnsafeMethods.ConvertInt32ByrefToPtr(ref propertyPutDispId);
        IDispatch dispatchObject = ((IDispatchComObject)instance).DispatchObject;
        IntPtr dispatchPointer = Marshal.GetIDispatchForObject(dispatchObject);
        try
        {
            ExcepInfo excepInfo;
            uint argErr;
            paramVariants.Element0.AsBstr = (string)value;
            int hresult = UnsafeMethods.IDispatchInvoke(
                dispatchPointer,
                dispId,
                INVOKEKIND.INVOKE_PROPERTYPUT,
                ref dispParams,
                out invokeResult,
                out excepInfo,
                out argErr);
            ComRuntimeHelpers.CheckThrowException(
                hresult,
                ref excepInfo,
                Fake.Const<ComMethodDesc>("_defaultToString<ComMethodDesc>"),
                new object[]
                {
                    ((IDispatchComObject)instance).DispatchObject as object,
                    value as object
                },
                argErr);
            returnValue = invokeResult.ToObject();
        }
        finally
        {
            UnsafeMethods.IUnknownRelease(dispatchPointer);
            paramVariants.Element0.Clear();
            invokeResult.Clear();
        }

        return AutomationNull.Value;

        return (object)value;
    };
}
```

If the binding restrictions included the property value type we'd it would trigger an update at the call site. I'm not 100% sure this would be considered an issue in C# as even in dynamic they require their casts to be a little bit more explicit. Hmm it might be though, I'll see if I can whip up a repro in a console app.

Also for completion, here's what the binder generates if `PathInfo` is the first binding for the call site:

```csharp
if ((instance is IDispatchComObject) &&
    (((IDispatchComObject)instance).ComTypeDesc == Fake.Const<ComTypeDesc>("_defaultToString<ComTypeDesc>")))
{
    return 
    {
        int dispId = DispId;
        dispParams.rgvarg = UnsafeMethods.ConvertVariantByrefToPtr(ref paramVariants.Element0);
        dispParams.cArgs = 1;
        dispParams.cNamedArgs = 1;
        int propertyPutDispId = -3;
        dispParams.rgdispidNamedArgs = UnsafeMethods.ConvertInt32ByrefToPtr(ref propertyPutDispId);
        IDispatch dispatchObject = ((IDispatchComObject)instance).DispatchObject;
        IntPtr dispatchPointer = Marshal.GetIDispatchForObject(dispatchObject);
        try
        {
            ExcepInfo excepInfo;
            uint argErr;
            paramVariants.Element0.AsVariant = value;
            int hresult = UnsafeMethods.IDispatchInvoke(
                dispatchPointer,
                dispId,
                INVOKEKIND.INVOKE_PROPERTYPUT,
                ref dispParams,
                out invokeResult,
                out excepInfo,
                out argErr);
            ComRuntimeHelpers.CheckThrowException(
                hresult,
                ref excepInfo,
                Fake.Const<ComMethodDesc>("_defaultToString<ComMethodDesc>"),
                new object[]
                {
                    ((IDispatchComObject)instance).DispatchObject as object,
                    value as object
                },
                argErr);
            returnValue = invokeResult.ToObject();
        }
        finally
        {
            UnsafeMethods.IUnknownRelease(dispatchPointer);
            paramVariants.Element0.Clear();
            invokeResult.Clear();
        }

        return AutomationNull.Value;

        return (object)value;
    };
}
```

**Comment by MatejKafka** [comment]
Still relevant.

**Comment by MatejKafka** [comment]
Still relevant.
