### ISSUE TITLE
Out-String includes ANSI escape sequences

### ISSUE THREAD

**Issue by alexbuzzbee** [PowerShell/PowerShell#16943]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
PS> 1/0
RuntimeException: Attempted to divide by zero.
PS> Get-Error | Out-String > out-string.txt
```

### Expected behavior

```console
Exception             : 
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Attempted to divide by zero.
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : RuntimeException
        InvocationInfo        : 
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : 1/0
            PositionMessage  : At line:1 char:1
                               + 1/0
                               + ~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : Divide
        DeclaringType : System.Management.Automation.IntOps, System.Management.Automation, Version=7.2.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Attempted to divide by zero.
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type    : System.DivideByZeroException
        Message : Attempted to divide by zero.
        HResult : -2147352558
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     : 
   at System.Management.Automation.IntOps.Divide(Int32 lhs, Int32 rhs)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], RuntimeException
FullyQualifiedErrorId : RuntimeException
InvocationInfo        : 
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : 1/0
    PositionMessage  : At line:1 char:1
                       + 1/0
                       + ~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Actual behavior

```console
[92mException             : [0m
    [92mType           : [0mSystem.Management.Automation.RuntimeException
    [92mErrorRecord    : [0m
        [92mException             : [0m
            [92mType    : [0mSystem.Management.Automation.ParentContainsErrorRecordException
            [92mMessage : [0m[31;1mAttempted to divide by zero.
            [92mHResult : [0m-2146233087
        [92mCategoryInfo          : [0mNotSpecified: (:) [], ParentContainsErrorRecordException
        [92mFullyQualifiedErrorId : [0mRuntimeException
        [92mInvocationInfo        : [0m
            [92mScriptLineNumber : [0m1
            [92mOffsetInLine     : [0m1
            [92mHistoryId        : [0m-1
            [92mLine             : [0m1/0
            [92mPositionMessage  : [0mAt line:1 char:1
                               + 1/0
                               + [31;1m~~~
            [92mCommandOrigin    : [0mInternal
        [92mScriptStackTrace      : [0mat <ScriptBlock>, <No file>: line 1
    [92mTargetSite     : [0m
        [92mName          : [0mDivide
        [92mDeclaringType : [0mSystem.Management.Automation.IntOps, System.Management.Automation, Version=7.2.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        [92mMemberType    : [0mMethod
        [92mModule        : [0mSystem.Management.Automation.dll
    [92mMessage        : [0m[31;1mAttempted to divide by zero.
    [92mData           : [0mSystem.Collections.ListDictionaryInternal
    [92mInnerException : [0m
        [92mType    : [0mSystem.DivideByZeroException
        [92mMessage : [0m[31;1mAttempted to divide by zero.
        [92mHResult : [0m-2147352558
    [92mSource         : [0mSystem.Management.Automation
    [92mHResult        : [0m-2146233087
    [92mStackTrace     : [0m
   at System.Management.Automation.IntOps.Divide(Int32 lhs, Int32 rhs)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[92mCategoryInfo          : [0mNotSpecified: (:) [], RuntimeException
[92mFullyQualifiedErrorId : [0mRuntimeException
[92mInvocationInfo        : [0m
    [92mScriptLineNumber : [0m1
    [92mOffsetInLine     : [0m1
    [92mHistoryId        : [0m-1
    [92mLine             : [0m1/0
    [92mPositionMessage  : [0mAt line:1 char:1
                       + 1/0
                       + [31;1m~~~
    [92mCommandOrigin    : [0mInternal
[92mScriptStackTrace      : [0mat <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alexbuzzbee** [comment]
I understand that this may sometimes be desired behavior, however it would be very helpful to have a switch causing PowerShell to generate plain text output without ANSI escape sequences for an individual `Out-String` command.

I use `Out-String` for logging the streams output by PowerShell scripts, and I have to work around the current behavior by using regular expressions to match the escape sequences and remove them so that the log content is readable.

If there is a better alternative, I would appreciate information about it from the community, as I couldn't fine one myself.

**Comment by 237dmitry** [comment]
> If there is a better alternative
```
$PSStyle.OutputRendering = 'Host'
```

**Comment by alexbuzzbee** [comment]
`$PSStyle.OutputRendering = 'Host'` has global effects. I don't want to make changes to the global environment, with potential unexpected consequences and implications, to work around an issue I'm encountering at a single-command level.

**Comment by 237dmitry** [comment]
> I don't want to make changes to the global environment

Write function or script to switch OutputRendering mode. Something like:
```powershell
function out
{
  $PSStyle.OutputRendering = 'Host'
  $input | Out-String                   
  $PSStyle.OutputRendering = 'Ansi'
 }      
```
```powershell     
 dir -Force /var/cache/pacman/pkg/ | out > ./Desktop/pkg.txt
```

**Comment by alexbuzzbee** [comment]
I don't want to get into a long argument about `OutputRendering`. While it is a valid workaround, even when reverted quickly, it is still a global state change and thus rather complex to use correctly (requiring saving the previous state and using a `finally` block to avoid leaving the changed state in place if an exception occurs). PowerShell should still provide a solution to this problem that doesn't require such a workaround.

**Comment by 237dmitry** [comment]
> PowerShell should still provide a solution to this problem that doesn't require such a workaround.

This discussion has been going on since the release of 7.2.1. I hope that the developers will come up with something.

**Comment by iSazonov** [comment]
All these Out-* cmdlets belong to the formatting subsystem so formatted output is the expected behavior.

> This discussion has been going on since the release of 7.2.1. I hope that the developers will come up with something.

I agree we need redesign this. (No one actually designed this in depth.)

**Comment by JamesWTruher** [comment]
The WG agrees that a reasonable ask for a new parameter `-OutputRendering` to be added to the applicable `Out` cmdlets would be useful. While it is possible to change the preference variable, it is a little clunky if you want it just for one invocation of `out-string`

**Comment by SteveL-MSFT** [comment]
We've had some changes to ANSI output so the original repro doesn't repro for me in 7.3 anymore

**Comment by dkaszews** [comment]
I was thinking about adding `-StripAnsiFormatting` to `Out-File` and `Out-String` for this very reason, will gladly take a stab at implementation.

**Comment by SeeminglyScience** [comment]
> I was thinking about adding `-StripAnsiFormatting` to `Out-File` and `Out-String` for this very reason, will gladly take a stab at implementation. I frequently use vim as a pager with `Select-String $pattern $files | vim -` getting cluttered with formatting escapes.

FYI you can sort of do this already, I have the inverse set up as [Out-AnsiFormatting](https://github.com/SeeminglyScience/dotfiles/blob/f94bf2c279a514e2facb9c9bad65e170607d251e/Documents/PowerShell/Utility.psm1#L5423-L5492) in my profile. You can copy the code and set `OutputFormatting` to `PlainText` instead.

(not weighing in on whether the switch should exist, just offering a workaround)
