### ISSUE TITLE
Inconsistent behavior when using New-Item on a registry key where Set Value was denied.

### ISSUE THREAD

**Issue by gbrag-ms** [PowerShell/PowerShell#16942]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Set the permission on a registry key, for example HKML:\SOFTWARE\DenySetValue, to Deny the Set Value permission for this key only:
![image](https://user-images.githubusercontent.com/33157656/156207197-04b551a7-14e8-4cef-820b-2d06ba670d0b.png)

### Expected behavior

```console
With REG and REGEDIT we can still create subkeys on that key.
The key permissions are not preventing that.
```

### Actual behavior

```console
The command New-Item HKLM:\SOFTWARE\DenySetValue\TestPS fails with the error:
"New-Item: Requested registry access is not allowed"

Checking the source code I have found that PowerShell relies on the CreateSubKey method to create the subkey.
CreateSubKey is a method of the object created with OpenSubKeyand passing the parameter writable = True
The permissions check in OpenSubKey is only allowing to create a writable object if both KEY_SET_VALUE and KEY_CREATE_SUB_KEY are permitted.

This is a possible workaround:
$key = [Microsoft.Win32.RegistryKey]::OpenBaseKey([Microsoft.Win32.RegistryHive]::LocalMachine,
[Microsoft.Win32.RegistryView]::Registry64) 
$sub = $key.OpenSubKey("software\PSDenySetValue",
[Microsoft.Win32.RegistryKeyPermissionCheck]::ReadWriteSubTree,
[System.Security.AccessControl.RegistryRights]::CreateSubKey) 
$sub.CreateSubKey("TestNet")
```

### Error details

```console
PS C:\Users\administrator> get-error

Exception             :
    Type       : System.Security.SecurityException
    TargetSite :
        Name          : InternalOpenSubKeyCore
        DeclaringType : Microsoft.Win32.RegistryKey
        MemberType    : Method
        Module        : Microsoft.Win32.Registry.dll
    Message    : Requested registry access is not allowed.
    Source     : Microsoft.Win32.Registry
    HResult    : -2146233078
    StackTrace :
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.PowerShell.Commands.RegistryWrapper.OpenSubKey(String name, Boolean writable)
   at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPath(String path, Boolean writeAccess)
   at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPathWriteIfError(String path, Boolean writeAccess)
TargetObject          : HKEY_LOCAL_MACHINE\SOFTWARE\DenySetValue
CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACHINE\SOFTWARE\DenySetValue:String) [New-Item],
SecurityException
FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.NewItemCommand
InvocationInfo        :
    MyCommand        : New-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : New-Item HKLM:\SOFTWARE\DenySetValue\TestPS
    PositionMessage  : At line:1 char:1
                       + New-Item HKLM:\SOFTWARE\DenySetValue\TestPS
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\Users\administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I don't think we can implement this because generic globbing is involved as check existence, then enumerate subkeys. The same is in Registry provider itself.

**Comment by iSazonov** [comment]
We use `public RegistryKey? OpenSubKey(string name, bool writable)` overload
where writable permissions is defined as
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Windows/Advapi32/Interop.RegistryConstants.cs#L37

Exception place https://github.com/PowerShell/PowerShell/blob/ee6bc9527c2596f048088fa7b396d2664a11ad08/src/System.Management.Automation/namespaces/RegistryProvider.cs#L3441

https://github.com/PowerShell/PowerShell/blob/ee6bc9527c2596f048088fa7b396d2664a11ad08/src/System.Management.Automation/namespaces/RegistryWrapper.cs#L180

```powershell
 Get-Error

Exception             :
    Type       : System.Security.SecurityException
    TargetSite :
        Name          : InternalOpenSubKeyCore
        DeclaringType : Microsoft.Win32.RegistryKey
        MemberType    : Method
        Module        : Microsoft.Win32.Registry.dll
    Message    : Requested registry access is not allowed.
    Source     : Microsoft.Win32.Registry
    HResult    : -2146233078
    StackTrace :
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.PowerShell.Commands.RegistryWrapper.OpenSubKey(String name, Boolean writable) in C:\Users\1\Documents\G
itHub\iSazonov\PowerShell\src\System.Management.Automation\namespaces\RegistryWrapper.cs:line 180
   at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPath(String path, Boolean writeAccess) in C:\Users\1\D
ocuments\GitHub\iSazonov\PowerShell\src\System.Management.Automation\namespaces\RegistryProvider.cs:line 3555
   at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPathWriteIfError(String path, Boolean writeAccess) in
C:\Users\1\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automation\namespaces\RegistryProvider.cs:line 34
41
TargetObject          : HKEY_LOCAL_MACHINE\SOFTWARE\DenySetValue
CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACHINE\SOFTWARE\DenySetValue:String) [New-Item], Securi
tyException
FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.NewItemCommand
InvocationInfo        :
    MyCommand        : New-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : New-Item HKLM:\SOFTWARE\DenySetValue\TestPS
    PositionMessage  : At line:1 char:1
                       + New-Item HKLM:\SOFTWARE\DenySetValue\TestPS
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```
