### ISSUE TITLE
[BUG] Az.Compute module's NewAz-VM cmdlet fails to create new vm - "New-AzVM: 'VMCustomization' is not enabled for the Subscription" Error

### ISSUE THREAD

**Issue by yaamas** [PowerShell/PowerShell#16982]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
New-AzVM -ResourceGroupName $rg -Name vm-demo-06 -Image Win2016Datacenter -Size Standard_D2s_v3
```

### Expected behavior

```console
Create VM
```

### Actual behavior

```console
PS /home/cloud> New-AzVM -ResourceGroupName $rg -Name vm-demo-06 -Image Win2016Datacenter -Size Standard_D2s_v3

cmdlet New-AzVM at command pipeline position 1
Supply values for the following parameters:
Credential
User: test    
Password for user test: ********************

New-AzVM: 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.
```

### Error details

```console
PS /home/cloud> Get-Error                                                                                               

Exception             : 
    Type       : Microsoft.Rest.Azure.CloudException
    Request    : 
        Method     : PUT
        RequestUri : https://management.azure.com/subscriptions/0f39574d-d756-48cf-b622-0e27a6943bd2/resourceGroups/1-4013897f-playground-sandbox/providers/Microsoft.Compute/virtualMachines/vm-demo-04?api-version=2021-11-01
        Content    : {
                     "properties": {
                     "hardwareProfile": {
                     "vmSize": "Standard_D2s_v3",
                     "vmSizeProperties": {}
                     },
                     "storageProfile": {
                     "imageReference": {
                     "publisher": "Canonical",
                     "offer": "UbuntuServer",
                     "sku": "16.04-LTS",
                     "version": "latest"
                     }
                     },
                     "additionalCapabilities": {},
                     "osProfile": {
                     "computerName": "vm-demo-04",
                     "adminUsername": "cloud",
                     "adminPassword": "U*6*#4U^&hw&a#7h8KG7",
                     "linuxConfiguration": {
                     "ssh": {}
                     }
                     },
                     "networkProfile": {
                     "networkInterfaces": [
                     {
                     "id": "/subscriptions/0f39574d-d756-48cf-b622-0e27a6943bd2/resourceGroups/1-4013897f-playground-sandbox/providers/Microsoft.Network/networkInterfaces/vm-demo-04"
                     }
                     ]
                     }
                     },
                     "location": "southcentralus"
                     }
        Headers    : 
            x-ms-client-request-id : 24f82e2a-373c-4b08-9048-20374548888f
            Accept-Language : en-US
            Authorization : …
            User-Agent : FxVersion/6.0.21.52210 OSName/Linux OSVersion/Linux.5.4.0.1072.azure.75.18.04.1.Ubuntu.SMP.Wed.Mar.2.14.41.08.UTC.2022 Microsoft.Azure.Management.Compute.ComputeManagementClient/52.0.0 AzurePowershell/v7.3.0 
Az.Accounts/2.7.3 Az.Compute/4.24.0 PSVersion/v7.2.1 ps-cloud-shell/0.1.0 Az.Resources/5.4.0
            CommandName : New-AzVM
            ParameterSetName : SimpleParameterSet
            Content-Type : application/json; charset=utf-8
            Content-Length : 831

    Response   : 
        StatusCode   : BadRequest
        ReasonPhrase : Bad Request
        Content      : {
                       "error": {
                       "code": "BadRequest",
                       "message": "'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature."
                       }
                       }
        Headers      : 
            Cache-Control : no-cache
            Pragma : no-cache
            x-ms-ratelimit-remaining-resource : Microsoft.Compute/PutVM3Min;300,Microsoft.Compute/PutVM30Min;1503
            Strict-Transport-Security : max-age=31536000; includeSubDomains
            x-ms-request-id : c2f518ff-30c7-4cd7-b4f5-4501b71f023f
            Server : Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
            x-ms-ratelimit-remaining-subscription-writes : 1199
            x-ms-correlation-request-id : c7c1f4e9-eee0-4004-ae55-d7b2156cd911
            x-ms-routing-request-id : WESTUS:20220309T224033Z:c7c1f4e9-eee0-4004-ae55-d7b2156cd911
            X-Content-Type-Options : nosniff
            Date : Wed, 09 Mar 2022 22:40:32 GMT
            Content-Length : 223
            Content-Type : application/json; charset=utf-8
            Expires : -1

    Body       : Microsoft.Rest.Azure.CloudError
    RequestId  : c2f518ff-30c7-4cd7-b4f5-4501b71f023f
    TargetSite : 
        Name          : Wait
        DeclaringType : Microsoft.Azure.Commands.Common.Strategies.SyncTaskScheduler
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Strategies.dll
    Message    : 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.
    Data       : System.Collections.ListDictionaryInternal
    Source     : Microsoft.Azure.PowerShell.Strategies
    HResult    : -2146233088
    StackTrace : 
   at Microsoft.Azure.Commands.Common.Strategies.SyncTaskScheduler.Wait(Task task, Action progressUpdate)
   at Microsoft.Azure.Commands.Common.Strategies.AsyncCmdletExtensions.CmdletStartAndWait(ICmdlet cmdlet, Func`2 createAndStartTask)
   at Microsoft.Azure.Commands.Compute.Strategies.AsyncCmdletExtensions.StartAndWait[T](T cmdlet, Func`2 createAndStartTask)
   at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
CategoryInfo          : CloseError: (:) [New-AzVM], CloudException
FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
InvocationInfo        : 
    MyCommand        : New-AzVM
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 25
    Line             : New-AzVM `
                       
    PositionMessage  : At line:1 char:1
                       + New-AzVM `
                       + ~~~~~~~~~~
    InvocationName   : New-AzVM
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS /home/cloud> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.4.0-1072-azure #75~18.04.1-Ubuntu SMP Wed Mar 2 14:41:08 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Related
https://github.com/Azure/CloudShell/issues/147
https://github.com/Azure/CloudShell/issues/145
https://github.com/Azure/azure-cli/issues/21224

**Comment by iSazonov** [comment]
The module is not in the repository. Please use Azure feedback to report the issue.

**Comment by doctordns** [comment]
The clue is in the error message: **Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature**.

To fix this, you go to the total and register the subscription for the VMCustomization Previe.

Sometimes, error messages are really good. The trick is to read them first.
