### ISSUE TITLE
PowerShell 7.2.0 Installer (and possibly others) cause .NET Core 3.1 apps (and possibly others) to crash with AccessViolationException / StackOverflowException

### ISSUE THREAD

**Issue by jshin47** [PowerShell/PowerShell#16980]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install the following in this order:

* .NET Core 3.1 SDK
* .NET Core 5 SDK
* .NET Core 3.1 Runtime
* PowerShell 7.2.0

Try running a .NET Core 3.1 test suite or application that has a fairly deep stack. I don't have easy to reproduce code, but I do know that the problem was fixed by removing PowerShell 7.2.0. Basically, the installer includes a DLL called `Microsoft_DiaSymReader_Native_amd64` that is used by the runtime to read PDB files when encountering Exceptions. But this included version of that library either does not work, or more likely, is not compatible with this scenario, and so what happens is that (non deterministically) you get exceptions being thrown from exception handlers leading to an infinite stack of exceptions. Typically seen as either `AccessViolationException` or `StackOverflowException`.

Note this occurs even when running from Release configuration.

### Expected behavior

```console
Installing PowerShell 7.2.0 does not break my .NET Core 3.1 applications.
```

### Actual behavior

Installing PowerShell 7.2.0 causes my .NET Core 3.1 applications to nondeterministically crash in deep call stacks at exception handlers.

Here is one such stack trace

```console
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Diagnostics.StackTrace.GetStackFramesInternal(System.Diagnostics.StackFrameHelper, Int32, Boolean, System.Exception)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32, Boolean, System.Exception)
   at System.Diagnostics.StackTrace.CaptureStackTrace(Int32, Boolean, System.Exception)
   at System.Diagnostics.StackTrace..ctor(System.Exception, Boolean)
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at System.Exception.ToString()
   at System.AggregateException.ToString()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(System.Exception)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(System.Collections.ICollection, System.Threading.CancellationToken, System.Exception)
   at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions,
System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>
, 
```

### Error details

```console
Run a .NET Core 3.1 Application from WinDbg and look for
`Microsoft_DiaSymReader_Native_amd64`
```

### Environment data

```powershell
N/A
```

**Comment by iSazonov** [comment]
Perhaps https://github.com/dotnet/runtime/issues/59077

**Comment by nickgermyn** [comment]
I can confirm that I experienced the exact issue described after installing PowerShell 7.2.1. I uninstalled and went back to PowerShell 7.1.6, and the issue no longer occurs.
