### ISSUE TITLE
Misleading error "Move-Item: Cannot create a file when that file already exists."

### ISSUE THREAD

**Issue by pluma9** [PowerShell/PowerShell#16990]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In the following case, the reason why the `Move-Item` fails is that the file is being used by another process, but the error says "Move-Item: Cannot create a file when that file already exists." which is misleading.
```
D:\bug-report> ls

    Directory: D:\bug-report

	Mode                 LastWriteTime         Length Name
	----                 -------------         ------ ----
	-a---           3/12/2022  6:02 PM              0 overwrite.mp4
	-a---          12/14/2020  5:03 AM         778242 video.mp4

D:\bug-report> Invoke-Item video.mp4 # open with VLC media player
D:\bug-report> Move-Item .\overwrite.mp4 .\video.mp4 -Force
Move-Item: Cannot create a file when that file already exists.
D:\bug-report> # close VLC media player
D:\bug-report> Move-Item .\overwrite.mp4 .\video.mp4 -Force
D:\bug-report>
```

### Expected behavior

```console
The error should be something like: The file is being used by another process.
```

### Actual behavior

```console
The error is "Move-Item: Cannot create a file when that file already exists."
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Can you rerun this and use `Get-Error` to get the full error information?

**Comment by dkaszews** [comment]
I suspect the issue may be that we treat both locked source and locked target the same, assuming that either means the file already exists.

**Comment by pluma9** [comment]
Get-Error returns the following:

```
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : MoveFile
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Cannot create a file when that file already exists.
    Source     : System.Private.CoreLib
    HResult    : -2147024713
    StackTrace :
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Microsoft.PowerShell.Commands.FileSystemProvider.MoveFileInfoItem(FileInfo file, String destination, Boolean force, Boolean output)
TargetObject          : D:\trash\hfxf0ft2egg\overwrite.mp4
CategoryInfo          : WriteError: (D:\trash\hfxf0ft2egg\overwrite.mp4:FileInfo) [Move-Item], IOException
FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
InvocationInfo        :
    MyCommand        : Move-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 18
    Line             : mi .\overwrite.mp4 .\video.mp4
    PositionMessage  : At line:1 char:1
                       + mi .\overwrite.mp4 .\video.mp4
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : mi
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```
