### ISSUE TITLE
non-Windows Named Pipe Server Length Limitation is calculated inproperly

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#16994]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a symlink with a name that exceeds ~80 chars

```bash
ln -s "$( which pwsh )" abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_pwsh
./abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_abc_pwsh

$connInfo = [System.Management.Automation.Runspaces.NamedPipeConnectionInfo]::new($pid)
$rp = [RunspaceFactory]::CreateRunspace($connInfo)
$rp.Open()
$Error[0] | Select *
```

This is happening as the name of the Unix Domain Socket created for PowerShell remoting will exceed 108 characters and PowerShell attempts to trim this to fit in that length but has a few problems:

* The logic for `pipeNameBuilder.Remove(MaxNamedPipeNameSize + 1, charsToTrim);` is incorrect and causes an exception (detailed below)
* The length calculation does not take into account a different tmpdir + the `CoreFXPipe_` prefix

### Expected behavior

```console
The Runspace is opened without any errors.
```

### Actual behavior

```console
Connection fails
```

### Error details

```console
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Open" with "0" argument(s): "An error has occurred which PowerShell cannot handle. A remote session might
                        have ended."
                         ---> System.Management.Automation.Remoting.PSRemotingDataStructureException: An error has occurred which PowerShell cannot handle. A remote session might have ended.
                         ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'length')
                           at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
                           at System.Management.Automation.Remoting.NamedPipeUtils.CreateProcessPipeName(Process proc, String appDomainName)
                           at System.Management.Automation.Remoting.NamedPipeUtils.CreateProcessPipeName(Int32 procId, String appDomainName)
                           at System.Management.Automation.Remoting.Client.NamedPipeClientSessionTransportManager.CreateAsync()
                           at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
                           at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
                           at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
                           at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
                           at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
                           at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
                           at System.Management.Automation.RemoteRunspace.Open()
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo
                        memberInfo)
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : PSRemotingDataStructureException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.16.12-200.fc35.x86_64 #1 SMP PREEMPT Wed Mar 2 19:06:17 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I tried and no errors. ArcoLinux, pwsh 7.2.1

**Comment by iSazonov** [comment]
> This is happening as the name of the Unix Domain Socket created for PowerShell remoting will exceed 108 characters and PowerShell attempts to trim this to fit in that length but has a few problems:

From https://man7.org/linux/man-pages/man7/unix.7.html
>When coding portable applications, keep in mind that some
       implementations have sun_path as short as 92 bytes.

**Comment by jborean93** [comment]
It does say that but Linux uses 108 (including NULL) but macOS is set to 104 so that would have to be the minimum, not 108). The 92 length came from a version of HP-UX but considering pwsh/.NET doesn't run on that platform I think we can safely ignore that.

**Comment by iSazonov** [comment]
Is it critical to have 10 byte more or less in the name/path?

We have to implement tricky code to handle the limitation. Maybe ask .Net for new public API to get the const `UnixDomainSocketEndPoint.MaxPathLength`? I guess this could be approved in days.

**Comment by jborean93** [comment]
> Is it critical to have 10 byte more or less in the name/path?

It isn't but it's a problem that needs to be solved as currently it is meant to trim the pipe name but fails to do so. The end result is really should it be trimming at all and if not do we have a better way to reduce the risk of having a long pipe name. This is being investigated in https://github.com/PowerShell/PowerShell/pull/16995 and requires some pending input from the security team.

> Maybe ask .Net for new public API to get the const UnixDomainSocketEndPoint.MaxPathLength

It might be possible if .NET creates some C/C++ code that does `sizeof(sockaddr_un.sun_path);` or something like that and allows .NET to retrieve that info. Personally I prefer to avoid all this complexity and just have pwsh attempt to create the pipe rather than attempting to trim it at all. Except for the very rare cases this is essentially what happens today.

**Comment by iSazonov** [comment]
> It might be possible if .NET creates some C/C++ code that does `sizeof(sockaddr_un.sun_path);`

They does
https://github.com/dotnet/runtime/blob/39fb7f7826270f00b856e3e9a13165c07dec87cc/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UnixDomainSocketEndPoint.Unix.cs#L10-L26
