### ISSUE TITLE
XML Docs are wrong for `Cmdlet.WriteDebug` re exceptions thrown

### ISSUE THREAD

**Issue by mgrandi** [PowerShell/PowerShell#17032]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In the XML docs for `Cmdlet.WriteDebug`, it says that it throws `System.InvalidOperationException` if you call `WriteDebug` outside of ProcessRecord/Begin/EndProcessing:

https://github.com/PowerShell/PowerShell/blob/10027be363cf37c5888befb7126b6f4a5380e314/src/System.Management.Automation/engine/cmdlet.cs#L611-L616

however, in the code right below it, it actually throws a `System.NotImplementedException`

https://github.com/PowerShell/PowerShell/blob/10027be363cf37c5888befb7126b6f4a5380e314/src/System.Management.Automation/engine/cmdlet.cs#L633-L642

and indeed, if you make a sample cmdlet and have a constructor for the cmdlet, and call `this.WriteDebug("debug!");` in it, it throws `NotImplementedException`.

So I feel like the XML docs are wrong here, however the exception `InvalidOperationException` makes more sense, since `Cmdlet.WriteDebug` (and friends)` are implemented, you just called it at the wrong spot in the processing.

the powershell window:

```plaintext

PS C:\Users\mgrandi\source\repos\TestCmdlet\bin\Debug\netstandard2.0> Test-writedebugcmdlet
Test-writedebugcmdlet: WriteDebug


PS C:\Users\mgrandi\source\repos\TestCmdlet\bin\Debug\netstandard2.0> $error[0].Exception.StackTrace
   at System.Management.Automation.Cmdlet.WriteDebug(String text)
   at TestCmdlet.TestWriteDebugCmdlet..ctor() in C:\Users\mgrandi\source\repos\TestCmdlet\TestWriteDebugCmdlet.cs:line 16
   at lambda_method17(Closure )
   at System.Management.Automation.CommandProcessor.ConstructInstance(Type type)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
PS C:\Users\mgrandi\source\repos\TestCmdlet\bin\Debug\netstandard2.0>


```

error from visual studio:

```plaintext

System.NotImplementedException
  HResult=0x80004001
  Message=WriteDebug
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.Cmdlet.WriteDebug(String text)
   at TestCmdlet.TestWriteDebugCmdlet..ctor() in C:\Users\mgrandi\source\repos\TestCmdlet\TestWriteDebugCmdlet.cs:line 16
   at System.Management.Automation.CommandProcessor.ConstructInstance(Type type)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)



```

source code of my test cmdlet that I used: 

```csharp
using System;
using System.Collections.Generic;
using System.Text;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

namespace TestCmdlet
{
    [Cmdlet(VerbsDiagnostic.Test, "WriteDebugCmdlet")]
    [OutputType(typeof(FavoriteStuff))]
    public class TestWriteDebugCmdlet : PSCmdlet
    {

        public TestWriteDebugCmdlet()
        {
            this.WriteDebug("this is debug!");
        }

        [Parameter(
            Mandatory = false,
            Position = 0,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = false)]
        public int ValueOne { get; set; }

       

        // This method gets called once for each cmdlet in the pipeline when the pipeline starts executing
        protected override void BeginProcessing()
        {
            WriteVerbose("Begin!");
        }

        // This method will be called for each input received from the pipeline to this cmdlet; if no input is received, this method is not called
        protected override void ProcessRecord()
        {

            WriteObject(String.Format("ValueOne (int): `{0}`", ValueOne));

        }

        // This method will be called once at the end of pipeline execution; if no input is received, this method is not called
        protected override void EndProcessing()
        {
            WriteVerbose("End!");
        }

    }

}



```

### Expected behavior

```console
N/A, xmldocs bug
```

### Actual behavior

```console
N/A, xmldocs bug
```

### Error details

```console
N/A, XMLdocs bug
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by RamiSJ12** [comment]
Try it
