### ISSUE TITLE
'#requires' not finding module with first run

### ISSUE THREAD

**Issue by nExoRek** [PowerShell/PowerShell#17052]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- include custom module with '#requires -module <name>' 
- run script

### Expected behavior

```console
script run flawlessly
```

### Actual behavior

```console
if run for the for the first time, error is cast and module fails:
.\manage-azure.ps1: The script 'manage-azure.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: eNLib.

if run the same script for the second time - it runs as expected. similarly if i load module with import-module - all works fine. this is globally installed module:
C:\ :))o- get-module enlib |select path

Path
----
C:\Program Files\WindowsPowerShell\Modules\eNLib\1.3.21\eNLib.psm1

i've installed PS7 recently - there is no issues with PS5
```

### Error details

```console
Exception             :
    Type             : System.Management.Automation.ScriptRequiresException
    CommandName      : manage-azure.ps1
    MissingPSSnapIns :
        Length : 5
    ErrorRecord      :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The script 'manage-azure.ps1' cannot be run because the following modules that are specified by the "#requires"
statements of the script are missing: eNLib.
            HResult : -2146233087
        TargetObject          : manage-azure.ps1
        CategoryInfo          : ResourceUnavailable: (manage-azure.ps1:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ScriptRequiresMissingModules
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 1
            Line             : .\manage-azure.ps1
            PositionMessage  : At line:1 char:1
                               + .\manage-azure.ps1
                               + ~~~~~~~~~~~~~~~~~~
            InvocationName   : .\manage-azure.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite       :
        Name          : VerifyRequiredModules
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.2.2.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message          : The script 'manage-azure.ps1' cannot be run because the following modules that are specified by the "#requires"
statements of the script are missing: eNLib.
    Data             : System.Collections.ListDictionaryInternal
    Source           : System.Management.Automation
    HResult          : -2146233087
    StackTrace       :
   at System.Management.Automation.CommandDiscovery.VerifyRequiredModules(ExternalScriptInfo scriptInfo, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.VerifyScriptRequirements(ExternalScriptInfo scriptInfo, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.CreateScriptProcessorForSingleShell(ExternalScriptInfo scriptInfo, ExecutionContext
context, Boolean useLocalScope, SessionStateInternal sessionState)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin,
Nullable`1 useLocalScope, SessionStateInternal sessionState)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1
useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements,
CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : manage-azure.ps1
CategoryInfo          : ResourceUnavailable: (manage-azure.ps1:String) [], ScriptRequiresException
FullyQualifiedErrorId : ScriptRequiresMissingModules
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : .\manage-azure.ps1
    PositionMessage  : At line:1 char:1
                       + .\manage-azure.ps1
                       + ~~~~~~~~~~~~~~~~~~
    InvocationName   : .\manage-azure.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
powershell 7 ‘s  $env:psmodulepath    is  different with powershell v5 .
try 'C:\Program Files\PowerShell\Modules' if you sure it work.

**Comment by nExoRek** [comment]
thx for a hint but it shouldn't matter. both paths are in the variable:
C:\Users\myuser\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;**C:\Program Files\WindowsPowerShell\Modules**;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\

and the fact that module is not found only with first run after launching the console, moreover - not always. sometimes it works, sometimes it thorws an error.

**Comment by RokeJulianLockhart** [comment]
https://github.com/PowerShell/PowerShell/issues/16679#issuecomment-1823629762
