### ISSUE TITLE
ForEach-Object -Parallel breaks pipeline objects ScriptMethods

### ISSUE THREAD

**Issue by MiguelBarro** [PowerShell/PowerShell#17077]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```pwsh
> $res = 1..3 | % -Parallel { 
   $o = [pscustomobject]@{'a'=$_};
   Add-Member -InputObject $o -Type ScriptMethod -Name GetA -Value {$this.a} -force -PassThru }
> $res.GetA()
```

### Expected behavior

```console
> $res.GetA()
1
2
3
```

which is the actual behavior if `-Parallel` is not used as in:
```pwsh
> $res = 1..3 | % { 
   $o = [pscustomobject]@{'a'=$_};
   Add-Member -InputObject $o -Type ScriptMethod -Name GetA -Value {$this.a} -force -PassThru }
> $res.GetA()
```

### Actual behavior

```console
> $res.GetA()
OperationStopped: Object reference not set to an instance of an object.
```

### Error details

```console
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : MethodInvokerWorker
        DeclaringType : System.Management.Automation.EnumerableOps, System.Management.Automation, Version=7.2.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Object reference not set to an instance of an object.
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Management.Automation
    HResult    : -2147467261
    StackTrace :
   at System.Management.Automation.EnumerableOps.MethodInvokerWorker(CallSite invokeMemberSite, IEnumerator enumerator, Object[] args, ExecutionContext context, List`1 result, Boolean& foundMethod)
   at System.Management.Automation.EnumerableOps.MethodInvoker(PSInvokeMemberBinder binder, Type delegateType, IEnumerator enumerator, Object[] args, Type typeForMessage)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $res.GetA()
    PositionMessage  : At line:1 char:1
                       + $res.GetA()
                       + ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Ooh, that's a fun one. 

I'm not sure there's going to be able to be a solution to this.

PowerShell scriptblocks are bound to the runspace they're created in by design, so yeah attaching a script method to an object and trying to use that in another runspace is going to cause some issues.

Might be something for the documentation of `ForEach-Object` to mention, there's a fair few pitfalls you can hit with `-Parallel` 😔

**Comment by SeeminglyScience** [comment]
I agree it's unlikely to be fixable. A better error message would be ideal though. A NRE should probably never be surfaced to user code.

`Get-Error` results for `$res[0].GetA()` gives a better stack trace:

```python
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : InvokeWithPipe
        DeclaringType : scriptblock
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Object reference not set to an instance of an object.
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Management.Automation
    HResult    : -2147467261
    StackTrace :
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object
dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1
variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior,
Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.PSScriptMethod.InvokeScript(String methodName, ScriptBlock script, Object this, Object[] arguments)
   at System.Management.Automation.PSScriptMethod.Invoke(Object[] arguments)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $res[0].GetA()
    PositionMessage  : At line:1 char:1
                       + $res[0].GetA()
                       + ~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by MiguelBarro** [comment]
I understand the runspace issue on the scriptblocks.
Though, sometimes a workaround is as good as a fix 😅. What about recreating the Scriptblocks in the new runspace when `ForEach-Object` pushes the objects back to the pipeline?
An *ugly as hell* example:
```pwsh
> $res = 1..3 | % -Parallel { $o = [pscustomobject]@{'a'=$_}; `
                      Add-Member -InputObject $o -Type ScriptMethod -Name GetA -Value {$this.a} -force -PassThru} `
            | % { # postprocessing to fix scriptblocks by creating a copy into this runspace
            foreach ( $name in ($_ | Get-Member -MemberType ScriptMethod).name)
            {
                 Add-Member -InputObject $_ -MemberType ScriptMethod -Name $name `
                            -Value ([ScriptBlock]::Create($_.$name.Script)) -Force -PassThru 
            }}
> $res.GetA()
1
3
2
```
Note that `ScriptMethods` and `ScriptProperties` often only reference `$this` contents.

**Comment by kasini3000** [comment]
I remember that the manual suggested:
Thread-safe objects, such as thread-safe queues, thread-safe stacks, thread-safe hash tables, should only be used in foreach-object -Parallel.

**Comment by PaulHigin** [comment]
We already search the Ast for some known thread safety issues in the scriptlbock, but missed this case.  I agree that this should be included.

**Comment by vexx32** [comment]
WG-Engine:

We don't think it's likely this could easily work as might be expected, but we think it's reasonable that we could provide a more informative error message to users when this is attempted. Exposing a NullReferenceException in this case is a bug, and we should have a null check here so that we can give a better error message.

The underlying issue appears to be that the ScriptMethods are attached to a secondary runspace created by ForEach-Object -Parallel, and then called after the secondary runspaces are disposed, creating the scenario where the runspace the scriptblock is bound to has been destroyed.

/cc @sdwheeler it would probably be a good idea to mention in the documentation for `-Parallel` and also the documentation for `Add-Member` that objects with attached script methods cannot be safely passed between runspaces.

**Comment by sdwheeler** [comment]
@vexx32 @PaulHigin Could someone file a [docs issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/new/choose) and include the pertinent details?

**Comment by vexx32** [comment]
Doc issue: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8713
