### ISSUE TITLE
Invoke-Command throws error with supposedly valid parameter combination

### ISSUE THREAD

**Issue by PalmEmanuel** [PowerShell/PowerShell#17205]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When looking at the help documentation for `Invoke-Command`, one of the valid parameter sets suggests that the only mandatory parameter is `-Credential`.

```plaintext
Invoke-Command
      -Credential <PSCredential>
      [-ConfigurationName <String>]
      [-ThrottleLimit <Int32>]
      [-AsJob]
      [-HideComputerName]
      [-ScriptBlock] <ScriptBlock>
      [-RemoteDebug]
      [-InputObject <PSObject>]
      [-ArgumentList <Object[]>]
      [-VMId] <Guid[]>
      [<CommonParameters>]
```

This means that the following command would be a valid way to run a specified `-ScriptBlock` with a provided credential.

```powershell
Invoke-Command -Credential $Cred -ScriptBlock { 'Hello world' }
```

But it results in an error saying it's an invalid combination of parameters.

```plaintext
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

I've tried both newer PowerShell versions as well as Windows PowerShell, and since the problem exists in several versions of the documentation I suspect it's an old bug.

### Expected behavior

```console
PS> $Cred = [pscredential]::new('test', ('123' | ConvertTo-SecureString -AsPlainText))
PS> Invoke-Command -Credential $Cred -ScriptBlock { 'Hello world' }
Hello world
```

### Actual behavior

```console
PS> $Cred = [pscredential]::new('test', ('123' | ConvertTo-SecureString -AsPlainText))
PS> Invoke-Command -Credential $Cred -ScriptBlock { 'Hello world' }
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Parameter set cannot be resolved using the specified named parameters. One or more
parameters issued cannot be used together or an insufficient number of parameters were provided.
    ErrorId           : AmbiguousParameterSet
    Line              : 1
    Offset            : 1
    CommandInvocation :
        MyCommand        : Invoke-Command
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 2
            Keys     :
                Length : 11

                Length : 10
            Values   :
                StartPosition : System.Management.Automation.PSToken
                Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                Ast           : { 'Hello world' }

                UserName : test
                Password : System.Security.SecureString
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 2
                Keys     :
                    Length : 11

                    Length : 10
                Values   :
                    StartPosition : System.Management.Automation.PSToken
                    Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                    Ast           : { 'Hello world' }

                    UserName : test
                    Password : System.Security.SecureString
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 2
                    Keys     :
                        Length : 11

                        Length : 10
                    Values   :
                        StartPosition : System.Management.Automation.PSToken
                        Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                        Ast           : { 'Hello world' }

                        UserName : test
                        Password : System.Security.SecureString
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 2
                        Keys     :
                            Length : 11

                            Length : 10
                        Values   :
                            StartPosition : System.Management.Automation.PSToken
                            Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                            Ast           : { 'Hello world' }

                            UserName : test
                            Password : System.Security.SecureString
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 2
                            Keys     :
                                Length : 11

                                Length : 10
                            Values   :
                                StartPosition : System.Management.Automation.PSToken
                                Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                                Ast           : { 'Hello world' }

                                UserName : test
                                Password : System.Security.SecureString
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 2
                                Keys     :
                                    Length : 11

                                    Length : 10
                                Values   :
                                    StartPosition : System.Management.Automation.PSToken
                                    Id            : 188c8021-e934-4603-b532-8541b78c9ccb
                                    Ast           : { 'Hello world' }

                                    UserName : test
                                    Password : System.Security.SecureString
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 2
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 20
        Line             : Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
        PositionMessage  : At line:1 char:1
                           + Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Invoke-Command
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Parameter set cannot be resolved using the specified named parameters. One or more
parameters issued cannot be used together or an insufficient number of parameters were provided.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Invoke-Command], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.InvokeCommandCommand
        InvocationInfo        :
            MyCommand        : Invoke-Command
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 20
            Line             : Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
            PositionMessage  : At line:1 char:1
                               + Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : ThrowAmbiguousParameterSetException
        DeclaringType : System.Management.Automation.CmdletParameterBinderController,
System.Management.Automation, Version=7.2.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at
System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32
parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
   at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean
prePipelineInput, Boolean setDefault)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Invoke-Command], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.InvokeCommandCommand
InvocationInfo        :
    MyCommand        : Invoke-Command
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 20
    Line             : Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
    PositionMessage  : At line:1 char:1
                       + Invoke-Command -ScriptBlock { 'Hello world' } -Credential $Cred
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PalmEmanuel** [comment]
I seem to have missed that `VMId` was a positional mandatory parameter, closing issue.
