### ISSUE TITLE
ForEach-Object -TimeoutSeconds Does Not Stop In The Mandated Time

### ISSUE THREAD

**Issue by superelitist** [PowerShell/PowerShell#17235]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$NAME_TO_SEARCH = "a_string"
$THROTTLE_LIMIT = 5
$TIMEOUT = 15
Get-ADObject -Filter 'ObjectClass -eq "serviceConnectionPoint" -and Name -eq "Microsoft Hyper-V"' |
ForEach-Object { $_.DistinguishedName.Split(",")[1].replace("CN=","") } |
ForEach-Object -Parallel {
  Get-VM -ComputerName $_ -Name *$($using:NAME_TO_SEARCH)* -ErrorAction SilentlyContinue |
  Select-Object -Property ComputerName, Name, State, Uptime
} -ThrottleLimit $THROTTLE_LIMIT -TimeoutSeconds $TIMEOUT
```

* `-ThrottleLimit 1 -TimeoutSeconds 10` completes in ~13 seconds.
* `-ThrottleLimit 2 -TimeoutSeconds 10` completes in ~14 seconds.
* `-ThrottleLimit 3 -TimeoutSeconds 10` completes in ~18 seconds.
* `-ThrottleLimit 3 -TimeoutSeconds 15` did not complete--I waited about twenty minutes.
* `-ThrottleLimit 4 -TimeoutSeconds 15` completes in ~45 seconds.
* `-ThrottleLimit 5 -TimeoutSeconds 15` completes in ~45 seconds.
* `-ThrottleLimit 5 -TimeoutSeconds 15 -UseNewRunspace` completes in ~638 seconds.
* `-ThrottleLimit 100 -TimeoutSeconds 15` completes in ~220 seconds.
* `-ThrottleLimit 100 -TimeoutSeconds 15 -UseNewRunspace` completes in ~71 seconds.
* Ctrl-C does not appear to cancel running script blocks as documented.
* The error appears anywhere from zero to three times, depending on `-TimeoutSeconds`. It seems apparent that Foreach-Object is indeed stopping the pipeline, but not stopping the scripts.
* I also experimented with a jobs-based version, and ran into a similar problem with `Stop-Job`. I suspect that the actual problem might be in PowerShell's inability to stop the `Get-VM` cmdlet, but there's no feedback to such effect, so I'm shooting in the dark here--the title indicates the *apparent* problem.
* #16507 appears to be related. If what they say is true (PowerShell *cannot* stop some tasks), then it's possible that the issue is with [incorrect/misleading documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/foreach-object?view=powershell-7.2#parameters). I don't believe this is true though: I am certainly capable of stopping the scripts by killing the `pwsh.exe` process. Under the hood, I would expect PowerShell to have even greater control over the code it's running.

### Expected behavior

```console
# after ~ten seconds...
ComputerName Name                     State Uptime
------------ ----                     ----- ------
<host_name>  <vm_name>              Running 2.10:53:54.3990000
...

PS>
```

### Actual behavior

```console
# after ~13-220 seconds...
ComputerName Name                     State Uptime
------------ ----                     ----- ------
<host_name>  <vm_name>              Running 2.10:53:54.3990000
...
InvalidOperation: The pipeline has been stopped.

PS>
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.PipelineStoppedException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The pipeline has been stopped.
            HResult : -2146233087
        CategoryInfo          : OperationStopped: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PipelineStopped
    TargetSite  :
        Name          : Throw
        DeclaringType : System.Runtime.ExceptionServices.ExceptionDispatchInfo
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message     : The pipeline has been stopped.
    Source      : System.Private.CoreLib
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
TargetObject          : System.Management.Automation.PSTasks.PSTask
CategoryInfo          : InvalidOperation: (System.Management.A…tion.PSTasks.PSTask:PSTask) [], PipelineStoppedException
FullyQualifiedErrorId : PSTaskException
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
My guess:
Nothing to do with ForEach-Object-Parallel. The problem is on the left side of the pipe.

```
1..20 | ForEach-Object -ThrottleLimit 10 -Parallel { "$_ start" ;Start-Sleep 15; "$_ end" } #a
1..20 | ForEach-Object -TimeoutSeconds 12  -ThrottleLimit 10 -Parallel { "$_ start" ;Start-Sleep 15; "$_ end" } #b
```
return is 【InvalidOperation: The pipeline has been stopped.】on “b” 


My personal advice:
Instead of the pipe symbol "|", use foreach ($a in $b) {}, which is better for debugging and easier to control the flow, such as BREAK CONTINUE
Instead of -computername, use new-pssession and invoke-command via winrm.

-------

my powershell script framework, which encapsulates new-pssession and invoke-command.

[kasini3000](https://gitee.com/chuanjiao10/kasini3000) site mirror:(https://github.com/kasini3000/kasini3000)   
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

**Comment by PaulHigin** [comment]
The timeout and Ctrl+C command just make a best effort to stop all running PowerShell scripts.  It does not abruptly terminate all threads, but instead sends a stop signal to each running script.  If the script or command ignores the stop signal, or is executing a native API call, the running script may not stop immediately or at all.  This is by design.
