### ISSUE TITLE
FileNotFoundException occurs exclusively after publish Visual Studio project

### ISSUE THREAD

**Issue by FSharpCSharp** [PowerShell/PowerShell#17241]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Take the following [sample project](https://github.com/FSharpCSharp/PowerShellHost) and open it in Visual Studio 2022, run it there, and notice that no runtime error occurs in both debug and release.

Then we publish the Visual Studio project. To do this, right-click on the project in the Solution Explorer and click publish. There you use the publish profile "FolderProfile.pubxml" and click on publish. After the publishing was successful click on "Open Folder" in the Publish dialog of Visual Studio. There you will find the MyApp.exe again and execute it. Then the error mentioned under "Actual behavior" occurs. Under "Expected behavior" you can see the output if you run the project directly from Visual Studio via Debug / Release.

### Expected behavior

```console
Start Execution
<PathToSampleApplication>\bin\Debug\net6.0-windows
```

### Actual behavior

```console
.\MyApp.exe
Start Execution
Unhandled exception. System.Management.Automation.PSSecurityException: AuthorizationManager check failed.
 ---> System.IO.FileNotFoundException: <PathToSampleApplication>\bin\Release\net6.0-windows\publish\win10-x64\Modules\PSDiagnostics\PSDiagnostics.psm1
   at System.Management.Automation.Internal.SecuritySupport.CheckIfFileExists(String filePath)
   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)
   at System.Management.Automation.SignatureHelper.GetSignatureFromCatalog(String filename)
   at System.Management.Automation.SignatureHelper.GetSignature(String fileName, String fileContent)
   at System.Management.Automation.Internal.SecuritySupport.IsProductBinary(String file)
   at Microsoft.PowerShell.PSAuthorizationManager.CheckPolicy(ExternalScriptInfo script, PSHost host, Exception& reason)
   at Microsoft.PowerShell.PSAuthorizationManager.ShouldRun(CommandInfo commandInfo, CommandOrigin origin, PSHost host, Exception& reason)
   at System.Management.Automation.AuthorizationManager.ShouldRunInternal(CommandInfo commandInfo, CommandOrigin origin, PSHost host)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at Application.Test.Program.Main(String[] args) in <PathToSampleApplication>\Program.cs:line 43
```

### Environment data

```powershell
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ALIENQuake** [comment]
@FSharpCSharp Hi,

To fix the problem inside your [sample project](https://github.com/FSharpCSharp/PowerShellHost) change:
`iss.ExecutionPolicy = ExecutionPolicy.Unrestricted;`
to
`iss.ExecutionPolicy = ExecutionPolicy.Bypass;`

Hope that helps.

**Comment by FSharpCSharp** [comment]
@ALIENQuake 
Thanks for the quick reply! Just tried it and it really works. I would not have thought in life that it could be due to something so banal.

But then I still do not understand, and maybe you can also say something about it, why this occurs exclusively with publish. If I, as described above, compiled the project normally within Visual Studio, then I could execute it without further ado. I would just be interested to know why this always worked then.

Thanks for all the help on this!
