### ISSUE TITLE
Invoke-Command pain point from lack of good argument-processing feedback

### ISSUE THREAD

**Issue by kfsone** [PowerShell/PowerShell#17280]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PSVersion 7.2.3

Invoke-Command seems to be a common source of confusion (c.f https://github.com/PowerShell/PowerShell/issues/17205 and many others, plus quora/so questions), for several factors:

1- It is frequently perceived as the command to use in order to execute a command with an argument list stored in a variable, the expectation being:

```
> invoke-command $cmd -argumentlist $arguments
e.g
> $args = $hostname, '-i', $identity
> invoke-command "ssh" -argumentlist $args
```

2- The ambiguity of missing-argument feedback:
```
Win|PS> invoke-command "ssh" -argumentlist (1,2,3)
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

3- The arbitrary mixing of required and optional parameters in help makes it impossible to identify which case invoke-command thinks applied:
```
    Invoke-Command [[-ConnectionUri] <Uri[]>] [-ScriptBlock] <ScriptBlock> [-AllowRedirection] [-ArgumentList <Object[]>] [-AsJob] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] [-CertificateThumbprint <String>] [-ConfigurationName
    <String>] [-Credential <PSCredential>] [-EnableNetworkAccess] [-HideComputerName] [-InDisconnectedSession] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-SessionOption <PSSessionOption>] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [[-ConnectionUri] <Uri[]>] [-FilePath] <String> [-AllowRedirection] [-ArgumentList <Object[]>] [-AsJob] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] [-ConfigurationName <String>] [-Credential <PSCredential>]
    [-EnableNetworkAccess] [-HideComputerName] [-InDisconnectedSession] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-SessionOption <PSSessionOption>] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [[-ComputerName] <String[]>] [-ScriptBlock] <ScriptBlock> [-ApplicationName <String>] [-ArgumentList <Object[]>] [-AsJob] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] [-CertificateThumbprint <String>]
    [-ConfigurationName <String>] [-Credential <PSCredential>] [-EnableNetworkAccess] [-HideComputerName] [-InDisconnectedSession] [-InputObject <PSObject>] [-JobName <String>] [-Port <Int32>] [-RemoteDebug] [-SessionName <String[]>] [-SessionOption <PSSessionOption>] [-ThrottleLimit <Int32>]
    [-UseSSL] [<CommonParameters>]

    Invoke-Command [[-ComputerName] <String[]>] [-FilePath] <String> [-ApplicationName <String>] [-ArgumentList <Object[]>] [-AsJob] [-Authentication {Default | Basic | Negotiate | NegotiateWithImplicitCredential | Credssp | Digest | Kerberos}] [-ConfigurationName <String>] [-Credential
    <PSCredential>] [-EnableNetworkAccess] [-HideComputerName] [-InDisconnectedSession] [-InputObject <PSObject>] [-JobName <String>] [-Port <Int32>] [-RemoteDebug] [-SessionName <String[]>] [-SessionOption <PSSessionOption>] [-ThrottleLimit <Int32>] [-UseSSL] [<CommonParameters>]

    Invoke-Command [[-Session] <PSSession[]>] [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [[-Session] <PSSession[]>] [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-VMId] <Guid[]> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -Credential <PSCredential> [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -Credential <PSCredential> [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] [-ThrottleLimit <Int32>] -VMName <String[]> [<CommonParameters>]

    Invoke-Command [-VMId] <Guid[]> [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -Credential <PSCredential> [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -Credential <PSCredential> [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] [-ThrottleLimit <Int32>] -VMName <String[]> [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] -HostName <String[]> [-InputObject <PSObject>] [-KeyFilePath <String>] [-Port <Int32>] [-RemoteDebug] [-SSHTransport {true}] [-UserName <String>] [<CommonParameters>]

    Invoke-Command [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -ContainerId <String[]> [-HideComputerName] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-RunAsAdministrator] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-ArgumentList <Object[]>] [-AsJob] [-ConfigurationName <String>] -ContainerId <String[]> [-HideComputerName] [-InputObject <PSObject>] [-JobName <String>] [-RemoteDebug] [-RunAsAdministrator] [-ThrottleLimit <Int32>] [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] -SSHConnection <Hashtable[]> [<CommonParameters>]

    Invoke-Command [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] -HostName <String[]> [-InputObject <PSObject>] [-KeyFilePath <String>] [-RemoteDebug] [-SSHTransport {true}] [-UserName <String>] [<CommonParameters>]

    Invoke-Command [-FilePath] <String> [-ArgumentList <Object[]>] [-AsJob] [-HideComputerName] [-InputObject <PSObject>] [-RemoteDebug] -SSHConnection <Hashtable[]> [<CommonParameters>]

    Invoke-Command [-ScriptBlock] <ScriptBlock> [-ArgumentList <Object[]>] [-InputObject <PSObject>] [-NoNewScope] [<CommonParameters>]
```

4- Despite being extensive, the -example's for Invoke-Command do not use argument list, as is relatively common with more complex built-in powershell cmdlets

### Expected behavior

```console
> invoke-command "ssh" -argumentlist (1,2,3)
Invoke-Command: Parameter set cannot be resolved using the named parameters provided. "-ScriptPath" parameter cannot be used with "-ArgumentList"

or

> invoke-command "ssh" -argumentlist (1,2,3)
Invoke-Command: Parameter set cannot be resolved using the named parameters provided without one or more of "-Credential", "-Hostname", ...
```

### Actual behavior

```console
Win|PS> invoke-command "ssh" -argumentlist (1,2,3)
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Error details

```console
Win|PS> Get-Error

Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Parameter set cannot be resolved using the specified named parameters. One or more parameters
issued cannot be used together or an insufficient number of parameters were provided.
    ErrorId           : AmbiguousParameterSet
    Line              : 1
    Offset            : 1
    CommandInvocation :
        MyCommand        : Invoke-Command
        BoundParameters  :
            BoundPositionally :
                Length : 12
            Comparer          : System.OrdinalIgnoreCaseComparer
            Count             : 2
            Keys              :
                Length : 12

                Length : 12
            Values            :
                Length      : 3
                LongLength  : 3
                Rank        : 1
                SyncRoot    :





                IsFixedSize : True
                Count       : 3

                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                    Length : 3
                IsFixedSize : True
                Count       : 1
            SyncRoot          :
                BoundPositionally :
                    Length : 12
                Comparer          : System.OrdinalIgnoreCaseComparer
                Count             : 2
                Keys              :
                    Length : 12

                    Length : 12
                Values            :
                    Length      : 3
                    LongLength  : 3
                    Rank        : 1
                    SyncRoot    :





                    IsFixedSize : True
                    Count       : 3

                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                        Length : 3
                    IsFixedSize : True
                    Count       : 1
                SyncRoot          :
                    BoundPositionally :
                        Length : 12
                    Comparer          : System.OrdinalIgnoreCaseComparer
                    Count             : 2
                    Keys              :
                        Length : 12

                        Length : 12
                    Values            :
                        Length      : 3
                        LongLength  : 3
                        Rank        : 1
                        SyncRoot    :





                        IsFixedSize : True
                        Count       : 3

                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                            Length : 3
                        IsFixedSize : True
                        Count       : 1
                    SyncRoot          :
                        BoundPositionally :
                            Length : 12
                        Comparer          : System.OrdinalIgnoreCaseComparer
                        Count             : 2
                        Keys              :
                            Length : 12

                            Length : 12
                        Values            :
                            Length      : 3
                            LongLength  : 3
                            Rank        : 1
                            SyncRoot    :





                            IsFixedSize : True
                            Count       : 3

                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                Length : 3
                            IsFixedSize : True
                            Count       : 1
                        SyncRoot          :
                            BoundPositionally :
                                Length : 12
                            Comparer          : System.OrdinalIgnoreCaseComparer
                            Count             : 2
                            Keys              :
                                Length : 12

                                Length : 12
                            Values            :
                                Length      : 3
                                LongLength  : 3
                                Rank        : 1
                                SyncRoot    :





                                IsFixedSize : True
                                Count       : 3

                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                    Length : 3
                                IsFixedSize : True
                                Count       : 1
                            SyncRoot          :
                                BoundPositionally :
                                    Length : 12
                                Comparer          : System.OrdinalIgnoreCaseComparer
                                Count             : 2
                                Keys              :
                                    Length : 12

                                    Length : 12
                                Values            :
                                    Length      : 3
                                    LongLength  : 3
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 3

                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1
                                SyncRoot          :
                                    BoundPositionally : …
                                    Comparer          : System.OrdinalIgnoreCaseComparer
                                    Count             : 2
                                    Keys              : …
                                    Values            : …
                                    SyncRoot          : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 4
        Line             : invoke-command "ssh" -argumentlist (1,2,3)
        PositionMessage  : At line:1 char:1
                           + invoke-command "ssh" -argumentlist (1,2,3)
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : invoke-command
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Parameter set cannot be resolved using the specified named parameters. One or more parameters
issued cannot be used together or an insufficient number of parameters were provided.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Invoke-Command], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.InvokeCommandCommand
        InvocationInfo        :
            MyCommand        : Invoke-Command
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 4
            Line             : invoke-command "ssh" -argumentlist (1,2,3)
            PositionMessage  : At line:1 char:1
                               + invoke-command "ssh" -argumentlist (1,2,3)
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : ThrowAmbiguousParameterSetException
        DeclaringType : System.Management.Automation.CmdletParameterBinderController, System.Management.Automation,
Version=7.2.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32
parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
   at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput,
Boolean setDefault)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Invoke-Command], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.InvokeCommandCommand
InvocationInfo        :
    MyCommand        : Invoke-Command
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : invoke-command "ssh" -argumentlist (1,2,3)
    PositionMessage  : At line:1 char:1
                       + invoke-command "ssh" -argumentlist (1,2,3)
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Win|PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Note that _any_ cmdlet / advanced function with multiple parameter sets could benefit from more specific error messages, not just `Invoke-Command` (can't speak to the general feasibility).

**Comment by jdhitsolutions** [comment]
Added to the Cmdlet WG to review

**Comment by SteveL-MSFT** [comment]
This should be reviewed by the Engine WG as it's in the parameter binder

**Comment by SeeminglyScience** [comment]
The Engine WG reviewed this today. We agree that it would be ideal to give a better error message here, but we think a specific message about which parameter set failed will be more complex than it's worth.

We would however like to add a message suggesting the user look at parameter sets via `Get-Command -Syntax` via recommended action. Adding up for grabs.

**Comment by xtqqczze** [comment]
@microsoft-github-policy-service bad bot
