### ISSUE TITLE
Null-coalescing assignment operator ??= Fails When Assigning to Strongly-Typed Variables

### ISSUE THREAD

**Issue by BinaryWizard904** [PowerShell/PowerShell#17282]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The [null-coalescing assignment operator `??=`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#null-coalescing-assignment-operator-) is supposed to "assign the value of its right-hand operand to its left-hand operand only if the left-hand operand evaluates to null." However, if the left-hand operand is strongly typed this assignment fails, even if the type is nullable such as a string.  For example, the one-liner `[string]$y = $null; $y ??= "test"; $y`, silently fails to assign a value to `$y`.

This issue also interacts very oddly with **ValidateSet**, where it actually produces an error.  A simple example of this is the function below.
```
function Test-NullCondAssignment{
	[CmdletBinding()]
	Param (
		[ValidateSet("None","Read","ReadOverrideEffectiveIdentity")]
		[string]$DatasourceAccessRight
	)
	$DatasourceAccessRight ??= "Read"
	$DatasourceAccessRight
}

Test-NullCondAssignment
```
Throws the error:
```
MetadataError: untitled:Untitled-1:7:2
Line |
   7 |      $DatasourceAccessRight ??= "Read"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The variable cannot be validated because the value  is not a valid value for the DatasourceAccessRight variable.
```
However if you remove the typing from `$DatasourceAccessRight` the function succeeds.  If you remove the **ValidateSet** the assignment silently fails just like the one-liner.

### Expected behavior

```console
PS> [string]$y = $null; $y ??= "test"; $y
test
PS> Test-NullCondAssignment
Read
```

### Actual behavior

```console
PS> [string]$y = $null; $y ??= "test"; $y

PS> Test-NullCondAssignment
MetadataError: untitled:Untitled-1:7:2
Line |
   7 |      $DatasourceAccessRight ??= "Read"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The variable cannot be validated because the value  is not a valid value for the DatasourceAccessRight variable.
```

### Error details

```console
Exception             : 
    Type        : System.Management.Automation.ValidationMetadataException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The variable cannot be validated because the value  is not a valid value for the DatasourceAccessRight variable.
            HResult : -2146233087
        CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ValidateSetFailure
        InvocationInfo        : 
            ScriptLineNumber : 7
            OffsetInLine     : 2
            HistoryId        : -1
            ScriptName       : untitled:Untitled-1
            Line             : $DatasourceAccessRight ??= "Read"

            PositionMessage  : At untitled:Untitled-1:7 char:2
                               +     $DatasourceAccessRight ??= "Read"
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSCommandPath    : untitled:Untitled-1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Test-NullCoalescing, untitled:Untitled-1: line 7
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : 
        Name          : SetValue
        DeclaringType : psvariable
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The variable cannot be validated because the value  is not a valid value for the DatasourceAccessRight variable.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  : 
   at System.Management.Automation.PSVariable.SetValue(Object value)
   at System.Management.Automation.VariableOps.SetVariableValue(VariablePath variablePath, Object value, ExecutionContext executionContext, AttributeBaseAst[] attributeAsts)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
FullyQualifiedErrorId : ValidateSetFailure
InvocationInfo        : 
    ScriptLineNumber : 7
    OffsetInLine     : 2
    HistoryId        : -1
    ScriptName       : untitled:Untitled-1
    Line             : $DatasourceAccessRight ??= "Read"

    PositionMessage  : At untitled:Untitled-1:7 char:2
                       +     $DatasourceAccessRight ??= "Read"
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSCommandPath    : untitled:Untitled-1
    CommandOrigin    : Internal
ScriptStackTrace      : at Test-NullCoalescing, untitled:Untitled-1: line 7
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
When you strongly type something as string, `$null` will be converted to an empty string. So while `string` is nullable, it's special cased to be treated like it isn't (and like it's default value is `''`).

This will work as expected with other reference types:

```powershell
[IO.DirectoryInfo] $directory = $null
$directory ??= 'C:\Program Files'
$directory
```

```console
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-r--            5/4/2022 11:08 AM                Program Files
```
