### ISSUE TITLE
Caveat message for the Hombrew Cask produces error

### ISSUE THREAD

**Issue by soyfrien** [PowerShell/PowerShell#17290]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When installing, upgrading, or doing `brew info powershell`, we're given the message:
```
To use Homebrew in PowerShell, set:
  Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/bin/brew shellenv) | Invoke-Expression'
```

When trying this from pwsh I get the error:
`Add-Content: Could not find a part of the path '/Users/louis/.config/powershell/profile.ps1'.`

I do not have a "powershell" directory in `~/.config`.

Is this even necessary? I ask because brew seems to working from PowerShell anyway:
```
PS /Users/louis> brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
mbt
==> Updated Casks
lunar
```

### Expected behavior

```console
PS> Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/bin/brew shellenv) | Invoke-Expression'
PS>
```

### Actual behavior

```console
PS> Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/bin/brew shellenv) | Invoke-Expression'    
Add-Content: Could not find a part of the path '/Users/louis/.config/powershell/profile.ps1'.
PS>

```

### Error details

```console
PS /Users/louis> get-error

Exception             : 
    Type       : System.IO.DirectoryNotFoundException
    TargetSite : 
        Name          : ThrowExceptionForIoErrno
        DeclaringType : Interop, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Could not find a part of the path '/Users/louis/.config/powershell/profile.ps1'.
    Source     : System.Private.CoreLib
    HResult    : -2147024893
    StackTrace : 
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 
preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.PowerShell.Commands.FileSystemContentReaderWriter.CreateStreams(String filePath, String streamName, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Encoding 
fileEncoding)
   at Microsoft.PowerShell.Commands.FileSystemContentReaderWriter..ctor(String path, String streamName, FileMode mode, FileAccess access, FileShare share, Encoding encoding, Boolean 
usingByteEncoding, Boolean waitForChanges, CmdletProvider provider, Boolean isRawStream)
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetContentWriter(String path)
TargetObject          : /Users/louis/.config/powershell/profile.ps1
CategoryInfo          : ObjectNotFound: (/Users/louis/.confi…ershell/profile.ps1:String) [Add-Content], DirectoryNotFoundException
FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand
InvocationInfo        : 
    MyCommand        : Add-Content
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/bin/brew shellenv) | Invoke-Expression'
    PositionMessage  : At line:1 char:1
                       + Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/usr/local/b …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Add-Content
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS /Users/louis> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
> s this even necessary? I ask because brew seems to working from PowerShell anyway:

@TravisEz13, @SteveL-MSFT, and @andschwa, can one of you comment whether that is really necessary?

**Comment by TravisEz13** [comment]
The cask is maintained by homebrew.   To install the formula we support, run `brew install powershell/tap/powershell`

**Comment by soyfrien** [comment]
Thank you, the tap's caveats were so useful. I didn't know about `/etc/shells` or `chsh`.

**Comment by TravisEz13** [comment]
The caveats are here if you think they can be improved:  https://github.com/PowerShell/Homebrew-Tap/blob/master/Formula/powershell.rb#L43

**Comment by soyfrien** [comment]
Great, yes, I was just looking for them.

```

% sudo echo '/usr/local/opt/powershell/bin/pwsh' >> /etc/shells

zsh: permission denied: /etc/shells

% sudo sh -c "echo '/usr/local/opt/powershell/bin/pwsh'>> /etc/shells"

%

```

You're a mind reader.

**Comment by TravisEz13** [comment]
I opened a PR:  https://github.com/PowerShell/Homebrew-Tap/pull/881

**Comment by TravisEz13** [comment]
Never mind,  I just saw your PR:  https://github.com/PowerShell/Homebrew-Tap/pull/880
