### ISSUE TITLE
Navigating to "$env:temp" is not possible, even though the path exists

### ISSUE THREAD

**Issue by batzen** [PowerShell/PowerShell#17359]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to navigate to `$env:temp` i get the error message `Set-Location: An object at the specified path C:\Users\B536F~1.SCH does not exist.`

The value of `$env:temp` is `C:\Users\B536F~1.SCH\AppData\Local\Temp` the full path (non 8.3) is `C:\Users\b.schmidt\AppData\Local\Temp`.

This issue is also present in older PowerShell 5.1 and known there for years, but was never fixed.
If you fix it in PowerShell 7 it might be worth fixing it also in 5.1.

As far as i remember the issue is that the 8.3 version `B536F~1.SCH` is longer than the original `b.schmidt`.
For comparison:
```
B536F~1.SCH (11 chars)
b.schmidt (9 chars)
```

### Expected behavior

```console
Successful navigation without any error.
```

### Actual behavior

```console
No navigation and an error message.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.PSArgumentException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : An object at the specified path C:\Users\B536F~1.SCH does not exist.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : Argument
    Message     : An object at the specified path C:\Users\B536F~1.SCH does not exist.
    ParamName   : path
    TargetSite  :
        Name          : NormalizeThePath
        DeclaringType : Microsoft.PowerShell.Commands.FileSystemProvider
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source      : System.Management.Automation
    HResult     : -2147024809
    StackTrace  :
   at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeThePath(String basepath, Stack`1 tokenizedPathStack)
   at Microsoft.PowerShell.Commands.FileSystemProvider.NormalizeRelativePathHelper(String path, String basePath)
CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand
InvocationInfo        :
    MyCommand        : Set-Location
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : cd $env:temp
    PositionMessage  : At line:1 char:1
                       + cd $env:temp
                       + ~~~~~~~~~~~~
    InvocationName   : cd
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
PowerShell doesn't do the work of resolving the 8.3 path as far as I know, we just delegate to the operating system / .NET APIs to resolve the path. If the TEMP var contains a non usable path there's not much we can do.

I'm not sure how you got an 8.3 path like that into your TEMP variable or what caused it, but I don't think there's much PowerShell can do here. 😕

**Comment by batzen** [comment]
> we just delegate to the operating system / .NET APIs to resolve the path

That does not seem to be true. Having a look at `FileSystemProvider.cs` there is a lot going on before a path reaches the operating system or .NET APIs.
The culprit should be here:
https://github.com/PowerShell/PowerShell/blob/65d8f11aebbdb49b7e28af026d84bf1d38705d37/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L5642

I don't know how to activate tracing for PowerShell. But the tracing output should show that the culprit is there.

> If the TEMP var contains a non usable path there's not much we can do.

The path is totally valid and doing a `cd %temp%` in a batch is not an issue.
Using .NET APIs with that path is not an issue.
So it's clearly a PowerShell issue.

> I'm not sure how you got an 8.3 path like that into your TEMP variable or what caused it (generally as far as I'm aware 8.3 paths aren't used if the name is sufficiently short, so it's odd that the path was recorded in that way)

That's done by windows itself. Try it yourself. Create a new local user account on your machine with the username "b.schmidt" and viola, your user directory is `C:\Users\B536F~1.SCH`.

**Comment by vexx32** [comment]
So calling this code in PowerShell works?

```powershell
[System.IO.Directory]::GetFiles($env:temp)
```

I'm rather surprised we do work with the 8.3 path representation in PowerShell, but if so that definitely sounds like something we need to fix.

**Comment by batzen** [comment]
Calling `[System.IO.Directory]::GetFiles($env:temp)` works fine as the path exists.

> I'm rather surprised we do additional processing on the 8.3 path representation in PowerShell, but if so that definitely sounds like something we need to fix.

There isn't really processing, but the check asserts that `FullName.Length >= current.Length` and that's not the case for that path. As FullName would be `C:\Users\b.schmidt` and current would be `C:\Users\B536F~1.SCH` (as far as i can tell from just reading the code).

**Comment by TheAlienDrew** [comment]
I can confirm this is happening for me too.

Name the user `NWP IT`.

It'll end up showing `C:\Users\NWPIT~1`

I think what's happening here is the filename length checks are ignoring the additional length from `~1`, causing the shortname to appear shorter than than the fullname (when it's not the case).

**Comment by TheAlienDrew** [comment]
Easiest workaround is the following:
```powershell
$envTEMP = (Get-Item -LiteralPath $env:TEMP).FullName # then replace all instances of `env:TEMP` with `envTEMP`
# and/or
$envTMP = (Get-Item -LiteralPath $env:TMP).FullName # then replace all instances of `env:TMP` with `envTMP`
```

**Comment by Jaykul** [comment]
That's a little silly. Why are we checking if the new length is greater than the old? That's not relevant!

**Comment by SteveL-MSFT** [comment]
```powershell
cd c:\progra~1
```

works with 7.4.  `$env:TEMP` (on my Windows system) no longer returns a 8.3 name.  Although I agree that length check seems incorrect, is there still a repro here?

**Comment by batzen** [comment]
Still broken in 7.4.1:

```
PS C:\> cd C:\Users\B536F~1.SCH
Set-Location: An object at the specified path C:\Users\B536F~1.SCH does not exist.
```

Explorer and cmd navigate there without any issues.
The repro is still valid and nothing has changed.
Your sample works because the full name is longer than the 8.3 version.
The bug is triggered if the 8.3 version is longer than the full name, which is the case for `b.schmidt` (full name) vs `B536F~1.SCH` (8.3 name).

It's very sad that, after 2 years and numerous proofs that it's broken i still have to repeat myself over and over again.

**Comment by jimbobmcgee** [comment]
@SteveL-MSFT...

> ```powershell
> cd c:\progra~1
> ```
> 
> works with 7.4. `$env:TEMP` (on my Windows system) no longer returns a 8.3 name. Although I agree that length check seems incorrect, is there still a repro here?

It _would_ work, because the resolved `C:\Program Files` _is_ longer than `C:\progra~1`, so control flow does not enter the subsequent block:

```
if (fsinfo.FullName.Length < currentPath.Length)
{
    throw PSTraceSource.NewArgumentException("path", FileSystemProviderStrings.ItemDoesNotExist, currentPath);
}
```

The issue is that there are times when `currentPath.Length` is _legitimately_ larger than `FullName.Length`, such as when _currentPath_ is set to the NTFS 8.3 (so-called "short name") representation of a path that is _actually_ longer than its normal representation.

The title of the issue is therefore somewhat misleading, as it isn't specific to `$env:TEMP` (although that _is_ an environment variable that _can_ end up being set to the 8.3 path by the OS).

The length check is within a function intented to normalize/canonicalize paths to a one representation.  The comment immediately before the length check _does_ add some context as to why the check was believed to be necessary...

```
// This might happen if you've passed a child name of two or more dots,
// which the .NET APIs treat as the parent directory
if (fsinfo.FullName.Length < currentPath.Length)
```

...so it is clearly an attempt to sanitise user input, but you might need a more-specific check which additionally handles when an 8.3 name has been supplied as _currentPath_.

The obvious difficulty I can see here is that, within an given _currentPath_, any part of that path could be an 8.3 representation, so you'd probably have to iterate over all the parts, building a list of all valid paths (8.3 and normal), then compare to each of them, factoring the filesystem's case-sensitivity.  That could become expensive, for any reasonably-long path (although there might well be existing API which handles this more sensibly).

Instead, you may have to take the length check out and actually handle what the _comment_ is concerned with (i.e. dots in the path crossing directory boundaries) directly.

Perhaps the check is actually unnecessary.  The length check is part of a wider process which might _also_ suffer from the expectation that 8.3 is shorter than normal representation:

```
currentPath = MakePath(currentPath, childName);
var fsinfo = GetFileSystemInfo(currentPath, out bool _);

// Clean up the child name to proper casing and short-path
// expansion if required. Also verify that .NET hasn't over-normalized
// the path
if (fsinfo != null)
{
    // This might happen if you've passed a child name of two or more dots,
    // which the .NET APIs treat as the parent directory
    if (fsinfo.FullName.Length < currentPath.Length)
    {
        throw PSTraceSource.NewArgumentException("path", FileSystemProviderStrings.ItemDoesNotExist, currentPath);
    }

    // Expand the short file name
    if (fsinfo.Name.Length >= childName.Length)
    {
        childName = fsinfo.Name;
    }
}
else
{
    // We couldn't find the item
    if (tokenizedPathStack.Count == 0)
    {
        throw PSTraceSource.NewArgumentException("path", FileSystemProviderStrings.ItemDoesNotExist, currentPath);
    }
}
```

Perhaps this process could be replaced with...

```
var parentfsi = GetFileSystemInfo(currentPath, out bool _);
currentPath = MakePath(currentPath, childName);
var childfsi = GetFileSystemInfo(currentPath, out bool _);

// Clean up the child name to proper casing and short-path
// expansion if required. Also verify that .NET hasn't over-normalized
// the path
if (childfsi != null)
{
    // This might happen if you've passed a child name of two or more dots,
    // which the .NET APIs treat as the parent directory
    if (!string.Equals(parentfsi.FullName, childfsi.Directory.FullName))
    {
        throw PSTraceSource.NewArgumentException("path", FileSystemProviderStrings.ItemDoesNotExist, currentPath);
    }

    // Expand the short file name
    childName = childfsi.Name;
}
else
{
    // We couldn't find the item
    if (tokenizedPathStack.Count == 0)
    {
        throw PSTraceSource.NewArgumentException("path", FileSystemProviderStrings.ItemDoesNotExist, currentPath);
    }
}
```

...although I expect I am missing some nuance, somewhere.

**Comment by batzen** [comment]
@SteveL-MSFT Any news on a fix here? Two years have passed and i still can't navigate to my temp folder.
