### ISSUE TITLE
ArrayList is not accepted as a "Mandatory" parameter to a function if one of its elements is $null

### ISSUE THREAD

**Issue by davidreis97** [PowerShell/PowerShell#17362]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I found, after half an hour of pure confusion, that an instance of `System.Collections.ArrayList` is not accepted as a parameter that is marked as `Mandatory` if one of its elements is $null.

As an example, running the following script:

```
function Test-Function { 
    param(
        [Parameter(Mandatory = $true)] 
        [System.Collections.ArrayList] $phrases) 

    foreach ($phrase in $phrases)
    {
        Write-Host $phrase
    }
}

$myList = New-Object System.Collections.ArrayList
$myList.Add($null) 
$myList.Add("Should this happen?")

Test-Function $myList
```

Results in the following error:

```
Test-Function: C:\Users\DavidReis\Documents\mytest.ps1:16
Line |
  16 |  Test-Function $myList
     |                ~~~~~~~
     | Cannot bind argument to parameter 'phrases' because it is null.
```

Removing the line marked as `$myList.Add($null)` makes the list be accepted, as expected.

### Expected behavior

```console
I would expect a "Mandatory" parameter to accept any ArrayList reference that is not $null, independently of its contents.
```

### Actual behavior

```console
A "Mandatory" parameter rejects ArrayList instances which contain one $null element.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingValidationException
    Message           : Cannot bind argument to parameter 'phrases' because it is null.
    ParameterName     : phrases
    ErrorId           : ParameterArgumentValidationErrorNullNotAllowed
    Line              : 16
    Offset            : 15
    CommandInvocation :
        MyCommand        : Test-Function
        ScriptLineNumber : 16
        OffsetInLine     : 1
        HistoryId        : 13
        ScriptName       : C:\Users\DavidReis\Documents\mytest.ps1
        Line             : Test-Function $myList
        PositionMessage  : At C:\Users\DavidReis\Documents\mytest.ps1:16 char:1
                           + Test-Function $myList
                           + ~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\Users\DavidReis\Documents
        PSCommandPath    : C:\Users\DavidReis\Documents\mytest.ps1
        InvocationName   : Test-Function
        PipelineLength   : 1
        PipelinePosition : 1
        CommandOrigin    : Internal
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind argument to parameter 'phrases' because it is null.
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Test-Function], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-Function
        InvocationInfo        :
            MyCommand        : Test-Function
            ScriptLineNumber : 16
            OffsetInLine     : 15
            HistoryId        : 13
            ScriptName       : C:\Users\DavidReis\Documents\mytest.ps1
            Line             : Test-Function $myList
            PositionMessage  : At C:\Users\DavidReis\Documents\mytest.ps1:16 char:15
                               + Test-Function $myList
                               +               ~~~~~~~
            PSScriptRoot     : C:\Users\DavidReis\Documents
            PSCommandPath    : C:\Users\DavidReis\Documents\mytest.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\Users\DavidReis\Documents\mytest.ps1: line 16
                                at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : BindPositionalParametersInSet
        DeclaringType : System.Management.Automation.ParameterBinderController, System.Management.Automation,
Version=7.2.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets,
Dictionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags,
ParameterBindingException& bindingException)
   at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments,
UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Test-Function], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-Function
InvocationInfo        :
    MyCommand        : Test-Function
    ScriptLineNumber : 16
    OffsetInLine     : 15
    HistoryId        : 13
    ScriptName       : C:\Users\DavidReis\Documents\mytest.ps1
    Line             : Test-Function $myList
    PositionMessage  : At C:\Users\DavidReis\Documents\mytest.ps1:16 char:15
                       + Test-Function $myList
                       +               ~~~~~~~
    PSScriptRoot     : C:\Users\DavidReis\Documents
    PSCommandPath    : C:\Users\DavidReis\Documents\mytest.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\DavidReis\Documents\mytest.ps1: line 16
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

(I stumbled upon this issue in version 5 and reproduced it in 7 to see if this behavior had changed since then.)
```

**Comment by SeeminglyScience** [comment]
`Mandatory` assumes not null, if you want to allow it you need to add `[AllowNull()]`

**Comment by davidreis97** [comment]
Hi @SeeminglyScience, thanks for the quick answer.

I think that `AllowNull()` is not the right answer for this case given that my ArrayList is not null. It's a completely valid instance of a list, it's just that one of its elements happens to be $null.

I personally wouldn't expect this use case to require `AllowNull()`, especially given that using that attribute will make it so that the ArrayList itself could be a `$null` reference, which isn't what I want.

**Comment by SeeminglyScience** [comment]
Yeah there isn't an easy way atm to validate not null without enumerating (aside from implementing your own validation attribute). Opening up to WG-Engine to discuss
