### ISSUE TITLE
Invoke-RestMethod strips Content-Type Header from supplied Headers with -SkipHeaderValidation

### ISSUE THREAD

**Issue by jberkers42** [PowerShell/PowerShell#17434]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Since upgrading to PowerShell 7.2.4 from 7.2.3 we are encountering an issue with some Invoke-RestMethod calls.

When `Invoke-RestMethod` is called with a Headers parameter containing **Content-Type** and a **-SkipHeaderValidation** parameter, the Content-Type Header is stripped from the request.

In previous versions (7.2.3) this was not the case.

When adding the **-ContentType** parameter to the `Invoke-RestMethod` call in 7.2.4, the request returns the expected response.

### Expected behavior

```console
PS> $DdHeaders = @{}
PS> $DdHeaders.Add('Authorization',('Bearer {0}' -f $LrtConfig.LogRhythm.ApiKey.GetNetworkCredential().Password))
PS> $DdHeaders.Add('Content-Type','application/json')
PS> $DdUri = '{0}/lr-drilldown-cache-api/drilldown/8863182' -f $LrtConfig.LogRhythm.BaseUrl
PS> $response = Invoke-RestMethod -Uri $DdUri -Headers $DdHeaders -Method 'GET' -SkipHeaderValidation -SkipCertificateCheck -Verbose -Debug
VERBOSE: GET with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: utf-8
```

### Actual behavior

```console
PS> $DdHeaders = @{}
PS> $DdHeaders.Add('Authorization',('Bearer {0}' -f $LrtConfig.LogRhythm.ApiKey.GetNetworkCredential().Password))
PS> $DdHeaders.Add('Content-Type','application/json')
PS> $DdUri = '{0}/lr-drilldown-cache-api/drilldown/8863182' -f $LrtConfig.LogRhythm.BaseUrl
PS> $response = Invoke-RestMethod -Uri $DdUri -Headers $DdHeaders -Method 'GET' -SkipHeaderValidation -SkipCertificateCheck -Verbose -Debug
VERBOSE: GET with 0-byte payload
VERBOSE: received -byte response of content type application/json
Invoke-RestMethod: {"source":"lr-api-gateway","statusCode":504,"serviceName":"lr-drilldown-cache-api","message":"The request to the upstream 'lr-drilldown-cache-api' timed out.","details":"Error: socket hang up\n    at createHangUpError (_http_client.js:331:15)\n    at Socket.socketCloseListener (_http_client.js:363:23)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:567:12)"}
```

### Error details

```console
PS> Get-Error
Exception             :
    Type       : Microsoft.PowerShell.Commands.HttpResponseException
    Response   : StatusCode: 504, ReasonPhrase: 'Gateway Timeout', Version: 1.1, Content:
System.Net.Http.HttpConnectionResponseContent, Headers:
                 {
                 Strict-Transport-Security: max-age=31536000; includeSubDomains
                 X-XSS-Protection: 1; mode=block
                 X-Content-Type-Options: nosniff
                 X-Frame-Options: SAMEORIGIN
                 Content-Security-Policy: script-src 'self'
                 Date: Wed, 25 May 2022 04:18:18 GMT
                 Connection: keep-alive
                 Transfer-Encoding: chunked
                 Content-Type: application/json
                 }
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Response status code does not indicate success: 504 (Gateway Timeout).
    Source     : System.Management.Automation
    HResult    : -2146233088
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Method: GET, RequestUri:
'https://vhppmdr.dhsoc.ipsec.net.au:8501/lr-drilldown-cache-api/drilldown/614619', Version: 1.1, Content: <null>,
Headers:
                        {
                        Authorization: Bearer #obfuscated#
                        User-Agent: Mozilla/5.0
                        User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.14393; en-AU)
                        User-Agent: PowerShell/7.2.4
                        }
CategoryInfo          : InvalidOperation: (Method: GET, Reques…PowerShell/7.2.4
                        }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
{"source":"lr-api-gateway","statusCode":504,"serviceName":"lr-drilldown-cache-api","message":"The request to the
upstream 'lr-drilldown-cache-api' timed out.","details":"Error: socket hang up\n    at createHangUpError
(_http_client.js:331:15)\n    at Socket.socketCloseListener (_http_client.js:363:23)\n    at emitOne
(events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:567:12)"}
InvocationInfo        :
    MyCommand        : Invoke-RestMethod
    ScriptLineNumber : 1
    OffsetInLine     : 13
    HistoryId        : 49
    Line             : $response = Invoke-RestMethod -Uri $DdUri -Headers $DdHeaders -Method 'GET'
-SkipCertificateCheck -Verbose -Debug -SkipHeaderValidation
    PositionMessage  : At line:1 char:13
                       + $response = Invoke-RestMethod -Uri $DdUri -Headers $DdHeaders -Method …
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-RestMethod
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Not Provided

**Comment by iSazonov** [comment]
@jberkers42 Could you please point an public site we could use to reproduce the issue with?

**Comment by jberkers42** [comment]
@iSazonov I'll see what I can find.  The specific application we are encountering this with is not exposed to the public Internet, and requires a valid Bearer token for authentication.

**Comment by jberkers42** [comment]
@iSazonov There is a public site at [httpbin.org](https://httpbing.org) with a test web page at [RestTestTest](https://resttesttest.com/) that can be used to simulate REST requests and validate what is received.

I have just tested from a Mac as well:

## PowerShell 7.2.3

```
PS> $PsVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> $Headers = @{}
PS> $Headers.Add('Content-Type','application/json')
PS> $response = Invoke-RestMethod -Uri $TestUri -Headers $Headers -Verbose -SkipHeaderValidation
VERBOSE: GET with 0-byte payload
VERBOSE: received 452-byte response of content type application/json
VERBOSE: Content encoding: utf-8
PS> $response.headers

Content-Length  : 0
Content-Type    : application/json
Host            : httpbin.org
User-Agent      : Mozilla/5.0 (Macintosh; Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64; en-GB) PowerShell/7.2.3
X-Amzn-Trace-Id : Root=1-628dc175-17c33fa26e5fe7936519c890
```

## PowerShell 7.2.4

```
PS>$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> $Headers = @{}
PS> $Headers.Add('Content-Type','application/json')
PS> $response = Invoke-RestMethod -Uri $TestUri -Headers $Headers -Verbose -SkipHeaderValidation
VERBOSE: GET with 0-byte payload
VERBOSE: received 383-byte response of content type application/json
VERBOSE: Content encoding: utf-8
PS> > $response.headers                                                                           

Host        User-Agent                                                                                                                                                       X-Amzn-Trace-Id
----        ----------                                                                                                                                                       ---------------
httpbin.org Mozilla/5.0 (Macintosh; Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64; en-GB) PowerShell/7.2.4 Root=1-628dc458-393be3cd1d064af72af5d66f
```

Hopefully this will assist you with testing also.

**Comment by jberkers42** [comment]
Also, FWIW, when supplying the **-ContentType** argument we get the following behaviour:

```
PS> $response = Invoke-RestMethod -Uri $TestUri -Verbose -SkipHeaderValidation -ContentType $Headers.'Content-Type'
VERBOSE: GET with 0-byte payload
VERBOSE: received 452-byte response of content type application/json
VERBOSE: Content encoding: utf-8
PS /Users/jberkers> $response.headers                                                                                              

Content-Length  : 0
Content-Type    : application/json
Host            : httpbin.org
User-Agent      : Mozilla/5.0 (Macintosh; Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64; en-GB) PowerShell/7.2.4
X-Amzn-Trace-Id : Root=1-628dc73c-5d46de286d51aa7150f8b4fb
```
