### ISSUE TITLE
Add-Type fails sporadically with "An item with the same key has already been added"

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#17443]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is elusive but *Add-Type* fails sporadically with *"An item with the same key has been already added"*  when auto-importing module on daily build of PS 7.3 (Preview.4) and PS 7.2.4 as well.

It happens usually on freshly started PowerShell console session.

**What is strange is that importing the failing module again but implicitly with *-Force* switch succeeds (please see the actual behavior)**

This is not unique to specific module. In the attached example the *Add-Type* fails in official release of *PowerShellGet* module (2.2.5) - lines 517 and 796 as well as in my module *KBSystemTools* line 136:

PowerShellGet (file - PSModule.psm1):
~line 517
```powershell
    try {
        $AddType_prams = @{
            TypeDefinition = $InternalWebProxySource
            Language       = 'CSharp'
            ErrorAction    = 'SilentlyContinue'
        }
        if (-not $script:IsCoreCLR -or $script:IsNanoServer) {
            $AddType_prams['ReferencedAssemblies'] = $RequiredAssembliesForInternalWebProxy
        }
>>>EXCEPTION>>>        Add-Type @AddType_prams
    }
    catch {
        Write-Warning -Message "InternalWebProxy: $_"
    }
```
~line 796
```powershell
    try {
        $AddType_prams = @{
            TypeDefinition = $Win32HelpersSource
            Language       = 'CSharp'
            ErrorAction    = 'SilentlyContinue'
        }
        if ((-not $script:IsCoreCLR -or $script:IsNanoServer) -and $RequiredAssembliesForWin32Helpers) {
            $AddType_prams['ReferencedAssemblies'] = $RequiredAssembliesForWin32Helpers
        }
>>>EXCEPTION>>>        Add-Type @AddType_prams
    }
    catch {
        Write-Warning -Message "Win32Helpers: $_"
    }
}
```
KBSystemTools (file - KBSystemTools.psm1):
~ line 136
```powershell
	$Local_ReferencedAssemblies = if ($PSVersionTable.PSVersion.Major -lt 6) {
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'net20', 'Cassia.dll')) -ErrorAction Stop
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'net472', 'NuGet.Versioning.dll')) -ErrorAction Stop
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'net45', 'Figgle.dll')) -ErrorAction Stop
	} else {
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'netstandard20', 'Cassia.dll')) -ErrorAction Stop
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'netstandard20', 'NuGet.Versioning.dll')) -ErrorAction Stop
		Add-Type -Path ([IO.Path]::Combine($PSScriptRoot, 'Assemblies', 'netstandard13', 'Figgle.dll')) -ErrorAction Stop
		[String[]][IO.Directory]::EnumerateFiles([IO.Path]::Combine($PSHOME, 'ref'), '*.dll', [IO.SearchOption]::TopDirectoryOnly)
	}
	Add-Type -TypeDefinition $Local_KBSystemToolsType -ReferencedAssemblies $Local_ReferencedAssemblies -ErrorAction Stop
```

### Expected behavior

```console
Add-Type should not fail.
```

### Actual behavior

```console
[7.2][Bukem@ATLANTIS] > Update-KBModule -Verbose
WARNING: InternalWebProxy: An item with the same key has already been added. Key: 1151434954
WARNING: Win32Helpers: An item with the same key has already been added. Key: -620943648
update-kbmodule: The term 'Update-KBModule' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[7.2][Bukem@ATLANTIS] > Import-Module KBSystemTools -Force -Verbose
VERBOSE: Loading module from path 'D:\USERS\BUKEM\Documents\PowerShell\Modules\KBSystemTools\KBSystemTools.psd1'.
VERBOSE: Removing the imported "Compare-KBCmdletParameter" function.
VERBOSE: Removing the imported "Connect-KBShadowSession" function.
VERBOSE: Removing the imported "Find-KBModulePopular" function.
VERBOSE: Removing the imported "Find-KBModuleUpdate" function.
VERBOSE: Removing the imported "Get-KBMcAfeeEpoPattern" function.
VERBOSE: Removing the imported "Get-KBPublicIP" function.
VERBOSE: Removing the imported "Get-KBSymantecMailSecurityPattern" function.
VERBOSE: Removing the imported "Get-KBWindowsUpdate" function.
VERBOSE: Removing the imported "Install-KBWindowsUpdate" function.
VERBOSE: Removing the imported "Send-KBMouseLeftClick" function.
VERBOSE: Removing the imported "Set-KBPSEConfiguration" function.
VERBOSE: Removing the imported "Test-KBWebAccess" function.
VERBOSE: Removing the imported "Uninstall-KBOutdatedModule" function.
VERBOSE: Removing the imported "Update-KBHelp" function.
VERBOSE: Removing the imported "Update-KBModule" function.
VERBOSE: Removing the imported "Write-KBAsciiBanner" function.
VERBOSE: Loading 'FormatsToProcess' from path 'D:\USERS\BUKEM\Documents\PowerShell\Modules\KBSystemTools\Data\FormatData\KBModulePopular.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'D:\USERS\BUKEM\Documents\PowerShell\Modules\KBSystemTools\Data\FormatData\KBModuleUpdate.Format.ps1xml'.
VERBOSE: Loading module from path 'D:\USERS\BUKEM\Documents\PowerShell\Modules\KBSystemTools\KBSystemTools.psm1'.
VERBOSE: Importing function 'Compare-KBCmdletParameter'.
VERBOSE: Importing function 'Connect-KBShadowSession'.
VERBOSE: Importing function 'Find-KBModulePopular'.
VERBOSE: Importing function 'Find-KBModuleUpdate'.
VERBOSE: Importing function 'Get-KBMcAfeeEpoPattern'.
VERBOSE: Importing function 'Get-KBPublicIP'.
VERBOSE: Importing function 'Get-KBSymantecMailSecurityPattern'.
VERBOSE: Importing function 'Get-KBWindowsUpdate'.
VERBOSE: Importing function 'Install-KBWindowsUpdate'.
VERBOSE: Importing function 'Send-KBMouseLeftClick'.
VERBOSE: Importing function 'Set-KBPSEConfiguration'.
VERBOSE: Importing function 'Test-KBWebAccess'.
VERBOSE: Importing function 'Uninstall-KBOutdatedModule'.
VERBOSE: Importing function 'Update-KBHelp'.
VERBOSE: Importing function 'Update-KBModule'.
VERBOSE: Importing function 'Write-KBAsciiBanner'.
[7.2][Bukem@ATLANTIS] > Update-KBModule -Verbose
VERBOSE: Local module: CompletionPredictor v0.1.0
VERBOSE: Local module: Microsoft.PowerShell.ConsoleGuiTools v0.6.2
VERBOSE: Local module: Microsoft.PowerShell.Crescendo v1.0.0
VERBOSE: Local module: ScriptBlockDisassembler v1.1.0
VERBOSE: Local module: WindowsCompatibility v1.0.0
VERBOSE: Cached PSGallery module: [2022-05-26 18:33:10] Microsoft.PowerShell.Crescendo v1.0.0
VERBOSE: Cached PSGallery module: [2022-05-26 18:33:11] WindowsCompatibility v1.0.0
VERBOSE: Cached PSGallery module: [2022-05-26 18:33:11] Microsoft.PowerShell.ConsoleGuiTools v0.6.2
VERBOSE: Cached PSGallery module: [2022-05-26 18:33:10] CompletionPredictor v0.1.0
VERBOSE: Cached PSGallery module: [2022-05-26 18:33:09] ScriptBlockDisassembler v1.1.0
VERBOSE: Local module is up-to-date: CompletionPredictor
VERBOSE: Local module is up-to-date: Microsoft.PowerShell.ConsoleGuiTools
VERBOSE: Local module is up-to-date: Microsoft.PowerShell.Crescendo
VERBOSE: Local module is up-to-date: ScriptBlockDisassembler
VERBOSE: Local module is up-to-date: WindowsCompatibility
```

### Error details

```console
PSMessageDetails      : 
Exception             : System.Management.Automation.CommandNotFoundException: The term 'Update-KBModule' is not recognized as a name of a cmdlet, function, script file, or executable program.
                        Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
                           at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                           at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
                           at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                           at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                           at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Update-KBModule
CategoryInfo          : ObjectNotFound: (Update-KBModule:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.ArgumentException: An item with the same key has already been added. Key: -1537659534
                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.DoEmitAndLoadAssembly(Compilation compilation, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing()
                           at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, D:\USERS\BUKEM\Documents\PowerShell\Modules\KBSystemTools\KBSystemTools.psm1: line 136
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.ArgumentException: An item with the same key has already been added. Key: -620943648
                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.DoEmitAndLoadAssembly(Compilation compilation, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing()
                           at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1: line 796
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.ArgumentException: An item with the same key has already been added. Key: 1151434954
                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.DoEmitAndLoadAssembly(Compilation compilation, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing()
                           at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1: line 517
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-139-g0882737efb830d8072dc0c2830b50a74ab2166df
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Can you create simple repro steps?

**Comment by kborowinski** [comment]
I'll try to reproduce the issue a few more times and then publish the results here if that's OK.

**Comment by kborowinski** [comment]
@daxian-dbw Sorry for bothering. The exception has happened again. This time on Windows Terminal with single PS 7.3 Preview console:
![wt](https://user-images.githubusercontent.com/16168755/170827526-e0783834-e783-4c4d-ab95-09dea83cdc6d.jpg)

No other PS sessions. Two runspaces, one default, created by *pswh* on startup and other by *CompletionPredictor* module:
![wt2](https://user-images.githubusercontent.com/16168755/170827561-4f36cd3b-4624-4783-a8da-831c0f4ee3e3.jpg)

The only recent change I did is importing *CompletionPredictor* in profile and changing *PredictionSource* to *HistoryAndPlugin*:
![image](https://user-images.githubusercontent.com/16168755/170827683-ee2186d3-519e-4fa9-a960-3313814daf25.png)

I'll reverse those changes at do further testing.

**Comment by kborowinski** [comment]
@daxian-dbw  The exception is definitely caused by interaction between *PSReadLine* and *CompletionPredictor* plugin. I am able to reproduce the issue every single time when *PredictionSource* is set to **HistoryAndPlugin**:

![Animation](https://user-images.githubusercontent.com/16168755/170844387-aaebd052-0112-42a5-947c-c68aa77fb50d.gif)

There is no exception when *CompletionPredictor* module is not imported or *PredictionSource* is set to **History**.

Additional info:
1. The `Update-KBModule` cmdlet is from `KBSystemTools` module *(I can provide the module if requested)*.
2. The `KBSystemTools` module imports `PowerShellGet` module:

![image](https://user-images.githubusercontent.com/16168755/170844573-545a6ff5-7ab9-41b0-ab56-7d40b5b72984.png)

3. To reproduce the exception reliably it is important to type the command `Update-KBModule -Verbose` without completion (no TAB key) and to press *Alt+h* (ShowParameterHelp) after `-Verbose` switch.

Exception:
```powershell

PSMessageDetails      : 
Exception             : System.Management.Automation.PSArgumentException: No parameter matches criteria verbose.
TargetObject          : System.Management.Automation.ProviderCommandHelpInfo
CategoryInfo          : InvalidArgument: (System.Management.AÔÇŽiderCommandHelpInfo:ProviderCommandHelpInfo) [Get-Help], PSArgumentException
FullyQualifiedErrorId : NoParmsFound,Microsoft.PowerShell.Commands.GetHelpCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at PSConsoleHostReadLine, C:\Program Files\PowerShell\Modules\PSReadLine\2.2.5\PSReadLine.psm1: line 7
PipelineIterationInfo : {0, 1}

PSMessageDetails      : 
Exception             : System.ArgumentException: An item with the same key has already been added. Key: -253402996
                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CacheAssembly(Assembly assembly) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1148
                           at Microsoft.PowerShell.Commands.AddTypeCommand.DoEmitAndLoadAssembly(Compilation compilation, EmitOptions emitOptions) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1173
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1072
                           at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing() in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1039
                           at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing() in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 612
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 596
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\program files\powershell\nightly\Modules\PowerShellGet\PSModule.psm1: line 796
                        at PSConsoleHostReadLine, C:\Program Files\PowerShell\Modules\PSReadLine\2.2.5\PSReadLine.psm1: line 7
PipelineIterationInfo : {}

PSMessageDetails      : 
Exception             : System.ArgumentException: An item with the same key has already been added. Key: 85024274
                           at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                           at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CacheAssembly(Assembly assembly) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1148
                           at Microsoft.PowerShell.Commands.AddTypeCommand.DoEmitAndLoadAssembly(Compilation compilation, EmitOptions emitOptions) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1173
                           at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1072
                           at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing() in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 1039
                           at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing() in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.Commands.Utility\commands\utility\AddType.cs:line 612
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 596
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Add-Type], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.AddTypeCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\program files\powershell\nightly\Modules\PowerShellGet\PSModule.psm1: line 517
                        at PSConsoleHostReadLine, C:\Program Files\PowerShell\Modules\PSReadLine\2.2.5\PSReadLine.psm1: line 7
PipelineIterationInfo : {}
```

Profile:
```powershell
Import-Module -Name 'CompletionPredictor'

Set-PSReadLineOption -HistoryNoDuplicates
Set-PSReadLineOption -PredictionSource 'HistoryAndPlugin'

Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

$Parameters = @{
	Key			= 'RightArrow'
	BriefDescription	= 'ForwardCharAndAcceptNextSuggestionWord'
	ScriptBlock		= {
		param($key, $arg)
		$line = $null
		$cursor = $null
		[Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([Ref]$line, [Ref]$cursor)
		if ($cursor -lt $line.Length) {
			[Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar($key, $arg)
		} else {
			[Microsoft.PowerShell.PSConsoleReadLine]::AcceptNextSuggestionWord($key, $arg)
		}
	}
}
Set-PSReadlineKeyHandler @Parameters
```
PowerShell version:
```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-142-g5b6407741cd2b85409538c1b99e858846a1259e7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
