### ISSUE TITLE
PowerShell allows creating an invalid class

### ISSUE THREAD

**Issue by alexbuzzbee** [PowerShell/PowerShell#17470]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a PowerShell class. Extend `System.ValueType` and give it a constructor.
2. Attempt to create an instance of the new type.

### Expected behavior

```console
PS> class MyStruct : System.ValueType {
>>   [int]$field
>>   MyStruct([int]$param) {$field = $param}
>> }
InvalidOperation: PowerShell classes cannot extend System.ValueType.
PS> [MyStruct]::new()
InvalidOperation: Unable to find type [MyStruct].
```

OR

```console
PS> class MyStruct : System.ValueType {
>>   [int]$field
>>   MyStruct([int]$param) {$field = $param}
>> }
PS> [MyStruct]::new()
MyStruct
```

### Actual behavior

```console
PS> class MyStruct : System.ValueType {
>>   [int]$field
>>   MyStruct([int]$param) {$field = $param}
>> }
PS> [MyStruct]::new()
OperationStopped: Common Language Runtime detected an invalid program.
```

### Error details

```console
PS> Get-Error

Exception             :
    Type       : System.InvalidProgramException
    TargetSite : Void .ctor()
    Message    : Common Language Runtime detected an invalid program.
    Data       : System.Collections.ListDictionaryInternal
    Source     : PowerShell Class Assembly
    HResult    : -2146233030
    StackTrace :
   at MyStruct..ctor()
   at CallSite.Target(Closure , CallSite , Type )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], InvalidProgramException
FullyQualifiedErrorId : System.InvalidProgramException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [MyStruct]::new()
    PositionMessage  : At line:1 char:1
                       + [MyStruct]::new()
                       + ~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This seems to be a duplicate of #10231

**Comment by alexbuzzbee** [comment]
It is. I didn't find that when I searched for something.
