### ISSUE TITLE
Split-Path cannot handle sequential colons in the path

### ISSUE THREAD

**Issue by krzydoug** [PowerShell/PowerShell#17501]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying to split a registry path to get the name of the key or property. When that path contains sequential colon characters, Split-Path is incorrectly assuming it's a provider. This is true for both Path and LiteralPath parameters. It works fine if it's only one colon, but 2 or more encounter the bug. 

### Expected behavior

```powershell
PS> Split-Path -Path 'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName::5901' -Leaf

ComputerName::5901
```

### Actual behavior

```powershell
PS> Split-Path -Path 'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName::5901' -Leaf

Split-Path: Cannot find a provider with the name 'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName'. The name is not in the proper format. A provider name can only be alphanumeric characters, or a PowerShell snap-in name that is followed by a single '\', followed by alphanumeric characters
```

### Error details

```powershell
Exception             :
    Type                 : System.Management.Automation.ProviderNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find a provider with the name
'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName'. The name is not in the proper
format. A provider name can only be alphanumeric characters, or a PowerShell snap-in name that
is followed by a single '\', followed by alphanumeric characters.
            HResult : -2146233087
        TargetObject          : HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName
        CategoryInfo          : ObjectNotFound:
(HKEY_CURRENT_USER\s…\History\ComputerName:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ProviderNotFoundBadFormat
    ItemName             : HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName
    SessionStateCategory : CmdletProvider
    TargetSite           :
        Name          : GetProvider
        DeclaringType : System.Management.Automation.SessionStateInternal,
System.Management.Automation, Version=7.2.4.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find a provider with the name
'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName'. The name is not in the proper
format. A provider name can only be alphanumeric characters, or a PowerShell snap-in name that
is followed by a single '\', followed by alphanumeric characters.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.SessionStateInternal.GetProvider(String name)
   at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name)
   at System.Management.Automation.LocationGlobber.GetProviderPath(String path,
CmdletProviderContext context, Boolean isTrusted, ProviderInfo& provider, PSDriveInfo& drive)
   at System.Management.Automation.SessionStateInternal.GetChildName(String path,
CmdletProviderContext context, Boolean useDefaultProvider)
   at System.Management.Automation.PathIntrinsics.ParseChildName(String path,
CmdletProviderContext context, Boolean useDefaultProvider)
   at Microsoft.PowerShell.Commands.SplitPathCommand.ProcessRecord()
TargetObject          : HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName
CategoryInfo          : ObjectNotFound: (HKEY_CURRENT_USER\s…\History\ComputerName:String)
[Split-Path], ProviderNotFoundException
FullyQualifiedErrorId : ProviderNotFoundBadFormat,Microsoft.PowerShell.Commands.SplitPathCommand
InvocationInfo        :
    MyCommand        : Split-Path
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 20
    Line             : split-path -Path
'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName::5901' -Leaf
    PositionMessage  : At line:1 char:1
                       + split-path -Path 'HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : split-path
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
`::` designates a PowerShell provider in the path ,if you specify the provider for the path you are trying to split 

`split-path -path 'Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\software\TightVNC\Viewer\History\ComputerName::5901'  -leaf`

It works so does a drive.   
`split-path -path 'HKCU:software\TightVNC\Viewer\History\ComputerName::5901'  -leaf`

But "HKEY_CURRENT_USER" isn't a valid start to a PowerShell path, it's either the `Microsoft.PowerShell.Core\Registry::` provider.  
 or the `HKCU:` _drive_ (and if that is the current drive the path can begin `\Software`  but `::` in the name will make that an invalid path)
