### ISSUE TITLE
ErrorRecord - Garbled `Exception.Message` When Text Contains `\r\n`

### ISSUE THREAD

**Issue by thecliguy** [PowerShell/PowerShell#17507]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've discovered that an `ErrorRecord` produces a garbled `Exception.Message` when the text contains `\r\n` _(Windows style)_ line endings.

Steps performed:
  * Use `Get-Content` to obtain the content of a text file containing `env = DEV` on three separate lines with `\r\n` line endings.
  * Use `ConvertFrom-StringData` against the file content. An error will occur due to the repetition of the key.
  * Inspect the value of `$Error.Exception.Message`. The message should be `Data item 'env' in line 'env = DEV' is already defined.` but is shown as `' is already defined. e 'env = DEV`.

Repeating the steps above with a file containing `\n` line endings results in `$Error.Exception.Message` being displayed correctly.

### Expected behavior

```console
`$Error.Exception.Message` should show `Data item 'env' in line 'env = DEV' is already defined.` but instead shows `' is already defined. e 'env = DEV`.
```

### Actual behavior

```console
PS C:\> $string = Get-Content 'C:\bitbucket\settings-crlf.txt' -Raw
PS C:\> $string
env = DEV
env = DEV
env = DEV
PS C:\> $string.Replace("`r", '\r').Replace("`n", '\n')
env = DEV\r\nenv = DEV\r\nenv = DEV
PS C:\> ConvertFrom-StringData $string
ConvertFrom-StringData: Data item 'env' in line 'env = DEV' is already defined.
PS C:\> $Error.Exception

ErrorRecord    : Data item 'env' in line 'env = DEV' is already defined.
TargetSite     : Void ProcessRecord()
Message        : Data item 'env' in line 'env = DEV' is already defined.
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079
StackTrace     :    at Microsoft.PowerShell.Commands.ConvertFromStringDataCommand.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()


PS C:\> $Error.Exception.Message
' is already defined. e 'env = DEV
PS C:\> $Error.Clear()
PS C:\> $string = Get-Content 'C:\bitbucket\settings-lf.txt' -Raw
PS C:\> $string
env = DEV
env = DEV
env = DEV
PS C:\> $string.Replace("`r", '\r').Replace("`n", '\n')
env = DEV\nenv = DEV\nenv = DEV
PS C:\> ConvertFrom-StringData $string
ConvertFrom-StringData: Data item 'env' in line 'env = DEV' is already defined.
PS C:\> $Error.Exception

ErrorRecord    : Data item 'env' in line 'env = DEV' is already defined.
TargetSite     : Void ProcessRecord()
Message        : Data item 'env' in line 'env = DEV' is already defined.
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079
StackTrace     :    at Microsoft.PowerShell.Commands.ConvertFromStringDataCommand.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()


PS C:\> $Error.Exception.Message
Data item 'env' in line 'env = DEV' is already defined.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It looks like the cmdlet creating the error is stripping LF but leaving CR
```
$error[0].exception.message -replace "`r","\r" -replace "`n","\n"
Data item 'env' in line 'env = dev\r' is already defined.
```

In fact looking at 
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-StringData.cs 

Line 58 
```
            string[] lines = _stringData.Split('\n');

            foreach (string line in lines)
            {
                string s = line.Trim();
```

Means each  `line` will end with \r and `s` will have it removed

Then the error is thrown which is used ... 
Line 70
```
                    throw PSTraceSource.NewInvalidOperationException(
                        ConvertFromStringData.InvalidDataLine,
                        line);
```
Line 80
```
                    throw PSTraceSource.NewInvalidOperationException(
                        ConvertFromStringData.DataItemAlreadyDefined,
                        line,
                        name);
```

if those use `s` instead of line that should fix it.
