### ISSUE TITLE
ProxyCommand breaks ValidateRange for enum-parameters

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#17546]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
function Test-EnumValidation {
    param(
        [ValidateSet([Microsoft.PowerShell.ExecutionPolicy]::Unrestricted, [Microsoft.PowerShell.ExecutionPolicy]::Undefined)]
        [Microsoft.PowerShell.ExecutionPolicy]$Works,

        [ValidateRange([Microsoft.PowerShell.ExecutionPolicy]::Unrestricted, [Microsoft.PowerShell.ExecutionPolicy]::Undefined)]
        [Microsoft.PowerShell.ExecutionPolicy]$Fails
    )
}


$m = New-Object System.Management.Automation.CommandMetaData (Get-Command Test-EnumValidation)
$s = [System.Management.Automation.ProxyCommand]::Create($m)

$function:proxy = [scriptblock]::Create($s)

# fails with .ctor exception
proxy

# if we check the generated function, we see that `ValidateRange` got unquoted strings as arguments in the proxycommand
$s

...
param(
    [ValidateSet('Unrestricted','Undefined')]
    [Microsoft.PowerShell.ExecutionPolicy]
    ${Works},

    [ValidateRange(Unrestricted,Undefined)]
    [Microsoft.PowerShell.ExecutionPolicy]
    ${Fails})
....
```

### Expected behavior

`proxy` should work without errors

### Actual behavior

`proxy` throws MethodException due to missing overload.

### Error details

```powershell
Exception             :
    Type        : System.Management.Automation.MethodException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find an overload for ".ctor" and the argument count: "0".
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodCountCouldNotFindBest
        InvocationInfo        :
            ScriptLineNumber : 7
            OffsetInLine     : 5
            HistoryId        : -1
            Line             : [ValidateRange(Unrestricted, Undefined)]

            PositionMessage  : At line:7 char:5
                               +     [ValidateRange(Unrestricted, Undefined)]
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : GetAttribute
        DeclaringType : System.Management.Automation.Language.Compiler, System.Management.Automation, Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Cannot find an overload for ".ctor" and the argument count: "0".
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.Language.Compiler.GetAttribute(AttributeAst attributeAst)
   at System.Management.Automation.Language.AttributeAst.GetAttribute()
   at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
   at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
   at System.Management.Automation.Language.ScriptBlockAst.System.Management.Automation.Language.IParameterMetadataProvider.GetParameterMetadata(Boolean automaticPositions, Boolean& usesCmdletBinding)
   at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
   at System.Management.Automation.CompiledScriptBlockData.get_ObsoleteAttribute()
   at System.Management.Automation.DlrScriptCommandProcessor.Init()
   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionCont
ext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandR
edirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
InvocationInfo        :
    ScriptLineNumber : 7
    OffsetInLine     : 5
    HistoryId        : -1
    Line             : [ValidateRange(Unrestricted, Undefined)]

    PositionMessage  : At line:7 char:5
                       +     [ValidateRange(Unrestricted, Undefined)]
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fflaten** [comment]
Looks like it's missing another condition here. If `rangeType` is enum, prefix MinRange/MaxRange-values with `[${rangeType.FullName}]::`
https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/System.Management.Automation/engine/TypeMetadata.cs#L930-L945


```powershell
$m = New-Object System.Management.Automation.CommandMetaData (Get-Command Start-BitsTransfer)
$m.Parameters['Fails'].Attributes[1] 

    MinRange  MaxRange TypeId
    --------  -------- ------
Unrestricted Undefined System.Management.Automation.ValidateRangeAttribute

$m.Parameters['Fails'].Attributes[1].MaxRange.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ExecutionPolicy                          System.Enum
```

**Comment by fflaten** [comment]
Using ValidateRange like this should be discouraged in general for poor usability.

```powershell
# This parameter
[ValidateRange([Microsoft.PowerShell.ExecutionPolicy]::Unrestricted, [Microsoft.PowerShell.ExecutionPolicy]::AllSigned)]
[Microsoft.PowerShell.ExecutionPolicy]$UntypedBroken

# Will fail like this
> test -UntypedBroken Bypass    
test: Cannot validate argument on parameter 'UntypedBroken'. The Bypass argument is greater than the maximum allowed range of AllSigned. Supply an argument that is less than or equal to AllSigned and then try the command again.
```

However the tabcomplete is sorted, so they'd have to get all enum-values to figure out the allowed range
```powershell
> test -UntypedBroken       
AllSigned     Bypass        Default       RemoteSigned  Restricted    Undefined     Unrestricted

> [enum]::GetValues([Microsoft.PowerShell.ExecutionPolicy])
Unrestricted
RemoteSigned
AllSigned
Restricted
Restricted
Bypass
Undefined
```

Using ValidateSet the tabcomplete will still show all, but at least the user valid options in the error
```
test: Cannot validate argument on parameter 'UntypedBroken'. The argument "Bypass" does not belong to the set "Unrestricted,AllSigned" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
```

Maybe the error message should be fixed in a separate issue and PR to be more clear when using enum ranges?
