### ISSUE TITLE
Unable to run ps1 scripts that are in path if they start with a number

### ISSUE THREAD

**Issue by github-account1111** [PowerShell/PowerShell#17547]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Name the script starting with a number.
E.g. `20220611-robocopy.ps1`, where `20220611` signifies creation date.
1. Add the script's path to path.
1. Run `./20220611-robocopy.ps1` from a different location.

### Expected behavior

```console
No errors.
```

### Actual behavior

```console
./20220611-robocopy.ps1: The term './20220611-robocopy.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
```


### Error details

```console
PS > Get-Error

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term './20220611-robocopy.ps1' is not recognized as a name of a cmdlet, function, script file,
or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
            HResult : -2146233087
        TargetObject          : ./20220611-robocopy.ps1
        CategoryInfo          : ObjectNotFound: (./20220611-robocopy.ps1:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 1
            Line             : ./20220611-robocopy.ps1 -Restore
            PositionMessage  : At line:1 char:1
                               + ./20220611-robocopy.ps1 -Restore
                               + ~~~~~~~~~~~~~~~~~~~~~
            InvocationName   : ./20220611-robocopy.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : ./20220611-robocopy.ps1
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation,
Version=7.2.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term './20220611-robocopy.ps1' is not recognized as a name of a cmdlet, function, script file, or
executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin
commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[]
commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : ./20220611-robocopy.ps1
CategoryInfo          : ObjectNotFound: (./20220611-robocopy.ps1:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : ./20220611-robocopy.ps1 -Restore
    PositionMessage  : At line:1 char:1
                       + ./20220611-robocopy.ps1 -Restore
                       + ~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : ./20220611-robocopy.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> Run ./20220611-robocopy.ps1 from a different location.

This is current directory.

**Comment by ThomasNieto** [comment]
This is most likely because PowerShell is trying to treat is as a command since it has a hyphen. You can workaround this by doing one of the following things.

```powershell
# Run using the full path name instead of 20220611-robocopy.ps1
 ./20220611-robocopy.ps1

# Place a non-number character before the hyphen
20220611a-robocopy.ps1

# Remove the hyphen
20220611_robocopy.ps1
```
