### ISSUE TITLE
Get-Command can't get parameters for alias to local function when in a different module sesssionstate

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#17629]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When creating an alias for local function and passing `AliasInfo` into a different module state, the module code is unable to fetch parameters from `AliasInfo` because `Parameters` is null.

Repro:
```powershell
Get-Module funcModule | Remove-Module
New-Module funcModule { 
    function moduleFunc ($Param1234) { }
} | Import-Module

Get-Module testModule | Remove-Module
New-Module testModule { 
    function test($localAlias, $localFunc, $moduleFunc, $localAlias2) {
        "Running in $($ExecutionContext.SessionState.Module.name)"
        "Script Function $($localFunc.Name) contains parameters $($null -ne $localFunc.Parameters)"
        "Script Alias $($localAlias.Name) contains parameters $($null -ne $localAlias.Parameters)"
        "Module Function $($moduleFunc.Name) contains parameters $($null -ne $moduleFunc.Parameters)"
        "Script Alias $($localAlias2.Name) for module func contains parameters $($null -ne $localAlias2.Parameters)"
        
        #Try accessing AliasInfo.Parameters for the local function
        $localAlias.Parameters.PSBase.ContainsKey('MyParam1')
    }
} | Import-Module

# running in a local scope. dot-sourcing this would work because the function is created in the root
& {
    function scriptFunc ($MyParam1) { }
    Set-Alias -Name alias1 -Value scriptFunc
    Set-Alias -Name alias2 -Value moduleFunc
    test -localFunc (Get-Command scriptFunc) -localAlias (Get-Command alias1) -moduleFunc (Get-Command moduleFunc) -localAlias2 (Get-Command alias2)
}
```

Related: https://github.com/pester/Pester/issues/1431#issuecomment-1174989179

### Expected behavior

```console
# Notice the second line. Parameters dict available and can find Parameter-key at the end

Running in testModule
Script Function scriptFunc contains parameters True
Script Alias alias1 contains parameters True
Module Function moduleFunc contains parameters True
Script Alias alias2 for module func contains parameters True
True
```

### Actual behavior

```console
# Notice the second line + exception

Running in testModule
Script Function scriptFunc contains parameters True
Script Alias alias1 contains parameters False
Module Function moduleFunc contains parameters True
Script Alias alias2 for module func contains parameters True
InvalidOperation:
Line |
  10 |          $localAlias.Parameters.PSBase.ContainsKey('MyParam1')
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : You cannot call a method on a null-valued expression.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvokeMethodOnNull
        InvocationInfo        :
            ScriptLineNumber : 10
            OffsetInLine     : 9
            HistoryId        : -1
            Line             :         $localAlias.Parameters.PSBase.ContainsKey('MyParam1')

            PositionMessage  : At line:10 char:9
                               +         $localAlias.Parameters.PSBase.ContainsKey('MyParam1')
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at test, <No file>: line 10
                                at <ScriptBlock>, <No file>: line 5
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.String)
    Message     : You cannot call a method on a null-valued expression.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
InvocationInfo        :
    ScriptLineNumber : 10
    OffsetInLine     : 9
    HistoryId        : -1
    Line             :         $localAlias.Parameters.PSBase.ContainsKey('MyParam1')

    PositionMessage  : At line:10 char:9
                       +         $localAlias.Parameters.PSBase.ContainsKey('MyParam1')
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at test, <No file>: line 10
                        at <ScriptBlock>, <No file>: line 5
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
I play with your sample and I found this workaround.

I'll let someone else explain why there's this behavior but it's probably performance related.

```
& {
    function scriptFunc ($MyParam1) { }
    Set-Alias -Name alias1 -Value scriptFunc
    Set-Alias -Name alias2 -Value moduleFunc
    $alias1 = Get-Command alias1
    $alias2 = Get-Command alias2
    # Force Parameters enumeration
    $null = $alias1.Parameters, $alias2.Parameters
    test -localFunc (Get-Command scriptFunc) -localAlias (Get-Command alias1) -moduleFunc (Get-Command moduleFunc) -localAlias2 (Get-Command alias2)
}
```

Short Version
```
& {
    function scriptFunc ($MyParam1) { }
    Set-Alias -Name alias1 -Value scriptFunc
    Set-Alias -Name alias2 -Value moduleFunc
    test -localFunc (Get-Command scriptFunc) -localAlias (Get-Command alias1 | Where Parameters) -moduleFunc (Get-Command moduleFunc) -localAlias2 (Get-Command alias2 | Where Parameters)
}
```

**Comment by daxian-dbw** [comment]
The reported behavior is due to the fact that `AliasInfo` is delay resolved.

When calling `Set-Alias -Name alias1 -Value scriptFunc`, `scriptFunc` is not immediately resolved to the local function, but is just stored as the name. The command resolution doesn't happen until needed, such as when you access `AliasInfo.Parameters`.

In the repro, when `AliasInfo.Parameters` is accessed, it's in the scope `local2` in the diagram below. From within `local2`, command discovery is not able to find the simple function `scriptFunc`, because the scope `local1` in the diagram that contains the function `scriptFunc` is not in the scope chain where `local2` is at. 

![image](https://user-images.githubusercontent.com/127450/202778143-67cb32d8-dc02-4cce-adde-99970d385f05.png)

The alias to `moduleFunc` works fine in the repro because `moduleFunc` was already exported to the global scope when importing `funcModule`.

So, this is a by design behavior, and any change to it would be a breaking change in behavior.
As a workaround, you can call `$null = AliasInfo.ResolvedCommand` before calling the `test` function in the repro, so as to force the resolution to happen within the scope `local1`.

**Comment by fflaten** [comment]
Thanks for the WG review and detailed explanation @daxian-dbw 👍
Hopefully this issue will help others who might hit this, though I doubt many will notice.

In Pester we unfortunately won't be able to automatically call `ResolvedCommand` in the correct state, so we'll just detect the issue and provide the user with [workarounds](https://github.com/pester/Pester/pull/2233).
