### ISSUE TITLE
New-Object -ComObject does not support instantiation by class identifier (CLSID)

### ISSUE THREAD

**Issue by kirillkovalenko** [PowerShell/PowerShell#17626]
### Steps to reproduce

PS> $o = New-Object -ComObject "{0444EB80-3B35-4108-B52B-DEB178AD3064}"

### Expected behavior

```console
It works
```

### Actual behavior

```console
New-Object: Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
```

### Error details

```console
Exception             :
    Type       : System.Runtime.InteropServices.COMException
    ErrorCode  : -2147221164
    TargetSite :
        Name          : AllocateComObject
        DeclaringType : System.RuntimeTypeHandle
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed due to the following
error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
    Source     : System.Private.CoreLib
    HResult    : -2147221164
    StackTrace :
   at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Microsoft.PowerShell.Commands.NewObjectCommand.SafeCreateInstance(Type t)
CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand
InvocationInfo        :
    MyCommand        : New-Object
    ScriptLineNumber : 1
    OffsetInLine     : 6
    HistoryId        : 1
    Line             : $o = New-Object -ComObject "{0444EB80-3B35-4108-B52B-DEB178AD3064}"
    PositionMessage  : At line:1 char:6
                       + $o = New-Object -ComObject "{0444EB80-3B35-4108-B52B-DEB178AD3064}"
                       +      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I get REGDB_E_CLASSNOTREG in pwsh and WinPS too. What is 0444EB80-3B35-4108-B52B-DEB178AD3064 class?

**Comment by fMichaleczek** [comment]
@iSazonov same as you on my Windows 10, 0444EB80-3B35-4108-B52B-DEB178AD3064 >Class not registered

> New-Object -ComObject does not support instantiation by class identifier (CLSID)(https://github.com/PowerShell/PowerShell/issues/17626#)

 I made a PowerShell workaround/prototype. 

```
function Resolve-ComObject {
    param([Parameter(Mandatory)] [Guid] $CLSID)
    begin {
        if (-not('Ole32.Resolve' -as 'Type')) {
            Add-Type -Namespace Ole32 -Name Resolve -MemberDefinition @'
[DllImport("ole32.dll")]
public static extern int ProgIDFromCLSID(
    [In()]ref Guid clsid, 
    [MarshalAs(UnmanagedType.LPWStr)]out string lplpszProgID);
'@
        }
        $progId = [string]::Empty
        $errorCode = [Ole32.Resolve]::ProgIDFromCLSID([ref]$CLSID, [ref]$progId)
        if ($errorCode -eq 0) {
            $progID
        } else {
            Write-Error -Exception ([System.ComponentModel.Win32Exception]::new($errorCode))
        }
    }
}
```

```
PS> Resolve-ComObject 72C24DD5-D70A-438B-8A42-98424B88AFB8
WScript.Shell.1

PS> Resolve-ComObject 093FF999-1EA0-4079-9525-9614C3504B74
> WScript.Network.1
```

**Comment by kirillkovalenko** [comment]
> I get REGDB_E_CLASSNOTREG in pwsh and WinPS too. What is 0444EB80-3B35-4108-B52B-DEB178AD3064 class?

My own class. I does not matter. Other CLSIDs give the same behavior.

**Comment by kirillkovalenko** [comment]
> Can also do
> 
> ```powershell
> $comObject = [Activator]::CreateInstance([type]::GetTypeFromCLSID($guid))
> ```

Yes, I can. But why should I?

**Comment by scriptingstudio** [comment]
simple workaround
```powershell
function New-ComObject ([alias('name')]$guid) {
    if ($guid -as [guid]) {
        [Activator]::CreateInstance([type]::GetTypeFromCLSID($guid))
    } else {
        New-Object -ComObject $guid
    }
}
```

**Comment by fMichaleczek** [comment]
> > Can also do
> > ```powershell
> > $comObject = [Activator]::CreateInstance([type]::GetTypeFromCLSID($guid))
> > ```
> 
> Yes, I can. But why should I?

As a developper, you should declare a registry key to resolve your ProgID to your CLSID.
https://docs.microsoft.com/en-us/windows/win32/com/-progid--key

Then New-Object -ComObject <yourProgId> will work.

**Comment by SeeminglyScience** [comment]
> Yes, I can. But why should I?

I was providing a work around, but also it's a rare use case. Either way attaching the Cmdlets WG for discussion
