### ISSUE TITLE
can't omit .\ when running commands in current working directory

### ISSUE THREAD

**Issue by jeffythedragonslayer** [PowerShell/PowerShell#17652]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In this document,

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7.2

we have:

> As a security feature, PowerShell does not run executable (native) commands, including PowerShell scripts, unless the command is located in a path that is listed in the Path environment variable $env:path or unless you specify the path to the script file.

When I put "." in my PATH environment variable, I still can't run commands without .\

Why I can't I override this behavior?  Unix shells allow me to do this.  Is there another way?

### Expected behavior

```console
PS E:\echotest> echo.bat
hi
PS E:\echotest>
```

### Actual behavior

```console
PS E:\echotest> echo.bat
echo.bat: The term 'echo.bat' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command echo.bat was not found, but does exist in the current location. PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\echo.bat". See "get-help about_Command_Precedence" for more details.
PS E:\echotest>
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'echo.bat' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : echo.bat
        CategoryInfo          : ObjectNotFound: (echo.bat:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 6
            Line             : echo.bat
            PositionMessage  : At line:1 char:1
                               + echo.bat
                               + ~~~~~~~~
            InvocationName   : echo.bat
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : echo.bat
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.2.5.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'echo.bat' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : echo.bat
CategoryInfo          : ObjectNotFound: (echo.bat:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 6
    Line             : echo.bat
    PositionMessage  : At line:1 char:1
                       + echo.bat
                       + ~~~~~~~~
    InvocationName   : echo.bat
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> Why I can't I override this behavior? Unix shells allow me to do this. Is there another way?

In Windows (unlike Unix) the current directory is in the PATH by design. If you add `.` to the PATH environment variable you're doing an useless job. To avoid typing `.\` you can try rewrite `$env:PATH` in `$funcion:prompt`, something like:

```powershell
# $profile

$env:Path += ";$pwd"

function prompt {
...
$env:Path = $env:PATH -replace ';[^;]+$', ";$pwd"
}
```

**Comment by jhoneill** [comment]
> > Why I can't I override this behavior? Unix shells allow me to do this. Is there another way?
> 
> In Windows (unlike Unix) the current directory is in the PATH by design. If you add `.` to the PATH environment variable you're doing an useless job. To avoid typing `.\` you can try to rewrite `$env:PATH` in `$funcion:prompt`, something like:
> 

@237dmitry   Sorry, that's not correct.   In `Cmd`  the current directory is treated as being on the path as it was in command.com and CP/M. PowerShell does not, and explains that it does not. 

![image](https://user-images.githubusercontent.com/16209593/178100828-870385c5-fbd4-437a-a0ff-98ae2a0354a2.png)

Using prompt to do it is not very reliable; `cd <apppath>; <appName>` wouldn't work 


Because I have scripts in my `WindowsPowerShell` directory which I need to run in PowerShell 7 where the profile directory is `PowerShell`
I have these 4 lines in my profile - the last one handles the issue of modules sometimes not being on `PSModulepath.`  
```
$psDir = Join-path ([System.Environment]::GetFolderPath( [System.Environment+SpecialFolder]::MyDocuments)) "\windowsPowershell"
if (-not (Test-Path $psDir)) {$psdir = $PSScriptRoot}
Set-Item -Path "Env:\PATH" (".;$psDir\;"+(Get-Content "ENV:\PATH"))  #Linux is case sensitive and uses "PATH"; windows isnt and uses "Path".
if ($env:PSModulePath -notmatch [regex]::Escape($psDir)) { $env:PSModulePath += ";$psDir\Modules" }
 ```


@jeffythedragonslayer  - you want a version of line 3 -  I think some variation of     
`Set-Item -Path "Env:\PATH" (".;"+(Get-Content "ENV:\PATH") ) `     
has been in my profile since 2007 or 2008 - and if I trust my memory just setting it in the Path environment variable before PowerShell starts doesn't work, you need to do it in the PowerShell session.  I can't recall if there is a reason I couldn't use `$env:path` and used `Set-item` and `Get-Content`
 
That works. 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/16209593/178101014-e761e9f0-1502-4912-9490-d2c3a5d26a51.png">

**Comment by 237dmitry** [comment]
> PowerShell does not

This is a security restriction. Is not it so?

> Using prompt to do it is not very reliable; `cd <apppath>; <appName>` wouldn't work

I will note that I am absolutely satisfied with how it is now.  I just suggested a solution. And, I don't have any file with the ';' symbol in its full name.

**Comment by jhoneill** [comment]
> > PowerShell does not
> 
> This is a security restriction. Is not it so?
Because a malicious script could be placed in the users directory with a name like "notepad.ps1" powershell broke with previous practice so that in its default state things were slightly more secure. It is also easy to add "." but hard to remove it.  So following "secure by default" is good and the inconvenience is small.  


> 
> > Using prompt to do it is not very reliable; `cd <apppath>; <appName>` wouldn't work
> 
> I will note that I am absolutely satisfied with how it is now. I just suggested a solution. And, I don't have any file with the ';' symbol in its full name.

You wouldn't have files with ; in their name. But you might want to do 

```
cd 'C:\Program Files\Notepad++\'  ;   'Notepad++.exe'
```
entering two commands as one.

**Comment by 237dmitry** [comment]
> entering two commands as one.

My variant does not work ((

**Comment by rkeithhill** [comment]
This is a security feature that you could override by adding `.` to your path.  It's not something I would do.  And I would NOT RECOMMEND it but a quick test indicates it works:
```powershell
PS> $env:PATH += "."  # Don't do this!
PS> '@echo "This is a bat script"' > echo.bat
PS> echo.bat
"This is a bat script"
```
The reason PowerShell doesn't automatically run scripts in the current dir is that someone might put `.` at the **head** of their PATH and then bad things can happen.  For example, if a bad actor places a native command in the current dir (that your credentials allow), that effectively overrides another, potentially built-in command you use without your knowledge:
```powershell
PS> $env:PATH = ".;$env:PATH" # Don't do this!
PS> '@echo "This is a bat script, might do something you would not like" && certmgr.msc' > certmgr.bat
PS> certmgr
"This is a bat script, might do something you would not like"
```
Here you might have thought you were going to invoke the Windows `certmgr.msc` utility, but the bat file was able to interject itself, and normally you wouldn't know that it did.  BTW even with the dot at the end of the PATH, a bad actor could rely on frequently mistyped commands such as `dit`, `gti` or `gx` (instead of dir, git, gc).
 
IMO PowerShell is working "as designed". 
 
Does anybody know if there is a tag or something you can place on a fenced code block to indicate to tools like Copilot not to EVER recommend this code?

**Comment by jhoneill** [comment]
> This is a security feature that you could override by adding `.` to your path. It's not something I would do. And I would NOT RECOMMEND it 

It is something I do myself, but advise people to think carefully about before doing it

> a quick test indicates it works:
> 
> ```powershell
> PS> $env:PATH += "."  # Don't do this!
> PS> '@echo "This is a bat script"' > echo.bat
> PS> echo.bat
> "This is a bat script"
> ```

Note that in this case `echo.bat` runs the script but `echo`  will run the PowerShell alias (and would run a function or cmdlet before searching the path). 

> 
> The reason PowerShell doesn't automatically run scripts in the current dir is that bad things can happen. For example, if a bad actor places a native command in the current dir (that your credentials allow), that effectively overrides another, potentially built-in command you use without your knowledge, you invoke the bad script without even knowing it:
> 
> ```powershell
> PS> $env:PATH = ".;$env:PATH" # Don't do this!
> PS> '@echo "This is a bat script, might do something you would not like" && certmgr.msc' > certmgr.bat
> PS> certmgr
> "This is a bat script, might do something you would not like"
> ```

This is correct in all regards and is the logic behind the original design. However. 
1. In your first example you put "." last on the path, if a user does that, then the original executable is found. In this version "." comes first allowing the script to be found. 
2. The bad actor needs to drop scripts which match names of _commands which will be run_ into directories you will be in when you issue those commands. I need to know that you run `certmgr` from the prompt and not via [win]R , and that you put yourself in the a "cert files" directory first.  
3. If the directory is being attacked is the where your profile is found. why not just append `set-alias certmgr "~\certmgr.bat"` to the profile? Or add a module to the `modules` directory which defines `certmgr` that will then be loaded on demand? If anywhere on the path or PSModulePath is attackable, it's a place for malicious scripts, "." is a moving target. But with access to the profile an attacker can add somewhere to the path/psmodulepath.  
4. If a bad actor was able to do this, in reality there were dozens of worse things they could do, and probably did do. 


> IMO PowerShell is working "as designed".

It is. The correct decision was made - i.e. where there are choices for configuration and one is even slightly more secure it  should be the default.  

 In reality the example I gave above:
```
cd \program files\notepad++
notepad++
```
isn't something I'd ever type.  I would type `\prog[TAB]\note[tab]\not[tab]`   even in the current directory I'd type `note[tab]` and PowerShell would expand it to `.\notepad++.exe`   the message "Save typing AND improve security with tab completion" is probably the right one to give. But if people have a way of working which they want to stick to, and understand the small risk that comes with it, PowerShell allows them to make that choice.
