### ISSUE TITLE
Can't start multiple out of process runspaces with System.Management.Automation 7.1.preview.2 and beyond

### ISSUE THREAD

**Issue by leonardder** [PowerShell/PowerShell#17682]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
1. Download the following project: [psTest_remote_runspace.zip](https://github.com/PowerShell/PowerShell/files/9112153/psTest_remote_runspace.zip)
2. Execute it

### Expected behavior
Output:
```console
one
two
three
```

This output is generated when using System.Management.Automation 7.0.*

### Actual behavior
Output:

```console
one
Unhandled exception. System.Management.Automation.Runspaces.InvalidRunspaceStateException: The runspace state is not valid for this operation.
 ---> System.Management.Automation.Runspaces.InvalidRunspacePoolStateException: Cannot perform the operation because the runspace pool is not in the 'Opened' state. The current state is 'Broken'.
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.AssertPoolIsOpen()
   at System.Management.Automation.Runspaces.RunspacePool.AssertPoolIsOpen()
   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)
   --- End of inner exception stack trace ---
   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)
   at System.Management.Automation.PowerShell.BeginInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state)
   at System.Management.Automation.PowerShell.BeginInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output)
   at System.Management.Automation.PowerShell.InvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output)
   at Program.RunPowerShell(PowerShellProcessInstance instance, String message) in D:\psTest_remote_runspace\Program.cs:line 23
   at Program.Main(String[] args) in D:\psTest_remote_runspace\Program.cs:line 39
   at Program.<Main>(String[] args)
```

Alternative output:

```console
one
Unhandled exception. System.Management.Automation.Remoting.PSRemotingTransportException: There is an error processing data from the background process. Error reported: UPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUFNQcmltaXRpdmVEaWN0aW9uYXJ5PC9UPjxUPlN5c3RlbS5Db2xsZWN0aW9ucy5IYXNodGFibGU8L1Q+PFQ+U3lzdGVtLk9iamVjdDwvVD48L1ROPjxEQ1Q+PEVuPjxTIE49IktleSI+QnJlYWtBbGw8L1M+PEIgTj0iVmFsdWUiPmZhbHNlPC9CPjwvRW4+PEVuPjxTIE49IktleSI+RGV<Data Stream='Default' PSGuid='00000000-0000-0000-0000-000000000000'>AAAAAAAAAAoAAAAAAAAAAAMAAABnAQAAAAUQAgDZ5A0ndChcQryGVexra4VDAAAAAAAAAAAAAAAAAAAAAO+7vzxPYmogUmVmSWQ9IjAiPjxNUz48STMyIE49IlJ1bnNwYWNlU3RhdGUiPjI8L0kzMj48L01TPjwvT2JqPg==</Data>.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at Program.RunPowerShell(PowerShellProcessInstance instance, String message) in D:\psTest_remote_runspace\Program.cs:line 12
   at Program.Main(String[] args) in D:\psTest_remote_runspace\Program.cs:line 39
   at Program.<Main>(String[] args)`
```

### Environment data

```powershell
PSVersion                      5.1.22000.653                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.22000.653                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

**Comment by leonardder** [comment]
After some debugging, I found the following:

* With S.M.A 7.0.x, after closing the runspace, the runspace pool on the ProcessInstance is properly disposed. When a new runspace is opened, the runspace pool on the process instance is replaced with a new pool
* With S.M.A 7.2, the new runspace gets in a broken state after opening and the runspace pool on the process instance is still disposed. Therefore I think that the runspace pool isn't replaced correctly.

**Comment by leonardder** [comment]
I was able to pinpoint the bug somewhere between 7.1.0.Preview.1 and 7.1.0.Preview.2. Starting from 7.1.0.preview.2 and onwards, this problem occurs.

**Comment by JamesWTruher** [comment]
@WG-engine
@leonardder would it be possible to get a more compact repro? Preferably one that does not rely on downloading a zip file and building a project.

**Comment by iSazonov** [comment]
> It should be possible to convert this to a test, I assume?

You could try using Pester as all pwsh tests do.
