### ISSUE TITLE
Escaping quotation mark not working inside subexpression inside of String

### ISSUE THREAD

**Issue by kevinholtkamp** [PowerShell/PowerShell#17698]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$Array = "Test", "NewTest", "OtherTest"
"$($Array | ForEach-Object {"\`"$_\`""})"

This gives the error seen below, however when not encapsulating the subexpression in a string, it works just fine.
$($Array | ForEach-Object {"\`"$_\`""}) returns the expected output, except that each string is in a separate line, since it is not encapsulated

### Expected behavior

```console
"Test" "NewTest" "OtherTest"
```

### Actual behavior

```console
ParserError:
Line |
   1 |  "$($Array | ForEach-Object {"`"$_`""})"
     |                                 ~~~~~
     | Unexpected token '$_`""' in expression or statement.
```

### Error details

```console
Type        : System.Management.Automation.ParseException
Errors      :
    Extent  : $_`""
    ErrorId : UnexpectedToken
    Message : Unexpected token '$_`""' in expression or statement.

    Extent  : `""
    ErrorId : UnexpectedToken
    Message : Unexpected token '`""' in expression or statement.
Message     : At line:1 char:32
              + "$($Paths | ForEach-Object {"`"$_`""})"
              +                                ~~~~~
              Unexpected token '$_`""' in expression or statement.

              At line:1 char:34
              + "$($Paths | ForEach-Object {"`"$_`""})"
              +                                  ~~~
              Unexpected token '`""' in expression or statement.
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : At line:1 char:32
                  + "$($Paths | ForEach-Object {"`"$_`""})"
                  +                                ~~~~~
                  Unexpected token '$_`""' in expression or statement.

                  At line:1 char:34
                  + "$($Paths | ForEach-Object {"`"$_`""})"
                  +                                  ~~~
                  Unexpected token '`""' in expression or statement.
        HResult : -2146233087
    CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : UnexpectedToken
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 32
        HistoryId        : -1
        Line             : "$($Paths | ForEach-Object {"`"$_`""})"
        PositionMessage  : At line:1 char:32
                           + "$($Paths | ForEach-Object {"`"$_`""})"
                           +                                ~~~~~
        CommandOrigin    : Internal
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.3.0.5, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/32170328/179373344-7ddfca66-cf19-49ee-abba-b9df216fba1f.png)

**Comment by mklement0** [comment]
I haven't looked at the specifics, but https://github.com/PowerShell/PowerShell/issues/3039#issuecomment-353224924 may shed light on this.

**Comment by kevinholtkamp** [comment]
@mklement0 Yes, it seems to be the same issue, thank you!

**Comment by kevinholtkamp** [comment]
@mklement0 Yes, it seems to be the same issue, thank you!
