### ISSUE TITLE
Using `SteppablePipeline` outside of the scope it was created in results in undefined behavior

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#17868]
### Steps to reproduce

1. Create a new scope
2. Create a steppable pipeline and run begin
3. Let that scope be cleaned up by the engine
4. Run process on the pipeline created in step 2
5. The scope in the steppable pipeline is not detached from global

```powershell
function testing { process { Get-Date } }
$pipe = & {
    $pipe = { testing }.GetSteppablePipeline('Internal')
    $pipe.Begin($true)
    return $pipe
}

& { $pipe.Process('some input') }
```

### Expected behavior

Maybe an error message saying that the scope is no longer valid, or even just documentation saying this is results in undefined behavior. Best case scenario, it returns the date.

### Actual behavior

```console
Get-Date:
Line |
   2 |  function testing { process { Get-Date }}
     |                               ~~~~~~~~
     | The term 'Get-Date' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: Get-Date, Set-Date, Test-Date, Get-Dtc
```

### Error details

Also in a debug build this assert fails:

<details>

<summary>

### Long call stack, click to expand</summary>

```console
Process terminated. Assertion failed.
The scope specified to be set in CurrentScope is not in the global scope lineage. All scopes must originate from the global scope.
   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen, String detailMessage) in C:\Projects\PowerShell\src\System.Management.Automation\utils\assert.cs:line 202
   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen) in C:\Projects\PowerShell\src\System.Management.Automation\utils\assert.cs:line 134
   at System.Management.Automation.SessionStateInternal.set_CurrentScope(SessionStateScope value) in C:\Projects\PowerShell\src\System.Management.Automation\engine\SessionStateScopeAPIs.cs:line 202
   at System.Management.Automation.CommandProcessorBase.SetCurrentScopeToExecutionScope() in C:\Projects\PowerShell\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 363
   at System.Management.Automation.CommandProcessorBase.DoExecute() in C:\Projects\PowerShell\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 563
   at System.Management.Automation.Internal.PipelineProcessor.Inject(Object input, Boolean enumerate) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 1216
   at System.Management.Automation.Internal.PipelineProcessor.Step(Object input) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 936
   at System.Management.Automation.SteppablePipeline.Process(Object input) in C:\Projects\PowerShell\src\System.Management.Automation\engine\lang\scriptblock.cs:line 1204
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\DynamicInstructions.Generated.cs:line 166
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 355
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 355
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 105
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 81
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in C:\Projects\PowerShell\src\System.Management.Automation\engine\ScriptCommandProcessor.cs:line 575
   at System.Management.Automation.DlrScriptCommandProcessor.Complete() in C:\Projects\PowerShell\src\System.Management.Automation\engine\ScriptCommandProcessor.cs:line 426
   at System.Management.Automation.CommandProcessorBase.DoComplete() in C:\Projects\PowerShell\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 631
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 619
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 504   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) in C:\Projects\PowerShell\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 495
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 608
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 355
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 355
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 105
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in C:\Projects\PowerShell\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 81
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in C:\Projects\PowerShell\src\System.Management.Automation\engine\ScriptCommandProcessor.cs:line 575
   at System.Management.Automation.DlrScriptCommandProcessor.Complete() in C:\Projects\PowerShell\src\System.Management.Automation\engine\ScriptCommandProcessor.cs:line 426
   at System.Management.Automation.CommandProcessorBase.DoComplete() in C:\Projects\PowerShell\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 631
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 619
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in C:\Projects\PowerShell\src\System.Management.Automation\engine\pipeline.cs:line 504   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() in C:\Projects\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs:line 400
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() in C:\Projects\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs:line 588
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProcImpersonate() in C:\Projects\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs:line 544
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc() in C:\Projects\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs:line 1217
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

</details>

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.6
PSEdition                      Core
GitCommitId                    7.3.0-preview.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Note that this kinda makes writing a class that utilizes steppable pipeline somewhat impossible. At least if the target command is defined within the same module as the class.
