### ISSUE TITLE
AMSI close session fails with error about protected memory

### ISSUE THREAD

**Issue by YuxinHan258** [PowerShell/PowerShell#17866]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

(After installation, open the error message) 安装后，打开报错

PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Management.Automation.AmsiUtils+AmsiNativeMethods.AmsiCloseSession(IntPtr, IntPtr)
   at System.Management.Automation.AmsiUtils.WinCloseSession()
   at System.Management.Automation.Runspaces.PipelineBase..ctor(System.Management.Automation.Runspaces.Runspace, System.Management.Automation.Runspaces.CommandCollection, Boolean, Boolean, System.Management.Automation.Internal.ObjectStreamBase, System.Management.Automation.Internal.ObjectStreamBase, System.Management.Automation.Internal.ObjectStreamBase, System.Management.Automation.PSInformationalBuffers)
   at System.Management.Automation.PowerShell+Worker.ConstructPipelineAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell+Worker.CreateRunspaceIfNeededAndDoWork(System.Management.Automation.Runspaces.Runspace, Boolean)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.CoreInvoke[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.IEnumerable, System.Management.Automation.PSDataCollection`1<System.__Canon>, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.PowerShell.Invoke(System.Collections.IEnumerable, System.Management.Automation.PSInvocationSettings)
   at System.Management.Automation.Runspaces.InitialSessionState.ProcessOneModule(System.Management.Automation.Runspaces.Runspace, System.String, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.HashSet`1<System.Management.Automation.CommandInfo>)
   at System.Management.Automation.Runspaces.InitialSessionState.ProcessModulesToImport(System.Management.Automation.Runspaces.Runspace, System.Collections.IEnumerable, System.String, System.Collections.Generic.HashSet`1<System.Management.Automation.CommandInfo>, System.Collections.Generic.HashSet`1<System.String>)
   at System.Management.Automation.Runspaces.InitialSessionState.BindRunspace(System.Management.Automation.Runspaces.Runspace, System.Management.Automation.PSTraceSource)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean)
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean)
   at System.Management.Automation.Runspaces.RunspaceBase.Open()
   at Microsoft.PowerShell.ConsoleHost.OpenConsoleRunspace(System.Management.Automation.Runspaces.Runspace, Boolean)
   at Microsoft.PowerShell.ConsoleHost.DoCreateRunspace(System.String, Boolean, Boolean, System.String, System.Collections.ObjectModel.Collection`1<System.Management.Automation.Runspaces.CommandParameter>)
   at Microsoft.PowerShell.ConsoleHost.CreateRunspace(System.Object)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(System.String, Boolean, System.Collections.ObjectModel.Collection`1<System.Management.Automation.Runspaces.CommandParameter>, Boolean, System.String)
   at Microsoft.PowerShell.ConsoleHost.Run(Microsoft.PowerShell.CommandLineParameterParser, Boolean)
   at Microsoft.PowerShell.ConsoleHost.Start(System.String, System.String)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

[已退出进程，代码为 3221225477 (0xc0000005)]

### Expected behavior

```console
Hope to use (希望可以使用)
```

### Actual behavior

```console
Can't open (无法打开)
```

### Environment data

```powershell
版本	Windows 10 家庭中文版
版本号	21H2
安装日期	‎2021/‎8/‎5
操作系统内部版本	19044.1889
体验	Windows Feature Experience Pack 120.2212.4180.0
```

### OS Data

```powershell
(Unable to open after installation) 安装后无法打开
```

**Comment by TravisEz13** [comment]
This is failing a call to Windows.  You will likely have to open a support request with windows do see why this is failing on your machine.

**Comment by YuxinHan258** [comment]
> This is failing a call to Windows. You will likely have to open a support request with windows do see why this is failing on your machine.
> 
> Because it is AMSI, I think it could also be your antivirus software.

感谢您的帮助，是因为安装了 Symantec Endpoint Protection 这个软件导致无法使用power shell ，Symantec Endpoint Protection太可恨了，已经卸载。
