### ISSUE TITLE
The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception.

### ISSUE THREAD

**Issue by ProRedMax** [PowerShell/PowerShell#18109]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem when running the PowerShell SDK in a kiosk (AssignedAccess) environment in a WindowsBackgroundService. When I am using the library in a non-kiosk environment it works fine. But the weird thing is that once I am in the kiosk or when I get back from it, I am always getting an exception. I already asked this on StackOverflow but without any solutions.

### Expected behavior

```console
﻿$user = "ExamX"
$Sid = (Get-LocalUser -Name $user).SID.Value
Remove-LocalUser -SID $Sid
Clear-AssignedAccess
sc.exe stop "ExamX Service"
sc.exe delete "ExamX Service"
$path = "HKLM:\SOFTWARE\ExamX\ExamInfo\"
Remove-Item -Recurse $path -ErrorAction SilentlyContinue
```

### Actual behavior

```console
Exception Trace System.TypeInitializationException: The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Management.Automation.Configuration.PowerShellConfig..ctor()
   at System.Management.Automation.Configuration.PowerShellConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExperimentalFeature..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at ExamX_Service.WindowsService.PowershellHandler.Execute() in C:\ExamX\Service\ExamX_Service\ExamX_Service\PowershellHandler.cs:line 33
   at ExamX_Service.WindowsService.WindowsBackgroundService.RunRecoveryScript(ILogger`1 logger) in C:\ExamX\Service\ExamX_Service\ExamX_Service\WindowsBackgroundService.cs:line 134
   at ExamX_Service.WindowsService.WindowsBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\ExamX\Service\ExamX_Service\ExamX_Service\WindowsBackgroundService.cs:line 110
```

### Environment data

```powershell
I can't really execute this command due to the exception being thrown
```

**Comment by ProRedMax** [comment]
So I am using a fresh virtual machine (So I am not hosting PowerShell in any way I know) and just calling the PowerShell library. As I mentioned it works fine in a non-kiosk environment. The weird thing is that when I return from the kiosk it still does not work. This is how I am using the library:
Call in WindowsBackgroundService.cs
```c#
        var powershellHandler = new PowershellHandler();
        powershellHandler.AddCommand("Set-ExecutionPolicy Unrestricted");
        foreach (var line in File.ReadAllLines(@"C:\Program Files (x86)\ExamX\ExamX_Service\RecoveryScript.ps1"))
            powershellHandler.AddCommand(line);

        return powershellHandler.Execute();
```


And this is the actual PowershellHandler:

```c#
public class PowershellHandler
    {
        private readonly PowerShell _powerShell;

        public PowershellHandler()
        {
            _powerShell = PowerShell.Create();
        }

        public void AddCommand(string command)
        {
            _powerShell.AddScript(command);
        }

        public string Execute()
        {
            string errorMsg = string.Empty;
            string output = string.Empty;
            _powerShell.AddCommand("Out-String");
            PSDataCollection<PSObject> outputCollection = new();
            _powerShell.Streams.Error.DataAdded += (object sender, DataAddedEventArgs e) =>
            {
                errorMsg = ((PSDataCollection<ErrorRecord>) sender)[e.Index].ToString();
            };

            IAsyncResult result = _powerShell.BeginInvoke<PSObject, PSObject>(null, outputCollection);

            _powerShell.EndInvoke(result);

            StringBuilder sb = new();

            foreach (var outputitem in outputCollection)
            {
                sb.AppendLine(outputitem.BaseObject.ToString());
            }

            _powerShell.Commands.Clear();

            if (!string.IsNullOrEmpty(errorMsg))
            {
                return errorMsg;
            }

            return sb.ToString().Trim();
        }
    }
```

**Comment by FeelProud** [comment]
I would like to support this problem that I have also just encountered.

**Setup :** 
- Windows Server 2019

**My application :**
- A Windows Background Service

**Explanation :**
I'm using this following code in my background service 

`
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.ServiceProcess;
using Microsoft.PowerShell;
PowerShell.Create().AddCommand("Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted")
PowerShellInstance.Invoke();
`

And I'm getting the following error
`
System.TypeInitializationException: The type initializer for 
'System.Management.Automation.Configuration.PowerShellConfig' threw an 
exception. ---&gt; System.ArgumentNullException: Value cannot be null. 
(Parameter 'path1') at System.IO.Path.Combine(String path1, String path2) at 
System.Management.Automation.Configuration.PowerShellConfig..ctor() at 
System.Management.Automation.Configuration.PowerShellConfig..cctor
`

**Comment by SteveL-MSFT** [comment]
What specific version of the PowerShell SDK are you using?

**Comment by ProRedMax** [comment]
I am using 7.2.5

**Comment by FeelProud** [comment]
I am using 7.2.7 for my part

**Comment by tannertaylor** [comment]
Just wanted to throw my voice in here as well. I'm getting this exact error with a self-contained single-file app. I'm using version 7.2.4. The PR looks like it ought to fix my problem.
