### ISSUE TITLE
pwsh: cannot get System.Windows.Forms.Application.UserAppDataPath

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#18131]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following commands

```powershell
Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::UserAppDataPath
```

### Expected behavior

Result from PowerShell 5.1:

```
C:\Users\roman.kuzmin\AppData\Roaming\Microsoft Corporation\Microsoft® Windows® Operating System\10.0.19041.1
```

### Actual behavior

```
OperationStopped: The directory name is invalid. : 'C:\Users\roman.kuzmin\AppData\Roaming\Microsoft Corporation\PowerShell\7.2.6 SHA: eb2c4accddda2995e50cd349e655888500899d8b'
```

### Error details

```console
Type           : System.Management.Automation.RuntimeException
ErrorRecord    :
    Exception             :
        Type       : System.IO.IOException
        TargetSite :
            Name          : CreateDirectory
            DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : The directory name is invalid. : 'C:\Users\roman.kuzmin\AppData\Roaming\Microsoft Corporation\PowerShell\7.2.6 SHA:
eb2c4accddda2995e50cd349e655888500899d8b'
        Data       : System.Collections.ListDictionaryInternal
        Source     : System.Private.CoreLib
        HResult    : -2147024629
        StackTrace :
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at System.Windows.Forms.Application.GetDataPath(String basePath)
   at System.Windows.Forms.Application.get_UserAppDataPath()
   at System.Management.Automation.Interpreter.FuncCallInstruction`1.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    CategoryInfo          : OperationStopped: (:) [], IOException
    FullyQualifiedErrorId : System.IO.IOException
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : -1
        Line             : [System.Windows.Forms.Application]::UserAppDataPath
        PositionMessage  : At line:1 char:1
                           + [System.Windows.Forms.Application]::UserAppDataPath
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CommandOrigin    : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.2.6.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message        : The directory name is invalid. : 'C:\Users\roman.kuzmin\AppData\Roaming\Microsoft Corporation\PowerShell\7.2.6 SHA:
eb2c4accddda2995e50cd349e655888500899d8b'
Data           : System.Collections.ListDictionaryInternal
InnerException :
    Type       : System.IO.IOException
    TargetSite :
        Name          : CreateDirectory
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : The directory name is invalid. : 'C:\Users\roman.kuzmin\AppData\Roaming\Microsoft Corporation\PowerShell\7.2.6 SHA:
eb2c4accddda2995e50cd349e655888500899d8b'
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2147024629
    StackTrace :
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at System.Windows.Forms.Application.GetDataPath(String basePath)
   at System.Windows.Forms.Application.get_UserAppDataPath()
   at System.Management.Automation.Interpreter.FuncCallInstruction`1.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Source         : System.Management.Automation
HResult        : -2146233087
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by nightroman** [comment]
This issue causes other issues. In particular it is not possible to use `Microsoft.VisualBasic.Logging.FileLogTraceListener` because it's constructor calls `System.Windows.Forms.Application.UserAppDataPath`.

**Comment by fMichaleczek** [comment]
There is more issues than UserAppDataPath : 

```
>  Add-Type -AssemblyName System.Windows.Forms

> [System.Windows.Forms.Application]::CommonAppDataPath
OperationStopped: The directory name is invalid. : 'C:\ProgramData\Microsoft Corporation\PowerShell\7.2.6 SHA: eb2c4accddda2995e50cd349e655888500899d8b'

> [System.Windows.Forms.Application]::UserAppDataPath
OperationStopped: The directory name is invalid. : 'C:\Users\Flavien\AppData\Roaming\Microsoft Corporation\PowerShell\7.2.6 SHA: eb2c4accddda2995e50cd349e655888500899d8b'

> [System.Windows.Forms.Application]::LocalUserAppDataPath
OperationStopped: The directory name is invalid. : 'C:\Users\Flavien\AppData\Local\Microsoft Corporation\PowerShell\7.2.6 SHA: eb2c4accddda2995e50cd349e655888500899d8b'

> [System.Windows.Forms.Application]::CommonAppDataRegistry.ToString()
HKEY_LOCAL_MACHINE\Software\Microsoft Corporation\PowerShell\7.3.0-preview.6 SHA: bcafe74c174091a0f47cf7a5eeb4bca8aefa8718
```

The documentation said if a path does not exist, one is created in the following format:

_Base Path\CompanyName\ProductName\ProductVersion_

source : [learn.microsoft.com|Application.UserAppDataPath](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.application.userappdatapath?view=windowsdesktop-6.0#remarks)

The problem is located in pwsh.exe where the ProductVersion contains a ":" colon.

```
> (Get-Command powershell.exe | Get-Item).VersionInfo.ProductVersion
10.0.19041.1

> (Get-Command pwsh.exe | Get-Item).VersionInfo.ProductVersion
7.2.6 SHA: eb2c4accddda2995e50cd349e655888500899d8b
```

**Comment by iSazonov** [comment]
We followed .Net in this. In 7.0 they changed this to semantic version. We could do the same.

----

Although it is too reckless for WinForms to trust this attribute. I would advise you to open new issue there too.

**Comment by fMichaleczek** [comment]
> We followed .Net in this. In 7.0 they changed this to semantic version. We could do the same.

```
> (Get-Command dotnet.exe | Get-Item).VersionInfo.ProductVersion
7.0.0-preview.7.22375.6 @Commit: eecb02807867cad56cd05badddef65e432248b75
```

there is a commit version but dotnet.exe isn't a Windows UI app model, and pwsh.exe is not a console app on Windows ?

```
> (Get-Item $PSHome\System.Windows.Forms.dll).VersionInfo.ProductVersion
7.0.0-preview.6.22351.2+f6720164c48ea0de634e574de94dd8450f761b25
```
> Although it is too reckless for WinForms to trust this attribute. I would advise you to open new issue there too.

ProductVersion is a special attribute for Windows UI app mode, it's not a free string in this context.
I don't think we should ask to open a issue about a breaking in the Winforms .NET Framework 1.1 Application API.

```
> # List Product Version
> (Get-Item $PSHome\*.dll).VersionInfo.ProductVersion | Select-Object -Unique
```
