### ISSUE TITLE
Get-WmiObject command listed but not recognized for tab completion

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#18182]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I understand that WMI is deprecated in favor of CIM. Why are WMI commands still listed in `Get-Command`?

### Expected behavior

```console
Get-Command -Name '*wmi*' should not display unusable commands.
```

### Actual behavior

```console
PS C:\> $PSVersionTable.PSVersion.ToString()
7.2.6
PS C:\> Get-Command -Name '*-wmi*'

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-WmiObject                                      3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Invoke-WmiMethod                                   3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Register-WmiEvent                                  3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Remove-WmiObject                                   3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Set-WmiInstance                                    3.1.0.0    Microsoft.PowerShell.Management

PS C:\> Get-WmiObject
Get-WmiObject: The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Error details

```console
PS C:\> Get-Error

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : Get-WmiObject
        CategoryInfo          : ObjectNotFound: (Get-WmiObject:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 325
            Line             : Get-WmiObject
            PositionMessage  : At line:1 char:1
                               + Get-WmiObject
                               + ~~~~~~~~~~~~~
            InvocationName   : Get-WmiObject
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : Get-WmiObject
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.2.6.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions,
CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin
commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions,
CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[]
pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Get-WmiObject
CategoryInfo          : ObjectNotFound: (Get-WmiObject:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 325
    Line             : Get-WmiObject
    PositionMessage  : At line:1 char:1
                       + Get-WmiObject
                       + ~~~~~~~~~~~~~
    InvocationName   : Get-WmiObject
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dkaszews** [comment]
Can you show output of `Get-Command 'Get-WmiObject' | Select-Object *`? It should show where the command is supposedly located. Also, try running `Get-Help 'Get-WmiObject'`, maybe `Get-Command` is confused by some leftover help files.

**Comment by 237dmitry** [comment]
Because WMI cmdlets are unavailable in "Core". Instead use `Get-CimInstance`
```
Get-Command *-Cim*
```

**Comment by iSazonov** [comment]
> 3.1.0.0

This explicitly says that comes from Windows PowerShell.

**Comment by 237dmitry** [comment]
> On my system Get-Command -Name '*-wmi*' returns nothing

Nothing on my system either, although `$env:PSModulePath` includes paths to Windows PowerShell modules. If you run `pwsh -noprofile` then wmi cmdlets will appear in the `Get-Command` list.

**Comment by Liturgist** [comment]
This issue can not be produced this morning. I do not know why. The question I posted was copy/paste from the machine. Closing.

**Comment by fMichaleczek** [comment]
![image](https://user-images.githubusercontent.com/6187529/193813772-acf5115c-ce7c-4471-b3e4-c3771359c014.png)

**Comment by dkaszews** [comment]
@fMichaleczek So you're saying you can reproduce it, but it's weirdly flaky?

**Comment by fMichaleczek** [comment]
@dkaszews yes, it shows a bug 🙂

**Comment by Liturgist** [comment]
@fMichaleczek, could you try this with the current PowerShell Core 7.2.6? Does it produce the same bug?

**Comment by fMichaleczek** [comment]
@Liturgist 7.2.6 and 7.3.0-Preview.8 (I upgraded to the last preview) to be sure.

**Comment by Liturgist** [comment]
@fMichaleczek, given that you can reproduce the bug, I will "Reopen" this item.

**Comment by SteveL-MSFT** [comment]
The problem appears to be that the WindowsCompat feature finds the cmdlet in the Windows PowerShell management module and shows it, but, of course, you can't use that module in PS7.  I think we should consider not having command discovery look at the core set of modules outside of $PSHOME.

**Comment by iSazonov** [comment]
> I think we should consider not having command discovery look at the core set of modules outside of $PSHOME.

Hasn't that already been done? 😕

**Comment by daxian-dbw** [comment]
Just want to leave a message that the issue sometimes reproduces for me, and some other times not. My module path has the Windows PowerShell module folders at the end, which is expected. I haven't spent the time to figure out what is exactly wrong, but I'm guessing it's related to module auto-discovery analysis.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets  discussed this, we believe the problem is in the tabcompleter for cmdlets working differently than how command discovery is working with the UseWindowsPowerShell feature.  We agreed this is a bug.

**Comment by ps81frt** [comment]
Updated to 7.3.5 same error.

**Comment by Liturgist** [comment]
```
PS C:\Users\lit> $PSVersionTable.PSVersion.ToString()
7.3.5
PS C:\Users\lit> Get-Command -Name '*-wmi*'
PS C:\Users\lit> $Env:PSModulePath -split ';'
C:\Users\lit\OneDrive\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\Windows\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files (x86)\Microsoft SQL Server\160\Tools\PowerShell\Modules\
```

**Comment by ps81frt** [comment]
![Animation](https://github.com/PowerShell/PowerShell/assets/32146568/46175dd1-df3d-4337-9cc2-a94902458ad1)

**Comment by MacKey-255** [comment]
Any Update?
