### ISSUE TITLE
Exception incorrectly being thrown when using SetBufferContents with a Rectangle

### ISSUE THREAD

**Issue by nsstrickland** [PowerShell/PowerShell#18239]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using the Host's `$host.UI.RawUI.SetBufferContents` method, an exception is thrown when using a Rectangle, but not when using a Coordinate. The exception notes that an overload cannot be found with an argument count of 2, but both overloads for SetBufferContents use 2 arguments. 

From what I've seen, this happens in `5.1`, `7.2.6`, and the newest `7.3.0-preview.8`. It should be noted that this will only apply to Windows, as GetBufferContents is not implemented into the Unix platform.

### Expected behavior

```console
#test message before clearing buffer
PS> $rec=[System.Management.Automation.Host.Rectangle]::new(0,0,0,10)
PS> $buffer=$host.ui.RawUI.GetBufferContents($rec)
PS> Clear-Host
PS> $host.ui.RawUI.SetBufferContents($rec,$buffer)

The exact text "PS>#test m" should be overlaid on the first line in the buffer.
```

### Actual behavior

```console
#test message before clearing buffer
PS> $rec=[System.Management.Automation.Host.Rectangle]::new(0,0,0,10)
PS> $buffer=$host.ui.RawUI.GetBufferContents($rec)
PS> Clear-Host
PS> $host.ui.RawUI.SetBufferContents($rec,$buffer)
MethodException: Cannot find an overload for "SetBufferContents" and the argument count: "2".
```

### Error details

```console
Exception             : 
    Type        : System.Management.Automation.MethodException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find an overload for "SetBufferContents" and the argument count: "2".
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodCountCouldNotFindBest
        InvocationInfo        : 
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $host.ui.RawUI.SetBufferContents($rec,$buffer)
            PositionMessage  : At line:1 char:1
                               + $host.ui.RawUI.SetBufferContents($rec,$buffer)
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object, System.Object)
    Message     : Cannot find an overload for "SetBufferContents" and the argument count: "2".
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  : 
   at CallSite.Target(Closure, CallSite, Object, Object, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
InvocationInfo        : 
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $host.ui.RawUI.SetBufferContents($rec,$buffer)
    PositionMessage  : At line:1 char:1
                       + $host.ui.RawUI.SetBufferContents($rec,$buffer)
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.8
PSEdition                      Core
GitCommitId                    7.3.0-preview.8
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![0](https://user-images.githubusercontent.com/7866945/194740103-7ec4860c-0a18-4d10-9468-694754ba049d.png)
![1](https://user-images.githubusercontent.com/7866945/194740105-c8841416-27ef-4d3d-9e9d-d6d04d8bd7cf.png)
![2](https://user-images.githubusercontent.com/7866945/194740106-cec64413-6096-442e-a06f-64faa0447776.png)

**Comment by 237dmitry** [comment]
Because `$Host.UI.RawUI.GetBufferContents()` is not implemented
```
$rec=[System.Management.Automation.Host.Rectangle]::new(0,0,10,0)
$host.ui.RawUI.GetBufferContents($rec)

MethodInvocationException: 
Line |
   3 |  $host.ui.RawUI.GetBufferContents($rec)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetBufferContents" with "1" argument(s): "The method or operation is not implemented."
```

**Comment by nsstrickland** [comment]
> Because `$Host.UI.RawUI.GetBufferContents()` is not implemented
`$Host.UI.RawUI.GetBufferContents()` is not implemented on the Unix platform, this will only apply to Windows. I'll amend the description to note that.

**Comment by 237dmitry** [comment]
It's good that this overload works:
```
void SetBufferContents(System.Management.Automation.Host.Coordinates origin, System.Management.Automation.Host.BufferCell[,] contents)
```

```powershell
Clear-Host
Write-Host "aaaaaa`nbbbbbb`ncccccc" -F Green

$rec=[System.Management.Automation.Host.Rectangle]::new(0,0,2,2)
$buffer = $Host.UI.RawUI.GetBufferContents($rec)
$coord = [System.Management.Automation.Host.Coordinates]::new(0,0)

Clear-Host

$Host.UI.RawUI.SetBufferContents($coord, $buffer)
[console]::CursorTop = 5
```

**Comment by nsstrickland** [comment]
> It's good that this overload works (on Windows)

Yes, that's mentioned in the description and shown in one of the screenshots. The Rectangle overload not working is still unexpected behavior.

**Comment by MartinGC94** [comment]
It's working as intended. `SetBufferContents` has 2 overloads, one that takes `Coordinates` + `BufferCell[,]` and one that takes `Rectangle` + `BufferCell` you are attempting to call it with a `Rectangle` + `BufferCell[,]` so that obviously won't work.  
If your goal is to save some content, clear the screen and then reapply it then you can do it like this:

```
$UpperLeft        = [System.Management.Automation.Host.Coordinates]::new(0, 0)
$LowerRight       = [System.Management.Automation.Host.Coordinates]::new($Host.UI.RawUI.BufferSize.Width, 0)
$TopLineRectangle = [System.Management.Automation.Host.Rectangle]::new($UpperLeft, $LowerRight)
$TopLineContent   = $Host.UI.RawUI.GetBufferContents($TopLineRectangle)
$Host.UI.RawUI.SetBufferContents($UpperLeft, $TopLineContent)
```
