### ISSUE TITLE
Windows Core `Copy-Item` falsely believes file without extension is a directory

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/PowerShell#18358]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In Windows Core:

```
Invoke-WebRequest -Uri https://aka.ms/sqlpackage-linux -OutFile ./temp/sqlpackage-linux.zip
Expand-Archive -Path ./temp/sqlpackage-linux.zip -DestinationPath ./temp/linux
Copy-Item (Join-Path ./temp/linux "*") lib -Exclude (Get-ChildItem lib -Recurse) -Recurse
```

### Expected behavior

```console
Copies the file
```

### Actual behavior

```console
Copy-Item: C:\github\dbatools-library\build\build-core.ps1:98
Line |
  98 |  Copy-Item (Join-Path ./temp/linux "*") lib -Exclude (Get-ChildItem li …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The target file 'C:\github\dbatools-library\lib\sqlpackage' is a directory, not a
     | file.
```

### Error details

```console
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : CopyFile
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0,
Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : The target file 'C:\github\dbatools-library\lib\sqlpackage' is a directory, not a
file.
    Source     : System.Private.CoreLib
    HResult    : 5
    StackTrace :
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String
destinationPath, Boolean force, PowerShell ps)
TargetObject          : C:\github\dbatools-library\temp\linux\sqlpackage
CategoryInfo          : WriteError: (C:\github\dbatools-…mp\linux\sqlpackage:FileInfo)
[Copy-Item], IOException
FullyQualifiedErrorId : CopyFileInfoItemIOError,Microsoft.PowerShell.Commands.CopyItemCommand
InvocationInfo        :
    MyCommand        : Copy-Item
    ScriptLineNumber : 98
    OffsetInLine     : 1
    HistoryId        : 17
    ScriptName       : C:\github\dbatools-library\build\build-core.ps1
    Line             : Copy-Item (Join-Path ./temp/linux "*") lib -Exclude (Get-ChildItem lib
-Recurse) -Recurse

    PositionMessage  : At C:\github\dbatools-library\build\build-core.ps1:98 char:1
                       + Copy-Item (Join-Path ./temp/linux "*") lib -Exclude (Get-ChildItem li …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\github\dbatools-library\build
    PSCommandPath    : C:\github\dbatools-library\build\build-core.ps1
    InvocationName   : Copy-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\github\dbatools-library\build\build-core.ps1: line 98
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by potatoqualitee** [comment]
Happens in Linux too, what? Oh, oops! There was indeed a mkdir that made the sqlpackage dir in the script.
