### ISSUE TITLE
PS 7.2

### ISSUE THREAD

**Issue by kfsone** [PowerShell/PowerShell#18410]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

According to the Powershell DSC documentation for 1.1, 2.0 and 3.0 preview
https://learn.microsoft.com/en-us/powershell/dsc/concepts/configurations?view=dsc-3.0

the following should be a valid configuration:

```
Configuration MyTest {
  Import-DscResource -ModuleName 'PSDscResources'  # With or without this line
  File TestDir {
    Type = 'Directory'; DestinationPath = 'C:\MyTest'; Ensure = 'Present'
  }
}
```

Both with and without the import-dsc resource, the configuration is accepted, but cannot be compiled with an error that suggests a fundamentally backwards incompatible change to how Powershell Core's DSC expects a configuration to work.

### Expected behavior

```console
PS> Configuration MyTest { File TestDir { Type='Directory'; DestinationPath='C:\MyTest'; Ensure='Present' } }
PS> Configuration
    Directory: C:\PS\MyTest


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        10/28/2022  11:59 AM           1934 localhost.mof
WARNING: The configuration 'MyTest' is loading one or more built-in resources without explicitly importing associated modules. Add Import-DscResource –ModuleName 'PSDesiredStateConfiguration' to your configuration to avoid this message.
```

### Actual behavior

```console
PS> Configuration MyTest { File TestDir { Type='Directory'; DestinationPath='C:\MyTest'; Ensure='Present' } }
PS> Configuration
WARNING: Module PSDesiredStateConfiguration is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Configuration: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
```

### Error details

```console
OriginInfo            : localhost
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to   
type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                     at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                                     at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                     at System.Management.Automation.LanguagePrimitives.ConvertViaIEnumerableConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                     --- End of inner exception stack trace ---
                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                     --- End of inner exception stack trace ---
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to   
type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                             at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                                             at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                             at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                             at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                             at System.Management.Automation.LanguagePrimitives.ConvertViaIEnumerableConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                             at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                             at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                             at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                             --- End of inner exception stack trace ---
                                             at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                             --- End of inner exception stack trace ---
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             --- End of stack trace from previous location where exception was thrown ---
                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to   
type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                                     at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                                                     at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                     at System.Management.Automation.LanguagePrimitives.ConvertViaIEnumerableConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)        
                                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                     --- End of inner exception stack trace ---
                                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                     --- End of inner exception stack trace ---
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     --- End of stack trace from previous location where exception was thrown ---
                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert the "System.Collections.ArrayList" value of type 
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to   
type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                                             at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                                                             at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                             at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                             at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                             at System.Management.Automation.LanguagePrimitives.ConvertViaIEnumerableConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable
backupTable)
                                                             at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                             at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                             at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                             --- End of inner exception stack trace ---
                                                             at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                             --- End of inner exception stack trace ---
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             --- End of stack trace from previous location where exception was thrown ---
                                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type     
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert the "System.Collections.ArrayList" value of type
"System.Collections.ArrayList" to type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to   
type "System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                                                     at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                                                                     at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                                     at System.Management.Automation.LanguagePrimitives.ConvertViaIEnumerableConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable     
backupTable)
                                                                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                                                                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
                                                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                                     --- End of inner exception stack trace ---
                                                                     at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                                     --- End of inner exception stack trace ---
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     --- End of stack trace from previous location where exception was thrown ---
                                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                                    HResult                        : -2146233087
                                CategoryInfo          : InvalidData: (:) [Configuration], ParameterBindingArg…sformationException
                                FullyQualifiedErrorId : ParameterArgumentTransformationError,Configuration
                            Message                        : Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                            HResult                        : -2146233087
                        CategoryInfo          : InvalidData: (:) [Configuration], ParameterBindingArg…sformationException
                        FullyQualifiedErrorId : ParameterArgumentTransformationError,Configuration
                    Message                        : Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
                    HResult                        : -2146233087
                CategoryInfo          : InvalidData: (:) [Configuration], ParameterBindingArg…sformationException
                FullyQualifiedErrorId : ParameterArgumentTransformationError,Configuration
            Message                        : Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
            HResult                        : -2146233087
        CategoryInfo          : InvalidData: (:) [Configuration], ParameterBindingArg…sformationException
        FullyQualifiedErrorId : ParameterArgumentTransformationError,Configuration
    Message                        : Cannot process argument transformation on parameter 'ResourceModuleTuplesToImport'. Cannot convert the "System.Collections.ArrayList" value of type "System.Collections.ArrayList" to type 
"System.Tuple`3[System.String[],Microsoft.PowerShell.Commands.ModuleSpecification[],System.Version]".
    HResult                        : -2146233087
CategoryInfo          : InvalidData: (:) [Configuration], ParameterBindingArg…sformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Configuration
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
DSC is moving away from MOF and the `configuration` keyword expects to output MOF, so currently this is no longer supported until we have a JSON format defined.  If you need the old `configuration` support, you should stick with Windows PowerShell.

**Comment by kfsone** [comment]
Truly appreciative that it's ongoing work.

For additional clarity: I'm in the process of learning/introducing DSC as part of the transition over to mainly remote workers, and also as in-house powershell-adoption ambassador (for CI, etc... my script runs on all 3 plats? *tears of joy*)

During the process, powershell core gets installed, and suddenly the windows powershell dsc config stops working correctly.

My initial mistake was thinking that it had started running under PS Core. In actuality, the main issue appeared to be PackageManager related.

However, the MS Learn/MSDN pages/blogs did nothing to dissuade me from that line of investigation.
(https://learn.microsoft.com/en-us/powershell/dsc/getting-started/wingettingstarted?view=dsc-1.1&viewFallbackFrom=dsc-3.0 etc)

FWIW: Installing ps core, or something accompanying it, results in two versions of PackageManager 1.0.0.1 and 1.4.8.1. This further made it seem like DSC/Configuration was good-to-go for PS Core.

I have to file a separate issue for that, it feels wrong that it complains you have two versions when they are both for different editions, and adding a -ModuleVersion feels like a hack. -ModuleVersion has to be a constant so you can't do your own 'select the right one' :(
