### ISSUE TITLE
Azure Function App executing PNP.PowerShell script produces logging error between PowerShell Core versions 7.0 & 7.2

### ISSUE THREAD

**Issue by callumlinning** [PowerShell/PowerShell#18454]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've got an Azure Function App that is executing some PNP PowerShell as part of automated translation between SharePoint Online multi-lingual pages on news posts. Creating a Function App with PowerShell Core 7.0 and the script is executed without any errors observed. I then re-created the app using the latest available in Azure Function Apps (7.2) and produced a "Microsoft.Extensions.Logging.Abstractions.Internal.NullScope" error when the exact same script is run on the newer version.

Script is here:
https://github.com/spjeff/spo-page-translation/blob/main/SPJEFF-Translation-Azure-Function-PowerShell-HttpTrigger1.ps1

### Expected behavior

```console
2022-11-03T11:51:05Z   [Information]   OUTPUT: 
2022-11-03T11:51:05Z   [Information]   OUTPUT: InstanceId                           Type        Title       Section Column Position PropertiesJson
2022-11-03T11:51:05Z   [Information]   OUTPUT: ----------                           ----        -----       ------- ------ -------- --------------
2022-11-03T11:51:05Z   [Information]   OUTPUT: 1212fc8d-dd6b-408a-8d5d-9f1cc787efbb PageText                1       1      1        
2022-11-03T11:51:05Z   [Information]   OUTPUT: 22e0a4a8-13a1-4ed7-89ee-622d71980aae PageWebPart Quick links 1       1      2        {"items":[{"sourceItem":{"guids":{…
2022-11-03T11:51:05Z   [Information]   OUTPUT: 
2022-11-03T11:51:05Z   [Information]   OUTPUT: 
2022-11-03T11:51:05Z   [Information]   OUTPUT: Type
2022-11-03T11:51:05Z   [Information]   OUTPUT: ----
2022-11-03T11:51:05Z   [Information]   OUTPUT: PnP.Core.Model.SharePoint.PageText
2022-11-03T11:51:05Z   [Information]   OUTPUT: PnP.Core.Model.SharePoint.PageWebPart
2022-11-03T11:51:05Z   [Information]   OUTPUT: 
2022-11-03T11:51:05Z   [Information]   OUTPUT: 
2022-11-03T11:51:05Z   [Information]   INFORMATION: Translating content...
2022-11-03T11:51:05Z   [Warning]   WARNING: Please use 'Set-PnPPageTextPart'. The alias 'Set-PnPClientSideText' will be removed in the 1.5.0 release
2022-11-03T11:51:06Z   [Information]   INFORMATION: Translation Complete
2022-11-03T11:51:06Z   [Information]   OUTPUT: InstanceId                           Type     Title Section Column Position PropertiesJson
2022-11-03T11:51:06Z   [Information]   OUTPUT: ----------                           ----     ----- ------- ------ -------- --------------
2022-11-03T11:51:06Z   [Information]   OUTPUT: 1212fc8d-dd6b-408a-8d5d-9f1cc787efbb PageText       1       1      1        
2022-11-03T11:51:06Z   [Information]   OUTPUT: **Translated Content**.<br>
2022-11-03T11:51:06Z   [Information]   OUTPUT: 
2022-11-03T11:51:06Z   [Information]   Executed 'Functions.HttpTrigger1' (Succeeded, Id=aceff8e0-146b-49dc-81fa-c2b4055837d0, Duration=20073ms)
```

### Actual behavior

```console
[Error]   ERROR: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.3.0, Culture=neutral,
```

### Error details

```console
[Error]   ERROR: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.3.0, Culture=neutral, PublicKeyToken='.

Exception             : 
    Type       : System.TypeLoadException
    Message    : Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
    TypeName   : Microsoft.Extensions.Logging.Abstractions.Internal.NullScope
    TargetSite : 
        Name          : BeginScope
        DeclaringType : Microsoft.Extensions.Logging.Logger, Microsoft.Extensions.Logging, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
        MemberType    : Method
        Module        : Microsoft.Extensions.Logging.dll
    Data       : System.Collections.ListDictionaryInternal
    Source     : Microsoft.Extensions.Logging
    HResult    : -2146233054
    StackTrace : 
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass2_0`2.<DefineScope>b__0(ILogger logger, T1 arg1, T2 arg2)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Services.PnPContextFactory.InitializeContextAsync(PnPContext context, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(Uri url, IAuthenticationProvider authenticationProvider, CancellationToken cancellationToken, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(Uri url, IAuthenticationProvider authenticationProvider, PnPContextOptions options)
   at PnP.Framework.PnPCoreSdk.GetPnPContextAsync(ClientContext context)
   at PnP.Framework.PnPCoreSdk.GetPnPContext(ClientContext context)
   at PnP.PowerShell.Commands.Base.PnPConnection.get_PnPContext() in c:\build\src\Commands\Base\PnPConnection.cs:line 51
   at PnP.PowerShell.Commands.Base.PipeBinds.PagePipeBind.GetPage(PnPConnection connection) in c:\build\src\Commands\Base\PipeBinds\PagePipeBind.cs:line 33
   at PnP.PowerShell.Commands.Pages.GetPage.ExecuteCmdlet() in c:\build\src\Commands\Pages\GetPage.cs:line 17
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 114
CategoryInfo          : WriteError: (:) [Get-PnPPage], TypeLoadException
FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.GetPage
ErrorDetails          : Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.3.0, Culture=neutral, PublicKeyToken='.
```

### Environment data

```powershell
Variables are posted to the Function App in a JSON format for the following from the SharePoint page.

"siteURL",
"language":,
"pageTitle":
```

**Comment by kilasuit** [comment]
As this is related to Azure Functions you would be better placed rasing this issue in the [Azure Functions PowerShell Worker repo](https://github.com/Azure/azure-functions-powershell-worker) as it's likely something to do with how PowerShell is running in Azure Functions than it being PowerShell itself.
To confirm you should test your script locally in PowerShell 7.2.0 though I don't think you'd get this error locally
