### ISSUE TITLE
Invoke-WebRequest: Access to the path 'PATH' is denied.

### ISSUE THREAD

**Issue by penalvch** [PowerShell/PowerShell#18528]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi all, I'm ecountering the below error when attempting to download a file via PWSH in macOS and Windows Powershell.

in macOS PWSH has Full Disk Access as per Apple System Preferences (see below screenshot). However, I can make a directory called temp1 and curl the same file with no problem via built-in macOS terminal using the default user. AV Bitdefender is completely disabled during command execution attempts.

Same thing with Windows 11, ran Visual Studio Code as Administrator with Powershell extension, same thing same problem.

macOS:
```
Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releases/download/2022-03-15/asio.1.12.1.nupkg' -OutFile "$home/Downloads/temp1" -verbose
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received 810467-byte response of content type application/octet-stream
Invoke-WebRequest: Access to the path '/Users/username/Downloads/temp1' is denied.

sw_vers                        
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380

sysctl -n machdep.cpu.brand_string
Apple M1
```
![image](https://user-images.githubusercontent.com/115644052/201224374-92a17059-7700-4b73-8fda-c304881323a6.png)
![image](https://user-images.githubusercontent.com/115644052/201223873-232e0ffd-118d-4cdd-92d6-646927d367d2.png)

Windows:
```
([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
True

Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releases/download/2022-03-15/asio.1.12.1.nupkg' -OutFile 'C:\Users\username\Downloads'

Invoke-WebRequest : Access to the path 'C:\Users\username\Downloads' is denied.
At line:1 char:1
+ Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

[environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.25227.0 Microsoft Windows NT 10.0.25227.0

(Get-CimInstance Win32_operatingsystem).OSArchitecture
ARM 64-bit Processor

$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.25227.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25227.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

(get-acl 'c:\users\username\downloads').access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : hostname\username
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None
```

### Expected behavior

```console
SEE ABOVE
```

### Actual behavior

```console
SEE ABOVE
```

### Error details

```console
get-error                       

Exception             : 
    Type           : System.UnauthorizedAccessException
    TargetSite     : 
        Name          : ThrowExceptionForIoErrno
        DeclaringType : Interop, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message        : Access to the path '/Users/moniker/Downloads/temp1' is denied.
    InnerException : 
        Type    : System.IO.IOException
        Message : Permission denied
        HResult : 13
    Source         : System.Private.CoreLib
    HResult        : -2147024891
    StackTrace     : 
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, 
UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 
unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.PowerShell.Commands.StreamHelper.SaveStreamToFile(Stream stream, String filePath, PSCmdlet cmdlet, CancellationToken cancellationToken)
   at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(HttpResponseMessage response)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], UnauthorizedAccessException
FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
InvocationInfo        : 
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 28
    Line             : Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releases/download/2022-03-15/asio.1.12.1.nupkg' -OutFile "$home/Downloads/temp1"
    PositionMessage  : At line:1 char:1
                       + Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releas …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-WebRequest
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

SEE ABOVE

**Comment by 237dmitry** [comment]
You have to specify the file name `-OutFile /path/to/asio.1.12.1.nupkg`

**Comment by penalvch** [comment]
@237dmitry, thanks for the quick response!

While the documentation does confirm -OutFile requires a filename, the command did specify a filename called download, although with no extension. As is known, one can have a file with no extension in both Windows and macOS. The documentation does not advise having an extension is required:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.3

macOS:
![image](https://user-images.githubusercontent.com/115644052/201237269-c773919a-92ad-4949-b647-9c274388ee80.png)

Windows:
![image](https://user-images.githubusercontent.com/115644052/201237640-b3121438-0372-4f7f-9dd7-a6141e8e1d39.png)

Any problem with the docs being updated to advise having an extension is required, or would a FR be more appropriate here?

**Comment by 237dmitry** [comment]
Is temp1 an existing directory?
```powershell
$ Invoke-WebRequest -Uri 'https://github.com/ros2/choco-packages/releases/download/2022-03-15/asio.1.12.1.nupkg' -OutFile ./Desktop/filewithoutextension

$  dir ./Desktop/

    Directory: ~/Desktop

UnixMode     Num    User   Group      LastWriteTime    Size Name
--------     ---    ----   -----      -------------    ---- ----
drwxr-xr-x   755    herz    herz   11.11.2022 04:13         $x
-rw-r--r--   644    herz    herz   10.11.2022 23:34      68 0.ps1
-rw-r--r--   644    herz    herz   11.11.2022 03:31   52,2K 1.png
-rw-r--r--   644    herz    herz   19.10.2022 21:30    1,7K 1.ps1
-rw-r--r--   644    herz    herz   08.11.2022 18:03     999 cl.ps1
-rw-r--r--   644    herz    herz   11.11.2022 04:21  791,5K filewithoutextension
```

**Comment by penalvch** [comment]
Hi @237dmitry, yes, temp1 is an existing directory on both OSes.

**Comment by mklement0** [comment]
This issue isn't specific to `Invoke-WebRequest` and boils down to the fact that you cannot save file data to a _directory_ path.

You can provoke the symptom as follows: `'hi' > .`

That said, `-OutFile` _should_ allow passing a _directory_ path, in which case the name of the file being downloaded should _implicitly_ be used as the output file name inside that directory. See the following issue; @SteveL-MSFT has agreed to allowing this to be implemented as an _experimental_ feature first, but no one has stepped up yet:

  * #11671

**Comment by ali90taz** [comment]
> You have to specify the file name `-OutFile /path/to/asio.1.12.1.nupkg`

Very useful tip, fix my issues.
