### ISSUE TITLE
Invoke-WebRequest: Head request failing after update to v7.3.0

### ISSUE THREAD

**Issue by brogers5** [PowerShell/PowerShell#18531]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```ps1
Invoke-WebRequest -Uri 'https://www.foxit.com/downloads/latest.html?product=Foxit-Reader&platform=Windows&version=&package_type=exe&language=German' -Method Head
```

### Expected behavior

`Invoke-WebRequest` succeeds without issues.

I cannot reproduce this behavior with v7.2.7.

### Actual behavior

`Invoke-WebRequest` fails. The provided URI is claimed to be invalid, since the hostname is not parsed correctly.

### Error details

```console
Exception             : 
    Type       : System.UriFormatException
    TargetSite : 
        Name          : CreateThis
        DeclaringType : uri
        MemberType    : Method
        Module        : System.Private.Uri.dll
    Message    : Invalid URI: The hostname could not be parsed.
    Source     : System.Private.Uri
    HResult    : -2146233033
    StackTrace : 
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri.CreateUri(Uri baseUri, String relativeUri, Boolean dontEscape)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ParseLinkHeader(HttpResponseMessage response, Uri requestUri)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], UriFormatException
FullyQualifiedErrorId : System.UriFormatException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
InvocationInfo        : 
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : Invoke-WebRequest -Uri 'https://www.foxit.com/downloads/latest.html?product=Foxit-Reader&platform=Windows&version=&package_type=exe&language=German' -Method Head
    PositionMessage  : At line:1 char:1
                       + Invoke-WebRequest -Uri 'https://www.foxit.com/downloads/latest.html?p …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-WebRequest
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me on Windows with 7.3.0:

```console
PowerShell 7.3.0
C:\Users\slee
PS> Invoke-WebRequest -Uri 'https://www.foxit.com/downloads/latest.html?product=Foxit-Reader&platform=Windows&version=&package_type=exe&language=German' -Method Head

StatusCode        : 200
StatusDescription : OK
Content           : {}
RawContent        : HTTP/1.1 200 OK
                    Date: Mon, 14 Nov 2022 21:07:11 GMT
                    Server: Apache/2.4.10
                    Server: (Debian)
                    ETag: "bd1be58-5ec5f4890509a"
                    Accept-Ranges: bytes
                    Last-Modified: Tue, 01 Nov 2022 02:14:27 GMT
                    Conten…
Headers           : {[Date, System.String[]], [Server, System.String[]], [ETag, System.String[]], [Accept-Ranges, System.String[]]…}
RawContentLength  : 0
RelationLink      : {}
```

Does this repro consistently for you?

**Comment by brogers5** [comment]
I can only consistently reproduce this on one of my devices: a self-assembled desktop running Windows 11 22H2.

I've attempted reproduction from a Dell XPS 13 9310 2-in-1 (personal laptop) running Windows 11 22H2, as well as an HP ZBook Studio G5 (work laptop) running Windows 10 Enterprise 20H2. The request succeeded on both devices without issues.

On the failing device, the call succeeds in Windows PowerShell, but I'm seeing a different response which may be relevant:

```ps1
StatusCode        : 200
StatusDescription : OK
Content           : {}
RawContent        : HTTP/1.1 200 OK
                    Link: <https://*.foxitsoftware.com/product/manifest.txt>; rel=prefetch
                    Accept-Ranges: bytes
                    Content-Length: 198295128
                    Content-Type: application/x-msdos-program
                    Date: Mon, 14 Nov 2...
Headers           : {[Link, <https://*.foxitsoftware.com/product/manifest.txt>; rel=prefetch], [Accept-Ranges, bytes], [Content-Length, 198295128],
                    [Content-Type, application/x-msdos-program]...}
RawContentLength  : 0
```

Based on the stack trace, I'm guessing we're trying to parse the `Link` header's URI, which fails:

```ps1
PS C:\Users\brian> [System.Uri]::new('https://*.foxitsoftware.com/product/manifest.txt')
MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Invalid URI: The hostname could not be parsed."
```

**Comment by adityapatwardhan** [comment]
It seems that the regression was introduced by this change: https://github.com/PowerShell/PowerShell/pull/15973
Maybe @sliekens can help here?

**Comment by sliekens** [comment]
@adityapatwardhan @brogers5

I can see that the server is using unquoted rel types. (`rel=prefetch` instead of `rel="prefetch"`)

- PowerShell versions older than 7.3.0 completely ignore Link headers with unquoted reltypes.
  - (Technically, the regex patten didn't match)
- PowerShell 7.3.0 does support them, but now you have a different problem because `*` is not an allowed character for a hostname.
- It seems the server is also not consistently returning a Link header.

**Comment by SteveL-MSFT** [comment]
We should probably update the code so that if there is an exception parsing the links, we just leave the links empty and maybe emit a warning message.

**Comment by CarloToso** [comment]
@SteveL-MSFT #19162 shuld fix this issue, I'll add a warning message after we merge it in a following PR
