### ISSUE TITLE
"IBM437 is not supported encoding name" exception when saving Excel workbook on daily PS 7.3 build

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#18537]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Saving Excel workbook with *ImportExcel* module on latest daily build of PS 7.3 throws following exception:
*(It works correctly on PowerShell 7.3.0 GA and PowerShell 7.2.7 or PowerShell 5.1)*
```powershell
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "SaveAs" with "1" argument(s): "Error saving file ---"
                         ---> System.InvalidOperationException: Error saving file ---
                         ---> System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                           at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                           at System.Text.EncodingTable.GetCodePageFromName(String name)
                           at System.Text.Encoding.GetEncoding(String name)
                           at OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream..ctor(Stream stream, Boolean leaveOpen)
                           at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
                           at OfficeOpenXml.ExcelPackage.Save()
                           --- End of inner exception stack trace ---
                           at OfficeOpenXml.ExcelPackage.Save()
                           at CallSite.Target(Closure, CallSite, ExcelPackage, Object)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 1659
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 504
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 101
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 82
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\CompiledScriptBlock.cs:line 2435
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 593
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Close-ExcelPackage, C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.8.2\Public\Close-ExcelPackage.ps1: line 25
                        at Export-KBExcelNodeStatusReport<End>, <No file>: line 1001
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

### Expected behavior

```console
The Excel workbook should be saved without exception like on PowerShell 7.3.0 GA and PowerShell 7.2.7, or PowerShell 5.1
```

### Actual behavior

```console
An exception is thrown.
```

### Error details

```console
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "SaveAs" with "1" argument(s): "Error saving file ---"
                         ---> System.InvalidOperationException: Error saving file ---
                         ---> System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                           at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                           at System.Text.EncodingTable.GetCodePageFromName(String name)
                           at System.Text.Encoding.GetEncoding(String name)
                           at OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream..ctor(Stream stream, Boolean leaveOpen)
                           at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
                           at OfficeOpenXml.ExcelPackage.Save()
                           --- End of inner exception stack trace ---
                           at OfficeOpenXml.ExcelPackage.Save()
                           at CallSite.Target(Closure, CallSite, ExcelPackage, Object)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 1659
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 504
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 101
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 82
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\CompiledScriptBlock.cs:line 2435
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 593
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Close-ExcelPackage, C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.8.2\Public\Close-ExcelPackage.ps1: line 25
                        at Export-KBExcelNodeStatusReport<End>, <No file>: line 1001
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-461-g9f459c05f617fe530dac340aa546d198724d85da
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![exception](https://user-images.githubusercontent.com/16168755/201366948-8225c4ec-938d-4925-9466-bce19dff5850.jpg)

**Comment by iSazonov** [comment]
I guess it is regression after https://github.com/PowerShell/PowerShell/pull/18356/files#r1002716991

/cc @daxian-dbw

**Comment by xtqqczze** [comment]
The exception at `OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream..ctor` is in the `EPPlus, Version=4.5.3.2, Culture=neutral, PublicKeyToken=ea159fdaa78159a1` assembly.

Decompilation yields the following code:

```csharp
private Encoding _alternateEncoding = Encoding.GetEncoding("IBM437");
```

Since .NET Core, IBM437 encoding is not natively supported by `GetEncoding`, instead it must be made available by registering an [EncodingProvider](https://learn.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=net-7.0) object.

As the version of `EPPlus.dll` in ImportExcel targets .NET Framework 4.0 (where `EncodingProvider` does not exist), it would seems it is not compatible with .NET Core.

It is very likely #18356 exposed this issue, but I don't think we should revert the changes. We should instead consider changes to register the necessary encoding provider when loading assemblies targeting .NET Framework 4.5 and earlier.

**Comment by jhoneill** [comment]
> As the version of `EPPlus.dll` in ImportExcel targets .NET Framework 4.0 (where `EncodingProvider` does not exist), it would seems it is not compatible with .NET Core.

You missed the part above which said that it works with Powershell 7.3 GA 

> Since .NET Core, IBM437 encoding is not natively supported by `GetEncoding`,

I might misunderstand you but  ` [System.Text.Encoding]::GetEncoding("IBM437") `  **works** in 7.3 GA.  The code you decompiled looks to be calling exactly the same thing. 

` [System.Text.Encoding]::GetEncodings() | Sort-Object name` gives a list of encoding that should work with `GetEncoding`

Since I don't have the daily build maybe testing 
` [System.Text.Encoding]::GetEncodings() | % { [System.Text.Encoding]::GetEncoding($_.name)}` with it would be a good idea ?

**Comment by kborowinski** [comment]
PS 7.3 GA:
```powershell
> [Text.Encoding]::GetEncodings()|%{[Text.Encoding]::GetEncoding($_.Name).WebName}
shift_jis
ibm860
ibm861
ibm880
dos-862
ibm863
gb2312
ibm864
ibm865
cp866
koi8-u
ibm037
ibm869
ibm500
x-mac-icelandic
ibm01140
ibm01141
ibm01142
ibm273
ibm01143
ibm01144
ibm01145
windows-1250
ibm01146
windows-1251
ibm01147
macintosh
windows-1252
dos-720
ibm277
ibm01148
x-mac-japanese
windows-1253
ibm437
ibm278
ibm01149
x-mac-chinesetrad
windows-1254
windows-1255
johab
windows-1256
x-mac-arabic
windows-1257
x-mac-hebrew
windows-1258
x-mac-greek
x-mac-cyrillic
ibm00924
iso-8859-2
iso-8859-3
iso-8859-4
iso-8859-5
iso-8859-6
ibm870
iso-8859-7
iso-8859-8
iso-8859-9
x-mac-turkish
x-mac-croatian
windows-874
cp875
ibm420
ks_c_5601-1987
ibm423
ibm424
ibm280
ibm01047
ibm284
ibm285
x-mac-romanian
euc-jp
x-mac-ukrainian
x-europa
ibm737
x-ia5
big5
x-cp20936
x-ia5-german
x-ia5-swedish
x-ia5-norwegian
koi8-r
ibm775
iso-8859-13
ibm290
iso-8859-15
x-chinese-cns
asmo-708
ibm297
x-mac-thai
x-cp20001
ibm905
x-chinese-eten
x-ebcdic-koreanextended
x-cp20003
x-cp20004
x-cp20005
ibm850
ibm-thai
ibm852
ibm871
x-mac-ce
ibm855
cp1025
x-cp20949
ibm857
ibm00858
x-cp20261
ibm1026
x-cp20269
utf-16
utf-16BE
utf-32
utf-32BE
us-ascii
iso-8859-1
utf-8
```

vs latest daily 7.3:
```powershell
> [Text.Encoding]::GetEncodings()|%{[Text.Encoding]::GetEncoding($_.Name).WebName}
utf-16
utf-16BE
utf-32
utf-32BE
us-ascii
iso-8859-1
utf-8
```

**Comment by xtqqczze** [comment]
@kborowinski Could you please try invoking the following command:

```powershell
[System.Text.Encoding]::RegisterProvider([System.Text.CodePagesEncodingProvider]::Instance)
```

**Comment by jhoneill** [comment]
@kborowinski  Woah .. that's very , very bad. It means you can't set `$outputEncoding` to the default windows code page for Europe (IBM 850) or "Ansi" aka Windows 1252

**Comment by kborowinski** [comment]
@xtqqczze Thanks, it solves the problem. I'll add it to my profile as a workaround for the time being.

**Comment by xtqqczze** [comment]
Source code for `OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream._alternateEncoding`:

```csharp
#if (Core)
        private System.Text.Encoding _alternateEncoding
            = System.Text.Encoding.GetEncoding("utf-8"); // 
#else
        private System.Text.Encoding _alternateEncoding
            = System.Text.Encoding.GetEncoding("IBM437"); // default = IBM437
#endif
```

https://github.com/JanKallman/EPPlus/blob/4dacf27661b24d92e8ba3d03d51dd5468845e6c1/EPPlus/Packaging/DotNetZip/ZipOutputStream.cs#L1622-L1628

**Comment by xtqqczze** [comment]
> @kborowinski Woah .. that's very , very bad. It means you can't set `$outputEncoding` to the default windows code page for Europe (IBM 850) or "Ansi" aka Windows 1252

Using PowerShell Core on Windows, the most reliable method to achieve this is as follows:
```csharp
$OutputEncoding = [System.Text.CodePagesEncodingProvider]::Instance.GetEncoding(850)
```

**Comment by jhoneill** [comment]
> ```cs
> $OutputEncoding = [System.Text.CodePagesEncodingProvider]::Instance.GetEncoding(850)
> ```

That's not helpful in a script which needs to work on a Windows machine which has not had PowerShell 7 added to to it., to work _everywhere_ a script needs to use `[System.Text.Encoding]::GetEncoding("IBM437")` .  

Up to 7.3 GA this works, there is no good reason to break it, and **if this new bug can't be fixed the code needs to be reverted.**

**Comment by daxian-dbw** [comment]
The root cause is:
- before the change of #18356, `Encoding.RegisterProvider` will be called on the first time retrieving the default encoding by `GetDefaultEncoding()`, which happens when loading the `PSReadLine` module on startup. So, the encoding provider gets registered early enough for `GetEncoding("IBM437")` to work in user script/code. 
- after #18356, `Encoding.RegisterProvider` won't be called until `GetOEMEncoding()` is called, which happens pretty late -- until you run a cmdlet that accesses `EncodingConversion`. So, the encoding provider is not registered when `GetEncoding("IBM437")` is used in user script/code.

I've submitted #18605 to fix the regression.
