### ISSUE TITLE
Type 'System.Management.Automation.OrderedHashtable' in Assembly 'System.Management.Automation, Version=7.3.0.500' is not marked as serializable.

### ISSUE THREAD

**Issue by ClaudiuSchuster** [PowerShell/PowerShell#18551]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

**$obj = [System.Management.Automation.OrderedHashtable]@{}**
$ms = New-Object System.IO.MemoryStream
$bf = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
$bf.Serialize($ms, $obj)

### OR 

**$obj = '{}' | ConvertFrom-JSON -AsHashtable**
$ms = New-Object System.IO.MemoryStream
$bf = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
try { $bf.Serialize($ms, $obj) } catch { get-error $_}

### Expected behavior

```console
Serializing the object as pwsh versions before ...
```

### Actual behavior

```console
Exception calling "Serialize" with "2" argument(s): "Type 'System.Management.Automation.OrderedHashtable' in Assembly 'System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
```

### Error details

```console
Exception             : 
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Serialize" with "2" argument(s): "Type 'System.Management.Automation.OrderedHashtable' in Assembly 'System.Management.Automation, Version=7.3.0.500, 
Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : SerializationException
        InvocationInfo        : 
            ScriptLineNumber : 7
            OffsetInLine     : 15
            HistoryId        : -1
            ScriptName       : D:\test.ps1
            Line             : try { $bf.Serialize($ms, $obj) } catch { get-error $_}

            PositionMessage  : At D:\test.ps1:7 char:15
                               +         try { $bf.Serialize($ms, $obj) } catch { get-error $_}
                               +               ~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : D:\
            PSCommandPath    : D:\test.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, D:\test.ps1: line 7
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Serialize" with "2" argument(s): "Type 'System.Management.Automation.OrderedHashtable' in Assembly 'System.Management.Automation, Version=7.3.0.500, 
Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type       : System.Runtime.Serialization.SerializationException
        TargetSite : 
            Name          : InitSerialize
            DeclaringType : System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo, System.Runtime.Serialization.Formatters, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a     
            MemberType    : Method
            Module        : System.Runtime.Serialization.Formatters.dll
        Message    : Type 'System.Management.Automation.OrderedHashtable' in Assembly 'System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked    
as serializable.
        Source     : System.Runtime.Serialization.Formatters
        HResult    : -2146233076
        StackTrace : 
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, 
IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at CallSite.Target(Closure, CallSite, Object, Object, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : SerializationException
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 5.17.4-200.fc35.x86_64 #1 SMP PREEMPT Wed Apr 20 15:37:53 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

AND

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ClaudiuSchuster** [comment]
Same on:

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by ClaudiuSchuster** [comment]
```
$obj = '{}' | ConvertFrom-Json -AsHashtable

# workaround start
$_obj = $obj -is [System.Management.Automation.OrderedHashtable] ? @{} : $obj
if ($obj -is [System.Management.Automation.OrderedHashtable]) {
    foreach ($e in $obj.GetEnumerator()) { $_obj.Add($e.key, $e.value) }
}
# workaround end

$ms = New-Object System.IO.MemoryStream
$bf = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
$bf.Serialize($ms, $_obj)
```

**Comment by jborean93** [comment]
You should avoid using the binary formatter as per https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide. If you wish to serializer and deserialize data you can use PowerShell CLIXML output.

```powershell
$clixml = [System.Management.Automation.PSSerializer]::Serialize($obj, $depth)  # Depth is optiona

[System.Management.Automation.PSSerialize]::Deserialize($clixml)
```

There's also `Export-Clixml` and `Import-Clixml` which do the same thing but deal with files directly.

**Comment by xtqqczze** [comment]
Related issue: #14054.

**Comment by xtqqczze** [comment]
Its seems calls to BinaryFormatter APIs are disabled in .NET 7.

**Comment by ClaudiuSchuster** [comment]
> You should avoid using the binary formatter as per https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide. If you wish to serializer and deserialize data you can use PowerShell CLIXML output.
> 
> ```powershell
> $clixml = [System.Management.Automation.PSSerializer]::Serialize($obj, $depth)  # Depth is optional
> 
> [System.Management.Automation.PSSerialize]::Deserialize($clixml)
> ```
> 
> There's also `Export-Clixml` and `Import-Clixml` which do the same thing but deal with files directly.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b4e2e8d4b12a27bb9a0d7d7cc2211cb53f6e473cd20eeec671c70d6f32eb017c/68747470733a2f2f6c6561726e2e6d6963726f736f66742e636f6d2f646f746e65742f6d656469612f646f742d6e65742d63726f73732d706c6174666f726d2e706e67">**[Deserialization risks in use of BinaryFormatter and related types](https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)**Learn about security vulnerabilities of BinaryFormatter, SoapFormatter, NetDataContractSerializer, LosFormatter, and ObjectStateFormatter. The article recommends safer alternatives.

Thank you that explained and solved *my* issue :-)

My function is now working again after the clixml rework :-)
```
function Copy-Object {
    <#
        .SYNOPSIS
        Deep-Copy a PowerShell Object
        .DESCRIPTION
        Copy-Object will Deep-Copy a PowerShell Object.
        .OUTPUTS
        [object]
        .EXAMPLE
        Copy-Object $InputObjectect
        $deepCopy
        .EXAMPLE
        Copy-Object -InputObject $InputObjectect
        $deepCopy
    #>
    [CmdletBinding()] param (
        # Specifies the InputObject for deep copy
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)] [object]
        $InputObject
    ) Begin { } Process {
        $s = [System.Management.Automation.PSSerializer]::Serialize($InputObject, [int32]::MaxValue)
        return [System.Management.Automation.PSSerializer]::Deserialize($s)
    }
}

```

**Comment by ClaudiuSchuster** [comment]
> Related issue: #14054.

Thank you that explains *my* issue, yep BinaryFormatter is gone, so I will close the issue
