### ISSUE TITLE
Tuples from System.Tuple Get a Bogus Typename and thus can't be used for parameters in functions. 

### ISSUE THREAD

**Issue by wkyrlach** [PowerShell/PowerShell#18563]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$Person = New-Object -TypeName 'System.Tuple[String,String]' -ArgumentList 'Helen', 'Bob'
$Person | Get-Member

TypeName: System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e]]

When passing to a function...

PS C:\Program Files\PowerShell\7> function Garbage-Test-Function
>> {
>> [CmdletBinding()]
>> Param(
>>     [Parameter(Mandatory=$true, position=0)]
>>     [System.Tuple] $somePair
>> )
>> Process
>> {
>> $functionName = "Update-Json-String"
>> $somePair
>>     }
>> }

Garbage-Test-Function $Person

PS C:\Program Files\PowerShell\7> Garbage-Test-Function $Person
Garbage-Test-Function: Cannot process argument transformation on parameter 'somePair'. Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".

### Expected behavior

```console
Garbage-Test-Function $Person
$Person

Item1 Item2 Length
----- ----- ------
Helen Bob        2
```

### Actual behavior

```console
Garbage-Test-Function $Person

PS C:\Program Files\PowerShell\7> Garbage-Test-Function $Person
Garbage-Test-Function: Cannot process argument transformation on parameter 'somePair'. Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
```

### Error details

```console
PS C:\Program Files\PowerShell\7> get-error

Exception             :
    Type              : System.Management.Automation.ParameterBindingArgumentTransformationException
    Message           : Cannot process argument transformation on parameter 'somePair'. Cannot convert the "(Helen,
Bob)" value of type "System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
    ParameterName     : somePair
    ParameterType     : System.Tuple
    TypeSpecified     : psobject
    ErrorId           : ParameterArgumentTransformationError
    Line              : 1
    Offset            : 23
    CommandInvocation :
        MyCommand        : Garbage-Test-Function
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 40
        Line             : Garbage-Test-Function $Person
        PositionMessage  : At line:1 char:1
                           + Garbage-Test-Function $Person
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Garbage-Test-Function
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot process argument transformation on parameter 'somePair'. Cannot convert the "(Helen,
Bob)" value of type "System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Garbage-Test-Function], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentTransformationError,Garbage-Test-Function
        InvocationInfo        :
            MyCommand        : Garbage-Test-Function
            ScriptLineNumber : 1
            OffsetInLine     : 23
            HistoryId        : 40
            Line             : Garbage-Test-Function $Person
            PositionMessage  : At line:1 char:23
                               + Garbage-Test-Function $Person
                               +                       ~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : BindPositionalParametersInSet
        DeclaringType : System.Management.Automation.ParameterBinderController, System.Management.Automation,
Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type           : System.Management.Automation.ArgumentTransformationMetadataException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
                HResult : -2146233087
            CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : RuntimeException
        TargetSite     :
            Name          : Transform
            DeclaringType : System.Management.Automation.ArgumentTypeConverterAttribute, System.Management.Automation,
Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
        InnerException :
            Type        : System.Management.Automation.PSInvalidCastException
            ErrorRecord :
                Exception             :
                    Type    : System.Management.Automation.ParentContainsErrorRecordException
                    Message : Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
                    HResult : -2146233087
                CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
                FullyQualifiedErrorId : ConvertToFinalInvalidCastException
            TargetSite  :
                Name          : ThrowInvalidCastException
                DeclaringType : System.Management.Automation.LanguagePrimitives
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message     : Cannot convert the "(Helen, Bob)" value of type "System.Tuple`2[[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type "System.Tuple".
            Source      : System.Management.Automation
            HResult     : -2147467262
            StackTrace  :
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType,
Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType,
Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean
recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object
inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
        Source         : System.Management.Automation
        HResult        : -2146233087
        StackTrace     :
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object
inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderController.BindPositionalParametersInSet(UInt32 validParameterSets,
Dictionary`2 nextPositionalParameters, CommandParameterInternal argument, ParameterBindingFlags flags,
ParameterBindingException& bindingException)
   at System.Management.Automation.ParameterBinderController.BindPositionalParameters(Collection`1 unboundArguments,
UInt32 validParameterSets, UInt32 defaultParameterSet, ParameterBindingException& outgoingBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Garbage-Test-Function], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Garbage-Test-Function
InvocationInfo        :
    MyCommand        : Garbage-Test-Function
    ScriptLineNumber : 1
    OffsetInLine     : 23
    HistoryId        : 40
    Line             : Garbage-Test-Function $Person
    PositionMessage  : At line:1 char:23
                       + Garbage-Test-Function $Person
                       +                       ~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Define  ```
[Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e]]]``` )))))

As a workaround, this woks without type definition

```powershell
function test
{
    param (
        [Parameter()]
        $somepair
    )
    $somepair.GetType()
}

$tuple = [tuple]::Create('a','b')
test $tuple
```

**Comment by jhoneill** [comment]
@237dmitry  posted while I was typing :-) 
Don't specify the type conversion for the the parameter. 
In many languages parameters have type constraints which say this parameter must be of type X. In PowerShell the type specifies that the parameter should be converted. 

`[system.tuple]::Create("bob","Helen") | gm` returns the same specialized type and  I think (but haven't checked) that happens in any .NET language

**Comment by 237dmitry** [comment]
The same is in Windows Powershell.

**Comment by wkyrlach** [comment]
Thank you for the replies and work arounds.

Goal is to program in a type safe way.  Since Powershell has the type [system.touple], and they fill a nice niche between arrays and structs, I'd love to see [System.Tuple] get fixed in a future patch.

**Comment by jhoneill** [comment]
Yeah, PowerShell does a lot of things to help those who don't want to be type safe - or even type _aware_, that's what separates "scripting" languages form compiled languages. I've never needed `tuple` as a parameter in the small amount of C# I've done so I don't know what happens there, but my hunch is this behaviour is the same over everything using .NET  It doesn't help that when a tuple is created the new object's type is not derived from `tuple` but from `system.object`

**Comment by MartinGC94** [comment]
If your goal is to accept all sorts of different tuples then you need to leave out the type constraint or manually specify `[system.object]` because they are all distinct types. If your goal is to accept a specific tuple type then you just need to specify it the same way you do when you create the tuple:

```
function Verb-Noun
{
    Param
    (
        [Parameter()]
        [System.Tuple[string,string]]
        $Param1
    )
    $Param1
}
$Tuple = [System.Tuple[string,string]]::new("Hello","World")
Verb-Noun -Param1 $Tuple
```

**Comment by MartinGC94** [comment]
I would call it user error. I'm by no means an expert in Generic types but from what I understand generics like `[System.Collections.Generic.Dictionary]` always require type arguments like `[System.Collections.Generic.Dictionary[string,int]]` if you don't provide a type argument PowerShell won't find the type:
```
PS C:\> [System.Collections.Generic.Dictionary]
InvalidOperation: Unable to find type [System.Collections.Generic.Dictionary].
PS C:\>
```
I don't understand why there's a non-generic `System.Tuple` type but as you've discovered you can't use it interchangeably with the typed variants.

Also that long name you found is an assembly qualified name and if you wanted to you could use it as an argument like this:

```
Param
(
    [Parameter()]
    [System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]]
    $Param1
)
```

but the short name is typically the way to go.

**Comment by mklement0** [comment]
@wkyrlach, indeed it's not a bug. Let me attempt a systematic summary, building on the existing, helpful comments:

* ``[System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]]`` may look funny, but it's the correct type name, which can be simplified to `[System.Tuple[string,string]]` and even `[Tuple[string, string]]`
  (I'm unclear on why .NET expresses the type arguments of generic types by their _assembly-qualified name_ - PowerShell is just the messenger here)):

```powershell
# -> $true
[Tuple[string, string]] -eq [System.Tuple`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]] 

# -> the verbose form as a string (without enclosing "[" and "]")
[Tuple[string, string]].FullName
```

* [`System.Tuple`](https://docs.microsoft.com/en-US/dotnet/api/System.Tuple) and [`System.ValueTuple`](https://docs.microsoft.com/en-US/dotnet/api/System.ValueTuple) are nongeneric, _static helper classes_ that _facilitate the construction of_ tuple and value tuples, which themselves are instances of _generic_ types:

```powershell
# Creates an instance of [Tuple[string, int]]
[Tuple]::Create('one', 42).GetType().FullName

# Equivalent, using the result type explicitly:
[Tuple[string, int]]::new('one', 42)
```

* The always-generic tuple and value-tuple types (e.g, [``System.Tuple`2``](https://learn.microsoft.com/en-us/dotnet/api/system.tuple-2) or  [``System.ValueTuple`2``](https://learn.microsoft.com/en-us/dotnet/api/system.valuetuple-2)) do NOT inherit from `System.Tuple` and `System.ValueTuple`, which is the the reason you cannot use the latter as _parameter_ types:

```powershell
# !! BREAKS, because [System.Tuple[string, int]] does NOT derive from [System.Tuple]
& {
  param(
    [System.Tuple] $tuple  # !! WRONG
  ) 
  $tuple
}  ([System.Tuple]::Create('one', 42))
```

* **To type script or function parameters as tuples or value tuples**, you have two options:

  * To only accept (value) tuples with a specific arity (element count) and fixed element types, in order, use the exact type, as @MartinGC94  has already shown (e.g, `param([Tuple[string, int]] $tuple)`)

  * If the parameter must be more flexible with respect to what tuples it accepts:
    * type it as [`[System.Runtime.CompilerServices.ITuple]`](https://docs.microsoft.com/en-US/dotnet/api/System.Runtime.CompilerServices.ITuple), which makes it accept _any_ tuple or value tuple, irrespective of arity and element types.
    * if needed, enforce constraints with respect to arity or element types via a `[ValidateScript()]` attribute.
    
The following sample commands demonstrate all techniques:

```powershell
# Accept any tuple (value or not, any arity, any element types)
& { 
 param(
   [System.Runtime.CompilerServices.ITuple] $tuple
 )
$tuple 
} ([ValueTuple]::Create('one',42))

# Accept a tuple with fixed arity and element types - must commit to Tuple vs. ValueTuple
& { 
  param(
    [System.ValueTuple[string, int]] $tuple
  ) 
  $tuple 
} ([ValueTuple]::Create('one', 42))

# *Selectively* Constraining arity and / or element types requires a *validation attribute*:
# Accept (value-or-not) tuples with a given arity, irrespective of element types.
& { 
  param(
    [ValidateScript({ $_.Length -eq 2 }, ErrorMessage="Tuple length must be 2.")] 
    [System.Runtime.CompilerServices.ITuple] $tuple
  )
  $tuple 
} ([ValueTuple]::Create('one', 42))

# Accept (value-or-not) tuples with any arity, but only with elements of a given type
& { 
  param(
    [ValidateScript(
      { [string] -eq ($_[0..($_.Length-1)] | ForEach-Object GetType | Select-Object -Unique) }, 
      ErrorMessage="All tuple elements must be strings."
    )] 
    [System.Runtime.CompilerServices.ITuple] $tuple
  ) 
  $tuple 
} ([ValueTuple]::Create('one', 'two'))
```
