### ISSUE TITLE
PSInvalidCastException: Cannot convert value "Utc" to type "System.Int32". Creating date in 7.3

### ISSUE THREAD

**Issue by Seekatar** [PowerShell/PowerShell#18589]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When creating a DateTime pre 7.3.0, this worked

`New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,'Utc'`

Adding another 0 fixes it. This works in 7.3 (but fails in 7.2.7) 

`New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,0,'Utc'`

Thursday, January 1, 1970 12:00:00 AM

This change broke my module published in the Gallery and I can't just add a zero since that would break users on earlier versions.

### Expected behavior

```console
PS> New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,'Utc'
Thursday, January 1, 1970 12:00:00 AM
```

### Actual behavior

```console
PS> New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,'Utc'
New-Object: Cannot convert argument "7", with value: "Utc", for "DateTime" to type "System.Int32": "Cannot convert value "Utc" to type "System.Int32". Error: "The input string 'Utc' was not in a correct format.""
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.MethodException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert argument "7", with value: "Utc", for "DateTime" to type "System.Int32": "Cannot convert value "Utc"
to type "System.Int32". Error: "The input string 'Utc' was not in a correct format.""
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
    TargetSite     :
        Name          : SetNewArgument
        DeclaringType : System.Management.Automation.Adapter, System.Management.Automation, Version=7.3.0.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Cannot convert argument "7", with value: "Utc", for "DateTime" to type "System.Int32": "Cannot convert value "Utc"
to type "System.Int32". Error: "The input string 'Utc' was not in a correct format.""
    InnerException :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "Utc" to type "System.Int32". Error: "The input string 'Utc' was not in a correct format."
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidCastFromStringToInteger
        TargetSite     :
            Name          : ConvertStringToInteger
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "Utc" to type "System.Int32". Error: "The input string 'Utc' was not in a correct format."
        InnerException :
            Type       : System.FormatException
            TargetSite :
                Name          : ThrowOverflowOrFormatException
                DeclaringType : System.Number, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : The input string 'Utc' was not in a correct format.
            Source     : System.Private.CoreLib
            HResult    : -2146233033
            StackTrace :
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertStringToInteger(Object valueToConvert, Type resultType, Boolean recursion,
PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse,
PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion,
IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.Adapter.PropertySetAndMethodArgumentConvertTo(Object valueToConvert, Type resultType, IFormatProvider
formatProvider)
   at System.Management.Automation.Adapter.MethodArgumentConvertTo(Object valueToConvert, Boolean isParameterByRef, Int32
parameterIndex, Type resultType, IFormatProvider formatProvider)
   at System.Management.Automation.Adapter.SetNewArgument(String methodName, Object[] arguments, Object[] newArguments,
ParameterInformation parameter, Int32 index)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.Adapter.SetNewArgument(String methodName, Object[] arguments, Object[] newArguments,
ParameterInformation parameter, Int32 index)
   at System.Management.Automation.Adapter.GetMethodArgumentsBase(String methodName, ParameterInformation[] parameters, Object[]
arguments, Boolean expandParamsOnBest)
   at System.Management.Automation.Adapter.GetBestMethodAndArguments(String methodName, MethodInformation[] methods,
PSMethodInvocationConstraints invocationConstraints, Object[] arguments, Object[]& newArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
InvocationInfo        :
    MyCommand        : New-Object
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 32
    Line             : New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,'Utc'
    PositionMessage  : At line:1 char:1
                       + New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,'Utc'
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
I only have 7.3 and 5.1 installed on my PC so I can't check if it's new in 7.3 or if it was added earlier but it looks like there's a new overload definition for the datetime constructor: `datetime new(int year, int month, int day, int hour, int minute, int second, int millisecond, int microsecond)` and that's what you are hitting.  
The fix for this is to not rely on the string -> Enum conversion and instead specify the enum directly: `New-Object DateTime -ArgumentList 1970,1,1,0,0,0,0,([System.DateTimeKind]::Utc)` this works in both 5.1 and 7.3

Maybe converting strings to enums should have a higher priority than ints? It would be a breaking change but maybe it's worth it?

**Comment by Seekatar** [comment]
Thanks. I tried the enum, but missed adding the parens. I also found this worked for both versions.  `$script:epochStart = [DateTime]::parse('1970-01-01T00:00:00.0000000Z',$null,'AdjustToUniversal')` 

I have a box with 7.2.7 on it and that worked, so it's after that.

**Comment by mklement0** [comment]
@MartinGC94, good point about making `[string]` arguments looking for `[enum]` parameters first: this was asked before: 
* #13161

@Seekatar, as an alternative approach, consider the following:

```powershell
# v7.2+
Get-Date '1970-01-01Z' -AsUTC

# cross-edition
(Get-Date '1970-01-01Z').ToUniversalTime()
```

**Comment by mklement0** [comment]
As for the unfortunately _unavoidable_ perils of _non-type-exact_ .NET method calls from PowerShell over time, see [this comment](https://github.com/PowerShell/PowerShell/issues/11720#issuecomment-579866445).
