### ISSUE TITLE
Forcing a hard link to itself deletes the file

### ISSUE THREAD

**Issue by Yay295** [PowerShell/PowerShell#18620]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$filename = 'test.txt'
'Hello, world!' | Out-File -LiteralPath $filename
New-Item -ItemType HardLink -Name $filename -Value $filename -Force
```

### Expected behavior

```console
The existing file is not deleted.
```

### Actual behavior

```console
The existing file is deleted.
```

### Error details

```console
New-Item : The system cannot find the file specified
At line:1 char:1
+ New-Item -ItemType HardLink -Name $filename -Value $filename -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.NewItemCommand

```powershell
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 2
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : NewItem
        DeclaringType : Microsoft.PowerShell.Commands.FileSystemProvider
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message         : The system cannot find the file specified.
    Source          : System.Management.Automation
    HResult         : -2147467259
    StackTrace      :
   at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
   at System.Management.Automation.SessionStateInternal.NewItemPrivate(CmdletProvider providerInstance, String path, String type, Object content, CmdletProviderContext context)
CategoryInfo          : NotSpecified: (:) [New-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.NewItemCommand
InvocationInfo        :
    MyCommand        : New-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 152
    Line             : New-Item -ItemType HardLink -Name $filename -Value $filename -Force
    PositionMessage  : At line:1 char:1
                       + New-Item -ItemType HardLink -Name $filename -Value $filename -Force
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by Yay295** [comment]
I included PowerShell 5.1 for comparison because it does have the same issue.

**Comment by 237dmitry** [comment]
> Expected behavior
>The existing file is not deleted.

![hl](https://user-images.githubusercontent.com/78153320/202889058-1eb7085c-cbd8-42b7-9f30-e2a04d9f1a18.png)

**Comment by Yay295** [comment]
🤷‍♀️
![capture_2022-11-20_00 55 41_06](https://user-images.githubusercontent.com/8922038/202889924-7e976006-88ff-486b-83a5-bbd1e7468357.png)

**Comment by mklement0** [comment]
That's unfortunate.

A note on reproducing the symptom: 
  * It may be obscured by an unrelated bug:
    * https://github.com/PowerShell/PowerShell/issues/18623
  * To see the symptom, `[Environment]::CurrentDirectory = $PWD.ProviderPath` must be run first, or full paths must be used.

A related bug is that when you use `-ItemType SymbolicLink`, creation of the symlink unexpectedly succeeds, and creates a link that points to itself.

In both cases, `-Force` is the culprit, and a fix necessitates implementing an up-front check for whether the `-Path` and `-Target` paths are, in effect, the same (requires resolving them to full, normalized paths with any symlink components resolved) and error out, if so.
