### ISSUE TITLE
[System.Data.Sql.SqlDataSourceEnumerator] type not available

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#18654]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
PS C:\> [System.Data.Sql.SqlNotificationRequest]
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    SqlNotificationRequest                   System.Object

PS C:\> [System.Data.Sql.SqlDataSourceEnumerator]
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    SqlDataSourceEnumerator                  System.Data.Common.DbDataSourceEnume...
PS C:\> $PSVersionTable.PSVersion.ToString()
5.1.19041.1682
```

SqlDataSourceEnumeratr is not available on PowerShell Core 7.3

```
PS C:\> [System.Data.Sql.SqlNotificationRequest]
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    SqlNotificationRequest                   System.Object

PS C:\> [System.Data.Sql.SqlDataSourceEnumerator]
InvalidOperation: Unable to find type [System.Data.Sql.SqlDataSourceEnumerator].
PS C:\> $PSVersionTable.PSVersion.ToString()
7.3.0
```

### Expected behavior

```console
[System.Data.Sql.SqlDataSourceEnumerator] is available.
```

### Actual behavior

```console
InvalidOperation: Unable to find type [System.Data.Sql.SqlDataSourceEnumerator].
```

### Error details

```console
PS C:\> Get-Error

Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to find type [System.Data.Sql.SqlDataSourceEnumerator].
            HResult : -2146233087
        TargetObject          : System.Data.Sql.SqlDataSourceEnumerator
        CategoryInfo          : InvalidOperation: (System.Data.Sql.SqlDataSourceEnumerator:TypeName) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : TypeNotFound
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : [System.Data.Sql.SqlDataSourceEnumerator]
            PositionMessage  : At line:1 char:1
                               + [System.Data.Sql.SqlDataSourceEnumerator]
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : ResolveTypeName
        DeclaringType : System.Management.Automation.TypeOps, System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Unable to find type [System.Data.Sql.SqlDataSourceEnumerator].
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : System.Data.Sql.SqlDataSourceEnumerator
CategoryInfo          : InvalidOperation: (System.Data.Sql.SqlDataSourceEnumerator:TypeName) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : [System.Data.Sql.SqlDataSourceEnumerator]
    PositionMessage  : At line:1 char:1
                       + [System.Data.Sql.SqlDataSourceEnumerator]
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
There is no `System.Data.Sql.SqlDataSourceEnumerator` class in net-7.0, the latest is .NET Framework 4.8

**Comment by Liturgist** [comment]
> There is no `System.Data.Sql.SqlDataSourceEnumerator` class in net-7.0, the latest is .NET Framework 4.8

Is there a way to achieve this functionality?

**Comment by 237dmitry** [comment]
> Is there a way to achieve this functionality?

I do not programmer or IT-specialist, try to load System.Data.dll from .Net-Framework

```powershell
PS > Add-Type -AssemblyName C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll
PS > [System.Data.Sql.SqlDataSourceEnumerator]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    SqlDataSourceEnumerator                  System.Data.Common.DbDataSourceEnumerator
```

**Comment by kilasuit** [comment]
There is a recommendation to move from using `System.Data` to `Microsoft.Data`, I am trying to find the blog post about it but struggling.

**Comment by CarloToso** [comment]
@iSazonov we can close

**Comment by iSazonov** [comment]
It seems System.Data.Sql is not supported on .Net Core at all.

We are tracking System.Data.SqlClent in #16156
Blog post https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/
