### ISSUE TITLE
The first array type in a generic method doesn't work

### ISSUE THREAD

**Issue by InSb** [PowerShell/PowerShell#18686]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I try to flatten a two-dimensional array by `Enumerable.SelectMany` method with generic type arguments, the first type argument `int[]` may not be treated correctly.
```powershell
[Linq.Enumerable]::SelectMany[int[], int](
  [int[][]] @((,2), (,4), (,6), (,8)),
  [Func[[int[]], int[]]] { param ($x); $x }
) | ConvertTo-Json -Compress
```

### Expected behavior

```console
[2,4,6,8]
```

### Actual behavior

```console
Unable to find type [int,int].
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to find type [int,int].
            HResult : -2146233087
        TargetObject          : int,int
        CategoryInfo          : InvalidOperation: (int,int:TypeName) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : TypeNotFound
        InvocationInfo        :
            ScriptLineNumber : 2
            OffsetInLine     : 31
            HistoryId        : -1
            Line             : [Linq.Enumerable]::SelectMany[int[], int](

            PositionMessage  : At line:2 char:31
                               + [Linq.Enumerable]::SelectMany[int[], int](
                               +                               ~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
    TargetSite  :
        Name          : ResolveTypeName
        DeclaringType : System.Management.Automation.TypeOps, System.Management.Automation, Version=7.3.0.500, Culture=
neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Unable to find type [int,int].
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Adapter.ResolveGenericTypeParameters(Object[] genericTypeParameters)
   at System.Management.Automation.Adapter.FindBestMethodImpl(MethodInformation[] methods, PSMethodInvocationConstraint
s invocationConstraints, Boolean allowCastingToByRefLikeType, Object[] arguments, String& errorId, String& errorMsg, Bo
olean& expandParamsOnBest)
   at System.Management.Automation.Adapter.FindBestMethod(MethodInformation[] methods, PSMethodInvocationConstraints in
vocationConstraints, Boolean allowCastingToByRefLikeType, Object[] arguments, String& errorId, String& errorMsg, Boolea
n& expandParamsOnBest, Boolean& callNonVirtually)
   at System.Management.Automation.Language.PSInvokeMemberBinder.InvokeDotNetMethod(CallInfo callInfo, String name, PSM
ethodInvocationConstraints psMethodInvocationConstraints, MethodInvocationType methodInvocationType, DynamicMetaObject
target, DynamicMetaObject[] args, BindingRestrictions restrictions, MethodInformation[] mi, Type errorExceptionType)
   at System.Management.Automation.Language.PSInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, Dynamic
MetaObject[] args, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLab
el)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : int,int
CategoryInfo          : InvalidOperation: (int,int:TypeName) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
InvocationInfo        :
    ScriptLineNumber : 2
    OffsetInLine     : 31
    HistoryId        : -1
    Line             : [Linq.Enumerable]::SelectMany[int[], int](

    PositionMessage  : At line:2 char:31
                       + [Linq.Enumerable]::SelectMany[int[], int](
                       +                               ~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CarloToso** [comment]
It should work like this:
```ps1
[Linq.Enumerable]::SelectMany(
  [int[][]] @((,2), (,4), (,6), (,8)),
  [Func[[int[]], int[]]] { param ($x); $x }
) | ConvertTo-Json -Compress
```

Great reference for Linq in Powershell: 
[https://www.red-gate.com/simple-talk/sysadmin/powershell/high-performance-powershell-linq/](url)

**Comment by SeeminglyScience** [comment]
I believe this is an existing problem with generic types that has just been made more common. I don't think I ever filed an issue, but I've hit this quite a few times with delegate types:

```powershell
# Also throws
[Func[int[], int]]
```

Fortunately the work around is really easy for generic *types*, just surround the inner type in more square brackets:

```powershell
[Func[[int[]], int]]
```

Unfortunately, this doesn't work with generic method args:

```powershell
# Throws differently because we don't seem to be checking for brackets around generic args
[Linq.Enumerable]::SelectMany[[int[]], int](
  [int[][]] @((,2), (,4), (,6), (,8)),
  [Func[[int[]], int[]]] { param ($x); $x }
) | ConvertTo-Json -Compress
```

**Comment by vexx32** [comment]
The latter you mention (double-bracketing) I think was at least semi-intentional, since `$a.[[int[]]]` is potentially valid array-access syntax. In fact I think @daxian-dbw did a patch after the initial PR to ensure weird stuff like that worked.

The initial issue here seems to be... hm. Not a parsing error directly perhaps, but definitely something strange.

This code path parser-wise at least is very messy due to the overloaded meaning for `[]` being used for both types and for arrays. Not simple to tease out :?

**Comment by MartinGC94** [comment]
> I believe this is an existing problem with generic types that has just been made more common. I don't think I ever filed an issue, but I've hit this quite a few times with delegate types:

Rob has reported it here: https://github.com/PowerShell/PowerShell/issues/9639

**Comment by SeeminglyScience** [comment]
I even already gave it a thumb! Good catch, thanks @MartinGC94!
