### ISSUE TITLE
DateTime Variable Expansion Fails Inside Get-ADComputer Scriptblock Filter on Server 2016

### ISSUE THREAD

**Issue by JamesAugustGreig** [PowerShell/PowerShell#18704]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When executing get-adcomputer on Windows Server 2016 in Powershell 7.3.0 using a [DateTime] variable as a filter, variable expansion fails.

I contact Microsoft, opened a ticket, and troubleshot this issue with the engineer.
He discussed the issue with the powershell developers and the powershell discussion team internally.
They were able to re-produce the issue and recommend I report this bug.

### Expected behavior

```console
Windows Server 2016
Powershell 7.3.0

$Date = (Get-Date).AddDays(-30)
Get-ADComputer -Filter {passwordlastset -gt $Date}

The above commands should yield a list of all computers whose password was last set greater than 30 days ago.
```

### Actual behavior

```console
Windows Server 2016
Powershell 7.3.0

$Date = (Get-Date).AddDays(-30)
Get-ADComputer -Filter {passwordlastset -gt $Date}

The above conditions result in an error stating:
"Get-ADComputer: Variable: 'date' found in expression: $date is not defined."
```

### Error details

```console
PS C:\> $Date = (Get-Date).AddDays(-30)
>> Get-ADComputer -Filter {passwordlastset -gt $Date}
Get-ADComputer: Variable: 'Date' found in expression: $Date is not defined.
PS C:\>
PS C:\>
PS C:\>
PS C:\>
PS C:\> get-error

OriginInfo            : localhost
Exception             :
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.ArgumentException: Variable: 'Date' found in expression: $Date is not defined.
                                     at Microsoft.ActiveDirectory.Management.VariableExpressionConverter.GetVariableExpressionValue(String variableExpression)
                                     at Microsoft.ActiveDirectory.Management.VariableADOPathNode..ctor(String varNameStr, EvaluateVariableDelegate variableConverterDelegate, Boolean encodeAsteriskChar)
                                     at Microsoft.ActiveDirectory.Management.QueryParser.yyparse()
                                     at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                                     at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                                     at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    :
        Exception             :
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.ArgumentException: Variable: 'Date' found in expression: $Date is not defined.
                                             at Microsoft.ActiveDirectory.Management.VariableExpressionConverter.GetVariableExpressionValue(String variableExpression)
                                             at Microsoft.ActiveDirectory.Management.VariableADOPathNode..ctor(String varNameStr, EvaluateVariableDelegate variableConverterDelegate, Boolean encodeAsteriskChar)
                                             at Microsoft.ActiveDirectory.Management.QueryParser.yyparse()
                                             at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                                             at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                                             at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    :
                Exception             :
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.ArgumentException: Variable: 'Date' found in expression: $Date is not defined.
                                                     at Microsoft.ActiveDirectory.Management.VariableExpressionConverter.GetVariableExpressionValue(String variableExpression)
                                                     at Microsoft.ActiveDirectory.Management.VariableADOPathNode..ctor(String varNameStr, EvaluateVariableDelegate variableConverterDelegate, Boolean encodeAsteriskChar)
                                                     at Microsoft.ActiveDirectory.Management.QueryParser.yyparse()
                                                     at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                                                     at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                                                     at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    :
                        Exception             :
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.ArgumentException: Variable: 'Date' found in expression: $Date is not defined.
                                                             at Microsoft.ActiveDirectory.Management.VariableExpressionConverter.GetVariableExpressionValue(String variableExpression)
                                                             at Microsoft.ActiveDirectory.Management.VariableADOPathNode..ctor(String varNameStr, EvaluateVariableDelegate variableConverterDelegate, Boolean encodeAsteriskChar)
                                                             at Microsoft.ActiveDirectory.Management.QueryParser.yyparse()
                                                             at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                                                             at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                                                             at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    :
                                Exception             :
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.ArgumentException: Variable: 'Date' found in expression: $Date is not defined.
                                                                     at Microsoft.ActiveDirectory.Management.VariableExpressionConverter.GetVariableExpressionValue(String variableExpression)
                                                                     at Microsoft.ActiveDirectory.Management.VariableADOPathNode..ctor(String varNameStr, EvaluateVariableDelegate variableConverterDelegate, Boolean encodeAsteriskChar)
                                                                     at Microsoft.ActiveDirectory.Management.QueryParser.yyparse()
                                                                     at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                                                                     at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                                                                     at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : Variable: 'Date' found in expression: $Date is not defined.
                                    HResult                        : -2146233087
                                CategoryInfo          : InvalidArgument: (:) [Get-ADComputer], ArgumentException
                                FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
                            Message                        : Variable: 'Date' found in expression: $Date is not defined.
                            HResult                        : -2146233087
                        CategoryInfo          : InvalidArgument: (:) [Get-ADComputer], ArgumentException
                        FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
                    Message                        : Variable: 'Date' found in expression: $Date is not defined.
                    HResult                        : -2146233087
                CategoryInfo          : InvalidArgument: (:) [Get-ADComputer], ArgumentException
                FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
            Message                        : Variable: 'Date' found in expression: $Date is not defined.
            HResult                        : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Get-ADComputer], ArgumentException
        FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer
    Message                        : Variable: 'Date' found in expression: $Date is not defined.
    HResult                        : -2146233087
CategoryInfo          : InvalidArgument: (:) [Get-ADComputer], ArgumentException
FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.ArgumentException,Microsoft.ActiveDirectory.Management.Commands.GetADComputer

PS C:\>
```

### Environment data

```powershell
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\>
```

### Visuals

![VariableExpansionFailure](https://user-images.githubusercontent.com/119624726/205142384-f384473a-b3b3-45be-91e8-f77b325c3c69.jpg)

**Comment by jborean93** [comment]
The problem here stems from running the AD module on Server 2016 which at that time did not support dotnet core and ran in implicit remoting mode. Implicit remoting mode was a feature in pwsh 6+ where it loaded incompatible modules in a separate WinPS (5.1) process and serialized the input/parameters to that process and returned the serialized output. To the user it looked like it ran in the process but rather it ran in another process.

Because of this implicit remoting mode, any session state in the local process will not exist in the remote process, in this case it cannot see the `$date` variable. You'll find the same problem will happen even for other types and not just `DateTime`.

There are 3 things you can do here

* Simplest option is to upgrade to Server 2019 or newer

The AD module in those versions have been updated to run natively in pwsh 6+. This means you don't have this implicit remoting session and things just run as you expect. It will also allow you to pipe data between the AD cmdlets.

* Avoid using `-Filter` and send a preformatted string for `-LDAPFilter`

An example of this is

```powershell
$date = (Get-Date).AddDays(-30)
Get-ADComputer -LDAPFilter ('(pwdLastSet<={0})' -f $date.ToFileTimeUtc())
```

_Note: I'm not 100% sure this is the same but I believe it is. It should return all objects where the pwdLastSet has a date older than the one passed on_

This works because the string contains the already processed filter value to use and the remote PSSession won't have to lookup the `$date` variable.

* Define `$date` in the implicit remoting session

```powershell
$s = New-PSSession -UseWindowsPowerShell
$out = Invoke-Command -Session $s -ScriptBlock {
    $date = (Get-Date).AddDays(-90)
    Get-ADComputer -Filter {passwordlastset -gt $date}
}
$s | Remove-PSSession
```

This essentially runs all the code in the scriptblock in the remote session. As this is running in WinPS (5.1) you can do whatever you want here and just output the data you then want to capture and use in pwsh.

**Comment by JamesAugustGreig** [comment]
Thank you for the explanation Jordan. That all makes sense. I will use one of the work-arounds. Thanks for your help.
