### ISSUE TITLE
Add-AppxPackage doesn't handle string array param DependencyPath in PS7

### ISSUE THREAD

**Issue by MSLukeWest** [PowerShell/PowerShell#18708]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Call [Add-AppxPackage](https://learn.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2022-ps) in PS7, passing in an array of paths for the DependencyPath argument

Required Setup: "c:\Package\Dependencies" contains two msix files, Foo.msix and Bar.msix

$DependencyPackages = @()
$DependencyPackages += Get-ChildItem ("c:\Package\Dependencies\*.msix") | Where-Object { $_.Mode -NotMatch "d" }
Add-AppxPackage -Path "c:\Package\Main.msix" -DependencyPath $DependencyPackages.FullName -ForceApplicationShutdown

### Expected behavior

Add-AppxPackage successfully installs dependencies Foo and Bar.  This is how 5.1 works.

### Actual behavior

It combines the two array items into a single string, resulting in error:

```console
Add-AppxPackage: Cannot find path 'c:\Package\Dependencies\Foo.msix c:\Package\Dependencies\Bar.msix' because it does not exist.
```

### Error details

OriginInfo            : localhost
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                     at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
                                     at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                     at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                     at System.Management.Automation.PSCmdlet.GetResolvedProviderPathFromPSPath(String path, ProviderInfo& provider)
                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ResolveArgumentPath(String path)
                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.EvaluateParameters()
                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ProcessRecord()
                                     at System.Management.Automation.CommandProcessor.ProcessRecord()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                             at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
                                             at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                             at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                             at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
                                             at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                             at System.Management.Automation.PSCmdlet.GetResolvedProviderPathFromPSPath(String path, ProviderInfo& provider)
                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ResolveArgumentPath(String path)
                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.EvaluateParameters()
                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ProcessRecord()
                                             at System.Management.Automation.CommandProcessor.ProcessRecord()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                                     at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
                                                     at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                                     at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                     at System.Management.Automation.PSCmdlet.GetResolvedProviderPathFromPSPath(String path, ProviderInfo& provider)
                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ResolveArgumentPath(String path)
                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.EvaluateParameters()
                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ProcessRecord()
                                                     at System.Management.Automation.CommandProcessor.ProcessRecord()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                                             at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
                                                             at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                                             at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                                             at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                             at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                             at System.Management.Automation.PSCmdlet.GetResolvedProviderPathFromPSPath(String path, ProviderInfo& provider)
                                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ResolveArgumentPath(String path)
                                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.EvaluateParameters()
                                                             at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ProcessRecord()
                                                             at System.Management.Automation.CommandProcessor.ProcessRecord()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                                                     at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
                                                                     at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                                                     at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                                     at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                                                     at System.Management.Automation.PSCmdlet.GetResolvedProviderPathFromPSPath(String path, ProviderInfo& provider)
                                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ResolveArgumentPath(String path)
                                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.EvaluateParameters()
                                                                     at Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand.ProcessRecord()
                                                                     at System.Management.Automation.CommandProcessor.ProcessRecord()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                                    HResult                        : -2146233087
                                TargetObject          : C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
                                CategoryInfo          : ObjectNotFound: (C:\Users\lukewest\D…Libs.x64.14.00.appx:String) [Add-AppxPackage], ItemNotFoundException
                                FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
                            Message                        : Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                            HResult                        : -2146233087
                        TargetObject          : C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
                        CategoryInfo          : ObjectNotFound: (C:\Users\lukewest\D…Libs.x64.14.00.appx:String) [Add-AppxPackage], ItemNotFoundException
                        FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
                    Message                        : Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
                    HResult                        : -2146233087
                TargetObject          : C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
                CategoryInfo          : ObjectNotFound: (C:\Users\lukewest\D…Libs.x64.14.00.appx:String) [Add-AppxPackage], ItemNotFoundException
                FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
            Message                        : Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
            HResult                        : -2146233087
        TargetObject          : C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
        CategoryInfo          : ObjectNotFound: (C:\Users\lukewest\D…Libs.x64.14.00.appx:String) [Add-AppxPackage], ItemNotFoundException
        FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
    Message                        : Cannot find path 'C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx' because it does not exist.
    HResult                        : -2146233087
TargetObject          : C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx C:\Users\lukewest\Desktop\1667099_Repro\Uwp\App8_1.0.0.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
CategoryInfo          : ObjectNotFound: (C:\Users\lukewest\D…Libs.x64.14.00.appx:String) [Add-AppxPackage], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MSLukeWest** [comment]
This was noticed in the Add-AppDevPackage.ps1 script that gets shipped with Visual Studio, see https://developercommunity.visualstudio.com/t/Installps1-script-fails-to-install-depe/10186233

**Comment by kilasuit** [comment]
@MSLukeWest I think on quick reading and not being able to replicate that you've missed out a vital step out 

Can you try this and see if that works instead

```powershell
$DependencyPackages = @()
$DependencyPackages += "c:\Package\Dependencies\Foo.msix"
$DependencyPackages += "c:\Package\Dependencies\Bar.msix"
$DependencyPackages = Get-item $DependencyPackages
Add-AppxPackage -Path "c:\Package\Main.msix" -DependencyPath $DependencyPackages.FullName -ForceApplicationShutdown
```

**Comment by MSLukeWest** [comment]
@kilasuit Thanks for taking a look.  I realized that in trying to simplify the repro steps I made a mistake, which has now been corrected under "Steps To Reproduce".  Can you take another look?

**Comment by MSLukeWest** [comment]
@kilasuit Can you take a look at my updated repro steps above?

**Comment by asklar** [comment]
@kilasuit is there something that the Add-AppxPackage can do to work around this issue? the script works fine in Windows PowerShell, but it is failing in pwsh core. This is causing app installs to fail when initiated from pwsh, so it's a pretty high priority for us.

**Comment by asklar** [comment]
CC @SteveL-MSFT could you please help unblock us? 🙏

**Comment by SteveL-MSFT** [comment]
The problem appears to be that the PS remoting generated proxy function incorrectly has the `-DependencyPath` parameter as a string instead of an array.  So when PowerShell sees that it's just a string, it converts the array to a single space separate string and fails.  Here's a simpler repro:

```powershell
1 > 1.msix
2 > 2.msix
main > main.msix
$deps = gci ?.msix
$main = gci main.msix
add-appxpackage -path $main.fullname -dependencypath $deps.fullname
```

On Windows 11, the AppX module has been fixed to work directly in PS7, so remoting isn't used and the original command will work.  Given that PS remoting is generating the proxy function and getting the signature wrong, I don't have a workaround for now for older Win 10 that still relies on PS remoting to Windows PowerShell to use AppX module.

**Comment by asklar** [comment]
thanks @SteveL-MSFT - note that I'm hitting this on the latest internal Windows 11 builds, so even there it's not working as expected

**Comment by SteveL-MSFT** [comment]
@asklar sorry, just checked my Win 11 system and the AppX module still reports itself as not PS7 compatible, so a WinPS session is created and remoting has this problem.

**Comment by SteveL-MSFT** [comment]
I debugged this and the problem is this [helper function](https://github.com/PowerShell/PowerShell/blob/b195088c5a7af53ca61aa246c1a48628d32df48d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs#L1266-L1277) which only handles `SwitchParameter` so then any other type becomes an `object` (even if it is an array).  So then at parameter binding time, the array you pass gets coerced into a single object (string) which causes it to fail.  In fact, any parameter that expects an array will fail over implicit remoting.

@PaulHigin do you know if this design is intended?  I see there's another [help to check type safety](https://github.com/PowerShell/PowerShell/blob/b195088c5a7af53ca61aa246c1a48628d32df48d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs#L1135-L1170), but by the time that code is reached, it's either a switchparameter or object.

**Comment by asklar** [comment]
@PaulHigin any updates? we're currently blocked by this.

**Comment by ACGNnsj** [comment]
Same problem when running install scripts generated by VS.

**Comment by kuwana77499981** [comment]
Any updates? Can we see this as a bug that should be fixed in powershell that the receiving parameters are not the same type as documented?

Compared to the ```Copy-Item```, we have ```String[]``` for ```-Path```, but ```-DependencyPath```, etc. in ```Add-AppxPackage``` are ```System.Object``` when we see the command using ```Show-Command```.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-5.1
![image](https://github.com/PowerShell/PowerShell/assets/23856257/add946e4-e6f3-4de8-b7fa-db71d85f2246)

https://learn.microsoft.com/es-es/powershell/module/appx/add-appxpackage?view=winserver2012-ps
![image](https://github.com/PowerShell/PowerShell/assets/23856257/6128946a-82c4-43ea-91f1-94d96286053a)

Thank you!

**Comment by daxian-dbw** [comment]
The Appx module has been fixed to work with PowerShell 7.4+ in latest Windows Upgrades. So, now using Appx command doesn't involve loading a proxy module with the Windows Compatible feature, and `-DependencyPath` should support string array just fine.


![Image](https://github.com/user-attachments/assets/69a3d11d-b59e-4f28-b1a4-ff796b3043bd)
