### ISSUE TITLE
Powershell doesn't get proper control after "clifm" exits

### ISSUE THREAD

**Issue by Justaus3r** [PowerShell/PowerShell#18720]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After running a terminal file manager called [clifm](https://github.com/leo-arch/clifm) and quiting it from powershell, powershell just hangs up doing nothing. every other shell works as expected.

Steps to Reproduce:
1: Run clifm from powershell
2: exit

### Expected behavior

```console
powershell should work normally afterwards.
```

### Actual behavior

```console
in version ``7.2.3`` it dumps following stacktrace:

^[[11;1RProcess terminated. Input/output error
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.IO.IOException: Input/output error
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.ConsolePal.GetCursorPosition()
   at System.Console.get_CursorLeft()
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
Warning: Program '/usr/bin/pwsh' crashed.
```
in latest version(7.3.0) it just does nothing(also doesn't accept any keyboard interrupts).
```


### Error details

```console
None
```

### Environment data

```powershell
[PSVersion, 7.3.0] [PSEdition, Core] [GitCommitId, 7.3.0] [OS, Linux 5.18.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Jun 2022 16:14:10 +0000] [Platform, Unix] [PSCompatibleVersions, System.Version[]] [PSRemotingProtocolVersion, 2.3] [SerializationVersion, 1.1.0.1] [WSManStackVersion, 3.0]
```

**Comment by sdwheeler** [comment]
We need a repo using current versions.

**Comment by JamesWTruher** [comment]
I believe this to be related to dotnet problem: https://github.com/dotnet/runtime/issues/59059

**Comment by theJasonHelmick** [comment]
Thank you for this issue -- the Interactive WG agrees this is a .NET issue.
