### ISSUE TITLE
Add-Type -AssemblyName Microsoft.Web.Administration does not work in PowerShell 7.3, but used to work in PowerShell 7.2

### ISSUE THREAD

**Issue by VladimirKhvostov** [PowerShell/PowerShell#18749]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello,
the following stopped working in the PowerShell 7.3:
```PowerShell
Add-Type -AssemblyName 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```
To workaround the issue, we had to replace line above with:
```PowerShell
$assembly = [System.Reflection.Assembly]::LoadFrom('C:\WINDOWS\assembly\GAC_MSIL\Microsoft.Web.Administration\7.0.0.0__31bf3856ad364e35\Microsoft.Web.Administration.dll')
```
Notice that Microsoft.Web.Administration.dll is installed in .NET 2.x GAC.

### Expected behavior

```console
Add-Type -AssemblyName 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
should load C:\WINDOWS\assembly\GAC_MSIL\Microsoft.Web.Administration\7.0.0.0__31bf3856ad364e35\Microsoft.Web.Administration.dll
```

### Actual behavior

```console
Add-Type -AssemblyName 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Add-Type: Cannot find path 'C:\Microsoft.Web.Administration.dll' because it does not exist.
```

### Error details

```console
Exception             :
    Type                 : System.Management.Automation.ItemNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find path 'C:\Microsoft.Web.Administration.dll' because it does not exist.
            HResult : -2146233087
        TargetObject          : C:\Microsoft.Web.Administration.dll
        CategoryInfo          : ObjectNotFound: (C:\Microsoft.Web.Administration.dll:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PathNotFound
    ItemName             : C:\Microsoft.Web.Administration.dll
    SessionStateCategory : Drive
    TargetSite           :
        Name          : ExpandMshGlobPath
        DeclaringType : System.Management.Automation.LocationGlobber, System.Management.Automation, Version=7.3.0.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find path 'C:\Microsoft.Web.Administration.dll' because it does not exist.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive,
ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean
allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths,
CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths,
CmdletProvider& providerInstance)
   at System.Management.Automation.PathIntrinsics.GetResolvedPSPathFromPSPath(String path)
   at Microsoft.PowerShell.Commands.AddTypeCommand.ResolveAssemblyName(String assembly, Boolean isForReferenceAssembly)
   at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblies(IEnumerable`1 assemblies)
   at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          : C:\Microsoft.Web.Administration.dll
CategoryInfo          : ObjectNotFound: (C:\Microsoft.Web.Administration.dll:String) [Add-Type], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.AddTypeCommand
InvocationInfo        :
    MyCommand        : Add-Type
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : Add-Type -AssemblyName 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'
    PositionMessage  : At line:1 char:1
                       + Add-Type -AssemblyName 'Microsoft.Web.Administration, Version=7.0.0.0 …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Add-Type
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

N/A

**Comment by daxian-dbw** [comment]
It fails for me in PowerShell 7.2.9:

![image](https://user-images.githubusercontent.com/127450/217394803-eed2eb45-3e6d-4567-bb1d-6665dc04ba89.png)

@VladimirKhvostov, which specific 7.2 version did you use and found it worked?

It's .NET Framework 2.x legacy assembly, and there is no guarantee that the .NET Framework 2.x assemblies will work with .NET. So, it's by design that PowerShell doesn't search in the `C:\WINDOWS\assembly` folder for GAC assemblies.
