### ISSUE TITLE
pscustomobject comes back with null You cannot call a method on a null-valued expression on powershell 7.3.1

### ISSUE THREAD

**Issue by seanatcsaa** [PowerShell/PowerShell#18860]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
param ([Parameter(
    Mandatory=$true,
    ValueFromPipeline=$true)]
    [string[]]$urls
    )
foreach ($url in $urls){
  $req = [Net.HttpWebRequest]::Create($url)
#$req.GetResponse() | Out-Null 
  $output = [PSCustomObject]@{
      URL = $url
     'Cert Start Date' = $req.ServicePoint.Certificate.GetEffectiveDateString()
     'Cert End Date' = $req.ServicePoint.Certificate.GetExpirationDateString()
      }#endCustomobject.
  $output | sort URL
}#endForeach
```

when I ran this interactive session it works or when I dot source it on powershell 5.1 it works as expected.

However this errors out when I dot source it with in 7.3.1. with message
You cannot call a method on a null-valued expression that is specifcally calling on the $output PScustomobject.

OS is WIn10 enterprise 20J2
build 19042.1466.

### Expected behavior

```console
$output pscutomboject will list url and respective dates as it does in Powershell 5.1.

Output example

URL                    Cert Start Date       Cert End Date       
---                    ---------------       -------------       
https://www.google.com 11/28/2022 1:19:01 AM 2/20/2023 1:19:00 AM
```

### Actual behavior

```console
|  $output = [PSCustomObject]@{
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : You cannot call a method on a null-valued expression.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvokeMethodOnNull
        InvocationInfo        :
            ScriptLineNumber : 9
            OffsetInLine     : 1
            HistoryId        : -1
            ScriptName       : C:\scripts\get-certExpirev2.ps1
            Line             : $output = [PSCustomObject]@{

            PositionMessage  : At C:\scripts\get-certExpirev2.ps1:9 char:1
                               + $output = [PSCustomObject]@{
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\scripts
            PSCommandPath    : C:\scripts\get-certExpirev2.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\scripts\get-certExpirev2.ps1: line 9
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure,
System.Runtime.CompilerServices.CallSite, System.Object)
    Message     : You cannot call a method on a null-valued expression.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : InvokeMethodOnNull
InvocationInfo        :
    ScriptLineNumber : 9
    OffsetInLine     : 1
    HistoryId        : -1
    ScriptName       : C:\scripts\get-certExpirev2.ps1
    Line             : $output = [PSCustomObject]@{

    PositionMessage  : At C:\scripts\get-certExpirev2.ps1:9 char:1
                       + $output = [PSCustomObject]@{
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\scripts
    PSCommandPath    : C:\scripts\get-certExpirev2.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\scripts\get-certExpirev2.ps1: line 9
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

```
param ([Parameter(
    Mandatory=$true,
    ValueFromPipeline=$true)]
    [string[]]$url
    )

$req = [Net.HttpWebRequest]::Create($url)
#$req.GetResponse() | Out-Null 
$output = [PSCustomObject]@{
    URL = $url
   'Cert Start Date' = $req.ServicePoint.Certificate.GetEffectiveDateString()
   'Cert End Date' = $req.ServicePoint.Certificate.GetExpirationDateString()
}
$output
```

**Comment by jhoneill** [comment]
There was a change between .NET framework (Windows PowerShell up to 5) and .NET Core (PowerShell 6 onwards).  
$req.ServicePoint.Certificate is now null . 

I have not found code that works for both, so I have two scripts to check certs one for PS 5 and for PS7   The PS7 one has this 
```
# I get the host name and port from the URL (or assume port 443 if there is no port) 
             $tcpClient = $stream  = $sslstream = $certificate  = $null
            try {
                #We will get an error if the server resolves but is off-line - catch it - we will close whatever was opened and output whatever info we have
                $tcpclient     = [Sockets.TcpClient]::new($hostName,$port)
                $Stream        = $tcpclient.GetStream()
                $sslstream     = [Security.SslStream]::new($Stream, $false, {$true})
                $sslstream.AuthenticateAsClient($hostname)
                $certificate   = $sslstream.RemoteCertificate
            }
            catch {}
            if ($sslstream)        {$sslstream.close() }
	    if ($stream)           {$stream.close()    }
            if ($tcpClient)        {$tcpClient.close() }
```

It's annoying, but it's not a PowerShell thing, and .NET is unlikely to change back to the old behaviour.

**Comment by JAK1047** [comment]
If you're just looking to get the cert creation and expiration here's a function I wrote that works in both PoSH 7 and 5.1.

```powershell
  function Get-CertExpiration {
    [cmdletbinding()]
    Param (
      [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
      [Alias('IP')]
      [string[]]$URL,
      [int]$Port = 443
    )
      
    Try {
      $TCPClient = New-Object -TypeName System.Net.Sockets.TCPClient
  
      $TcpSocket = New-Object -TypeName Net.Sockets.TcpClient -ArgumentList ($URL, $Port)
      $tcpstream = $TcpSocket.GetStream()
      $Callback = { param($sender, $Cert, $chain, $errors) return $true }
      $SSLStream = New-Object -TypeName System.Net.Security.SSLStream -ArgumentList @($tcpstream, $true, $Callback)
      $SSLStream.AuthenticateAsClient($URL, $null, 'tls12', $false)
      $Certificate = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList ($SSLStream.RemoteCertificate)
    }
    Catch {
      $TCPClient = New-Object -TypeName System.Net.Sockets.TCPClient
  
      $TcpSocket = New-Object -TypeName Net.Sockets.TcpClient -ArgumentList ($URL, $Port)
      $tcpstream = $TcpSocket.GetStream()
      $Callback = { param($sender, $Cert, $chain, $errors) return $true }
      $SSLStream = New-Object -TypeName System.Net.Security.SSLStream -ArgumentList @($tcpstream, $true, $Callback)
      $SSLStream.AuthenticateAsClient($URL, $null, 'tls', $false)
      $Certificate = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList ($SSLStream.RemoteCertificate)
    }
    Finally {
      $SSLStream.Dispose()
      $TCPClient.Dispose()
    }
    
    Return $Certificate
  }
```

![image](https://user-images.githubusercontent.com/29665481/209862402-96390d70-554b-441b-9a4b-8b7316c7bb06.png)

**Comment by mklement0** [comment]
Some backstory:

* https://github.com/dotnet/runtime/issues/29301
