### ISSUE TITLE
Linux: PlatformNotSupportedException on Open() for RunspacePool

### ISSUE THREAD

**Issue by christophwille** [PowerShell/PowerShell#18934]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Sample project: https://github.com/christophwille/pscore-playground/tree/master/ExO3onNet6LocalModule/ExO3onNet7Containerized

Line in question that throws: https://github.com/christophwille/pscore-playground/blob/6b19d6eadc69629c34242399d2bfdddf64d1a364/ExO3onNet6LocalModule/ExO3PsLib/ExchangeOnlinePowerShellFactory.cs#L99

Exact error message: 

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=System.Management.Automation
```

The code works on Windows with .NET 6 & 7 (PS 7.2 and 7.3 respectively) as well locally as in a container. However, on Linux it throws. Are RunspacePools not supported in Linux, or is it something in my InitialSessionState that is not supported on Linux?

https://github.com/christophwille/pscore-playground/blob/6b19d6eadc69629c34242399d2bfdddf64d1a364/ExO3onNet6LocalModule/ExO3PsLib/ExchangeOnlinePowerShellFactory.cs#L20

The error message doesn't give a hint as to what exactly is not supported.

### Expected behavior

```console
Linux behavior == Windows behavior
```

### Actual behavior

```console
Exception
```

### Error details

```console
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.Internal.SecuritySupport.SetExecutionPolicy(ExecutionPolicyScope scope, ExecutionPolicy policy, String shellId)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
   at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, InitialSessionState iss)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.Open()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.CreateRunspace()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.OpenHelper()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.CoreOpen(Boolean isAsync, AsyncCallback callback, Object asyncState)
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at ExO3PsLib.ExchangeOnlinePowerShellFactory.ConnectViaPool(String appId, String organization, X509Certificate2 certificate, String modulePath) in D:\GitWorkspace\pscore-playground\ExO3onNet6LocalModule\ExO3PsLib\ExchangeOnlinePowerShellFactory.cs:line 99

  This exception was originally thrown at this call stack:
    [External Code]
    ExO3PsLib.ExchangeOnlinePowerShellFactory.ConnectViaPool(string, string, System.Security.Cryptography.X509Certificates.X509Certificate2, string) in ExchangeOnlinePowerShellFactory.cs
```

### Environment data

```powershell
7.3
```

**Comment by 237dmitry** [comment]
This example seems to work:
```powershell
$Scriptblock = {
    param($Name)
    New-Item -Path /tmp -Name $Name -ItemType File
}

$MaxThreads = 5
$RunspacePool = [runspacefactory]::CreateRunspacePool(1, $MaxThreads)
$RunspacePool.Open()
$Jobs = @()

1..9 | Foreach-Object {
    $PowerShell = [powershell]::Create()
    $PowerShell.RunspacePool = $RunspacePool
    [void] $PowerShell.AddScript($ScriptBlock).AddArgument($_)
    $Jobs += $PowerShell.BeginInvoke()
}

while ($Jobs.IsCompleted -contains $false) {
    Start-Sleep 1
}
```

**Comment by christophwille** [comment]
My hunch re: CreateInitialSessionState was correct:

`iss.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Unrestricted;`

That is the culprit for PlatformNotSupportedException. Everything else - local loading of the module, running a startup script - work.

Is there a specific reason that (a) the exception is so terse and unhelpful, (b) does that really have to be an exception?

**Comment by iSazonov** [comment]
We could annotate InitialSessionStateEntry.ExecutionPolicy with [SupportedOSPlatformAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute)
And that's not the only place it could be useful.

**Comment by christophwille** [comment]
I fixed it this way: https://github.com/christophwille/pscore-playground/commit/1565b3715aca7a42dbfd375e03a6a72a7157b0de#diff-dcdbe6c7176e6088252af06b0ed05bc4cdf15d5b17019636ebf5328a319791cc

```
            // See https://github.com/PowerShell/PowerShell/issues/18934 (will crash Linux with an exception)
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                // If not done on Windows: ".. cannot be loaded because running scripts is disabled on this system"
                iss.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Unrestricted;
            }
```

Note that my case is especially bad - ExecutionPolicy is required on Windows for my scenario.
