### ISSUE TITLE
`bash -ic` and `zsh -ic` commands crashes PowerShell on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 
* The problem affects Unix-like platforms and WSL (possibly other Unix-emulation environments).
* Combining `-i` (interactive shell) with `-c` (unattended command execution) isn't common, but does happen if you explicitly want to load `~/.bashrc` first, for instance. 
* The problem seems to affect all of the major POSIX-compatible shells (`bash`, `dash`, `ksh`, `zsh`)

```powershell
bash -ic date
```

### Expected behavior

```console
Today's date should print, and control should return to PowerShell.
```

### Actual behavior

```console
* If PowerShell itself is running as the terminal's shell: crashes
* If you start a terminal with, say, `bash` first, the enter a PowerShell session and submit the command, the `date` output prints and control is returned to `bash`, with the PowerShell session having become a stopped (suspended) Bash background job.
```

### Environment data

```powershell
PowerShell Core 7.3.2
PowerShell Core 7.4.0-preview.1
on Unix-like platforms / WSL
```

**Comment by kasini3000** [comment]
The problem can be reproduced and the pwsh process exits. 
In alma linux 8.6+ps 7.3.2, 
in openeuler22.03+ps7.4-pr1

I seem to remember that pwsh does not support any -i parameter. 
eg: docker run -it

**Comment by JamesWTruher** [comment]
it seems to be specific to certain commands (and their position???) - this works just fine:
`bash -ic 'date;pwd'`
but
`bash -ic 'date'` 
has a problem. It looks like a builtin run as the last command will not display the problem.

I've used `docker run -it ubuntu:latest` successfully too many times to count (on mac), so I'm not so sure about what you've seen @kasini3000 - although I definitely am aware of issues with _some_ interactive apps

**Comment by JamesWTruher** [comment]
I was able to capture a stack trace and it reminds me of an outstanding dotnet issue where the cursor position cannot be reported, which causes lots of grief.
```
[Error - 11:44:56 AM] Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost: An error occurred while running the REPL loop - System.IO.IOException: Input/output error
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.ConsolePal.GetCursorPosition()
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Console.PsrlReadLine.InvokePSReadLine(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Console\PsrlReadLine.cs:line 48
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousDelegateTask`1.Run(CancellationToken cancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousDelegateTask.cs:line 63
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousTask`1.ExecuteSynchronously(CancellationToken executorCancellationToken) in D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousTask.cs:line 103
   ```

**Comment by mklement0** [comment]
Re workaround: `bash -ic 'date;:'`  works too; `:` is the no-op built-in; however, like `P=0` it resets the exit code; if that is a concern, use  `bash -ic 'date; exit $?'`

**Comment by JamesWTruher** [comment]
additionally, i think this might serve
`bash -ic 'exec date'`
I'm growing more suspicious of the fork/exec child/parent process handling in dotnet. In this example, the child/parent process relationship is altered

**Comment by mklement0** [comment]
Interestingly, involving a _redirection_ also makes the problem go away (and using a Bash redirection, with its raw-byte-conduit behavior, is a good reason to shell out to `bash`, though not necessarily with `-i`):

```powershell
# Does NOT crash.
# The 3>/dev.null is a dummy redirection here.
bash -ic 'date 3>/dev/null'
```
