### ISSUE TITLE
Unable to get hostname from `[System.Net.DNS]::GetHostByName('')` after changing hostname with `hostnamectl hostname <hostname>`.

### ISSUE THREAD

**Issue by rokejulianlockhart** [PowerShell/PowerShell#19137]
Prerequisites
--

- [X] Write a descriptive title.
- [ ] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

**The headings have been chronologically numbered and ordered.**

1. Expected behavior
   --
   ```powershell
   rokejulianlockhart@localhost:~> pwsh-preview
   PowerShell 7.4.0-preview.1
   PS /home/rokejulianlockhart> [System.Net.DNS]::GetHostByName('')

   HostName              Aliases AddressList
   --------              ------- -----------
   localhost.localdomain {}      {127.0.0.1, 192.168.0.132, fd60:b525:84eb:0:17dc:c4a7:874b:a81a, fd60:b525:84eb:0:f22f:74ff:fe23:55ef…}

   PS /home/rokejulianlockhart> hostnamectl status                                                                                        
   Static hostname: (unset)                            
   Transient hostname: localhost           
       CPE OS Name: cpe:/o:opensuse:tumbleweed:20230209
               Kernel: Linux 6.1.10-1-default
   PS /home/rokejulianlockhart>
   ```

2. Steps to reproduce
   --

   ```bash
   rokejulianlockhart@localhost:~> hostnamectl hostname
   localhost
   rokejulianlockhart@localhost:~> hostnamectl hostname --pretty

   rokejulianlockhart@localhost:~> hostnamectl hostname --static

   rokejulianlockhart@localhost:~> hostnamectl hostname --transient
   localhost
   rokejulianlockhart@localhost:~> hostnamectl hostname beedell.rokejulianlockhart.1676161096
   rokejulianlockhart@localhost:~> hostnamectl hostname
   beedell.rokejulianlockhart.1676161096
   rokejulianlockhart@localhost:~> hostnamectl hostname --pretty

   rokejulianlockhart@localhost:~> hostnamectl hostname --static
   beedell.rokejulianlockhart.1676161096
   rokejulianlockhart@localhost:~> hostnamectl hostname --transient
   beedell.rokejulianlockhart.1676161096
   rokejulianlockhart@localhost:~> hostnamectl hostname --pretty
   ```

3. Actual behavior
   --

   ```powershell
   PS /home/rokejulianlockhart> [System.Net.DNS]::GetHostByName('').HostName                                                                                 
   MethodInvocationException: Exception calling "GetHostByName" with "1" argument(s): "Name or service not known"
   ```

4. Error details
   --

   ```powershell
   PS /home/rokejulianlockhart> Get-Error                                                                                                                                      

   Exception             : 
       Type           : System.Management.Automation.MethodInvocationException
       ErrorRecord    : 
           Exception             : 
               Type    : System.Management.Automation.ParentContainsErrorRecordException
               Message : Exception calling "GetHostByName" with "1" argument(s): "Name or service not known"
               HResult : -2146233087
           CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
           FullyQualifiedErrorId : SocketException
           InvocationInfo        : 
               ScriptLineNumber : 1
               OffsetInLine     : 1
               HistoryId        : -1
               Line             : [System.Net.DNS]::GetHostByName('').HostName
               PositionMessage  : At line:1 char:1
                               + [System.Net.DNS]::GetHostByName('').HostName
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               CommandOrigin    : Internal
           ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
       TargetSite     : 
           Name          : ConvertToMethodInvocationException
           DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.4.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35
           MemberType    : Method
           Module        : System.Management.Automation.dll
       Message        : Exception calling "GetHostByName" with "1" argument(s): "Name or service not known"
       Data           : System.Collections.ListDictionaryInternal
       InnerException : 
           Type            : System.Net.Sockets.SocketException
           Message         : Name or service not known
           SocketErrorCode : HostNotFound
           ErrorCode       : -131073
           NativeErrorCode : -131073
           TargetSite      : 
               Name          : GetHostEntryOrAddressesCore
               DeclaringType : System.Net.Dns
               MemberType    : Method
               Module        : System.Net.NameResolution.dll
           Source          : System.Net.NameResolution
           HResult         : 5
           StackTrace      : 
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
   at System.Net.Dns.GetHostByName(String hostName)
   at CallSite.Target(Closure, CallSite, Type, String)
       Source         : System.Management.Automation
       HResult        : -2146233087
       StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure, CallSite, Type, String)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
   FullyQualifiedErrorId : SocketException
   InvocationInfo        : 
       ScriptLineNumber : 1
       OffsetInLine     : 1
       HistoryId        : -1
       Line             : [System.Net.DNS]::GetHostByName('').HostName
       PositionMessage  : At line:1 char:1
                       + [System.Net.DNS]::GetHostByName('').HostName
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       CommandOrigin    : Internal
   ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

   PS /home/rokejulianlockhart>
   ```

Environment data
--

```powershell
PS /home/rokejulianlockhart> $PSVersionTable 

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Linux 6.1.10-1-default #1 SMP PREEMPT_DYNAMIC Mon Feb  6 07:27:26 UTC 2023 (2a0570b)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/rokejulianlockhart>
```

Visuals
--

![image](https://user-images.githubusercontent.com/42837531/218287549-f750e789-05a4-4460-806d-e0cd458743e2.png)

**Comment by rhubarb-geek-nz** [comment]
Is this a PowerShell issue or dotnet core? Does a C# program demonstrate the same issue?

**Comment by rhubarb-geek-nz** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.net.dns.gethostbyname?view=net-7.0

```
Caution
GetHostByName has been deprecated. Use GetHostEntry instead.
```

**Comment by rhubarb-geek-nz** [comment]
Does [System.Net.Dns.GetHostName](https://learn.microsoft.com/en-us/dotnet/api/system.net.dns.gethostname?view=net-7.0) work?

**Comment by 237dmitry** [comment]
> Does [System.Net.Dns.GetHostName](https://learn.microsoft.com/en-us/dotnet/api/system.net.dns.gethostname?view=net-7.0) work?

Yes, it does.

**Comment by rhubarb-geek-nz** [comment]
Does your hostname, beedell.rokejulianlockhart.1676161096, actually resolve to an IP address?
Is it in your /etc/hosts file?

**Comment by rhubarb-geek-nz** [comment]
For example, there is no IP address for FQDN "wibble."

```
PS /home/bythesea> [System.Net.DNS]::GetHostByName('wibble.')    
MethodInvocationException: Exception calling "GetHostByName" with "1" argument(s): "Name or service not known"
```

**Comment by 237dmitry** [comment]
> For example, there is no IP address for FQDN "wibble." or "localhost.localdomain."

```
$ [System.Net.Dns]::GetHostByName('localhost.localdomain.')

HostName  Aliases AddressList
--------  ------- -----------
localhost {}      {::1, 127.0.0.1}
```

**Comment by rhubarb-geek-nz** [comment]
On my opensuse system there is no entry in /etc/hosts for localhost.localdomain so I get no result.

```
~> cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	opensuse-leap15.docker.rhubarb.geek.nz opensuse-leap15
```

likewise

```
> ssh localhost.localdomain.
ssh: Could not resolve hostname localhost.localdomain.: Name or service not known
```

**Comment by 237dmitry** [comment]
> On my opensuse system there is no entry in /etc/hosts for localhost.localdomain so I get no result.

![hosts](https://user-images.githubusercontent.com/78153320/218308081-8e44d5bf-f92d-45b0-b7d6-e8805b9159c0.png)

**Comment by rhubarb-geek-nz** [comment]
Original issue was reported on opensuse hence I was replicating on opensuse.

```
CPE OS Name: cpe:/o:opensuse:tumbleweed:20230209
```

**Comment by 237dmitry** [comment]
> Original issue was reported on opensuse hence I was replicating on opensuse.

Differences only in distribution methods

**Comment by jborean93** [comment]
Ultimately this isn't a PowerShell issue but something in dotnet. The command `[System.Net.DNS]::GetHostByName` calls [Dns.GetHostByName](https://learn.microsoft.com/en-us/dotnet/api/system.net.dns.gethostbyname?view=net-7.0) in dotnet and has nothing to do with PowerShell. The docs there do state to use [Dns.GetHostEntry](https://learn.microsoft.com/en-us/dotnet/api/system.net.dns.gethostentry?view=net-7.0) instead though.

**Comment by rokejulianlockhart** [comment]
@jborean93, can you transfer this to the correct DotNet repository, or must I create a new issue there?

**Comment by kilasuit** [comment]
@rokejulianlockhart unfortunately we can't transfer issues to the dotnet repo's, so you'll need to find the right one and raise it there & link it to this issue.

**Comment by rhubarb-geek-nz** [comment]
> > Original issue was reported on opensuse hence I was replicating on opensuse.
> 
> Differences only in distribution methods

Not really. Different distributions can use different versions of the kernel and compile options, different boot loaders and optjons, different system configuration, different init systems, eg classic sys-v init, systemd, or openrc, different versions of each library and compilation options, different networking configuration and defaults, for instance static network configuration or DHCP, manually created /etc/resolv.conf or one generated by DHCP services. Different packaging mechanisms, although systems may use x86_64 and ELF, there is technically no guaranteed binary compatibility between different distributions unless explicitly stated.

**Comment by rhubarb-geek-nz** [comment]
@rokejulianlockhart although we have established we are discussing the behaviour of the dotnet APIs themselves, you haven't shown that they are not working correctly.

What is the hostname of your system as reported by the shell command `hostname`, and then what does `[System.Net.Dns]::GetHostName` return?

Have you confirmed that there is a correct mapping between your current hostname and an IP address using the shell? Eg with

```
$ curl -v http://$(hostname)
```

And confirm the address it connects to. Then demonstrate with `[System.Net.Dns]::GetHostEntry`

**Comment by rokejulianlockhart** [comment]
@rhubarb-geek-nz,

```
rokejulianlockhart@beedell:~> script -a
Script started, output log file is 'typescript'.
rokejulianlockhart@beedell:~> pwsh-preview 
PowerShell 7.4.0-preview.1
PS /home/rokejulianlockhart> [System.Net.Dns]::GetHostName

OverloadDefinitions
-------------------
static string GetHostName()


PS /home/rokejulianlockhart> curl -v http://$(hostname)
* Could not resolve host: beedell.rokejulianlockhart.1676161096
* Closing connection 0
curl: (6) Could not resolve host: beedell.rokejulianlockhart.1676161096
NativeCommandExitException: Program "curl" ended with non-zero exit code: 6.
PS /home/rokejulianlockhart> [System.Net.DNS]::GetHostByName('')
MethodInvocationException: Exception calling "GetHostByName" with "1" argument(s): "Name or service not known"
PS /home/rokejulianlockhart>
```

Is my network configuration perhaps the problem? It might explain

```
PS /home/rokejulianlockhart> ssh localhost                                                                                                                
(rokejulianlockhart@localhost) Password: 
client_loop: send disconnect: Broken pipe
NativeCommandExitException: Program "ssh" ended with non-zero exit code: 255.
PS /home/rokejulianlockhart>
```

which is another problem I'm having.

**Comment by rhubarb-geek-nz** [comment]
To execute a c# method you need the round brackets

```
% pwsh
PowerShell 7.3.2
PS > [System.Net.Dns]::GetHostName()
hamburg.local
PS > hostname
hamburg.local
```

If you have set your hostname but can't resolve the address either you need a DNS entry or else an entry in the /etc/hosts file to map the name to IP address

**Comment by rokejulianlockhart** [comment]
@rhubarb-geek-nz:

```
PS /home/rokejulianlockhart> [System.Net.Dns]::GetHostName()    
beedell.rokejulianlockhart.1676161096
```

**Comment by rhubarb-geek-nz** [comment]
That is good, in that it looks like a network configuration problem with your machine rather than a problem with either dotnet or powershell.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/19137#issuecomment-1433866822

@rhubarb-geek-nz, can you re-close this as invalid, instead of "completed"?
