### ISSUE TITLE
ForEach-Object -Parallel {...} -TimeoutSeconds - Exception returned when timeout reached is generic. Consider changing to use System.TimeoutException

### ISSUE THREAD

**Issue by chadbaldwin** [PowerShell/PowerShell#19255]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using `-TimeoutSeconds` with the `-Parallel` parameter on `ForEach-Object`, if the timeout is exceeded then the error returned is a generic error (`System.Management.Automation.ActionPreferenceStopException`).

This makes it so that I am unable to write a try/catch that looks for a timeout exception.

Instead I would expect it to return `System.TimeoutException` or similar.

Or maybe it could provide the same exception, but have `System.TimeoutException` as an InnerException? This way it doesn't change existing behavior, but provides more information as to why the exception occured?

Sample code provided below.

### Expected behavior

```console
PS> 1..10 | ForEach-Object -Parallel { sleep 6 } -ThrottleLimit 3 -TimeoutSeconds 5
InvalidOperation: The pipeline has been stopped.
```

### Actual behavior

```console
PS> 1..10 | ForEach-Object -Parallel { sleep 6 } -ThrottleLimit 3 -TimeoutSeconds 5
OperationStopped: The operation has timed out.
```

### Error details

```console
System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The pipeline has been stopped.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chadbaldwin** [comment]
Here's the full version of the error that is returned:

```console

Type        : System.Management.Automation.ActionPreferenceStopException
ErrorRecord : 
    Exception             : 
        Type        : System.Management.Automation.PipelineStoppedException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The pipeline has been stopped.
                HResult : -2146233087
            CategoryInfo          : OperationStopped: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : PipelineStopped
        TargetSite  : 
            Name          : Throw
            DeclaringType : System.Runtime.ExceptionServices.ExceptionDispatchInfo
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message     : The pipeline has been stopped.
        Source      : System.Private.CoreLib
        HResult     : -2146233087
        StackTrace  : 
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
    TargetObject          : System.Management.Automation.PSTasks.PSTask
    CategoryInfo          : InvalidOperation: (System.Management.A…tion.PSTasks.PSTask:PSTask) [], PipelineStoppedException
    FullyQualifiedErrorId : PSTaskException
    InvocationInfo        : 
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : -1
        Line             : 1..10 | ForEach-Object -Parallel { sleep 6 } -ThrottleLimit 3 -TimeoutSeconds 5
        PositionMessage  : At line:1 char:1
                           + 1..10 | ForEach-Object -Parallel { sleep 6 } -ThrottleLimit 3 -Timeou …
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CommandOrigin    : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
TargetSite  : 
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.3.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The pipeline has been stopped.
Data        : System.Collections.ListDictionaryInternal
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  : 
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

**Comment by kasini3000** [comment]
Yes, it will not throw exceptions nor write lastexitcode.
Better to enhance “add EverypipeTimeoutSecond to ForEach-Object-Parallel” 
#18027

**Comment by chadbaldwin** [comment]
@kasini3000 it does throw an exception (run my sample code and you'll see), the issue I'm reporting here is that the exception it throws is generic and does not indicate that it is a timeout exception.

And it is specific to the exception thrown due to the `-TimeoutSeconds` parameter triggering.

This is different from the issue that you linked because it occurs at a different scope. That issue you linked is in regard to timeouts at the child parallel pipeline level, not at the parent level.

While I agree that both scopes should return a timeout exception if either reaches its timeout configuration, I think it's best to keep these items separate.

**Comment by chadbaldwin** [comment]
@kasini3000 not all exceptions are terminating exceptions. If you want to catch the exception thrown, you need to set `$ErrorActionPreference = 'Stop'`

**Comment by kasini3000** [comment]
en ,ok.

**Comment by chadbaldwin** [comment]
.

**Comment by chadbaldwin** [comment]
.
