### ISSUE TITLE
JSON truncation errors with Set-MailboxFolderPermission

### ISSUE THREAD

**Issue by wassilywabbit** [PowerShell/PowerShell#19288]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am newly having problems with Set-MailboxFolderPermission, wherein I get JSON truncation errors when I try to adjust calendar visibility using the same command that I have used successfully in the past.

Set-MailboxFolderPermission -Identity khris.clevenger:\calendar -User Default -AccessRights {AvailabilityOnly}

When I launched PowerShell, it threw a notice indicating that version 7.3.2 was available. Before updating, I tried the command, which failed, so I installed the 7.3.2 update (via HomeBrew). When the problem persisted, since I usually get WSMan errors after updates (I did NOT this time), I pre-emptively ran the following update commands:

pwsh -Command 'Install-Module -Name PSWSMan'
sudo pwsh -Command 'Install-WSMan'

There was no change after those updates; the command failed again. 

However, when I launched PowerShell again, it threw a notice indicating that version 7.3.3 was available, so I went through the update process again, but to no avail. The command still fails.

I would note that Get-MailboxFolderPermission & Add-MailboxFolderPermission commands DID execute successfully

### Expected behavior

```console
I expect the command to execute & output the new state of permissions for the calendar
```

### Actual behavior

```console
I consistently get the following errors:

WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 10.
ConvertTo-Json: An item with the same key has already been added. Key: Value

And the output from the following command indicates that no change was made:

Get-MailboxFolderPermission khris.clevenger@ten35.com:\calendar
```

### Error details

```console
Exception             : 
    Type       : System.ArgumentException
    Message    : An item with the same key has already been added. Key: Value
    TargetSite : 
        Name          : ThrowAddingDuplicateWithKeyArgumentException
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147024809
    StackTrace : 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessEnumerable(IEnumerable enumerable, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessCustomObject[T](Object o, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessEnumerable(IEnumerable enumerable, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessDictionary(IDictionary dict, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessDictionary(IDictionary dict, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessDictionary(IDictionary dict, Int32 depth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ProcessValue(Object obj, Int32 currentDepth, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertToJson(Object objectToProcess, ConvertToJsonContext& context)
   at Microsoft.PowerShell.Commands.ConvertToJsonCommand.EndProcessing()
   at System.Management.Automation.Cmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [ConvertTo-Json], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertToJsonCommand
InvocationInfo        : 
    MyCommand        : ConvertTo-Json
    ScriptLineNumber : 1348
    OffsetInLine     : 17
    HistoryId        : 6
    ScriptName       : /var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw/tmpEXO_yxicll12.2bw.psm1
    Line             : $Body = ConvertTo-Json $BodyObj -Depth 10 -Compress
                       
    PositionMessage  : At /var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw/tmpEXO_yxicll12.2bw.psm1:1348 char:17
                       +         $Body = ConvertTo-Json $BodyObj -Depth 10 -Compress
                       +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : /var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw
    PSCommandPath    : /var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw/tmpEXO_yxicll12.2bw.psm1
    InvocationName   : ConvertTo-Json
    CommandOrigin    : Internal
ScriptStackTrace      : at Execute-Command<Process>, 
/var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw/tmpEXO_yxicll12.2bw.psm1: line 1348
                        at script:Set-MailboxFolderPermission<Process>, 
/var/folders/0k/vyzjsckx729c11yr_7l46y4h0000gn/T/tmpEXO_yxicll12.2bw/tmpEXO_yxicll12.2bw.psm1: line 91840
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM6…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Looks like you're using a [cmdlet from ExchangePowerShell module](https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxfolderpermission?view=exchange-ps).  Your error seems to indicate this is a problem within their cmdlet so you'll need to report this to Exchange team.

**Comment by wassilywabbit** [comment]
I'm fairly new to PowerShell, so how am I supposed to report this problem to the Exchange team?
