### ISSUE TITLE
PS command invoke failed with runspace issue

### ISSUE THREAD

**Issue by WD1993** [PowerShell/PowerShell#19327]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Deployed .NET6 self-contained worker service applications, the ps command run failed with:

```
using (System.Management.Automation.PowerShell ps = System.Management.Automation.PowerShell.Create())
            {
                ps.AddCommand("Get-Volume");
                ps.AddParameter("DriveLetter", driveLetter);

                Collection<PSObject> result;
                try
                {
                    result = ps.Invoke();
                    CheckPsErrorStream(ps);
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException(
                        string.Format(CultureInfo.InvariantCulture, ServerConfigurationsManagementMessages.VolumeNotFoundByDriveErrorMessage, driveLetter, e.Message));
                }

                return result.First();
            }
```

### Expected behavior

```console
PS command should be executed
```

### Actual behavior

```console
IaaS Worker exception at: No Volume found with drive letter F. Message:    at System.Management.Automation.Runspaces.PSSnapInHelpers.LoadPSSnapInAssembly(PSSnapInInfo psSnapInInfo)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning)
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Microsoft.SqlServer.Management.ServerConfigurationsManagement.Common.StorageHelper.GetVolumeByDriveLetter(Char driveLetter)
```

### Error details

```console
IaaS Worker exception at: No Volume found with drive letter F. Message:    at System.Management.Automation.Runspaces.PSSnapInHelpers.LoadPSSnapInAssembly(PSSnapInInfo psSnapInInfo)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning)
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at Microsoft.SqlServer.Management.ServerConfigurationsManagement.Common.StorageHelper.GetVolumeByDriveLetter(Char driveLetter)
```

### Environment data

```powershell
NET6, self-contained (not singlefile publish)
```

**Comment by daxian-dbw** [comment]
I suspect you only have the `System.Management.Automation` NuGet package in `PackageReference`. If that's the case, you need to replace it with `Microsoft.PowerShell.SDK`.
