### ISSUE TITLE
PowerShell 7.4.0-preview.2 - ActiveDirectory module - Attempting to perform the InitializeDefaultDrives operation on the 'ActiveDirectory' provider failed.

### ISSUE THREAD

**Issue by RMarkwald** [PowerShell/PowerShell#19336]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Preview 7.4.0-preview.1 was running without issue until I upgraded to preview.2 about 30 minutes ago.  Opening Windows Terminal and PowerShell-Preview windows produce the same error when importing my PS Profile which has a few modules that rely on the ActiveDirectory module.  I can run Import-Module -Name ActiveDirectory and no errors occur.

Opening PowerShell-Preview displays "Attempting to perform the InitializeDefaultDrives operation on the 'ActiveDirectory' provider failed."

Importing the module then running an AD command like Get-ADComputer -Identity 'mycomputer' displays "Get-ADComputer: The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an exception.".  This seems to happen for any AD command I've tried.

### Expected behavior

```console
When opening PowerShell Preview (similar to what 7.3.3 will show):
PowerShell 7.3.3
Loading personal and system profiles took 1512ms.


When running AD commands:
PS C:\Users\myuser> get-adcomputer -identity 'mycomputer'

DistinguishedName : CN=mycomputer,OU=Workstations,DC=domain,DC=com
DNSHostName       : mycomputer.domain.com
Enabled           : True
Name              : mycomputer
ObjectClass       : computer
ObjectGUID        : <guid here>
SamAccountName    : mycomputer$
SID               : <sid here>
UserPrincipalName :
```

### Actual behavior

```console
PowerShell 7.4.0-preview.2
Import-Module: C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:12
Line |
  12 |  Import-Module Disable-CompanyADUser,Get-CompanyADUser,New-CompanyUserCreation,Rem …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempting to perform the InitializeDefaultDrives operation on the 'ActiveDirectory' provider failed.
Loading personal and system profiles took 729ms.

PS C:\Users\rmarkwald> import-Module -Name activedirectory

PS C:\Users\myuser> get-adcomputer -identity 'mycomputer'
Get-ADComputer: The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an exception.

PS C:\Users\myuser> Get-ADDomain
Get-ADDomain: The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an exception.

PS C:\Users\myuser> get-adUser -Identity 'testuser'
Get-ADUser: The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an exception.
```

### Error details

```console
PowerShell 7.4.0-preview.2
Import-Module: C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:12
Line |
  12 |  Import-Module Disable-CompanyADUser,Get-CompanyADUser,New-CompanyUserCreation,Rem …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Attempting to perform the InitializeDefaultDrives operation on the 'ActiveDirectory' provider failed.
Loading personal and system profiles took 877ms.
PS C:\Users\myuser> get-error

Exception             :
    Type           : System.Management.Automation.ProviderInvocationException
    ProviderInfo   : Microsoft.ActiveDirectory.Management\ActiveDirectory
    ErrorRecord    :
        Exception             :
            Type           : System.TypeInitializationException
            TypeName       : System.ServiceModel.Diagnostics.TraceUtility
            TargetSite     :
                Name          : SetEtwProviderId
                DeclaringType : System.ServiceModel.Diagnostics.TraceUtility, System.ServiceModel, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089
                MemberType    : Method
                Module        : System.ServiceModel.dll
            Message        : The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an
exception.
            InnerException :
                Type        : System.Configuration.ConfigurationErrorsException
                Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                Errors      :
                    Type        : System.Configuration.ConfigurationErrorsException
                    Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                    Errors      :
                        Type        : System.Configuration.ConfigurationErrorsException
                        Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created.
The machine.config file is missing information. Verify that this configuration section is properly registered and that
you have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i
to fix this error.
                        Errors      :
                            Type        : System.Configuration.ConfigurationErrorsException
                            Message     : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                            Errors      :
                                Type        : System.Configuration.ConfigurationErrorsException
                                Message     : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                Errors      :
                                    Type        : System.Configuration.ConfigurationErrorsException
                                    Message     : The 'system.serviceModel/diagnostics' configuration section cannot
be created. The machine.config file is missing information. Verify that this configuration section is properly
registered and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                    Errors      : …
                                    BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot
be created. The machine.config file is missing information. Verify that this configuration section is properly
registered and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                    HResult     : -2146232062
                                BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                HResult     : -2146232062
                            BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                            HResult     : -2146232062
                        BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created.
The machine.config file is missing information. Verify that this configuration section is properly registered and that
you have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i
to fix this error.
                        HResult     : -2146232062
                    BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                    HResult     : -2146232062
                BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                TargetSite  :
                    Name          : UnsafeGetSectionNoTrace
                    DeclaringType : System.ServiceModel.Configuration.ConfigurationHelpers, System.ServiceModel,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
                    MemberType    : Method
                    Module        : System.ServiceModel.dll
                Source      : System.ServiceModel
                HResult     : -2146232062
                StackTrace  :
   at System.ServiceModel.Configuration.ConfigurationHelpers.UnsafeGetSectionNoTrace(String sectionPath)
   at System.ServiceModel.Configuration.DiagnosticSection.UnsafeGetSectionNoTrace()
   at System.ServiceModel.Diagnostics.TraceUtility.SetEtwProviderId()
   at System.ServiceModel.Diagnostics.TraceUtility..cctor()
            Source         : System.ServiceModel
            HResult        : -2146233036
            StackTrace     :
   at System.ServiceModel.Diagnostics.TraceUtility.SetEtwProviderId()
   at System.ServiceModel.ChannelFactory..ctor()
   at System.ServiceModel.ChannelFactory`1..ctor(Type channelType)
   at System.ServiceModel.ChannelFactory`1..ctor(Binding binding, EndpointAddress remoteAddress)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.InitializeChannel[TChannel](TChannel& channel,
ChannelFactory`1& chFactory, String endpointName, CommunicationException& commException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperatio
ns.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE(ICollection`1 propertyList, Boolean
propertyNamesOnly)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE(ICollection`1 propertyList)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.GetRootDSE(ADSessionInfo sessionInfo, ICollection`1
propertiesToRetrieve)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.GetRootDSE(ADSessionInfo sessionInfo)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.InitializeDefaultDrives()
   at System.Management.Automation.SessionStateInternal.InitializeProvider(CmdletProvider providerInstance,
ProviderInfo provider, CmdletProviderContext context)
        CategoryInfo          : InvalidOperation: (:) [], TypeInitializationException
        FullyQualifiedErrorId : InitializeDefaultDrivesException
    Message        : Attempting to perform the InitializeDefaultDrives operation on the 'ActiveDirectory' provider
failed.
    InnerException :
        Type           : System.TypeInitializationException
        TypeName       : System.ServiceModel.Diagnostics.TraceUtility
        TargetSite     :
            Name          : SetEtwProviderId
            DeclaringType : System.ServiceModel.Diagnostics.TraceUtility, System.ServiceModel, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089
            MemberType    : Method
            Module        : System.ServiceModel.dll
        Message        : The type initializer for 'System.ServiceModel.Diagnostics.TraceUtility' threw an exception.
        InnerException :
            Type        : System.Configuration.ConfigurationErrorsException
            Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
            Errors      :
                Type        : System.Configuration.ConfigurationErrorsException
                Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                Errors      :
                    Type        : System.Configuration.ConfigurationErrorsException
                    Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                    Errors      :
                        Type        : System.Configuration.ConfigurationErrorsException
                        Message     : The 'system.serviceModel/diagnostics' configuration section cannot be created.
The machine.config file is missing information. Verify that this configuration section is properly registered and that
you have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i
to fix this error.
                        Errors      :
                            Type        : System.Configuration.ConfigurationErrorsException
                            Message     : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                            Errors      :
                                Type        : System.Configuration.ConfigurationErrorsException
                                Message     : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                Errors      :
                                    Type        : System.Configuration.ConfigurationErrorsException
                                    Message     : The 'system.serviceModel/diagnostics' configuration section cannot
be created. The machine.config file is missing information. Verify that this configuration section is properly
registered and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                    Errors      : …
                                    BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot
be created. The machine.config file is missing information. Verify that this configuration section is properly
registered and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                    HResult     : -2146232062
                                BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                                HResult     : -2146232062
                            BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be
created. The machine.config file is missing information. Verify that this configuration section is properly registered
and that you have correctly spelled the section name. For Windows Communication Foundation sections, run
ServiceModelReg.exe -i to fix this error.
                            HResult     : -2146232062
                        BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created.
The machine.config file is missing information. Verify that this configuration section is properly registered and that
you have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i
to fix this error.
                        HResult     : -2146232062
                    BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                    HResult     : -2146232062
                BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
                HResult     : -2146232062
            BareMessage : The 'system.serviceModel/diagnostics' configuration section cannot be created. The
machine.config file is missing information. Verify that this configuration section is properly registered and that you
have correctly spelled the section name. For Windows Communication Foundation sections, run ServiceModelReg.exe -i to
fix this error.
            TargetSite  :
                Name          : UnsafeGetSectionNoTrace
                DeclaringType : System.ServiceModel.Configuration.ConfigurationHelpers, System.ServiceModel,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
                MemberType    : Method
                Module        : System.ServiceModel.dll
            Source      : System.ServiceModel
            HResult     : -2146232062
            StackTrace  :
   at System.ServiceModel.Configuration.ConfigurationHelpers.UnsafeGetSectionNoTrace(String sectionPath)
   at System.ServiceModel.Configuration.DiagnosticSection.UnsafeGetSectionNoTrace()
   at System.ServiceModel.Diagnostics.TraceUtility.SetEtwProviderId()
   at System.ServiceModel.Diagnostics.TraceUtility..cctor()
        Source         : System.ServiceModel
        HResult        : -2146233036
        StackTrace     :
   at System.ServiceModel.Diagnostics.TraceUtility.SetEtwProviderId()
   at System.ServiceModel.ChannelFactory..ctor()
   at System.ServiceModel.ChannelFactory`1..ctor(Type channelType)
   at System.ServiceModel.ChannelFactory`1..ctor(Binding binding, EndpointAddress remoteAddress)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.InitializeChannel[TChannel](TChannel& channel,
ChannelFactory`1& chFactory, String endpointName, CommunicationException& commException)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperatio
ns.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE(ICollection`1 propertyList, Boolean
propertyNamesOnly)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE(ICollection`1 propertyList)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.GetRootDSE(ADSessionInfo sessionInfo, ICollection`1
propertiesToRetrieve)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.GetRootDSE(ADSessionInfo sessionInfo)
   at Microsoft.ActiveDirectory.Management.Provider.ADProvider.InitializeDefaultDrives()
   at System.Management.Automation.SessionStateInternal.InitializeProvider(CmdletProvider providerInstance,
ProviderInfo provider, CmdletProviderContext context)
    HResult        : -2146233087
TargetObject          : Microsoft.ActiveDirectory.Management\ActiveDirectory
CategoryInfo          : InvalidOperation: (Microsoft.ActiveDir…ent\ActiveDirectory:ProviderInfo) [Import-Module],
ProviderInvocationException
FullyQualifiedErrorId : InitializeDefaultDrivesException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 12
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
    Line             : Import-Module
Disable-CompanyADUser,Get-CompanyADUser,New-CompanyUserCreation,Remove-CompanyADUser,Set-CompanyADAccountPassword,Start-CompanyAADSync

    Statement        : Import-Module
Disable-CompanyADUser,Get-CompanyADUser,New-CompanyUserCreation,Remove-CompanyADUser,Set-CompanyADAccountPassword,Start-CompanyAADSync
    PositionMessage  : At C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:12 char:1
                       + Import-Module Disable-CompanyADUser,Get-CompanyADUser,New-CompanyUserCreation,Rem …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\myuser\Documents\PowerShell
    PSCommandPath    : C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\myuser\Documents\PowerShell\Microsoft.PowerShell_profile.ps1: line 12
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\Users\myuser> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="867" alt="Pwsh-Preview7 4 0preview2" src="https://user-images.githubusercontent.com/3027879/225435945-c07253d5-375f-472a-b75a-23ddc50ea76a.png">
<img width="867" alt="Pwsh7 3 3 3" src="https://user-images.githubusercontent.com/3027879/225435947-5ac59e4b-809d-40fc-99ba-59903c1ac3f7.png">

**Comment by gwojan** [comment]
I can confirm `Import-Module ActiveDirectory -UseWindowsPowerShell` allows the module to import into `PowerShell 7.4.0-daily20230315.1` although I much prefer the implicit remoting of the previous behavior.

I had previously created a similar issue #19238.

**Comment by jborean93** [comment]
Any reason for the duplicate issue with #19238, they seem to be the same thing.
