### ISSUE TITLE
Get-Service fails to enumerate all services

### ISSUE THREAD

**Issue by NotNotWrongUsually** [PowerShell/PowerShell#19373]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a problem with a service on my local machine (unrelated to this issue). This causes a bug when trying to run Get-Service.

Enumeration stops at the problematic service and does not list remaining services.

### Expected behavior

```console
PS > get-service

Status   Name               DisplayName
------   ----               -----------
<Enumeration of all services>
```
```


### Actual behavior

```console
PS > get-service

Status   Name               DisplayName
------   ----               -----------
Stopped  AarSvc_686e4       AarSvc_686e4
.
<Snip of listed services between AarSvc_686e4 and CryptSvc>
.
Running  CryptSvc           Cryptographic Services
Running  DcomLaunch         DCOM Server Process Launcher
Get-Service: Service 'dcsvc (dcsvc)' cannot be queried due to the following error:
Get-Service: The system cannot find the file specified.

PS >
```
```


### Error details

```console
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 2
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : get_StartType
        DeclaringType : System.ServiceProcess.ServiceController
        MemberType    : Method
        Module        : System.ServiceProcess.ServiceController.dll
    Message         : The system cannot find the file specified.
    Source          : System.ServiceProcess.ServiceController
    HResult         : -2147467259
    StackTrace      :
   at System.ServiceProcess.ServiceController.get_StartType()
   at Microsoft.PowerShell.Commands.GetServiceCommand.AddProperties(ServiceController service)
   at Microsoft.PowerShell.Commands.GetServiceCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Get-Service], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.GetServiceCommand
InvocationInfo        :
    MyCommand        : Get-Service
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 5
    Line             : get-service
    PositionMessage  : At line:1 char:1
                       + get-service
                       + ~~~~~~~~~~~
    InvocationName   : get-service
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Here is a paste bin of the definition in registry of the service in question. Might be useful to reproduce: https://pastebin.com/uHf0gris

**Comment by jhoneill** [comment]
I'm sure that I reported a similar issue but I cannot find it. 
Try  Get-CimInstance -Query "Select * from Win32_service where name = 'dcsvc'" and see if there is a similar error. Usually this is a sign of an incorrectly configured service. IIRC the name of something was a resource in a DLL which was missing in my case.

**Comment by iSazonov** [comment]
Dup #10371

**Comment by jhoneill** [comment]
> Dup #10371

That's the one I couldn't find :-)

**Comment by iSazonov** [comment]
I believe both issues have one nature - no permissions. (Although it could be different code paths.)

**Comment by NotNotWrongUsually** [comment]
> I believe both issues have one nature - no permissions. (Although it could be different code paths.)

Fair. Probably different severities though. In the incarnation described in #10371 scripts would mostly work (maybe with a little massaging if you are using trapping).

In my case any script trying to do something with services as a whole just utterly breaks (e.g. `Get-Service | Measure-Object`, `Get-Service | Group-Object`, `Get-Service | Foreach-Object { #Whatever }` are all dead in the water. Essentially, the `Get-Service` cmdlet is totally broken for any purpose beyond polling a specific named service.

**Comment by eabase** [comment]
Related to
https://github.com/PowerShell/PowerShell/issues/20188
