### ISSUE TITLE
`Test-Path` with `OlderThan`/`NewerThan` parameters fails in combination with `PathType` parameter

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#19462]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running `Test-Path` with `OlderThan`/`NewerThan` parameters works as expected. Including `PathType` to limit file type results in an error.

It's not necessary to check path type for file datetime comparison, but the parameter sets indicate that you should be able to use both these parameters together.

```powershell
Test-Path [-Path] <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-PathType <TestPathType>] [-IsValid] [-Credential <pscredential>] [-OlderThan <datetime>] [-NewerThan <datetime>] [<CommonParameters>]

Test-Path -LiteralPath <string[]> [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-PathType <TestPathType>] [-IsValid] [-Credential <pscredential>] [-OlderThan <datetime>] [-NewerThan <datetime>] [<CommonParameters>]
```

### Expected behavior

```console
PS> Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1)) -PathType Leaf
True

PS> Test-Path -Path .\requirements.txt -NewerThan ((Get-Date).AddHours(-1)) -PathType Leaf
False
```

### Actual behavior

```console
PS> Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1)) -PathType Leaf
Test-Path: A parameter cannot be found that matches parameter name 'OlderThan'.

PS> Test-Path -Path .\requirements.txt -NewerThan ((Get-Date).AddHours(-1)) -PathType Leaf
Test-Path: A parameter cannot be found that matches parameter name 'NewerThan'.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : A parameter cannot be found that matches parameter name 'OlderThan'.
    ParameterName     : OlderThan
    ErrorId           : NamedParameterNotFound
    Line              : 1
    Offset            : 36
    CommandInvocation :
        MyCommand        : Test-Path
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 2
            Keys     :
                Length : 4

                Length : 8
            Values   :
                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                    Length : 18
                IsFixedSize : True
                Count       : 1

                value__ : 2
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 2
                Keys     :
                    Length : 4

                    Length : 8
                Values   :
                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                        Length : 18
                    IsFixedSize : True
                    Count       : 1

                    value__ : 2
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 2
                    Keys     :
                        Length : 4

                        Length : 8
                    Values   :
                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                            Length : 18
                        IsFixedSize : True
                        Count       : 1

                        value__ : 2
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 2
                        Keys     :
                            Length : 4

                            Length : 8
                        Values   :
                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                Length : 18
                            IsFixedSize : True
                            Count       : 1

                            value__ : 2
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 2
                            Keys     :
                                Length : 4

                                Length : 8
                            Values   :
                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                    Length : 18
                                IsFixedSize : True
                                Count       : 1

                                value__ : 2
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 2
                                Keys     :
                                    Length : 4

                                    Length : 8
                                Values   :
                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1

                                    value__ : 2
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 2
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 4
        Line             : Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1)) -PathType Leaf
        PositionMessage  : At line:1 char:1
                           + Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1 …
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Test-Path
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : A parameter cannot be found that matches parameter name 'OlderThan'.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Test-Path], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestPathCommand
        InvocationInfo        :
            MyCommand        : Test-Path
            ScriptLineNumber : 1
            OffsetInLine     : 36
            HistoryId        : 4
            Line             : Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1)) -PathType Leaf
            PositionMessage  : At line:1 char:36
                               + Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1 …
                               +                                    ~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : VerifyArgumentsProcessed
        DeclaringType : System.Management.Automation.CmdletParameterBinderController, System.Management.Automation,
Version=7.3.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException
originalBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Test-Path], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestPathCommand
InvocationInfo        :
    MyCommand        : Test-Path
    ScriptLineNumber : 1
    OffsetInLine     : 36
    HistoryId        : 4
    Line             : Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1)) -PathType Leaf
    PositionMessage  : At line:1 char:36
                       + Test-Path -Path .\requirements.txt -OlderThan ((Get-Date).AddHours(-1 …
                       +                                    ~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ArmaanMcleod** [comment]
@iSazonov I think this is because dynamic parameters from file system provider is only working for `TestPathType.Any`: https://github.com/PowerShell/PowerShell/blob/71c123cd53d1cde539888403c5dd93fd3af713b3/src/Microsoft.PowerShell.Commands.Management/commands/management/PingPathCommand.cs#L139

I would think that the `-OlderThan` and `-NewerThan` parameters would work with any path type. Do you think this is a bug or is it by design?

**Comment by iSazonov** [comment]
I agree that the dynamic parameters must work in scenarios like "Is there a test.txt file created in the last week?".
It is also obvious that TestPathType.Any implies that this includes TestPathType.Containter and TestPathType.Leaf. This seems to be a mind game :-) It seems to imply that TestPathType is a Flags Enum.

**Comment by ArmaanMcleod** [comment]
@iSazonov Yep I agree, I thought it was Flags enum as well. I guess you could do:

```csharp
[Flags]
public enum TestPathType
{
    Container = 0x01,
    Leaf = 0x02,
    Any = Container | Leaf
}
```

But not sure this is a breaking change as it changes the enum definition a bit. 

Other option I see perhaps is just removing the condition for `TestPathType.Any` and allow all path types to get dynamic parameters from file system provider.

In the current state it seems like unintuitive UX to always have to use `TestPathType.Any`. I think it should included for any path type.

**Comment by iSazonov** [comment]
> But not sure this is a breaking change as it changes the enum definition a bit.
> 

Formally it is a breaking change and we need PowerShell Committee approval. I think it is under 3 bracket.

/cc @SteveL-MSFT 

> Other more straightforward option I see perhaps is just removing the condition for `TestPathType.Any` and allow all path types to get dynamic parameters from file system provider.
> 
> In the current state it is unintuitive UX to always have to use `TestPathType.Any`. I think it should be included for any path type.

`TestPathType.Any` is default so I don't see any problems in both UX and the implementation.

**Comment by SteveL-MSFT** [comment]
Will have Cmdlets WG review

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets  reviewed this.  We agree that -PathType should be able to be used with -OlderThan and -NewerThan.  It appears to be an issue with how the dynamic parameters are returned, but more due diligence is needed to understand the root cause for a proper fix.

**Comment by ArmaanMcleod** [comment]
@SteveL-MSFT I believe a simple fix would be to remove the `this.PathType == TestPathType.Any` check from `GetDynamicParameters` so that `OlderThan`/`NewerThan` dynamic parameters from File System Provider can be used for any path type. 

I wonder though if this restriction on dynamic parameters was by design or just an oversight when the cmdlet was created.

**Comment by iSazonov** [comment]
I suppose we can remove this check, since `Oldthan/NewerThen` parameters works today for Leaf and Container with default arguments and we are not opening new paths for other code branches.
