### ISSUE TITLE
Bug (ConfigCI module) when creating WDAC policy rule with PFN level in PowerShell 7.4

### ISSUE THREAD

**Issue by HotCakeX** [PowerShell/PowerShell#19526]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Type this in PowerShell:

```powershell
$Packages = Get-AppXPackage -Name "Microsoft.WindowsStore"
foreach ($Package in $Packages){ $Rules += New-CIPolicyRule -Package $Package }
New-CIPolicy -FilePath "C:\store.xml" -Rules $Rules 
```

### Expected behavior

The expected behavior and the behavior of running the same command in Windows PowerShell, is for store.xml file to be created in C drive and no output to be shown on the console, meaning it was a success.

### Actual behavior

```console
New-CIPolicyRule: Cannot bind parameter 'Package'. Cannot convert the "Microsoft.WindowsStore_22301.1401.15.0_x64__8wekyb3d8bbwe" value of type "Deserialized.Microsoft.Windows.Appx.PackageManager.Commands.AppxPackage" to type "Microsoft.Windows.Appx.PackageManager.Commands.AppxPackage".
```

### Error details

```console
OriginInfo            : localhost
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Rules' because it is null.
                                     at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Rules' because it is null.
                                             at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             --- End of stack trace from previous location where exception was thrown ---
                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Rules' because it is null.
                                                     at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     --- End of stack trace from previous location where exception was thrown ---
                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Rules' because it is null.
                                                             at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             --- End of stack trace from previous location where exception was thrown ---
                                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Rules' because it is null.
                                                                     at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     --- End of stack trace from previous location where exception was thrown ---
                                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : ΓÇª
                                    Message                        : Cannot bind argument to parameter 'Rules' because it is null.
                                    HResult                        : -2146233087
                                CategoryInfo          : InvalidData: (:) [New-CIPolicy], ParameterBindingValidationException
                                FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.SecureBoot.UserConfig.NewCIPolicy
                            Message                        : Cannot bind argument to parameter 'Rules' because it is null.
                            HResult                        : -2146233087
                        CategoryInfo          : InvalidData: (:) [New-CIPolicy], ParameterBindingValidationException
                        FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.SecureBoot.UserConfig.NewCIPolicy
                    Message                        : Cannot bind argument to parameter 'Rules' because it is null.
                    HResult                        : -2146233087
                CategoryInfo          : InvalidData: (:) [New-CIPolicy], ParameterBindingValidationException
                FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.SecureBoot.UserConfig.NewCIPolicy
            Message                        : Cannot bind argument to parameter 'Rules' because it is null.
            HResult                        : -2146233087
        CategoryInfo          : InvalidData: (:) [New-CIPolicy], ParameterBindingValidationException
        FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.SecureBoot.UserConfig.NewCIPolicy
    Message                        : Cannot bind argument to parameter 'Rules' because it is null.
    HResult                        : -2146233087
CategoryInfo          : InvalidData: (:) [New-CIPolicy], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.SecureBoot.UserConfig.NewCIPolicy
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/118815227/232768302-070a1691-d1be-4bd5-8009-f00a7c4820c9.png)

**Comment by HotCakeX** [comment]
Tried first importing ConfigCI module in PowerShell core and then run my command, but still get an error:

```powershell
Import-Module -name ConfigCI -SkipEditionCheck
Import-Module -name ConfigCI -SkipEditionCheck
$Packages = Get-AppXPackage -Name "Microsoft.WindowsStore"
foreach ($Package in $Packages) { $Rules += New-CIPolicyRule -Package $Package -Deny }
New-CIPolicy -FilePath "C:\store.xml" -Rules $Rules
```

Error

```
ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "
```

**Comment by PaulHigin** [comment]
@HotCakeX The `ConfigCI` module is not marked as compatible with PowerShell Core (it is built with an old version of the dotNet framework not compatible with PS7) and so PowerShell7 uses a proxy module to run it in WindowsPowerShell(5.1) as a remote session.  The problem with this is that returned objects are de-serialized property bags (not live type instances) and is why you are getting the de-serialization errors.  

```powershell
$Rules += New-CIPolicyRule -Package $Package -Deny
New-CIPolicy -FilePath "C:\store.xml" -Rules $Rules
```
The `$Rules` variable contains de-serialized versions of the ConfigCI rule type and when you pass that variable back to the cmdlet as an input argument, the module cannot recognize the type.

Loading `ConfigCI` with the `-SkipEditionCheck` parameter switch is a last-ditch effort to go ahead and run the module in PowerShell7 session anyway to see if it might work (make sure you do this in a new PowerShell session).  But it seems like this doesn't work either and ConfigCI is not compatible.

I recommend only using `ConfigCI` in WindowsPowerShell5.1 until the module is updated to support PowerShell core.

**Comment by HotCakeX** [comment]
@PaulHigin Thank you for the perfect explanation,
unfortunately I can't use Windows PowerShell, because my [WDACConfig](https://github.com/HotCakeX/Harden-Windows-Security/wiki/WDACConfig) PowerShell module requires version 7.3.4 (a specific related bug is fixed in that version) and the advanced functionalities won't allow me to downgrade.

Given the importance of `ConfigCI` module in Windows security, I really hope it will be updated soon.

**Comment by PaulHigin** [comment]
Agreed.  I'll make internal inquiries to see when the module can be updated.

**Comment by HotCakeX** [comment]
Thank you so much!
