### ISSUE TITLE
Enable-PSRemoting fails with "Value cannot be null. (Parameter 's')"

### ISSUE THREAD

**Issue by K0nne** [PowerShell/PowerShell#19569]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello,

I am working with new Win10 Client (22H2) with Powershell 7.3.4.
When I run `enable-psremoting` in an elevated shell, it fails with the following error:

```
PowerShell 7.3.4
PS C:\Windows\System32> enable-psremoting
WARNING: PowerShell remoting has been enabled only for PowerShell 6+ configurations and does not affect Windows PowerShell remoting configurations. Run this cmdlet in Windows PowerShell to affect all PowerShell remoting configurations.

Set-WSManQuickConfig:
Line |
 121 |                  Set-WSManQuickConfig -force
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 's')
```

Not sure what is missing.The system ist fresh and up to date.
I tried the following:

Component store is ok:
```
PS C:\Windows\System32> dism /Online /Cleanup-Image /ScanHealth

Tool zur Imageverwaltung für die Bereitstellung
Version: 10.0.19041.844

Abbildversion: 10.0.19045.2846

[==========================100.0%==========================] Es wurde keine Komponentenspeicherbeschädigung erkannt.
Der Vorgang wurde erfolgreich beendet.
```

The image is healthy:
```
PS C:\Windows\System32> Repair-WindowsImage -Online -CheckHealth

Path             :
Online           : True
ImageHealthState : Healthy
RestartNeeded    : False
```
```
PS C:\Windows\System32> Repair-WindowsImage -Online -ScanHealth

Path             :
Online           : True
ImageHealthState : Healthy
RestartNeeded    : False
```
```
PS C:\Windows\System32> Repair-WindowsImage -Online -RestoreHealth

Path             :
Online           : True
ImageHealthState : Healthy
RestartNeeded    : False
```
Reboot

Windows 10 seems to be okay:
```
PowerShell 7.3.4
PS C:\Windows\System32> sfc /scannow

Systemsuche wird gestartet. Dieser Vorgang kann einige Zeit dauern.

Überprüfungsphase der Systemsuche wird gestartet.
Überprüfung 100 % abgeschlossen.

Der Windows-Ressourcenschutz hat keine Integritätsverletzungen gefunden.
```

Do you have any hint for me how to fix this? I need to enable ps-remoting.

### Expected behavior

```console
enable-psremoting should work.
```

### Actual behavior

```console
enable-psremoting fails and the error message is not helfpul, from the perspective of an enduser. what is parameter s and how can i set it? what exactly is missing or broken?
```

### Error details

```console
PS C:\Windows\System32> get-error

Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 's')
    ParamName  : s
    TargetSite :
        Name          : ThrowArgumentNullException
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147467261
    StackTrace :
   at System.IO.StringReader..ctor(String s)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at Microsoft.WSMan.Management.SetWSManQuickConfigCommand.QuickConfigRemoting(Boolean serviceonly)
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [Set-WSManQuickConfig], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.WSMan.Management.SetWSManQuickConfigCommand
InvocationInfo        :
    MyCommand        : Set-WSManQuickConfig
    ScriptLineNumber : 121
    OffsetInLine     : 17
    HistoryId        : 2
    Line             : Set-WSManQuickConfig -force

    PositionMessage  : At line:121 char:17
                       +                 Set-WSManQuickConfig -force
                       +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Set-WSManQuickConfig
    CommandOrigin    : Internal
ScriptStackTrace      : at Enable-PSSessionConfiguration<Begin>, <No file>: line 121
                        at <ScriptBlock>, <No file>: line 207
                        at Enable-PSRemoting<End>, <No file>: line 145
                        at <ScriptBlock>, <No file>: line 231
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\Windows\System32> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by K0nne** [comment]
I have found the source of the problem.

PS-Remoting works perfectly until I run sysprep against the image:
`C:\Windows\System32\Sysprep\sysprep.exe /oobe /generalize /unattend:C:\windows\panther\unattend.xml`

After the generalization something seems to be broken with WSMan.
