### ISSUE TITLE
powershell on rhel 8 gives error running on docker without maximized powershell windows on windows

### ISSUE THREAD

**Issue by GjpaRRY** [PowerShell/PowerShell#19639]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
tryuing to run any commend in docker container after opening interactive session with it using:

nerdctl exec -it 36fd8cdfaa53 /bin/bash


get error after running pwsh

EProcess terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)Aborted
```

### Screenshot

bash-4.4$ pwsh
PowerShell 7.3.4
PS /home/oracle>

### Environment data

```console
bash-4.4$ pwsh -c '$psversiontable'

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 PowerShell/PSReadLine#1 SMP …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Steps to reproduce

install powershell 7.3.4.1 on container... on oracle enterprise linux... run conatiner connect to it without maximising powershell windows on widnows.  open pwsh ... typoe any commands and get error

### Expected behavior

No exception

### Actual behavior

get error shown above

**Comment by daxian-dbw** [comment]
The exception happens when setting the `Console.CursorLeft` with an invalid value, and that invalid value is actually just read from `Console.CursorLeft` (see details in the [ReadLineFromConsole](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1567) method). This is likely due to something with the terminal in the repro environment that caused .NET's `Console` API to not work properly.

It would be great if detailed repro steps can be provided for us to repro it locally.

**Comment by GjpaRRY** [comment]
Hi sure.. actuallly the repro steps are above... CReated a Oracle enterprise linux 8 docker container from the slim container., copying the powershell 7.3.4.1 rpm to it . 

afetr creating the docker container installed powershell from the rpm., prio to this installed libciu aswell. 

connected session to container using nerdctl exec -it 36fd8cdfaa53 /bin/bash  from powershel 7.3.4 windows session. 

in a maximized windows powersghell window, it does not crash, but repeats visually characaters typed... if the powershell on windows isn not maximized it crashes after tryping anything. 

my pc has powershell 7.3.4 and widnows 11 with all latest updates.

**Comment by kasini3000** [comment]
hi ,I have compiled the best way powershell , share with you


### Powershell Docker Home Page
https://hub.docker.com/_/microsoft-powershell

### Docker pull's tag list
https://mcr.microsoft.com/v2/powershell/tags/list

### Usage:
On the host:
===================================
mkdir /powershell
docker run -it --pid=host -v /powershell:/mnt    mcr.microsoft.com/powershell:7.3-alpine-3.17
Then use the powershell command to read and write files under/mnt in the container.
===================================


----

### Multiple Linux distributions, one click installation of powershell, and batch and offline installation.
https://gitee.com/chuanjiao10/kasini3000_agent_linux

**Comment by theJasonHelmick** [comment]
@GjpaRRY - Would it be possible to test this with PowerShell 7.4 on the container?  Can you run `tty` on the container and provide the results? Another option - could you test using our container image: mcr.microsoft.com/powershell:ubi-8
