### ISSUE TITLE
Generated proxy code for Export-Csv doesn't properly handle the -Encoding parameter

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#19647]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you generate a proxy for `Export-Csv` using:

```powershell
$MetaData = New-Object System.Management.Automation.CommandMetaData (Get-Command  Export-Csv)
[System.Management.Automation.ProxyCommand]::Create($MetaData)
```

The resulting code contains the following definition for the `-Encoding` parameter:

```powershell
    [ValidateNotNullOrEmpty()]
    [System.Text.Encoding]
    ${Encoding},
```

As a result, the proxy code only accepts the values that are in the  `System.Text.Encoding` type, so notably not `utf8BOM`:

```powershell
PS> $null | C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
Export-Csv-Proxy-7.3.4.ps1: Cannot process argument transformation on parameter 'Encoding'. Cannot convert the "utf8bom" value of type "System.String" to type "System.Text.Encoding".
```

Another anomaly: Attempting to provide the value of the `-Encoding` parameter using `Ctrl+Space` doesn't work.

(running PSReadLine 2.3.1 beta1 at this point, FWIW)

### Expected behavior

utf8BOM support:
```console
PS> Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
# no error, same behavior as Export-Csv
```

Ctrl+Space behavior:
```console
C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding<Ctrl+Space>
ascii             bigendianutf32    unicode           utf8              utf8NoBOM
bigendianunicode  oem               utf7              utf8BOM           utf32
```

### Actual behavior

utf8BOM is not supported:
```console
PS> Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
Export-Csv-Proxy-7.3.4.ps1: Cannot process argument transformation on parameter 'Encoding'. Cannot convert the "utf8bom" value of type "System.String" to type "System.Text.Encoding".
```

Ctrl+Space does nothing:
```console
C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding<Ctrl+Space>
(nothing happens)
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingArgumentTransformationException
    Message           : Cannot process argument transformation on parameter 'Encoding'. Cannot convert the "utf8bom"
value of type "System.String" to type "System.Text.Encoding".
    ParameterName     : Encoding
    ParameterType     : System.Text.Encoding
    TypeSpecified     : string
    ErrorId           : ParameterArgumentTransformationError
    Line              : 1
    Offset            : 45
    CommandInvocation :
        MyCommand        : Export-Csv-Proxy-7.3.4.ps1
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 10
        Line             : C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
        PositionMessage  : At line:1 char:1
                           + C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : C:\tmp\Export-Csv-Proxy-7.3.4.ps1
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot process argument transformation on parameter 'Encoding'. Cannot convert the "utf8bom"
value of type "System.String" to type "System.Text.Encoding".
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Export-Csv-Proxy-7.3.4.ps1], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-Csv-Proxy-7.3.4.ps1
        InvocationInfo        :
            MyCommand        : Export-Csv-Proxy-7.3.4.ps1
            ScriptLineNumber : 1
            OffsetInLine     : 45
            HistoryId        : 10
            Line             : C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
            PositionMessage  : At line:1 char:45
                               + C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
                               +                                             ~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : BindParameter
        DeclaringType : System.Management.Automation.ParameterBinderBase, System.Management.Automation,
Version=7.3.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type           : System.Management.Automation.ArgumentTransformationMetadataException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert the "utf8bom" value of type "System.String" to type "System.Text.Encoding".
                HResult : -2146233087
            CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : RuntimeException
        TargetSite     :
            Name          : Transform
            DeclaringType : System.Management.Automation.ArgumentTypeConverterAttribute, System.Management.Automation,
Version=7.3.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert the "utf8bom" value of type "System.String" to type "System.Text.Encoding".
        InnerException :
            Type        : System.Management.Automation.PSInvalidCastException
            ErrorRecord :
                Exception             :
                    Type    : System.Management.Automation.ParentContainsErrorRecordException
                    Message : Cannot convert the "utf8bom" value of type "System.String" to type
"System.Text.Encoding".
                    HResult : -2146233087
                CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
                FullyQualifiedErrorId : ConvertToFinalInvalidCastException
            TargetSite  :
                Name          : ThrowInvalidCastException
                DeclaringType : System.Management.Automation.LanguagePrimitives
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message     : Cannot convert the "utf8bom" value of type "System.String" to type "System.Text.Encoding".
            Source      : System.Management.Automation
            HResult     : -2147467262
            StackTrace  :
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType,
Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType,
Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean
recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object
inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
        Source         : System.Management.Automation
        HResult        : -2146233087
        StackTrace     :
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object
inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument,
MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets,
CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets,
CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Export-Csv-Proxy-7.3.4.ps1], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-Csv-Proxy-7.3.4.ps1
InvocationInfo        :
    MyCommand        : Export-Csv-Proxy-7.3.4.ps1
    ScriptLineNumber : 1
    OffsetInLine     : 45
    HistoryId        : 10
    Line             : C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
    PositionMessage  : At line:1 char:45
                       + C:\tmp\Export-Csv-Proxy-7.3.4.ps1 -Encoding utf8bom
                       +                                             ~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sba923** [comment]
A poor man'(s workaround can be to change the definition of the parameter to

```powershell
    [ValidateNotNullOrEmpty()]
    [System.String]
    ${Encoding},
```

**Comment by mklement0** [comment]
The problem is that the proxy-generation code doesn't include the `[System.Management.Automation.ArgumentTransformationAttribute]` that the original parameter is decorated with, which is necessary to convert a string (e.g. `'windows-1252'` or number (e.g., `1252`) to a `[System.Text.Encoding]` instance.

(For that reason you're probably better off not typing the parameter at all in your workaround.)

There's also an argument-completer attribute that's not included.

I wonder if such attributes are categorically not included.

**Comment by sba923** [comment]
Reworked the description to include #19648, per @mklement0's suggestion.
