### ISSUE TITLE
PowerShell 7.2.11 fails to start on Alpine 3.18 using .NET SDK 6.0.408

### ISSUE THREAD

**Issue by lbussell** [PowerShell/PowerShell#19703]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a Dockerfile with the following content:
```Dockerfile
FROM amd64/alpine:3.18

RUN apk add --no-cache \
        ca-certificates \
        bash \
        \
        # .NET dependencies
        krb5-libs \
        libgcc \
        libintl \
        libssl3 \
        libstdc++ \
        zlib \
        curl \
        icu-data-full \
        icu-libs \
        git

# Install .NET 6
RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Quality preview -Channel 6.0 -InstallDir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

# Install PowerShell global tool
RUN powershell_version=7.2.11 \
    && wget -O PowerShell.Linux.Alpine.$powershell_version.nupkg https://pwshtool.blob.core.windows.net/tool/$powershell_version/PowerShell.Linux.Alpine.$powershell_version.nupkg \
    && powershell_sha512='ce57a18d2b6bc98340eb34861bbd7552964dd6d5258f9af2b7cb22513ced655668df01ff8359fca03abf3bd8ffb8321e141e14bf955be167648296be36b8e0e1' \
    && echo "$powershell_sha512  PowerShell.Linux.Alpine.$powershell_version.nupkg" | sha512sum -c - \
    && mkdir -p /usr/share/powershell \
    && dotnet tool install --add-source / --tool-path /usr/share/powershell --version $powershell_version PowerShell.Linux.Alpine \
    && dotnet nuget locals all --clear \
    && rm PowerShell.Linux.Alpine.$powershell_version.nupkg \
    && ln -s /usr/share/powershell/pwsh /usr/bin/pwsh \
    && chmod 755 /usr/share/powershell/pwsh \
    # To reduce image size, remove the copy nupkg that nuget keeps.
    && find /usr/share/powershell -print | grep -i '.*[.]nupkg$' | xargs rm \
    # Add ncurses-terminfo-base to resolve psreadline dependency
    && apk add --no-cache ncurses-terminfo-base
```

2. Build the Dockerfile: `> docker build -t repro -f .\Dockerfile .`
3. Try to run PowerShell: `> docker run --rm repro pwsh`

### Expected behavior

```console
Powershell runs successfully and outputs

> docker run --rm repro pwsh
PowerShell 7.2.11
>
```
```


### Actual behavior

```console
PS C:\...> docker run --rm repro pwsh
PowerShell 7.2.11
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

One or more errors occurred. (The type initializer for 'System.Management.Automation.TypeAccelerators' threw an exception.)
One or more errors occurred. (The type initializer for 'System.Management.Automation.TypeAccelerators' threw an exception.)
Cannot load PSReadline module.  Console is running without PSReadline.
Process terminated. The type initializer for 'System.Management.Automation.PSObject' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSObject' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.get_Properties()
   at System.Management.Automation.HostUtilities.GetDollarProfile(String allUsersAllHosts, String allUsersCurrentHost, String currentUserAllHosts, String currentUserCurrentHost)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceInitialization(Boolean skipProfiles, String initialCommand, String configurationName, Collection`1 initialCommandArgs)
   at Microsoft.PowerShell.ConsoleHost.DoCreateRunspace(String initialCommand, Boolean skipProfiles, Boolean staMode, String configurationName, Collection`1 initialCommandArgs)
   at Microsoft.PowerShell.ConsoleHost.CreateRunspace(Object runspaceCreationArgs)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
```

### Environment data

```powershell
Cannot access $PSVersionTable because PowerShell will not start. The bash variable $PSVersionTable is empty.
```

**Comment by rhubarb-geek-nz** [comment]
I tried in an Alpine docker with the alpine 7.3.4 and 7.2.11 tar gz and they both worked

```
$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

With [powershell-7.3.4-linux-alpine-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/powershell-7.3.4-linux-alpine-x64.tar.gz)

```
$ powershell-7.3.4/pwsh 
PowerShell 7.3.4
PS> exit 
```

With [powershell-7.2.11-linux-alpine-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/powershell-7.2.11-linux-alpine-x64.tar.gz)

```
$ powershell-7.2.11/pwsh
PowerShell 7.2.11
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS> exit
```

**Comment by rhubarb-geek-nz** [comment]
Alpine 3.18.0 has its own build of dotnet-sdk-6.0

```
alpine3:~$ sudo apk add dotnet-sdk-6.0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
fetch https://svn.rhubarb.geek.nz/pkg/alpine/3.18.0/x86_64/APKINDEX.tar.gz
(1/15) Installing dotnet-host (7.0.5-r3)
(2/15) Installing dotnet6-hostfxr (6.0.16-r3)
(3/15) Installing icu-data-full (73.1-r1)
(4/15) Installing lttng-ust (2.13.5-r2)
(5/15) Installing xz-libs (5.4.3-r0)
(6/15) Installing libunwind (1.6.2-r3)
(7/15) Installing dotnet6-runtime (6.0.16-r3)
(8/15) Installing aspnetcore6-runtime (6.0.16-r3)
(9/15) Installing aspnetcore6-targeting-pack (6.0.16-r3)
(10/15) Installing dotnet6-apphost-pack (6.0.16-r3)
(11/15) Installing dotnet6-targeting-pack (6.0.16-r3)
(12/15) Installing dotnet6-templates (6.0.116-r2)
(13/15) Installing netstandard21-targeting-pack (7.0.105-r3)
(14/15) Installing dotnet6-sdk (6.0.116-r2)
(15/15) Purging icu-data-en (73.1-r1)
Executing busybox-1.36.0-r9.trigger
OK: 746 MiB in 102 packages
```

and dotnet-sdk-7.0

```
alpine3:~$ sudo apk add dotnet-sdk-7.0
(1/9) Installing dotnet7-hostfxr (7.0.5-r3)
(2/9) Installing dotnet7-runtime (7.0.5-r3)
(3/9) Installing aspnetcore7-runtime (7.0.5-r3)
(4/9) Installing aspnetcore7-targeting-pack (7.0.5-r3)
(5/9) Installing dotnet7-apphost-pack (7.0.5-r3)
(6/9) Installing dotnet7-targeting-pack (7.0.5-r3)
(7/9) Installing dotnet7-templates (7.0.105-r3)
(8/9) Installing libucontext (1.2-r2)
(9/9) Installing dotnet7-sdk (7.0.105-r3)
OK: 1196 MiB in 111 packages
```

**Comment by rhubarb-geek-nz** [comment]
It also has powershell 7.3.4 as an apk

```
alpine3:~$ sudo apk add powershell
(1/2) Installing libpsl-native (7.3.1-r0)
(2/2) Installing powershell (7.3.4-r1)
Executing busybox-1.36.0-r9.trigger
OK: 1245 MiB in 113 packages
alpine3:~$ pwsh
PowerShell 7.3.4
PS> exit
```

**Comment by lbussell** [comment]
> I tried in an Alpine docker with the alpine 7.3.4 and 7.2.11 tar gz and they both worked

Those tar.gz's include the .NET Runtime. Since we want to keep our image size as small as possible, we want to use the .NET Runtime/SDK version from the base image, in this case it would be the official ASP.NET/SDK images. I didn't care about size in the repro Dockerfile above so I just installed the whole .NET SDK wholesale in the same image. The actual Dockerfile we're working on is here: https://github.com/dotnet/dotnet-docker/blob/nightly/src/sdk/6.0/alpine3.17/amd64/Dockerfile

> Alpine 3.18.0 has its own build of dotnet-sdk-6.0
> 
> ```
> alpine3:~$ sudo apk add dotnet-sdk-6.0
> ...
> OK: 746 MiB in 102 packages
> ```

For similar reasons, we can't have a 700+ MB installation of PowerShell or .NET in these images. The total image size here usually ends up around 200MB.

**Comment by rhubarb-geek-nz** [comment]
Just installing PowerShell APK depends just the dotnet7-runtime APK, not the entire SDK

```
alpine3:~$ sudo apk add powershell
(1/12) Installing libgcc (12.2.1_git20220924-r10)
(2/12) Installing libstdc++ (12.2.1_git20220924-r10)
(3/12) Installing dotnet-host (7.0.5-r3)
(4/12) Installing dotnet7-hostfxr (7.0.5-r3)
(5/12) Installing icu-data-full (73.1-r1)
(6/12) Installing icu-libs (73.1-r1)
(7/12) Installing lttng-ust (2.13.5-r2)
(8/12) Installing xz-libs (5.4.3-r0)
(9/12) Installing libunwind (1.6.2-r3)
(10/12) Installing dotnet7-runtime (7.0.5-r3)
(11/12) Installing libpsl-native (7.3.1-r0)
(12/12) Installing powershell (7.3.4-r1)
Executing busybox-1.36.0-r9.trigger
OK: 172 MiB in 45 packages
```

**Comment by lbussell** [comment]
I am not seeing this issue any more with the latest image, `mcr.microsoft.com/dotnet/sdk:6.0.417-alpine3.18`.
