### ISSUE TITLE
Powershell 7.4.0 don't handle Microsoft Exchange exceptions

### ISSUE THREAD

**Issue by tron2k** [PowerShell/PowerShell#19793]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$UserCredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://<ServerFQDN>/PowerShell/ -Authentication Kerberos -Credential $UserCredential
Import-PSSession $Session -DisableNameChecking
try { Get-Mailbox x -ErrorAction "Stop" } catch { Write-Warning $_.Exception.Message }

### Expected behavior

```console
try { Get-Mailbox x -ErrorAction Stop} catch { Write-Warning $_.Exception.Message }
WARNING: The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
```

### Actual behavior

```console
try { Get-Mailbox x -ErrorAction Stop} catch { Write-Warning $_.Exception.Message }
Get-Mailbox: The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
```

### Error details

```console
OriginInfo            : <ServerFQDN>
Exception             :
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                                     at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl)
                                     at Microsoft.Exchange.Configuration.Tasks.GetObjectWithIdentityTaskBase`2.InternalProcessRecord()
                                     at Microsoft.Exchange.Configuration.Tasks.GetRecipientObjectTask`2.InternalProcessRecord()
                                     at Microsoft.Exchange.Management.RecipientTasks.GetRecipientWithAddressListBase`2.InternalProcessRecord()
                                     at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
                                     at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    :
        Exception             :
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                                             at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl)
                                             at Microsoft.Exchange.Configuration.Tasks.GetObjectWithIdentityTaskBase`2.InternalProcessRecord()
                                             at Microsoft.Exchange.Configuration.Tasks.GetRecipientObjectTask`2.InternalProcessRecord()
                                             at Microsoft.Exchange.Management.RecipientTasks.GetRecipientWithAddressListBase`2.InternalProcessRecord()
                                             at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
                                             at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    :
                Exception             :
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                                                     at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl)
                                                     at Microsoft.Exchange.Configuration.Tasks.GetObjectWithIdentityTaskBase`2.InternalProcessRecord()
                                                     at Microsoft.Exchange.Configuration.Tasks.GetRecipientObjectTask`2.InternalProcessRecord()
                                                     at Microsoft.Exchange.Management.RecipientTasks.GetRecipientWithAddressListBase`2.InternalProcessRecord()
                                                     at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
                                                     at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    :
                        Exception             :
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because object 'x' couldn't be found on
'<ServerFQDN>'.
                                                             at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl)
                                                             at Microsoft.Exchange.Configuration.Tasks.GetObjectWithIdentityTaskBase`2.InternalProcessRecord()
                                                             at Microsoft.Exchange.Configuration.Tasks.GetRecipientObjectTask`2.InternalProcessRecord()
                                                             at Microsoft.Exchange.Management.RecipientTasks.GetRecipientWithAddressListBase`2.InternalProcessRecord()
                                                             at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
                                                             at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    :
                                Exception             :
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException: The operation couldn't be performed because object 'x' couldn't be found on
'<ServerFQDN>'.
                                                                     at Microsoft.Exchange.Configuration.Tasks.Task.ThrowError(Exception exception, ErrorCategory errorCategory, Object target, String helpUrl)
                                                                     at Microsoft.Exchange.Configuration.Tasks.GetObjectWithIdentityTaskBase`2.InternalProcessRecord()
                                                                     at Microsoft.Exchange.Configuration.Tasks.GetRecipientObjectTask`2.InternalProcessRecord()
                                                                     at Microsoft.Exchange.Management.RecipientTasks.GetRecipientWithAddressListBase`2.InternalProcessRecord()
                                                                     at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__91_1()
                                                                     at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                                    HResult                        : -2146233087
                                CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
                                FullyQualifiedErrorId : [Server=<ServerName>,RequestId=e538be6a-bee1-4906-9a9d-4f9b7297abc4,TimeStamp=13.06.2023 15:35:06] [FailureCategory=Cmdlet-ManagementObjectNotFoundException]
FB2EBAB0,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
                                ScriptStackTrace      : at <ScriptBlock><Process>, <No file>: line 101
                            Message                        : The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                            HResult                        : -2146233087
                        CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
                        FullyQualifiedErrorId : [Server=<ServerName>,RequestId=e538be6a-bee1-4906-9a9d-4f9b7297abc4,TimeStamp=13.06.2023 15:35:06] [FailureCategory=Cmdlet-ManagementObjectNotFoundException]
FB2EBAB0,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
                        ScriptStackTrace      : at <ScriptBlock><Process>, <No file>: line 101
                    Message                        : The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
                    HResult                        : -2146233087
                CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
                FullyQualifiedErrorId : [Server=<ServerName>,RequestId=e538be6a-bee1-4906-9a9d-4f9b7297abc4,TimeStamp=13.06.2023 15:35:06] [FailureCategory=Cmdlet-ManagementObjectNotFoundException]
FB2EBAB0,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
                ScriptStackTrace      : at <ScriptBlock><Process>, <No file>: line 101
            Message                        : The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
            HResult                        : -2146233087
        CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
        FullyQualifiedErrorId : [Server=<ServerName>,RequestId=e538be6a-bee1-4906-9a9d-4f9b7297abc4,TimeStamp=13.06.2023 15:35:06] [FailureCategory=Cmdlet-ManagementObjectNotFoundException]
FB2EBAB0,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
        ScriptStackTrace      : at <ScriptBlock><Process>, <No file>: line 101
    Message                        : The operation couldn't be performed because object 'x' couldn't be found on '<ServerFQDN>'.
    HResult                        : -2146233087
CategoryInfo          : NotSpecified: (:) [Get-Mailbox], ManagementObjectNotFoundException
FullyQualifiedErrorId : [Server=<ServerName>,RequestId=e538be6a-bee1-4906-9a9d-4f9b7297abc4,TimeStamp=13.06.2023 15:35:06] [FailureCategory=Cmdlet-ManagementObjectNotFoundException]
FB2EBAB0,Microsoft.Exchange.Management.RecipientTasks.GetMailbox
ScriptStackTrace      : at <ScriptBlock><Process>, <No file>: line 101
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tron2k** [comment]
In Powershell 7.4.0-preview.5 the problem still exists.

**Comment by tron2k** [comment]
I can no longer reproduce the problem in Powershell 7.4.
