### ISSUE TITLE
ProxyCommand generates invalid parameter for OrderedDictionary

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#19834]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Starting in PS 7.3, ProxyCommands generates invalid paramblock when command has a `[OrderedDictionary]`-parameter.

This bug was introduced in PS 7.3 due to https://github.com/PowerShell/PowerShell/pull/17804. After the PR, ProxyCommands use the type accelerator which is throws due to a parser check which was kept per https://github.com/PowerShell/PowerShell/issues/10513#issuecomment-1191947235.

Related https://github.com/pester/Pester/issues/2370

### Expected behavior

```console
# Define the function
function demoFunc {
    param (
        [System.Collections.Specialized.OrderedDictionary]
        $Param1
    )
}

> [System.Management.Automation.ProxyCommand]::GetParamBlock((Get-Command demoFunc))

    [System.Collections.Specialized.OrderedDictionary]
    ${Param1}
```

### Actual behavior

```console
# Windows PowerShell 5.1 & PowerShell < 7.3 = Valid
> [System.Management.Automation.ProxyCommand]::GetParamBlock((Get-Command demoFunc))

    [System.Collections.Specialized.OrderedDictionary]
    ${Param1}

# Generated in PowerShell 7.3+ = Invalid
> [System.Management.Automation.ProxyCommand]::GetParamBlock((Get-Command demoFunc))

    [ordered]
    ${Param1}
```

### Error details

```console
> [scriptblock]::Create("param($([System.Management.Automation.ProxyCommand]::GetParamBlock((Get-Command demoFunc))))")

Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Create" with "1" argument(s): "At line:2 char:5
                      +     [ordered]
                      +     ~~~~~~~~~
                      The ordered attribute can be specified only on a hash literal node."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParseException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 32
            HistoryId        : -1
            Line             : [scriptblock]::Create("param($([System.Management.Automation.ProxyCommand]::GetParamBloc
k((Get-Command demoFunc))))")
            PositionMessage  : At line:1 char:32
                               + … te("param($([System.Management.Automation.ProxyCommand]::GetParamBloc …
                               +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.3.4.
500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Create" with "1" argument(s): "At line:2 char:5
                     +     [ordered]
                     +     ~~~~~~~~~
                     The ordered attribute can be specified only on a hash literal node."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type        : System.Management.Automation.ParseException
        Errors      :
            Extent  : [ordered]
            ErrorId : OrderedAttributeOnlyOnHashLiteralNode
            Message : The ordered attribute can be specified only on a hash literal node.
        Message     : At line:2 char:5
                      +     [ordered]
                      +     ~~~~~~~~~
                      The ordered attribute can be specified only on a hash literal node.
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : At line:2 char:5
                          +     [ordered]
                          +     ~~~~~~~~~
                          The ordered attribute can be specified only on a hash literal node.
                HResult : -2146233087
            CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : OrderedAttributeOnlyOnHashLiteralNode
            InvocationInfo        :
                ScriptLineNumber : 2
                OffsetInLine     : 5
                HistoryId        : -1
                Line             : [ordered]

                PositionMessage  : At line:2 char:5
                                   +     [ordered]
                                   +     ~~~~~~~~~
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
        TargetSite  :
            Name          : Create
            DeclaringType : scriptblock
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Source      : System.Management.Automation
        HResult     : -2146233087
        StackTrace  :
   at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
   at CallSite.Target(Closure, CallSite, Type, String)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type ty
peToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure, CallSite, Type, String)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ParseException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 32
    HistoryId        : -1
    Line             : [scriptblock]::Create("param($([System.Management.Automation.ProxyCommand]::GetParamBlock((Get-C
ommand demoFunc))))")
    PositionMessage  : At line:1 char:32
                       + … te("param($([System.Management.Automation.ProxyCommand]::GetParamBloc …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fflaten** [comment]
I assume the decision to keep the parser check still holds.

The quick fix would be to simply skip the `ToStringCodeMethods.Type(...)` call [here](https://github.com/fflaten/PowerShell/blob/7057745c0a037ae5629e4f18d873e89721223992/src/System.Management.Automation/engine/TypeMetadata.cs#L864) for `[OrderedDictionary]` specifically since it's a very special case.

Is there anything besides ProxyCommands where this parser check might break the accelerator? If so it might be better to change it in `ToStringCodeMethods.Type(...)` or `TypeAccelerators.FindBuiltinAccelerator(..)`. Unfortunately I'm not familiar enough with the codebase.

**Comment by kborowinski** [comment]
Any progress on this?
