### ISSUE TITLE
$LASTEXITCODE does not get set for native commands in pipelines

### ISSUE THREAD

**Issue by j0le** [PowerShell/PowerShell#19848]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to get the exit code of a native command, but the variable $LASTEXITCODE is not set. This happens only, if I pipe the output of the native command to a cmdlet.

The stripped down script, to reproduce this, is:
```pwsh
Set-StrictMode -Version:'3.0'
$local:ErrorActionPreference = 'Stop'

# Using cmd.exe here is only an example. Could be any native command.
$firstLine = cmd.exe /c 'echo hello & echo world & exit 42' | Select-Object -First 1
$firstLine
"The exit code of cmd.exe is ${LASTEXITCODE}"
'end'
```
I give this script the name `temp.ps1`.
To run this script, I execute the following line in cmd.exe:
```
pwsh -NoProfile -File .\temp.ps1
```

### Expected behavior

```console
The expected output is:

hello
the exit code of cmd.exe is 42
end
```
```


### Actual behavior

```console
The actual output is:

hello
InvalidOperation: C:\Users\User\temp.ps1:7
Line |
   7 |  "The exit code of cmd.exe is ${LASTEXITCODE}"
     |                               ~~~~~~~~~~~~~~~
     | The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
```
```


### Error details

```console
Type        : System.Management.Automation.RuntimeException
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
        HResult : -2146233087
    TargetObject          : LASTEXITCODE
    CategoryInfo          : InvalidOperation: (LASTEXITCODE:String) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : VariableIsUndefined
    InvocationInfo        :
        ScriptLineNumber : 7
        OffsetInLine     : 30
        HistoryId        : -1
        ScriptName       : C:\Users\User\temp.ps1
        Line             : "The exit code of cmd.exe is ${LASTEXITCODE}"

        PositionMessage  : At C:\Users\User\temp.ps1:7 char:30
                           + "The exit code of cmd.exe is ${LASTEXITCODE}"
                           +                              ~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\Users\User
        PSCommandPath    : C:\Users\User\temp.ps1
        CommandOrigin    : Internal
    ScriptStackTrace      : at <ScriptBlock>, C:\Users\User\temp.ps1: line 7
                            at <ScriptBlock>, <No file>: line 1
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.3.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message     : The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
Data        : System.Collections.ListDictionaryInternal
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

and also

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> pwsh -NoProfile -File .\temp.ps1

Exit code of your script has to return `$LASTEXITCODE = 1` 

 Inside the script you have to catch the exception:

```
Set-StrictMode -Version:'3.0'
$local:ErrorActionPreference = 'Stop'

try { bash -c "exit 42" } catch { $LASTEXITCODE }
```

**Comment by j0le** [comment]
Hi @237dmitry!
Thanks for the quick answer!

Executing `cmd /c exit 42` or `bash -c "exit 42"` does not throw an error/exception that can be caught by try-catch.
But that is ok, because not for every program an exit code unequal zero signals an error. For some programs an exit code like 7 signals a successfuly run.

PowerShell doesn't terminate, when cmd.exe exits (that's ok), but when accessing the variable `$LASTEXITCODE`.

You can use `Get-Variable` to see, if LASTEXITCODE is set:

```pwsh
Set-StrictMode -Version:'3.0'
$local:ErrorActionPreference = 'Stop'

# LASTEXITCODE is not set, because a native command wasn't executed yet
Get-Variable -Name:LASTEXITCODE -ErrorAction:Continue



$firstLine = cmd.exe /c 'echo hello & echo world & exit 42' | Select-Object -First 1
$firstLine

# LASTEXITCODE should be set now, because a native command was executed, but it isn't
Get-Variable -Name:LASTEXITCODE -ErrorAction:Continue



cmd.exe /c 'echo hello & echo world & exit 42'

# LASTEXITCODE is finally set now
Get-Variable -Name:LASTEXITCODE -ErrorAction:Continue

'end'

```

**Comment by 237dmitry** [comment]
> Executing cmd /c exit 42 or bash -c "exit 42" does not throw an error/exception that can be caught by try-catch.

![lec](https://github.com/PowerShell/PowerShell/assets/78153320/6acb56b1-d1fb-4b3d-80e4-5a83f68bdf81)

**Comment by kasini3000** [comment]
I found inconsistencies between 7.3 and 7.4. 
This should be related to the implementation parameters.

**Comment by ninmonkey** [comment]
> 7.3 vs 7.4

New defaults change there. Check the values of your [`$PSNativeCommandErrorActionPreference`, `$PSNativeCommandUseErrorActionPreference `, `$ErrorActionPreference`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.4#psnativecommanduseerroractionpreference) 
the docs gives this example
```ps1
$definedPreference = $PSNativeCommandUseErrorActionPreference
$PSNativeCommandUseErrorActionPreference = $false
robocopy.exe D:\reports\operational "\\reporting\ops" CY2022Q4.md
$robocopyExitCode = $LASTEXITCODE
if ($robocopyExitCode -gt 8) {
    throw "robocopy failed with exit code $robocopyExitCode"
}
$PSNativeCommandUseErrorActionPreference = $definedPreference
```

**Comment by j0le** [comment]
Oh, that is interesting. I will try that tomorrow.

**Comment by j0le** [comment]
Yes, using the parentheses works. Thank you @SeeminglyScience!

I used these two command lines to test:
```pwsh
cmd.exe /c 'echo firstline & timeout /T 3 & echo secondline & echo to file > file.txt & echo to conout > CONOUT$ & echo to stderr 1>&2 & exit 7'  | Select-Object -First:1; $LASTEXITCODE

(cmd.exe /c 'echo firstline & timeout /T 3 & echo secondline & echo to file > file.txt & echo to conout > CONOUT$ & echo to stderr 1>&2 & exit 42')  | Select-Object -First:1; $LASTEXITCODE
```

But I have to correct you. You said:

> `Select-Object -First 1` stops upstream commands after they have output one item, so `cmd` never hits the `exit 42` part.

But `Select-Object -First 1` (and PowerShell) do not stop upstream commands. PowerShell just doesn't wait for the `cmd.exe` process to exit. Cmd is still able to write to a file or to the console via `CONOUT$` or the standard error stream. (To see what `CONOUT$` is, look in the documentation for [CreateFileA](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#consoles).)

I guess the difference between having parentheses and not having parentheses is as designed. But you PowerShell guys should know that.

When I think about it, bash and POSIX shells also cannot report the exit code of the first command in a pipeline.

```sh
#!/bin/sh
# "false" and "true" are programs defined in POSIX
# note: we only use one "|" character to make a pipeline, and not "||" for logical or.
false | true
echo $? # this should display "0"
```

But in bash we can use "pipefail".
```bash
#!/bin/bash
set -e
set -o pipefail

false | echo hello
echo world # at least "world" should not be displayed
```

**Comment by j0le** [comment]
I close this issue, because I see that the label "Issue-Question" was added. I interpret this to mean that the behaviour is as designed.
Thanks again for your help.
