### ISSUE TITLE
CommandCompletion CompleteInput : NullReferenceException

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#19912]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I develop an dotnet UI app with dotnet sdk 8.0.100-preview.5.23303.2
I am using the workaround for this SDK
```<RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />```

But when I migrate from **PowerShell 7.4.0-preview.3** to **7.4.0-preview.4**, I am experiencing a NullReference exception with the API System.Management.Automation.CommandCompletion.CompleteInput

### Expected behavior

```console
It works.
```

### Actual behavior

```console
It failed.
```

### Error details

```console
System.NullReferenceException: 'Object reference not set to an instance of an object.'
   at System.Management.Automation.CommandCompletion.CompleteInputImpl(Ast ast, Token[] tokens, IScriptPosition positionOfCursor, Hashtable options)
   at System.Management.Automation.CommandCompletion.CompleteInput(String input, Int32 cursorIndex, Hashtable options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
Thanks, I see a lot of changes with my name on it in preview 4 so it would be helpful if you could show what the the input text is when it throws.

**Comment by fMichaleczek** [comment]
@MartinGC94 Yes it's nothing ... or all ^^

So it's not related to my app (so not related to the thread UI hosting). 
You will found a C# example to reproduce the regression between 7.4.0.Preview3 et 7.4.0.Preview4

In my app, if I don't define a DefaultRunspace, CommandCompletion.CompleteInput failed with a message "no runspace available" and if I define it then I have a Null Reference exception.

I found a workaround with the TestCompletion4 method.

```powershell
Add-Type -TypeDefinition @'
using System;
using System.Collections;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

public static class Bug 
{
    public static dynamic TestCompletion1() 
    {
        return CommandCompletion.CompleteInput("Get-", 3, new Hashtable());
    }
    
    public static dynamic TestCompletion2() 
    {
       var iss = InitialSessionState.CreateDefault();
       var runspace = RunspaceFactory.CreateRunspace(iss);
       runspace.Open();
       return CommandCompletion.CompleteInput("Get-", 3, new Hashtable());
    }
    
    public static dynamic TestCompletion3() 
    {
       var iss = InitialSessionState.CreateDefault();
       var runspace = RunspaceFactory.CreateRunspace(iss);
       runspace.Open();
       Runspace.DefaultRunspace = runspace;
       return CommandCompletion.CompleteInput("Get-", 3, new Hashtable());
    }
    
    public static dynamic TestCompletion4() 
    {
       var iss = InitialSessionState.CreateDefault();
       var runspace = RunspaceFactory.CreateRunspace(iss);
       runspace.Open();
       Runspace.DefaultRunspace = runspace;
       var powerShell = PowerShell.Create();
       return CommandCompletion.CompleteInput("Get-", 3, new Hashtable(), powerShell);
    }
}
'@

[Bug]::TestCompletion1()
[Bug]::TestCompletion2()
[Bug]::TestCompletion3()
[Bug]::TestCompletion4()



```

7.4.0-Preview3 : 
![image](https://github.com/PowerShell/PowerShell/assets/6187529/6e3ed183-3dc0-440b-9371-6025f61a01a4)

7.4.0-Preview4 :
![image](https://github.com/PowerShell/PowerShell/assets/6187529/2caa1efc-13be-4d9b-8dd3-d070eddab9f5)
