### ISSUE TITLE
Invoke-WebRequest TLS alert: 'IllegalParameter' on WS2019stnd 1809 on "A" grade webservers

### ISSUE THREAD

**Issue by czuk** [PowerShell/PowerShell#19962]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Let me start by saying that I don't know if this is a Powershell issue or a webserver issue or an OS issue.  Certainly it only manifests for me on Windows Server 2019 1809 (17763.44.99) with Powershell 7.2.12 and 7.3.5 on webservers that score A on SSLLabs Server Test.

Example Code
`Invoke-WebRequest -Uri "https://cloud-images.ubuntu.com/releases/server/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"`

The example code works on the same WS2019 machine in Powershell Desktop 5.1 and also the URI works in Chrome on the same machine.  It also works on Windows 10 and Windows 11 on Powershell 7, unfortunately I don't currently have WS 2022 installed anywhere to test.  The PS version below is the LTS 7.2.15 version but the same issue is seen with 7.3.5.

### Expected behavior

```console
PS C:\Users\User> Invoke-WebRequest -UseBasicParsing -Uri "https://cloud-images.ubuntu.com/releases/server/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"

StatusCode        : 200
StatusDescription : OK
Content           : {81, 70, 73, 251…}
RawContent        : HTTP/1.1 200 OK
                    Date: Thu, 13 Jul 2023 13:09:38 GMT
                    Server: Apache/2.4.29
                    Server: (Ubuntu)
                    ETag: "28fa0000-600469954ac23"
                    Accept-Ranges: bytes
                    Last-Modified: Wed, 12 Jul 2023 09:11:20 GMT
                    Conte…
Headers           : {[Date, System.String[]], [Server, System.String[]], [ETag, System.String[]], [Accept-Ranges,
                    System.String[]]…}
RawContentLength  : 687472640
RelationLink      : {}
```

### Actual behavior

```console
PS C:\Users\user> Invoke-WebRequest -Uri "https://cloud-images.ubuntu.com/releases/server/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
Invoke-WebRequest: Authentication failed because the remote party sent a TLS alert: 'IllegalParameter'.
```

### Error details

```console
PS C:\Users\serveradmin> get-error

Exception             :
    Type           : System.Net.Http.HttpRequestException
    TargetSite     :
        Name          : MoveNext
        DeclaringType : System.Net.Http.ConnectHelper+<EstablishSslConnectionAsync>d__2, System.Net.Http,
Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.Net.Http.dll
    Message        : The SSL connection could not be established, see inner exception.
    InnerException :
        Type           : System.Security.Authentication.AuthenticationException
        TargetSite     :
            Name          : MoveNext
            DeclaringType : System.Net.Security.SslStream+<ForceAuthenticationAsync>d__175`1[TIOAdapter]
            MemberType    : Method
            Module        : System.Net.Security.dll
        Message        : Authentication failed because the remote party sent a TLS alert: 'IllegalParameter'.
        InnerException :
            Type            : System.ComponentModel.Win32Exception
            NativeErrorCode : -2146893018
            ErrorCode       : -2147467259
            Message         : The message received was unexpected or badly formatted.
            HResult         : -2147467259
        Source         : System.Net.Security
        HResult        : -2146233087
        StackTrace     :
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst,
Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions,
HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
    Source         : System.Net.Http
    HResult        : -2146233087
    StackTrace     :
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions,
HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken
cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async,
CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken
cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async,
CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean
async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken
cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption
completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request,
Boolean keepAuthorization)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : Method: GET, RequestUri:
'https://cloud-images.ubuntu.com/releases/server/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img', Version: 1.1,
Content: <null>, Headers:
                        {
                        User-Agent: Mozilla/5.0
                        User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.17763; en-GB)
                        User-Agent: PowerShell/7.2.12
                        }
CategoryInfo          : InvalidOperation: (Method: GET, Reques…owerShell/7.2.12
                        }:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : Authentication failed because the remote party sent a TLS alert: 'IllegalParameter'.
InvocationInfo        :
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 17
    Line             : Invoke-WebRequest -Uri
"https://cloud-images.ubuntu.com/releases/server/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    PositionMessage  : At line:1 char:1
                       + Invoke-WebRequest -Uri "https://cloud-images.ubuntu.com/releases/serv …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-WebRequest
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.12
PSEdition                      Core
GitCommitId                    7.2.12
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You could check with ` Invoke-WebRequest -SslProtocol Tls12`.

**Comment by czuk** [comment]
> You could check with ` Invoke-WebRequest -SslProtocol Tls12`.

Yep, that works ok, so must be something funny with the TLS1.3 negotiation?

**Comment by iSazonov** [comment]
Web cmdlets use OS defaults. I guess your OS has Tls 1.1 default.
