### ISSUE TITLE
fxdependent startup time is slow

### ISSUE THREAD

**Issue by 1268** [PowerShell/PowerShell#19983]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I recently moved from PowerShell 6.2.0 to 7.3.0, and I noticed a significant increase in the startup time. I figured it was due to the version change, but it seems it might also be due to which download I choose. For example, running this command:

~~~
Measure-Command { .\pwsh -noprofile -c exit }
~~~

I get these results:

milliseconds, best of 3 | version
------------------------|-------------------------
215                     | PowerShell-7.3.0-win-x64
222                     | PowerShell-7.3.0-win-x86
351                     | PowerShell-7.3.0-win-fxdependent
383                     | PowerShell-7.3.0-win-fxdependentWinDesktop

going from fastest to slowest, you experience a 78% increase in startup time. My test is rudimentary, so I would be interested if anyone has a better test, but the fxdependent versions to feel slower to me, especially coming from PowerShell 6.

### Expected behavior

```console
see above
```

### Actual behavior

```console
see above
```

### Environment data

```powershell
see above
```

**Comment by 1268** [comment]
looks like the issue remains on the current version as well:

milliseconds, best of 3 | version
------------------------|---------------------------------
213                     | PowerShell-7.3.6-win-x64
226                     | PowerShell-7.3.6-win-x86
364                     | PowerShell-7.3.6-win-fxdependent
379                     | PowerShell-7.3.6-win-fxdependentWinDesktop

**Comment by iSazonov** [comment]
What is you see for 7.4 Preview?

**Comment by 1268** [comment]
cant say:

PowerShell-7.4.0-preview.4-win-fxdependent:

~~~
Process terminated. The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSObject' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Management.Automation.PSObject..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.get_Properties()
   at System.Management.Automation.SemanticVersion.op_Implicit(SemanticVersion semver)
   at System.Management.Automation.PSVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSVersionInfo.get_PSVersion()
   at System.Management.Automation.PSSnapInReader.ReadRegistryInfo(Version& assemblyVersion, String& publicKeyToken, String& culture, String& applicationBase, Version& psVersion)
   at System.Management.Automation.PSSnapInReader.ReadCoreEngineSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCorePSSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
~~~

PowerShell-7.4.0-preview.4-win-fxdependentWinDesktop:

~~~
Process terminated. The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSVersionInfo' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSObject' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Management.Automation.PSObject..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.get_Properties()
   at System.Management.Automation.SemanticVersion.op_Implicit(SemanticVersion semver)
   at System.Management.Automation.PSVersionInfo..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSVersionInfo.get_PSVersion()
   at System.Management.Automation.PSSnapInReader.ReadRegistryInfo(Version& assemblyVersion, String& publicKeyToken, String& culture, String& applicationBase, Version& psVersion)
   at System.Management.Automation.PSSnapInReader.ReadCoreEngineSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCorePSSnapIn()
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
~~~

PowerShell-7.4.0-preview.4-win-x64:

Milliseconds      : 310

PowerShell-7.4.0-preview.4-win-x86:

Milliseconds      : 323

**Comment by flexdevguy** [comment]
Experiencing the Slow start in below version 
PowerShell 7.6.0
Loading personal and system profiles took 797ms. ( even more when any other local scripts are loading) 

$PROFILE
-----------
```ps1
# https://code.visualstudio.com/docs/terminal/shell-integration
#if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }
```

**Comment by groutoutlook** [comment]
> Experiencing the Slow start in below version PowerShell 7.6.0 Loading personal and system profiles took 797ms. ( even more when any other local scripts are loading)
> ```sh
> ## $PROFILE
> #if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }
> ```
it's not like that when you try to do 7.6.0-rc1 preview version .... really weird..
