### ISSUE TITLE
Start-Process does not work if used with "-Credential"

### ISSUE THREAD

**Issue by tps800** [PowerShell/PowerShell#20040]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Given the following code:
```
$cred = Get-Credential -Message "X" -User "some-admin-name"
Start-Process -FilePath "cmd.exe" -Credential $cred
```

will fail with `Start-Process: This command cannot be run due to the error: Der Benutzername oder das Kennwort ist falsch.`
Even if you can tell the username and password where correct. The very same will work using "runas.exe":
```
runas.exe /profile /env /user:some-admin-name "cmd.exe"
```

### Expected behavior

```console
$cred = Get-Credential -Message "X" -User "some-admin-name"
Start-Process -FilePath "cmd.exe" -Credential $cred
```
Starts an instance of cmd.exe running with admin-privileges.
```


### Actual behavior

```console
$cred = Get-Credential -Message "X" -User "some-admin-name"
Start-Process -FilePath "cmd.exe" -Credential $cred
```
Tells that user and or password are wrong. Even if they are not.
```


### Error details

```console
PowerShell 7.4:
Exception             :
    Type       : System.InvalidOperationException
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.4.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : This command cannot be run due to the error: Der Benutzername oder das Kennwort ist falsch.
    Source     : System.Management.Automation
    HResult    : -2146233079
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
InvocationInfo        :
    MyCommand        : Start-Process
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Start-Process -FilePath "cmd.exe" -Credential $cred
    Statement        : Start-Process -FilePath "cmd.exe" -Credential $cred
    PositionMessage  : At line:1 char:1
                       + Start-Process -FilePath "cmd.exe" -Credential $cred
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Start-Process
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1


PowerShell 7.3.6:
Exception             :
    Type       : System.InvalidOperationException
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.3.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : This command cannot be run due to the error: Der Benutzername oder das Kennwort ist falsch.
    Source     : System.Management.Automation
    HResult    : -2146233079
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
InvocationInfo        :
    MyCommand        : Start-Process
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Start-Process -FilePath "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -Credential $cred
    PositionMessage  : At line:1 char:1
                       + Start-Process -FilePath "C:\Windows\System32\WindowsPowerShell\v1.0\p …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Start-Process
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1


PowerShell 5.1:
Start-Process : Dieser Befehl kann aufgrund des folgenden Fehlers nicht ausgeführt werden: Der Benutzername oder das Kennwort ist falsch.
In Zeile:1 Zeichen:1
+ Start-Process -FilePath "powershell.exe" -Credential (Get-Credential  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

### Environment data

```powershell
PowerShell 7.4:
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PowerShell 7.3.6:
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Powershell 5.1:
Name                           Value
----                           -----
PSVersion                      5.1.17763.4644
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.4644
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Hmm... I cannot reproduce this, on any of the versions you mention.

However, there is a pitfall and a bug associated with `Start-Process -Credential`:

* Pitfall: You'll get a `The directory name is invalid` error if the target user is not permitted to access the caller's directory. (Either change to a suitable directory first or use `-WorkingDirectory`.

* Bug: Starting an _interactive_ shell session this way is currently broken:
  * #12129

In other words: If starting an _interactive_ `cmd.exe` session is your real use case, even solving the credentials problem won't help you - at least for now, though the fact that this bug dates back to Windows PowerShell and that the bug report here is 3+ years old doesn't bode well.

---

Just to rule out that the problem isn't a typo in the password, run `$cred.GetNetworkCredential().Password` after the credentials prompt to reveal its plain-text representation.

**Comment by tps800** [comment]
> Bug: Starting an interactive shell session this way is currently broken:

That is it. I've tried to start an interactive session this way. It does not seem to work regardless of what I start as long as it is in some way interactive. It will require some shell dance to have it done in this case (need some user interaction to install into the users account, while running elevated).

**Comment by mklement0** [comment]
I suggest closing this issue in favor of #12129 then.

Tu summarize the workarounds:

* Use `runas.exe`, as shown in the initial post.

* Launch the initial process hidden, non-interactively, and use it as an intermediary to launch an interactive session in a new, visible window; e.g.:

```powershell
Start-Process -WindowStyle Hidden -Credential someuser cmd '/c start cmd' -WorkingDirectory c:\somedir
```

Note that more work is needed if you want the target process to not only run as a different user, but also _with elevation_ - unfortunately, `-Verb RunAs` can _not_ be combined with `-Credential`.

**Comment by TobiasPSP** [comment]
Cmdlet Working Group is looking at #12129 now-ish, so I believe closing this issue makes sense. Thank you for reporting.
