### ISSUE TITLE
`Import-Module -Scope Local` in nested scripts removes the module from outer scripts

### ISSUE THREAD

**Issue by GamingMinds-UlfW** [PowerShell/PowerShell#20114]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using `Import-Module -Scope Local` in nested scripts, the module gets removed from the calling script after calling a script which also contains `Import-Module -Scope Local` for the same module.

`MyModule.psm1` contents:
```powershell
function Test-Something
{
    Write-Host "Test-Something called"
}
````

`OuterScript.ps1` contents:
```powershell
import-module -Scope Local -Force .\MyModule.psm1

Test-Something

.\InnerScript.ps1

Test-Something
```

`InnerScript.ps1` contents:
```powershell
import-module -Scope Local -Force .\MyModule.psm1

Write-Host "In InnerScript.ps1, module imported."
```

### Expected behavior

```console
PS D:\Source\Powershell\ImportModuleRepro> .\OuterScript.ps1
Test-Something called
In InnerScript.ps1, module imported.
Test-Something called
```

### Actual behavior

```console
PS D:\Source\Powershell\ImportModuleRepro> .\OuterScript.ps1
Test-Something called
In InnerScript.ps1, module imported.
Test-Something: D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1:7
Line |
   7 |  Test-Something
     |  ~~~~~~~~~~~~~~
     | The term 'Test-Something' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
```

### Error details

```console
PS D:\Source\Powershell\ImportModuleRepro> get-error

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'Test-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : Test-Something
        CategoryInfo          : ObjectNotFound: (Test-Something:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 7
            OffsetInLine     : 1
            HistoryId        : 9
            ScriptName       : D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1
            Line             : Test-Something
            PositionMessage  : At D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1:7 char:1
                               + Test-Something
                               + ~~~~~~~~~~~~~~
            PSScriptRoot     : D:\Source\Powershell\ImportModuleRepro
            PSCommandPath    : D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1
            InvocationName   : Test-Something
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1: line 7
                                at <ScriptBlock>, <No file>: line 1
    CommandName : Test-Something
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.3.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'Test-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin,
ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext
context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Test-Something
CategoryInfo          : ObjectNotFound: (Test-Something:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 7
    OffsetInLine     : 1
    HistoryId        : 9
    ScriptName       : D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1
    Line             : Test-Something
    PositionMessage  : At D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1:7 char:1
                       + Test-Something
                       + ~~~~~~~~~~~~~~
    PSScriptRoot     : D:\Source\Powershell\ImportModuleRepro
    PSCommandPath    : D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1
    InvocationName   : Test-Something
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, D:\Source\Powershell\ImportModuleRepro\OuterScript.ps1: line 7
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS D:\Source\Powershell\ImportModuleRepro> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by cmichaelingram** [comment]
I was able to reproduce this on PowerShell 7.3.6 as well as 5.1.  

The only workaround I've found so far is to Remove the -Force from on the Import-Module call in the InnerScript.ps1.

**Comment by GamingMinds-UlfW** [comment]
> I was able to reproduce this on PowerShell 7.3.6 as well as 5.1.
> 
> The only workaround I've found so far is to Remove the -Force from the Import-Module call in the InnerScript.ps1.

Yes, this sort of works around the issue, thanks for pointing this out! I forgot to mention that in my report. 

However when writing/debugging module code, I want to import new versions of the module code each time a script depending on the module runs. The problem is that the powershell session keeps the *"old"* module in its module list. Without `-Force`, it does not import the latest changes.
So either I do `Remove-Module` before starting a debug session, which is cumbersome, or use `-Force`, which does not work as expected.

As a side note, I find the whole module system of Powershell really overengineered and complicated. Writing a new module is a real pain. These days I usually just dot-source a script as *"module"* . I just stumbled upon this when changing some very old code from when I still thought using Powershell modules to keep things organized was a good idea, and felt the need to report this.

**Comment by cmichaelingram** [comment]
> > I was able to reproduce this on PowerShell 7.3.6 as well as 5.1.
> > The only workaround I've found so far is to Remove the -Force from the Import-Module call in the InnerScript.ps1.
> 
> Yes, this sort of works around the issue, thanks for pointing this out! I forgot to mention that in my report.
> 
> However when writing/debugging module code, I want to import new versions of the module code each time a script depending on the module runs. The problem is that the powershell session keeps the _"old"_ module in its module list. Without `-Force`, it does not import the latest changes. So either I do `Remove-Module` before starting a debug session, which is cumbersome, or use `-Force`, which does not work as expected.
> 
> As a side note, I find the whole module system of Powershell really overengineered and complicated. Writing a new module is a real pain. These days I usually just dot-source a script as _"module"_ . I just stumbled upon this when changing some very old code from when I still thought using Powershell modules to keep things organized was a good idea, and felt the need to report this.

I agree, the workaround would not work in your case as you would need to reload the module for the new changes to take effect.  I stumbled across this issue you reported as I was seeing something similar on one of our projects.

I did some further digging and there are similar issues reported such as this one, which is old but at least the team is aware of the problem: https://github.com/PowerShell/PowerShell/issues/2505
