### ISSUE TITLE
New-SelfSignedCertificate does not allow multiple KeyUsage

### ISSUE THREAD

**Issue by mikola-akbal** [PowerShell/PowerShell#20119]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run following:

```
$parameters =
@{
	Type = "Custom"
	Subject = "CN=Root Certificate Authority 2022"
	FriendlyName = "Root Certificate Authority 2022"
	KeyUsage = "CertSign,CRLSign,DigitalSignature"
	KeyUsageProperty = "All"
	KeyAlgorithm = "RSA"
	KeyLength = 2048
	HashAlgorithm = "SHA256"
	NotBefore = (Get-Date -Year 2022 -Month 01 -Day 01 -Hour 0 -Minute 0 -Second 0 -Millisecond 0)
	NotAfter  = (Get-Date -Year 2047 -Month 01 -Day 01 -Hour 0 -Minute 0 -Second 0 -Millisecond 0)
	CertStoreLocation = "Cert:\CurrentUser\My"
}

New-SelfSignedCertificate @parameters

```

### Expected behavior

```console
Creating of certificate
```

### Actual behavior

```console
New-SelfSignedCertificate: ...\New-SelfSignedCertificate.ps1:30
Line |
  30 |  New-SelfSignedCertificate @parameters
     |                            ~~~~~~~~~~~
     | Cannot bind parameter 'KeyUsage'. Cannot convert value "CertSign,CRLSign,DigitalSignature" to type
     | "Microsoft.CertificateServices.Commands.KeyUsage" due to enumeration values that are not valid. Specify one of
     | the following enumeration values and try again. The possible enumeration values are
     | "None;EncipherOnly;CRLSign;CertSign;KeyAgreement;DataEncipherment;KeyEncipherment;NonRepudiation;DigitalSignature;DecipherOnly".
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Cannot bind parameter 'KeyUsage'. Cannot convert value "CertSign,CRLSign,DigitalSignature" to type "Microsoft.CertificateServices.Co
mmands.KeyUsage" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration value
s are "None;EncipherOnly;CRLSign;CertSign;KeyAgreement;DataEncipherment;KeyEncipherment;NonRepudiation;DigitalSignature;DecipherOnly".
    ParameterName     : KeyUsage
    ParameterType     : Microsoft.CertificateServices.Commands.KeyUsage
    TypeSpecified     : string
    ErrorId           : CannotConvertArgumentNoMessage
    Line              : 30
    Offset            : 27
    CommandInvocation :
        MyCommand        : New-SelfSignedCertificate
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 7
            Keys     :
                Length : 4

                Length : 13

                Length : 7

                Length : 8

                Length : 12

                Length : 16

                Length : 17
            Values   :


                Length : 6

                Length : 44

                DisplayHint : DateTime
                DateTime    : 1 января 2047 г. 0:00:00
                Date        : 01/01/2047 00:00:00
                Day         : 1
                DayOfWeek   : Tuesday
                DayOfYear   : 1
                Kind        : Local
                Month       : 1
                Ticks       : 645655104000000000
                TimeOfDay   : 00:00:00
                Year        : 2047

                Length : 3

                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                    value__ : 16777215
                IsFixedSize : True
                Count       : 1

                Length : 20
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 7
                Keys     :
                    Length : 4

                    Length : 13

                    Length : 7

                    Length : 8

                    Length : 12

                    Length : 16

                    Length : 17
                Values   :


                    Length : 6

                    Length : 44

                    DisplayHint : DateTime
                    DateTime    : 1 января 2047 г. 0:00:00
                    Date        : 01/01/2047 00:00:00
                    Day         : 1
                    DayOfWeek   : Tuesday
                    DayOfYear   : 1
                    Kind        : Local
                    Month       : 1
                    Ticks       : 645655104000000000
                    TimeOfDay   : 00:00:00
                    Year        : 2047

                    Length : 3

                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                        value__ : 16777215
                    IsFixedSize : True
                    Count       : 1

                    Length : 20
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 7
                    Keys     :
                        Length : 4

                        Length : 13

                        Length : 7

                        Length : 8

                        Length : 12

                        Length : 16

                        Length : 17
                    Values   :


                        Length : 6

                        Length : 44

                        DisplayHint : DateTime
                        DateTime    : 1 января 2047 г. 0:00:00
                        Date        : 01/01/2047 00:00:00
                        Day         : 1
                        DayOfWeek   : Tuesday
                        DayOfYear   : 1
                        Kind        : Local
                        Month       : 1
                        Ticks       : 645655104000000000
                        TimeOfDay   : 00:00:00
                        Year        : 2047

                        Length : 3

                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                            value__ : 16777215
                        IsFixedSize : True
                        Count       : 1

                        Length : 20
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 7
                        Keys     :
                            Length : 4

                            Length : 13

                            Length : 7

                            Length : 8

                            Length : 12

                            Length : 16

                            Length : 17
                        Values   :


                            Length : 6

                            Length : 44

                            DisplayHint : DateTime
                            DateTime    : 1 января 2047 г. 0:00:00
                            Date        : 01/01/2047 00:00:00
                            Day         : 1
                            DayOfWeek   : Tuesday
                            DayOfYear   : 1
                            Kind        : Local
                            Month       : 1
                            Ticks       : 645655104000000000
                            TimeOfDay   : 00:00:00
                            Year        : 2047

                            Length : 3

                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                value__ : 16777215
                            IsFixedSize : True
                            Count       : 1

                            Length : 20
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 7
                            Keys     :
                                Length : 4

                                Length : 13

                                Length : 7

                                Length : 8

                                Length : 12

                                Length : 16

                                Length : 17
                            Values   :


                                Length : 6

                                Length : 44

                                DisplayHint : DateTime
                                DateTime    : 1 января 2047 г. 0:00:00
                                Date        : 01/01/2047 00:00:00
                                Day         : 1
                                DayOfWeek   : Tuesday
                                DayOfYear   : 1
                                Kind        : Local
                                Month       : 1
                                Ticks       : 645655104000000000
                                TimeOfDay   : 00:00:00
                                Year        : 2047

                                Length : 3

                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                    value__ : 16777215
                                IsFixedSize : True
                                Count       : 1

                                Length : 20
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 7
                                Keys     :
                                    Length : 4

                                    Length : 13

                                    Length : 7

                                    Length : 8

                                    Length : 12

                                    Length : 16

                                    Length : 17
                                Values   :


                                    Length : 6

                                    Length : 44

                                    DisplayHint : DateTime
                                    DateTime    : 1 января 2047 г. 0:00:00
                                    Date        : 01/01/2047 00:00:00
                                    Day         : 1
                                    DayOfWeek   : Tuesday
                                    DayOfYear   : 1
                                    Kind        : Local
                                    Month       : 1
                                    Ticks       : 645655104000000000
                                    TimeOfDay   : 00:00:00
                                    Year        : 2047

                                    Length : 3

                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1

                                    Length : 20
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 7
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 30
        OffsetInLine     : 1
        HistoryId        : 2
        ScriptName       : ...\Desktop\New-SelfSignedCertificate.ps1
        Line             : New-SelfSignedCertificate @parameters

        PositionMessage  : At ...\Desktop\New-SelfSignedCertificate.ps1:30 char:1
                           + New-SelfSignedCertificate @parameters
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : ...\Desktop
        PSCommandPath    : ...\Desktop\New-SelfSignedCertificate.ps1
        InvocationName   : New-SelfSignedCertificate
        PipelineLength   : 1
        PipelinePosition : 1
        CommandOrigin    : Internal
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind parameter 'KeyUsage'. Cannot convert value "CertSign,CRLSign,DigitalSignature" to type "Microsoft.CertificateServices.Comm
ands.KeyUsage" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values
are "None;EncipherOnly;CRLSign;CertSign;KeyAgreement;DataEncipherment;KeyEncipherment;NonRepudiation;DigitalSignature;DecipherOnly".
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [New-SelfSignedCertificate], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand
        InvocationInfo        :
            MyCommand        : New-SelfSignedCertificate
            ScriptLineNumber : 30
            OffsetInLine     : 27
            HistoryId        : 2
            ScriptName       : ...\Desktop\New-SelfSignedCertificate.ps1
            Line             : New-SelfSignedCertificate @parameters

            PositionMessage  : At ...\Desktop\New-SelfSignedCertificate.ps1:30 char:27
                               + New-SelfSignedCertificate @parameters
                               +                           ~~~~~~~~~~~
            PSScriptRoot     : ...\Desktop
            PSCommandPath    : ...\Desktop\New-SelfSignedCertificate.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, ...\Desktop\New-SelfSignedCertificate.ps1: line 30
                                at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : CoerceTypeAsNeeded
        DeclaringType : System.Management.Automation.ParameterBinderBase, System.Management.Automation, Version=7.3.6.500, Culture=neutral, PublicKeyToken=3
1bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type        : System.Management.Automation.PSInvalidCastException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "CertSign,CRLSign,DigitalSignature" to type "Microsoft.CertificateServices.Commands.KeyUsage" due to enumerat
ion values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "None;EncipherOnly;CRLSign
;CertSign;KeyAgreement;DataEncipherment;KeyEncipherment;NonRepudiation;DigitalSignature;DecipherOnly".
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : EnumParseUndefined
        TargetSite  :
            Name          : ThrowForUndefinedEnum
            DeclaringType : System.Management.Automation.LanguagePrimitives+EnumSingleTypeConverter, System.Management.Automation, Version=7.3.6.500, Cultur
e=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message     : Cannot convert value "CertSign,CRLSign,DigitalSignature" to type "Microsoft.CertificateServices.Commands.KeyUsage" due to enumeration
values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "None;EncipherOnly;CRLSign;Cer
tSign;KeyAgreement;DataEncipherment;KeyEncipherment;NonRepudiation;DigitalSignature;DecipherOnly".
        Source      : System.Management.Automation
        HResult     : -2147467262
        StackTrace  :
   at System.Management.Automation.LanguagePrimitives.EnumSingleTypeConverter.ThrowForUndefinedEnum(String errorId, Object enumValue, Object valueToUseToThr
ow, Type enumType)
   at System.Management.Automation.LanguagePrimitives.ConvertStringToEnum(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueT
oConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValu
eToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, T
ypeTable backupTypeTable)
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCol
lectionTypeInformation collectionTypeInfo, Object currentValue)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCol
lectionTypeInformation collectionTypeInfo, Object currentValue)
   at System.Management.Automation.ParameterBinderBase.EncodeCollection(CommandParameterInternal argument, String parameterName, ParameterCollectionTypeInfo
rmation collectionTypeInformation, Type toType, Object currentValue, Boolean coerceElementTypeIfNeeded, Boolean& coercionRequired)
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCol
lectionTypeInformation collectionTypeInfo, Object currentValue)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Paramet
erBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter
, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledComm
andParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompile
dCommandParameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[]
 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [New-SelfSignedCertificate], ParameterBindingException
FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand
InvocationInfo        :
    MyCommand        : New-SelfSignedCertificate
    ScriptLineNumber : 30
    OffsetInLine     : 27
    HistoryId        : 2
    ScriptName       : ...\Desktop\New-SelfSignedCertificate.ps1
    Line             : New-SelfSignedCertificate @parameters

    PositionMessage  : At ...\Desktop\New-SelfSignedCertificate.ps1:30 char:27
                       + New-SelfSignedCertificate @parameters
                       +                           ~~~~~~~~~~~
    PSScriptRoot     : ...\Desktop
    PSCommandPath    : ...\Desktop\New-SelfSignedCertificate.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, ...\Desktop\New-SelfSignedCertificate.ps1: line 30
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

If I open "Microsoft Root Certificate Authority 2010", I see multiple key usages. I see CertSign, CRLSign and DigitalSignature. But New-SelfSignedCertificate allows to supply **only one (!)** of key usages, not many. That restricts possibility of creating certificates.

**Comment by mikola-akbal** [comment]
I suspect that KeyUsage is an enumeration that allows at least partial combining of values. Like bit-fields. But New-SelfSignedCertificate does not allow to use multiple values.

**So, how to create certificate with multiple key usages??**

**Comment by mikola-akbal** [comment]
The suspicion is correct. Specification **allows** combining of KeyUsage values. It's restriction of cmdlet `New-SelfSignedCertificate`. Somebody wants to restrict creating of root certificates?

Repair it.

**Comment by jhoneill** [comment]
Your example asks for a single usage named "CertSign,CRLSign,DigitalSignature"   instead of 3 usages named  "CertSign", CRLSign" and "DigitalSignature" 

Change your line to  `KeyUsage = "CertSign","CRLSign","DigitalSignature" ` ( or if you want to really clear it's an array `@("CertSign","CRLSign","DigitalSignature")` ) and all should be good. 

BTW the command is in the PKI module supplied with Windows and not in the PowerShell language, so any real problems need to go Windows feedback.

**Comment by mikola-akbal** [comment]
> Change your line to `KeyUsage = "CertSign","CRLSign","DigitalSignature" ` 

Yes, it's my mistake. It solves. I think, you can close this issue.

Please, for clarity, add this line to examples.

**Comment by ehmiiz** [comment]
> > Change your line to `KeyUsage = "CertSign","CRLSign","DigitalSignature" `
> 
> Yes, it's my mistake. It solves. I think, you can close this issue.
> 
> Please, for clarity, add this line to examples.

I added a PR to the docs repository that hopefully solves this issue in the future.
