### ISSUE TITLE
Invoke-WebRequest / Invoke-RestMethod doesn't work with TLS 1.3

### ISSUE THREAD

**Issue by peetrike** [PowerShell/PowerShell#20587]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Invoke-WebRequest / Invoke-RestMethod have problems with connecting to web sites using TLS 1.3 protocol.  There is no error when connecting using TLS 1.2 protocol (using `-SslProtocol Tls12`).  Web browsers on same machine open web sites without any problem (and Developer Tools show that connection is using TLS 1.3).

### Expected behavior

```console
PS ❯ Invoke-WebRequest -Uri https://microsoft.com -SslProtocol Tls13

StatusCode        : 200
StatusDescription : OK
   . . .
```

### Actual behavior

```console
PS ❯ Invoke-WebRequest -Uri https://microsoft.com -SslProtocol Tls13
Invoke-WebRequest: The read operation failed, see inner exception.
```

### Error details

```console
Exception             :
    Type           : System.Net.Http.HttpRequestException
    TargetSite     :
        Name          : MoveNext
        DeclaringType : System.Net.Http.ConnectHelper+<EstablishSslConnectionAsync>d__2, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyTo
ken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.Net.Http.dll
    Message        : The SSL connection could not be established, see inner exception.
    InnerException :
        Type           : System.Security.Authentication.AuthenticationException
        TargetSite     :
            Name          : MoveNext
            DeclaringType : System.Net.Security.SslStream+<ForceAuthenticationAsync>d__146`1[TIOAdapter]
            MemberType    : Method
            Module        : System.Net.Security.dll
        Message        : Authentication failed, see inner exception.
        InnerException :
            Type            : System.ComponentModel.Win32Exception
            NativeErrorCode : -2146893052
            ErrorCode       : -2147467259
            Message         : The Local Security Authority cannot be contacted
            HResult         : -2147467259
        Source         : System.Net.Security
        HResult        : -2146233087
        StackTrace     :
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellat
ionToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, S
tream stream, CancellationToken cancellationToken)
    Source         : System.Net.Http
    HResult        : -2146233087
    StackTrace     :
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, S
tream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, Cancel
lationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts
, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : Method: GET, RequestUri: 'https://microsoft.com/', Version: 1.1, Content: <null>, Headers:
                        {
                        User-Agent: Mozilla/5.0
                        User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19045; et-EE)
                        User-Agent: PowerShell/7.3.9
                        }
CategoryInfo          : InvalidOperation: (Method: GET, Reques…PowerShell/7.3.9
                        }:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : Authentication failed, see inner exception.
InvocationInfo        :
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 16
    Line             : invoke-webRequest -Uri https://microsoft.com -SslProtocol Tls13
    PositionMessage  : At line:1 char:1
                       + invoke-webRequest -Uri https://microsoft.com -SslProtocol Tls13
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : invoke-webRequest
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Edge browser

![image](https://github.com/PowerShell/PowerShell/assets/34946805/177f6e0d-c1c5-4a24-a693-720a0b2a6960)

**Comment by peetrike** [comment]
hm, the same problem does not exist on Server 2022, with PowerShell v7.3.6

**Comment by UselessGuru** [comment]
Cannot reproduce on Win 11 client.
Tested with pwsh 7.3.8, 7.3.9 & 7.4-rc1

**Comment by yiya0802** [comment]
Hi peetrike, can you collect wireshark from both working server 2022 and none-working server? Can we have a quick review on the difference with them as i'm not able to repro issue on my server.

**Comment by jborean93** [comment]
The cmdlet uses the Windows C library for TLS operations. You need Windows 11 or Server 2022 or newer, any old versions will fail because TLS 1.3 is unavailable in Schannel. Edge and other programs might still be able to use TLS 1.3 but that’s because they use their own TLS library and not Schannel. PowerShell’s hands are tied to dotnet which is tied to Schannel on Windows.

**Comment by peetrike** [comment]
I was under impression that TLS 1.3 support was also released for Windows 10 v22H2.  If that's not true, then it's obivous why it fails.

**Comment by jborean93** [comment]
They had released it as a preview feature in the preview builds but I don’t think it ever made it to the official releases until Windows 11/Server 2022. The docs indicate only those versions https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp- and for 22H2 specifically https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-10-v22h2. Granted I have not tested this and maybe you just need to set the Schannel registry keys to enable it but ultimately that’s outside the realm of PowerShell here and it’s an OS configuration.

**Comment by peetrike** [comment]
I had SChannel registry key set.  The above error message is from that time.  When registry key was removed (restore default behaviour), then the inner exception message is:
```
The client and server cannot communicate, because they do not possess a common algorithm.
```
It seems that Windows 10 does not have TLS 1.3 support.
