### ISSUE TITLE
Crash with not elevated PowerShell runs.

### ISSUE THREAD

**Issue by emirefek** [PowerShell/PowerShell#20595]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I don't know how to reproduce that but I was installed Nvidia's CUDA toolkit and python 3.10.6 to my PC. I'm not sure these will cause the crash because I was installed same versions of them before wiping my PC couple months back.

I am able to run PowerShell with elevated admin access but when I try to run it normally with user level access it's getting crashed.

### Expected behavior

```console
PowerShell 7.3.9
PS C:\Users\emirefek>
```

### Actual behavior

```console
Process terminated. The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
 ---> System.ComponentModel.Win32Exception (126): Belirtilen modül bulunamadı.
   at System.Management.Automation.Internal.SecuritySupport.GetSaferPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.TestSaferPolicy(String testPathScript, String testPathModule)
   at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
   at System.Management.Automation.Runspaces.InitialSessionState..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[process exited with code 2148734499 (0x80131623)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### Error details

```console
Process terminated. The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
 ---> System.ComponentModel.Win32Exception (126): Belirtilen modül bulunamadı.
   at System.Management.Automation.Internal.SecuritySupport.GetSaferPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.TestSaferPolicy(String testPathScript, String testPathModule)
   at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
   at System.Management.Automation.Runspaces.InitialSessionState..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[process exited with code 2148734499 (0x80131623)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### Environment data

```powershell
PS C:\Users\emirefek> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

I got this response while running it as administrator because I can't run normally. I hope that helps.
```

**Comment by emirefek** [comment]
Sorry for Turkish output in shell error:
"Belirtilen modül bulunamadı" means, "Specified module not found."
` ---> System.ComponentModel.Win32Exception (126): Belirtilen modül bulunamadı.`

**Comment by SteveL-MSFT** [comment]
The stack looks like it's trying to call the https://learn.microsoft.com/en-us/windows/win32/api/winsafer/nf-winsafer-saferidentifylevel APIs.  The crash message is that a dll is not being found (even though it should just be part of Windows).  It would help to enable Fusion logging to see what exactly dlls are trying to be loaded.  See https://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net

**Comment by emirefek** [comment]
I didn't able to manage get logs. Btw I discovered, when I run powershell 7 normally it works but when I try to run it using new "Windows Terminal" application, it gives that error.

**Comment by emirefek** [comment]
Issue was related with Windows Terminal, it is fixed. Closing.
