### ISSUE TITLE
Set-Location -Path + fails because it mishandles the history (version 7.4.0)

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#20701]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I originally filed this bug under #14279, but today, the @microsoft-github-policy-service bot told me to verify it against the latest version and file it again! I tested the following on version 7.3.9. Just 12 minutes after I filed this issue, version 7.3.10 and 7.4.0 reached GA! So, I went back tested it on 7.4.0 too.

Open a PowerShell 7.1 window, navigate to a safe folder for experimentation, e.g., `D:\`, and enter the following commands:

```powershell
# Create a folder called '[Meta]'. Careful! '-Type Folder' doesn't work!
New-Item -Name '[Meta]' -Type Directory

# Output:
# 
#    Directory: D:\Desktop
#
# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# d----          2020-11-27    23:37                [Meta]
#

# Change the current folder to '[Meta]'
Set-Location -Path '.\`[Meta`]\'

# Alternatively, this:
Set-Location -LiteralPath '.\[Meta]\'

# Navigate back to "Desktop"
Set-Location -Path '-'

# Navigate forward to '[Meta]'
Set-Location -Path '+'
```

### Expected behavior

```console
PS D:\> Set-Location -Path '+'

PS D:\[Meta] >
```

### Actual behavior

```console
PS D:\> Set-Location -Path '+'

Set-Location: Cannot find path 'D:\[Meta]' because it does not exist.

PS D:\ >
```

### Error details

```plain
Exception             :
    Type                 : System.Management.Automation.ItemNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find path 'D:\[Meta]' because it does not exist.
            HResult : -2146233087
        TargetObject          : D:\[Meta]
        CategoryInfo          : ObjectNotFound: (D:\[Meta]:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PathNotFound
    ItemName             : D:\[Meta]
    SessionStateCategory : Drive
    TargetSite           :
        Name          : SetLocation
        DeclaringType : System.Management.Automation.SessionStateInternal, System.Management.Automation, Version=7.3.9.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find path 'D:\[Meta]' because it does not exist.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context, Boolean literalPath)
   at Microsoft.PowerShell.Commands.SetLocationCommand.ProcessRecord()
TargetObject          : D:\[Meta]
CategoryInfo          : ObjectNotFound: (D:\[Meta]:String) [Set-Location], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
InvocationInfo        :
    MyCommand        : Set-Location
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 9
    Line             : Set-Location -Path '+'
    PositionMessage  : At line:1 char:1
                       + Set-Location -Path '+'
                       + ~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Set-Location
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```plain
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by B-Art** [comment]
The problem her is that using '[' or ']' is messing things up.
'D:\[Meta]' is stored in history, but you can only use 'D:\\\`[Meta`]'

**Comment by Jaykul** [comment]
See also #14279

[SessionStateLocationAPIs.cs#L250-L265](https://github.com/PowerShell/PowerShell/blob/2502cc848066a6498297ea72bf643be9f831e406/src/System.Management.Automation/engine/SessionStateLocationAPIs.cs#L250-L265) needs to set `literalPath = true;` after it changes the value of `path` to a value from the history. Since those are always fully-qualified literal paths, right? (see [L268](https://github.com/PowerShell/PowerShell/blob/2502cc848066a6498297ea72bf643be9f831e406/src/System.Management.Automation/engine/SessionStateLocationAPIs.cs#L268) and [L836](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SessionStateLocationAPIs.cs#L836))

**Comment by iSazonov** [comment]
The SetLocation() method gets path as escaped string then we convert it to PathInfo and store the PathInfo in cache. With the PathInfo we lost the path escaping. So I think the fix is easy - after retrieving the path from the cache we should escape the path. Perhaps WilcardPatter.Escape() method can be used.

**Comment by iSazonov** [comment]
For reference #25282

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets discussed this.  We agree this is a bug that should be fixed.
