### ISSUE TITLE
Split-Path switches (-Leaf, -Parent, ...) do not work with -LiteralPath

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#20705]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Split-Path -Parent -LiteralPath $env:SystemRoot

### Expected behavior

```console
PS> Split-Path -Parent -LiteralPath $env:SystemRoot
C:\
```

### Actual behavior

```console
PS> Split-Path -Parent -LiteralPath $env:SystemRoot
Split-Path: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued
cannot be used together or an insufficient number of parameters were provided.
    ErrorId           : AmbiguousParameterSet
    Line              : 1
    Offset            : 1
    CommandInvocation :
        MyCommand        : Split-Path
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 2
            Keys     :
                Length : 6

                Length : 11
            Values   :
                IsPresent : True

                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                    Length : 10
                IsFixedSize : True
                Count       : 1
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 2
                Keys     :
                    Length : 6

                    Length : 11
                Values   :
                    IsPresent : True

                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                        Length : 10
                    IsFixedSize : True
                    Count       : 1
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 2
                    Keys     :
                        Length : 6

                        Length : 11
                    Values   :
                        IsPresent : True

                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                            Length : 10
                        IsFixedSize : True
                        Count       : 1
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 2
                        Keys     :
                            Length : 6

                            Length : 11
                        Values   :
                            IsPresent : True

                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                Length : 10
                            IsFixedSize : True
                            Count       : 1
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 2
                            Keys     :
                                Length : 6

                                Length : 11
                            Values   :
                                IsPresent : True

                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                    Length : 10
                                IsFixedSize : True
                                Count       : 1
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 2
                                Keys     :
                                    Length : 6

                                    Length : 11
                                Values   :
                                    IsPresent : True

                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 2
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 8
        Line             : Split-Path -Parent -LiteralPath $env:SystemRoot
        Statement        : Split-Path -Parent -LiteralPath $env:SystemRoot
        PositionMessage  : At line:1 char:1
                           + Split-Path -Parent -LiteralPath $env:SystemRoot
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Split-Path
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued
cannot be used together or an insufficient number of parameters were provided.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Split-Path], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.SplitPathCommand
        InvocationInfo        :
            MyCommand        : Split-Path
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 8
            Line             : Split-Path -Parent -LiteralPath $env:SystemRoot
            Statement        : Split-Path -Parent -LiteralPath $env:SystemRoot
            PositionMessage  : At line:1 char:1
                               + Split-Path -Parent -LiteralPath $env:SystemRoot
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : ThrowAmbiguousParameterSetException
        DeclaringType : System.Management.Automation.CmdletParameterBinderController, System.Management.Automation,
Version=7.4.0.101, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32 parameterSetFlags,
MergedCommandParameterMetadata bindableParameters)
   at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput, Boolean
setDefault)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Split-Path], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.SplitPathCommand
InvocationInfo        :
    MyCommand        : Split-Path
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 8
    Line             : Split-Path -Parent -LiteralPath $env:SystemRoot
    Statement        : Split-Path -Parent -LiteralPath $env:SystemRoot
    PositionMessage  : At line:1 char:1
                       + Split-Path -Parent -LiteralPath $env:SystemRoot
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-rc.1
PSEdition                      Core
GitCommitId                    7.4.0-rc.1
OS                             Microsoft Windows 10.0.25992
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![grafik](https://github.com/PowerShell/PowerShell/assets/25607767/ecd6d78e-73e6-467b-91da-0f3116e2ff65)

**Comment by jantari** [comment]
Originally reported by @mklement0 in https://github.com/PowerShell/PowerShell/issues/8751

> This issue has not had any activity in 6 months, if this is a bug please try to reproduce on the latest version of PowerShell and reopen a new issue and reference this issue if this is still a blocker for you.

**Yes this is still a blocker for me.**

**Comment by 237dmitry** [comment]
This is because the parameters must be in the parameter set in which they are specified. As you can see, `Parent` is not in the list of available options:

```powershell
$ (gcm Split-Path).ParameterSets.where{ $_.Name -eq 'LiteralPathSet' }.Parameters.Name
LiteralPath
Resolve
Credential
Verbose
Debug
ErrorAction
WarningAction
InformationAction
ProgressAction
ErrorVariable
WarningVariable
InformationVariable
OutVariable
OutBuffer
PipelineVariable
```

**Comment by mklement0** [comment]
Good to know the _technical reason_ for the bug, @237dmitry, but the point is that _it is a bug_: there is no conceivable reason _not_ to allow the combination of `-LiteralPath` with either `-Parent`  or `-Leaf`.

(As noted in the original issue (#8751), using `-Path` is a workaround, because `Split-Path` treats `-Path` and `-LiteralPath` arguments the same; also, for `-Parent` only, simply omitting it with `-LiteralPath` is an option, given that the `-Parent` functionality is the _default_ one, e.g. `Split-Path -LiteralPath $HOME`)

**Comment by 237dmitry** [comment]
> but the point is that it is a bug: there is no conceivable reason not to allow the combination of `-LiteralPath` with either `-Parent` or `-Leaf`

They are incompatible with each other due to the design of the cmdlet. Can this be considered a bug? Probably only from the point of view of what the authors meant by such sets of parameters. In my opinion this is rather a feature request.

**Comment by jantari** [comment]
Any bug can be considered "design" because it's always technically coded to behave that way. But if it makes no sense, goes against expectations, and there's no good reason for the behavior and it likely wasn't intended by the authors - then it becomes a bug.

**Comment by 237dmitry** [comment]
> Any bug can be considered "design"

No, because with proper syntax you won't get error.

**Comment by mklement0** [comment]
@237dmitry, what you're arguing about is a fruitless distraction (yes, you can _avoid_ the bug and choose to call it "proper syntax", using the circular argument that the current implementation is ipso facto by design).
If you _oppose the behavior this issue calls for_ - whatever you choose to label that call as - argue _that_.
If, by contrast, your concern is that the - legitimate - concern raised by this issue _will not be heard_ unless _properly classified_ - argue _that_.

**Comment by 237dmitry** [comment]
> argue that

- With proper syntax there are no errors.
- This is not a bug because you should read the docs & mans.

Ask the developers why they decided that `-LiteralPath` does not need to have the same functionality as `-Path`? Let them argue.

**Comment by mklement0** [comment]
* If there _is_ design intent, they will tell us - you don't know, and it is pointless to make yourself the defender of such speculative intent.
  * The syntax diagram in [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path) are generated _from the implementation_, and contain nothing  beyond that speaks to the intent that you speculate about.
* Even if there is, by all appearances, as _argued_, the cmdlet's behavior doesn't make sense (and is self-contradictory), so whether there was design intent is ultimately _irrelevant_ - unless someon can come up with a good _rationale_ for it; your circular reasoning does not constitute a rationale.
  * In the absence of a good rationale, the only other reason not to make a change would be the need to maintain backward compatibility, and that is _not_ a concern here.

**Comment by 237dmitry** [comment]
> In my opinion this is rather a feature request.

>> so whether there was design intent is ultimately irrelevant - unless someon can come up with a good rationale for it; your circular reasoning does not constitute a rationale.

What is your circular reasoning, is this a bug or bad design? I think this is the second.

And, what is for `-LiteralPath` in this cmdlet at all? This works correctly:

![sp](https://github.com/PowerShell/PowerShell/assets/78153320/c5871855-5481-4e14-92ab-4170776104c3)

**Comment by TobiasPSP** [comment]
Cmdlets should be intuitive to use. When there is no technical reason why a given parameter should not work in a specific parameterset, then adding it to the parameterset seems an easy fix. I‘ll take this issue to the cmdlet working group for discussion.

**Comment by mklement0** [comment]
Thank you, @TobiasPSP.

Let me point out two possible implementations of a fix:

* Remove the `-LiteralPath` parameter and simply make it an _alias_ of `-Path`, which it _in effect_ already is in the absence of switches such as`-Parent`.
   * There are two downsides, neither of which may be a problem in practice:
     * The syntax diagram will show only `-Path`
     * It'll be possible to combine `-LiteralPath` with `-Resolve`, which doesn't make sense - and ironically that _is currently also possible_; that could be documented as such.

* A proper fix would require fixing the `LiteralPathSet`  parameter set to include all switches _except_ `-Resolve` (though excluding the latter could hypothetically break existing, conceptually flawed code that combines these parameters).

**Comment by mklement0** [comment]
Thank you, @TobiasPSP.

The fix should indeed be simple; to spell it out: add all switches such as `-Parent` to the `LiteralPathSet` parameter set.

(I got myself confused earlier regarding the `-Resolve` switch: it resolves paths to _full_ paths, but (sensibly) supports _wildcards_ only with `-Path`, not also with `-LiteralPath`, so making `-LiteralPath` an _alias_ of `-Path` isn't an option, even though _without_ `-Resolve` it effectively is)

**Comment by 237dmitry** [comment]
> Cmdlets should be intuitive to use. When there is no technical reason why a given parameter should not work in a specific parameterset, then adding it to the parameterset seems an easy fix. I‘ll take this issue to the cmdlet working group for discussion.

I absolutely agree with you, thank you.

**Comment by mklement0** [comment]
Just to make sure that nothing is lost in translation, @237dmitry: @TobiasPSP's comment is aligned with what @jantari and I have been arguing, not your position. (If you've had a change of heart: great.)

---

> And, what is for `-LiteralPath` in this cmdlet at all?

My previous comment implies why `-LiteralPath` is still needed as a separate parameter (not just for symmetry with other cmdlets such as `Get-ChildItem`): it prevents (possibly accidental) wildcard expansion when combined with `-Resolve`, e.g. `Split-Path -Resolve -LiteralPath file[1].txt` would match a  file literally named `file[1].txt` (and resolve it to its full path and report that path's parent path), whereas `-Path` would not.

> What is your circular reasoning, is this a bug or bad design? 

The answer to this question is irrelevant, as argued.
By _circular reasoning_ I was referring to the logic of your arguments, which can be distilled to:
"Because it is that way it must be meant to be that way, otherwise it wouldn't be that way."

**Comment by 237dmitry** [comment]
> If you've had a change of heart: great.

No, I had not change my position:

- this is not an error, the error is the result of incorrect user command line syntax
- this is bad design, the user expects `-lp`, just like in other cmdlets
- the cmdlet should be improved, as written by Dr. Tobias Weltner.

> The answer to this question is irrelevant, as argued.
By circular reasoning I was referring to the logic of your arguments, which can be distilled to:
"Because it is that way, it must be meant to be that way, otherwise it wouldn't be that way."

A very strange answer. I expected to see your position not in relation to me, but on the essence of this issue

**Comment by jantari** [comment]
@mklement0 you have contributed many fantastic issues and discussions to PowerShell, but I don't think it's necessary to convince @237dmitry of your opinion here, what matters is that we can (finally) get it fixed.

Also, for both of yous information, when you submit a bug to this repository it explicitly states you can also do that for unexpected behavior:

![Screenshot_2023-11-18-11-40-23-232_org mozilla firefox-edit](https://github.com/PowerShell/PowerShell/assets/25607767/b8595268-fbee-4a3d-93b3-ee056568b32b)

So I think no matter how one defines "bug", we're good.

**Comment by 237dmitry** [comment]
> So I think no matter how one defines "bug", we're good here.

You can think as you want, this is your personal deal.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  -LiteralPath in all cases should work with the same set of parameters that -Path would accept (excluding some potential edge cases) as its intent is to allow an easier way to specify characters that shouldn't be interpreted.  The only concern is the complexity of untangling the parametersets to ensure no regression.  However, we agreed that the other switches should work with -LiteralPath

**Comment by jantari** [comment]
bump....

**Comment by jantari** [comment]
*activity*

Yes this is obviously still an issue.

**Comment by jantari** [comment]
_activity_
