### ISSUE TITLE
[System.IO.File]::WriteAllBytes raise a conversion exception

### ISSUE THREAD

**Issue by RickyVer77** [PowerShell/PowerShell#20720]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$NomeFile = "$HOME\InvoiceArchive\Customer\2023\Q1\CustomerInvoice.xml.p7m"
$DocFile = Invoke-RestMethod -Uri "$Global:DocEasyURI/api/DocumentoAttivo/$FileID/file" -Headers $Header -Method Get -ContentType 'application/json-patch+json'

[System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))

### Expected behavior

```console
Writing file: C:\Users\UserName\InvoiceArchive\Customer\2023\Q1\CustomerInvoice.xml.p7m... Completed.
```

### Actual behavior

```console
Cannot convert argument "bytes", with value: "System.Char[]", for "WriteAllBytes" to type "System.Byte[]"
```

### Error details

```console
Exception             : 
    Type           : System.Management.Automation.MethodException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert argument "bytes", with value: "System.Char[]", for "WriteAllBytes" to type "System.Byte[]": "Cannot convert value "€" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte.""
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
        InvocationInfo        : 
            ScriptLineNumber : 349
            OffsetInLine     : 4
            HistoryId        : 6
            ScriptName       : C:\Users\UserName\InvoiceArchive\DocEasy.ps1
            Line             : [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))
                               
            Statement        : [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))
            PositionMessage  : At C:\Users\UserName\InvoiceArchive\DocEasy.ps1:349 char:4
                               +             [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCh …
                               +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\UserName\InvoiceArchive
            PSCommandPath    : C:\Users\UserName\InvoiceArchive\DocEasy.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Write-DocEasyDocumento, C:\Users\UserName\InvoiceArchive\DocEasy.ps1: line 349
                                at Receive-DocEasyFaturePassive, C:\Users\UserName\InvoiceArchive\DocEasy.ps1: line 240
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : ConvertToArgumentConversionException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Cannot convert argument "bytes", with value: "System.Char[]", for "WriteAllBytes" to type "System.Byte[]": "Cannot convert value "€" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte.""
    InnerException : 
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "€" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte."
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidCastIConvertible
        TargetSite     : 
            Name          : ConvertIConvertible
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "€" to type "System.Byte". Error: "Value was either too large or too small for an unsigned byte."
        InnerException : 
            Type       : System.OverflowException
            TargetSite : 
                Name          : ThrowByteOverflowException
                DeclaringType : System.Convert
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : Value was either too large or too small for an unsigned byte.
            Source     : System.Private.CoreLib
            HResult    : -2146233066
            StackTrace : 
   at System.Convert.ThrowByteOverflowException()
   at System.Char.System.IConvertible.ToByte(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Management.Automation.LanguagePrimitives.ConvertIConvertible(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     : 
   at System.Management.Automation.LanguagePrimitives.ConvertIConvertible(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertUnrelatedArrays(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure, CallSite, Type, String, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.ConvertToArgumentConversionException(Exception exception, String parameterName, Object argument, String method, Type toType)
   at CallSite.Target(Closure, CallSite, Type, String, Object)
   at Write-DocEasyDocumento(Closure, FunctionContext)
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
InvocationInfo        : 
    ScriptLineNumber : 349
    OffsetInLine     : 4
    HistoryId        : 6
    ScriptName       : C:\Users\UserName\InvoiceArchive\DocEasy.ps1
    Line             : [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))
                       
    Statement        : [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))
    PositionMessage  : At C:\Users\UserName\InvoiceArchive\DocEasy.ps1:349 char:4
                       +             [System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCh …
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\UserName\InvoiceArchive
    PSCommandPath    : C:\Users\UserName\InvoiceArchive\DocEasy.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at Write-DocEasyDocumento, C:\Users\UserName\InvoiceArchive\DocEasy.ps1: line 349
                        at Receive-DocEasyFaturePassive, C:\Users\UserName\InvoiceArchive\DocEasy.ps1: line 240
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by RickyVer77** [comment]
Somethings was change in .NET?

**Comment by rhubarb-geek-nz** [comment]
Was this working before on a previous version?

```
[System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))
```

[WriteAllBytes](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writeallbytes?view=net-7.0) takes a byte array so rather than a char array you want an array of bytes, for JSON you may need to specify UTF-8 to convert the encoding.

The simplest may be to use [WriteAllText](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=net-7.0)

**Comment by RickyVer77** [comment]
Hi,

On previous version all work fine.
I couldn’t use WriteAllText because is a binary content

-Ricky-

Il giorno 18 nov 2023, alle ore 12:45, rhubarb-geek-nz ***@***.***> ha scritto:

﻿

Was this working before on a previous version?

[System.IO.File]::WriteAllBytes($NomeFile, ($DocFile.ToCharArray()))


WriteAllBytes<https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writeallbytes?view=net-7.0> takes a byte array so rather than a char array you want an array of bytes, for JSON you may need to specify UTF-8 to convert the encoding.

The simplest may be to use WriteAllText<https://learn.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=net-7.0>

**Comment by rhubarb-geek-nz** [comment]
> Hi, On previous version all work fine. I couldn’t use WriteAllText because is a binary content

JSON is text and you are using ToCharArray() which are effectively text as they depending on a character encoding.

**Comment by rhubarb-geek-nz** [comment]
I would expect the `-ContentType 'application/json-patch+json'` is redundant, as that refers to the body being sent, not the response.

**Comment by mklement0** [comment]
Good points, @rhubarb-geek-nz.

More generally, the cast from `[char[]]` to `[byte[]]`  fails with any Unicode character whose code point is outside the 8-bit range, i.e. higher than `255` (`0xFF`)

Expressed in .NET terms, this applies to any Unicode code unit encoded in the unsigned 16-bit value that constitutes a `[char]` instance with a value of `256` and above.

The code point of `€` (EURO SIGN, [`U+20AC`](http://www.fileformat.info/info/unicode/char/20ac)) is `0x20ac` == `8364` and therefore causes the error.

A minimal repro:

```powershell
[byte] [char] 'A'  # OK, the code point is 0x41 == 65 and therefore <= 255
[byte] [char] '€'  # !! FAILS, because the code point is 0x20ac == 8364 and therefore > 255
```

This behavior is as designed and has alway been in place - there has been no change there.

However, what _has_ changed  in v7.4 is the _default_ character encoding that `Invoke-WebRequest` / `Invoke-RestMethod` now assume: it is now UTF-8 (for `application/json`, specifically, it has been UTF-8 since 7.0 - I don't know how `application/json-patch+json` is handled in 7.3-).

Your approach looks like an old workaround for incorrectly decoded UTF-8 data because PowerShell used to use ISO-8859-1 (closely related to Windows-1252) as the default.

If so, then @rhubarb-geek-nz's recommendation to use `.WriteAllText` should indeed work, because `$DocFile` is now _correctly_ decoded.

**Comment by RickyVer77** [comment]
Thank you!
I understood my inaccuracies.
I solved this by removing the -ContentType parameter from Invoke-RestMethod and adding -OutFile. So I don't have to do conversions.

-Ricky-
