### ISSUE TITLE
7.4.0 Breaking change: Passing -OutFile $null to Invoke-WebRequest fails

### ISSUE THREAD

**Issue by nowakca** [PowerShell/PowerShell#20744]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Minimal version

```
Invoke-WebRequest "http://www.microsoft.com" -OutFile $null
```

Version that is more closely related to how that sneaks in as a surprise script breaker

```
function DoTheThing($file) {
  $Params=@{
    Uri="http://www.microsoft.com"
    OutFile=$file
    }
  Invoke-WebRequest @Params
}
```

### Expected behavior

```console
Should return the results of the web call to the output stream
```

### Actual behavior

```console
Invoke-WebRequest: Cannot validate argument on parameter 'OutFile'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

(Works correctly in 7.2.17 and 7.3.3)
```


### Error details

```console
Exception             : 
    Type              : System.Management.Automation.ParameterBindingValidationException
    Message           : Cannot validate argument on parameter 'OutFile'. The argument is null or empty. Provide an argument that is not null or empty, and then try t
he command again.
    ParameterName     : OutFile
    ParameterType     : string
    ErrorId           : ParameterArgumentValidationError
    Line              : 1
    Offset            : 46
    CommandInvocation : 
        MyCommand        : Invoke-WebRequest
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 35
        Line             : Invoke-WebRequest "http://www.microsoft.com" @h
        Statement        : Invoke-WebRequest "http://www.microsoft.com" @h
        PositionMessage  : At line:1 char:1
                           + Invoke-WebRequest "http://www.microsoft.com" @h
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Invoke-WebRequest
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot validate argument on parameter 'OutFile'. The argument is null or empty. Provide an argument that is not null or empty, and then try the
 command again.
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
        InvocationInfo        : 
            MyCommand        : Invoke-WebRequest
            ScriptLineNumber : 1
            OffsetInLine     : 46
            HistoryId        : 35
            Line             : Invoke-WebRequest "http://www.microsoft.com" @h
            Statement        : @h
            PositionMessage  : At line:1 char:46
                               + Invoke-WebRequest "http://www.microsoft.com" @h
                               +                                              ~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        : 
        Name          : BindParameter
        DeclaringType : System.Management.Automation.ParameterBinderBase, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad
364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    : 
        Type        : System.Management.Automation.ValidationMetadataException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
                HResult : -2146233087
            CategoryInfo          : MetadataError: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ArgumentIsNull
        TargetSite  : 
            Name          : Validate
            DeclaringType : System.Management.Automation.ValidateNotNullOrAttributeBase
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message     : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
        Source      : System.Management.Automation
        HResult     : -2146233087
        StackTrace  : 
   at System.Management.Automation.ValidateNotNullOrAttributeBase.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBinding
Flags flags)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        : 
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBinding
Flags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, Paramet
erBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParame
ter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandP
arameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElem
entAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
InvocationInfo        : 
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 46
    HistoryId        : 35
    Line             : Invoke-WebRequest "http://www.microsoft.com" @h
    Statement        : @h
    PositionMessage  : At line:1 char:46
                       + Invoke-WebRequest "http://www.microsoft.com" @h
                       +                                              ~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Red Hat Enterprise Linux 8.8 (Ootpa)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

No really necessary, literally just paste `Invoke-WebRequest "http://www.microsoft.com" -OutFile $null` into a shell and watch the error show up

**Comment by mklement0** [comment]
`Invoke-RestMethod` is affected too.

A breaking change is always unfortunate, and I don't know if this one was intentional or not, but it's worth noting that the original behavior is questionable:

* It treats `-OutFile $null` _as if the the `-OutFile` parameter hadn't been specified_ and therefore outputs the response to the success output stream.
* Arguably, it should only ever have done that if `-PassThru` is also specified (which is tantamount to specifying _neither_ `-OutFile` nor `-PassThru`).

---

The solution / workaround in the case of the given example function is to only add an `OutFile` entry to the splatting hashtable if `$file`  is non-`$null` / non-empty.

```powershell
function DoTheThing($file) {
  $Params=@{
    Uri = 'https://example.org'
  }
  if ($file) { $Params.OutFile = $file }
  Invoke-WebRequest @Params
}

DoTheThing
```

**Comment by iSazonov** [comment]
Came from https://github.com/PowerShell/PowerShell/pull/19044

Discussed in https://github.com/PowerShell/PowerShell/issues/19043

**Comment by mklement0** [comment]
Thanks, @iSazonov. I completely forgot about it and now see that I even actively suggested making this change - it hadn't occurred to me that someone would rely on the old behavior.

**Comment by nowakca** [comment]
@iSazonov Ah, thank you. That's the logic I expected once I saw the behavior. I see it mentioned on https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0-preview.2 . Sorry I didn't work the search well enough to find that before putting in the false alarm.

@mklement0 If you'd have asked me at the time, I wouldn't even have thought I was depending on it... the joys of a decade+ of code floating around. And yeah, the fix/workaround is pretty easy, assuming you can find all the places it may unexpectedly exist over that span of time. That's going to be "fun" to try to suss out.

So looks like I'm upgrading this system from 7.2 to 7.3 for now, and I'll have a separate project to try to find all the splats and see how they're used.

Thank you both!

**Comment by fbrosseau** [comment]
If anyone finds this issue because of Github Actions / Devops pipeline breaks as of today, it is because the hosted agents started consuming pwsh 7.4 today.

**Comment by Jaykul** [comment]
Yeah, this feels like one of those things where the fix is: don't do that.

I mean, that breaking changes should be documented in the change log (if it wasn't, already), but passing anything other than a valid _file_ path to `-OutFile` _should_ fail. ¯\_(ツ)_/¯
