### ISSUE TITLE
Breaking change: -Pr no longer works on Get-ADUser

### ISSUE THREAD

**Issue by ssg47** [PowerShell/PowerShell#20784]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Get-ADuser AB123456 -pr employeeid`
should list the user account properties including employeeID
but now generates an error:

It worked correctly in 7.3.9

### Expected behavior

```console
> Get-ADuser test0001 -pr employeeid

DistinguishedName : CN=Test0001,OU=TestUsers,DC=test,DC=local
EmployeeID        : 0000000001
Enabled           : True
GivenName         : Test
Name              : Test0001
ObjectClass       : user
ObjectGUID        : 123456aa-1234-abab-cdcd-ab1234cd5678
SamAccountName    : Test0001
SID               : S-1-5-21-23456789-1234567890-0987654321-12345
Surname           : 0001
UserPrincipalName : Test0001@test.local
```

### Actual behavior

```console
> Get-ADUser: Cannot bind parameter 'ProgressAction'. Cannot convert value "employeeid" to type "System.Management.Automation.ActionPreference". Error: "Unable to match the identifier name employeeid to a valid enumerator name. Specify one of the following enumerator names and try again:
> SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Cannot bind parameter 'ProgressAction'. Cannot convert value "employeeid" to type
"System.Management.Automation.ActionPreference". Error: "Unable to match the identifier name employeeid to a valid
enumerator name. Specify one of the following enumerator names and try again:
                        SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
    ParameterName     : ProgressAction
    ParameterType     : System.Management.Automation.ActionPreference
    TypeSpecified     : string
    ErrorId           : CannotConvertArgumentNoMessage
    Line              : 1
    Offset            : 25
    CommandInvocation :
        MyCommand        : Get-ADUser
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 27
        Line             : Get-ADuser test0001 -pr employeeid
        Statement        : Get-ADuser test0001 -pr employeeid
        PositionMessage  : At line:1 char:1
                           + Get-ADuser test0001 -pr employeeid
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Get-ADuser
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind parameter 'ProgressAction'. Cannot convert value "employeeid" to type
"System.Management.Automation.ActionPreference". Error: "Unable to match the identifier name employeeid to a valid
enumerator name. Specify one of the following enumerator names and try again:
                      SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Get-ADUser], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.ActiveDirectory.Management.Commands.GetADUser
        InvocationInfo        :
            MyCommand        : Get-ADUser
            ScriptLineNumber : 1
            OffsetInLine     : 25
            HistoryId        : 27
            Line             : Get-ADuser test0001 -pr employeeid
            Statement        : employeeid
            PositionMessage  : At line:1 char:25
                               + Get-ADuser test0001 -pr employeeid
                               +                         ~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : CoerceTypeAsNeeded
        DeclaringType : System.Management.Automation.ParameterBinderBase, System.Management.Automation,
Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "employeeid" to type "System.Management.Automation.ActionPreference".
Error: "Unable to match the identifier name employeeid to a valid enumerator name. Specify one of the following
enumerator names and try again:
                          SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : SubstringDisambiguationEnumParseThrewAnException
        TargetSite     :
            Name          : ConvertStringToEnum
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "employeeid" to type "System.Management.Automation.ActionPreference".
Error: "Unable to match the identifier name employeeid to a valid enumerator name. Specify one of the following
enumerator names and try again:
                         SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
        InnerException :
            Type        : System.Management.Automation.RuntimeException
            ErrorRecord :
                Exception             :
                    Type    : System.Management.Automation.ParentContainsErrorRecordException
                    Message : Unable to match the identifier name employeeid to a valid enumerator name. Specify one
of the following enumerator names and try again:
                              SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break
                    HResult : -2146233087
                CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
                FullyQualifiedErrorId : NoEnumNameMatch
            TargetSite  :
                Name          : EnumDisambiguate
                DeclaringType : System.Management.Automation.EnumMinimumDisambiguation, System.Management.Automation,
Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message     : Unable to match the identifier name employeeid to a valid enumerator name. Specify one of
the following enumerator names and try again:
                          SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break
            Source      : System.Management.Automation
            HResult     : -2146233087
            StackTrace  :
   at System.Management.Automation.EnumMinimumDisambiguation.EnumDisambiguate(String text, Type enumType)
   at System.Management.Automation.LanguagePrimitives.ConvertStringToEnum(Object valueToConvert, Type resultType,
Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertStringToEnum(Object valueToConvert, Type resultType,
Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean
recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String
parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String
parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument,
MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets,
CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets,
CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
   at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Get-ADUser], ParameterBindingException
FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.ActiveDirectory.Management.Commands.GetADUser
InvocationInfo        :
    MyCommand        : Get-ADUser
    ScriptLineNumber : 1
    OffsetInLine     : 25
    HistoryId        : 27
    Line             : Get-ADuser test0001 -pr employeeid
    Statement        : employeeid
    PositionMessage  : At line:1 char:25
                       + Get-ADuser test0001 -pr employeeid
                       +                         ~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Get-ADUser-pr_Error](https://github.com/PowerShell/PowerShell/assets/15728152/af8494ed-1813-4c97-b59e-4c4849b62227)

Also applies to Get-ADComputer, Get-ADGroup, Get-ADOrganizationalUnit, and, presumably, others.

**Comment by ALIENQuake** [comment]
Use full parameter name: `-Properties`

**Comment by jhoneill** [comment]
There is now a common parameter for progress.  Any shortening of a parameter to p, pr, pro, prog, etc will fail as a result. 

IIRC it was judged the upside of having the parameter outweighed the downside of breaking scripts which had (despite advice) used contractions of the name and peoples muscle memory that they could type (in this case) -pr. quick fix is to type `-pr[tab]` but unlearning use of some shortened names is going to painful for some people.

**Comment by mklement0** [comment]
To provide some more **context**:

* **PowerShell generally allows you to use only the *prefix* of a parameter name as long as that prefix _unambiguously_ identifies that parameter.** If two or more parameters share the same prefix - such as `-Properties` and `-ProgressAction` in your case sharing `-pr` - an error occurs by design.

* The ability to take such shortcuts is what PowerShell calls **_elastic syntax_**, and it is **intended for _interactive_ convenience** (on the command line). You should **avoid elastic syntax in _scripts_**, because such scripts may break in the future, if a command introduces a _new_ parameter that makes a previously unique name prefix no longer unique, or  - as in the new case at hand - a new [_common_ parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CommonParameters) is introduced.
  * As the name indicates, common parameters are implicitly supported by _all_ cmdlets (including advanced functions and scripts), so the likelihood of breaking existing uses of elastic syntax is higher.

  * While this is _primarily_ a problem with elastic syntax, it can at least hypothetically also affect other existing code, namely commands that collect any remaining arguments, such as [`Write-Output`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-output); e.g., `Write-Output -prog` worked fine up to v7.3.x and printed `-prog` verbatim; in v7.4+ it breaks now, because it is interpreted as an elastic-syntax attempt to reference the common `-ProgressAction` parameter (which fails syntactically, because this parameter requires an _argument_)

  * It is therefore somewhat unfortunate that common parameters themselves do not use a _reserved prefix_ (e.g, `-PS…`) to reduce the likelihood of name collisions. The same applies analogously to [_automatic variables_](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Automatic_Variables) - a [discussion about putting the latter into a dedicated namespace](https://github.com/PowerShell/PowerShell/issues/4216#issuecomment-315493182) never went anywhere, unfortunately.

* **Instances of code breaking due to the use of elastic syntax is _not_ considered a breaking change from PowerShell's perspective**, given that elastic syntax is designed for _interactive_ convenience only.

The **upshot** for **code that requires _long-term stability_** is:

* _Either_: Use **_full_ parameter names** (tab-completion helps), such as `-Properties` in the case at hand.

  * This not only avoids the problems with elastic syntax, but arguably more readable - if more verbose (see next point).

* _Or_: Use **short parameter _aliases_** - _if available_.

  * Note that such aliases - unlike ad hoc prefixes - _are_ part of the [breaking-change contract](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md). 
    * As an aside: not all such aliases are designed for _brevity_; other uses are: _synonyms_ (e.g.`-Last` for `-Tail`), for pipeline-binding by a differently named property (e.g. `-PSPath` for `-Literalpath`), or to cover both the singular plural forms of a name (e.g, `-Property` for `-Properties`).

  * For instance, `-lp` is an alias of `-LiteralPath` in [provider](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Providers) cmdlets such as [`Get-ChildItem`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem)

  * Unfortunately, only the _online_ help topics currently list these aliases (see #20787), but you can discover them _programmatically_ as follows, e.g. for `Get-Childitem`:

```powershell
(Get-Command -Name Get-ChildItem).ParameterSets.Parameters | 
  Where-Object Aliases |
  Sort-Object Name -Unique | 
  Select-Object Name, Aliases
```

**Comment by ssg47** [comment]
Thanks for the detailed explanation.

I've been using PowerShell since Monad and the ActiveDirectory module since it came into being and that's a lot of muscle memory to overcome.  I use tab completion in my scripts so I don't think you've broken anything there but I run some Get-ADxxxx command with -pr maybe 20 times per day so this is a non-trivial source of frustration.  And for something I can't see me ever needing.  I have many hundreds/thousand+ line scripts, some of which run interactively and others as scheduled tasks, and build one-liners everyday and I've never needed to care about the progress bar.  The easiest solution was to change the default profile in Terminal back to 5.1 because it's too much of a pain in the backside.

**Comment by mklement0** [comment]
@ssg47, I hear you.
As noted, it would have made sense for common parameters to have their own namespace, but that ship has sailed.

What is curious, however, is that built-in cmdlets that have `-Property` parameters too continue to select this parameter with `-p`, `-pr` and `-pro`, and that applies to custom advanced functions too:

```powershell
# These all work OK in v7.4.0
 & { [CmdletBinding()] param($Property) $Property } -p one
 & { [CmdletBinding()] param($Property) $Property } -pr two
 & { [CmdletBinding()] param($Property) $Property } -pro three
 ```

The usual elastic syntax kicks in with `-prog` (implies `-ProgressAction`).

So I wonder if explicit action was taken with respect to `-ProgressAction`, which then begs the question why it works differently with the AD cmdlets. (I have no background information, and I haven't looked at the source code.)

**Comment by mklement0** [comment]
Either way, there is a potential - albeit cumbersome and not future-proof - workaround: Create proxy (wrapper) functions for the AD cmdlets that pass everything through as is, but decorate the `$Property` parameter with `[Alias('pr')]`

**Comment by ssg47** [comment]
It has been more than six months and I am still making this mistake.  Multiple times.  Every.  Single.  Day.

So, to the people who made this decision: thank you.  From the bottom of my heart, for making every working day just a little bit worse, thank you.
