### ISSUE TITLE
New-PSSession fails with no supported WSMan client library was found v7.4.0 onwards.

### ISSUE THREAD

**Issue by miniagarwal0910** [PowerShell/PowerShell#20806]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a dotnet service running inside a container in which we are installing the latest Powershell core release (v7.4.0).
Now we are creating a pwsh process and creating a PSSession with a Remote Machine (WindowsServer)

The script we are executing to achieve this,
"$session = New-PSSession -ComputerName <Remote machine FQDN> -Authentication 'negotiate' -Credential $creds -SessionOption $so;" 

**v7.4.0 onwards** This is failing with "This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system."

This is working as expected for v7.3.9 or below.

### Expected behavior

```console
"$session = New-PSSession -ComputerName <Target machine FQDN> -Authentication 'negotiate' -Credential $creds -SessionOption $so;" should succeed without any error.
```

### Actual behavior

```console
"$session = New-PSSession -ComputerName <Target machine FQDN> -Authentication 'negotiate' -Credential $creds -SessionOption $so;" 

**v7.4.0 onwards** This is failing with "This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system."
```

### Error details

```console
This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Debian GNU/Linux 11 (bullseye)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
I have seen similar reports which look like a mismatch between versions of SSL libraries

[Ubuntu 20.4 Powershell - No supported WSMan client library was found](https://gist.github.com/agail/fe43e48288df2d98ac9cdc4fc5d80819)

Their solution was

```
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

The "postinst" for 7.4.0 debian package has

```
if [ -f /usr/lib/x86_64-linux-gnu/libssl.so.1.1 ] ; then
    ln -f -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /opt/microsoft/powershell/7/libssl.so.1.0.0
    ln -f -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /opt/microsoft/powershell/7/libcrypto.so.1.0.0
elif [ -f /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 ] ; then
    ln -f -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 /opt/microsoft/powershell/7/libssl.so.1.0.0
    ln -f -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /opt/microsoft/powershell/7/libcrypto.so.1.0.0
else
    ln -f -s /lib64/libssl.so.10 /opt/microsoft/powershell/7/libssl.so.1.0.0
    ln -f -s /lib64/libcrypto.so.10 /opt/microsoft/powershell/7/libcrypto.so.1.0.0
fi
```

So there the patching is done within the powershell directories itself.

How did you install powershell, by unpacking a tar or using a deb from microsoft.packages.com ?

**Comment by rhubarb-geek-nz** [comment]
My Ubuntu 22.04 box has

```
$ find /opt/microsoft/powershell -type l | xargs ls -ld
lrwxrwxrwx 1 root root 22 Nov 21 11:13 /opt/microsoft/powershell/7/libcrypto.so.1.0.0 -> /lib64/libcrypto.so.10
lrwxrwxrwx 1 root root 19 Nov 21 11:13 /opt/microsoft/powershell/7/libssl.so.1.0.0 -> /lib64/libssl.so.10
```

When comparing against those rules

```
$ pwsh --version
PowerShell 7.4.0
$ ls /usr/lib/x86_64-linux-gnu/libssl.so.1.1
ls: cannot access '/usr/lib/x86_64-linux-gnu/libssl.so.1.1': No such file or directory
$ ls /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
ls: cannot access '/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2': No such file or directory
```

What does exist is

```
$ ls -ld /usr/lib/x86_64-linux-gnu/libssl.so.*
-rw-r--r-- 1 root root 667864 Oct 13 12:02 /usr/lib/x86_64-linux-gnu/libssl.so.3
```

**Comment by rhubarb-geek-nz** [comment]
You could try setting the  [LD_DEBUG](https://man7.org/linux/man-pages/man8/ld.so.8.html) environment variable to see if it gives you better information on how it is failing.

**Comment by 237dmitry** [comment]
> My Ubuntu 22.04 box has

Not all distributed versions of pwsh have these libraries

```powershell

$ dir $pshome/lib*

    Directory: /opt/pwsh

UnixMode     Num   UID   GID      LastWriteTime    Size Name
--------     ---   ---   ---      -------------    ---- ----
-rwxr--r--   744     0     0   31.10.2023 17:48  804,3K libclrgc.so
-rwxr--r--   744     0     0   31.10.2023 17:51    3,5M libclrjit.so
-rwxr--r--   744     0     0   31.10.2023 17:49    6,6M libcoreclr.so
-rwxr--r--   744     0     0   31.10.2023 17:46  742,8K libcoreclrtraceptprovider.so
-rwxr--r--   744     0     0   31.10.2023 18:11  282,4K libhostfxr.so
-rwxr--r--   744     0     0   31.10.2023 18:11  303,1K libhostpolicy.so
-rwxr--r--   744     0     0   31.10.2023 17:49    2,3M libmscordaccore.so
-rwxr--r--   744     0     0   31.10.2023 17:49    1,6M libmscordbi.so
-rwxr--r--   744     0     0   01.11.2023 02:26   29,7K libpsl-native.so
-rwxr--r--   744     0     0   31.10.2023 17:52   59,2K libSystem.Globalization.Native.so
-rwxr--r--   744     0     0   31.10.2023 17:52  847,1K libSystem.IO.Compression.Native.so
-rwxr--r--   744     0     0   31.10.2023 17:46   14,1K libSystem.IO.Ports.Native.so
-rwxr--r--   744     0     0   31.10.2023 17:52   88,5K libSystem.Native.so
-rwxr--r--   744     0     0   31.10.2023 17:52   13,2K libSystem.Net.Security.Native.so
-rwxr--r--   744     0     0   31.10.2023 17:52  151,5K libSystem.Security.Cryptography.Native.OpenSsl.so

```

**Comment by MfMpEng** [comment]
Possibly related? My 7.4.1 PSsession crashes the entire terminal host upon connecting. 


saps pwsh 
$psversiontable 
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


enter-pssession {known-ps5-connectable-host}

Process terminated. Object reference not set to an instance of an object. 
    at system.environment.failfast(system.string, system.exception)
    at microsoft.powershell.unmanagedPSentry.start(system.string[], int32)
    at microsoft.powershell.managedPSentry.main(system.string[])
System.NullReferenceException: Object reference not set to an instance of an object.
    at system.management.automation.security.systemPolicy.LogWDACauditMessage(executionContext context, string title, string message, string fqid, Boolean dropIntoDebugger)
    at system.management.automation.remoting.runspaceref.parsePsCommandUsingScriptBlock(string line, nullable`1 useLocalScope)
    at system.management.automation.remoting.runspaceRef.CreatePipeline(string line, boolean addToHistory, boolean useNestedPipelines)
    at microsoft.powershell.executor.executecommandandgetresultasstring(string command, exception& exceptionThrown)
    at microsoft.powershell.consolehost.unputLoop.EvaluatePrompt()
    at microsoft.powershell.consolehost.inputloop.Run(Boolean inputLoopIsNested)
    at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
    at microsoft.powershell.consolehost.doRunspaceLoop(string initialCommand, boolean skipProfiles, Collection`1 initialCommandArgs, boolean ??staMode, String configurationName, String configurationFilePath)
    at Microsoft.PowerShell.ConsoleHost.Run(COmmandLineParameterParser cpp, Boolean insPrestartWarned)
    at Microsoft.PowerShell.ConsoleHost.Start(string bannerText, String helpText, Boolean issProvidedExternally)
    at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)

**Comment by rhubarb-geek-nz** [comment]
> Not all distributed versions of pwsh have these libraries

They are symbolic links created by the postrm script within the powershell deb install package, they are not part of any tar.

**Comment by AntonAntonyuk** [comment]
got same error with new pwsh 7.4.0 and 7.4.1 on ubuntu 20.04 
solution with :
    ln -f -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /opt/microsoft/powershell/7/libssl.so.1.0.0
    ln -f -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /opt/microsoft/powershell/7/libcrypto.so.1.0.0
this was on servers before and works as expected. with latest pwsh - doesn't work
 
for now as workaround pwsh was downgraded to version 7.3....

does anyone  found solution for pwsh 7.4...?

**Comment by adamkennedyasurion** [comment]
> Possibly related? My 7.4.1 PSsession crashes the entire terminal host upon connecting.
> 
> saps pwsh $psversiontable Name Value
> 
> PSVersion 7.4.1 PSEdition Core GitCommitId 7.4.1 OS Microsoft Windows 10.0.19045 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0
> 
> enter-pssession {known-ps5-connectable-host}
> 
> Process terminated. Object reference not set to an instance of an object. at system.environment.failfast(system.string, system.exception) at microsoft.powershell.unmanagedPSentry.start(system.string[], int32) at microsoft.powershell.managedPSentry.main(system.string[]) System.NullReferenceException: Object reference not set to an instance of an object. at system.management.automation.security.systemPolicy.LogWDACauditMessage(executionContext context, string title, string message, string fqid, Boolean dropIntoDebugger) at system.management.automation.remoting.runspaceref.parsePsCommandUsingScriptBlock(string line, nullable`1 useLocalScope) at system.management.automation.remoting.runspaceRef.CreatePipeline(string line, boolean addToHistory, boolean useNestedPipelines) at microsoft.powershell.executor.executecommandandgetresultasstring(string command, exception& exceptionThrown) at microsoft.powershell.consolehost.unputLoop.EvaluatePrompt() at microsoft.powershell.consolehost.inputloop.Run(Boolean inputLoopIsNested) at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt() at microsoft.powershell.consolehost.doRunspaceLoop(string initialCommand, boolean skipProfiles, Collection`1 initialCommandArgs, boolean ??staMode, String configurationName, String configurationFilePath) at Microsoft.PowerShell.ConsoleHost.Run(COmmandLineParameterParser cpp, Boolean insPrestartWarned) at Microsoft.PowerShell.ConsoleHost.Start(string bannerText, String helpText, Boolean issProvidedExternally) at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
> 
> ![image](https://private-user-images.githubusercontent.com/142014775/297490414-b06f7415-d86e-4c7a-b22d-dde3d74948da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzI4NjIsIm5iZiI6MTcwNzI3MjU2MiwicGF0aCI6Ii8xNDIwMTQ3NzUvMjk3NDkwNDE0LWIwNmY3NDE1LWQ4NmUtNGM3YS1iMjJkLWRkZTNkNzQ5NDhkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMjIyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2FjOTFmODA5ZjI0M2ZiYzA2M2I3MDJkYjE5ZWUzYTM1ZTVlNTNjNmMxYTJjMmEyOWM5Yjc5Nzk1NjNjNTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ppOloyBRFRlv1NfnC26JzLUvbFfoiv1Vr3lBlbs_V8)

Identical error message here on Windows 10 19045 and 7.4.1. I'm incredibly frustrated trying to figure it out. The kicker is that my other Windows 10 computers with 7.4.1 work fine with Enter-PSSession.

Issue is not present on 7.3.9 or 7.4.0

----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by HvyGun0331** [comment]
> Possibly related? My 7.4.1 PSsession crashes the entire terminal host upon connecting.
> 
> saps pwsh $psversiontable Name Value
> 
> PSVersion 7.4.1 PSEdition Core GitCommitId 7.4.1 OS Microsoft Windows 10.0.19045 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0
> 
> enter-pssession {known-ps5-connectable-host}
> 
> Process terminated. Object reference not set to an instance of an object. at system.environment.failfast(system.string, system.exception) at microsoft.powershell.unmanagedPSentry.start(system.string[], int32) at ...


Same issue since upgrading to 7.4.  Tried 7.4.1 and it produces the same result.  I rely on enter-pssession quite a lot and know this worked on 7.3.9.  So rolling back.  Until I found these posts, there was no other reference to the issue, so I assumed it was unique to my situation.  With more people experiencing the same issue, it may be a legit bug.

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by bedugan** [comment]
I have experienced this issue since upgrading to 7.4.1, although the error message seems slightly different. This occurs with Enter-PSSession or New-PSSession and crashes the `pwsh` process. PowerShell 5 on the same machine functions as expected.

`$psversiontable`

> Name                           Value
> ----                           -----
> PSVersion                      7.4.1
> PSEdition                      Core
> GitCommitId                    7.4.1
> OS                             Microsoft Windows 10.0.19045
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

`Enter-PSSession server-name`

> Process terminated. Object reference not set to an instance of an object.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Security.SystemPolicy.LogWDACAuditMessage(ExecutionContext context, String title, String message, Strin
g fqid, Boolean dropIntoDebugger)
   at System.Management.Automation.Remoting.RunspaceRef.ParsePsCommandUsingScriptBlock(String line, Nullable`1 useLocalScope)
   at System.Management.Automation.Remoting.RunspaceRef.CreatePipeline(String line, Boolean addToHistory, Boolean useNestedPipelines)
   at Microsoft.PowerShell.Executor.ExecuteCommandAndGetResultAsString(String command, Exception& exceptionThrown)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.EvaluatePrompt()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolea
n staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)

**Comment by MfMpEng** [comment]
> Possibly related? My 7.4.1 PSsession crashes the entire terminal host upon connecting.
> 
> saps pwsh $psversiontable Name Value
> 
> PSVersion 7.4.1 PSEdition Core GitCommitId 7.4.1 OS Microsoft Windows 10.0.19045 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0
> 
> enter-pssession {known-ps5-connectable-host}
> 
> Process terminated. Object reference not set to an instance of an object. at system.environment.failfast(system.string, system.exception) at microsoft.powershell.unmanagedPSentry.start(system.string[], int32) at microsoft.powershell.managedPSentry.main(system.string[]) System.NullReferenceException: Object reference not set to an instance of an object. at system.management.automation.security.systemPolicy.LogWDACauditMessage(executionContext context, string title, string message, string fqid, Boolean dropIntoDebugger) at system.management.automation.remoting.runspaceref.parsePsCommandUsingScriptBlock(string line, nullable`1 useLocalScope) at system.management.automation.remoting.runspaceRef.CreatePipeline(string line, boolean addToHistory, boolean useNestedPipelines) at microsoft.powershell.executor.executecommandandgetresultasstring(string command, exception& exceptionThrown) at microsoft.powershell.consolehost.unputLoop.EvaluatePrompt() at microsoft.powershell.consolehost.inputloop.Run(Boolean inputLoopIsNested) at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt() at microsoft.powershell.consolehost.doRunspaceLoop(string initialCommand, boolean skipProfiles, Collection`1 initialCommandArgs, boolean ??staMode, String configurationName, String configurationFilePath) at Microsoft.PowerShell.ConsoleHost.Run(COmmandLineParameterParser cpp, Boolean insPrestartWarned) at Microsoft.PowerShell.ConsoleHost.Start(string bannerText, String helpText, Boolean issProvidedExternally) at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
> 
> ![image](https://private-user-images.githubusercontent.com/142014775/297490414-b06f7415-d86e-4c7a-b22d-dde3d74948da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDQ3NjAsIm5iZiI6MTcxNTgwNDQ2MCwicGF0aCI6Ii8xNDIwMTQ3NzUvMjk3NDkwNDE0LWIwNmY3NDE1LWQ4NmUtNGM3YS1iMjJkLWRkZTNkNzQ5NDhkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQyMDIxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAxNmY1MzRlYzJkNTE1ODhmMmIzZDUyM2UzM2IxOTExMmRkODRjYWM4MTE4MmVlNzBiYTAwYmUxOTRkYjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sFl0681dz9HPNGxxEDtT7ol9TnKl-xQMyQmKV4PGGWQ)

Came back to report pwsh 7.4.2 has resolved my issues with psremoting causing complete pwsh crash. Close, fixed in update?

**Comment by Px-x64** [comment]
Still an issue on pwsh 7.4.5 and Ubuntu 22.04 LTS

**Comment by rhubarb-geek-nz** [comment]
[WSMan remoting isn't supported on non-Windows platforms](https://learn.microsoft.com/en-us/powershell/scripting/security/remoting/wsman-remoting-in-powershell?view=powershell-7.4#wsman-remoting-isnt-supported-on-non-windows-platforms)
