### ISSUE TITLE
Allow multiplying bools

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#20816]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'd expect multiplying bools to work as another way to do a logical and operation. Esp. because the logical or with "+" already works and when we start with int and multiply the int with bools also works. Just multiplying bools on their own or starting with a bool does not work. This is not just useful in shellgolf, but also to represent a mask or flags.

### Expected behavior

```console
PS> $a = $true
PS> $a *= $true
True
```

### Actual behavior

```console
PS> $a = $true
PS> $a *= $true
InvalidOperation: The operation '[System.Boolean] * [System.Boolean]' is not defined.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The operation '[System.Boolean] * [System.Boolean]' is not defined.
            HResult : -2146233087
        TargetObject          : True
        CategoryInfo          : InvalidOperation: (True:Boolean) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NotADefinedOperationForType
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $a *= $true
            PositionMessage  : At line:1 char:1
                               + $a *= $true
                               + ~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : ImplicitOp
        DeclaringType : System.Management.Automation.ParserOps, System.Management.Automation, Version=7.3.8.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The operation '[System.Boolean] * [System.Boolean]' is not defined.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.ParserOps.ImplicitOp(Object lval, Object rval, String op, IScriptExtent
errorPosition, String errorOp)
   at CallSite.Target(Closure, CallSite, Object, Boolean)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : True
CategoryInfo          : InvalidOperation: (True:Boolean) [], RuntimeException
FullyQualifiedErrorId : NotADefinedOperationForType
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $a *= $true
    PositionMessage  : At line:1 char:1
                       + $a *= $true
                       + ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
`[bool]` instances are consistently treated as `[int]` in _arithmetic_ operations - `$true` becomes `1`, `$false` becomes `0`, _except_ - surprisingly - in multiplication (`*`).

Therefore, to resolve this issue in a manner consistent with the  other operators, `*` should exhibit the same behavior, i.e., behave like `[int] $bool1 * [int] $bool2`; to spell it out:

```
$true * $true # -> 1 - same as: 1 * 1
$true * $false # -> 0 - same as: 1 * 0
$false * $true # -> 0 - same as: 0 * 1
$false * $false # -> 0 - same as: 0 * 0
```

**Comment by mklement0** [comment]
@agowa, I've opened a feature request to get `*` implemented for `[bool]` operands as outlined above:

* #20831

Unless you disagree with my analysis and my clarification in #20817 (now more completely fleshed out in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10688), I suggest closing both issues.

**Comment by kilasuit** [comment]
closing this in favour of #20831 as a duplicate as that issue is more fleshed out than this one
