### ISSUE TITLE
Get-WindowsPackage - PackageName - Now unrecoverable crash with wildcard character

### ISSUE THREAD

**Issue by alphacentauris44** [PowerShell/PowerShell#20858]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In the Windows 10 / 11 environment, when a wildcard character is used in the package name, typically *, an unrecoverable crash occurs.

As a workaround, all you have to do in the example is not specify the package parameter to obtain the same error-free result.

This applies to both online and offline modes.

To reproduce, run the command in administrator mode:

**Get-WindowsPackage -OnLine -PackageName ***

This problem has been detected for some versions (also tested in 7.3.8 to 7.4.0), and may be due to the element being called.

### Expected behavior

```console
Previously, specifying a wildcard / jocker would produce a corresponding result.

In the case of the example provided, the same result was obtained as by not providing the PackageName parameter.

This behavior should be restored, and certainly not a crash of this nature.
```

### Actual behavior

```console
Executing the command leads to a complete crash without powershell recovery.

I copy the recovered stack from the console window.
```

### Error details

```console
PS C:\Users\alpha> Get-WindowsPackage -OnLine -PackageName *
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.SpanHelpers.IndexOfNullCharacter(Char*)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   at Microsoft.Dism.Commands.ManagedHelper.PtrToStructure[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr)
   at Microsoft.Dism.Commands.BasicFeatureObject..ctor(IntPtr, System.String, System.String, Microsoft.Dism.Commands.LogLevel, System.String, Boolean, System.String, System.String)
   at Microsoft.Dism.Commands.AdvancedPackageObject..ctor(IntPtr, System.String, System.String, Microsoft.Dism.Commands.LogLevel, System.String, Boolean, System.String, System.String)
   at DynamicClass.InvokeStub_AdvancedPackageObject..ctor(System.Object, System.Span`1<System.Object>)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimeConstructorInfo.Invoke(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.ConstructorInfo.Invoke(System.Object[])
   at Microsoft.Dism.Commands.ManagedHelper.ConvertObject[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, UInt32, System.String, System.String, Microsoft.Dism.Commands.LogLevel, System.String, Boolean, System.String, System.String)
   at Microsoft.Dism.Commands.GetWindowsPackageCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

[processus terminé avec le code 3221225477 (0xc0000005)]
Vous pouvez maintenant fermer ce terminal avec Ctrl+D, ou appuyez sur Entrée pour redémarrer.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PS-7 4 0-Get-WindowsPackage-crash](https://github.com/PowerShell/PowerShell/assets/29732733/1dfae652-cb1e-405f-9f14-443b837f4a9b)

**Comment by mklement0** [comment]
Just a data point: I do not see the crash on my Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.2715) machine. Changing to culture `fr-FR` and a non-English display language didn't seem to make a difference.

I suggest targeting the packages one by one, to see if a specific one causes the crash:

```powershell
#requires -RunAsAdministrator

Get-WindowsPackage -Online | 
  % { $_.PackageName; $null = Get-WindowsPackage -Online -PackageName ($_.PackageName + '*') }
```

**Comment by alphacentauris44** [comment]
Before opening the incident to report, I made sure to correct the part of my scripts that was causing the problem, since they are used at least every time they are delivered, for every machine or VM.

As I only have Windows environments on Intel and AMD, and you haven't reproduced the case on ARM, it may be related.

I'll try to analyze the case when I've got a bit of time: submitting this incident took me a good two or three months ;)

I need to make sure of several things:
- Powershell origin.
- Environment origin (I'd recreate a VM from a version without a patch).
- Security patch.
- DSIM modification (this part I think I'd ignore)

**Comment by mklement0** [comment]
Thanks, @alphacentauris44. Did you run the code in my previous comment to see if a specific package is causing the crash?

**Comment by alphacentauris44** [comment]
Sorry, I forgot to do that :(

Indeed, I can see some module scrolling before the crash, but as the display is replaced by the application stack, I couldn't identify it.

I'll see about adding a pause before each module and I'll feckback.

**Comment by alphacentauris44** [comment]
This one : 
Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1

And if i entered only the package name, same thing 👍 
`Get-WindowsPackage -Online -PackageName Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1`

**Comment by alphacentauris44** [comment]
I this this too :

`PackageName  : Microsoft-Windows-FodMetadata-Package~31bf3856ad364e35~amd64~~10.0.22621.1
PackageState : Installed
ReleaseType  : FeaturePack
InstallTime  : 07/05/2022 10:25:00

PackageName  : Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1
PackageState : Installed
ReleaseType  : Foundation
InstallTime  : 07/05/2022 05:28:00`

**Comment by SteveL-MSFT** [comment]
This cmdlet is part of Windows and not part of PowerShell.  Please report any issues via the Windows Feedback tool.

**Comment by alphacentauris44** [comment]
This ok too.
