### ISSUE TITLE
Latest daily build of PS is crashing on start

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#20902]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

pwsh.exe daily build is crashing on start with following exception:
```powershell
Process terminated. The type initializer for 'Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.22.0.997, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.ApplicationInsights, Version=2.22.0.997, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry.SendPSCoreStartupTelemetry(String mode, Double parametersUsed) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\utils\Telemetry.cs:line 843
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 270
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.ConsoleHost\host\msh\ManagedEntrance.cs:line 86
```

### Expected behavior

```console
pwsh.exe should start
```

### Actual behavior

```console
Process terminated. The type initializer for 'Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.22.0.997, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.ApplicationInsights, Version=2.22.0.997, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry.SendPSCoreStartupTelemetry(String mode, Double parametersUsed) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\utils\Telemetry.cs:line 843
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 270
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc) in D:\DEVELOPMENT\PowerShellCore\src\Microsoft.PowerShell.ConsoleHost\host\msh\ManagedEntrance.cs:line 86
```

### Environment data

```powershell
N/A
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/16168755/de643869-bdbf-40f4-8536-feaef60f6468)

**Comment by StevenBucher98** [comment]
@kborowinski We can't seem to repro when building from source, where did you get the current build and any additional installation steps you can include?

**Comment by kborowinski** [comment]
@StevenBucher98 I'm building myself from the master. And this [PR](https://github.com/PowerShell/PowerShell/commit/ecbe1b9dcb69305dc7d188c860d182871895fda8) seems to break the build.

**Comment by iSazonov** [comment]
@kborowinski Could you please download and check daily build? Does it work well?

**Comment by iSazonov** [comment]
@kborowinski In OP you point "pwsh.exe daily build". Do you mean you download daily build from the repository or you build locally?

**Comment by kborowinski** [comment]
Local build from the latest master.

**Comment by iSazonov** [comment]
@kborowinski Thanks!  I see green icon for daily build in the repository so I guess you need clean your local build environment (for pwsh and nuget cache).

**Comment by kborowinski** [comment]
My bad that I called it a daily build. It's daily for me 😁

**Comment by StevenBucher98** [comment]
@iSazonov are you able to start a pwsh session from master? We were able to do so and not have it crash.

**Comment by iSazonov** [comment]
@StevenBucher98 I haven't problems with official daily build. We are waiting @kborowinski who have an issue with local build.

**Comment by kborowinski** [comment]
@iSazonov @StevenBucher98 I have no issues with the local build anymore. I'm closing this ticket.
