### ISSUE TITLE
AssemblyLoadContext that uses AssemblyDependencyResolver does not work with WinRM remoting

### ISSUE THREAD

**Issue by bording** [PowerShell/PowerShell#20909]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We have a [PowerShell module](https://www.powershellgallery.com/packages/Particular.ServiceControl.Management/5.0.0) that we ship for one of our products, and after running into some dependency conflicts, we followed the guidance in [this article](https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.4) to introduce an `AssemblyLoadContext` to isolate the dependencies.

This worked exactly as we hoped, so we shipped it. Shortly after we released it, we got a report from a customer that the new version of the module was not working when they used it from a remoting session.

After talking with the customer some more, I was able to reproduce the problem myself on my own machines. When using the module directly on the local machine, or when using SSH remoting, the module works properly. However, if WinRM remoting is used, cmdlets of the module fail to run with a 
type initialization error.

After asking here about [how to debug the module when remoting](https://github.com/orgs/PowerShell/discussions/20876), I was able to determine the underlying problem.

The [`AssemblyLoadContext`](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Management.PowerShell/InstallerEngineAssemblyLoadContext.cs) we created uses `AssemblyDependencyResolver`. When this type is used from the WinRM host, the following underlying error occurs:

```
Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
```

This appears to be coming from https://github.com/dotnet/runtime/blob/main/src/native/corehost/hostpolicy/hostpolicy.cpp#L905.

After realizing that the `AssemblyDependencyResolver` seemed to be source of the problem, I found that there are two other (closed) issues mentioning problems with `AssemblyDependencyResolver`: #11238 and #17492. These were both closed due to lack of activity.

Looking at both of those issues, I don't think either of them really capture the importance of fixing the WinRM host to enable `AssemblyDependencyResolver` to work.

The `AssemblyLoadContext` presented in the dependency conflicts article has a rather simple approach to finding assemblies, and it would not work properly for any dependencies that include platform-specific assets in a `runtimes` folder. To properly choose the correct assets in all cases, the `deps.json` file needs to be used. `AssemblyDependencyResolver` does this automatically for you.

It is quite common for NuGet packages to have `runtimes` assets. If you look at the content of our module, you'll see that we have a dependency on Microsoft.Data.SqlClient, and it has platform-specific assets in the `runtimes` folder. In fact, it has both IL assemblies and native binaries that need to be properly selected based on the platform.

If I can't rely on `AssemblyDependencyResolver` for this, I'm forced to handle this myself, so now I'm either writing my own `deps.json` parsing logic, or I'm hacking together something less robust.

Given that `AssemblyDependencyResolver` already works properly for 2 out of 3 scenarios (local an SSH) it really should work for all 3. 

---
Reproduction steps:
1. Establish a WinRM remote session (`New-PSSession| Enter-PSSession`)
2. `Install-Module Particular.ServiceControl.Management`
3. `Import-Module Particular.ServiceControl.Management`
4. `Get-ServiceControlInstances`

### Expected behavior

```console
`Get-ServiceControlInstances` executes without an error, and if there are no instances installed, it should complete with no output.
```

### Actual behavior

```console
Error from `Get-ServiceControlInstances`:

Error: Could not load file or assembly 'ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught exception during type initialization. (0x80131534)
```
```


### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    : 
    Exception             : 
        Type           : System.IO.FileLoadException
        Message        : Could not load file or assembly 'ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught exception during type initialization. (0x80131534)
        FileName       : ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null
        TargetSite     : 
            Name          : ProcessRecord
            DeclaringType : ServiceControl.Management.PowerShell.GetServiceControlInstances
            MemberType    : Method
            Module        : ServiceControl.Management.PowerShell.dll
        InnerException : 
            Type           : System.TypeInitializationException
            TypeName       : ServiceControl.Management.PowerShell.ModuleAssemblyInitializer
            TargetSite     : 
                Name          : Resolve
                DeclaringType : ServiceControl.Management.PowerShell.ModuleAssemblyInitializer
                MemberType    : Method
                Module        : ServiceControl.Management.PowerShell.dll
            Message        : The type initializer for 'ServiceControl.Management.PowerShell.ModuleAssemblyInitializer' threw an exception.
            InnerException : 
                Type       : System.InvalidOperationException
                TargetSite : Void .ctor(System.String)
                Message    : Dependency resolution failed for component C:\Users\Brandon\Documents\PowerShell\Modules\Particular.ServiceControl.Management\5.0.0\InstallerEngine\ServiceControlInstaller.Engine.dll with error code -2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
                             
                Source     : System.Private.CoreLib
                HResult    : -2146233079
                StackTrace : 
   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at ServiceControl.Management.PowerShell.InstallerEngineAssemblyLoadContext..ctor() in /_/src/ServiceControl.Management.PowerShell/InstallerEngineAssemblyLoadContext.cs:line 17
   at ServiceControl.Management.PowerShell.ModuleAssemblyInitializer..cctor() in /_/src/ServiceControl.Management.PowerShell/ModuleAssemblyInitializer.cs:line 9
            Source         : ServiceControl.Management.PowerShell
            HResult        : -2146233036
            StackTrace     : 
   at ServiceControl.Management.PowerShell.ModuleAssemblyInitializer.Resolve(AssemblyLoadContext defaultLoadContext, AssemblyName assemblyName) in /_/src/ServiceControl.Management.PowerShell/ModuleAssemblyInitializer.cs:line 15
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
        Source         : ServiceControl.Management.PowerShell
        HResult        : -2146233036
        StackTrace     : 
   at ServiceControl.Management.PowerShell.GetServiceControlInstances.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    CategoryInfo          : NotSpecified: (:) [Get-ServiceControlInstances], FileLoadException
    FullyQualifiedErrorId : System.IO.FileLoadException,ServiceControl.Management.PowerShell.GetServiceControlInstances
    InvocationInfo        : 
        MyCommand       : Get-ServiceControlInstances
        HistoryId       : 3
        InvocationName  : sc-instances
        CommandOrigin   : Internal
    PipelineIterationInfo : 





TargetSite     : 
    Name          : Throw
    DeclaringType : System.Runtime.ExceptionServices.ExceptionDispatchInfo
    MemberType    : Method
    Module        : System.Private.CoreLib.dll
Message        : Could not load file or assembly 'ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught exception during type initialization. (0x80131534)
InnerException : 
    Type           : System.IO.FileLoadException
    Message        : Could not load file or assembly 'ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'. Uncaught exception during type initialization. (0x80131534)
    FileName       : ServiceControlInstaller.Engine, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null
    TargetSite     : 
        Name          : ProcessRecord
        DeclaringType : ServiceControl.Management.PowerShell.GetServiceControlInstances
        MemberType    : Method
        Module        : ServiceControl.Management.PowerShell.dll
    InnerException : 
        Type           : System.TypeInitializationException
        TypeName       : ServiceControl.Management.PowerShell.ModuleAssemblyInitializer
        TargetSite     : 
            Name          : Resolve
            DeclaringType : ServiceControl.Management.PowerShell.ModuleAssemblyInitializer
            MemberType    : Method
            Module        : ServiceControl.Management.PowerShell.dll
        Message        : The type initializer for 'ServiceControl.Management.PowerShell.ModuleAssemblyInitializer' threw an exception.
        InnerException : 
            Type       : System.InvalidOperationException
            TargetSite : Void .ctor(System.String)
            Message    : Dependency resolution failed for component C:\Users\Brandon\Documents\PowerShell\Modules\Particular.ServiceControl.Management\5.0.0\InstallerEngine\ServiceControlInstaller.Engine.dll with error code -2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
                         
            Source     : System.Private.CoreLib
            HResult    : -2146233079
            StackTrace : 
   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at ServiceControl.Management.PowerShell.InstallerEngineAssemblyLoadContext..ctor() in /_/src/ServiceControl.Management.PowerShell/InstallerEngineAssemblyLoadContext.cs:line 17
   at ServiceControl.Management.PowerShell.ModuleAssemblyInitializer..cctor() in /_/src/ServiceControl.Management.PowerShell/ModuleAssemblyInitializer.cs:line 9
        Source         : ServiceControl.Management.PowerShell
        HResult        : -2146233036
        StackTrace     : 
   at ServiceControl.Management.PowerShell.ModuleAssemblyInitializer.Resolve(AssemblyLoadContext defaultLoadContext, AssemblyName assemblyName) in /_/src/ServiceControl.Management.PowerShell/ModuleAssemblyInitializer.cs:line 15
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
    Source         : ServiceControl.Management.PowerShell
    HResult        : -2146233036
    StackTrace     : 
   at ServiceControl.Management.PowerShell.GetServiceControlInstances.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Source         : System.Private.CoreLib
HResult        : -2146233087
StackTrace     : 
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Same for both machines involved in remoting sessions
```

**Comment by rhubarb-geek-nz** [comment]
[This may be related](https://github.com/PowerShell/PowerShell/issues/20740)

Here the loading of the modules either works or not depending on how PowerShell is invoked. If run interactive, they work, if launched with a script as a command line option they don't.

**Comment by mattcargile** [comment]
FYI, https://github.com/Particular/ServiceControl/pull/3896 appears to be the workaround.
