### ISSUE TITLE
Group-Object: StringBuilder parses value as format string

### ISSUE THREAD

**Issue by chrisdent-de** [PowerShell/PowerShell#20914]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Group-Object` in PowerShell 7.3.10 and below is able to group strings containing `{` and `}` characters.

In PowerShell 7.4 this fails.

### Expected behavior

```console
PS> '}' | Group-Object

Count  Name    Group
-----  ----    -----
    1  }       {}}
```

### Actual behavior

```console
PS> '}' | Group-Object
Group-Object: Input string was not in a correct format. Failure to parse near offset 1. Unexpected closing brace without a corresponding opening brace.
```

### Error details

```console
Exception             :
    Type       : System.FormatException
    TargetSite :
        Name          : ThrowFormatInvalidString
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Input string was not in a correct format. Failure to parse near offset 1. Unexpected closing brace without a corresponding opening brace.
    Source     : System.Private.CoreLib
    HResult    : -2146233033
    StackTrace :
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at Microsoft.PowerShell.Commands.GroupInfo.BuildName(List`1 propValues)
   at Microsoft.PowerShell.Commands.GroupObjectCommand.DoOrderedGrouping(OrderByPropertyEntry currentObjectEntry, Boolean noElement, List`1 groups, Dictionary`2 groupInfoDictionary, OrderByPropertyComparer
orderByPropertyComparer)
   at Microsoft.PowerShell.Commands.GroupObjectCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [Group-Object], FormatException
FullyQualifiedErrorId : System.FormatException,Microsoft.PowerShell.Commands.GroupObjectCommand
InvocationInfo        :
    MyCommand        : Group-Object
    ScriptLineNumber : 1
    OffsetInLine     : 7
    HistoryId        : 54
    Line             : '}' | Group-Object
    Statement        : Group-Object
    PositionMessage  : At line:1 char:7
                       + '}' | Group-Object
                       +       ~~~~~~~~~~~~
    InvocationName   : Group-Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chrisdent-de** [comment]
Closing, fixed in preview.

**Comment by mklement0** [comment]
This was previously reported in #20711 and fixed in PR #20745 on Nov 21.

However, it is unclear to me when the fix will land - at least for now, it looks like it will _not_ be in v7.4.1, because there is no "Backport" label to that effect.

Note that while the bug is indeed not present in PowerShell 7.4.0-rc.1, for instance, this preview version _predates_ v7.4.0.

As noted in https://github.com/PowerShell/PowerShell/issues/20895#issuecomment-1850570161, it is unfortunate that bug reports are instantly closed when a PR is merged, with no obvious way to tell when they will land, and with the potential for duplicate reports - such as in this case - in the period between when the PR is merged and when the fix actually lands, due to users not expecting to have to check among _closed_ reports.
