### ISSUE TITLE
Receive-Job hangs if job uses Read-Host

### ISSUE THREAD

**Issue by per-oestergaard** [PowerShell/PowerShell#20946]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```Powershell
$job=Start-Job {Read-Host 'something: '}
Receive-Job $job
```
or alternatively provoking an error
```Powershell
$job=Start-Job {Read-Host 'something: '}
Receive-Job $job -keep
Receive-Job $job -keep
```

### Expected behavior

```console
I expect Read-Host to either throw an error or return with blank input as stdin is non-existent. I would never expect Receive-Job to be hanging at the prompt as it should only return the job output ready for the moment it is executed.
```

### Actual behavior

```console
PS> $job=Start-Job {Read-Host 'something'}
PS> Receive-Job $job
something:

or

PS> $job=Start-Job {Read-Host 'something'}
PS> Receive-Job $job -Keep
something:
PS> Receive-Job $job -Keep
something:
Receive-Job: Object reference not set to an instance of an object.
```

### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type       : System.NullReferenceException
        TargetSite :
            Name          : Fragment
            DeclaringType : System.Management.Automation.Remoting.Fragmentor, System.Management.Automation, Version=7.4
.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message    : Object reference not set to an instance of an object.
        Source     : System.Management.Automation
        HResult    : -2147467261
        StackTrace :
   at System.Management.Automation.Remoting.Fragmentor.Fragment[T](RemoteDataObject`1 obj, SerializedDataStream dataToB
eSent)
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Add[T](RemoteDataObject`1 data, DataPriorityType
 priority)
   at System.Management.Automation.Remoting.ClientMethodExecutor.Execute(Action`1 writeErrorAction)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResults(Job job)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResultsRecursivelyHelper(Hashtable duplicate, Job job, Bo
olean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResultsRecursivelyHelper(Hashtable duplicate, Job job, Bo
olean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteResultsForJobsInCollection(List`1 jobs, Boolean checkForRecu
rse, Boolean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    CategoryInfo          : NotSpecified: (:) [Receive-Job], NullReferenceException
    FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.ReceiveJobCommand
    InvocationInfo        :
        MyCommand        : Receive-Job
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 7
        Line             : Receive-Job $job -Keep
        Statement        : Receive-Job $job -Keep
        PositionMessage  : At line:1 char:1
                           + Receive-Job $job -Keep
                           + ~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Receive-Job
        CommandOrigin    : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.4.0.50
0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message        : Object reference not set to an instance of an object.
Data           : System.Collections.ListDictionaryInternal
InnerException :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : Fragment
        DeclaringType : System.Management.Automation.Remoting.Fragmentor, System.Management.Automation, Version=7.4.0.5
00, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Object reference not set to an instance of an object.
    Source     : System.Management.Automation
    HResult    : -2147467261
    StackTrace :
   at System.Management.Automation.Remoting.Fragmentor.Fragment[T](RemoteDataObject`1 obj, SerializedDataStream dataToB
eSent)
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Add[T](RemoteDataObject`1 data, DataPriorityType
 priority)
   at System.Management.Automation.Remoting.ClientMethodExecutor.Execute(Action`1 writeErrorAction)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResults(Job job)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResultsRecursivelyHelper(Hashtable duplicate, Job job, Bo
olean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteJobResultsRecursivelyHelper(Hashtable duplicate, Job job, Bo
olean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.WriteResultsForJobsInCollection(List`1 jobs, Boolean checkForRecu
rse, Boolean registerInsteadOfWrite)
   at Microsoft.PowerShell.Commands.ReceiveJobCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Source         : System.Management.Automation
HResult        : -2146233087
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOp
tions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Skærmbillede 2023-12-19 130253](https://github.com/PowerShell/PowerShell/assets/6398503/c27299ab-e0d6-4074-83dc-9b908511cf2e)

**Comment by rhubarb-geek-nz** [comment]
I have tested a simple script and there is nothing that prevents a job reading or writing to the host

```
Write-Host 'main write to host'
$job = Start-Job { Write-Host 'job write to host' }
Receive-Job $job -Wait
Write-Host 'main after wait'
$job = Start-Job { Read-Host 'job read host' }
Receive-Job $job -Wait
Write-Host 'main write to host at end'
```

Result

```
main write to host
job write to host
main after wait
job read host: anything
anything
main write to host at end
```

At least that is consistent.

Note that there is a difference between reading and writing to the host and reading the input pipeline and writing to the output pipeline.

**Comment by jhoneill** [comment]
> ### Expected behavior
> ```
> I expect Read-Host to either throw an error or return with blank input as stdin is non-existent. 
> ```

Except that stdin is not non-existent. 

> 
> ### Actual behavior
> `PS> $job=Start-Job {Read-Host 'something'}`

At this point the job is waiting for input. 


> `PS> Receive-Job $job`
> `something:`

Now `Receive-job` displaying the prompt and will send your input back to the job so  
`here is my input`
 `PS> Receive-Job $job`
`here is my inout`


> `PS> Receive-Job $job -Keep`  

Will tie things up in knots because you have said don't clear the buffer by using `Keep` so next time you run receive job you get prompted again but now there is nothing to receive your input.   

Although I'm inclined to say the answer to the that is don't use Read-Host in a script if you don't want it to stop and ask for input, (e.g. have a switch to not use it if running as a job), there are scenarios where we want jobs and interaction (e.g. start 10 jobs to get data from a slow service, and get confirmation before writing the data returned to whatever destination). By using jobs we can have 10 calls waiting for data which might take 2 minutes to come back and then after 2 minutes we get 10 prompts (Save type 1, Save type 2 etc) so we save 18 minutes. If user input was unavailable we wouldn't be able parallelize the work

**Comment by mklement0** [comment]
First, some context:

* `Read-Host` doesn't use _stdin_ - except when PowerShell's CLI is directly called with stdin input and a command / script file to execute (which doesn't apply here).

* Regular background jobs (`Start-Job`) - which use a hidden PowerShell _child process_ - generally _do_ support using `Read-Host` from jobs, which - while unusual - can be useful, as noted.

  * Bash, for instance, supports analogous functionality.

* By contrast, _thread_-based jobs (`Start-ThreadJob`) - which use in-process PowerShell _runspaces_ -  indeed behave the way you expect (and so does the closely related `ForEach-Object -Parallel`):

  * They run in _non-interactive_ mode, which makes `Read-Host` _fail_, with the following error:

    * `Read-Host: A command that prompts the user failed because the host program or the command type does not support user interaction. [...]`

  * This asymmetry between child process-based and thread-based jobs is certainly surprising.

* Neither type of job offers (direct) control over the respective behavior.
 
  * However, child process-based jobs _inherit the caller's non-interactive mode_, if set (which requires having started PowerShell via its CLI and the `-noninteractive` parameter)

**Comment by mklement0** [comment]
* It follows from the above that the only way to get the behavior you want is to run  your entire session in non-interactive mode.

  * If you feel that that jobs should _always_ be non-interactive:

    * This would amount to a breaking change, which would only be acceptable if it fell into [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area), i.e. if it had very little or ideally no impact on existing code and - in this case - interactive practice.

  * If you feel that it's important to allow preventing interactivity on a per-job basis, say with a new `-NonInteractive` `Start-Job` switch.
    * Please open a feature request to that effect (arguably, `Start-ThreadJob` would need such a switch too, though - due to the asymmetry discussed - with opposite logic; `-NonInterative:$false` could technically work).

* As for the **symptom at hand**: To me it is unequivocally a _bug_.

  * The `-Keep` switch instructs the job to buffer the _output_ produced so far.

  * It shouldn't ever repeat an _input_ command, and certainly shouldn't fail on the next `Receive-Job` call.
