### ISSUE TITLE
Get-ADReplicationAttributeMetadata - invalid character error

### ISSUE THREAD

**Issue by Katana3128** [PowerShell/PowerShell#20947]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The cmdlet returns error:  "Get-ADReplicationAttributeMetadata: '►', hexadecimal value 0x10, is an invalid character." (or it shows another pictograms between ' ') for some accounts. Tested in Powershell 7.3.9 or 7.4.0
In Powershell 5.1: All accounts work fine

### Expected behavior

```console
Get-ADReplicationAttributeMetadata -Object "CN=xx,OU=xx,DC=xx,DC=xx" -Server dc1.xx.xx
AttributeName                                    : msRTCSIP-OptionFlags
AttributeValue                                   :
FirstOriginatingCreateTime                       :
IsLinkValue                                      : False
LastOriginatingChangeDirectoryServerIdentity     :
LastOriginatingChangeDirectoryServerInvocationId : bbd...
LastOriginatingChangeTime                        : 01.12.2020 8:27:40
LastOriginatingChangeUsn                         : 70482120
LastOriginatingDeleteTime                        :
LocalChangeUsn                                   : 46923
Object                                           : CN=xx,OU=xx,DC=xx,DC=xx
...
```

### Actual behavior

```console
Get-ADReplicationAttributeMetadata -Object "CN=xx,OU=xx,DC=xx,DC=xx" -Server dc1.xx.xx
Get-ADReplicationAttributeMetadata: '►', hexadecimal value 0x10, is an invalid character.
```

### Error details

```console
Exception             :
    Type           : Microsoft.ActiveDirectory.Management.ADException
    TargetSite     :
        Name          : CommonCatchAll
        DeclaringType : Microsoft.ActiveDirectory.Management.AdwsConnection, Microsoft.ActiveDirectory.Management, Vers
ion=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : Microsoft.ActiveDirectory.Management.dll
    Message        : '►', hexadecimal value 0x10, is an invalid character.
    InnerException :
        Type       : System.ArgumentException
        Message    : '►', hexadecimal value 0x10, is an invalid character.
        TargetSite :
            Name          : WriteElementTextBlock
            DeclaringType : System.Xml.XmlEncodedRawTextWriter, System.Private.Xml, Version=8.0.0.0, Culture=neutral, P
ublicKeyToken=cc7b13ffcd2ddd51
            MemberType    : Method
            Module        : System.Private.Xml.dll
        Source     : System.Private.Xml
        HResult    : -2147024809
        StackTrace :
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlDictionaryWriter.WriteTextNode(XmlDictionaryReader reader, Boolean isAttribute)
   at System.Xml.XmlDictionaryWriter.WriteNode(XmlDictionaryReader reader, Boolean defattr)
   at System.ServiceModel.Channels.BufferedMessage.OnBodyToString(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.ToString(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.ToString()
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
    Source         : Microsoft.ActiveDirectory.Management
    HResult        : -2146233088
    StackTrace     :
   at Microsoft.ActiveDirectory.Management.AdwsConnection.CommonCatchAll(Exception exception)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperatio
ns.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.PagedSearch(Object& pageCookie, Boolean& hasSizeLimitExceed
ed, Int32 pageSize, Int32 sizeLimit)
   at Microsoft.ActiveDirectory.Management.ADObjectSearchResultEnumerator.System.Collections.IEnumerator.MoveNext()
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.FindOne(Boolean& foundMoreThanOneResult)
   at Microsoft.ActiveDirectory.Management.Commands.ADFactoryUtil.GetObjectFromIdentitySearcher(ADObjectSearcher search
er, ADEntity identityObj, String searchRoot, AttributeSetRequest attrs, CmdletSessionInfo cmdletSessionInfo, String[]&
warningMessages)
   at Microsoft.ActiveDirectory.Management.Commands.ADFactory`1.GetExtendedObjectFromIdentity(T identityObj, String ide
ntityQueryPath, ICollection`1 propertiesToFetch, Boolean showDeleted, Boolean showLinkTtl)
   at Microsoft.ActiveDirectory.Management.Commands.ADFactory`1.GetExtendedObjectFromIdentity(T identityObj, String ide
ntityQueryPath, ICollection`1 propertiesToFetch, Boolean showDeleted)
   at Microsoft.ActiveDirectory.Management.Commands.GetADReplicationAttributeMetadata.GetADReplicationAttributeMetadata
ProcessCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Get-ADReplicationAttributeMetadata], ADException
FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.GetADReplicationAttribute
Metadata
InvocationInfo        :
    MyCommand        : Get-ADReplicationAttributeMetadata
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Get-ADReplicationAttributeMetadata -Object "CN=xx,OU=xx,DC=xx,DC=xx" -Server dc1.xx.xx
    Statement        : Get-ADReplicationAttributeMetadata -Object "CN=xx,OU=xx,DC=xx,DC=xx" -Server dc1.xx.xx
    PositionMessage  : At line:1 char:1
                       + Get-ADReplicationAttributeMetadata -Object "CN=xx,OU=xx …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-ADReplicationAttributeMetadata
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
What form is the attribute it is having problems with?

[ADReplicationAttributeMetadata.AttributeValue](https://learn.microsoft.com/en-us/dotnet/api/microsoft.activedirectory.management.adreplicationattributemetadata.attributevalue?view=activedirectory-management-10.0#microsoft-activedirectory-management-adreplicationattributemetadata-attributevalue)

is an object, that does not mean there is a correct automatic to string representation of the value.

**Comment by Katana3128** [comment]
It was tested with AD Users only, and for the object parameter was used Distinguished Name (DN) and GUID. Used DN or GUID of the same user returned me the same issue. 
In the Expected behavior is reported, what I obtain for the same tested user in Powershell 5.1 - running on the same server like pwsh7. So there must be some difference in pwsh7.
Thanks

**Comment by rhubarb-geek-nz** [comment]
Are you able to retrieve the value and assign it to a variable even if you can't display it? 

If you can get it as a variable can you then see what type of data it actually is (eg is it an array of bytes or shorts )?

**Comment by Katana3128** [comment]
Do you mean this infos?
PS C:\Program Files\PowerShell\7> $Vondrackova = Get-ADUser "CN=xx,OU=xx,DC=xx,DC=xx" -Server dc1.xx.xx
PS C:\Program Files\PowerShell\7> $Vondrackova.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    ADUser                                   Microsoft.ActiveDirectory.Management.ADAccount

PS C:\Program Files\PowerShell\7> $Vondrackova.DistinguishedName.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object

PS C:\Program Files\PowerShell\7> $Vondrackova.ObjectGUID.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Guid                                     System.ValueType

PS C:\Program Files\PowerShell\7> Get-ADReplicationAttributeMetadata -Object $Vondrackova.DistinguishedName -Server dc1.xx.xx
Get-ADReplicationAttributeMetadata: '►', hexadecimal value 0x10, is an invalid character.
PS C:\Program Files\PowerShell\7> Get-ADReplicationAttributeMetadata -Object $Vondrackova.ObjectGUID -Server dc1.xx.xx
Get-ADReplicationAttributeMetadata: '►', hexadecimal value 0x10, is an invalid character.

**Comment by rhubarb-geek-nz** [comment]
I am not familiar with AD but I might be able to help you get access to the data if we know what types they are that are causing problems. Yes there are huge differences between PowerShell Desktop and PowerShell Core

That is good!

If the DistinguishedName is a string, then it should already be a string so no conversion needed.

I am inferring that the ObjectGUID is really a GUID which is a binary type. While there is a standard conversion from GUID to string it might not be kicking in. Does the GUID have the hex digits "10" in it, as that is what the error messaging was complaining about.

Can you try

```
$Vondrackova.ObjectGUID.ToString()
```

To see if it can convert itself without assistance?

**Comment by Katana3128** [comment]
Yes, the conversion is working fine and it returns correct string same as string showed in AD User console - without any error.
And the user objectGUID does not contain the hex digit "10" - verified in AD User console also.

**Comment by rhubarb-geek-nz** [comment]
That is progress, but as far as I can really help. Has this ever worked on PowerShell 7 or is this the first time you tried?

With what you now know, do you have access to all the data fields you need?

**Comment by rhubarb-geek-nz** [comment]
Can you narrow down the specific fields and what data is causing the problem?

 If the fields contain valid data and are being used elsewhere it sounds like a translation/conversion problem. Is the problem only when you try and display them? Can you filter out those fields before display if they are not needed?
