### ISSUE TITLE
PowerShell installed as global tool with .NET 6 fails to run on Alpine 3.19

### ISSUE THREAD

**Issue by lbussell** [PowerShell/PowerShell#20945]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Similar issue to https://github.com/PowerShell/PowerShell/issues/16532. Build and run the following Dockerfile:

```Dockerfile
FROM alpine:3.19

ENV \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since ICU package isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

RUN apk add --upgrade --no-cache \
        ca-certificates \
        \
        # .NET dependencies
        krb5-libs \
        libgcc \
        libintl \
        libssl3 \
        libstdc++ \
        zlib

# Install .NET SDK
RUN wget -O dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0.417/dotnet-sdk-6.0.417-linux-musl-x64.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -C /usr/share/dotnet -oxzf dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

# Install PowerShell
RUN dotnet tool install --global PowerShell --version 7.2.17

ENTRYPOINT [ "/root/.dotnet/tools/pwsh" ]

```

### Expected behavior

```console
PowerShell starts and runs
```

### Actual behavior

```console
PowerShell 7.2.17
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

One or more errors occurred. (The type initializer for 'System.Management.Automation.TypeAccelerators' threw an exception.)
One or more errors occurred. (The type initializer for 'System.Management.Automation.TypeAccelerators' threw an exception.)
Cannot load PSReadline module.  Console is running without PSReadline.
Process terminated. The type initializer for 'System.Management.Automation.PSObject' threw an exception.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.PSObject' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.get_Properties()
   at System.Management.Automation.HostUtilities.GetDollarProfile(String allUsersAllHosts, String allUsersCurrentHost, String currentUserAllHosts, String currentUserCurrentHost)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceInitialization(Boolean skipProfiles, String initialCommand, String configurationName, Collection`1 initialCommandArgs)
   at Microsoft.PowerShell.ConsoleHost.DoCreateRunspace(String initialCommand, Boolean skipProfiles, Boolean staMode, String configurationName, Collection`1 initialCommandArgs)
   at Microsoft.PowerShell.ConsoleHost.CreateRunspace(Object runspaceCreationArgs)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
```

### Environment data

```powershell
Cannot get $PSVersionTable because PowerShell is not functional.
```

**Comment by lbussell** [comment]
/cc @adityapatwardhan 

Given the issue in the past was apparently the .NET RID not being available yet, I went ahead and filed some issues for that:

- https://github.com/dotnet/core/issues/9013
- https://github.com/dotnet/runtime/issues/96155

**Comment by rhubarb-geek-nz** [comment]
I installed the SDK from alpine itself, which gives 6.0.25 runtime

```
alpine3:~$ sudo apk add dotnet-sdk-6.0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/13) Installing dotnet-host (7.0.14-r0)
(2/13) Installing dotnet6-hostfxr (6.0.25-r0)
(3/13) Installing lttng-ust (2.13.6-r0)
(4/13) Installing xz-libs (5.4.5-r0)
(5/13) Installing libunwind (1.7.2-r1)
(6/13) Installing dotnet6-runtime (6.0.25-r0)
(7/13) Installing aspnetcore6-runtime (6.0.25-r0)
(8/13) Installing aspnetcore6-targeting-pack (6.0.25-r0)
(9/13) Installing dotnet6-apphost-pack (6.0.25-r0)
(10/13) Installing dotnet6-targeting-pack (6.0.25-r0)
(11/13) Installing dotnet6-templates (6.0.125-r0)
(12/13) Installing netstandard21-targeting-pack (7.0.114-r0)
(13/13) Installing dotnet6-sdk (6.0.125-r0)
Executing busybox-1.36.1-r15.trigger
OK: 729 MiB in 108 packages

```
And then installed the PowerShell tool version 7.2.17

```
alpine3:~$ dotnet tool install --global PowerShell --version 7.2.17

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.125

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
You can invoke the tool using the following command: pwsh
Tool 'powershell' (version '7.2.17') was successfully installed.
alpine3:~$ pwsh --version
PowerShell 7.2.17
alpine3:~$ pwsh
PowerShell 7.2.17
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/bythesea>
```

That sequence worked

**Comment by rhubarb-geek-nz** [comment]
This `Dockerfile` worked in that no error was raised with `PSReadLine` although its echoing behaviour when using `docker run -it` looked very odd.

```
FROM alpine:3.19

ENV \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since ICU package isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true

RUN apk add --upgrade --no-cache \
        ca-certificates \
        \
        # .NET dependencies
        krb5-libs \
        libgcc \
        libintl \
        libssl3 \
        libstdc++ \
        zlib \
        dotnet-sdk-6.0

# Install PowerShell
RUN dotnet tool install --global PowerShell --version 7.2.17

ENTRYPOINT [ "/root/.dotnet/tools/pwsh" ]
```

Then built and ran.

```
$ docker build -t alpine-3.19-pwsh .
$ docker run -it --rm alpine-3.19-pwsh
```

**Comment by lbussell** [comment]
@rhubarb-geek-nz I appreciate your investigation, but we aren't interested in using the Alpine-built .NET SDK or PowerShell for the official .NET container images.

/cc @adityapatwardhan, according to the issues I filed (https://github.com/dotnet/core/issues/9013, https://github.com/dotnet/runtime/issues/96155) adding the RID to .NET isn't the fix since RIDs are all portable now. I'm not sure how that affects this issue, but can you take a look? This issue will block moving .NET SDK's floating tags to Alpine 3.19 since excluding PowerShell from Alpine x64 is a regression in functionality.

**Comment by lbussell** [comment]
@adityapatwardhan Any update on this issue investigation?

**Comment by lbussell** [comment]
I confirmed that this is still an issue with PowerShell v7.2.18.

**Comment by lbussell** [comment]
I was looking at this again today and I found that adding the environment variable `    DOTNET_RUNTIME_ID=linux-musl-x64` allows PowerShell to start using a .NET 6 runtime! `alpine-x64` and `alpine.3.18-x64` also work.

However there is a strange issue with the interactive terminal, it repeats all of the characters you type, as you type. For example, if I typed `hello`, the terminal would show: `PS /> hhehelhellhello`. The extra text does not have an effect on command output - if I type `dotnet --list-runtimes` and press enter, no matter what shows in the terminal, I will get the correct output. This is using .NET 6.0.27, Alpine 3.19, and PowerShell 7.2.18.

**Comment by lbussell** [comment]
This should be checked again since https://github.com/dotnet/runtime/issues/96155 is complete.

**Comment by lbussell** [comment]
Confirmed this is fixed now.

```pwsh
PS C:\s> docker run -it --rm mcr.microsoft.com/dotnet/sdk:6.0-alpine3.19 pwsh
PowerShell 7.2.19
Copyright (c) Microsoft Corporation.
https://aka.ms/powershell
Type 'help' to get help.

PS /> echo "Hello!"
Hello!
```
