### ISSUE TITLE
Incorrect processing of localised dates

### ISSUE THREAD

**Issue by u20221022** [PowerShell/PowerShell#20972]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`(Get-Date).ToLongDateString()`
30 декабря 2023 г.
`(Get-Date).ToLongDateString().GetType().Name`
String
`[DateTime] (Get-Date).ToLongDateString()`
InvalidArgument: Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a valid DateTime. There is an unknown word starting at index '3'."
`[DateTime] "30 декабря 2023 г."`
InvalidArgument: Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a valid DateTime. There is an unknown word starting at index '3'."

### Expected behavior

```console
30 декабря 2023 г.
```

### Actual behavior

```console
Error.
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a valid
DateTime. There is an unknown word starting at index '3'."
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 47
            Line             : [DateTime] (Get-Date).ToLongDateString()
            Statement        : [DateTime] (Get-Date).ToLongDateString()
            PositionMessage  : At line:1 char:1
                               + [DateTime] (Get-Date).ToLongDateString()
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    Message        : Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a valid D
ateTime. There is an unknown word starting at index '3'."
    InnerException :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a va
lid DateTime. There is an unknown word starting at index '3'."
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
            InvocationInfo        :
                ScriptLineNumber : 1
                OffsetInLine     : 1
                HistoryId        : 47
                Line             : [DateTime] (Get-Date).ToLongDateString()
                Statement        : [DateTime] (Get-Date).ToLongDateString()
                PositionMessage  : At line:1 char:1
                                   + [DateTime] (Get-Date).ToLongDateString()
                                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
        TargetSite     :
            Name          : ConvertWithCulture
            DeclaringType : System.Management.Automation.LanguagePrimitives+ConvertViaParseMethod, System.Management.Automation, Version=7.4.0.500, Culture=neutr
al, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "30 декабря 2023 г." to type "System.DateTime". Error: "The string '30 декабря 2023 г.' was not recognized as a val
id DateTime. There is an unknown word starting at index '3'."
        Data           : System.Collections.ListDictionaryInternal
        InnerException :
            Type       : System.FormatException
            TargetSite :
                Name          : Parse
                DeclaringType : System.DateTimeParse, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : The string '30 декабря 2023 г.' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.
            Source     : System.Private.CoreLib
            HResult    : -2146233033
            StackTrace :
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at InvokeStub_DateTime.Parse(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithCulture(Object valueToConvert, Type resultType, Boolean recursion, PSObjec
t originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    HResult        : -2146233087
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 47
    Line             : [DateTime] (Get-Date).ToLongDateString()
    Statement        : [DateTime] (Get-Date).ToLongDateString()
    PositionMessage  : At line:1 char:1
                       + [DateTime] (Get-Date).ToLongDateString()
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Does this work in PowerShell 5.1?

Not all data types work with round trips, especially when you are asking for a conversion and there is no clue as to what format the data is in.

When you do the ToLongDataString() it is clear because you are going from a date to a string using the current culture as per [ToLongDateString](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tolongdatestring?view=net-8.0)

But the casting of a string to a DateTime is very ambiguous, there are many different formats the date could be in, long format, short format, localised, not localised, ISO formatted dates etc.

If you want to round-trip dates via strings I suggest using an ISO format for the string.

**Comment by 237dmitry** [comment]
> Does this work in PowerShell 5.1?

Yes, it works with non-localized date format.

**Comment by scriptingstudio** [comment]
Using string argument with `[datetime]` is safe for ISO 8601 format - YYYY-MM-DD.
For others to work use methods like `::parse()`
```powershell
[DateTime]::parse("30 декабря 2023 г.")
30 декабря 2023 г. 0:00:00
```

**Comment by 237dmitry** [comment]
> For others to work use methods like ::parse()

This is unfair to other cultures that can be found in `System.Globalisation.Cultureinfo`.

**Comment by rhubarb-geek-nz** [comment]
> This is unfair to other cultures that can be found in `System.Globalization.Cultureinfo`.

It is not unfair to other cultures, it is unfair to the entire human race!

The business of parsing human readable dates is a minefield of potential errors. For example just with English, in the US the dates are often month/day/year while in the UK that would be day/month/year, so with any day of the month less than 13 it is ambiguous, that is for over a third of the year!

I suggest that the human readable formats should only be used for presentation, that is date to string.

Parsing of dates should really be done with a standard machine readable format (such as ISO 8601). This means all storage of dates and all exchange of dates between systems should be in machine readable forms which are not dependent on any culture for interpretation. This means that dates in JSON and XML are self contained and not dependent on external cultural context.

**Comment by 237dmitry** [comment]
> For example just with English, in the US the dates are often month/day/year while in the UK that would be day/month/year, so with any day of the month less than 13 it is ambiguous, that is for over a third of the year!

Look at this, and answer why `en-UK` and `en-US` are not to be `::Parse()`ed?

![Screenshot 2023-12-30 114910](https://github.com/PowerShell/PowerShell/assets/78153320/909eac57-7be9-4ae4-ada9-7d20cff7047a)

**Comment by rhubarb-geek-nz** [comment]
> Look at this, and answer why `en-UK` and `en-US` are not to be `::Parse()`ed?

I am talking about the general case where you have little control of the source of the date string. It has come from some other party or system. 

If you are in a tightly controlled loop in control of both the output and input then yes it can be done, but in the case of using PowerShell to integrate different components where you have no control over the formats then human readable strings are problematic.

**Comment by 237dmitry** [comment]
ANY culture formats presented in `System.Globalization.CultureInfo` must be parsed on the fly. Why is `zu-Zu` inferior to `en-UK`?

**Comment by rhubarb-geek-nz** [comment]
> ANY culture formats presented in `System.Globalization.CultureInfo` must be parsed on the fly. Why is `zu-Zu` inferior to `en-UK`?

I am certainly not saying there is any cultural hierarchy. I am suggesting that all forms designed for presentation to humans are problematic, hence why standards like ISO 8601 exist.

**Comment by 237dmitry** [comment]
Are there templates for displaying date and time? Yes, every culture has its own. Why are one culture's date and time patterns better than another? Conditions must be equal, whether Japanese, Zulus or Bulgarians.

**Comment by rhubarb-geek-nz** [comment]
> Conditions must be equal, whether Japanese, Zulus or Bulgarians.

I am happy with that, the direct [DateTime] cast should support ISO 8601, and [DateTime]::Parse() should support all System.Globalization.CultureInfo equally.

Eg for the cast, it is not associated with any culture

```
[DateTime]'2022-09-27T18:00:00.000+03:00'
```

**Comment by mklement0** [comment]
For culture-independence, PowerShell uses the [_invariant_ culture](https://learn.microsoft.com/en-US/dotnet/api/System.Globalization.CultureInfo.InvariantCulture) in many string-processing contexts, including casts and expandable strings.

This culture is based on, but not identical to, the US-English culture.

`[DateTime] (Get-Date).ToLongDateString()` is therefore the same as:

```powershell
[DateTime]::Parse((Get-Date).ToLongDateString(), [cultureinfo]::InvariantCulture)
```

Therefore, the above only works if the invariant culture itself, the US-English culture (`en-US`) or any culture that effectively uses the same date and time formats is in effect.

**Comment by 237dmitry** [comment]
> Therefore, the above only works if the invariant culture itself, the US-English culture (en-US) or any culture that effectively uses the same date and time formats is in effect

`en-US` LongDateString format (`LongDatePattern + LongTimePattern = FullDateTimePattern`) is not the same as `inv`

`dddd, MMMM d, yyyy h:mm:ss tt`   en-US
 `dddd, MMMM d, yyyy HH:mm:ss`      inv (and en-UK)

Why en-US works? This is not the same format:
```powershell
$ [DateTime]::Parse((Get-Date).ToLongDateString(), [cultureinfo]::InvariantCulture)

Saturday, December 30, 2023 12:00:00 AM                                                 
```

**Comment by u20221022** [comment]
Not so long ago this error was not present.  The date line used to contain the day of the week, which it does not now.  Maybe it is because I am currently connected to the internet via VPN in the USA.  I will let you know if the error goes away after a reboot.  Simply disconnecting the VPN does not help.

`[Threading.Thread]::CurrentThread.CurrentCulture`

LCID             Name             DisplayName
----             ----             -----------
1049             ru-RU            русский (Россия)

`[cultureinfo]::InvariantCulture`

LCID             Name             DisplayName
----             ----             -----------
127                               Invariant Language (Invariant Country)

**Comment by rhubarb-geek-nz** [comment]
> Not so long ago this error was not present.

Was this when you were using a version using .NET 6 or .NET 7, eg PowerShell 7.2.x or 7.3.x? The big change is the move to .NET 8

>I will let you know if the error goes away after a reboot.

From the description here the issue is a feature rather than a bug. If you want to decode a string that is incompatible with the invariant culture then explicitly use [DateTime]::Parse rather than the simple casting.

**Comment by u20221022** [comment]
On the 23rd of November I installed Net 8.
On 28 November the error has not yet occurred.
But earlier I connected to VPN via Europe.
![dotNet](https://github.com/PowerShell/PowerShell/assets/117870409/959f26ff-2fd0-4b3e-89ae-43296ad9acde)

**Comment by mklement0** [comment]
@u20221022:

* The premise of your issue is flawed, as implied by my previous comment, which makes it a non-issue. (The culture-invariant behavior described has probably been in place since v1.)

* Separately, on a general note: 
  * As has been noted, PowerShell's culture definition rely on .NET's
  * With the exception of the _invariant_ culture - whose very purpose is to _never change_ - culture-specific representations _are allowed to_ and _do_ change; a notable, large-scale change occurred when .NET moved from NLS to ICU in .NET 5 on Windows (though note that the _current_ culture still uses the NLS settings by default).

**Comment by u20221022** [comment]
@mklement0:
I will remember to use the static "parse" method.  Thank you.
But I still do not understand at what point the behaviour changed.

**Comment by mklement0** [comment]
@u20221022, I don't think the behavior ever changed: with, say, `ru-RU` in effect, `[DateTime] (Get-Date).ToLongDateString() }`  should _always_ have failed - and indeed does fail in _Windows PowerShell_ as well as in PowerShell Core v7.2.10, for instance.

**Comment by mklement0** [comment]
@237dmitry, that is a question for the designers of the invariant culture; one thing is clear: it is based on the US culture, but omits the AM / PM specifiers by default - while still recognizing them while parsing.

You can use the following code to see in which specific .NET cultures casting from `.ToString('F')` (FullDateTimePattern) to `[datetime]` works:

```powershell
$matchingCultures = 
  [cultureinfo]::GetCultures('SpecificCultures') |
    ForEach-Object -Begin { 
      $prevCulture = [cultureinfo]::CurrentCulture 
    } -Process {
      [cultureinfo]::CurrentCulture = $_
      try {
        $dateStr = (Get-Date).ToString('F')
        $null = [datetime] $dateStr
        [pscustomobject] @{
          Culture = $_
          LongDate = $dateStr
        }
      } catch {}
    } -End {
      [cultureinfo]::CurrentCulture  = $prevCulture 
    }

$matchingCultures | Format-Table -GroupBy @{ n='Language'; e={ ($_.Culture -split '-')[0] } }
```

* On my macOS system, it is exclusively `en-` prefixed cultures - i.e. English-based  that match.

* Curiously, on my Windows 11 22H2 machine, I additionally get the following cultures:

  * `ibb-NG`, `ja-JP`, `kr-Latn-NG`, `ks-Deva-IN`, all of which use either the invariant or the US-English format.
  * Various `zsh` (Chinese) cultures, which use strings such as `2023年12月30日 8:51:18`

I didn't know about the support for CJK characters, which seems to be limited to the _date_ part: that is why the `ja` and `zh`-based cultures are included on Windows: they express the _time_ part in Arabic numerals (e.g. `8:51:18`) there, whereas on macOS CJK characters are used.

I presume the difference comes down to specific version of the ICU library used on different platforms.

Either way, it illustrates that culture-specific representations cannot be relied on for long-term stability in programmatic processing.

**Comment by u20221022** [comment]
@mklement0:
The behaviour has changed and it happened in the very last few days (no more than a week).  I use this operation quite often to adjust attributes of files downloaded via torrent.

**Comment by u20221022** [comment]
@mklement0:
You are probably right.  Most likely, earlier I used English strings like «Thu, 21 Dec 2023 11:20:34 GMT» instead of Russian.  Sorry.

**Comment by mklement0** [comment]
Makes sense, @u20221022.

The bottom line is:

* Use `[datetime]` to parse date/time strings that are compatible with the _invariant_ culture - though if you know a string to be from a specific culture, it's better to use that culture explicitly.

* If you want _culture-specific_ parsing...
  *  ... based on the _current_ culture, use the single-parameter `::Parse()` overload:

    ```powershell
    # OK with ru-RU in effect
    [datetime]::Parse('30 декабря 2023 г.')
    ```

  *  ... based on a _given_ culture, pass the relevant `[cultureinfo]` instance as the second argument:

    ```powershell
    [datetime]::Parse('30 декабря 2023 г.', [cultureinfo] 'ru-RU')
    ```

**Comment by 237dmitry** [comment]
> one thing is clear: it is based on the US culture, but omits the AM / PM specifiers by default - while still recognizing them while parsing.

I understood, football vs. soccer.

**Comment by u20221022** [comment]
@mklement0 But what?
`(Get-Item -LiteralPath test).LastWriteTime`

30 декабря 2023 г. 17:45:10

`(Get-Item -LiteralPath test).LastWriteTime = "30 декабря 2023 г. 17:45:10"`
Error…

Save into variable:
`[DateTime] $timChanged = (Get-Item -LiteralPath test).LastWriteTime`
`$timChanged`

30 декабря 2023 г. 17:45:10

`(Get-Item -LiteralPath test).LastWriteTime = $timChanged`
Not error.

**Comment by mklement0** [comment]
@237dmitry, loosely speaking, yes; note, however, that UK-style _day-first_ formats do _not_ work (e.g. `[datetime] '24/12/2023'`

@u20221022:

`.LastWriteTime` contains a `[datetime]` instance, not a string.

_On formatting for display_ PowerShell (a) must generate a _string_ representation and (b) unlike in casts and expandable strings, _does_ apply the rules of the current culture there.

On _assigning_ to `.LastWriteTime`, you must either use a `[datetime]` instance or a string recognized by the invariant culture. In other words:

```powershell
(Get-Item -LiteralPath test).LastWriteTime  = "30 декабря 2023 г. 17:45:10"
```

is implicitly the same as using a `[datetime]` cast on the string, which therefore predictably fails:

```powershell
(Get-Item -LiteralPath test).LastWriteTime  = [datetime] "30 декабря 2023 г. 17:45:10"
```

**Comment by u20221022** [comment]
@mklement0 I think I have got it.  Thank you.

**Comment by mklement0** [comment]
P.S.: 

There are two - unfortunate - exceptions to the culture-invariant parsing:

* Strings passed to strongly typed parameter of _binary cmdlets_ are unexpectedly parsed culture-_sensitively_.

  * This is a known problem that won't be fixed, however, so as not to break backward compatibility; see #6989

* The `-as` operator  _selectively_ parses in a culture-specific manner:
  * See  #8129 - no official decision has been made.

Therefore, with culture `ru-RU` in effect, the following unexpectedly DO work:

```powershell
# !! These SHOULDN'T work, but  DO:
Get-Date  '30 декабря 2023 г. 17:45:10'
'30 декабря 2023 г. 17:45:10' -as [datetime]
```
