### ISSUE TITLE
Occasional NullReferenceException in Microsoft.PowerShell.ProgresPane.Hide() when updating multiple progress bars on PS 7.4.0

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#21021]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

*This is not happening on PS 5.1*

Issue [was first identified](https://github.com/thoemmi/7Zip4Powershell/issues/88) by my when expanding multiple 7z archives with `Start-ThreadJob` and `Expand-7Zip` cmdlet from [*7Zip4PowerShell*](https://github.com/thoemmi/7Zip4Powershell/blob/c19e42f8c1cf70ec4c07bfee1c6c6ec27e1ffb51/7Zip4Powershell/ThreadedCmdlet.cs#L42C19-L42C19) module. It might be also  related to [this issue](https://github.com/PowerShell/PowerShell/issues/17497) with [corresponding PR](https://github.com/PowerShell/PowerShell/pull/17498)

**Issue description:**

When using and cmdlet that opens multiple progress panes on PS 7.4.0, a *NullReferenceException* is thrown occasionally on progress pan completion. Please refer to above links for more details.

**Workaround:**
Disable progress before calling cmdlet that opens multiple progress panes with `$ProgressPreference = 'SilentlyContinue'`

### Expected behavior

```console
NullReferenceException on ProgressPane completion should not happen
```

### Actual behavior

```console
Occasionally an exception is thrown that "Object reference not set to an instance of an object" at Microsoft.PowerShell.ProgressPane.Hide()
```

### Error details

```console
TargetSite      : Void Hide()
Message         : Object reference not set to an instance of an object.
Data            : {}
InnerException  :
HelpLink        :
Source          : Microsoft.PowerShell.ConsoleHost
Result          : -2147467261
StackTrace      :   at Microsoft.PowerShell.ProgressPane.Hide()
                    at Microsoft.PowerShell.ProgressPane.Show(PendingProgress pendingProgress)
                    at Microsoft.PowerShell.ConsoleHostUserInterface.HandleIncomingProgressRecord(Int64 sourceId, ProgressRecord record)
                    at Microsoft.PowerShell.ConsoleHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
                    at System.Management.Automation.Internal.Host.InternalHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
                    at System.Management.Automation.MshCommandRuntime.WriteProgress(Int64 sourceId, ProgressRecord progressRecord, Boolean overrideInquire)
                    at System.Management.Automation.Cmdlet.WriteProgress(ProgressRecord progressRecord) at SevenZip4PowerShell.ThreadedCmdlet.EndProcessing() in C:\Users\---\Documents\Visual Studio 2022\Projects\72ip4PowerShe11\72ip4Powershell\ThreadedCmdlet.cs:line 29
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![294245576-42cedbfa-b55a-413f-a955-e927ebb39adc](https://github.com/PowerShell/PowerShell/assets/16168755/7b90d139-685d-4b26-a5fc-8940ba533aee)

**Comment by centis** [comment]
I see this every time that Invoke-Command is executed on a -Session if the connection is broken during the command.  For example, "Invoke-Command -Session $Session -ScriptBlock { shutdown -t 0 -r }".  It does waits for the timeout and then throws the null object exception.

This may make it easier to reproduce...

**Comment by kborowinski** [comment]
Pinging to keep this issue open

**Comment by kborowinski** [comment]
@SteveL-MSFT Unfortunately this is still happening on `PowerShell 7.5.0 GA` and `PowerShell 7.6.0-preview.2`. I had to globally disable the progress bar to make sure that my heavily parallelized scripts do not break.

**Comment by iSazonov** [comment]
@kborowinski I see you use Start-ThreadJob so the https://github.com/PowerShell/PowerShell/issues/17497 issue is the same.
There was a fix https://github.com/PowerShell/PowerShell/pull/17498 not merged. We did not get understanding a root of the issue.

Can you share a simple script to reproduce the issue?

**Comment by kborowinski** [comment]
@iSazonov Tomorrow I'll try to come up with sensible reproduction script and will let you know.

**Comment by kborowinski** [comment]
Here is a version of the same script that uses `ForEach-Object -Parallel`. It does not trigger *NREs*. So it looks like this is `Microsoft.PowerShell.ThreadJob` issue?

```powershell
#Requires -Version 7.5 -Modules 7Zip4Powershell

$Global:ProgressPreference = 'Continue'
# $PSStyle.Progress.MaxWidth = 240

$numberOfSubfolders = 128
$maximumNumberOfFilesPerSubfolder = 1KB

# Define the main directory path
$rootFolder = 'C:\_ProgressTest'
$sourceFolders = Join-Path -Path $rootFolder -ChildPath 'SourceFolders'
$compressedFolders = Join-Path -Path $rootFolder -ChildPath 'CompressedFolders'

# Create folder structure
$null = New-Item -Path $rootFolder -ItemType Directory -Force
$null = New-Item -Path $sourceFolders -ItemType Directory -Force
$null = New-Item -Path $compressedFolders -ItemType Directory -Force

$splatForEachParallel = @{
    ThrottleLimit = [Environment]::ProcessorCount
}

function Test-Setup {
    [CmdletBinding()]
    param()

    # Remove pre-generated folders if any
    Remove-Item -Path "$sourceFolders\*" -Recurse -Force -ErrorAction Stop
    # Remove archives
    Remove-Item -Path "$compressedFolders\*" -Recurse -Force -ErrorAction Stop

    # Create subdirectories and files in parallel
    1..$numberOfSubfolders | ForEach-Object -Parallel {
        function Get-RandomNumber {Get-Random -Minimum 128 -Maximum $Using:maximumNumberOfFilesPerSubfolder}

        # Subfolder path
        $subfolderPath = Join-Path -Path $Using:sourceFolders -ChildPath "Subfolder$_"

        $fileCount = Get-RandomNumber

        Write-Host ('Creating "{0}" with {1} files' -f $subfolderPath, $fileCount)

        # Create the subfolder
        $null = New-Item -Path $subfolderPath -ItemType Directory -Force

        # Create files with random content
        1..$fileCount | ForEach-Object {
            $filePath = Join-Path -Path $subfolderPath -ChildPath "file$_.txt"
            $fileContent = [Guid]::NewGuid().Guid * (Get-RandomNumber)
            Set-Content -Path $filePath -Value $fileContent -Force
        }

    } @splatForEachParallel
}

function Test-Compress {
    [CmdletBinding()]
    param()

    $isVerbose = $PSBoundParameters['Verbose'] -eq $true

    Get-ChildItem -Path $sourceFolders -Directory | ForEach-Object -Parallel {
        try {
            $VerbosePreference = if ($Using:isVerbose) {'Continue'} else {'SilentlyContinue'}

            $subfolderPath = $_
            $archivePath = Join-Path -Path $Using:compressedFolders -ChildPath ('{0}.7z' -f $subfolderPath.BaseName)

            #Check if target archive exists and remove it
            if (Test-Path -Path $archivePath -PathType Leaf) {
                Remove-Item -Path $archivePath -Force
            }

            # Define the parameters for Compress-7Zip cmdlet
            $splatCompress = @{
                ArchiveFileName         = $archivePath
                Path                    = $subfolderPath
                PreserveDirectoryRoot   = $true
                Verbose                 = $false
                ErrorAction             = 'Stop'
            }
            Compress-7Zip @splatCompress
            Write-Verbose -Message (
                'Compression completted: "{0}"' -f
                    $archivePath
            )
        } catch {
            # Write-Warning ('[PID: "{0}" | RID: "{1}"]' -f
            #     $PID,
            #     [Management.Automation.Runspaces.Runspace]::DefaultRunspace.Id,
            #     $_.Exception.Message
            # )
            # Wait-Debugger
            throw $_
        }
    } @splatForEachParallel
}

function Test-Expand {
    [CmdletBinding()]
    param()

    $isVerbose = $PSBoundParameters['Verbose'] -eq $true

    Get-ChildItem -Path $compressedFolders -File | ForEach-Object -Parallel {
        try {
            $VerbosePreference = if ($Using:isVerbose) {'Continue'} else {'SilentlyContinue'}

            $subfolder = $_
            $subfolderPath = Join-Path -Path $Using:sourceFolders -ChildPath $subfolder.BaseName

            # Check if the target directory already exists and remove it.
            if (Test-Path -Path $subfolderPath -PathType Container) {
                Remove-Item -Path $subfolderPath -Recurse -Force
            }

            # Expand the archive to the target directory.
            $splatExpand = @{
                ArchiveFileName = $subfolder
                TargetPath      = $Using:sourceFolders
                Verbose         = $false
                ErrorAction     = 'Stop'
            }
            Expand-7Zip @splatExpand
            Write-Verbose -Message (
                'Expansion completted: "{0}"' -f
                    $subfolder
            )
        } catch {
            # Write-Warning ('[PID: "{0}" | RID: "{1}"]' -f
            #     $PID,
            #     [Management.Automation.Runspaces.Runspace]::DefaultRunspace.Id,
            #     $_.Exception.Message
            # )
            # Wait-Debugger
            throw $_
        }
    } @splatForEachParallel
}
```

**Comment by iSazonov** [comment]
@kborowinski Thanks for great repro!

> Here is a version of the same script that uses `ForEach-Object -Parallel`. It does not trigger _NREs_. So it looks like this is `Microsoft.PowerShell.ThreadJob` issue?

I don't think so. Root of the issue is most likely in conhost. From the demo I see NREs throw after verboses push progress bars out of the window. Perhaps this will allow us to make even simpler repro based on two "threads" or even one.

**Comment by kborowinski** [comment]
@iSazonov I came up with much simpler version that reproduces the same behavior. No need for initial test setup, however it still requires ~50 threads to reproduce reliably. I will also post it at the top.

1. Save as `Test-ProgressBar.ps1`
2. Dot-source
3. Execute `Test-ProgressBar -Verbose` the trigger NREs

```powershell
#Requires -Version 7.5 -Modules Microsoft.PowerShell.ThreadJob

function Test-ProgressBar {
    [CmdletBinding()]
    param()

    $Global:ProgressPreference = 'Continue'
    $PSStyle.Progress.MaxWidth = $Host.UI.RawUI.WindowSize.Width

    $splatThreadJob = @{
        ThrottleLimit = [Environment]::ProcessorCount
        StreamingHost = $Host
    }

    $isVerbose = $PSBoundParameters['Verbose'] -eq $true

    $threadJobs = 1..50 | ForEach-Object {
        Start-ThreadJob -Name $_ -ScriptBlock {
            try {
                $VerbosePreference = if ($Using:isVerbose) {'Continue'} else {'SilentlyContinue'}

                $progressBarId = $Using:_
                $progressBar = 'ProgressBar-{0}' -f $progressBarId

                foreach ($n in 0..100) {
                    Write-Progress -Activity $progressBar -Status ('{0}%' -f $n) -PercentComplete $n -Id $progressBarId
                    Start-Sleep -Milliseconds (Get-Random -Minimum 15 -Maximum 45)
                }
                Write-Progress -Activity $progressBar -Completed -Id $progressBarId

                Write-Verbose -Message (
                    'Progress bar completted: "{0}"' -f
                        $progressBar
                )
            } catch {
                # Write-Warning ('[PID: "{0}" | RID: "{1}"]' -f
                #     $PID,
                #     [Management.Automation.Runspaces.Runspace]::DefaultRunspace.Id,
                #     $_.Exception.Message
                # )
                # Wait-Debugger
                throw $_
            }
        } @splatThreadJob
    }

    $null = Wait-Job -Job $threadJobs | Receive-Job
    Remove-Job -Job $threadJobs -Force
}
```
# Visuals:

![Image](https://github.com/user-attachments/assets/528d1e95-f5e8-4d85-b465-9504bc7bbeb8)

**Comment by iSazonov** [comment]
@kborowinski Thanks! We get the error more fast if console windows height will be 4-5 line.

Could you please suppress virtual terminal support (set env variable TERM=dumb ) and try run your test again?

**Comment by kborowinski** [comment]
@iSazonov  Yeah, suppressing virtual terminal support helps:

![Image](https://github.com/user-attachments/assets/85d6aa94-2a8e-452d-9c7a-7646788e5293)

**Comment by iSazonov** [comment]
@kborowinski Thanks for confirmation!

PSAnsiRendering was introduced in https://github.com/PowerShell/PowerShell/pull/13758 (https://github.com/PowerShell/PowerShell/pull/15864)
Example for verbose method (there are others):
https://github.com/PowerShell/PowerShell/blob/6c216bff4db406ab22a211928f6d4ee2d0f70810/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1273-L1283

New WriteLine() method directly call WriteToConsole() method (WriteImpl()->[ConsoleTextWriter.Write()](https://github.com/PowerShell/PowerShell/blob/6c216bff4db406ab22a211928f6d4ee2d0f70810/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L753)->[WriteToConsole()](https://github.com/PowerShell/PowerShell/blob/6c216bff4db406ab22a211928f6d4ee2d0f70810/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleTextWriter.cs#L37)), 
https://github.com/PowerShell/PowerShell/blob/6c216bff4db406ab22a211928f6d4ee2d0f70810/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L710-L713

but old one calls the method using wrapper with global lock `_instanceLock`
https://github.com/PowerShell/PowerShell/blob/6c216bff4db406ab22a211928f6d4ee2d0f70810/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L805-L824

No global lock `_instanceLock` in new Write*() methods is a root of the issue. Most likely it was a flaw.

**Comment by kborowinski** [comment]
@iSazonov This is a great find. I will try to re-introduce the locks on my local fork to see if it solves the problem.

**Comment by iSazonov** [comment]
Perhaps @SteveL-MSFT  remembers whether the lack of the lock is intentional or accidental.

**Comment by kborowinski** [comment]
@iSazonov Yep, `_instanceLock` does the trick, at least on my local fork 😉

Thanks for solving it! 🚀

I will make a [draft pull request](https://github.com/PowerShell/PowerShell/pull/24911) to address this issue, but since I do not know the impact on the performance, I will wait for your review and guidance if that's OK.

**Comment by iSazonov** [comment]
> but since I do not know the impact on the performance, I will wait for your review and guidance if that's OK.

Old code (coming from Windows PowerShell) has the lock for years. So we don't lost performance more than before. Early we merge some PRs to improve progress bar performance and I think we can not do more in current code design. In general, it is bad idea to write to console from many threads - script writers should understand that writing to console slow down their scripts.

**Comment by kborowinski** [comment]
>  In general, it is bad idea to write to console from many threads - script writers should understand that writing to console slow down their scripts.

I know that it's better to avoid progress bars, as they can impact performance. The funny thing is that I had a check in my profile that on PS 7.5.0 preview was disabling it globally. The bug reappeared when I moved to the stable release and my check was no longer valid. Then I was hit by a progress bar bug coming from `Remove-Item` running in a thread, since it now has progress bar as well.

However, I find it particularly useful to have a method for visually indicating that a long-running thread task has been completed, such as using verbose output.
