### ISSUE TITLE
.where is (sometimes) changing Type to Collection

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#21046]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

.where is changing the object type to `System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]` and trying to call a method on it at least sometimes fails because of this.

```ps1
# let $db be an object of type [Microsoft.SqlServer.Management.Smo.Database]

# Code that failed just now (but worked previously without error for (at least until now) unknown reasons).
$db.FileGroups.Where{$true}.Files.Where{$true}.Rename('new_name')

$db.FileGroups.Where{$true}.Files.Where{$true}.GetType().FullName
# System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]

# Interestingly when I now send it through the pipe to an Select-Object it doesn't modify the type.
($db.FileGroups.Where{$true}.Files.Where{$true} | Select-Object).GetType().FullName
# Microsoft.SqlServer.Management.Smo.DataFile


# But even though the type is destroyed this way PowerShell still shows us that the Rename function should exist.
# But as seen in the error attached below it not always is.
$db.FileGroups.Where{$true}.Files.Where{$true}.Rename
#OverloadDefinitions
#-------------------
#void Rename(string newname)
#void IRenamable.Rename(string newname)

```

### Expected behavior

```console
.where and plain "Select-Object" not changing the type.
```

### Actual behavior

```console
Types change
```

### Error details

```console
Exception             :
    Type                        : System.Management.Automation.RuntimeException
    ErrorRecord                 :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Method invocation failed because [System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=7.3.10.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35]]] does not contain a method named 'Rename'.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodNotFound
        InvocationInfo        :
            ScriptLineNumber : 5
            OffsetInLine     : 19
            HistoryId        : -1
            ScriptName       : C:\Users\user\Desktop\script\main.ps1
            Line             : $db.FileGroups.Where{
 
            PositionMessage  : At C:\Users\user\Desktop\script\main.ps1:5 char:19
                               +                   $db.FileGroups.Where{
                               +                   ~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\user\Desktop\script
            PSCommandPath    : C:\Users\user\Desktop\script\main.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : <Removed>
    WasThrownFromThrowStatement : True
    TargetSite                  :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.3.10.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message                     : Method invocation failed because [System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=7.3.10.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35]]] does not contain a method named 'Rename'.
    Data                        : System.Collections.ListDictionaryInternal
    Source                      : System.Management.Automation
    HResult                     : -2146233087
    StackTrace                  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : MethodNotFound
InvocationInfo        :
    ScriptLineNumber : 5
    OffsetInLine     : 19
    HistoryId        : -1
    ScriptName       : C:\Users\user\Desktop\script\main.ps1
    Line             : $db.FileGroups.Where{
 
    PositionMessage  : At C:\Users\user\Desktop\script\main.ps1:5 char:19
                       +                   $db.FileGroups.Where{
                       +                   ~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\user\Desktop\script
    PSCommandPath    : C:\Users\user\Desktop\script\main.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : <removed>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The [intrinsic `.Where()` method](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Arrays#where):

* never changes the type of elements in its input
* _always_ wraps its results in a `[System.Collections.ObjectModel.Collection[psobject]]` collection, even with just one result object (notably even when you use the `'First'` option to explicitly request a single object only).

Arguably, calling `Select-Object` _without any arguments_ should never have been allowed syntactically, but it's too late to change that.
Such a call is an effective _no-op_ (however, due to the use of the pipeline, all output objects receive the mostly-but-not-always-invisible `[psobject]` wrappers, as discussed in #5579).

In cases where `.Where()` returns a _single-element_ collection, sending it through the pipeline _implicitly_ sends just that one element itself, given that the collection is auto-enumerated in the pipeline, as most `IEnumerable`s are.

You shouldn't expect to be able to cast `[System.Collections.ObjectModel.Collection[psobject]]` to a non-collection type (even if that type is that the collection's only element's type), and this applies to other collection (list-like) types too; for instance, `[int] $i = @(42)` fails as well.

If you expect only _one_ result object, you can simply apply `[0]` to the `.Where()` call to extract it.
If you have a strict mode version in effect that prevents access to non-existing collection (list) elements, use `.Where(...) | Select-Object -First 1` to avoid errors if the result collection is _empty_.

**Comment by agowa** [comment]
`Such a call is an effective no-op`, well because of the pipe it is not...

The core issue here is that powershell partially thinks that function exists (regardless of the type), but then still fails to actually call it.

**Comment by mklement0** [comment]
> well because of the pipe it is not...

Yes - I was referring to the `Select-Object` call, not to the pipeline behavior in general (which is also explained in my previous comment). 

> The core issue here is that powershell partially thinks that function exists 

In case you're referring to the `.Rename()` _method_: it is found and invoked due to [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration), _on every element of the collection_ returned by `.Where()`.

**Comment by agowa** [comment]
> In case you're referring to the `.Rename()` _method_: it is found and invoked due to [member-access enumeration](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration), _on every element of the collection_ returned by `.Where()`.

Then there is something wrong with the specific type here. As it is not invoked but fails with the above exception. But adding either a noop Select-Object, and/or manually iterating the list using `.foreach` always works. Where as relying on the member-access enumeration does not.

**Comment by mklement0** [comment]
I don't have access to a populated `[Microsoft.SqlServer.Management.Smo.Database]` instance, but one possible explanation is that the collection returned by `.Where()` contains only a single element _that is `$null`_:

```powershell
# -> "Method invocation failed because [System.Collections.ObjectModel.Collection`1[...]] 
# does not contain a method named 'ToUInt16'"
($null).Where({ $true }).ToUInt16($null)
```

The error message is somewhat unfortunate, however.

The one you get when there is a `$null` value _among other, non-null values_ is only slightly better:

```powershell
# -> "InvalidOperation: You cannot call a method on a null-valued expression."
 (42, $null).Where({ $true }).ToUInt16($null)
```

Note that, unlike in the pipeline, no partial results are reported - the entire operation fails, even though `(42).ToUInt16($null)` in isolation would succeed.

---

So - unless your exception has yet another cause - I'd say the only actionable thing here is to ask for the member-access enumeration error messages to be improved.

**Comment by agowa** [comment]
I don't think this is the same error, as I can ensure you that the input was not $null in the case where the error occurred.

**Comment by mklement0** [comment]
So when the call fails, what do `$db.FileGroups.Where{$true}.Files` and `Get-Member -InputObject $db.FileGroups.Where{$true}.Files` return?

**Comment by agowa** [comment]
A single "Microsoft.SqlServer.Management.Smo.DataFile" object. But it also sometimes succeeds. I wasn't able to find what exactly is different when it fails to when it succeeds. I had it fail and succeed using the same command within the same powershell just to two different times before...

**Comment by mklement0** [comment]
If you can find a reliably reproducible case, I suggest creating a new, properly framed issue.

From what I can tell, the only way to reproduce your symptom is to make `.Where()` return an _empty_ collection, suggesting a `$null`-valued input object (or an input object that is an empty enumerable), so I suspect the real problem is with `$db.FileGroups.Where{$true}.Files` intermittently evaluating to `$null`.

If your expectation is for the `.Where()` call to only ever return _one_ object, use `[0]` before the `.Rename()` call (or pipe to `Select-Object -First 1`), which will make it obvious when the problem is lack of input.

---

Separately, I've created a request to improve the error messages related to member-access enumeration:

* #21051

**Comment by agowa** [comment]
Thanks, maybe the improved error message will help to better debug this issue in the future.
At the moment it is kinda impossible to debug, as even a very simple test case sometimes works and sometimes doesn't.

I had this exact code in use for a few months now and it always worked. Even with the same data. But today I got a bug report for it failing.

I just replaced it with a combination of piping through Select-Object and then also calling the enumerator explicitly.
It works so far, but considering that there is no real consistency to it, it's probably impossible at this point to narrow it down more.

What I got so far:
* Same command worked in the past, now doesn't (extra checked git blame, and that code didn't change in a while; Also it is scoped into a script block that doesn't use any global variables and only gets the sqlinstance and strings passed in).
* The error occurs on different computers, so it's not just something local (these two weren't in the same domain and also not using the same sql server nor strings for the database rename).
* It only occurs with these specific object types. At least I didn't get the error when trying the get-item example.
* When just waiting and reexecuting the same command, within the same powershell window, after 30-60 minutes may yield different results (feels like re-rolling the dice).

So maybe the better error message will help. Or someone else that is able to reproduce this issue can provide some feedback.
