### ISSUE TITLE
Class static abstract properties on interfaces don't work

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#21059]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following

```powershell
Add-Type -TypeDefinition @'
public interface IProperty
{
    static abstract int Id { get; }
}

public class CSharpProperty : IProperty
{
    public static int Id { get=> 1; }
}
'@

class PwshProperty : IProperty {
    static [int] $Id = 1
}
```

### Expected behavior

```console
You can create the class then do `[PwshProperty]::Id` to return `1`.
```

### Actual behavior

```console
ParentContainsErrorRecordException: An error occurred while creating the pipeline.
```

### Error details

```console
Type           : System.Management.Automation.RuntimeException
ErrorRecord    :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : An error occurred while creating the pipeline.
        HResult : -2146233087
    CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : RuntimeException
TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message        : An error occurred while creating the pipeline.
InnerException :
    Type       : System.ArgumentException
    Message    : Method cannot be both static and virtual.
    TargetSite : Void .ctor(System.String, System.Reflection.MethodAttributes, System.Reflection.CallingConventions, System.Type, System.Type[], System.Type[], System.Type[],
System.Type[][], System.Type[][], System.Reflection.Emit.RuntimeModuleBuilder, System.Reflection.Emit.RuntimeTypeBuilder)
    Source     : System.Private.CoreLib
    HResult    : -2147024809
    StackTrace :
   at System.Reflection.Emit.RuntimeMethodBuilder..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[]
returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type[][] parameterTypeRequiredCustomModifiers, Type[][]
parameterTypeOptionalCustomModifiers, RuntimeModuleBuilder mod, RuntimeTypeBuilder type)
   at System.Reflection.Emit.RuntimeTypeBuilder.DefineMethodCore(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[]
returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type[][] parameterTypeRequiredCustomModifiers, Type[][]
parameterTypeOptionalCustomModifiers)
   at System.Reflection.Emit.TypeBuilder.DefineMethod(String name, MethodAttributes attributes, Type returnType, Type[] parameterTypes)
   at System.Management.Automation.Language.TypeDefiner.DefineTypeHelper.EmitPropertyIl(PropertyMemberAst propertyMemberAst, Type type)
   at System.Management.Automation.Language.TypeDefiner.DefineTypeHelper.DefineProperty(PropertyMemberAst propertyMemberAst)
   at System.Management.Automation.Language.TypeDefiner.DefineTypeHelper.DefineMembers()
   at System.Management.Automation.Language.TypeDefiner.DefineTypes(Parser parser, Ast rootAst, TypeDefinitionAst[] typeDefinitions)
   at System.Management.Automation.Language.Compiler.DefinePowerShellTypes(Ast rootForDefiningTypes, TypeDefinitionAst[] typeAsts)
   at System.Management.Automation.Language.Compiler.GenerateTypesAndUsings(ScriptBlockAst rootForDefiningTypesAndUsings, List`1 exprs)
   at System.Management.Automation.Language.Compiler.CompileSingleLambda(ReadOnlyCollection`1 statements, ReadOnlyCollection`1 traps, String funcName, IScriptExtent entryExtent,
IScriptExtent exitExtent, ScriptBlockAst rootForDefiningTypesAndUsings)
   at System.Management.Automation.Language.Compiler.CompileNamedBlock(NamedBlockAst namedBlockAst, String funcName, ScriptBlockAst rootForDefiningTypes)
   at System.Management.Automation.Language.Compiler.VisitScriptBlock(ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.Compiler.Compile(CompiledScriptBlockData scriptBlock, Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.ReallyCompile(Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.CompileUnoptimized()
   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
   at System.Management.Automation.DlrScriptCommandProcessor.Init()
   at System.Management.Automation.DlrScriptCommandProcessor..ctor(ScriptBlock scriptBlock, ExecutionContext context, Boolean useNewScope, CommandOrigin origin,
SessionStateInternal sessionState, Object dollarUnderbar)
   at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, Boolean addToHistory, CommandOrigin origin)
   at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
Source         : System.Management.Automation
HResult        : -2146233087
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Arch Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Just for future reference here is how you can define a class that implements such an interface with TypeBuilder

```powershell
using namespace System.Reflection
using namespace System.Reflection.Emit

$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @'
public interface IProperty
{
    static abstract int Id { get; }
}
'@

$ab = [AssemblyBuilder]::DefineDynamicAssembly(
    [AssemblyName]::new("MyAssembly"),
    [AssemblyBuilderAccess]::Run)
$mb = $ab.DefineDynamicModule("MyModule")
$tb = $mb.DefineType(
    "MyClass",
    [TypeAttributes]::Public,
    $null,
    [type[]]@([IProperty]))

$getAttr = $tb.DefineMethod(
    "get_Id",
    [MethodAttributes]"Public, Static, HideBySig, SpecialName",
    [int],
    [type]::EmptyTypes)
$getAttrIl = $getAttr.GetILGenerator()
$getAttrIl.Emit([OpCodes]::Ldc_I4_1)
$getAttrIL.Emit([OpCodes]::Ret)
$tb.DefineMethodOverride($getAttr, [IProperty].GetMethod("get_Id"))

$pb = $tb.DefineProperty(
    "Id",
    [PropertyAttributes]::None,
    [int],
    $null)
$pb.SetGetMethod($getAttr)

$null = $tb.CreateType()

[MyClass]::Id
```

**Comment by daxian-dbw** [comment]
The Engine WG reviewed this issue and happy to see this enhancement to PowerShell class.
