### ISSUE TITLE
  Class static abstract methods on interfaces don't work

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#21060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
Add-Type -TypeDefinition @'
public interface IMethod
{
    static abstract int GetId();
}

public class CSharpMethod : IMethod
{
    public static int GetId() => 1;
}
'@

class PwshMethod : IMethod {
    static [int] GetId() { return 1 }
}
```

### Expected behavior

```console
Class is created and you can do `[PwshMethod]::GetId()` to return `1`.
```

### Actual behavior

```console
ParserError:
Line |
   1 |  class PwshMethod : IMethod {
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error during creation of type "PwshMethod". Error message: Virtual static method 'GetId' is not implemented on type 'PwshMethod' from assembly 'PowerShell Class Assembly,
     | Version=1.0.0.1, Culture=neutral, PublicKeyToken=null'.
```

### Error details

```console
Type        : System.Management.Automation.ParseException
Errors      :
    Extent  : class PwshMethod : IMethod {
              static [int] GetId() { return 1 }
              }
    ErrorId : TypeCreationError
    Message : Error during creation of type "PwshMethod". Error message:
              Virtual static method 'GetId' is not implemented on type 'PwshMethod' from assembly 'PowerShell Class Assembly, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null'.
Message     : At line:1 char:1
              + class PwshMethod : IMethod {
              + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              Error during creation of type "PwshMethod". Error message:
              Virtual static method 'GetId' is not implemented on type 'PwshMethod' from assembly 'PowerShell Class Assembly, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null'.
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : At line:1 char:1
                  + class PwshMethod : IMethod {
                  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  Error during creation of type "PwshMethod". Error message:
                  Virtual static method 'GetId' is not implemented on type 'PwshMethod' from assembly 'PowerShell Class Assembly, Version=1.0.0.1, Culture=neutral,
PublicKeyToken=null'.
        HResult : -2146233087
    CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : TypeCreationError
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : -1
        Line             : class PwshMethod : IMethod {

        Statement        : class PwshMethod : IMethod {
                           static [int] GetId() { return 1 }
                           }
        PositionMessage  : At line:1 char:1
                           + class PwshMethod : IMethod {
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CommandOrigin    : Internal
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.4.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Arch Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Just for future reference here is how you can define a class that implements such an interface with TypeBuilder

```powershell
using namespace System.Reflection
using namespace System.Reflection.Emit

$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @'
public interface IMethod
{
    static abstract int GetId();
}
'@

$ab = [AssemblyBuilder]::DefineDynamicAssembly(
    [AssemblyName]::new("MyAssembly"),
    [AssemblyBuilderAccess]::Run)
$mb = $ab.DefineDynamicModule("MyModule")
$tb = $mb.DefineType(
    "MyClass",
    [TypeAttributes]::Public,
    $null,
    [type[]]@([IMethod]))

$getAttr = $tb.DefineMethod(
    "GetId",
    [MethodAttributes]"Public, Static",
    [int],
    [type]::EmptyTypes)
$getAttrIl = $getAttr.GetILGenerator()
$getAttrIl.Emit([OpCodes]::Ldc_I4_1)
$getAttrIL.Emit([OpCodes]::Ret)
$tb.DefineMethodOverride($getAttr, [IMethod].GetMethod("GetId"))

$null = $tb.CreateType()

[MyClass]::GetId()
```

**Comment by rhubarb-geek-nz** [comment]
How can you have static properties or methods on an interface when an interface depends on having a 'this'?

I would have expected the only static things an interface could have would be constants. 

How do you invoke a static method from an interface?

**Comment by jborean93** [comment]
It's a new feature added in C# 11 https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/static-virtual-interface-members. Just like any other static property/method, the implementation can only reference other static properties/methods on that same interface/type.

> How do you invoke a static method on an interface?

You don't invoke it on the interface you still invoke it on the class that implements the abstract property/method.

```powershell
Add-Type @'
public interface IMethod
{
    static abstract int GetId();
}

public class MyClass
{
    public static int GetId() => 1;
}
'@

# Can be called directly on the class like any other static member
[MyClass]::GetId()
```

**Comment by daxian-dbw** [comment]
The Engine WG reviewed this issue and happy to see this enhancement to PowerShell class.
