### ISSUE TITLE
The -ProgressAction parameter doesn't work (PowerShell 7.4.1 only)

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#21074]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Upon using the -ProgressAction switch, PowerShell returns an error message regardless of correct formatting. Please see the examples below.

### Expected behavior

```
PS > Expand-Archive -Path .\1.zip -DestinationPath ".\1" -ProgressAction 'SilentlyContinue'

PS > Repair-Volume -DriveLetter c -Scan -ProgressAction 'SilentlyContinue'

NoErrorsFound
```

### Actual behavior

```
PS > Expand-Archive -Path .\1.zip -DestinationPath ".\1" -ProgressAction 'SilentlyContinue'

Expand-Archive: Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."

PS > Repair-Volume -DriveLetter c -Scan -ProgressAction 'SilentlyContinue'

Repair-Volume: Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."
```

### Error details

```
Exception             :
    Type           : System.Management.Automation.PSInvalidCastException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference'
to 'System.Collections.IEnumerator'."
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidCastIConvertible
    TargetSite     :
        Name          : ConvertIConvertible
        DeclaringType : System.Management.Automation.LanguagePrimitives
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to
'System.Collections.IEnumerator'."
    InnerException :
        Type       : System.InvalidCastException
        TargetSite :
            Name          : DefaultToType
            DeclaringType : System.Convert
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'.
        Source     : System.Private.CoreLib
        HResult    : -2147467262
        StackTrace :
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.Management.Automation.LanguagePrimitives.ConvertIConvertible(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert,
IFormatProvider formatProvider, TypeTable backupTable)
    Source         : System.Management.Automation
    HResult        : -2147467262
    StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertIConvertible(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert,
IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert,
IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable
backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo[T](Object valueToConvert)
   at System.Management.Automation.MutableTuple`64.SetValueImpl(Int32 index, Object value)
   at System.Management.Automation.PSScriptCmdlet.SetPreferenceVariables()
   at System.Management.Automation.PSScriptCmdlet.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : InvalidArgument: (:) [Repair-Volume], PSInvalidCastException
FullyQualifiedErrorId : InvalidCastIConvertible,Repair-Volume
InvocationInfo        :
    MyCommand        : Repair-Volume
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Repair-Volume -DriveLetter c -Scan -ProgressAction 'SilentlyContinue'
    Statement        : Repair-Volume -DriveLetter c -Scan -ProgressAction 'SilentlyContinue'
    PositionMessage  : At line:1 char:1
                       + Repair-Volume -DriveLetter c -Scan -ProgressAction 'SilentlyContinue'
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Repair-Volume
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Output](https://github.com/PowerShell/PowerShell/assets/17097175/2baadd2b-a3e1-4e78-91d2-908710f2bc88)

**Comment by mklement0** [comment]
Related:

* #20725 
* #20657

**Comment by skycommand** [comment]
@mklement0 I'll check both. The second one is a feature request, though.

**Comment by skycommand** [comment]
Update regarding #20657.

It is impossible to reproduce #20657 in PowerShell 7.4.1 because of this thread's new bug. Here is my attempt:

```PowerShell
function test {
   [CmdletBinding()]
   param()
   Write-Output 'Something'
}

Write-Output ('-' * 40)
Write-Output 'Test -ProgressAction SilentlyContinue'
Test -ProgressAction SilentlyContinue

Write-Output ('-' * 40)
Write-Output 'Test -ProgressAction [System.Management.Automation.ActionPreference]::SilentlyContinue'
Test -ProgressAction [System.Management.Automation.ActionPreference]::SilentlyContinue
```

Here is the result:

```Output
----------------------------------------
Test -ProgressAction SilentlyContinue
test:
Line |
   9 |  Test -ProgressAction SilentlyContinue
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Specified argument was out of the range of valid values. (Parameter 'index')
----------------------------------------
Test -ProgressAction [System.Management.Automation.ActionPreference]::SilentlyContinue
test:
Line |
  13 |  … gressAction [System.Management.Automation.ActionPreference]::Silently …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'ProgressAction'. Cannot convert value "[System.Management.Automation.ActionPreference]::SilentlyContinue" to type "System.Management.Automation.ActionPreference". Error: "Unable to match the identifier name [System.Management.Automation.ActionPreference]::SilentlyContinue to a valid enumerator name. Specify one of the following enumerator names and try again:
SilentlyContinue, Stop, Continue, Inquire, Ignore, Suspend, Break"
```

**Comment by mklement0** [comment]
Thanks, @skycommand - #20657 is unequivocally a bug too, given that using `-ProgressAction` _breaks_ calls to advanced functions / scripts (I've updated the issue's title to make that clearer).

By contrast, failure of `Test -ProgressAction [System.Management.Automation.ActionPreference]::SilentlyContinue` is expected, because, due to [argument-mode parsing](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing?view=powershell-7.4#argument-mode), `[System.Management.Automation.ActionPreference]::SilentlyContinue` is treated as a _string_;  for it to be recognized _as an expression_, you'd have to enclose it in `(...)`

**Comment by ninbura** [comment]
I'm getting a slightly different error.
```PowerShell
Compress-Archive -Path "$configDirectory/*" -DestinationPath "$backupDirectory/$computerName $dateTime.zip" -CompressionLevel Fastest -ProgressAction SilentlyContinue -Force
```
```PowerShell
Cannot convert value "SilentlyContinue" to type "System.Management.Automation.SwitchParameter". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System
.Management.Automation.SwitchParameter'."
```

Using `([system.management.automation.actionpreference]::SilentlyContinue)` instead of `SilentlyContinue` provides the same error. No idea what `System.Management.Automation.SwitchParameter` is.

**Comment by bernosek** [comment]
I'm getting same error when calling Test-NetConnection in PowerShell 7.4.3:
```powershell
Test-NetConnection -ComputerName $Hostname -Port $Port -ProgressAction "SilentlyContinue"
```
Response is:
```powershell
Test-NetConnection: Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."
```
So this error is also in PowerShell 7.4.3, no only in 7.4.1. I guess it will be the same with 7.4.2.
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
When you are going to fix it?

**Comment by JustinGrote** [comment]
Still an issue in 7.4.4 when passing as a splat:

```powershell
❯ $splat = @{ProgressAction = 'continue'};function test {[cmdletbinding()]param()"Do nothing!"};test @splat
test: Specified argument was out of the range of valid values. (Parameter 'index')
```

**Comment by mklement0** [comment]
@JustinGrote, the bug actually surfaces whether or not you use splatting (`test -ProgressAction Continue`;  in the `Parameter 'index'` form it is the focus of #20657).

The other two manifestations are `"Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."` and `"Invalid cast from 'System.Management.Automation.ActionPreference' to 'System
.Management.Automation.SwitchParameter'."`. (@ninbura, the latter type, whose accelerator is `[switch]`, refers to a flag-like parameter, such as `-Force` - it's unclear why either of these conversions are attempted).

What all affected commands have in common is that they're _advanced functions_ rather than binary cmdlets (but I don't know what determines which form manifests when).

**Comment by jborean93** [comment]
We've looked into this in the PS Discord and found the cause behind it. When a script function is compiled it uses a tuple to store the value of the parameters and other local variables. The first few indexes of the tuples contain some special vars like `$_`, `$PSCmdlet`, etc, the next set are the common parameters, before the parameters/local variables after that. The current code didn't have the new progress preference in an enum so that the index that stores the `-ProgressAction` was defined for the first parameter/local var used in the cmdlet.

You can see that when there were no parmeters or vars set the error message is slightly different because the tuple isn't large enough

```powershell
Function Test-Function {
    [CmdletBinding()]
    param()
}

Test-Function -ProgressAction Ignore
# Test-Function: Specified argument was out of the range of valid values. (Parameter 'index')
```

When there is a parameter or variable defined you can reproduce the error by explicitly typing it to something `ActionPreference` cannot be casted to

```powershell
Function Test-Function {
    [CmdletBinding()]
    param()

    [System.IO.FileInfo]$var = $null
}

Test-Function -ProgressAction Ignore
# Test-Function: Cannot convert value "Ignore" to type "System.IO.FileInfo". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.IO.FileInfo'."
```

In the `Expand-Archive` case the `switch` in the definition occupies the slot under the special/internal `using` var that is typed to an `IEnumerator` hence the casting failing for that type

```powershell
Function Test-Function {
    [CmdletBinding()]
    param()

    switch($false) { default {} }
}

Test-Function -ProgressAction Ignore
# Test-Function: Cannot convert value "Ignore" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."
```

A side effect of this is that you can actually see the parameter affecting the variable if the cast works as the engine will assign the `-ProgressAction` to the tuple for that next variable

```powershell
Function Test-Function {
    [CmdletBinding()]
    param ([int]$Test)

    $Test
}

Test-Function -ProgressAction Ignore
# 4
```

@cmkb3 found the enum that was missing the required entry to ensure the tuple leaves the progress action index free for its variable so they'll open a PR with the required changed.

**Comment by skycommand** [comment]
@jborean93 That's a lot to grasp. Has it always been like this? Or is this a regression?

**Comment by jborean93** [comment]
Considering the issue was because an enum member was missing I assume it was just missed during the implementation in 7.4.

**Comment by cmkb3** [comment]
> @jborean93 That's a lot to grasp. Has it always been like this? Or is this a regression?

Boils down to an index out of bounds issue on an array. Re: @jborean93 's reply -- it was a small miss during implementation as a common parameter ~2 years ago (#18887) in 9.4.0.

**Comment by StewartRyanSony** [comment]
Still running into this issue in version 7.5.0. I see the PR is still open. Where are we on this?

**Comment by BjOrn-rsd** [comment]
Im on 7.5.2, still an issue it seems.

```
$Ping = Test-NetConnection -ComputerName $Computer -InformationLevel Quiet -WarningAction SilentlyContinue -ErrorAction SilentlyContinue -ProgressAction SilentlyContinue
Test-NetConnection: Cannot convert value "SilentlyContinue" to type "System.Collections.IEnumerator". Error: "Invalid cast from 'System.Management.Automation.ActionPreference' to 'System.Collections.IEnumerator'."
```

**Comment by fourpastmidnight** [comment]
Agreed, still an issue on 7.6.0-preview.2! I beat my head against a wall for _HOURS_ because of this!

**Comment by BalassaMarton** [comment]
Why is this closed? It's still not working in 7.5.2.

**Comment by mklement0** [comment]
The PR with the apparent fix, #24591, has been merged, but isn't part of a release yet.

At least currently it is _not_ labeled for back-porting to v7.5.x, which means that it will only land in the next _preview_ version of v7.6., and therefore eventually in v7.6.0
