### ISSUE TITLE
Bug - Format-Default - Cannot process argument because the value of argument "name" is not valid

### ISSUE THREAD

**Issue by BernieWhite** [PowerShell/PowerShell#21147]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The issue is specific to `TableControl` with that pulls from a localized resource.

### Expected behavior

```console
This starts failing from PS 7.4.


<View>
      <Name>PSRule.Rules.RuleRecord</Name>
      <ViewSelectedBy>
        <TypeName>PSRule.Rules.RuleRecord</TypeName>
      </ViewSelectedBy>
      <GroupBy>
        <PropertyName>TargetName</PropertyName>
      </GroupBy>
      <TableControl>
        <TableHeaders>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="RuleName"/>
            <Width>35</Width>
          </TableColumnHeader>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="Outcome"/>
            <Width>10</Width>
          </TableColumnHeader>
          <TableColumnHeader>
            <Label AssemblyName="Microsoft.PSRule.Core" BaseName="PSRule.Resources.ViewStrings" ResourceId="Recommendation"/>
          </TableColumnHeader>
        </TableHeaders>
        <TableRowEntries>
          <TableRowEntry>
            <TableColumnItems>
              <TableColumnItem>
                <PropertyName>RuleName</PropertyName>
              </TableColumnItem>
              <TableColumnItem>
                <PropertyName>Outcome</PropertyName>
              </TableColumnItem>
              <TableColumnItem>
                <PropertyName>Recommendation</PropertyName>
              </TableColumnItem>
            </TableColumnItems>
          </TableRowEntry>
        </TableRowEntries>
      </TableControl>
    </View>
```

### Actual behavior

```console
Generates exception.
```

### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type        : System.Management.Automation.PSArgumentException
        ErrorRecord :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : Argument
        Message     : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
        ParamName   : name
        TargetSite  :
            Name          : get_Item
            DeclaringType : System.Management.Automation.PSMemberInfoIntegratingCollection`1[T]
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Source      : System.Management.Automation
        HResult     : -2147024809
        StackTrace  :
   at System.Management.Automation.PSMemberInfoIntegratingCollection`1.get_Item(String name)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateTableHeaderInfoFromDataBaseInfo(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.WriteFormatStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    CategoryInfo          : InvalidArgument: (:) [format-default], PSArgumentException
    FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.FormatDefaultCommand
    InvocationInfo        :
        MyCommand       : format-default
        HistoryId       : 3
        CommandOrigin   : Internal
    ScriptStackTrace      : at Invoke-PSRule<Process>, D:\Dev\Workspace\PSRule\out\modules\PSRule\PSRule.psm1: line 181
                            at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :



TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation, Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message        : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
InnerException :
    Type        : System.Management.Automation.PSArgumentException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : Argument
    Message     : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
    ParamName   : name
    TargetSite  :
        Name          : get_Item
        DeclaringType : System.Management.Automation.PSMemberInfoIntegratingCollection`1[T]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source      : System.Management.Automation
    HResult     : -2147024809
    StackTrace  :
   at System.Management.Automation.PSMemberInfoIntegratingCollection`1.get_Item(String name)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateTableHeaderInfoFromDataBaseInfo(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.TableViewGenerator.GenerateStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.WriteFormatStartData(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Source         : System.Management.Automation
HResult        : -2146233087
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BernieWhite** [comment]
@daxian-dbw @SteveL-MSFT Do we know when this might ship?
