### ISSUE TITLE
Can't import v1.0.2 to pwsh.exe v7.4.1 with error "Import-Module: Assembly with same name is already loaded"

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#21201]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

* Install [`Microsoft.PowerShell.PSResourceGet` v1.0.2](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet/1.0.2).

#### Using pwsh.exe v7.4.1

* Open pwsh.exe, enter `Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.0.2 -Verbose -Debug`

#### Using VSCode

* Start a clean VSCode v1.86.0 session with [`vscode-powershell` extension v2024.0.0](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) and [PowerShell v7.4.1](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.1)
* Run `Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.0.2 -Verbose -Debug` in the PowerShell terminal inside VSCode

### Expected behavior

Module should load without problems, just like it does when doing the same from pwsh.exe

### Actual behavior

```console
PS C:\Users\olav.birkeland> Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.0.2 -Verbose -Debug
VERBOSE: Loading module from path 'C:\program files\powershell\7\Modules\Microsoft.PowerShell.PSResourceGet\Microsoft.PowerShell.PSResourceGet.psd1'.
VERBOSE: Loading module from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\Microsoft.PowerShell.PSResourceGet.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\PSGet.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\Microsoft.PowerShell.PSResourceGet.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\PSGet.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.PowerShell.PSResourceGet.
VERBOSE: Loading module from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\Microsoft.PowerShell.PSResourceGet.psm1'.
VERBOSE: Exporting function 'Import-PSGetRepository'.
VERBOSE: Importing function 'Import-PSGetRepository'.
VERBOSE: Loading module from path 'C:\Users\olav.birkeland\AppData\Local\Microsoft\PowerShell\Modules\Microsoft.PowerShell.PSResourceGet\1.0.2\Microsoft.PowerShell.PSResourceGet.dll'.
Import-Module: Assembly with same name is already loaded
PS C:\Users\olav.birkeland>
```

### Error details

```console
Exception             : 
    Type       : System.IO.FileLoadException
    Message    : Assembly with same name is already loaded
    TargetSite : 
        Name          : LoadBinaryModule
        DeclaringType : Microsoft.PowerShell.Commands.ModuleCmdletBase
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source     : System.Management.Automation
    HResult    : -2146232799
    StackTrace : 
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Object privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(String moduleBase, ManifestProcessingFlags manifestProcessingFlags, ImportModuleOptions importModuleOptions, Boolean& found)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        : 
    MyCommand        : Import-Module
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.0.2 -Verbose -Debug
    Statement        : Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.0.2 -Verbose -Debug
    PositionMessage  : At line:1 char:1
                       + Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVer ΓÇª
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

* Windows 11 23H2
* Visual Studio Code v1.86.0 x64
* vscode-powershell extension v2024.0.0
* Microsoft.PowerShell.PSResourceGet v1.0.3
* PowerShell v7.4.1 x64

**Comment by o-l-a-v** [comment]
Here is an easy and reliable repro of this issue.

Prerequisite: Module of lower version must not be inside a versioned folder.

* This is what happens when PSResourceGet is embedded inside a PowerShell release, but not in a versioned directory.

Does not repro:

```text
ModulesAllVersioned
├─ Modules1
│  └─ Microsoft.PowerShell.PSResourceGet
│     └─ 1.0.6
│        └─ <content>
└─ Modules2
   └─ Microsoft.PowerShell.PSResourceGet
      └─ 1.1.0
         └─ <content>
```

Does repro:

```text
ModulesFirstNotVersioned
├─ Modules1
│  └─ Microsoft.PowerShell.PSResourceGet
│     └─ <content>
└─  Modules2
    └─ Microsoft.PowerShell.PSResourceGet
       └─ 1.1.0
          └─ <content>
```

Repro:

* Start PowerShell with no profile: `pwsh -NoProfile`

```pwsh
# Set PSModulePath in process scope
$env:PSModulePath = (
    '{0}\ModulesFirstNotVersioned\Modules1;{0}\ModulesFirstNotVersioned\Modules2' -f
    [System.Environment]::GetFolderPath('Desktop')
)

# Import Microsoft.PowerShell.PSResourceGet v1.1.0
Import-Module -Name 'Microsoft.PowerShell.PSResourceGet' -RequiredVersion 1.1.0 -Verbose -Debug
```

**Comment by RPitt** [comment]
Trying to add some insight, this is my understanding:

### Background:
PowerShell is supposed to be able to manage module versions side-by-side, loading appropriate version as required.
However a fundamental limitation in the scheme is that PowerShell can't unload .Net assemblies.
This is problematic for versioned modules that depends on versioned assemblies like so
- 1.0.0\modulename.psd1 uses assemblyname.dll v1.0.0
- 1.0.1\modulename.psd1 uses assemblyname.dll v1.0.1

Because once the modulename +assembly is loaded at one version, there's no way to switch to a different version in that **session**, that's what `Assembly with same name is already loaded` is saying.

### Import-Module version searching bug?

I think the @o-l-a-v has rightly identified that there is something defficent in the version searching / loading logic.

My suspicion is that for modules in versioned subfolders (e.g. `1.0.1\`) PowerShell uses the folder name as quick indicator of the version whilst building a list of candidates.
However for modules that are not in a versioned folder it seems to **actually load** the module even before it's determined if its the appropraite version.
This then causes the problem when it later tries to load the actually desired version and hits an error because the previous version is already loaded.

^ I'm hoping someone else can anaylse and confirm or disprove my suspcion.


### @danielniccoli
Note, whilst your error has similarities I suspect your error is just down to a bad/mixed install of Microsoft.Graph components.
Check your versions with `Get-Module -ListAvailable Microsoft.Graph*` and if they're inconsistent I'd suggest uninstall/deleting them and re-installing Microsoft.Graph
