### ISSUE TITLE
"Out-File -Encoding utf8NoBOM" return errors in Windows 10 Ja-Jpn installed powershell version 7.4.1 script.

### ISSUE THREAD

**Issue by j-shimoda** [PowerShell/PowerShell#21202]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Generating a script named "out-file.ps1" with first line "Out-File -FilePath C:\Users\Administrator\Documents\aaa.csv -Encoding utf8NoBOM".
2. Execute the script in Powershell 7.4.1 command window such as below.
   "PowerShell -ExecutionPolicy RemoteSigned .\out-file.ps1"

### Expected behavior

```console
Following powershell command returns no error in powershell version7.4.1 and generate aaa.csv.
"Out-File -FilePath C:\Users\Administrator\Documents\aaa.csv -Encoding utf8NoBOM"

"-Encoding utf8NoBOM" parameter should be supported running any powershell scripts. 
But I am new to generate and execute powershell script, so need any update regarding this error or behavior.
```

### Actual behavior

```console
The script returns following error.

Out-File : パラメーター 'Encoding の引数を確認できません。引数 "utf8NoBOM" は、ValidateSet 属性で指定されたセット "unknown,string,unicode,bigendianunicode,utf8,utf7,utf32,ascii,default,oem" に属していません。このセットの引数を指定して、コマンドを再度実行してください。
発生場所 C:\Users\Administrator\documents\out-file.ps1:1 文字:71
+ ... FilePath C:\Users\Administrator\Documents\aaa.csv -Encoding utf8NoBOM
+                                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-File]、ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.OutFileCommand
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'out-file.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : out-file.ps1
        CategoryInfo          : ObjectNotFound: (out-file.ps1:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 40
            Line             : out-file.ps1
            Statement        : out-file.ps1
            PositionMessage  : At line:1 char:1
                               + out-file.ps1
                               + ~~~~~~~~~~~~
            InvocationName   : out-file.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : out-file.ps1
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.4.1.500,
 Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'out-file.ps1' is not recognized as a name of a cmdlet, function, script file, or executable
 program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try ag
ain.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : out-file.ps1
CategoryInfo          : ObjectNotFound: (out-file.ps1:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 40
    Line             : out-file.ps1
    Statement        : out-file.ps1
    PositionMessage  : At line:1 char:1
                       + out-file.ps1
                       + ~~~~~~~~~~~~
    InvocationName   : out-file.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
You're mistakenly using [`powershell.exe`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe), the _Windows PowerShell_ CLI, rather than [`pwsh.exe`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh), the _PowerShell (Core)_ CLI.

In Windows PowerShell, `-Encoding` doesn't support `utf8NoBOM` (and `utf8` means: UTF-8 _with BOM_).
In PowerShell (Core), `utf8NoBOM` is the _default_ (and `utf8` is the same as `utf8NoBOM`).

**Comment by arnaudhelin** [comment]
Hi @mklement0,

I have to disagree. I just have the case where I made an Out-File xxxxx (encoding by default), and I had UTF8. So, **No** utf8 is not the same as utf8NoBOM.

**Comment by mklement0** [comment]
@arnaudhelin 

> I had UTF8

UTF8 _with_ or _without_ a BOM?

In [_PowerShell (Core) 7_](https://github.com/PowerShell/PowerShell/blob/master/README.md) (which this repo is about, `-Encoding utf8` and `-Encoding utf8NoBom` are the same, and tantamount to omitting an `-Encoding` argument; that is, you get UTF-8 files _without a BOM_.

To create files _with_ a BOM in PowerShell 7, use `-Encoding utf8BOM`.
