### ISSUE TITLE
ForEach-Object -Parallel does not accept a scriptblock variable containing a $using

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/PowerShell#21332]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Test.ps1

```powershell
Param (
    [Parameter(Mandatory)]
    [String]$FruitName,
    [Parameter(Mandatory)]
    [Int]$MaxConcurrentJobs
)

$scriptBlock = {
    #region Declare variables for parallel execution
    if (-not $MaxConcurrentJobs) {
        $FruitName = $using:FruitName
    }
    #endregion

    $FruitName
}

#region Run code serial or parallel
$foreachParams = if ($MaxConcurrentJobs -eq 1) {
    @{
        Process = $scriptBlock
    }
}
else {
    @{
        Parallel      = $scriptBlock
        ThrottleLimit = $MaxConcurrentJobs
    }
}
#endregion

0..2 | ForEach-Object @foreachParams
```

### Run the code
```powershell
$params = @{
    FilePath          = '.\Test.ps1'
    ArgumentList      = @( 'kiwi', 2 )
    ComputerName      = 'PC1'
    ConfigurationName = 'PowerShell.7'
    ErrorAction       = 'Stop'
}
Invoke-Command @params -Verbose

$argumentList = $params.ArgumentList
& $params.FilePath @argumentList
```

Probably a regression, see [PR-16564](https://github.com/PowerShell/PowerShell/pull/16564)

### Expected behavior

```console
'kiwi'
'kiwi'
'kiwi'
```

### Actual behavior

```console
> The value of the using variable '$using:FruitName' cannot be retrieved because it has not been set in the local session.
```

### Error details

```console
Exception             : 
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The value of the using variable '$using:FruitName' cannot be retrieved because it has not been set in the local session.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : UsingVariableIsUndefined
        InvocationInfo        : 
            ScriptLineNumber : 11
            OffsetInLine     : 22
            HistoryId        : -1
            ScriptName       : T:\Test.ps1
            Line             : $FruitName = $using:FruitName

            Statement        : $using:FruitName
            PositionMessage  : At T:\Test.ps1:11 char:22
                               +         $FruitName = $using:FruitName
                               +                      ~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 13
    TargetSite  : 
        Name          : GetUsingVariableValues
        DeclaringType : Microsoft.PowerShell.Commands.PSExecutionCmdlet
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The value of the using variable '$using:FruitName' cannot be retrieved because it has not been set in the local session.
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  : 
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.GetUsingVariableValues(List`1 paramUsingVars)
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.GetConvertedScript(List`1& newParameterNames, List`1& newParameterValues)
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.GetPowerShellForPSv2()
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.CreatePipeline(RemoteRunspace remoteRunspace)
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.CreateHelpersForSpecifiedComputerNames()
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.BeginProcessing()
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : InvalidOperation: (:) [Invoke-Command], RuntimeException
FullyQualifiedErrorId : UsingVariableIsUndefined,Microsoft.PowerShell.Commands.InvokeCommandCommand
InvocationInfo        : 
    MyCommand        : Invoke-Command
    ScriptLineNumber : 13
    OffsetInLine     : 1
    HistoryId        : 59
    Line             : Invoke-Command @params -Verbose
    Statement        : Invoke-Command @params -Verbose
    PositionMessage  : At line:13 char:1
                       + Invoke-Command @params -Verbose
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-Command
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 13
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Interesting. The problem equally affects nested `Start-ThreadJob` and `Start-Job` calls and also affects Windows PowerShell, so it long predates #16564 (though they're conceptually related).

It seems to come down to this: when the content of a `-FilePath` script file - which is meant to execute _remotely_ - is first parsed _locally_, the existence of _local_ variables in the context of the _caller_ is mistakenly enforced for `$using:` references inside _nested_ `$using:` contexts (`ForEach-Object -Parallel`, `Star-ThreadJob`, `Start-Job`)

Here's a minimal example:

```powershell
# !! FAILS:
#   "The value of the using variable '$using:foo' cannot be retrieved 
#     because it has not been set in the local session."
'$foo = 1; ForEach-Object -Parallel { $using:foo }' > t.ps1
Invoke-Command -ComputerName Bar -FilePath t.ps1
```

Note that direct local invocation (`./t.ps1`) works just fine.

**Comment by 237dmitry** [comment]
> The problem equally affects nested Start-ThreadJob and Start-Job calls

I did not find any problems in pwsh on Linux:

```powershell
$ gc ./t.ps1
$foo = 1; 0..2 | ForEach-Object -Parallel { $using:foo }

$ Start-ThreadJob ./t.ps1

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
73     Job73           ThreadJob       NotStarted    False           PowerShell           ./t.ps1

$ Receive-Job -id 73
1
1
1
 
$ Get-Job | Remove-Job
```

PS. Invoke-Expression does not work at all (no WSMan)

**Comment by mklement0** [comment]
@237dmitry, the problem at hand is about nested `$using` contexts _in the context of remoting_, so your sample code doesn't apply (and, as I had already noted, "Note that direct local invocation (`./t.ps1`) works just fine.").

If you want to manifest the problem on Unix-like platforms, simply replace `-ComputerName` with `-Host` (`Invoke-Command -Host Bar -FilePath t.ps1`)

**Comment by 237dmitry** [comment]
> the problem at hand is about nested $using contexts in the context of remoting

ssh works fine, but Invoke-Command....

```
$ Invoke-Command -HostName localhost -FilePath ./t.ps1
user@localhost's password: 
subsystem request failed on channel 0
OpenError: [localhost] The SSH client session has ended with error message: The SSH transport process has abruptly terminated causing this remote session to break.
```

Try to escaped ``` `$using:var ```. I could not test

**Comment by jborean93** [comment]
Easiest way to test `Invoke-Command` without any networking endpoints setup

```powershell
$foo = 'bar'

$psProc = New-PSSession -UseWindowsPowerShell
Invoke-Command -Session $psProc -ScriptBlock { $using:foo }
$psProc | Remove-PSSession
```

On Windows `-UseWindowsPowerShell` starts a local `powershell.exe` process as the target session whereas on non-Windows it just starts a new `pwsh` process.

**Comment by 237dmitry** [comment]
This work without starting issue:

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/50ee04a1-67f5-4de9-b6a7-ee06c74506ae)

**Comment by 237dmitry** [comment]
>  you should see this fail on Unix-like platforms too

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/878cd180-e7bf-444e-ba9c-60f6ad6e67ae)

**Comment by mklement0** [comment]
@237dmitry: 

Do _not_ define a `$foo` variable _locally_, because the code then _accidentally_ works. 

Run the repro exactly as provided.

The point is that the _nested_ `$using:foo` reference - the one inside the `ForEach-Object -Parallel` script block - should _not_ depend on the presence of a `$foo` variable in the caller's scope.

**Comment by mklement0** [comment]
> Yes, when $foo set not in script (t.ps1), the error occurs

Yes, but that part _works as designed_: in the context of `t.ps1` alone, `$using:foo` inside `ForEach-Object -Parallel` requires `$foo` to exist in _its_ caller's scope (which is the remotely executing `t.ps1` code). It's the same as trying
`& { rv -ea 4 foo; % -parallel { $using:foo} }`  locally, which equally fails.

**Comment by mklement0** [comment]
@237dmitry, to avoid creating a distraction I've hidden my responses to your comments.
Assuming we've reached a shared understanding, I encourage you to hide your comments too.

**Comment by dsczltch** [comment]
I can confirm mklement0 case. 
We also have the same issue with a paralelle foreach using "using" keyword inside the loop without using Invoke-Command.
Also same issue with Start-ThreadJob.

**Comment by TobiasPSP** [comment]
This seems to be a simple local parser issue:
```powershell
Invoke-Command -ScriptBlock { 
    & { $FruitName = $using:FruitName }
}  -ComputerName any
```

This throws the exception w/o ever initiating remoting or using any parallel loop.

**Comment by DarkLite1** [comment]
Is there currently a known workaround for this issue?

**Comment by mklement0** [comment]
Good point, @DarkLite1:

* Initializing `$foo`  in the caller's scope (the first `$foo = 1`) makes the _error_ go away ...
* ... but the nested `$using:foo` reference (inside the `ForEach-Object -Parallel` script block) then unexpectedly _evaluates to `$null`_.

I'm not aware of a workaround, other than making per-input-object `Start-ThreadJob` calls with `-ArgumentList` in lieu of using `ForEach-Object -Parallel`
