### ISSUE TITLE
MacOS 14.4 breaks X509 Certificate that are marked with Exportable keys

### ISSUE THREAD

**Issue by phatmandrake** [PowerShell/PowerShell#21357]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

So this is a MacOS/dotnet issue, but my understanding is that it would necessitate updating Powershell to patch.

The following code was working on MacOS 14.3, but now fails on multiple devices after a 14.4 update.

```powershell
$certPath = "/Path/to/cert.p12"
$certPswd = "secret"

$Cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certPath, $certPswd,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable )

$rsaPrivate = $Cert.PrivateKey
$rsa = New-Object System.Security.Cryptography.RSACryptoServiceProvider
$null = $rsa.ImportParameters($rsaPrivate.ExportParameters($true)) #Errors here
```

It appears to be related to the following dotnet issue:

https://github.com/dotnet/runtime/issues/99735

Which patched around the 14.4 change, which I believe would require powershell to update it's dotnet dependencies to accommodate as well.

### Expected behavior

```console
Successfully import certificate parameters marked as exportable.
```

### Actual behavior

```console
Exception calling "ExportParameters" with "1" argument(s): "The operation couldn't be completed. (OSStatus error -67738 - CSSM Exception: -2147415780 CSSMERR_CSP_INVALID_KEYATTR_MASK)"
```

### Error details

```console
ErrorRecord                 : Exception calling "ExportParameters" with "1" argument(s): "The operation couldn’t be completed. (OSStatus error -67738 - CSSM 
                              Exception: -2147415780 CSSMERR_CSP_INVALID_KEYATTR_MASK)"
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
Message                     : Exception calling "ExportParameters" with "1" argument(s): "The operation couldn’t be completed. (OSStatus error -67738 - CSSM 
                              Exception: -2147415780 CSSMERR_CSP_INVALID_KEYATTR_MASK)"
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : Interop+AppleCrypto+AppleCFErrorCryptographicException: The operation couldn’t be completed. (OSStatus error -67738 - CSSM 
                              Exception: -2147415780 CSSMERR_CSP_INVALID_KEYATTR_MASK)
                                 at Interop.AppleCrypto.TrySecKeyCopyExternalRepresentation(SafeSecKeyRefHandle key, Byte[]& externalRepresentation)
                                 at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.ExportParameters(Boolean includePrivateParameters)
                                 at CallSite.Target(Closure, CallSite, Object, Boolean)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                                 at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Darwin 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xn…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Looks like the dotnet issue was fixed, PowerShell will get those updates at the new dotnet versions come out, closing for now but if this issue still persists after dotnet 8.0.4, 7.0.18, and 6.0.29, then we can reopen or open a new issue. Thanks @phatmandrake!
