### ISSUE TITLE
Unable to Resolve Parameter Set When Dynamic Parameter Qualifies Parameter Set

### ISSUE THREAD

**Issue by netsec4u** [PowerShell/PowerShell#21500]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using dynamic parameters with parameter set where the selection of parameter set is dependent on, the error "Parameter set cannot be resolved using the specified named parameters." is returned.

The function below, Test-StaticParameter, results in Get-Help showing eight parameter sets as expected.

```
enum MyEnum {
	Default;
	ValueA;
	ValueB;
	ValueC;
	ValueD
}
function Test-StaticParameter {
	[CmdletBinding(
		DefaultParameterSetName="Default-String1"
	)]

	PARAM (
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Default-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[string]$String1,

		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Default-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[string]$String2,

		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Default-String1'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Default-String2'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[MyEnum]$Type = 'Default',

		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[int]$Count,

		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[int64]$DynamicParam
	)

	BEGIN {
	}

	PROCESS {
		Write-Output $PSCmdlet.ParameterSetName
	}

	END {
	}
}
```

However, if you convert the DynamicParam parameter to a dynamic parameter, as in the function Test-DynamicParameter, Get-Help will show the same eight parameter sets as the function Test-StaticParameter

```
function Test-DynamicParameter {
	[CmdletBinding(
		DefaultParameterSetName="Default-String1"
	)]

	PARAM (
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Default-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[string]$String1,

		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Default-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[string]$String2,

		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Default-String1'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Default-String2'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$false,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicA-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[MyEnum]$Type = 'Default',

		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Static-String2'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'DynamicB-String1'
		)]
		[Parameter(
			Mandatory=$true,
			ParameterSetName = 'Dynamic-String2'
		)]
		[int]$Count
	)

	DynamicParam {
		$RuntimeDefinedParameterDictionary = [System.Management.Automation.RuntimeDefinedParameterDictionary]::New()

		if ($null -eq $PSBoundParameters['Type']) {
			$Type = 'Default'
		} else {
			$Type = $PSBoundParameters['Type']
		}

		switch ($Type) {
			{$_ -in @('ValueA', 'ValueB')} {
				$ParameterName = 'DynamicParam'

				$AttributeCollection = [System.Collections.ObjectModel.Collection[System.Attribute]]::New()

				#Region ParameterSet DynamicA-String1
				$ParameterAttribute = [System.Management.Automation.ParameterAttribute]::New()
				$ParameterAttribute.Mandatory = $true
				$ParameterAttribute.ParameterSetName = 'DynamicA-String1'

				$AttributeCollection.Add($ParameterAttribute)
				#EndRegion

				#Region ParameterSet DynamicA-String2
				$ParameterAttribute = [System.Management.Automation.ParameterAttribute]::New()
				$ParameterAttribute.Mandatory = $true
				$ParameterAttribute.ParameterSetName = 'DynamicA-String2'

				$AttributeCollection.Add($ParameterAttribute)
				#EndRegion

				#Region ParameterSet DynamicB-String1
				$ParameterAttribute = [System.Management.Automation.ParameterAttribute]::New()
				$ParameterAttribute.Mandatory = $true
				$ParameterAttribute.ParameterSetName = 'DynamicB-String1'

				$AttributeCollection.Add($ParameterAttribute)
				#EndRegion

				#Region ParameterSet Dynamic-String2
				$ParameterAttribute = [System.Management.Automation.ParameterAttribute]::New()
				$ParameterAttribute.Mandatory = $true
				$ParameterAttribute.ParameterSetName = 'Dynamic-String2'

				$AttributeCollection.Add($ParameterAttribute)
				#EndRegion

				$RuntimeDefinedParameter = [System.Management.Automation.RuntimeDefinedParameter]::New($ParameterName, [int64], $AttributeCollection)

				$RuntimeDefinedParameterDictionary.Add($ParameterName, $RuntimeDefinedParameter)
			}

			{$_ -in @('Default', 'ValueC', 'ValueD')} {
				# No Dynamic Parameters
			}

			Default {
				throw [System.Management.Automation.ErrorRecord]::New(
					[Exception]::New('Unknown setting.'),
					'1',
					[System.Management.Automation.ErrorCategory]::InvalidArgument,
					$Type
				)
			}
		}

		return $RuntimeDefinedParameterDictionary
	}

	BEGIN {
	}

	PROCESS {
		Write-Output $PSCmdlet.ParameterSetName
	}

	END {
	}
}
```

Both functions, Test-StaticParameter and Test-DynamicParameter, should return the same results for each parameter set used.  The only difference between the two functions is the parameter  DynamicParam can only be used when the Type parameter has certain values.  However, when the Type parameter is specified when the parameter set to be selected is not the default parameter set, no mater the value, an error is returned.

### Expected behavior

```console
PS C:\> Test-DynamicParameter-String1 asdf
Default-String1
PS C:\> Test-DynamicParameter-String2 fdsa
Default-String2
PS C:\> Test-DynamicParameter-String1 asdf -Count 1
Static-String1
PS C:\> Test-DynamicParameter-String2 fdsa -Count 1
Static-String2
PS C:\> Test-DynamicParameter-String1 asdf -Type ValueB -DynamicParam 1234
DynamicA-String1
PS C:\> Test-DynamicParameter-String2 fdsa -Type ValueB -DynamicParam 1234
DynamicA-String2
PS C:\> Test-DynamicParameter-String1 asdf -Type ValueB -DynamicParam 1234 -Count 1
DynamicB-String1
PS C:\> Test-DynamicParameter-String2 fdsa -Type ValueB -DynamicParam 1234 -Count 1
Dynamic-String2
PS C:\> Test-DynamicParameter -String1 asdf -Type ValueD
Default-String1
Test-DynamicParameter -String2 fdsa -Type ValueD
Default-String2
```

### Actual behavior

```console
PS C:\> Test-DynamicParameter-String1 asdf
Default-String1
PS C:\> Test-DynamicParameter-String2 fdsa
Default-String2
PS C:\> Test-DynamicParameter-String1 asdf -Count 1
Static-String1
PS C:\> Test-DynamicParameter-String2 fdsa -Count 1
Static-String2
PS C:\> Test-DynamicParameter-String1 asdf -Type ValueB -DynamicParam 1234
DynamicA-String1
PS C:\> Test-DynamicParameter-String2 fdsa -Type ValueB -DynamicParam 1234
Test-DynamicParameter: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
PS C:\> Test-DynamicParameter-String1 asdf -Type ValueB -DynamicParam 1234 -Count 1
Test-DynamicParameter: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
PS C:\> Test-DynamicParameter-String2 fdsa -Type ValueB -DynamicParam 1234 -Count 1
Test-DynamicParameter: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
PS C:\> Test-DynamicParameter -String1 asdf -Type ValueD
Default-String1
Test-DynamicParameter -String2 fdsa -Type ValueD
Test-DynamicParameter: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Parameter set cannot be resolved using the specified named parameters. One or more parameters
issued cannot be used together or an insufficient number of parameters were provided.
    ErrorId           : AmbiguousParameterSet
    Line              : 1
    Offset            : 1
    CommandInvocation :
        MyCommand        : Test-DynamicParameter
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 2
            Keys     :
                              String2
                              Type
            Values   :
                              fdsa

                value__ : 4
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 2
                Keys     :
                                      String2
                                      Type
                Values   :
                                      fdsa

                    value__ : 4
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 2
                    Keys     :
                                              String2
                                              Type
                    Values   :
                                              fdsa

                        value__ : 4
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 2
                        Keys     :
                                                      String2
                                                      Type
                        Values   :
                                                      fdsa

                            value__ : 4
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 2
                            Keys     :
                                                              String2
                                                              Type
                            Values   :
                                                              fdsa

                                value__ : 4
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 2
                                Keys     :
                                                                      String2
                                                                      Type
                                Values   :
                                                                      fdsa

                                    value__ : 4
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 2
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 58
        Line             : Test-DynamicParameter -String2 fdsa -Type ValueD
        Statement        : Test-DynamicParameter -String2 fdsa -Type ValueD
        PositionMessage  : At line:1 char:1
                           + Test-DynamicParameter -String2 fdsa -Type ValueD
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Test-DynamicParameter
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Parameter set cannot be resolved using the specified named parameters. One or more parameters
issued cannot be used together or an insufficient number of parameters were provided.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Test-DynamicParameter], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AmbiguousParameterSet,Test-DynamicParameter
        InvocationInfo        :
            MyCommand        : Test-DynamicParameter
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 58
            Line             : Test-DynamicParameter -String2 fdsa -Type ValueD
            Statement        : Test-DynamicParameter -String2 fdsa -Type ValueD
            PositionMessage  : At line:1 char:1
                               + Test-DynamicParameter -String2 fdsa -Type ValueD
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : ThrowAmbiguousParameterSetException
        DeclaringType : [System.Management.Automation.CmdletParameterBinderController]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32
parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
   at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput,
Boolean setDefault)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Test-DynamicParameter], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Test-DynamicParameter
InvocationInfo        :
    MyCommand        : Test-DynamicParameter
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 58
    Line             : Test-DynamicParameter -String2 fdsa -Type ValueD
    Statement        : Test-DynamicParameter -String2 fdsa -Type ValueD
    PositionMessage  : At line:1 char:1
                       + Test-DynamicParameter -String2 fdsa -Type ValueD
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The immediate problem is that `-String2` and `-Type` cannot be combined unambiguously, causing parameter binding to stop right there - your `DynamicParam` block is never called.

To at least eliminate the "parameter set cannot be resolved error", comment out the `[Parameter()]` attribute that contains `ParameterSetName = 'DynamicA-String2'` that decorates the `$String2` parameter.

It looks like you can greatly reduce the number of parameter sets, which will likely also solve your problem.

**Comment by netsec4u** [comment]
In other words, dynamic parameters cannot be used to make a parameter set unambiguous, requiring the static parameters to unambiguously select a parameter set.

I was able to change the dynamic parameter to not set the ParameterSetName, which allowed for the reduction of parameter sets to resolve.  However, I want to know if this was a bug or if it was by design.  It sounds like it is by design.

**Comment by mklement0** [comment]
> In other words, dynamic parameters cannot be used to make a parameter set unambiguous, requiring the static parameters to unambiguously select a parameter set.

That's a great summary. Yes, any given static parameters must resolve unambiguously to a parameter set first.

While I cannot speak in any official capacity, I do think that this is by design, given the stages of parameter binding described by a team member in https://github.com/PowerShell/PowerShell/issues/14701#issuecomment-773476552 - also see the clarification at  https://github.com/PowerShell/PowerShell/issues/14701#issuecomment-774332772.

Here's what I _think_ is a minimal example:

```powershell
function Test-AmbiguousParameter {
  [CmdletBinding(DefaultParameterSetName = 'Default')]
  param (
    [Parameter(Mandatory = $true, ParameterSetName = 'Default')]
    $A,

    [Parameter(Mandatory = $false, ParameterSetName = 'Other')]
    $B
  )

  DynamicParam {
    Write-Verbose -Verbose HERE
  }

  process {
    Write-Output $PSCmdlet.ParameterSetName
  }

}
```

`Test-AmbiguousParameter -a 1 -b 2`  predictably yields the  "parameter set cannot be resolved" error and never prints the  `VERBOSE: HERE` message, implying that the `DynamicParam` block is never invoked.

Contrast with `Test-AmbiguousParameter -a 1` and `Test-AmbiguousParameter -b 2`

**Comment by netsec4u** [comment]
Thank you for your help and information!  It is greatly appreciated!
