### ISSUE TITLE
No runspace available to run scripts in this thread.  You can provide one in the DefaultRunspace property 

### ISSUE THREAD

**Issue by msekkappan** [PowerShell/PowerShell#21551]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running these commands in interactive mode works perfectly.  However, saving them to a file and running them throws this error.

format-default: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: 

Connect-MicrosoftTeams
$AllTeams = Get-Team -User JXXXXXX@XXXXX.OnMicrosoft.com
$AllTeams

### Expected behavior

```console
Should display all the teams that the user is a member of.
```

### Actual behavior

```console
Error
format-default: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:
```

### Error details

```console
Type           : System.Management.Automation.CmdletInvocationException

ErrorRecord    :

    Exception             :

        Type       : System.NullReferenceException

        TargetSite :

            Name          : Inject

            DeclaringType : System.Management.Automation.Internal.PipelineProcessor, System.Management.Automation,

Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35

            MemberType    : Method

            Module        : System.Management.Automation.dll

        Message    : Object reference not set to an instance of an object.

        Source     : System.Management.Automation

        HResult    : -2147467261

        StackTrace :

   at System.Management.Automation.Internal.PipelineProcessor.Inject(Object input, Boolean enumerate)

   at System.Management.Automation.Internal.PipelineProcessor.Step(Object input)

   at Microsoft.PowerShell.Commands.Internal.Format.OutputManagerInner.ProcessRecord()

   at Microsoft.PowerShell.Commands.OutDefaultCommand.ProcessRecord()

   at System.Management.Automation.CommandProcessor.ProcessRecord()

    CategoryInfo          : NotSpecified: (:) [Out-Default], NullReferenceException

    FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.OutDefaultCommand

   InvocationInfo        :

        MyCommand       : Out-Default

        HistoryId       : 3

        InvocationName  : Out-Default

        CommandOrigin   : Internal

    ScriptStackTrace      : at <ScriptBlock>, C:\temp\Test.ps1: line 18

                            at <ScriptBlock>, <No file>: line 1

    PipelineIterationInfo :

 

 

 

Message        : Object reference not set to an instance of an object.

InnerException :

    Type       : System.NullReferenceException

    TargetSite :

        Name          : Inject

        DeclaringType : System.Management.Automation.Internal.PipelineProcessor, System.Management.Automation,

Version=7.4.1.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35

        MemberType    : Method

        Module        : System.Management.Automation.dll

    Message    : Object reference not set to an instance of an object.

    Source     : System.Management.Automation

    HResult    : -2147467261

    StackTrace :

   at System.Management.Automation.Internal.PipelineProcessor.Inject(Object input, Boolean enumerate)

   at System.Management.Automation.Internal.PipelineProcessor.Step(Object input)

   at Microsoft.PowerShell.Commands.Internal.Format.OutputManagerInner.ProcessRecord()

   at Microsoft.PowerShell.Commands.OutDefaultCommand.ProcessRecord()

   at System.Management.Automation.CommandProcessor.ProcessRecord()

HResult        : -2146233087
```

### Environment data

```powershell
Name                           Value

----                           -----

PSVersion                      7.4.1

PSEdition                      Core

GitCommitId                    7.4.1

OS                             Microsoft Windows 10.0.19045

Platform                       Win32NT

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1

WSManStackVersion              3.0
```

**Comment by msekkappan** [comment]
Version 7.4.2 behaves the same.

**Comment by mklement0** [comment]
So you're saying that saving the commands to a `.ps1` file and invoking that file from a stand-alone PowerShell session produces this symptom? Or are you executing the file via the PowerShell SDK (e.g. from a C# project)?

**Comment by msekkappan** [comment]
Invoking the file in a PowerShell session produces the error. Regards,MalathiSent from my iPhoneOn Apr 29, 2024, at 3:57 PM, Michael Klement ***@***.***> wrote:﻿Re: [PowerShell/PowerShell] No runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property (Issue #21551)So you're saying that saving the commands to a .ps1 file and invoking that file from a stand-alone PowerShell session produces this symptom? Or are you executing the file via the PowerShell SDK (e.g. from a C# project)?—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by msekkappan** [comment]
Saving these in a ps1 file and invoking in a PS Console throws this error message.  If I type these commands individually in the console it does not happen.

**Comment by mklement0** [comment]
The error comes from the display-formatting system, but the error message is usually only seen when PowerShell is hosted in other applications.
Also, the error details describe  a different error, "Object reference not set to an instance of an object."

Your symptom suggests that execution - and therefore joint formatting - in a _single_ pipeline may trigger the bug, so see if the following makes a difference:

```powershell
Connect-MicrosoftTeams | Out-Host  # force instant, direct-to-display output
$AllTeams = Get-Team -User JXXXXXX@XXXXX.OnMicrosoft.com
$AllTeams
```

**Comment by msekkappan** [comment]
Will try Regards,MalathiSent from my iPhoneOn May 1, 2024, at 1:30 PM, Michael Klement ***@***.***> wrote:﻿Re: [PowerShell/PowerShell] No runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property (Issue #21551)The error comes from the display-formatting system, but the error message is usually only seen when PowerShell is hosted in other applications.Also, the error details describe a different error, "Object reference not set to an instance of an object."Your symptom suggests that execution - and therefore joint formatting - in a single pipeline may trigger the bug, so see if the following makes a difference:Connect-MicrosoftTeams | Out-Host  # force instant, direct-to-display output
$AllTeams = Get-Team -User ***@***.***
$AllTeams—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by msekkappan** [comment]
Adding pipeline to the get-team command displayed results along with the same error message “no runspace available message…”Adding pipeline to the connect-MicrosoftTeams had no impact.  Regards,MalathiSent from my iPhoneOn May 2, 2024, at 3:59 PM, Malathi ***@***.***> wrote:﻿Will try Regards,MalathiSent from my iPhoneOn May 1, 2024, at 1:30 PM, Michael Klement ***@***.***> wrote:﻿Re: [PowerShell/PowerShell] No runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property (Issue #21551)The error comes from the display-formatting system, but the error message is usually only seen when PowerShell is hosted in other applications.Also, the error details describe a different error, "Object reference not set to an instance of an object."Your symptom suggests that execution - and therefore joint formatting - in a single pipeline may trigger the bug, so see if the following makes a difference:Connect-MicrosoftTeams | Out-Host  # force instant, direct-to-display output
$AllTeams = Get-Team -User ***@***.***
$AllTeams—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by msekkappan** [comment]
Connect-Microsoftteams with an out-host didn’t make any difference. However, adding out-host to get-team command displayed anticipated results plus  same error message “No runspace…”Regards,MalathiSent from my iPhoneOn May 2, 2024, at 3:59 PM, Malathi ***@***.***> wrote:﻿Will try Regards,MalathiSent from my iPhoneOn May 1, 2024, at 1:30 PM, Michael Klement ***@***.***> wrote:﻿Re: [PowerShell/PowerShell] No runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property (Issue #21551)The error comes from the display-formatting system, but the error message is usually only seen when PowerShell is hosted in other applications.Also, the error details describe a different error, "Object reference not set to an instance of an object."Your symptom suggests that execution - and therefore joint formatting - in a single pipeline may trigger the bug, so see if the following makes a difference:Connect-MicrosoftTeams | Out-Host  # force instant, direct-to-display output
$AllTeams = Get-Team -User ***@***.***
$AllTeams—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you authored the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mklement0** [comment]
Thanks; personally, I can't be of further assistance, because I don't have access to Microsoft Teams, but I hope someone else can help you narrow this down.

**Comment by kilasuit** [comment]
I believe this to be an issue with the MicrosoftTeams module more than PowerShell 
Please can you provide which version of the module you are using from `Get-Module MicrosoftTeams` as this was missed from your inital repro steps
