### ISSUE TITLE
Setting $? crashes PowerShell

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#2243]
Setting `$?` crashes PowerShell on both FullCLR and CoreCLR. 

Steps to reproduce
------------------
`$? = 1`

Expected behavior
-----------------
Throw an error object that explains why $? cannot and should not be set. 

Actual behavior
---------------
PowerShell crashes, emitting the following to the screen:

```
Unhandled Exception: System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Management.Automation.InvocationInfo" value of type "System.Management.Automation.InvocationInfo" to type "System.Management.Automation.PSBoundParametersDictionary".
   at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
   at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo[T](Object valueToConvert)
   at System.Management.Automation.MutableTuple`16.SetValueImpl(Int32 index, Object value)
   at System.Management.Automation.MutableTuple.SetNestedValue(Int32 size, Int32 index, Object value)
   at System.Management.Automation.MutableTuple.SetAutomaticVariable(AutomaticVariable auto, Object value, ExecutionContext context)
   at System.Management.Automation.DlrScriptCommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
CLRVersion
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.9
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1

```

**Comment by vors** [comment]
Oh, that's pretty bad.
Also verified it on 
```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leftcase** [comment]
Confirmed on OSX
```
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.9                                  
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1    
```
