### ISSUE TITLE
.NET App using Powershell.SDK fails to run, when building as SingeFile

### ISSUE THREAD

**Issue by RobinGFT** [PowerShell/PowerShell#23797]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a .NET 8 Application executing a lot of Powershell commands, but when I build it as a SingleFile it throws an exception.
Issue is already documented in [#13540](https://github.com/PowerShell/PowerShell/issues/13540) 

I also opened an issue in the dotnet repo, which is to find under: [dotnet/runtime #102193](https://github.com/dotnet/runtime/issues/102193). There is already a very helpful comment which shows a possible way fixing the issue:  [Comment](https://github.com/dotnet/runtime/issues/102193#issuecomment-2110290621) 

------

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.2"  />
  </ItemGroup>
</Project>
```

```
using System;
using System.Management.Automation;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            String cmd = "New-Item -Force -Type Directory -Path '%userprofile%\test123'";
             PowerShell ps1 = PowerShell.Create().AddScript(cmd);
             ps1.Invoke();
        }
    }
}
```

`dotnet publish -r win-x64 --self-contained false /p:PublishSingleFile=true`

### Expected behavior

```console
Publish and run successfully.
```

### Actual behavior

Publish works, but application doesn' t run. At the first execution of a powershell script, following exception is thrown:

```
ERROR: 2024-05-14T12:33:51.8318820Z - Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at System.Management.Automation.PSSnapInReader.ReadEnginePSSnapIns()
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
```

### Environment data

* .NET 8
* Win10-x64
* PowerShell.SDK 7.4.2

**Comment by samuel-weber-nc** [comment]
Having exactly the same issue!

**Comment by kasini3000** [comment]
dotnet publish MyPowerShellApp -r linux-x64 -c release --self-contained true /p:PublishSingleFile=true
dotnet publish MyPowerShellApp -r linux-x64 -c release --self-contained false /p:PublishSingleFile=true
Having exactly the same issue!

----

normal without "/p:PublishSingleFile=true"

----

# Environment data
.NET 8
linux-x64
PowerShell.SDK 7.4.2

**Comment by RobinGFT** [comment]
Are there any further updates on this case?

**Comment by DaRacci** [comment]
Still encountering this issue.

**Comment by RobinGFT** [comment]
> Still encountering this issue.

In current stable versions the issue still persists. However, as described in https://github.com/PowerShell/PowerShell/issues/13540#issuecomment-2597693795  if possible you can switch to preview release of the NUGET package, which had solved the problem for my case. 
It should be just a matter of time, till the corresponding changes are merged into a stable release.
