### ISSUE TITLE
Add-Type ReferencedAssemblies only works with full file paths now?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#23791]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This should work, but it does not anymore.

```PowerShell
Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "WindowsBase"
```

I have to pass the **full path** to the DLLs to get them to load:

```PowerShell
Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "$PSHome\WindowsBase.dll"
```

This appears to be because the assemblies are in `$PSHome` but `Add-Type` is searching `$PSHome\ref`

https://github.com/PowerShell/PowerShell/blob/0f3fd2077cfd63b298ce7f88babe041f4dc6849e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L801-L808

https://github.com/PowerShell/PowerShell/blob/0f3fd2077cfd63b298ce7f88babe041f4dc6849e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L643-L646

### Expected behavior

```console
PS> Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "WindowsBase"
PS>
```

### Actual behavior

```console
PS> Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "WindowsBase"

Add-Type: (1,37): error CS0234: The type or namespace name 'DependencyObject' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)
public class Style : System.Windows.DependencyObject {}
                                    ^
Add-Type: Cannot add type. Compilation errors occurred.

PS>
```

### Error details

```console
Exception             : 
    Type       : System.IO.FileNotFoundException
    Message    : Could not find file 'C:\Program Files\PowerShell\7\WindowsBase'.
    FileName   : C:\Program Files\PowerShell\7\WindowsBase
    TargetSite : 
        Name          : CreateFile
        DeclaringType : [Microsoft.Win32.SafeHandles.SafeFileHandle]
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147024894
    StackTrace : 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.StandardFileSystem.OpenFile(String filePath, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.CommonCompilerFileSystemExtensions.OpenFileWithNormalizedException(ICommonCompilerFileSystem fileSystem, String filePath, FileMode fileMode, FileAccess fileAccess, FileShare fileShare)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.PowerShell.Commands.AddTypeCommand.GetPortableExecutableReferences()
   at Microsoft.PowerShell.Commands.AddTypeCommand.CompileToAssembly(List`1 syntaxTrees, CompilationOptions compilationOptions, EmitOptions emitOptions)
   at Microsoft.PowerShell.Commands.AddTypeCommand.SourceCodeProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
InvocationInfo        : 
    MyCommand        : Add-Type
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "$PSHome\WindowsBase"
    Statement        : Add-Type "public class Style : System.Windows.DependencyObject {}" -ReferencedAssemblies "$PSHome\WindowsBase"
    PositionMessage  : At line:1 char:1
                       + Add-Type "public class Style : System.Windows.DependencyObject {}" -R ΓÇª
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Add-Type
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The curious thing is that it does find the assembly in principle; e.g.,
`Add-Type "public class Style {}" -ReferencedAssemblies WindowsBase.dll` compiles (but wouldn't in a pristine session if you specified a non-existent assembly).
