### ISSUE TITLE
Unable to install PowerShell Module from GitHub NuGet repository

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#23834]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a PowerShell module in a github NuGet repository at https://github.com/rhubarb-geek-nz/SQLiteConnection/pkgs/nuget/rhubarb-geek-nz.SQLiteConnection

I was hoping to be able to install it with PowerShell. I can install it with the nuget command line tool

```
$ grep github.com .nuget/NuGet/NuGet.Config
   <add key="github" value="https://nuget.pkg.github.com/rhubarb-geek-nz/index.json" />

$ dotnet add package rhubarb-geek-nz.SQLiteConnection --version 1.0.118

$ find .nuget/ -name rhubarb-geek-nz.SQLiteConnection.psd1
.nuget/packages/rhubarb-geek-nz.sqliteconnection/1.0.118/rhubarb-geek-nz.SQLiteConnection.psd1
```

I added the NuGet repository as a PSRepository

```
PS> Register-PSRepository -Name 'github' -SourceLocation 'https://nuget.pkg.github.com/rhubarb-geek-nz/index.json' -Credential $credObject

PS> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
github                    Untrusted            https://nuget.pkg.github.com/rhubarb-geek-nz/index.json
Foo                       Trusted              http://10.1.2.12:5000/
```

Install-Module fails to find the module

### Expected behavior

```console
PS> install-module -name rhubarb-geek-nz.SQLiteConnection -Repository Foo -RequiredVersion 1.0.118 -Verbose
VERBOSE: Suppressed Verbose Repository details, Name = 'Foo', Location = 'http://10.1.2.12:5000/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'Foo', Location = 'http://10.1.2.12:5000/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'Foo'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'http://10.1.2.12:5000/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'http://10.1.2.12:5000/FindPackagesById()?id='rhubarb-geek-nz.SQLiteConnection'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'rhubarb-geek-nz.SQLiteConnection'.
VERBOSE: Performing the operation "Install-Module" on target "Version '1.0.118' of module 'rhubarb-geek-nz.SQLiteConnection'".
VERBOSE: The installation scope is specified to be 'CurrentUser'.
VERBOSE: The specified module will be installed in '/home/bythesea/.local/share/powershell/Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'rhubarb-geek-nz.SQLiteConnection' with version '1.0.118' from the repository 'http://10.1.2.12:5000/'.
VERBOSE: Searching repository 'http://10.1.2.12:5000/FindPackagesById()?id='rhubarb-geek-nz.SQLiteConnection'' for ''.
VERBOSE: InstallPackage' - name='rhubarb-geek-nz.SQLiteConnection', version='1.0.118',destination='/tmp/1705137894'
VERBOSE: DownloadPackage' - name='rhubarb-geek-nz.SQLiteConnection', version='1.0.118',destination='/tmp/1705137894/rhubarb-geek-nz.SQLiteConnection.1.0.118/rhubarb-geek-nz.SQLiteConnection.1.0.118.nupkg', uri='http://10.1.2.12:5000//download/rhubarb-geek-nz.SQLiteConnection/1.0.118'
VERBOSE: Downloading 'http://10.1.2.12:5000//download/rhubarb-geek-nz.SQLiteConnection/1.0.118'.
VERBOSE: Completed downloading 'http://10.1.2.12:5000//download/rhubarb-geek-nz.SQLiteConnection/1.0.118'.
VERBOSE: Completed downloading 'rhubarb-geek-nz.SQLiteConnection'.
VERBOSE: InstallPackageLocal' - name='rhubarb-geek-nz.SQLiteConnection', version='1.0.118',destination='/tmp/1705137894'
VERBOSE: Validating the 'rhubarb-geek-nz.SQLiteConnection' module contents under '/tmp/1705137894/rhubarb-geek-nz.SQLiteConnection.1.0.118' path.
VERBOSE: Test-ModuleManifest successfully validated the module manifest file '/tmp/1705137894/rhubarb-geek-nz.SQLiteConnection.1.0.118'.
VERBOSE: Module 'rhubarb-geek-nz.SQLiteConnection' was installed successfully to path '/home/bythesea/.local/share/powershell/Modules/rhubarb-geek-nz.SQLiteConnection/1.0.118'.
```

### Actual behavior

```console
PS> install-module -name rhubarb-geek-nz.SQLiteConnection -Repository github -RequiredVersion 1.0.118 -Verbose
VERBOSE: Suppressed Verbose Repository details, Name = 'github', Location = 'https://nuget.pkg.github.com/rhubarb-geek-nz/index.json'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'github', Location = 'https://nuget.pkg.github.com/rhubarb-geek-nz/index.json'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'github'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://nuget.pkg.github.com/rhubarb-geek-nz/index.json' and PackageManagementProvider is 'NuGet'.
VERBOSE: Retry downloading 'https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json' for '0' more times
VERBOSE: Total package yield:'0' for the specified package 'rhubarb-geek-nz.SQLiteConnection'.
Install-Package: No match was found for the specified search criteria and module name 'rhubarb-geek-nz.SQLiteConnection'. Try Get-PSRepository to see all available registered module repositories.
```

### Error details

```console
Install-Package: No match was found for the specified search criteria and module name 'rhubarb-geek-nz.SQLiteConnection'. Try Get-PSRepository to see all available registered module repositories.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

none

**Comment by rhubarb-geek-nz** [comment]
I was able to use `Publish-Module` to push the package to github.

The debug output for `Install-Module` finds the module but does not like it

```
DEBUG: 00:00:08.5978373 Calling 'NuGetPackageFeed3'::'Find', 'https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/index.json'.
DEBUG: 00:00:08.5979971 Downloading 'https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/index.json'.
DEBUG: 00:00:08.8012946 Completed downloading 'https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/index.json'.
DEBUG: 00:00:08.8078864 JSON object: {"count":1,"items":[{"@id":"https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/index.json","lower":"1.0.118","upper":"1.0.118","count":1,"items":[{"@id":"https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json","packagecontent":"https://nuget.pkg.github.com/rhubarb-geek-nz/download/rhubarb-geek-nz.sqliteconnection/1.0.118/rhubarb-geek-nz.sqliteconnection.1.0.118.nupkg","catalogentry":{"@id":"https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json","authors":"Roger Brown","copyright":"Copyright © 2024 Roger Brown","dependencygroups":[],"description":"SQLite Connection Tool","iconurl":"","id":"rhubarb-geek-nz.sqliteconnection","isprerelease":false,"language":"Multiple architectures loaded in an AssemblyLoadContext","licenseurl":"","packagecontent":"https://nuget.pkg.github.com/rhubarb-geek-nz/download/rhubarb-geek-nz.sqliteconnection/1.0.118/rhubarb-geek-nz.sqliteconnection.1.0.118.nupkg","projecturl":"https://github.com/rhubarb-geek-nz/SQLiteConnection","requirelicenseacceptance":false,"summary":"","tags":"PowerShellGetFormatVersion_2.0 PSModule PSIncludes_Cmdlet PSCmdlet_New-SQLiteConnection PSCommand_New-SQLiteConnection","version":"1.0.118"}}]}]}
DEBUG: 00:00:08.8260983 System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.GetPackageById(PackageSource source, String name, NuGetRequest request, String requiredVersion, String minimumVersion, String maximumVersion, Boolean minInclusive, Boolean maxInclusive, Boolean isDependency)
VERBOSE: Total package yield:'0' for the specified package 'rhubarb-geek-nz.SQLiteConnection'.
DEBUG: 00:00:08.8320741 Completed iterating for 'rhubarb-geek-nz.SQLiteConnection'.
DEBUG: 00:00:08.8335023 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:08.8358116 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:28.6391205 unmatched package name='rhubarb-geek-nz.SQLiteConnection'
```

**Comment by iSazonov** [comment]
In my browser `https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json` ask me login/password. Maybe it is a reason of the issue.

**Comment by rhubarb-geek-nz** [comment]
> Maybe it is a reason of the issue.

No, I pass the credentials.

```
[securestring]$secStringPassword = ConvertTo-SecureString $userPassword -AsPlainText -Force

[pscredential]$credObject = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $userName, $secStringPassword

Install-Module -Repository 'github' -Name 'rhubarb-geek-nz.SQLiteConnection' -Credential $credObject -Verbose -Debug
```

It is getting the json description back, printed in the DEBUG trace above.

```
{
  "count": 1,
  "items": [
    {
      "@id": "https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/index.json",
      "lower": "1.0.118",
      "upper": "1.0.118",
      "count": 1,
      "items": [
        {
          "@id": "https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json",
          "packagecontent": "https://nuget.pkg.github.com/rhubarb-geek-nz/download/rhubarb-geek-nz.sqliteconnection/1.0.118/rhubarb-geek-nz.sqliteconnection.1.0.118.nupkg",
          "catalogentry": {
            "@id": "https://nuget.pkg.github.com/rhubarb-geek-nz/rhubarb-geek-nz.sqliteconnection/1.0.118.json",
            "authors": "Roger Brown",
            "copyright": "Copyright © 2024 Roger Brown",
            "dependencygroups": [],
            "description": "SQLite Connection Tool",
            "iconurl": "",
            "id": "rhubarb-geek-nz.sqliteconnection",
            "isprerelease": false,
            "language": "Multiple architectures loaded in an AssemblyLoadContext",
            "licenseurl": "",
            "packagecontent": "https://nuget.pkg.github.com/rhubarb-geek-nz/download/rhubarb-geek-nz.sqliteconnection/1.0.118/rhubarb-geek-nz.sqliteconnection.1.0.118.nupkg",
            "projecturl": "https://github.com/rhubarb-geek-nz/SQLiteConnection",
            "requirelicenseacceptance": false,
            "summary": "",
            "tags": "PowerShellGetFormatVersion_2.0 PSModule PSIncludes_Cmdlet PSCmdlet_New-SQLiteConnection PSCommand_New-SQLiteConnection",
            "version": "1.0.118"
          }
        }
      ]
    }
  ]
}
```

But does not recognize it.

**Comment by rhubarb-geek-nz** [comment]
Another observation, if I do download the nupkg and put it in a local directory based PSRepository, PowerShell fails to install it until I have changed the case of the filename from all lowercase as returned by the repository to the correct upper and lowercase for the module name.

**Comment by iSazonov** [comment]
There was a similar story when changing the name of  PSReadline -> PSReadLine 
https://github.com/PowerShell/PowerShell/issues/1621
There was a fix for folder name on Unix.
But I don't recall that it was about the file name then.

**Comment by sikksakk** [comment]
Did you find out anything more around this? Seems to still not work.

**Comment by BrianL-STCU** [comment]
Unless the documentation is out of date (which is possible), it seems like the problem is that [the `-Credential` parameter isn't supported](https://learn.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershellget-3.x#-credential "Register-PSRepository: -Credential Parameter"):

> #### -Credential
> 
> The proxy cmdlet ignores this parameter since it's not supported by Register-PSResourceRepository.

**Comment by LaurentDardenne** [comment]
> Another observation, if I do download the nupkg and put it in a local directory based PSRepository, PowerShell fails to install it until I have changed the case of the filename from all lowercase as returned by the repository to the correct upper and lowercase for the module name. ( tested on Linux )

Yes, that's the cause of the problem; all files must be the same case.

See:
https://github.com/potatoqualitee/psmodulecache/issues/54
