### ISSUE TITLE
Invoke-WebRequest fails with “Request headers must contain only ASCII characters.” for simple requests

### ISSUE THREAD

**Issue by schuelermine** [PowerShell/PowerShell#23858]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On running a command like `Invoke-WebRequest "http://example.org"`, it fails with `Invoke-WebRequest: Request headers must contain only ASCII characters.`.

### Expected behavior

```console
PS> Invoke-WebRequest "http://example.org"
...

PS>
```

### Actual behavior

```console
PS> Invoke-WebRequest "http://example.org"
Invoke-WebRequest: Request headers must contain only ASCII characters.
PS>
```

### Error details

```console
Exception             :
    Type       : System.Net.Http.HttpRequestException
    TargetSite :
        Name          : <WriteString>g__ThrowForInvalidCharEncoding|56_0
        DeclaringType : [System.Net.Http.HttpConnection]
        MemberType    : Method
        Module        : System.Net.Http.dll
    Message    : Request headers must contain only ASCII characters.
    Source     : System.Net.Http
    HResult    : -2146233088
    StackTrace :
   at System.Net.Http.HttpConnection.<WriteString>g__ThrowForInvalidCharEncodin
g|56_0()
   at System.Net.Http.HttpConnection.WriteString(String s, Encoding encoding)
   at System.Net.Http.HttpConnection.WriteHeaderCollection(HttpHeaders
headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.WriteHeaders(HttpRequestMessage request,
HttpMethod normalizedMethod)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(
HttpRequestMessage request, Boolean async, Boolean doRequestAuth,
CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request,
Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage
request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage
request, HttpCompletionOption completionOption, CancellationTokenSource cts,
Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient
client, HttpRequestMessage request, Boolean handleRedirect)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : Method: GET, RequestUri: 'http://example.org/',
Version: 1.1, Content: <null>, Headers:
                        {
                        User-Agent: Mozilla/5.0
                        User-Agent: (Linux; NixOS 24.11 (Vicuña); en-US)
                        User-Agent: PowerShell/7.4.2
                        Accept-Encoding: gzip
                        Accept-Encoding: deflate
                        Accept-Encoding: br
                        }
CategoryInfo          : InvalidOperation: (Method: GET, Reques…cept-Encoding:
br
                        }:HttpRequestMessage) [Invoke-WebRequest],
HttpRequestException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Comm
ands.InvokeWebRequestCommand
InvocationInfo        :
    MyCommand        : Invoke-WebRequest
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Invoke-WebRequest "http://example.org"
    Statement        : Invoke-WebRequest "http://example.org"
    PositionMessage  : At line:1 char:1
                       + Invoke-WebRequest "http://example.org"
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-WebRequest
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS /home/anselmschueler> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             NixOS 24.11 (Vicuña)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/48802534/a25901ab-1fb3-458b-bdb1-ed8dfd4a81bf)

**Comment by mklement0** [comment]
What causes the error is the word `Vicuña` in the user-agent string, which contains a non-ASCII-range character (`ñ`).

The simplest way to reproduce the error is:

```powershell
Invoke-WebRequest https://example.org -UserAgent '(ñ)'
```

While I don't know what the proper resolution for this issue is, the above points toward a workaround: pass an all-ASCII-character `-UserAgent` arugment.

**Comment by iSazonov** [comment]
I suggest to report the issue to dotnet/runtime repository.

**Comment by fanuelsen** [comment]
I have the same trouble on macOS when trying to get some data from graph.

`Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`
