### ISSUE TITLE
CreateOutOfProcessRunspace fails to Open 

### ISSUE THREAD

**Issue by saidas3524** [PowerShell/PowerShell#23886]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to run the following script 

function Get-PowerShellVersion {
    $PSVersionTable.PSVersion
}
 
$psVersion = Get-PowerShellVersion
$typeTable = [System.Management.Automation.Runspaces.TypeTable]::new([string[]]@())
$powershellInstance = [System.Management.Automation.Runspaces.PowerShellProcessInstance]::new($psVersion, $null, $null, $true)
$runspace = [System.Management.Automation.Runspaces.RunspaceFactory]::CreateOutOfProcessRunspace($typeTable, $powershellInstance)
$runspace.Open()

### Expected behavior

```console
$runspace.Open() should succeed.
```

### Actual behavior

```console
Fails with Error 

System.Management.Automation.Remoting.PSRemotingTransportException: The background process reported an error with the following message: W i n d o w s   P o w e r S h e l l   t e r m i n a t e d   w i t h   t h e   f o l l o w i n g   e r r o r :   .
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17763.5820
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.5820
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Please note that this repository is _not_ for reporting _Windows PowerShell_ issues (PowerShell versions up to 5.1); to report Windows PowerShell issues, use the [Feedback Hub application](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332), though note that Windows PowerShell is no longer actively developed and will see security-critical fixes only.

If you (also) see the issue in a [currently supported _PowerShell [Core]_ version](https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle#powershell-releases-end-of-life), including the current preview version, please provide minimal sample code that reproduces the problem, directly in your original post, using proper formatting.
