### ISSUE TITLE
Dot backslash doesn't work for .ps1 scripts on non-windows platforms

### ISSUE THREAD

**Issue by ikkierie** [PowerShell/PowerShell#23956]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When on linux, and in the same directory as a file `<name>.ps1`, attempt to execute it as `.\<name>` as would be possible on windows.

### Expected behavior

```console
PS> ./test.ps1
Success
PS> .\test.ps1
Success
PS> ./test
Success
PS> .\test
Success
```

### Actual behavior

```console
PS> ./test.ps1
Success
PS> .\test.ps1
Success
PS> ./test
Success
PS> .\test
.\test: The term '.\test' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term '.\test' is not recognized as a name of a cmdlet, function, script file, or executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            HResult : -2146233087
        TargetObject          : .\test
        CategoryInfo          : ObjectNotFound: (.\test:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 28
            Line             : .\test
            Statement        : .\test
            PositionMessage  : At line:1 char:1
                               + .\test
                               + ~~~~~~
            InvocationName   : .\test
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : .\test
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : [System.Management.Automation.CommandDiscovery]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term '.\test' is not recognized as a name of a cmdlet, function, script file, or executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions
searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst,
CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[]
pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : .\test
CategoryInfo          : ObjectNotFound: (.\test:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 28
    Line             : .\test
    Statement        : .\test
    PositionMessage  : At line:1 char:1
                       + .\test
                       + ~~~~~~
    InvocationName   : .\test
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.3
PSEdition                      Core
GitCommitId                    7.5.0-preview.3
OS                             Raspbian GNU/Linux 11 (bullseye)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ikkierie** [comment]
Under 7.4.1/2 the error text is as follows: ```
.\test: The term '.\test' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command ".\test" was not found, but does exist in the current location.
PowerShell does not load commands from the current location by default (see ''Get-Help about_Command_Precedence'').

If you trust this command, run the following command instead:
```

**Comment by 237dmitry** [comment]
This is because   `.\` can be a part of filename:

```
$ ./.\test

CommandType     Name                           Version    Source
-----------     ----                           -------    ------
ExternalScript  .\test.ps1                                /home/herz/Desktop/.\test.ps1

$ cat ./.\test.ps1
$MyInvocation.MyCommand

```

**Comment by rhubarb-geek-nz** [comment]
As @237dmitry said, the backslash character is a legitimate file name character on UNIX, but not on windows

On Linux

```
PS> [System.IO.Path]::GetInvalidFileNameChars() | Where-Object { $_ -gt 32 }
/
```

On Windows

```
PS> [System.IO.Path]::GetInvalidFileNameChars() | Where-Object { $_ -gt 32 }
"
<
>
|
:
*
?
\
/
```

So rather than referring to a file relative in the current directory you were actually referring to a filename starting with a period and containing the backslash character.

**Comment by mklement0** [comment]
PowerShell treats `\` and `/` interchangeably, on all supported platforms.
This is problematic on Unix-like platforms, where `\` is a legitimate filename character, as noted, but it is rarely a problem in practice.

`.\test.ps1` works  just fine on Unix, so there's no reason why `.\test` shouldn't work, and the nonsensical suggestion that is emitted also implies that this is a bug (the suggestion is truncated, which is yet another bug: #20916).
