### ISSUE TITLE
Invoke-WebRequest (usually) results in pointer being freed was not allocated, set a breakpoint in malloc_error_break to debug and abort

### ISSUE THREAD

**Issue by BoukeG** [PowerShell/PowerShell#24001]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing an issue with Invoke-WebRequest. It's almost the same as this issue: [21602](https://github.com/PowerShell/PowerShell/issues/21602).

Only exception: for me it's a GET request, however, the similarity is using credentials.
```ps1
$creds = Get-Credential
$objects = Invoke-WebRequest -Uri https://<url> -Credential $creds
```

Also: it doesn't always happen. Usually it does, but not always (the endpoint always returns the same data).

It NEVER happens on pwsh-lts version:
```ps1
PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.9
PSEdition                      Core
GitCommitId                    7.2.9
OS                             Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Expected behavior

```console
PS> $creds = Get-Credential
<provide credentials>

PS> $objects = Invoke-WebRequest -Uri https://<url> -Credential $creds
<objects filled with the results of the Invoke-WebRequest>
```

### Actual behavior

```console
PS> $objects = Invoke-WebRequest -Uri https://<url> -Credential $creds
pwsh(30328,0x16bf17000) malloc: *** error for object 0x600002434f40: pointer being freed was not allocated
pwsh(30328,0x16bf17000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    30328 abort      /usr/local/microsoft/powershell/7/pwsh
```

### Error details

```console
Unable to run 'Get-Error' since pwsh crashed completely.
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS>
```

**Comment by SteveL-MSFT** [comment]
Need someone who can repro this get a stack trace.  Note that `malloc` is happening within the .NET runtime and not something the cmdlet is explicitly doing.

**Comment by BoukeG** [comment]
Can you point towards documentation how to get a stack trace? And what to do when PowerShell crashes completely?

**Comment by SteveL-MSFT** [comment]
I'm not an expert on macOS, but perhaps something like this https://apple.stackexchange.com/questions/272508/how-do-you-get-a-stack-trace-of-a-running-process

I'm assuming you're not familiar with building PS7 yourself and attaching VSCode

**Comment by BoukeG** [comment]
"I'm assuming you're not familiar with building PS7 yourself and attaching VSCode"

Your assumption is right, but there is a first time for everything ;-).

Anyway, running the command during the sample function brings out more details:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetStateMachineBox[[System.Net.Http.HttpConnection+<ReadAsync>d__87, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ReadAsync>d__87 ByRef, System.Threading.Tasks.Task`1<Int32> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AwaitUnsafeOnCompleted[[System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+<ReadAsync>d__87, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ConfiguredValueTaskAwaiter<Int32> ByRef, <ReadAsync>d__87 ByRef, System.Threading.Tasks.Task`1<Int32> ByRef)
   at System.IO.Compression.Inflater.SetInput(System.ReadOnlyMemory`1<Byte>)
   at System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d, System.IO.Compression, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d, System.IO.Compression, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d, System.IO.Compression, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(Int32)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<Int32>, Int32)
   at System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(Int32)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<Int32>, Int32)
   at System.Net.Http.HttpConnection+<ReadAsync>d__87.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+<ReadAsync>d__87, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+<ReadAsync>d__87, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+<ReadAsync>d__87, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream+<ReadAsyncInternal>d__163`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1+StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<ReadAsyncInternal>d__163`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1+StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<ReadAsyncInternal>d__163`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__161`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1+StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__161`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1+StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__161`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32, System.Memory`1<Byte>, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[1]    6108 abort      /usr/local/microsoft/powershell/7/pwsh

Saving session...completed.
```

I've added the sample of the process during running the command.

[Sample of pwsh.txt](https://github.com/user-attachments/files/16063877/Sample.of.pwsh.txt)

Some additional information, confirmed with another macbook the same issue exists. Running on Windows: no issues. So it is related to OSX, but not limited to just mine.

**Comment by jborean93** [comment]
I've got a few questions which can hopefully help people reproduce the problem:

+ Is this a public site that we could potentially test against
+ How did you install push (brew, macports, tar, something else)
+ It looks like you are on an arm64 mac, is that correct
+ Are you running the arm64 pwsh or the x64 one (`file $(which pwsh)`)?

**Comment by SteveL-MSFT** [comment]
@BoukeG thanks for the stacktrace.  It appears to be during .NET runtime expanding a compressed payload.  Do you have a public URL that can be used to repro?  It seems this issue needs to be reported to dotnet runtime.

**Comment by BoukeG** [comment]
@SteveL-MSFT Thanks for checking it out. Unfortunately this is an internal company, non-public URL. I'll see if I can somehow mimic on private hardware and provide a link to that.

**Comment by BoukeG** [comment]
> I've got a few questions which can hopefully help people reproduce the problem:
> 
> * Is this a public site that we could potentially test against

No, sorry, this is an internal only site

> * How did you install pwsh (brew, macports, tar, something else)

I've tried brew (which allows me to install multiple versions) and the PKG installer from here - all the same results.

> * When you say the LTS version do you just mean 7.2.x, or is 7.4.x also failing

I was using LTS 7.2.9. There it never happens. I'll try LTS 7.4.x and report the results.

> * It looks like you are on an arm64 mac, is that correct

Correct, I've confirmed with a macbook from a colleague being able to reproduce the issue. I cannot reproduce this issue on a Windows based machine (so it appears to be isolated to MacOS use, unsure if ARM/Intel is different, cannot test that).

> * Are you running the arm64 pwsh or the x64 one (`file $(which pwsh)`)?

```/usr/local/microsoft/powershell/7/pwsh: Mach-O 64-bit executable arm64```

**Comment by BoukeG** [comment]
Okay, small update. I've been able to alter the endpoint to also accept without authentication. And it appears this helps.

Results when the bug doesn't occur (with authentication):
```ps1
StatusCode        : 200
StatusDescription : OK
Content           : (cannot disclose this)
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: max-age=0, private
                    Transfer-Encoding: chunked
                    Vary: Accept-Encoding
                    Server: Microsoft-IIS/10.0
                    X-AspNet-Version: 4.0.30319
                    X-Powered-By: ASP.NET
                    WWW-Authenticate: Negoti…
Headers           : {[Cache-Control, System.String[]], [Transfer-Encoding, System.String[]], [Vary, System.String[]], [Server, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 26151974
RelationLink      : {}
```

Note the WWW-Authenticate: Negotiation
RawContentLength is 26MB, resulting in 30077 objects when converting from json.


Then the results without authentication, which works reliable every time, on 7.4.3 (and 7.4.3 LTS):
```ps1
StatusCode        : 200
StatusDescription : OK
Content           : (cannot disclose this)
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: max-age=0, private
                    Transfer-Encoding: chunked
                    Vary: Accept-Encoding
                    Server: Microsoft-IIS/10.0
                    X-AspNet-Version: 4.0.30319
                    X-Powered-By: ASP.NET
                    Date: Thu, 18 Jul 2024 0…
Headers           : {[Cache-Control, System.String[]], [Transfer-Encoding, System.String[]], [Vary, System.String[]], [Server, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 26151905
RelationLink      : {}
```
RawContentLength is 26MB, resulting in 30077 objects when converting from json - the same.

So in a way: there IS a relationship in the authentication module. Looking at that other issue reported ([21602](https://github.com/PowerShell/PowerShell/issues/21602)), I see credentials were also used. So this might be a lead?
