### ISSUE TITLE
`Microsoft.PowerShell.SDK` package numspec references on one version of `System.Management.Automation`, but inside `nupkg` is stored another version of `System.Management.Automation.dll`

### ISSUE THREAD

**Issue by obratim** [PowerShell/PowerShell#24110]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Microsoft PowerShell SDK` is a meta-project, thar references another projects, including `System.Management.Automation`.

Inside `Microsoft.PowerShell.SDK.csproj` the project `System.Management.Automation` is referenced as project, not as package:
```
<ProjectReference Include="..\System.Management.Automation\System.Management.Automation.csproj" />
```

The `System.Management.Automation` is presented as a separate package in nuget: https://www.nuget.org/packages/System.Management.Automation/

As the result there is a confusion with `Microsoft.PowerShell.SDK` dependences: in the nuspec file written that it depends on a one version of `System.Management.Automation`, but inside `nupkg` archive under `ref/net8.0/` there is another version of `System.Management.Automation.dll`

And as the result of this confusion `dotnet interactive` cli tool cannot be launched and `Polyglot` extension for Visual Studio Code cannot be initialized.

### Expected behavior

```console
`Polyglot Notebook` extension for Visual Studio Code works.
`dotnet interactive` tool works.
The `Microsoft.PowerShell.SDK` package don't have contradictions in the information about it's dependencies.
```

### Actual behavior

```console
`dotnet interactive` tool and `Polyglot Notebook` extension falls with error.

In the nuspec file of `Microsoft.PowerShell.SDK` package is specified one version of `System.Management.Automation`, but inside `nupkg` file under `ref/net8.0/` there is another version of `System.Management.Automation.dll`.

For example, for `microsoft.powershell.sdk.7.5.0-preview.3` numspec file says:

<dependency id="System.Management.Automation" version="7.5.0-preview.3" />
```
but inside `nupkg` file under `ref/net9.0/` there is `System.Management.Automation.dll` with `ProductVersion: 7.5.0-preview.1`

Another example, for `microsoft.powershell.sdk.7.4.3` numspec file says:
```
<dependency id="System.Management.Automation" version="7.4.3" />
```
but inside `nupkg` file under `ref/net8.0/` there is `System.Management.Automation.dll` with `ProductVersion: 7.4.2`
```


### Error details

```console
When I try to create a notebook with `Polyglot Notebook` - a notebook appears, but it is not interactive, in the Visual Studio Code `OUTPUT` view, under category `Polyglot Notebook: diagnostics` I see error message:

Extension started for VS Code Stable.
Started process 3681: dotnet tool run dotnet-interactive -- notebook-parser
Starting kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' using: dotnet tool run dotnet-interactive -- [vscode] stdio --working-dir /home/obratim/devel/lab_.Net/8/interactive
Kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' started (3900).
kernel (3900) stderr: Unhandled exception: 
kernel (3900) stderr: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=7.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'System.Management.Automation, Version=7.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel..ctor() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 85
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.CreateKernel(String defaultKernelName, FrontendEnvironment frontendEnvironment, StartupOptions startupOptions, TelemetrySender telemetrySender) in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 488
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__20>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 333
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__2>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 161
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Kernel for 'untitled:Untitled-1.ipynb?jupyter-notebook' ended (3900) with code 1.
```

I tried to install `dotnet interactive` tool, but there was the same error:
```
obratim@localhost /tmp/microsoft.powershell.sdk.7.4.3 $ dotnet interactive stdio
Unhandled exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=7.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'System.Management.Automation, Version=7.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Interactive.PowerShell.PowerShellKernel..ctor() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive.PowerShell\PowerShellKernel.cs:line 85
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.CreateKernel(String defaultKernelName, FrontendEnvironment frontendEnvironment, StartupOptions startupOptions, TelemetrySender telemetrySender) in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 488
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__20>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 333
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.App.CommandLine.CommandLineParser.<>c__DisplayClass5_0.<<Create>b__2>d.MoveNext() in D:\a\_work\1\s\src\dotnet-interactive\CommandLine\CommandLineParser.cs:line 161
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I tried to clone the `interactive` repository (https://github.com/dotnet/interactive.git) to understand what happends.
Some tests fails with the same error that file not found for `System.Management.Automation`.
In particular, when I edit file `PowerShellKernel.cs` and press `F12` on expression `typeof(PSObject)` to see what disassembler says, it lists disassembled file starting with this contradicting message:
```
#region Assembly System.Management.Automation, Version=7.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// /home/obratim/.nuget/packages/system.management.automation/7.4.2/ref/net8.0/System.Management.Automation.dll
#endregion

...
```
```


### Environment data

```powershell
I use Calculate Linux with kernel `6.6.32-calculate`

Visual Studio Code 1.92.0

dev-dotnet/dotnet-sdk-8.0.105
```

**Comment by obratim** [comment]
I think, referencing `System.Management.Automation` as a package inside `Microsoft.PowerShell.SDK.csproj` could help, so that file `System.Management.Automation.dll` would no longer be copied in the nuget package for `Microsoft.PowerShell.SDK`

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan

**Comment by obratim** [comment]
by the way, the package `System.Management.Automation` has itself this contradiction:

for version `7.4.3` for example, in the under folders `runtimes/unix/lib/net8.0/` and `runtimes/win/lib/net8.0/` there are files `System.Management.Automation.dll` with property `ProductVersion: 7.4.3`, as expected

but under at the path `ref/net8.0/System.Management.Automation.dll` the file has property `ProductVersion: 7.4.2`

how this even possible?

**Comment by DeviantSpark** [comment]
I am also seeing this issue and hoping for an update.

**Comment by Zyggyrat** [comment]
This appears to have no workaround and renders it impossible for me to use the PowerShell SDK in my C# console app at all. My only solution was to not use the PowerShell SDK at all (reverting to StartProcess approach instead). Feels like nobody else must be successfully using this SDK since the issue has not been fixed.

**Comment by hmodera** [comment]
Any update on this? @adityapatwardhan

**Comment by BornToBeRoot** [comment]
With the update from 7.4.6 to 7.5.0 of the SDK i get the same error:

`"The type or namespace name 'Management' does not exist in the namespace 'System'. (Possibly missing an assembly reference.)"`

Error message in the pipeline: https://ci.appveyor.com/project/BornToBeRoot/networkmanager/builds/51398021

Will this be fixed or is there a workaround?

**Comment by adityapatwardhan** [comment]
@BornToBeRoot - when updating from 7.4.x to 7.5.x, the .NET version should also be updated from .NET 8 to .NET 9.

**Comment by adityapatwardhan** [comment]
We have started pinning the reference assembly version to 7.4.6.500 for all subsequent releases for 7.4. Can you please retry with 7.4.6+ version?

**Comment by BornToBeRoot** [comment]
Ah ok, so the latest version for .NET 8 LTS ist PS 7.4.x?
