### ISSUE TITLE
[Build][Windows 11] Failing to complete local build with publish step based on current docs

### ISSUE THREAD

**Issue by 4creators** [PowerShell/PowerShell#24124]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Following exactly docs on Windows build requirements and commands I do get the following error:

Command after bootstrapping and importing build.psm1 module:
`
Start-PSBuild -Clean -Detailed -PSModuleRestore -UseNuGetOrg
`

`
VERBOSE: Build experimental feature list by running 'Get-ExperimentalFeature'
&: The term 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ConvertFrom-Json: Cannot bind argument to parameter 'InputObject' because it is null.
Get-Content: Cannot find path 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh.deps.json' because it does not exist.
PropertyNotFoundException: The property 'targets' cannot be found on this object. Verify that the property exists.
PropertyNotFoundException: The property 'targets' cannot be found on this object. Verify that the property exists.
`

### Expected behavior

```console
What I would expect is the following output and freshly build pwsh bundle in output directory i.e.:

`
Build succeeded in 6.6s
PowerShell output: c:/powershell/artifacts/release/pwsh.exe
Restore PowerShell modules to c:\powershell\artifacts\release
Name='PowerShellGet', Version='2.2.5', Destination='c:\powershell\artifacts\release\Modules'
Name='PackageManagement', Version='1.4.8.1', Destination='c:\powershell\artifacts\release\Modules'
Name='Microsoft.PowerShell.PSResourceGet', Version='1.0.5', Destination='c:\powershell\artifacts\release\Modules'
Name='Microsoft.PowerShell.Archive', Version='1.2.5', Destination='c:\powershell\artifacts\release\Modules'
Name='PSReadLine', Version='2.3.5', Destination='c:\powershell\artifacts\release\Modules'
Name='ThreadJob', Version='2.0.3', Destination='c:\powershell\artifacts\release\Modules'
VERBOSE: runtime pattern check: win7-x64 -match ^win.*-X64
VERBOSE: Generating experimental feature list
VERBOSE: Build experimental feature list by running 'Get-ExperimentalFeature'
VERBOSE: Removing microsoft.diasymreader.native.amd64.dll from pwsh.deps.json
VERBOSE: Performing the operation "Remove File" on target "C:\powershell\artifacts\release\microsoft.diasymreader.native.amd64.dll".
`
```

### Actual behavior

```console
Please find complete cmd log output for failing build:

`
Start-PSBuild -Clean -Detailed -PSModuleRestore -UseNuGetOrg

Cleaning your working directory. You can also do it with 'git clean -fdX --exclude .vs/PowerShell/v16/Server/sqlite3'
Removing .vs/
Removing src/Microsoft.Management.Infrastructure.CimCmdlets/bin/
Removing src/Microsoft.Management.Infrastructure.CimCmdlets/gen/
Removing src/Microsoft.Management.Infrastructure.CimCmdlets/obj/
Removing src/Microsoft.Management.UI.Internal/bin/
Removing src/Microsoft.Management.UI.Internal/gen/
Removing src/Microsoft.Management.UI.Internal/obj/
Removing src/Microsoft.PowerShell.Commands.Diagnostics/bin/
Removing src/Microsoft.PowerShell.Commands.Diagnostics/gen/
Removing src/Microsoft.PowerShell.Commands.Diagnostics/obj/
Removing src/Microsoft.PowerShell.Commands.Management/bin/
Removing src/Microsoft.PowerShell.Commands.Management/gen/
Removing src/Microsoft.PowerShell.Commands.Management/obj/
Removing src/Microsoft.PowerShell.Commands.Utility/bin/
Removing src/Microsoft.PowerShell.Commands.Utility/gen/
Removing src/Microsoft.PowerShell.Commands.Utility/obj/
Removing src/Microsoft.PowerShell.ConsoleHost/bin/
Removing src/Microsoft.PowerShell.ConsoleHost/gen/
Removing src/Microsoft.PowerShell.ConsoleHost/obj/
Removing src/Microsoft.PowerShell.CoreCLR.Eventing/bin/
Removing src/Microsoft.PowerShell.CoreCLR.Eventing/gen/
Removing src/Microsoft.PowerShell.CoreCLR.Eventing/obj/
Removing src/Microsoft.PowerShell.LocalAccounts/gen/
Removing src/Microsoft.PowerShell.SDK/bin/
Removing src/Microsoft.PowerShell.SDK/obj/
Removing src/Microsoft.PowerShell.Security/bin/
Removing src/Microsoft.PowerShell.Security/gen/
Removing src/Microsoft.PowerShell.Security/obj/
Removing src/Microsoft.WSMan.Management/bin/
Removing src/Microsoft.WSMan.Management/gen/
Removing src/Microsoft.WSMan.Management/obj/
Removing src/Microsoft.WSMan.Runtime/bin/
Removing src/Microsoft.WSMan.Runtime/obj/
Removing src/Modules/obj/
Removing src/ResGen/bin/
Removing src/ResGen/obj/
Removing src/System.Management.Automation/CoreCLR/CorePsTypeCatalog.cs
Removing src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/bin/
Removing src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/obj/
Removing src/System.Management.Automation/bin/
Removing src/System.Management.Automation/gen/
Removing src/System.Management.Automation/obj/
Removing src/TypeCatalogGen/bin/
Removing src/TypeCatalogGen/obj/
Removing src/TypeCatalogGen/powershell_win7-x64.inc
Removing src/powershell-unix/bin/
Removing src/powershell-unix/obj/
Removing src/powershell-win-core/bin/
Removing src/powershell-win-core/obj/
Removing test/xUnit/bin/
Removing test/xUnit/obj/
Removing tools/wix/obj/
VERBOSE: In Find-DotNet
VERBOSE: Executing:  dotnet --list-sdks
VERBOSE: Find-DotNet: dotnetCLIInstalledVersion = 9.0.100-preview.3.24204.13; chosenDotNetVersion = 9.0.100-preview.3.24204.13
VERBOSE: Using configuration 'Debug'
VERBOSE: Using framework 'net9.0'
VERBOSE: Using runtime 'win7-x64'
VERBOSE: Top project directory is C:\powershell\src\powershell-win-core
Run dotnet restore C:\powershell\src\powershell-win-core --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet /property:EnableWindowsTargeting=True /property:UseRidGraph=True
Restore complete (1.4s)

Build succeeded in 1.7s
Done restoring C:\powershell\src\powershell-win-core
Run dotnet restore C:\powershell/src/TypeCatalogGen --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet /property:EnableWindowsTargeting=True /property:UseRidGraph=True
Restore complete (0.3s)

Build succeeded in 0.6s
Done restoring C:\powershell/src/TypeCatalogGen
Run dotnet restore C:\powershell/src/ResGen --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet /property:EnableWindowsTargeting=True /property:UseRidGraph=True
Restore complete (0.3s)

Build succeeded in 0.5s
Done restoring C:\powershell/src/ResGen
Run dotnet restore C:\powershell/src/Modules --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet /property:EnableWindowsTargeting=True /property:UseRidGraph=True
Restore complete (0.5s)

Build succeeded in 0.7s
Done restoring C:\powershell/src/Modules
Run dotnet restore C:\powershell/tools/wix --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet /property:EnableWindowsTargeting=True /property:UseRidGraph=True
Restore complete (1.1s)

Build succeeded in 1.3s
Done restoring C:\powershell/tools/wix
Run ResGen (generating C# bindings for resx files)
Run TypeGen (generating CorePsTypeCatalog.cs)

Build succeeded in 0.6s
Restore complete (0.3s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  TypeCatalogGen succeeded (0.4s) → bin\x64\Debug\net9.0\TypeCatalogGen.dll

Build succeeded in 0.9s
VERBOSE: Building without shim
Run dotnet publish /property:GenerateFullPaths=true /property:ErrorOnDuplicatePublishOutputFiles=false --self-contained /property:UseRidGraph=true /property:IsWindows=true --configuration Debug --framework net9.0 --verbosity d --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop from C:\powershell\src\powershell-win-core
Restore complete (1.2s)

Build succeeded in 1.4s
  Microsoft.WSMan.Runtime succeeded (0.4s) → C:\powershell\src\Microsoft.WSMan.Runtime\bin\x64\Debug\net9.0\Microsoft.WSMan.Runtime.dll
  Microsoft.PowerShell.CoreCLR.Eventing succeeded (0.5s) → C:\powershell\src\Microsoft.PowerShell.CoreCLR.Eventing\bin\x64\Debug\net9.0\Microsoft.PowerShell.CoreCLR.Eventing.dll
  PSVersionInfoGenerator succeeded (0.2s) → C:\powershell\src\System.Management.Automation\SourceGenerators\PSVersionInfoGenerator\bin\x64\Debug\netstandard2.0\SMA.Generator.dll
  System.Management.Automation succeeded (8.0s) → C:\powershell\src\System.Management.Automation\bin\x64\Debug\net9.0\System.Management.Automation.dll
  Microsoft.PowerShell.Security succeeded (1.7s) → C:\powershell\src\Microsoft.PowerShell.Security\bin\x64\Debug\net9.0\Microsoft.PowerShell.Security.dll
  Microsoft.WSMan.Management succeeded (1.9s) → C:\powershell\src\Microsoft.WSMan.Management\bin\x64\Debug\net9.0\Microsoft.WSMan.Management.dll
  Microsoft.PowerShell.Commands.Diagnostics succeeded (2.0s) → C:\powershell\src\Microsoft.PowerShell.Commands.Diagnostics\bin\x64\Debug\net9.0\Microsoft.PowerShell.Commands.Diagnostics.dll
  Microsoft.Management.Infrastructure.CimCmdlets succeeded (1.9s) → C:\powershell\src\Microsoft.Management.Infrastructure.CimCmdlets\bin\x64\Debug\net9.0\Microsoft.Management.Infrastructure.CimCmdlets.dll
  Microsoft.PowerShell.ConsoleHost succeeded (2.0s) → C:\powershell\src\Microsoft.PowerShell.ConsoleHost\bin\x64\Debug\net9.0\Microsoft.PowerShell.ConsoleHost.dll
  Microsoft.PowerShell.Commands.Utility succeeded (2.1s) → C:\powershell\src\Microsoft.PowerShell.Commands.Utility\bin\x64\Debug\net9.0\Microsoft.PowerShell.Commands.Utility.dll
  Microsoft.PowerShell.Commands.Management succeeded (1.2s) → C:\powershell\src\Microsoft.PowerShell.Commands.Management\bin\x64\Debug\net9.0\Microsoft.PowerShell.Commands.Management.dll
  Microsoft.PowerShell.SDK succeeded (0.8s) → C:\powershell\src\Microsoft.PowerShell.SDK\bin\x64\Debug\net9.0\Microsoft.PowerShell.SDK.dll
  Microsoft.PowerShell.GraphicalHost succeeded (2.2s) → C:\powershell\src\Microsoft.Management.UI.Internal\bin\x64\Debug\net9.0\Microsoft.PowerShell.GraphicalHost.dll
  powershell-win-core net9.0 succeeded (2.5s) → bin\x64\Debug\net9.0\win7-x64\publish\

Build succeeded in 14.8s
PowerShell output: C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh.exe
Restore PowerShell modules to C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish
Name='PowerShellGet', Version='2.2.5', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
Name='PackageManagement', Version='1.4.8.1', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
Name='Microsoft.PowerShell.PSResourceGet', Version='1.0.5', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
Name='Microsoft.PowerShell.Archive', Version='1.2.5', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
Name='PSReadLine', Version='2.3.5', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
Name='ThreadJob', Version='2.0.3', Destination='C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\Modules'
VERBOSE: runtime pattern check: win7-x64 -match ^win.*-X64
VERBOSE: Generating experimental feature list
VERBOSE: Build experimental feature list by running 'Get-ExperimentalFeature'
&: The term 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ConvertFrom-Json: Cannot bind argument to parameter 'InputObject' because it is null.
Get-Content: Cannot find path 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh.deps.json' because it does not exist.
PropertyNotFoundException: The property 'targets' cannot be found on this object. Verify that the property exists.
PropertyNotFoundException: The property 'targets' cannot be found on this object. Verify that the property exists.
`
```

### Error details

```console
`
Exception             :
    Type        : System.Management.Automation.PropertyNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The property 'targets' cannot be found on this object. Verify that the property exists.
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PropertyNotFoundStrict
        InvocationInfo        :
            ScriptLineNumber : 3595
            OffsetInLine     : 5
            HistoryId        : 49
            ScriptName       : C:\powershell\build.psm1
            Line             :     $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject.Properties.Name -like 'runtimepack.Microsoft.WindowsDesktop.App.Runtime*'

            Statement        : $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject.Properties.Name -like 'runtimepack.Microsoft.WindowsDesktop.App.Runtime*'
            PositionMessage  : At C:\powershell\build.psm1:3595 char:5
                               +     $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject. …
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\powershell
            PSCommandPath    : C:\powershell\build.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Clear-NativeDependencies, C:\powershell\build.psm1: line 3595
                                at Start-PSBuild, C:\powershell\build.psm1: line 718
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object)
    Message     : The property 'targets' cannot be found on this object. Verify that the property exists.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure, CallSite, Object)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
FullyQualifiedErrorId : PropertyNotFoundStrict
InvocationInfo        :
    ScriptLineNumber : 3595
    OffsetInLine     : 5
    HistoryId        : 49
    ScriptName       : C:\powershell\build.psm1
    Line             :     $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject.Properties.Name -like 'runtimepack.Microsoft.WindowsDesktop.App.Runtime*'

    Statement        : $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject.Properties.Name -like 'runtimepack.Microsoft.WindowsDesktop.App.Runtime*'
    PositionMessage  : At C:\powershell\build.psm1:3595 char:5
                       +     $runtimePackWinDesktop = $deps.targets.${targetRuntime}.PSObject. …
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\powershell
    PSCommandPath    : C:\powershell\build.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Clear-NativeDependencies, C:\powershell\build.psm1: line 3595
                        at Start-PSBuild, C:\powershell\build.psm1: line 718
                        at <ScriptBlock>, <No file>: line 1
`
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 4creators** [comment]
Build was tested at this commit:

`commit a1774fd9332925f7635e0832b64b2d158e3a3745

**Comment by daxian-dbw** [comment]
@4creators I cannot reproduce your building failure.

In your case, the `pwsh.exe` was already produced:
> Build succeeded in 14.8s
PowerShell output: C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh.exe
Restore PowerShell modules to C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish
...

But executing `C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh` failed due to the `pwsh` file cannot be found.
> &: The term 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh' is not recognized as a name of a cmdlet, function, script file, or executable program.

The `pwsh.deps.json` file also couldn't be found
> Get-Content: Cannot find path 'C:\powershell\src\powershell-win-core\bin\Debug\net9.0\win7-x64\publish\pwsh.deps.json' because it does not exist.

It looks to me the generated build artifacts such as `pwsh.exe` and `pwsh.deps.json` were somehow deleted during the build. The issue should be something related to your local system.

**Comment by 4creators** [comment]
@daxian-dbw Yes, you are right. This is local build environment issue related to using Visual Studio 2022 development terminal as build environment. Build does not fail with plain terminal or pwsh. After investigating further it turns out that environment value `Platform=x64` or with any other architecture introduced with dev terminal causes above build errors.

My proposal would be to either i) explicitly indicate in build docs that Visual Studio dev terminals environments conflict with build infra or ii) accept proposed fix to build scripts.

**Comment by adityapatwardhan** [comment]
We will update the docs to not use Visual Studio dev terminal to building PowerShell. An alternative is to use the PowerShell terminal in VSCode.
