### ISSUE TITLE
PS Remoting does not function after upgrading to 7.4.4 from 7.2.19

### ISSUE THREAD

**Issue by danikuci1** [PowerShell/PowerShell#24140]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After upgrading machines from 7.2.19 to 7.4.4, none of them are able to accept remoting connections despite PS remoting being enabled and firewall rules in place.

### Expected behavior

```console
PS C:\> Enter-PSSession -ConfigurationName 'PowerShell.7' -ComputerName "myremoteserverwithps7installed"
[myremoteserverwithps7installed]: PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
```

### Actual behavior

```console
PS C:\> Enter-PSSession -ConfigurationName 'PowerShell.7' -ComputerName "myremoteserverwithps7installed"
Enter-PSSession: Connecting to remote server myremoteserverwithps7installed failed with the following error message : Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. For more information, see the about_Remote_Troubleshooting Help topic.
```

### Error details

```console
PS C:\> get-error

Exception             :
    Type        : System.Management.Automation.Remoting.PSRemotingTransportException
    ErrorCode   : -2141974624
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Connecting to remote server myremoteserverwithps7installed failed with the following error message : Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. For more information, see the about_Remote_Troubleshooting Help topic.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException
    TargetSite  :
        Name          : EndInvoke
        DeclaringType : System.Management.Automation.Runspaces.AsyncResult, System.Management.Automation, Version=7.2.19.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Connecting to remote server myremoteserverwithps7installed failed with the following error message : Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. For more information, see the about_Remote_Troubleshooting Help topic.
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.CreateTemporaryRemoteRunspace(PSHost host, WSManConnectionInfo connectionInfo)
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.CreateRunspaceWhenComputerNameParameterSpecified()
TargetObject          : myremoteserverwithps7installed
CategoryInfo          : InvalidArgument: (myremoteserverwithps7installed:String) [Enter-PSSession], PSRemotingTransportException
FullyQualifiedErrorId : CreateRemoteRunspaceFailed
InvocationInfo        :
    MyCommand        : Enter-PSSession
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Enter-PSSession -ConfigurationName 'PowerShell.7' -ComputerName "myremoteserverwithps7installed" -Credential $credential
    PositionMessage  : At line:1 char:1
                       + Enter-PSSession -ConfigurationName 'PowerShell.7' -ComputerName "myremoteserverwithps7installed …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Enter-PSSession
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by danikuci1** [comment]
`([AppDomain]::CurrentDomain.GetAssemblies())` shows that C:\Program Files\PowerShell\7\System.Security.Cryptography.dll is present on disk

**Comment by danikuci1** [comment]
also fails when attempting to open a session locally

```
New-PSSession -ComputerName localhost -ConfigurationName PowerShell.7
New-PSSession: [localhost] Connecting to remote server localhost failed with the following error message : Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. For more information, see the about_Remote_Troubleshooting Help topic.
```

**Comment by jborean93** [comment]
You need to unregister the PowerShell.7 configuration and re-register it with `Enable-PSRemoting`.

```powershell
Get-PSSessionConfiguration -Name PowerShell.7 | Unregister-PSSessionConfiguration
Enable-PSRemoting
```

This was a problem because PowerShell 7.3 added a direct dependency to this new dll and the WSMan configuration dll needs to be updated to trust `System.Security.Cryptography.dll` so it'll load with PowerShell on the new session. Unfortunately updating PowerShell won't update this dll because it's copied to a location in `C:\Windows\System32` so you need to unregister it and re-register the configuration so the new dll is copied across.
