### ISSUE TITLE
Scope polluted and error is thrown

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/PowerShell#24227]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Steps:

1. Open VS Code and run the test code below in PowerShell 7.4.4
2. Notice after running the code for the first time: no issue, after the second run the following error is thrown: 

`ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "`

This only happens when the following line is present in the script. Removing this line resolves the issue, but it is required for us to close some sessions.

```powershell
Get-PSSession | Remove-PSSession -EA Ignore
```
### Test code

```powershell
Param (
    $MaxConcurrentJobs = 1,
    $Actions = 0..1
)

$VerbosePreference = 'Continue'
$Error.Clear()

$EventVerboseParams = @{
    ErrorAction = 'Stop'
    Source      = 'TEST'
    EntryType   = 'Information'
    EventID     = '1'
    LogName     = 'HCScripts'
}

$M = 'Script started'
Write-Verbose $M
Write-EventLog @EventVerboseParams -Message $M

$scriptBlock = {
    #region Declare variables for code running in parallel
    if (-not $MaxConcurrentJobs) {
        $VerbosePreference = $using:VerbosePreference
        $EventVerboseParams = $using:EventVerboseParams
    }
    #endregion

    $M = "Script execution task $_"
    Write-Verbose $M
    Write-EventLog @EventVerboseParams -Message $M
}

#region Run code serial or parallel
$foreachParams = if ($MaxConcurrentJobs -eq 1) {
    @{
        Process = $scriptBlock
    }
}
else {
    @{
        Parallel      = $scriptBlock
        ThrottleLimit = $MaxConcurrentJobs
    }
}

$Actions | ForEach-Object @foreachParams
#endregion

$M = 'Script finished'
Write-Verbose $M
Write-EventLog @EventVerboseParams -Message $M

# Comment the next line and run the code again in a clean PowerShell session
# notice no error is thrown even after running this code multiple times
Get-PSSession | Remove-PSSession -EA Ignore
```

### Expected behavior

```console
After each run these messages should be displayed, not only after the first run:

#### First run & second run
VERBOSE: Script started
VERBOSE: Script execution task 0
VERBOSE: Script execution task 1
VERBOSE: Script finished
```

### Actual behavior

```console
#### First run
VERBOSE: Script started
VERBOSE: Script execution task 0
VERBOSE: Script execution task 1
VERBOSE: Script finished

#### Second run
VERBOSE: Script started
Creating a new session for implicit remoting of "Write-EventLog" command...
ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "
```

### Error details

```console
Exception             : 
    Type                        : System.Management.Automation.MethodInvocationException
    ErrorRecord                 : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CmdletInvocationException
        InvocationInfo        : 
            ScriptLineNumber : 3398
            OffsetInLine     : 13
            HistoryId        : 2
            ScriptName       : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPower 
ShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
            Line             : $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)

            Statement        : $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
            PositionMessage  : At C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPo 
werShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1:3398 char:13
                               +             $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI …
                               +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f
            PSCommandPath    : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPower 
ShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock><Begin>, C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remo 
teIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1: line 3398
                                at <ScriptBlock>, T:\Test\Brecht\PowerShell\Testie1.ps1: line 19
                                at <ScriptBlock>, <No file>: line 1
    WasThrownFromThrowStatement : True
    TargetSite                  : 
        Name          : Invoke
        DeclaringType : [System.Management.Automation.Runspaces.PipelineBase]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message                     : Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "
    Data                        : System.Collections.ListDictionaryInternal
    InnerException              : 
        Type           : System.Management.Automation.CmdletInvocationException
        ErrorRecord    : 
            Exception             : 
                Type        : System.Management.Automation.PSInvalidOperationException
                ErrorRecord : 
                    Exception             : 
                        Type    : System.Management.Automation.ParentContainsErrorRecordException
                        Message : The parameter is incorrect. 
                        HResult : -2146233087
                    CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
                    FullyQualifiedErrorId : InvalidOperation
                TargetSite  : 
                    Name          : Initialize
                    DeclaringType : [System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager]
                    MemberType    : Method
                    Module        : System.Management.Automation.dll
                Message     : The parameter is incorrect. 
                Source      : System.Management.Automation
                HResult     : -2146233079
                StackTrace  : 
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.Initialize(Uri connectionUri, WSManConnectionInfo connectionInfo)
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager..ctor(Guid runspacePoolInstanceId, WSManConnectionInfo connectionInfo, PSRemotingCryptoHelper cryptoHelper, String  
sessionName)
   at System.Management.Automation.Runspaces.WSManConnectionInfo.CreateClientSessionTransportManager(Guid instanceId, String sessionName, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl..ctor(ClientRemoteSession session, PSRemotingCryptoHelper cryptoHelper, RunspaceConnectionInfo connectionInfo,
URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspacePoolInternal rsPool, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreateClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDSHandler(TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary
applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments,
RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.RemoteRunspace..ctor(TypeTable typeTable, RunspaceConnectionInfo connectionInfo, PSHost host, PSPrimitiveDictionary applicationArguments, String name, Int32 id)       
   at Microsoft.PowerShell.Commands.NewPSSessionCommand.CreateRunspacesWhenComputerNameParameterSpecified()
   at Microsoft.PowerShell.Commands.NewPSSessionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
            CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
            FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.NewPSSessionCommand
            InvocationInfo        : 
                MyCommand        : New-PSSession
                ScriptLineNumber : 137
                OffsetInLine     : 17
                HistoryId        : 2
                ScriptName       : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftP 
owerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
                Line             : & $script:NewPSSession `

                Statement        : & $script:NewPSSession `
                                   -ConfigurationName '' `
                                   -SessionOption (Get-PSImplicitRemotingSessionOption) `
                                   `
                                   -CertificateThumbprint ''
                PositionMessage  : At C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_Microso 
ftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1:137 char:17
                                   +                 & $script:NewPSSession `
                                   +                 ~~~~~~~~~~~~~~~~~~~~~~~~
                PSScriptRoot     : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f
                PSCommandPath    : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftP 
owerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
                InvocationName   : &
                CommandOrigin    : Internal
            ScriptStackTrace      : at Get-PSImplicitRemotingSession, C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35 
f9c55a4f\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1: line 137
                                    at <ScriptBlock><Begin>, C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\
remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1: line 3398
                                    at <ScriptBlock>, T:\Test\Brecht\PowerShell\Testie1.ps1: line 19
                                    at <ScriptBlock>, <No file>: line 1
            PipelineIterationInfo : 
                              0
                              1
        TargetSite     : 
            Name          : CheckActionPreference
            DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : The parameter is incorrect. 
        Data           : System.Collections.ListDictionaryInternal
        InnerException : 
            Type        : System.Management.Automation.PSInvalidOperationException
            ErrorRecord : 
                Exception             : 
                    Type    : System.Management.Automation.ParentContainsErrorRecordException
                    Message : The parameter is incorrect. 
                    HResult : -2146233087
                CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
                FullyQualifiedErrorId : InvalidOperation
            TargetSite  : 
                Name          : Initialize
                DeclaringType : [System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager]
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message     : The parameter is incorrect. 
            Source      : System.Management.Automation
            HResult     : -2146233079
            StackTrace  : 
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.Initialize(Uri connectionUri, WSManConnectionInfo connectionInfo)
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager..ctor(Guid runspacePoolInstanceId, WSManConnectionInfo connectionInfo, PSRemotingCryptoHelper cryptoHelper, String  
sessionName)
   at System.Management.Automation.Runspaces.WSManConnectionInfo.CreateClientSessionTransportManager(Guid instanceId, String sessionName, PSRemotingCryptoHelper cryptoHelper)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl..ctor(ClientRemoteSession session, PSRemotingCryptoHelper cryptoHelper, RunspaceConnectionInfo connectionInfo,
URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspacePoolInternal rsPool, URIDirectionReported uriRedirectionHandler)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.CreateClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
   at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDSHandler(TypeTable typeTable)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary
applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary applicationArguments,
RunspaceConnectionInfo connectionInfo, String name)
   at System.Management.Automation.RemoteRunspace..ctor(TypeTable typeTable, RunspaceConnectionInfo connectionInfo, PSHost host, PSPrimitiveDictionary applicationArguments, String name, Int32 id)       
   at Microsoft.PowerShell.Commands.NewPSSessionCommand.CreateRunspacesWhenComputerNameParameterSpecified()
   at Microsoft.PowerShell.Commands.NewPSSessionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
        Source         : System.Management.Automation
        HResult        : -2146233087
        StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.CommandProcessorBase.Complete()
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]      
commandRedirections, FunctionContext funcContext)
   at lambda_method1341(Closure, FunctionContext)
   at System.Management.Automation.Language.Compiler.GetExpressionValue(ExpressionAst expressionAst, Boolean isTrustedInput, ExecutionContext context, SessionStateInternal sessionStateInternal,
IDictionary usingValues, Func`2& lambda, IScriptExtent[]& sequencePoints, Type& localsTupleType)
   at System.Management.Automation.PipelineOps.GetSteppablePipeline(PipelineAst pipelineAst, CommandOrigin commandOrigin, ScriptBlock scriptBlock, Object[] args)
   at CallSite.Target(Closure, CallSite, Object, Object)
    Source                      : System.Management.Automation
    HResult                     : -2146233087
    StackTrace                  : 
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings) in
C:\__w\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 76
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeCommand[TResult](PowerShell pwsh, PSCommand psCommand, PSInvocationSettings invocationSettings) in       
C:\__w\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 99
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) in
C:\__w\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 136
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : CmdletInvocationException
InvocationInfo        : 
    ScriptLineNumber : 3398
    OffsetInLine     : 13
    HistoryId        : 2
    ScriptName       : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPowerShellMan 
agement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
    Line             : $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)

    Statement        : $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
    PositionMessage  : At C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPowerShell 
Management_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1:3398 char:13
                       +             $steppablePipeline = $scriptCmd.GetSteppablePipeline($myI …
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f
    PSCommandPath    : C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoProxy_MicrosoftPowerShellMan  
agement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock><Begin>, C:\Users\bgijbels\AppData\Local\Temp\2\remoteIpMoProxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f\remoteIpMoPr  
oxy_MicrosoftPowerShellManagement_3.1.0.0_localhost_37343236-1bdb-4a58-805a-bf35f9c55a4f.psm1: line 3398
                        at <ScriptBlock>, T:\Test\Brecht\PowerShell\Testie1.ps1: line 19
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
It seems that some runspace initialization or new session code is missing here.
Perhaps you will be interested in the PowerShell project I wrote: search for "kasini3000"
It uses SQLite database to encapsulate multiprocessing and multi-threaded concurrency.

**Comment by rhubarb-geek-nz** [comment]
It looks like you have closed a session that was being used by Write-EventLog judging by the line about creating it the second time.

Rather than silently close all sessions, show what sessions you are closing.

**Comment by mklement0** [comment]
Good catch, @rhubarb-geek-nz:

The cause of the problem is indeed the removal of the session that was implicitly created by invoking `Write-EventLog`; the latter can only be used via the  [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility).

It is unfortunate that the error message is so obscure, though.

To exclude this implicitly created session from removal, use the following:

```
Get-PSSession | Where-Object Name -ne WinPSCompatSession | Remove-PSSession
```

**Comment by DarkLite1** [comment]
> It looks like you have closed a session that was being used by Write-EventLog judging by the line about creating it the second time.
> 
> Rather than silently removing all sessions, show what sessions you are removing.

There is no session opened anywhere in the test code posted. Or maybe I don't really get what you're saying. Even when `Foreach-Object -Process` is used, without runspaces, it still throws the same error.
