### ISSUE TITLE
7.4.5 windows-arm build fails to start with TypeInitializationException

### ISSUE THREAD

**Issue by lilith** [PowerShell/PowerShell#24226]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'C:\Program Files\PowerShell\7\Newtonsoft.Json.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'C:\Program Files\PowerShell\7\Newtonsoft.Json.dll'
   at System.Management.Automation.Configuration.PowerShellConfig..ctor()
   at System.Management.Automation.Configuration.PowerShellConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Utils.GetPolicySettingFromConfigFile[T](ConfigScope[] preferenceOrder)
   at System.Management.Automation.Utils.GetPolicySetting[T](ConfigScope[] preferenceOrder)
   at Microsoft.PowerShell.CommandLineParameterParser.GetConfigurationNameFromGroupPolicy()
   at Microsoft.PowerShell.ConsoleHost.ParseCommandLine(String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args)

[process exited with code 3762504530 (0xe0434352)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

### Expected behavior

```console
Powershell 7 (Arm) starts.
```

### Actual behavior

```console
Crashes
```

### Environment data

```powershell
Cannot access
```

**Comment by lilith** [comment]
Duplicate of https://github.com/PowerShell/PowerShell/issues/23969, but I think it should either support both versions installed side-by-side, or make the installer prevent both.

**Comment by SteveL-MSFT** [comment]
If this is a Microsoft update problem, then that's something the team can investigate.  As noted, if this is installing multiple architectures on same system, then that is not supported.  Use the zip package if you are a developer that requires both architectures.

**Comment by lilith** [comment]
Still bad UX

**Comment by rhubarb-geek-nz** [comment]
> Still bad UX

It is not problem unique to PowerShell. See [MSI for ARM64 Java should install in C:\Program Files, not C:\Program Files (Arm)](https://github.com/microsoft/openjdk/issues/344). The mistake referenced with Java was they were installing ARM64 into a directory for 32-bit ARM.

This dates back to the move from WIN32 to WIN64, and then porting to DEC-Alpha,  MIPS, PowerPC, ARM and more recently to ARM64. 

The decision was made that "C:\Program Files" is allocated to the primary architecture of the host. However, for backwards compatibility it is possible to install x64 programs on non-x64 64-bit machines.

So on ARM64 we have

`C:\Program Files` and `C:\Windows\System32`
`C:\Program Files (Arm)` and `C:\Windows\SysArm32`
`C:\Program Files (x86)` and `C:\Windows\SysWOW64`

The choice could have been made that when an MSI installs x64 onto an ARM64 machine then it goes into "c:\Program Files (x64)" rather than "C:\Program Files", but they didn't.

**Comment by lilith** [comment]
My point is that this kind of corruption is avoidable at the installer
level. .msi custom actions (type 2) can run executables, and checking the
architecture of a .exe or .dll is maybe 4 lines of Rust. Might add a couple
hundred kb at most?

I'd be suprised if there isn't already a recipie for making installers
resilient, but it's hardly much work to add a check and prevent this kind
of corruption, and stave off the inevitable influx of support cost.

**Comment by rhubarb-geek-nz** [comment]
The ARM64 MSI is a very new feature for PowerShell despite ARM64 windows having been available for a couple of years. The ARM64 MSI for Windows first came out with 7.4.3

An alternative would be to use WIX_NATIVE_MACHINE ([example](https://github.com/dotnet/aspnetcore/pull/37318)) to prevent the x64 being installed on ARM64.

**Comment by lilith** [comment]
Perhaps a stupid question, but when pwsh invokes child processes, does its
architecture affect the child processes at all?

**Comment by rhubarb-geek-nz** [comment]
In Windows a process runs with a single architecture, and all native dlls loaded into that process must be of the same architecture.  The architecture of that process is governed by the exe program that is used by CreateProcess, which may be specified exactly or found on the path. Which dlls are loaded are then dependent on the exe and the path. DotNet's runtime permits 'any' architecture dlls to be used by any CPU.

**Comment by SteveL-MSFT** [comment]
> An option would be to use WIX_NATIVE_MACHINE ([example](https://github.com/dotnet/aspnetcore/pull/37318)) to prevent the x64 being installed on ARM64.

Seems like we could use that variable to error out if the architecture doesn't match.  Marking this `up-for-grabs` if someone wants to make a fix.

**Comment by lilith** [comment]
Do we want to prevent x64 from installing on woa? That might have unintended consequences and will probably break a lot of tooling that installs pwsh automatically.

**Comment by lilith** [comment]
I think the correct thing to do is require uninstallation of x86_64 before allowing aarch64 to be installed and vice versa (which probably fixes update issues too, not just user error) 

Only allowing the native version of a product limits workarounds for architecture specific issues.

I realize checking the currently installed architecture adds complexity, but if it's the most correct thing to do, we should probably do it, and open-source the approach used for the msi, so other products can do the same.

I could probably make a tiny rust executable with no dependencies (other than the ucrt), if that is the best way forward. I've had to implement this kind of thing in C# before, due to how bad .NET 4.X is about native/arch-specific dependency resolution.

**Comment by rhubarb-geek-nz** [comment]
Can I suggest testing aspnetcore and confirm the mechanism it claims to implement works?

I see PowerShell as part of the same family as aspnetnet & dotnet-sdk so it would be strange to adopt a different approach to the same problem.
