### ISSUE TITLE
Using Microsoft.Powershell.SDK 7.4.5 (.NET Core 8) on Ubuntu 24.04 fails loading libpsl-native

### ISSUE THREAD

**Issue by stefanboerner** [PowerShell/PowerShell#24342]
### Steps to reproduce

Using Microsoft.PowerShell.SDK fails on Ubuntu 24.04 with the following exception

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace.
```
   
The Microsoft.PowerShell.Native Nuget package containing the missing libpsl-native.so is available on the system. If I check the /runtimes folder, instead of

`/home/<appPath>/runtimes/unix/lib/net8.0/libpsl-native.so
`
as the stacktrace implies, libpsl-native.so is located in

`/home/<appPath>/runtimes/linux-x64/native/libps-native.so`

So it seems, something is off with the nuget package(s).
The package used is Microsoft.Powershell.SDK 7.4.5

### Expected behavior

```console
.NET Core application is able to create a runspace to run powershell commands
```

### Actual behavior

```console
An exception is thrown pointing out that libpsl-native.so cannot be found
```

### Error details

```console
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libpsl-native.so: cannot open shared object file: No such file or directory
/home/<appPath>/runtimes/unix/lib/net8.0/libpsl-native.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/liblibpsl-native.so: cannot open shared object file: No such file or directory
/home/<appPath>/runtimes/unix/lib/net8.0/liblibpsl-native.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/libpsl-native: cannot open shared object file: No such file or directory
/home/<appPath>/runtimes/unix/lib/net8.0/libpsl-native: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.8/liblibpsl-native: cannot open shared object file: No such file or directory
/home/<appPath>/runtimes/unix/lib/net8.0/liblibpsl-native: cannot open shared object file: No such file or directory

   at System.Management.Automation.Tracing.NativeMethods.OpenLog(IntPtr ident, SysLogPriority facility)
   at System.Management.Automation.Tracing.SysLogProvider..ctor(String applicationId, PSLevel level, PSKeyword keywords, PSChannel channels)
   at System.Management.Automation.Tracing.PSSysLogProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSSysLogProvider..ctor()
   at System.Management.Automation.Tracing.PSEtwLog..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSEtwLog.LogOperationalInformation(PSEventId id, PSOpcode opcode, PSTask task, PSKeyword keyword, Object[] args)
   at System.Management.Automation.Remoting.RemoteSessionNamedPipeServer.ProcessListeningThread(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Ubuntu 24.04.1 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Hi, fortunately I have a [project ready to go](https://github.com/rhubarb-geek-nz/powershell-executive) to demo this.

Check the environment

```
$ grep ID /etc/os-release 
VERSION_ID="24.04"
ID=ubuntu
ID_LIKE=debian
```

First compile and run in one step....

```
$ dotnet run --framework net8.0 -OutputString echo foo
foo
```

That works, so now run the dll with dotnet

```
$ dotnet bin/Release/net8.0/pwshexec.dll  -OutputString echo foo
foo
```

That works, so run the compiled program

```
$ bin/Release/net8.0/pwshexec -OutputString echo foo
foo
```

So all present and correct

```
$ find bin -name "libpsl*.so"
bin/Release/net8.0/runtimes/linux-arm/native/libpsl-native.so
bin/Release/net8.0/runtimes/linux-x64/native/libpsl-native.so
bin/Release/net8.0/runtimes/linux-arm64/native/libpsl-native.so
bin/Release/net8.0/runtimes/linux-musl-x64/native/libpsl-native.so
```

So lets remove those shared libraries

```
$ find bin -name "libpsl*.so" | xargs rm
```

Now try and run and we get a similar list as you get searching for a library. Except it alternates looking for `unix` and `linux-x64` which seems appropriate. Now yours only looks under `unix` which is odd.

The only dotnet-sdk I have on my machine is dotnet-sdk-8.0 provided by Ubuntu.

Is your app compiled for 'any' or for a specific architecture?

**Comment by stefanboerner** [comment]
Turns out, the assembly that called "my" code had a custom AssemblyLoadContext implementation that had a Bug. Issue is resolved. Thanks for your input.
