### ISSUE TITLE
pwsh crashes when callback scriptblock passed to TcpClient.BeginConnect is called

### ISSUE THREAD

**Issue by guyrleech** [PowerShell/PowerShell#24415]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run these lines and pwsh.exe will crash , presumably when the callback is called. If BeginConnect is called with $null for the callback  the crash does not occur.

```
$TCPClient = [System.Net.Sockets.TcpClient]::new()
$callback = { Param($object) ; "Hello World" }
$tcpClient.BeginConnect( 'microsoft.com' , 443, [System.AsyncCallback]$callback , $TCPClient )

```

Also crashes 5.1

### Expected behavior

```console
Hello World is echoed (probably) but the pwsh.exe process does not crash
```

### Actual behavior

```console
pwsh crashes
```

### Error details

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:  Param($object) ; "Hello World"
   at System.Management.Automation.ScriptBlock.GetContextFromTLS()
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at lambda_method133(Closure, IAsyncResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[process exited with code 3762504530 (0xe0434352)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
This is unfortunately what happens when a scriptblock is executed as a delegate in another thread than the main one that PowerShell is running on. Without a Runspace being present the scriptblock cannot be run.

Unfortunately there is little you can do in PowerShell to avoid this. Your main options are to:

+ Find a method that doesn’t execute a callback/delegate in another thread
+ Define the delegate as C# code through Add-Type

I’m not 100% sure if anything can be done about the crash as that happens in the .NET stack here but maybe PowerShell can do something to handle it.
