### ISSUE TITLE
Provide a standardised mechanism to render nested attributes expanded (in a dependency-preserving manner):

### ISSUE THREAD

**Issue by RokeJulianLockhart** [PowerShell/PowerShell#24471]
### Summary of the new feature / enhancement

Provide a standardised way to render nested attributes expanded (with `Format-Table` and `Format-List`). This would affect any PSObject with nested attributes. However, it would also make a `tree` replacement using `Get-ChildItem` significantly easier to implement.

As an example, consider the undermentioned question that I posed earlier today:

<blockquote cite="https://github.com/PowerShell/PowerShell/discussions/24470#discussion-7347207">

An example is available at [this GitHub issue-comment](https://github.com/Pscx/Pscx/issues/103#issue-2601956172):

> ```log
> Exception             : 
>     Type       : System.IO.FileNotFoundException
>     Message    : Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
>                  
>     FileName   : System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>     TargetSite : 
>         Name          : GetExportedTypes
>         DeclaringType : [System.Reflection.RuntimeAssembly]
>         MemberType    : Method
>         Module        : System.Private.CoreLib.dll
>     Source     : System.Private.CoreLib
>     HResult    : -2147024894
>     StackTrace : 
>    at System.Reflection.RuntimeAssembly.GetExportedTypes()
>    at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
>    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
>    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
>    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean& found, String 
> shortModuleName, Boolean disableFormatUpdates)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Object 
> privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 
> requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& 
> moduleFileFound)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingMultiVersionModuleBase(String moduleBase, ManifestProcessingFlags manifestProcessingFlags, ImportModuleOptions importModuleOptions, Boolean& found)
>    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
>    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
>    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
>    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
>    at System.Management.Automation.CommandProcessor.ProcessRecord()
> CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
> FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
> InvocationInfo        : 
>     MyCommand        : Import-Module
>     ScriptLineNumber : 1
>     OffsetInLine     : 1
>     HistoryId        : 15
>     Line             : Import-Module 'Pscx'
>     Statement        : Import-Module 'Pscx'
>     PositionMessage  : At line:1 char:1
>                        + Import-Module 'Pscx'
>                        + ~~~~~~~~~~~~~~~~~~~~
>     InvocationName   : Import-Module
>     CommandOrigin    : Internal
> ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
> ```

Specifically, the undermentioned section:

> ```log
>     FileName   : System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
>     TargetSite : 
>         Name          : GetExportedTypes
>         DeclaringType : [System.Reflection.RuntimeAssembly]
>         MemberType    : Method
>         Module        : System.Private.CoreLib.dll
> ```

Summarily, how can I replicate `TargetSite` printing its properties with their values, with indentation to visualise the depedency? I ask because I've been utterly unable to locate online and alone how to force a PSObject with nested properties to render them in the CLI as a tree like `Get-Error` is evidently able to.

---

Originally asked at [Reddit](https://www.reddit.com/r/PowerShell/comments/1g8pwwo/comment/lt05ctx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), but it was immediately redacted by AutoMod.

</blockquote>

### Proposed technical implementation details (optional)

As [its (currently sole) response](https://github.com/PowerShell/PowerShell/discussions/24470#discussioncomment-11009430) states:

> There's no single/automatic way of doing this unfortunately. The `Get-Error` cmdlet works by inserting the `System.Management.Automation.ErrorRecord#PSExtendedError` type name to the error object and PowerShell has a custom formatter set for that type name to do the manual string building to create this format [in the undermentioned]:
> 
> https://github.com/PowerShell/PowerShell/blob/623c45174ac7c455518f1e0f11fa485110bcb45d/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L824-L1030
> 
> You can certainly copy/modify the code for your own needs but it's not a simple function you can call here and something very specific to the `Get-Error` output. You could look at using a YAML library to try and achieve a similar setup but it won't strictly be the same as the `Get-Error` format which is YAML like but not actually YAML.

**Comment by 237dmitry** [comment]
In my opinion you can examine ErrorRecord object by its properties:

```powershell
(Get-Error).Exception.TargetSite      # list output
```

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/24471#issuecomment-2427816955

@237dmitry, I'm referring to a situation in which you want to see the contents of `(Get-Error).Exception`:

<blockquote>

```log
ErrorRecord                 : The 'Show-Tree' command was found in the module 'Pscx', but the module could not be loaded due to the following error: [Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              ]
                              For more information, run 'Import-Module Pscx'.
CommandName                 : Show-Tree
WasThrownFromThrowStatement : False
TargetSite                  : System.Management.Automation.CommandInfo TryModuleAutoDiscovery(System.String, System.Management.Automation.ExecutionContext, System.String, System.Management.Automation.CommandOrigin, System.Management.Automation.SearchResolutionOptions, System.Management.Automation.CommandTypes, 
                              System.Exception ByRef)
Message                     : The 'Show-Tree' command was found in the module 'Pscx', but the module could not be loaded due to the following error: [Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              ]
                              For more information, run 'Import-Module Pscx'.
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.Management.Automation.CmdletInvocationException: Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              
                               ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              
                              File name: 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
                                 at System.Reflection.RuntimeAssembly.GetExportedTypes()
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                                 at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String 
                              prefix, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& 
                              moduleFileFound)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags 
                              manifestProcessingFlags, Object privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version 
                              requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& 
                              moduleFileFound)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T]()
                                 at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateEntryVisibility visibility, Exception& exception)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                                 at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                                 at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                                 at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

</blockquote>

...and the children of its properties (in this case, `TargetSite`):

<blockquote>

```log
Name                       : TryModuleAutoDiscovery
DeclaringType              : System.Management.Automation.CommandDiscovery
ReflectedType              : System.Management.Automation.CommandDiscovery
MemberType                 : Method
MetadataToken              : 100667239
Module                     : System.Management.Automation.dll
IsSecurityCritical         : True
IsSecuritySafeCritical     : False
IsSecurityTransparent      : False
MethodHandle               : System.RuntimeMethodHandle
Attributes                 : Private, Static, HideBySig
CallingConvention          : Standard
ReturnType                 : System.Management.Automation.CommandInfo
ReturnTypeCustomAttributes : System.Management.Automation.CommandInfo
ReturnParameter            : System.Management.Automation.CommandInfo
IsCollectible              : False
IsGenericMethod            : False
IsGenericMethodDefinition  : False
ContainsGenericParameters  : False
MethodImplementationFlags  : IL
IsAbstract                 : False
IsConstructor              : False
IsFinal                    : False
IsHideBySig                : True
IsSpecialName              : False
IsStatic                   : True
IsVirtual                  : False
IsAssembly                 : False
IsFamily                   : False
IsFamilyAndAssembly        : False
IsFamilyOrAssembly         : False
IsPrivate                  : True
IsPublic                   : False
IsConstructedGenericMethod : False
CustomAttributes           : {}
```

</blockquote>

...inline, like the undermentioned (custom) example:

```log
ErrorRecord                 : The 'Show-Tree' command was found in the module 'Pscx', but the module could not be loaded due to the following error: [Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              ]
                              For more information, run 'Import-Module Pscx'.
CommandName                 : Show-Tree
WasThrownFromThrowStatement : False
TargetSite                  : 
	Name                       : TryModuleAutoDiscovery
	DeclaringType              : System.Management.Automation.CommandDiscovery
	ReflectedType              : System.Management.Automation.CommandDiscovery
	MemberType                 : Method
	MetadataToken              : 100667239
	Module                     : System.Management.Automation.dll
	IsSecurityCritical         : True
	IsSecuritySafeCritical     : False
	IsSecurityTransparent      : False
	MethodHandle               : System.RuntimeMethodHandle
	Attributes                 : Private, Static, HideBySig
	CallingConvention          : Standard
	ReturnType                 : System.Management.Automation.CommandInfo
	ReturnTypeCustomAttributes : System.Management.Automation.CommandInfo
	ReturnParameter            : System.Management.Automation.CommandInfo
	IsCollectible              : False
	IsGenericMethod            : False
	IsGenericMethodDefinition  : False
	ContainsGenericParameters  : False
	MethodImplementationFlags  : IL
	IsAbstract                 : False
	IsConstructor              : False
	IsFinal                    : False
	IsHideBySig                : True
	IsSpecialName              : False
	IsStatic                   : True
	IsVirtual                  : False
	IsAssembly                 : False
	IsFamily                   : False
	IsFamilyAndAssembly        : False
	IsFamilyOrAssembly         : False
	IsPrivate                  : True
	IsPublic                   : False
	IsConstructedGenericMethod : False
	CustomAttributes           : {}
Message                     : The 'Show-Tree' command was found in the module 'Pscx', but the module could not be loaded due to the following error: [Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              ]
                              For more information, run 'Import-Module Pscx'.
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.Management.Automation.CmdletInvocationException: Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              
                               ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                              
                              File name: 'System.Messaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
                                 at System.Reflection.RuntimeAssembly.GetExportedTypes()
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
                                 at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
                                 at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String 
                              prefix, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& 
                              moduleFileFound)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags 
                              manifestProcessingFlags, Object privateData, Boolean& found, String shortModuleName, Nullable`1 manifestLanguageMode)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version 
                              requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
                                 at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& 
                              moduleFileFound)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
                                 at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T]()
                                 at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateEntryVisibility visibility, Exception& exception)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                                 at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                                 at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                                 at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                                 at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/24471#issuecomment-2429639476

This also appears to be exposed via `Get-Command -Name "${.exe}"`:

1.	~~~pwsh
	#!/usr/bin/env pwsh
	#Requires -PSEdition Core
	#Requires -Version 7.4

	(Get-Command -Name 'msinfo32.exe') | Format-List
	~~~

1.	<blockquote>

	~~~YAML
	Name            : msinfo32.exe
	CommandType     : Application
	Definition      : C:\WINDOWS\system32\msinfo32.exe
	Extension       : .exe
	Path            : C:\WINDOWS\system32\msinfo32.exe
	FileVersionInfo : File:             C:\WINDOWS\system32\msinfo32.exe
	                  InternalName:     msinfo.dll
	                  OriginalFilename: msinfo.dll.mui
	                  FileVersion:      10.0.26100.3323 (WinBuild.160101.0800)
	                  FileDescription:  System Information
	                  Product:          Microsoft® Windows® Operating System
	                  ProductVersion:   10.0.26100.3323
	                  Debug:            False
	                  Patched:          False
	                  PreRelease:       False
	                  PrivateBuild:     False
	                  SpecialBuild:     False
	                  Language:         English (United Kingdom)
	~~~

	</blockquote>
