### ISSUE TITLE
Microsoft.Management.Infrastructure.CimSession.Create Error

### ISSUE THREAD

**Issue by dongzhaosheng73** [PowerShell/PowerShell#24506]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

An exception occurred using CimSession.Create(null))

windows system name：Windows 10 Home China

ver：10.0.19045.3208

Microsoft.Management.Infrastructure ver 2.0.0

Microsoft.Management.Infrastructure.Runtime.Win ver 2.0.0

.net runtime ver 6.0

### Expected behavior

```console
using CimSession.Create(null)) not error
```

### Actual behavior

```console
using CimSession.Create(null)) error
```

### Error details

```console
An exception occurred using CimSession.Create(null))

Microsoft.Management.Infrastructure.CimException: CimSessionOptions instance is invalid: unsupported protocol or unrecognized custom option. Verify parameter passed to the CimSessionOptions(string) constructor and/or parameters passed to the CimSessionOptions.SetCustomOption(string, string) or CimSessionOptions.SetCustomOption(string, int) method.
at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
at Microsoft.Management.Infrastructure.CimSession.Create(String computerName)
```

### Environment data

```powershell
Microsoft.Management.Infrastructure.Runtime.Win ver 2.0.0
```

**Comment by dongzhaosheng73** [comment]
This issue still occurs when upgrading to 3.0.0

**Comment by iRon7** [comment]
It might be me but there aren't any **Steps to reproduce** in your issue description.
What is the relation with PowerShell or better: why is this a PowerShell issue?
And if it is, what is the version of PowerShell?

**Comment by dongzhaosheng73** [comment]
> 可能是我的问题，但您的问题描述中没有任何**可重现的步骤**。 与 PowerShell 有什么关系？或者更好的是：为什么这是 PowerShell 问题？ 如果是，PowerShell 的版本是什么？

https://github.com/PowerShell/MMI/issues     

According to the description of the MMI project, MMI is a dependency library of powershell, but this project has been set as read-only, so I can't raise a new issue, I don't know where to feedback this problem, I can only feedback it to powershell project, I'm sorry if the feedback is wrong. I hope you can provide a place to give correct feedback on this issue.

**Comment by iRon7** [comment]
It is still unclear how anyone could reproduce this error as the **details questioned in the bug report form** are missing.

But taking a close look at the error:

```PowerShell
using CimSession.Create(null))
```

Is ***not*** a PowerShell command but more probably a [`C#/.Net` language command](https://github.com/dotnet/csharplang).

Anyhow, if you really intend to resolve your issue, I would start with placing [a found question](https://stackoverflow.com/help/how-to-ask) on a community site as [StackOverflow](https://stackoverflow.com/) as it is unlikely that anybody would resolve this from a PowerShell standpoint.
