### ISSUE TITLE
7.5.0-preview.5: Crashin' @startup

### ISSUE THREAD

**Issue by emmedve1** [PowerShell/PowerShell#24550]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$ pwsh -nop -nol
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflectioemedve@lus-pw00njlz:~ $ pwsh -nop
PowerShell 7.5.0-preview.5
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef, System.String ByRef)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(System.Reflection.Assembly, System.Management.Automation.PSModuleInfo)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.Reflection.Assembly, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.String, Boolean ByRef, System.String, Boolean)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(System.Management.Automation.PSModuleInfo, Microsoft.PowerShell.Commands.ModuleSpecification, System.String, Boolean, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Object, Boolean ByRef, System.String, System.Nullable`1<System.Management.Automation.PSLanguageMode>)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(System.String, System.Management.Automation.ExternalScriptInfo, System.Collections.Hashtable, System.Collections.Hashtable, ManifestProcessingFlags, System.Version, System.Version, System.Version, System.Nullable`1<System.Guid>, ImportModuleOptions ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.String, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

### Expected behavior

```console
Start successfully
```

### Actual behavior

```console
$ pwsh -nop -nol
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflectioemedve@lus-pw00njlz:~ $ pwsh -nop
PowerShell 7.5.0-preview.5
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])
   at A.E.d(System.RuntimeMethodHandle[])
   at A.a.D(A, System.String, System.Type, System.Reflection.MethodBase, Boolean)
   at A.a.B(System.Reflection.Assembly, A)
   at A.a.a(System.Reflection.Assembly)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(System.Reflection.Assembly, System.String)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.String, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(System.Reflection.Assembly, System.String, System.Management.Automation.PSSnapInInfo, System.Management.Automation.PSModuleInfo, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateCmdletEntry> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<System.Management.Automation.Runspaces.SessionStateAliasEntry>> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.Management.Automation.Runspaces.SessionStateProviderEntry> ByRef, System.String ByRef)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(System.Reflection.Assembly, System.Management.Automation.PSModuleInfo)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.Reflection.Assembly, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.String, Boolean ByRef, System.String, Boolean)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(System.Management.Automation.PSModuleInfo, Microsoft.PowerShell.Commands.ModuleSpecification, System.String, Boolean, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Object, Boolean ByRef, System.String, System.Nullable`1<System.Management.Automation.PSLanguageMode>)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(System.String, System.Management.Automation.ExternalScriptInfo, System.Collections.Hashtable, System.Collections.Hashtable, ManifestProcessingFlags, System.Version, System.Version, System.Version, System.Nullable`1<System.Guid>, ImportModuleOptions ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.Management.Automation.SessionState, System.Object, ImportModuleOptions ByRef, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo, System.String, System.String, System.String, System.String, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, Boolean ByRef, Boolean ByRef)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

### Environment data

```powershell
$ pwsh -c '$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      7.5.0-preview.5
PSEdition                      Core
GitCommitId                    7.5.0-preview.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/user-attachments/assets/c3a57a0b-b4b8-4332-8226-9f94911133a8)

**Comment by emmedve1** [comment]
Duplicate of #24435

**Comment by powercode** [comment]
See https://github.com/PowerShell/PowerShell/issues/24435#issuecomment-2464295579

Sentinel One is hard at work.
