### ISSUE TITLE
IISAdministration module fails to load with `pwsh.exe -Command "Import-Module -Name IISAdministration"`

### ISSUE THREAD

**Issue by eg-bernardo** [PowerShell/PowerShell#24569]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Typing `Import-Module -Name IISAdministration -Verbose` in the interactive prompt works:
```
VERBOSE: Loading module from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\IISAdministration.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\iiscommands.types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\iiscommands.format.ps1xml'.
VERBOSE: Loading module from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\Microsoft.IIS.Powershell.Commands.dll'.
VERBOSE: Importing cmdlet 'Get-IISAppPool'.
VERBOSE: Importing cmdlet 'Start-IISCommitDelay'.
VERBOSE: Importing cmdlet 'Stop-IISCommitDelay'.
VERBOSE: Importing cmdlet 'Get-IISSite'.
VERBOSE: Importing cmdlet 'Remove-IISSite'.
VERBOSE: Importing cmdlet 'New-IISSite'.
VERBOSE: Importing cmdlet 'Stop-IISSite'.
VERBOSE: Importing cmdlet 'Start-IISSite'.
VERBOSE: Importing cmdlet 'Get-IISConfigSection'.
VERBOSE: Importing cmdlet 'Get-IISConfigCollection'.
VERBOSE: Importing cmdlet 'Get-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'New-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'Remove-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'Remove-IISConfigElement'.
VERBOSE: Importing cmdlet 'Clear-IISConfigCollection'.
VERBOSE: Importing cmdlet 'Get-IISConfigElement'.
VERBOSE: Importing cmdlet 'Get-IISConfigAttributeValue'.
VERBOSE: Importing cmdlet 'Remove-IISConfigAttribute'.
VERBOSE: Importing cmdlet 'Set-IISConfigAttributeValue'.
VERBOSE: Importing cmdlet 'Get-IISServerManager'.
VERBOSE: Importing cmdlet 'Reset-IISServerManager'.
VERBOSE: Importing cmdlet 'Get-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Set-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Set-IISCentralCertProviderCredential'.
VERBOSE: Importing cmdlet 'Clear-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Disable-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Enable-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Enable-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Disable-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Export-IISConfiguration'.
VERBOSE: Importing cmdlet 'Get-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Get-IISSiteBinding'.
VERBOSE: Importing cmdlet 'Remove-IISSiteBinding'.
VERBOSE: Importing cmdlet 'New-IISSiteBinding'.
VERBOSE: Loading module from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\iisadministration.psm1'.
VERBOSE: Exporting cmdlet 'Get-IISAppPool'.
VERBOSE: Exporting cmdlet 'Start-IISCommitDelay'.
VERBOSE: Exporting cmdlet 'Stop-IISCommitDelay'.
VERBOSE: Exporting cmdlet 'Get-IISSite'.
VERBOSE: Exporting cmdlet 'Remove-IISSite'.
VERBOSE: Exporting cmdlet 'New-IISSite'.
VERBOSE: Exporting cmdlet 'Stop-IISSite'.
VERBOSE: Exporting cmdlet 'Start-IISSite'.
VERBOSE: Exporting cmdlet 'Get-IISConfigSection'.
VERBOSE: Exporting cmdlet 'Get-IISConfigCollection'.
VERBOSE: Exporting cmdlet 'Get-IISConfigCollectionElement'.
VERBOSE: Exporting cmdlet 'New-IISConfigCollectionElement'.
VERBOSE: Exporting cmdlet 'Remove-IISConfigCollectionElement'.
VERBOSE: Exporting cmdlet 'Remove-IISConfigElement'.
VERBOSE: Exporting cmdlet 'Clear-IISConfigCollection'.
VERBOSE: Exporting cmdlet 'Get-IISConfigElement'.
VERBOSE: Exporting cmdlet 'Get-IISConfigAttributeValue'.
VERBOSE: Exporting cmdlet 'Remove-IISConfigAttribute'.
VERBOSE: Exporting cmdlet 'Set-IISConfigAttributeValue'.
VERBOSE: Exporting cmdlet 'Get-IISServerManager'.
VERBOSE: Exporting cmdlet 'Reset-IISServerManager'.
VERBOSE: Exporting cmdlet 'Get-IISCentralCertProvider'.
VERBOSE: Exporting cmdlet 'Set-IISCentralCertProvider'.
VERBOSE: Exporting cmdlet 'Set-IISCentralCertProviderCredential'.
VERBOSE: Exporting cmdlet 'Clear-IISCentralCertProvider'.
VERBOSE: Exporting cmdlet 'Disable-IISCentralCertProvider'.
VERBOSE: Exporting cmdlet 'Enable-IISCentralCertProvider'.
VERBOSE: Exporting cmdlet 'Enable-IISSharedConfig'.
VERBOSE: Exporting cmdlet 'Disable-IISSharedConfig'.
VERBOSE: Exporting cmdlet 'Export-IISConfiguration'.
VERBOSE: Exporting cmdlet 'Get-IISSharedConfig'.
VERBOSE: Exporting cmdlet 'Get-IISSiteBinding'.
VERBOSE: Exporting cmdlet 'Remove-IISSiteBinding'.
VERBOSE: Exporting cmdlet 'New-IISSiteBinding'.
VERBOSE: Importing cmdlet 'Clear-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Clear-IISConfigCollection'.
VERBOSE: Importing cmdlet 'Disable-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Disable-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Enable-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Enable-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Export-IISConfiguration'.
VERBOSE: Importing cmdlet 'Get-IISAppPool'.
VERBOSE: Importing cmdlet 'Get-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Get-IISConfigAttributeValue'.
VERBOSE: Importing cmdlet 'Get-IISConfigCollection'.
VERBOSE: Importing cmdlet 'Get-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'Get-IISConfigElement'.
VERBOSE: Importing cmdlet 'Get-IISConfigSection'.
VERBOSE: Importing cmdlet 'Get-IISServerManager'.
VERBOSE: Importing cmdlet 'Get-IISSharedConfig'.
VERBOSE: Importing cmdlet 'Get-IISSite'.
VERBOSE: Importing cmdlet 'Get-IISSiteBinding'.
VERBOSE: Importing cmdlet 'New-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'New-IISSite'.
VERBOSE: Importing cmdlet 'New-IISSiteBinding'.
VERBOSE: Importing cmdlet 'Remove-IISConfigAttribute'.
VERBOSE: Importing cmdlet 'Remove-IISConfigCollectionElement'.
VERBOSE: Importing cmdlet 'Remove-IISConfigElement'.
VERBOSE: Importing cmdlet 'Remove-IISSite'.
VERBOSE: Importing cmdlet 'Remove-IISSiteBinding'.
VERBOSE: Importing cmdlet 'Reset-IISServerManager'.
VERBOSE: Importing cmdlet 'Set-IISCentralCertProvider'.
VERBOSE: Importing cmdlet 'Set-IISCentralCertProviderCredential'.
VERBOSE: Importing cmdlet 'Set-IISConfigAttributeValue'.
VERBOSE: Importing cmdlet 'Start-IISCommitDelay'.
VERBOSE: Importing cmdlet 'Start-IISSite'.
VERBOSE: Importing cmdlet 'Stop-IISCommitDelay'.
VERBOSE: Importing cmdlet 'Stop-IISSite'.
```

but running `pwsh.exe -Command "Import-Module -Name IISAdministration -Verbose"` fails with:
```
VERBOSE: Loading module from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\IISAdministration.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\iiscommands.types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\iiscommands.format.ps1xml'.
VERBOSE: Loading module from path 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\IISAdministration\Microsoft.IIS.Powershell.Commands.dll'.
Import-Module: Assembly with same name is already loaded
```

I found a closed issue that may be related: #9498

### Expected behavior

```console
`pwsh.exe -Command "Import-Module -Name IISAdministration"` doesn't fail
```

### Actual behavior

```console
`pwsh.exe -Command "Import-Module -Name IISAdministration"` fails with `Import-Module: Assembly with same name is already loaded`
```

### Error details

```console
Exception             :
    Type       : System.IO.FileLoadException
    Message    : Assembly with same name is already loaded
    TargetSite :
        Name          : LoadBinaryModule
        DeclaringType : [Microsoft.PowerShell.Commands.ModuleCmdletBase]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source     : System.Management.Automation
    HResult    : -2146232799
    StackTrace :
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase,
SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean
searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Object privateData, Boolean& found, String shortModuleName,
Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData,
ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options,
Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData,
ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String
prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, IEnumerable`1 modulePath, String name, SessionState ss, ImportModuleOptions options,
ManifestProcessingFlags manifestProcessingFlags, PSModuleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Import-Module -Name IISAdministration -Verbose; Get-Error
    Statement        : Import-Module -Name IISAdministration -Verbose
    PositionMessage  : At line:1 char:1
                       + Import-Module -Name IISAdministration -Verbose; Get-Error
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
This repository only deals with issues related to PowerShell 7. For issues related to external modules shipped with Windows, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by kenlyon** [comment]
@eg-bernardo I just encountered this today for the first time. Very annoying!

@SeeminglyScience I accidentally found that if I included the `-NoExit` parameter, the `IISAdministration` module was loaded correctly. This would suggest there's some funny business with PowerShell itself.

My workaround for now is to add the `-UseWindowsPowerShell` parameter, but I'm not thrilled with this option. The whole reason I'm migrating a lot of code to PowerShell is to eliminate a dependency on .NET Framework. If I'm not mistaken, the `-UseWindowsPowerShell` parameter just puts me back in the .NET Framework land.

(BTW, my use case for spawning a separate pwsh instance is for elevation to admin account. Everything works great when run directly in PowerShell. It's just when started as a separate process that this happens.)

**Comment by kenlyon** [comment]
@SeeminglyScience The `-UseWindowsPowerShell` flag was still a problem. It got me past the `Import-Module` line, but the subsequent serialization meant that $Manager.Sites["Default Web Site"] would return a string rather than the expected `Microsoft.Web.Administration.Site` object.

I did find a workaround that seems to work:

```
[System.Reflection.Assembly]::LoadFrom("$env:systemroot\system32\inetsrv\Microsoft.Web.Administration.dll") | Out-Null
$Manager = New-Object Microsoft.Web.Administration.ServerManager
```

Hopefully this means I'm unstuck. Time will tell.

I do still think the fact that `-NoExit` affects the outcome points to this being a PowerShell 7 problem, not a problem with the module itself.
