### ISSUE TITLE
Get-ChildItem -Path c::\ -Directory Returns incorrect error message

### ISSUE THREAD

**Issue by CasperStekelenburg** [PowerShell/PowerShell#24579]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run "Get-ChildItem -Path c::\ -Directory" (yes, the typo is deliberate, this is what's causing the issue). PowerShell returns the error message "Get-ChildItem: A parameter cannot be found that matches parameter name 'Directory'." Obviously this is incorrect and when running the command from the prompt it is easier to spot, but when this is in a script, and you get this message you'll be very confused by this misleading message.

### Expected behavior

```console
A clear error message stating that the path does not exist should be enough.
```

### Actual behavior

```console
PS C:\> get-childItem -Path c::\ -Directory
Get-ChildItem: A parameter cannot be found that matches parameter name 'Directory'.
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : A parameter cannot be found that matches parameter name 'Directory'.
    ParameterName     : Directory
    ErrorId           : NamedParameterNotFound
    Line              : 1
    Offset            : 26
    CommandInvocation :
        MyCommand        : Get-ChildItem
        BoundParameters  :
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 1
            Keys     :
                              Path
            Values   :
                Length      : 1
                LongLength  : 1
                Rank        : 1
                SyncRoot    :
                                      c::\
                IsFixedSize : True
                Count       : 1
            SyncRoot :
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 1
                Keys     :
                                      Path
                Values   :
                    Length      : 1
                    LongLength  : 1
                    Rank        : 1
                    SyncRoot    :
                                              c::\
                    IsFixedSize : True
                    Count       : 1
                SyncRoot :
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 1
                    Keys     :
                                              Path
                    Values   :
                        Length      : 1
                        LongLength  : 1
                        Rank        : 1
                        SyncRoot    :
                                                      c::\
                        IsFixedSize : True
                        Count       : 1
                    SyncRoot :
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 1
                        Keys     :
                                                      Path
                        Values   :
                            Length      : 1
                            LongLength  : 1
                            Rank        : 1
                            SyncRoot    :
                                                              c::\
                            IsFixedSize : True
                            Count       : 1
                        SyncRoot :
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 1
                            Keys     :
                                                              Path
                            Values   :
                                Length      : 1
                                LongLength  : 1
                                Rank        : 1
                                SyncRoot    :
                                                                      c::\
                                IsFixedSize : True
                                Count       : 1
                            SyncRoot :
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 1
                                Keys     :
                                                                      Path
                                Values   :
                                    Length      : 1
                                    LongLength  : 1
                                    Rank        : 1
                                    SyncRoot    : …
                                    IsFixedSize : True
                                    Count       : 1
                                SyncRoot :
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 1
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 3
        Line             : get-childItem -Path c::\ -Directory
        Statement        : get-childItem -Path c::\ -Directory
        PositionMessage  : At line:1 char:1
                           + get-childItem -Path c::\ -Directory
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : get-childItem
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : A parameter cannot be found that matches parameter name 'Directory'.
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
        InvocationInfo        :
            MyCommand        : Get-ChildItem
            ScriptLineNumber : 1
            OffsetInLine     : 26
            HistoryId        : 3
            Line             : get-childItem -Path c::\ -Directory
            Statement        : -Directory
            PositionMessage  : At line:1 char:26
                               + get-childItem -Path c::\ -Directory
                               +                          ~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : VerifyArgumentsProcessed
        DeclaringType : [System.Management.Automation.CmdletParameterBinderController]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException o
riginalBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 a
rguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterIntern
al[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext func
Context)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
InvocationInfo        :
    MyCommand        : Get-ChildItem
    ScriptLineNumber : 1
    OffsetInLine     : 26
    HistoryId        : 3
    Line             : get-childItem -Path c::\ -Directory
    Statement        : -Directory
    PositionMessage  : At line:1 char:26
                       + get-childItem -Path c::\ -Directory
                       +                          ~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
* `Get-ChildItem` is a provider cmdlet, meaning that it works with _all_ PowerShell [providers](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Providers), not just the `FileSystem` provider.

* `-Directory` is a _dynamic_ parameter that is specific to the `FileSystem` provider (as is `-File`).

* Therefore, `Get-ChildItem` only recognizes `-Directory` if it can infer from the `-Path` / `-LiteralPath` argument that a `FileSystem` path is being targeted, and `c::\` is _not_ recognized as one, because what precedes the `::` is interpreted as the target _provider name_.

   * Seemingly, detection of an inapplicable parameter (`-Directory`) preempts the error message that you would get if you _omitted_ this parameter, namely that `c` isn't the name of an existing provider.
