### ISSUE TITLE
pwsh7 jump path will crash

### ISSUE THREAD

**Issue by watchingfun** [PowerShell/PowerShell#24656]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

First of all, this problem occurred after I upgraded win1123h2 to 24h2. In 23h2, pwsh was 7.x, but I forgot the specific version.

After upgrading the system, pwsh seemed to have been upgraded to the latest version. I tried to download the installation package from github release and reinstall it, and also tried to install it from window store, but the problem still exists.

Right click in the resource manager to open the terminal, 

or follow the steps below：

Start the window terminal, the default shell is pwsh7, enter `cd D:\Downloads` and press Enter, an error will be thrown;

But if you first enter `pwsh` and press Enter, 
then enter `cd D:\Downloads` and press Enter, an error will be thrown and the previously entered pwsh will be exited. 
At this time, the current pwsh will not throw an error when entering `cd D:\Downloads`;

### Expected behavior

```console
Jump to directory
```

### Actual behavior

```console
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.IO.Directory.GetFileSystemEntries(System.String, System.String, System.IO.EnumerationOptions)
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetCorrectCasedPath(System.String)
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(System.String, System.Management.Automation.ErrorRecord ByRef)
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(System.String)
   at System.Management.Automation.Provider.ItemCmdletProvider.ItemExists(System.String, System.Management.Automation.CmdletProviderContext)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(System.String, System.Management.Automation.CmdletProviderContext, Boolean, System.Management.Automation.Provider.CmdletProvider ByRef)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(System.String, Boolean, System.Management.Automation.CmdletProviderContext, System.Management.Automation.Provider.CmdletProvider ByRef)
   at System.Management.Automation.SessionStateInternal.SetLocation(System.String, System.Management.Automation.CmdletProviderContext, Boolean)
   at System.Management.Automation.Runspaces.InitialSessionState.SetSessionStateDrive(System.Management.Automation.ExecutionContext, Boolean)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(System.Management.Automation.ExecutionContext, Boolean, System.Management.Automation.PSModuleInfo, Boolean, Boolean, Boolean)
   at System.Management.Automation.AutomationEngine..ctor(System.Management.Automation.Host.PSHost, System.Management.Automation.Runspaces.InitialSessionState)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean)
   at Microsoft.PowerShell.ConsoleHost.OpenConsoleRunspace(System.Management.Automation.Runspaces.Runspace, Boolean)
   at Microsoft.PowerShell.ConsoleHost.DoCreateRunspace(Microsoft.PowerShell.RunspaceCreationEventArgs)
   at Microsoft.PowerShell.ConsoleHost.CreateRunspace(Microsoft.PowerShell.RunspaceCreationEventArgs)
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(System.String, Boolean, System.Collections.ObjectModel.Collection`1<System.Management.Automation.Runspaces.CommandParameter>, Boolean, System.String, System.String)
   at Microsoft.PowerShell.ConsoleHost.Run(Microsoft.PowerShell.CommandLineParameterParser, Boolean)
   at Microsoft.PowerShell.ConsoleHost.Start(System.String, System.String, Boolean)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
```

### Error details

```console
PowerShell 7.4.6
PS C:\Users\wenhu> cd D:\Downloads
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.IO.Directory.GetFileSystemEntries(System.String, System.String, System.IO.EnumerationOptions)
   at Microsoft.PowerShell.Commands.FileSystemProvider.GetCorrectCasedPath(System.String)
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(System.String, System.Management.Automation.ErrorRecord ByRef)
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(System.String)
   at System.Management.Automation.Provider.ItemCmdletProvider.ItemExists(System.String, System.Management.Automation.CmdletProviderContext)
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(System.String, Boolean, System.Management.Automation.PSDriveInfo, System.Management.Automation.Provider.ContainerCmdletProvider, System.Management.Automation.CmdletProviderContext)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(System.String, System.Management.Automation.CmdletProviderContext, Boolean, System.Management.Automation.Provider.CmdletProvider ByRef)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(System.String, Boolean, System.Management.Automation.CmdletProviderContext, System.Management.Automation.Provider.CmdletProvider ByRef)
   at System.Management.Automation.SessionStateInternal.SetLocation(System.String, System.Management.Automation.CmdletProviderContext, Boolean)
   at Microsoft.PowerShell.Commands.SetLocationCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

[已退出进程，代码为 3221225477 (0xc0000005)]
现在可以使用Ctrl+D关闭此终端，或按 Enter 重新启动。
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\wenhu> dotnet --info
.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.996cfe54
 MSBuild version:   17.11.9+a69bbaaf5

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\

已安装 .NET 工作负载:
配置为在安装新清单时使用 loose manifests。
没有要显示的已安装工作负载。

Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3

.NET SDKs installed:
  7.0.402 [C:\Program Files\dotnet\sdk]
  8.0.404 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Visuals

![image](https://github.com/user-attachments/assets/85556f1d-e67d-4292-af35-3308dde7ac10)
![image](https://github.com/user-attachments/assets/5328748c-3492-408b-a64d-297a527742f7)

**Comment by watchingfun** [comment]
I tried 7.5.0.rc1 and 7.2.24, both had this problem. The cause of this problem may not be pwsh. I also tried to upgrade .net8, but it still didn't work. But I'm not a professional, so I don't know how to solve this problem.

**Comment by SeeminglyScience** [comment]
I'm afraid there's not much we can do as it seems like this may have been a failed update in Windows. We can only suggest running the usual [windows repair tools](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e).
