### ISSUE TITLE
.Net method overload is ambiguous when invoked in one context but not in others

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#24702]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
Add-Type @'
using System;
public class a {}
public class b {}

public class c {
    public c (a a) {}
    public c (b b) {}
}
'@

function f { [c]::new([a]$null) }
f
. { [c]::new([a]$null) }
. (New-Module {$c = [c]::new([a]$null)}) {$c}
$c = [c]::new([a]$null); $c
```

### Expected behavior

```console
c
c
c
c
```

### Actual behavior

```console
c
c
c
MethodException: C:\test.ps1:16
Line |
  16 |  $c = [c]::new([a]$null); $c
     |  ~~~~~~~~~~~~~~~~~~~~~~~
     | Multiple ambiguous overloads found for "new" and the argument count: "1".
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.MethodException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Multiple ambiguous overloads found for "new" and the argument count: "1".
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : MethodCountCouldNotFindBest
        InvocationInfo        :
            ScriptLineNumber : 16
            OffsetInLine     : 1
            HistoryId        : 1
            ScriptName       : C:\test.ps1
            Line             : $c = [c]::new([a]$null); $c

            Statement        : $c = [c]::new([a]$null)
            PositionMessage  : At C:\test.ps1:16 char:1
                               + $c = [c]::new([a]$null); $c
                               + ~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\User1\Desktop\parts
            PSCommandPath    : C:\test.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\test.ps1: line 16
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Object)
    Message     : Multiple ambiguous overloads found for "new" and the argument count: "1".
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure, CallSite, Type, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodException
FullyQualifiedErrorId : MethodCountCouldNotFindBest
InvocationInfo        :
    ScriptLineNumber : 16
    OffsetInLine     : 1
    HistoryId        : 1
    ScriptName       : C:\test.ps1
    Line             : $c = [c]::new([a]$null); $c

    Statement        : $c = [c]::new([a]$null)
    PositionMessage  : At C:\test.ps1:16 char:1
                       + $c = [c]::new([a]$null); $c
                       + ~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\User1\Desktop\parts
    PSCommandPath    : C:\test.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\test.ps1: line 16
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Yeah it only passes the invocation constraint to `PSInvokeMemberBinder` if the type is resolvable *at compile time*.

That may not be feasible to fix as invocation constraints are part of the cache key (and dictionary keys must not mutate). Adding Engine WG

**Comment by alx9r** [comment]
>Yeah it only passes the invocation constraint to `PSInvokeMemberBinder` if the type is resolvable _at compile time_.

@SeeminglyScience Thank you for investigating.  I'm not familiar with this part of PowerShell.  Can you elaborate at bit on when this would manifest?  

I've been casting about for some other examples that fail, but each of these succeeds:

```PowerShell
Start-ThreadJob {$c = [c]::new([a]$null); $c} | Receive-Job -Wait
Invoke-Expression '$c = [c]::new([a]$null); $c'
[powershell]::Create().AddScript('$c = [c]::new([a]$null); $c').Invoke()
```

The only other example I have found that fails is this:

```PowerShell
Start-Job {
        param($typeDefinition)
        Add-Type @'
using System;
public class a {}
public class b {}

public class c {
    public c (a a) {}
    public c (b b) {}
}
'@
        $c = [c]::new([a]$null); $c
    } |
    Receive-Job -Wait
```

So I'm trying to work out what, exactly, is special about being about the two contexts that fail.

**Comment by SeeminglyScience** [comment]
It's not actually about the cast, it's about how it changes the method binder. If you have an explicit cast on a method argument it will tell the binder to disambiguate via the cast. This is called an "invocation constraint".

For this constraint to work, the type you are casting to must exist *at compile time* (e.g. once before first invocation). In this case, the type will not exist at compile time because the type `a` will not itself be compiled and present until midway through *invocation* time. If it doesn't exist at compile time then it's a simple dynamic cast.

To give you an idea using [`ScriptBlockDisassembler`](https://github.com/SeeminglyScience/ScriptBlockDisassembler), here's how that statement compiles when `a` is not resolvable:

```cs
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSVariableAssignmentBinder.Get())(
    Fake.Dynamic<Func<CallSite, Type, object, object>>(PSCreateInstanceBinder.Get(
        new CallInfo(1),
        PSMethodInvocationConstraints.Default,
        publicTypeOnly: true))
    (
        TypeOps.ResolveTypeName(Fake.Const<TypeName>("c"), Fake.Const<InternalScriptExtent>("[c]")),
        Fake.Dynamic<Func<CallSite, Type, object, object>>(PSDynamicConvertBinder.Get())(
            TypeOps.ResolveTypeName(Fake.Const<TypeName>("a"), Fake.Const<InternalScriptExtent>("a")),
            null)));
```

and if the `Add-Type` code is ran first, this is the result:

```cs
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSVariableAssignmentBinder.Get())(
    Fake.Dynamic<Func<CallSite, Type, a, object>>(PSCreateInstanceBinder.Get(
        new CallInfo(1),
        new PSMethodInvocationConstraints(
            methodTargetType: null,
            new Type[] { typeof(a) }),
            publicTypeOnly: true))
    (
        Fake.Const<Type>(typeof(c)),
        Fake.Dynamic<Func<CallSite, object, a>>(PSConvertBinder.Get(typeof(a)))(null)));
```

Not the most readable thing unfortunately but hopefully helpful in illustrating.

**Comment by SeeminglyScience** [comment]
Yeah it *feels* like a bug, but it wouldn't be inaccurate to call it an enhancement request. It's in a weird spot for sure
