### ISSUE TITLE
Why doesn't PowerShell use my system's language pack?

### ISSUE THREAD

**Issue by ChinaGodMan** [PowerShell/PowerShell#24722]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [ ] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

My system uses the `zh-CN` locale, why is the PowerShell prompt not set to Chinese? I found that other computers can display it in Chinese.

### Expected behavior

```console
Enter the wrong command,  it displays English
```

### Actual behavior

```console
PowerShell should display Chinese
```

### Error details

```console
Exception             : 
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Join" with "2" argument(s): "Value cannot be null. (Parameter 'values')"
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ArgumentNullException
        InvocationInfo        : 
            ScriptLineNumber : 5
            OffsetInLine     : 13
            HistoryId        : -1
            Line             : $formatString -f [string]::Join(', ', (Get-Command $lastError.TargetObject -UseFuzzyMatching -FuzzyMinimumDistance 1 | Select-Object -First 5 -Unique -ExpandProperty Name))
                               
            Statement        : $formatString -f [string]::Join(', ', (Get-Command $lastError.TargetObject -UseFuzzyMatching -FuzzyMinimumDistance 1 | Select-Object -First 5 -Unique -ExpandProperty Name))
            PositionMessage  : At line:5 char:13
                               +             $formatString -f [string]::Join(', ', (Get-Command $lastE …
                               +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
    TargetSite     : 
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Join" with "2" argument(s): "Value cannot be null. (Parameter 'values')"
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Type       : System.ArgumentNullException
        Message    : Value cannot be null. (Parameter 'values')
        ParamName  : values
        TargetSite : 
            Name          : ThrowArgumentNullException
            DeclaringType : [System.ThrowHelper]
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Source     : System.Private.CoreLib
        HResult    : -2147467261
        StackTrace : 
   at CallSite.Target(Closure, CallSite, Type, String, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeReturnAsIs(Object[] args)
   at System.Management.Automation.PSModuleInfo.Invoke(ScriptBlock sb, Object[] args)
   at System.Management.Automation.HostUtilities.GetSuggestionText(Object suggestion, Object[] suggestionArgs, PSModuleInfo invocationModule)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ArgumentNullException
InvocationInfo        : 
    ScriptLineNumber : 5
    OffsetInLine     : 13
    HistoryId        : -1
    Line             : $formatString -f [string]::Join(', ', (Get-Command $lastError.TargetObject -UseFuzzyMatching -FuzzyMinimumDistance 1 | Select-Object -First 5 -Unique -ExpandProperty Name))
                       
    Statement        : $formatString -f [string]::Join(', ', (Get-Command $lastError.TargetObject -UseFuzzyMatching -FuzzyMinimumDistance 1 | Select-Object -First 5 -Unique -ExpandProperty Name))
    PositionMessage  : At line:5 char:13
                       +             $formatString -f [string]::Join(', ', (Get-Command $lastE …
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
```

### Environment data

```powershell
PSVersion                      7.5.0-rc.1
PSEdition                      Core
GitCommitId                    7.5.0-rc.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![eee](https://github.com/user-attachments/assets/c6556a21-ecd9-4ecd-9dd6-789edf53be8d)

**Comment by mklement0** [comment]
Unlike _Windows PowerShell_ (the legacy, ships-with-Windows, Windows-only edition of PowerShell whose latest and _last_ version is 5.1), PowerShell (Core) 7 has not (yet?) been localized; see:

* #666
* #19860

**Comment by kilasuit** [comment]
As this is tracked in #19860 I'm marking this resolution-duplicate
