### ISSUE TITLE
PropertyNotFoundException should set TargetObject property to the target object

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#2569]
copied from MSFT:7266395

ISSUE: PropertyNotFoundException does not set the TargetObject property to the object for which the property could not be found.

IMPACT:
Debugging these exceptions is unnecessarily difficult because information about the object missing the property (such as its type or members) can't be logged via the exception record.

EXAMPLE:
When developing a test platform, a property that's expected to be on an XML node is missing.  The debug output produced by our platform is below.  I want to enhance this output to tell me the type and members of the object whose property access produced the exception, which would greatly reduce debug time.

```
Reading configuration file: D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\Tests\ntttcp\config.xml
Applying an action for edition ServerDatacenterCore...
Getting EditionConfig nodes for edition ServerDatacenterCore...
PS>TerminatingError(): "The property 'filename' cannot be found on this object. Verify that the property exists."
>> TerminatingError(): "The property 'filename' cannot be found on this object. Verify that the property exists."
>> TerminatingError(ApplyEditionConfigAction): "The property 'filename' cannot be found on this object. Verify that the property exists."
>> TerminatingError(ApplyEditionConfigAction): "The property 'filename' cannot be found on this object. Verify that the property exists."
********************************************************************
ERROR - Script will terminate.
--------------------------------------------------------------------
The property 'filename' cannot be found on this object. Verify that the property exists.
--------------------------------------------------------------------
Script stack trace:
at <ScriptBlock>, D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\harness\inc\configPerfBag.psm1: line 157
at IIf, D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\harness\inc\common.psm1: line 26
at ApplyEditionConfigAction, D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\harness\inc\configPerfBag.psm1: line 157
at ProcessConfigFile, D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\harness\bootTracer\1_CopyLocal.ps1: line 169
at Main, D:\IronMan\d52863f6-1eaf-40cb-91fd-809ce6f18573\harness\bootTracer\1_CopyLocal.ps1: line 56
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1
--------------------------------------------------------------------
Exception stack trace:
   at System.Management.Automation.EnumerableOps.PropertyGetter(PSGetMemberBinder binder, IEnumerator enumerator)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
--------------------------------------------------------------------
Inner exception stack trace:
<Null>
********************************************************************<!--
```

**Comment by no-identd** [comment]
Please reopen this is still an issue
