### ISSUE TITLE
Package build fails on macOS in fpm

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2741]
From https://travis-ci.org/PowerShell/PowerShell/jobs/177477612
```
WARNING: -Type was not specified, continuing with osxpkg!
WARNING: Suffix not given, building primary PowerShell package!
     roff: /Users/travis/build/PowerShell/PowerShell/assets/powershell.1
/gems/ruby-2.2.1/gems/bundler-1.13.2/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:76:in `contains_requirable_file?'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `block in find_in_unresolved'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_all'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_in_unresolved'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:74:in `require'
	from /Users/travis/.rvm/gems/ruby-2.2.1/gems/bundler-1.13.2/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.2.1/gems/bundler-1.13.2/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1370:in `add_self_to_load_path'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1283:in `activate'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/fpm:22:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Execution of { fpm $Arguments } failed with exit code 1
At /Users/travis/build/PowerShell/PowerShell/build.psm1:2128 char:13
```

I could not repro it locally on mac.

**Comment by iSazonov** [comment]
@vors Can we close the old issue?
