### ISSUE TITLE
powershell abort error on centos7

### ISSUE THREAD

**Issue by ezlee** [PowerShell/PowerShell#2839]
I installed powershell on centos7, but when I tried to run "Invoke-Command" either for localhost or remote computer, got the following error messges:
Does anyone know what's happening? 
thanks a lot!

PS /home/vagrant> Invoke-Command -ComputerName localhost -ScriptBlock { ifconfig } -credential vagrant

Windows PowerShell credential request
Enter your credentials.
Password for user vagrant: *******

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Clear()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.Finalize()
Aborted

Environment data
----------------

PS /home/vagrant> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by ezlee** [comment]
Remoting Support

Client-side remoting from Linux/macOS is not supported with the initial package. The work is being done in the psl-omi-provider repo.
