### ISSUE TITLE
Copy-Item throws Cannot validate remote path

### ISSUE THREAD

**Issue by stej** [PowerShell/PowerShell#3143]
Steps to reproduce
------------------
I created some new machines in Azure and enabled HTTPS remoting.

Then ran code like this:
```
$ips = '10.1.0.0', '10.1.0.1'
$credentials = New-Object Management.Automation.PSCredential ("user", (ConvertTo-SecureString "creds" -AsPlainText -Force))
$sessions = New-PsSession -SessionOption (New-PsSessionOption –SkipCACheck -SkipCNCheck) -computer $ips -credential $credentials -usessl

invoke-command -session $sessions { mkdir c:\temp }
$sessions | % { 
  Copy-Item $dir\tools-common.zip -dest c:\temp\ -tosession $_ -verbose
}
```

Expected behavior
-----------------
1) Should be working. No idea why it makes some remote path validation.
2) the XmlDocument exception is quite confusing

Actual behavior
---------------
```
Copy-Item : Cannot convert the "System.Xml.XmlDocument" value of type "System.Xml.XmlDocument" to type "System.Collec tions.Hashtable".
At line:2 char:3
+   Copy-Item $dir\tools-common.zip -dest c:\temp\ -tosession $_ -verbo ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Management.Automation.PowerShell:PowerShell) [Copy-Item], PS
   InvalidCastException
    + FullyQualifiedErrorId : CopyFileRemoteExecutionError,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot validate remote path 'c:\temp\'.
At line:2 char:3
+   Copy-Item $dir\tools-common.zip -dest c:\temp\ -tosession $_ -verbo ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (c:\temp\:String) [Copy-Item], InvalidOperationException
    + FullyQualifiedErrorId : FailedToValidateRemotePath,Microsoft.PowerShell.Commands.CopyItemCommand
```

Environment data
----------------

**Local**
```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Remote**
```
[45]: Invoke-Command -Session $sessions[0] { $PSVersionTable }

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   10.0.14393.693
PSVersion                      5.1.14393.693
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Desktop
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
SerializationVersion           1.1.0.1


[46]: Invoke-Command -Session $sessions[1] { $PSVersionTable }

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   10.0.14393.693
PSVersion                      5.1.14393.693
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Desktop
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

I tried to google this error, but with no luck. Found that it probably is thrown at this line https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/System.Management.Automation/engine/SessionStateContainer.cs#L5241

**Comment by iSazonov** [comment]
Thanks for reporting the issue!
Could you publish results of `error[0..1] | fl -force` ?

**Comment by stej** [comment]
I tried that yesterday and I was able to copy some files into the session. However, today again.. errors with copying. So this are the errors:

```
[30]: $error[0] | fl -force


writeErrorStream      : True
Exception             : System.InvalidOperationException: Cannot validate remote path 'c:\temp\'.
TargetObject          : c:\temp\
CategoryInfo          : InvalidOperation: (c:\temp\:String) [Copy-Item], InvalidOperationException
FullyQualifiedErrorId : FailedToValidateRemotePath,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
PSMessageDetails      :


[31]: $error[1] | fl -force


writeErrorStream      : True
Exception             : System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Xml.XmlDocume
                        nt" value of type "System.Xml.XmlDocument" to type "System.Collections.Hashtable".
                           at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
                           at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCo
                        llection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                           at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 i
                        nput, PSDataCollection`1 output, PSInvocationSettings settings)
                           at System.Management.Automation.PowerShell.Invoke[T]()
                           at Microsoft.PowerShell.Commands.SafeInvokeCommand.Invoke(PowerShell ps, FileSystemProvide
                        r fileSystemContext, CmdletProviderContext cmdletContext, Boolean shouldHaveOutput)
TargetObject          : System.Management.Automation.PowerShell
CategoryInfo          : InvalidOperation: (System.Management.Automation.PowerShell:PowerShell) [Copy-Item], PSInvalid
                        CastException
FullyQualifiedErrorId : CopyFileRemoteExecutionError,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
PSMessageDetails      :
```

When using the old `Resolve-Error` cmdlet:

```
[32]: Resolve-Error


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.InvalidOperationException: Cannot validate remote path 'c:\temp\'.
TargetObject          : c:\temp\
CategoryInfo          : InvalidOperation: (c:\temp\:String) [Copy-Item], InvalidOperationException
FullyQualifiedErrorId : FailedToValidateRemotePath,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}




MyCommand             : Copy-Item
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 2
OffsetInLine          : 3
HistoryId             : 28
ScriptName            :
Line                  :   Copy-Item $deploymentsDir\tools-common.zip -dest c:\temp\ -tosession $_ -verbose }
PositionMessage       : At line:2 char:3
                        +   Copy-Item $deploymentsDir\tools-common.zip -dest c:\temp\ -tosessio ...
                        +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          :
PSCommandPath         :
InvocationName        : Copy-Item
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :



00000000000000000000000000000000000000000000000000000000000000000000000000000000


Message        : Cannot validate remote path 'c:\temp\'.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233079



[33]: Resolve-Error -ErrorRecord $Error[1]


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Xml.XmlDocume
                        nt" value of type "System.Xml.XmlDocument" to type "System.Collections.Hashtable".
                           at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
                           at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCo
                        llection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                           at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 i
                        nput, PSDataCollection`1 output, PSInvocationSettings settings)
                           at System.Management.Automation.PowerShell.Invoke[T]()
                           at Microsoft.PowerShell.Commands.SafeInvokeCommand.Invoke(PowerShell ps, FileSystemProvide
                        r fileSystemContext, CmdletProviderContext cmdletContext, Boolean shouldHaveOutput)
TargetObject          : System.Management.Automation.PowerShell
CategoryInfo          : InvalidOperation: (System.Management.Automation.PowerShell:PowerShell) [Copy-Item], PSInvalid
                        CastException
FullyQualifiedErrorId : CopyFileRemoteExecutionError,Microsoft.PowerShell.Commands.CopyItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 2
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}




MyCommand             : Copy-Item
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 2
OffsetInLine          : 3
HistoryId             : 28
ScriptName            :
Line                  :   Copy-Item $deploymentsDir\tools-common.zip -dest c:\temp\ -tosession $_ -verbose }
PositionMessage       : At line:2 char:3
                        +   Copy-Item $deploymentsDir\tools-common.zip -dest c:\temp\ -tosessio ...
                        +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          :
PSCommandPath         :
InvocationName        : Copy-Item
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :



00000000000000000000000000000000000000000000000000000000000000000000000000000000


ErrorRecord    : Cannot convert the "System.Xml.XmlDocument" value of type "System.Xml.XmlDocument" to type "System.C
                 ollections.Hashtable".
Message        : Cannot convert the "System.Xml.XmlDocument" value of type "System.Xml.XmlDocument" to type "System.C
                 ollections.Hashtable".
Data           : {}
InnerException :
TargetSite     : Void EndInvoke()
StackTrace     :    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
                    at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollectio
                 n`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, P
                 SDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke[T]()
                    at Microsoft.PowerShell.Commands.SafeInvokeCommand.Invoke(PowerShell ps, FileSystemProvider fileS
                 ystemContext, CmdletProviderContext cmdletContext, Boolean shouldHaveOutput)
HelpLink       :
Source         : System.Management.Automation
HResult        : -2147467262
```

**Comment by iSazonov** [comment]
Oh, sorry. It would be interesting to see a call stack:
$error[0..1].Exception | fl -Force

**Comment by stej** [comment]
Content of `Resolve-Error` is this

```
[1]: gc Function:\Resolve-Error
param($ErrorRecord=$Error[0])

   $ErrorRecord | Format-List * -Force
   $ErrorRecord.InvocationInfo |Format-List *
   $Exception = $ErrorRecord.Exception
   for ($i = 0; $Exception; $i++, ($Exception = $Exception.InnerException))
   {   "$i" * 80
       $Exception |Format-List * -Force
   }
``` 
so the Exception is in fact in my previous response.

**Comment by stej** [comment]
It's here again

```
[9]: $error[0..1].Exception | fl -Force


Message        : Cannot validate remote path 'c:\temp\'.
Data           : {}
InnerException :
TargetSite     :
StackTrace     :
HelpLink       :
Source         :
HResult        : -2146233079

ErrorRecord    : Cannot convert the "System.Xml.XmlDocument" value of type "System.Xml.XmlDocument" to type "System.C
                 ollections.Hashtable".
Message        : Cannot convert the "System.Xml.XmlDocument" value of type "System.Xml.XmlDocument" to type "System.C
                 ollections.Hashtable".
Data           : {}
InnerException :
TargetSite     : Void EndInvoke()
StackTrace     :    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
                    at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollectio
                 n`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, P
                 SDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke[T]()
                    at Microsoft.PowerShell.Commands.SafeInvokeCommand.Invoke(PowerShell ps, FileSystemProvider fileS
                 ystemContext, CmdletProviderContext cmdletContext, Boolean shouldHaveOutput)
HelpLink       :
Source         : System.Management.Automation
HResult        : -2147467262
```

And it happened again after I created new VMs in Azure, setup windows remoting, opened session and ran the command (see the first post in this issue).

**Comment by stej** [comment]
!clrstack:

```
0:017> !clrstack
OS Thread Id: 0x2a00 (17)
        Child SP               IP Call Site
0000002bdef8e4a8 00007fff38036154 [HelperMethodFrame: 0000002bdef8e4a8] 
0000002bdef8e590 00007ffeed2c827c System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(System.Object, System.Type)
0000002bdef8e5d0 00007ffeed2c729b System.Management.Automation.LanguagePrimitives.ConvertNoConversion(System.Object, System.Type, Boolean, System.Management.Automation.PSObject, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
0000002bdef8e610 00007ffeec886005 System.Management.Automation.LanguagePrimitives+ConversionData`1[[System.__Canon, mscorlib]].Invoke(System.Object, System.Type, Boolean, System.Management.Automation.PSObject, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
0000002bdef8e650 00007ffeec8854c1 System.Management.Automation.LanguagePrimitives.ConvertTo(System.Object, System.Type, Boolean, System.IFormatProvider, System.Management.Automation.Runspaces.TypeTable)
0000002bdef8e6f0 00007ffeec91441b System.Management.Automation.Internal.PSDataCollectionStream`1[[System.__Canon, mscorlib]].Write(System.Object, Boolean)
0000002bdef8e790 00007ffeed4011e5 System.Management.Automation.Runspaces.Internal.ClientRemotePowerShell.HandleOutputReceived(System.Object, System.Management.Automation.RemoteDataEventArgs`1)
0000002bdef8e7f0 00007ffeec919cdf System.Management.Automation.ExtensionMethods.SafeInvoke[[System.__Canon, mscorlib]](System.EventHandler`1, System.Object, System.__Canon)
0000002bdef8e820 00007ffeec858c69 System.Management.Automation.Internal.ClientPowerShellDataStructureHandler.ProcessReceivedData(System.Management.Automation.Remoting.RemoteDataObject`1)
0000002bdef8e8c0 00007ffeec858a3c System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.DispatchMessageToPowerShell(System.Management.Automation.Remoting.RemoteDataObject`1)
0000002bdef8e910 00007ffeec93ec50 System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.ProcessNonSessionMessages(System.Management.Automation.Remoting.RemoteDataObject`1)
0000002bdef8e970 00007ffeec919cdf System.Management.Automation.ExtensionMethods.SafeInvoke[[System.__Canon, mscorlib]](System.EventHandler`1, System.Object, System.__Canon)
0000002bdef8e9a0 00007ffeec93d4fe System.Management.Automation.Remoting.BaseTransportManager.OnDataAvailableCallback(System.Management.Automation.Remoting.RemoteDataObject`1)
0000002bdef8ea20 00007ffeec93d100 System.Management.Automation.Remoting.Client.BaseClientTransportManager.ServicePendingCallbacks(System.Object)
0000002bdef8ead0 00007ffeed2b5c96 System.Management.Automation.Utils.WorkItemCallback(System.Object)
0000002bdef8eb40 00007fff18e7674e System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0000002bdef8ec10 00007fff18e765e7 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0000002bdef8ec40 00007fff18e804a0 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
0000002bdef8ec80 00007fff18e7fa10 System.Threading.ThreadPoolWorkQueue.Dispatch()
0000002bdef8f118 00007fff1a736a53 [DebuggerU2MCatchHandlerFrame: 0000002bdef8f118]
```

As PowerShell is compiled in release mode, there is no useful info when trying `!Clrstack -a` :/

**Comment by stej** [comment]
Workaround: close sessions and open new sessions.
But this is really ugly to have such a workaround in deployment scripts..

**Comment by iSazonov** [comment]
@stej Thanks for the additional information!
Please clarify - is the problem only with connection to a remote Azure VM? Did you try to connect to non-Azure?

**Comment by stej** [comment]
Haven't tried so far.. I don't have any suitable & available VM here right now..

**Comment by iSazonov** [comment]
We need to check with latest builds.

**Comment by jwikman** [comment]
I just stumbled upon this error myself.
I narrowed it down to that I get a casting error if I have a variable called $result in the remote session that I'm trying to copy from.

This piece of code was run in the remote session before I called copy-item
```
[string[]]$Result = @()
```
If I rename the variable to anything else, it works.

**Comment by yacuzo** [comment]
This is old now, but I just encountered it. In the same session I ran some chocolatey installs, which I guess defined the $result variable.

A workaround that is a bit simpler that restarting the session:
Run `Remove-Variable result` on the VM

PSVersion locally:  
```
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.18362.752                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.18362.752                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1
```

PSVersion on VM:
```
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17763.1007                                                                               
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.1007                                                                              
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1   
```
