### ISSUE TITLE
NetCore Invoke() throwing ArgumentNullException

### ISSUE THREAD

**Issue by Diastro** [PowerShell/PowerShell#3311]
Steps to reproduce
------------------
1. Running this on ```Win10```
2. Install PowerShell release ```1.0.0-alpha17```
3. Create a .NetCore1.1 project that references ```Microsoft.PowerShell.SDK``` version ```1.0.0-alpha17``` from the MyGet feed 
4. Add the following code to Program.cs

Am I missing anything?

```
using System;
using System.Management.Automation;

namespace SB
{
    class Program
    {
        static void Main(string[] args)
        {
            PowerShellAssemblyLoadContextInitializer.SetPowerShellAssemblyLoadContext("C:\\Program Files\\PowerShell\\6.0.0.17");

            using (PowerShell ps = PowerShell.Create())
            {
                ps.AddScript("Write-Host 'It works!'");
                var result = ps.Invoke()[0];
                Console.WriteLine(result.ToString());
            }
        }
    }
}
```

Expected behavior
-----------------
The process should output "It works!"

Actual behavior
---------------

The process crashes on an unhandled  reflection exception:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.TypeExtensions.GetMethod(Type type, String name, BindingFlags bindingAttr)
   at System.Management.Automation.Runspaces.Types_Ps1Xml.GetMethodInfo(Type type, String method)
   at System.Management.Automation.Runspaces.Types_Ps1Xml.<Get>d__2.MoveNext()
   at System.Management.Automation.Runspaces.TypeTable.ProcessTypeData(String filePath, ConcurrentBag`1 errors, IEnumerable`1 types)
   at System.Management.Automation.Runspaces.TypeTable.ProcessIsBuiltIn(String filePath, ConcurrentBag`1 errors, Boolean& failToLoadFile)
   at System.Management.Automation.Runspaces.TypeTable.Initialize(String snapinName, String fileToLoad, ConcurrentBag`1 errors, AuthorizationManager authorizationManager, PSHost host, Boolean& failToLoadFile)
   at System.Management.Automation.Runspaces.TypeTable.Update(Collection`1 psSnapinTypes, AuthorizationManager authorizationManager, PSHost host)
   at System.Management.Automation.Runspaces.RunspaceConfiguration.UpdateTypes()
   at System.Management.Automation.Runspaces.RunspaceConfiguration.Initialize(ExecutionContext executionContext)
   at System.Management.Automation.Runspaces.RunspaceConfiguration.Bind(ExecutionContext executionContext)
   at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, RunspaceConfiguration runspaceConfiguration, InitialSessionState iss)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.Open()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at SB.Program.Main(String[] args)
```

Environment data
----------------

```powershell
PS C:\Users\Me> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.17
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

@vors Any pointers?

**Comment by erwinwildenburg** [comment]
I get the same thing but I have the following changes:
```
    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="6.0.0-alpha17" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Management" Version="6.0.0-alpha17" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Utility" Version="6.0.0-alpha17" />
    <PackageReference Include="Microsoft.PowerShell.ConsoleHost" Version="6.0.0-alpha17" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="6.0.0-alpha17" />
    <PackageReference Include="System.Management.Automation" Version="6.0.0-alpha17" />
```

And the following line in Program.cs:
`PowerShellAssemblyLoadContextInitializer.SetPowerShellAssemblyLoadContext(AppContext.BaseDirectory);`

**Comment by Diastro** [comment]
@erwinwildenburg you're right, I should have mentionned that I also have the same installed. I also tried with the AppContext.BaseDirectory without any luck.
Do you remember how you got it to work like you did [here]?(https://github.com/PowerShell/PowerShell/issues/2291)

**Comment by erwinwildenburg** [comment]
@Diastro 

I managed to get my code running again :)

First of all you NEED the following dotnet core sdk: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.1-preview2-download.md
Any newer or older version crashes the application.

I uploaded sample code here that works: https://github.com/erwinwildenburg/PowerShellInDotNetCoreExample

**Comment by Diastro** [comment]
@erwinwildenburg Thanks for the reply! I'll test this out!
@PowerShellTeam How should this be treated? Seems to be like this is a pretty important scenario.

**Comment by Diastro** [comment]
So last night I debugged the powershell source code a little more and here's what I found : 
At some point the the file ```Types_Ps1Xml.cs``` (line 831) contains a call to ```ResolveType("Microsoft.PowerShell.Commands.Security.SecurityDescriptorCommandBase")```. For some reason it seems like this type cannot be resolve and the call returns null.
Then when ```Types_Ps1Xml.cs``` line 864 call ```GetMethodInfo( <previsouly_resolved_type>, "GetPath")``` is invoked, since the previously resolved type is null then the reflection error is thrown. Anyone on the Powershell team can comment on this? What could cause that type to resolve to null?

**Comment by erwinwildenburg** [comment]
@Diastro 
Were you able to do a projectreference to test that out?
I am unable to add a project reference to start working on this. Any hints to get it working?

**Comment by daxian-dbw** [comment]
> For some reason it seems like this type cannot be resolved and the call returns null.

@erwinwildenburg @Diastro this happens because you were using the API `SetPowerShellAssemblyLoadContext` in your code, which is not correct. When building your application with .NET CLI, you need to use `InitializeAndCallEntryMethod` to bootstrap your application.

Due to the lack of necessary APIs to manipulate assemblies in .NET Core, powershell needs to control assembly loading via our customized AssemblyLoadContext in order to do tasks like type resolution. So any applications that need to host powershell (using powershell APIs) needs to be bootstrapped from `PowerShellAssemblyLoadContextInitializer`.

`PowerShellAssemblyLoadContextInitializer` exposes 3 methods for this purpose: “SetPowerShellAssemblyLoadContext”, “InitializeAndCallEntryMethod” and “InitializeAndLoadEntryAssembly”. They are for different scenarios:
- For “SetPowerShellAssemblyLoadContext”, it’s to be used by a native host whose TPA (trusted platform assemblies) doesn’t include powershell assemblies, such as the in-box powershell.exe and other native CoreCLR host in NanoServer.
- For “InitializeAndCallEntryMethod” and “InitializeAndLoadEntryAssembly”, they are to be used with dotnet.exe where TPA list does include powershell assemblies. powershell core itself also uses it for bootstrapping (see code [here](https://github.com/PowerShell/PowerShell/blob/master/src/powershell/Program.cs#L27)). The only difference between these two methods is that the former calls into the entry point method, while the latter just load the real entry assembly and return it, so it’s up to the user to actually call into the entry point method using the returned assembly.

The attached "Sample.zip" is an example application that hosts powershell core (dotnet cli 1.0.0-preview3-003705 was used on my local machine). Hopefully this will help you understand the pattern.

[Sample.zip](https://github.com/PowerShell/PowerShell/files/848392/Sample.zip)

**Comment by daxian-dbw** [comment]
I will update our documentation to have a topic about hosting powershell core. It's an important scenario that we shouldn't have overlooked.

**Comment by Diastro** [comment]
Thanks @daxian-dbw
