### ISSUE TITLE
New-CimSession from within a PSJob created by a scheduled task

### ISSUE THREAD

**Issue by Glober777** [PowerShell/PowerShell#3538]
Hi!

I'm having a strange issue with one of my scripts, where the New-CimSession cmdlet throws out a strange error. Basically, the line that errors out looks as follows:
```Posh
$CimSession = New-CimSession -ComputerName $Target

# Value inside $Target defined above and confirmed to be correct
```
Here's the content of the generated Error Record:

```
Exception                     : Microsoft.Management.Infrastructure.CimException: An error -2147024882 was encountered
                                while subscribing to a Group Policy change notification.
                                   at Microsoft.Management.Infrastructure.CimException.ThrowIfMiResultFailure(MiResult result, String errorMessage, InstanceHandle errorData)
                                   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
                                   at Microsoft.Management.Infrastructure.CimCmdlets.CimSessionProxy.CreateSetSession(String computerName, CimSession cimSession, CimSessionOptions sessionOptions, CimOperationOptions operOptions, Boolean temporaryCimSession)
                                   at Microsoft.Management.Infrastructure.CimCmdlets.CimSessionProxy..ctor(String computerName, CimSessionOptions sessionOptions)
                                   at Microsoft.Management.Infrastructure.CimCmdlets.CimNewSession.NewCimSession(NewCim SessionCommand cmdlet, CimSessionOptions sessionOptions, CimCredential credential)
                                   at Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand.ProcessRecord()
                                   at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject                  :
FullyQualifiedErrorId         : Microsoft.Management.Infrastructure.CimException,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand
InvocationInfo                : System.Management.Automation.InvocationInfo
ErrorCategory_Category        : 0
ErrorCategory_Activity        : New-CimSession
ErrorCategory_Reason          : CimException
ErrorCategory_TargetName      :
ErrorCategory_TargetType      :
ErrorCategory_Message         : NotSpecified: (:) [New-CimSession], CimException
SerializeExtendedInfo         : False
ErrorDetails_ScriptStackTrace : <-Removed->
PSMessageDetails              :
```

Here's what's inside the Exception property of the abovementioned Error Record object:

```
NativeErrorCode : Failed
ErrorData       : MSFT_WmiError
MessageId       : HRESULT 0x803381d1
ErrorSource     :
ErrorType       : 0
StatusCode      : 1
Message         : An error -2147024882 was encountered while subscribing to a Group Policy change notification.
Data            : {}
InnerException  :
TargetSite      : Void ThrowIfMiResultFailure(Microsoft.Management.Infrastructure.Native.MiResult, System.String, Microsoft.Management.Infrastructure.Native.InstanceHandle)
StackTrace      :    at Microsoft.Management.Infrastructure.CimException.ThrowIfMiResultFailure(MiResult result, String errorMessage, InstanceHandle errorData)
                     at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
                     at Microsoft.Management.Infrastructure.CimCmdlets.CimSessionProxy.CreateSetSession(String computerName, CimSession cimSession, CimSessionOptions sessionOptions, CimOperationOptions operOptions, Boolean temporaryCimSession)
                     at Microsoft.Management.Infrastructure.CimCmdlets.CimSessionProxy..ctor(String computerName, CimSessionOptions sessionOptions)
                     at Microsoft.Management.Infrastructure.CimCmdlets.CimNewSession.NewCimSession(NewCimSessionCommand cmdlet, CimSessionOptions sessionOptions, CimCredential credential)
                     at Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand.ProcessRecord()
                     at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink        :
Source          : Microsoft.Management.Infrastructure
HResult         : -2146233088
```

There are no inner exceptions.

The error message seems to be misleading, as the script has nothing to do with Group Policies (unless this is something that was caused by some group policy setting). 

The issue occurs only if I run the script as a Scheduled Task and not if I run it interactively (running as the same RunAs account that's used to schedule it).

The script creates a new PSJob, inside which it is creating a new CimSession to a remote machine (which is available on the network) before running some queries. Unfortunately, I can't publish the whole script here.

The issue is observed on Windows Server 2008 R2 machine. PowerShell version is:
```
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.36373
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
We've tried disabling the antivirus software but that made no difference here.

Are there any suggestions on what may be causing this error?

Thanks!

**Comment by MaximoTrinidad** [comment]
@Glober777 

Although this is not truly PowerShell (v6-Alpha) Open Source issue, I may suggest to also post this incident at Windows PowerShell UserVoice site at: https://windowsserver.uservoice.com/forums/301869-powershell/category/148044-powershell-engine 

This way the Windows PowerShell team can assist in this issue.  

Now, because this is part of the PowerShell Core modules, I'm sure they are going to take a look at it too.

Thanks!

**Comment by iSazonov** [comment]
@Glober777 Can you test in latest Windows 10 versions and maybe with latest PowerShell Core?

**Comment by Glober777** [comment]
@MaximoTrinidad, thanks for the prompt reply. I've submitted the incident on UserVoice:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/18917938-new-cimsession-from-within-a-psjob-created-by-a-sc

**Comment by Glober777** [comment]
@iSazonov, I'll give it a try from a Windows Server 2016 box tomorrow and will tell whether it's going to be any different. I'm not 100% sure about trying through PowerShell Core, as some of the stuff that my script depends on may not be ready for that.

**Comment by MaximoTrinidad** [comment]
Awesome @Glober777 and @iSazonov !  It will help for sure.
:)

**Comment by SteveL-MSFT** [comment]
This looks like an issue in the WMIv2 client layer and not in PowerShell itself.  I would suggest trying to pass an explicit credential to `new-cimsession` instead of using the current security context.

**Comment by Glober777** [comment]
@SteveL-MSFT, specifying credentials explicitly didn't help. It fails with the same misleading error message.

@iSazonov, running in on a Windows Server 2016 machine as a scheduled task worked like a charm (even without explicit creds). Here's the PS details from that machine:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.953
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.953
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Are there any other suggestions rather than moving the script over to 2016 server? :)

**Comment by Glober777** [comment]
I could probably try upgrading WMF to 5.1 on that 2008R2 machine and see if that helps.

**Comment by iSazonov** [comment]
To make the update is good.
