### ISSUE TITLE
PowerShellGet crashes in Bash on Ubuntu on Windows (alpha 18)

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShell#3564]
Steps to reproduce
------------------
Open PowerShell Core as administrator on Windows 10 Creator Update
Install and open Bash on Ubuntu on Windows
Open PowerShell in Bash
Find-Module or Install-Module

Expected behavior
-----------------
Return search results from PSGallery or install named module

Actual behavior
---------------
```powershell
Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/proc/sys/net/ipv4/conf/eth0/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__2(String name, LinkLayerAddressInfo* llAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at CallSite.Target(Closure , CallSite , Type )
Aborted (core dumped)
```
Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
Confirmed!  

Windows 10 Pro Build 16170.rs_prerelease.170331_1532

PowerShell Core in Windows - is fine!
![posh_win_2017-04-14_12-27-56](https://cloud.githubusercontent.com/assets/19892435/25049127/27e68806-210e-11e7-9fe8-4f0602519445.jpg)

PowerShell Core in "Bash On Ubuntu On Windows" - fails!
![posh_wsl_2017-04-14_12-27-56](https://cloud.githubusercontent.com/assets/19892435/25049154/4db200ba-210e-11e7-99cc-9b6a88ab9963.jpg)

:)

**Comment by joeyaiello** [comment]
@SteveL-MSFT I'm also positive this is a WSL or CoreCLR issue

**Comment by SteveL-MSFT** [comment]
@joeyaiello I briefly looked at this, looks like corefx is making a P/Invoke call to a native api to enumerate network interfaces.  Not sure if WSL is expected to have that file path above or not or if the native api is making incorrect assumptions about the OS.  Agree it's WSL or CoreFx issue.

**Comment by joeyaiello** [comment]
This is fixed.
