### ISSUE TITLE
macOS 10.12.4 and Exchange Online Remote Powershell

### ISSUE THREAD

**Issue by SchmatzS** [PowerShell/PowerShell#3606]
Steps to reproduce
------------------
```powershell
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell -Credential $cred -Authentication Basic -AllowRedirection  
```

Expected behavior
-----------------
Get connected to Exchange Online Remote Powershell

Actual behavior
---------------
```
New-PSSession : Unable to load DLL 'libpsrpclient': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PSSession], DllNotFoundException
    + FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.NewPSSessionCommand
```

or
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Clear()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.Finalize()
```

Environment data
----------------

Fresh installation on my macOS without any previous versions. Do I miss anything beside that package?
powershell-6.0.0-alpha.18-osx.10.11-x64.pkg

```powershell
> $PSVersionTable

Name                           Value                                                                                                   
----                           -----                                                                                                   
PSVersion                      6.0.0-alpha                                                                                             
PSEdition                      Core                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                 
BuildVersion                   3.0.0.0                                                                                                 
GitCommitId                    v6.0.0-alpha.18                                                                                         
CLRVersion                                                                                                                             
WSManStackVersion              3.0                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                     
SerializationVersion           1.1.0.1   
```

**Comment by jas0nat0r** [comment]
I'm experiencing the same results with macOS 10.12.5 and 6.0.0-beta.  I'm using a slightly modified connections string but it essentially does the same thing.
## Steps to reproduce
```
Import-PSSession (New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell -Authentication Basic -AllowRedirection -Credential (Get-Credential))
```
## Environmental Data
```
Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      6.0.0-beta                                                                                             
PSEdition                      Core                                                                                                   
GitCommitId                    v6.0.0-beta.3                                                                                          
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELE...
Platform                       Unix                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1                                                                                                
WSManStackVersion              3.0                                                                                                    
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PS /Users/jthrasher> sion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0      
```

**Comment by MaximoTrinidad** [comment]
@SchmatzS 

Well, using PowerShell Core Beta 3, works in Windows OS. Then, it fails on my Ubuntu because I'm missing the PS Remoting components:

* Install OMI from https://github.com/Microsoft/omi/releases
* Install PSRP from https://github.com/PowerShell/psl-omi-provider/releases

There are some instruction in how to setup PS Remoting using Basic Authentication in the following thread: https://github.com/PowerShell/PowerShell/issues/3708#issuecomment-310281499 

This should clear the issue with Exchange Online Remote.

:)

**Comment by jas0nat0r** [comment]
@MaximoTrinidad 

I could be wrong but I reviewed the OMI and PSRP pieces you mentioned and I don't believe they would apply in this case.  My understanding of the OMI and PSRP components is they would enable inbound (server) remoting.  In this specific use case we're trying to remote, through New/Import-PSSession to a Windows environment (Exchange Online).

**Comment by SteveL-MSFT** [comment]
@jas0nat0r the psl-omi-provider handles both the inbound and outbound PSRP over WSMan on non-Windows

**Comment by vors** [comment]
@SteveL-MSFT My understanding is that outgoing PSRP session should not require any additional setup like installing omi, see https://github.com/PowerShell/psl-omi-provider/releases/tag/v1.0.0.18

**Comment by hoetz** [comment]
I actually managed to establish a connection but as soon as I start executing commands it's just sitting at the terminal and nothing happens, can't even cancel the command once it's running (i.e. get-mailbox etc. )
macOS Sierra 10.12

**Comment by tarigand** [comment]
similar issue as @hoetz here.  running a command just hangs the terminal.
