### ISSUE TITLE
Copy-Item to Remote session from a write protected medium throws exception

### ISSUE THREAD

**Issue by volviq** [PowerShell/PowerShell#3615]
Steps to reproduce
------------------
```
# Mount a CD ISO or insert a CD to drive.
# Go to the drives folder:
cd G:
# Establish a remote session (In my case a running Nano Server vm):
$ip=[ip address]
Set-Item WSMan:\localhost\Client\TrustedHosts $ip
$s = New-PSSession -ComputerName $ip -Credential ~\Administrator
#Copy over the file to the remote system:
Copy-Item -ToSession $s -Path .\Filename.example c:\
```

Expected behavior
-----------------
No Error messages/Exceptions are shown in case there is no valid reason.

Actual behavior
---------------

In case the file is within a mounted ISO, I get the following error message:
```
Copy-Item : The parameter is incorrect
At line:1 char:1
+ Copy-Item -ToSession $s -Path .\Filename.example c:\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.CopyItemCommand
```

The file is still successfully copied to the remote system.

Doing the same from a normal hard drive does not show the exception.

Environment data
----------------

Reproducible on Official installed Release:
```
Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.14393.953                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.14393.953                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1   
```

And latest Github Release:
```
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
CLRVersion
PSRemotingProtocolVersion      2.3
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
```

**Comment by iSazonov** [comment]
@PaulHigin Could you please comment the Issue?

**Comment by PaulHigin** [comment]
I don't know what is causing this error, but I agree that it shouldn't be reported if the copy succeeds.  It needs to be investigated.

**Comment by iSazonov** [comment]
@PaulHigin Thanks for your comment. It seemed to me that we had the same Issue.

**Comment by damienvanrobaeys** [comment]
I have exactly the same issue, same error reported but the file has been successfully copied

**Comment by iSazonov** [comment]
Can you repo if remote computer is localhost?

**Comment by damienvanrobaeys** [comment]
I tried to copy a file from my local computer to a remote. the file has been copied successully to the remote computer but still have the mentioned error.

**Comment by dumpvn** [comment]
I have same issue.

**Comment by nthanhcong0** [comment]
I also have the same issues when copy file to remote server via PSSession variable. File .zip was transferred successfully to remote server but still showing error
![image](https://user-images.githubusercontent.com/47897572/111578324-847dd900-87e6-11eb-98a2-71bc496ee26d.png)

**Comment by iSazonov** [comment]
(See #16310 for possible test with Mount-DiskImage -Access ReadOnly)

**Comment by tonybounty** [comment]
Same error, I try to copy file from network directory (VMware Share) to remote server : 
```ps
PS> Get-FileHash -Algorithm MD5 -Path "\\vmware-host\Shared Folders\ShareVm\psscript\INSTALL2\Certs\hello.txt"

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             5D41402ABC4B2A76B9719D911017C592                                       \\vmware-host\Shared Folders\ShareVm\psscript\INSTALL2\Certs\hello.txt

PS > Copy-Item "\\vmware-host\Shared Folders\ShareVm\psscript\INSTALL2\Certs\hello.txt" "c:\ded.dd" -ToSession $ss -Force
Copy-Item : The parameter is incorrect
At line:1 char:1
+ Copy-Item "\\vmware-host\Shared Folders\ShareVm\psscript\INSTALL2\Cer ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.CopyItemCommand
```
```ps
PS> $Error[0].Exception | select *
NativeErrorCode : 87 (0x57)
ErrorCode       : -2147467259 (0x80004005)
Message         : The parameter is incorrect
Data            : {}
InnerException  :
TargetSite      : System.Collections.Generic.List`1[System.Management.Automation.Internal.AlternateStreamData] GetStreams(System.String)
StackTrace      :    at System.Management.Automation.Internal.AlternateDataStreamUtilities.GetStreams(String path)
                     at Microsoft.PowerShell.Commands.FileSystemProvider.PerformCopyFileToRemoteSession(FileInfo file, String destinationPath, PowerShell ps)
                     at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean force, PowerShell ps)
                     at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemLocalOrToSession(String path, String destinationPath, Boolean recurse, Boolean
                  Force, PowerShell ps)
                     at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destinationPath, Boolean recurse)
                     at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstance, String path, String copyPath, Boolean recurse,
                  CmdletProviderContext context)
HelpLink        :
Source          : System.Management.Automation
HResult         : -2147467259
```

However, on my remote machine the file is well copied : 
```ps
PS C:\> Get-FileHash -Algorithm MD5 .\ded.dd

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             5D41402ABC4B2A76B9719D911017C592                                       C:\ded.dd
```

Local:
```ps
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

WindowsProductName                      WindowsVersion OsHardwareAbstractionLayer
------------------                      -------------- --------------------------
Windows Server 2019 Standard Evaluation 1809           10.0.17763.737
```

Remote:
```ps
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

WindowsProductName                      WindowsVersion OsHardwareAbstractionLayer
------------------                      -------------- --------------------------
Windows Server 2019 Standard Evaluation 1809           10.0.17763.737
```
