### ISSUE TITLE
Failed to compile on Archlinux from AUR

### ISSUE THREAD

**Issue by masterkorp** [PowerShell/PowerShell#3681]
Hello,

I am running ArchLinux (updated today) and trying to build Powershell version 6.0.0.alpha.17-2 from the [AUR](https://aur.archlinux.org/packages/powershell)

Steps to reproduce
------------------
Build powershell from the AUR

Expected behavior
-----------------
It should compile.

Actual behavior
---------------
```
/tmp/pkgbuild-1000/powershell/src/powershell

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytesOpenSsl(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
proot info: pid 5886: terminated with signal 6
proot info: pid 5888: terminated with signal 6
proot info: pid 5887: terminated with signal 6
proot info: pid 5885: terminated with signal 6
proot info: pid 5884: terminated with signal 6
proot info: pid 5883: terminated with signal 6
proot info: pid 5882: terminated with signal 6
/tmp/pkgbuild-1000/powershell/src/build.sh: line 3:  5882 Aborted                 (core dumped) dotnet restore
/tmp/pkgbuild-1000/powershell/src/powershell/src/ResGen /tmp/pkgbuild-1000/powershell/src/powershell

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytesOpenSsl(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
proot info: pid 5897: terminated with signal 6
proot info: pid 5896: terminated with signal 6
proot info: pid 5895: terminated with signal 6
proot info: pid 5894: terminated with signal 6
proot info: pid 5893: terminated with signal 6
proot info: pid 5892: terminated with signal 6
proot info: pid 5891: terminated with signal 6
/tmp/pkgbuild-1000/powershell/src/build.sh: line 6:  5891 Aborted                 (core dumped) dotnet run -c Linux
/tmp/pkgbuild-1000/powershell/src/powershell
/tmp/pkgbuild-1000/powershell/src/powershell/src/TypeCatalogParser /tmp/pkgbuild-1000/powershell/src/powershell

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytesOpenSsl(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
proot info: pid 5914: terminated with signal 6
proot info: pid 5913: terminated with signal 6
proot info: pid 5912: terminated with signal 6
proot info: pid 5911: terminated with signal 6
proot info: pid 5910: terminated with signal 6
proot info: pid 5909: terminated with signal 6
proot info: pid 5908: terminated with signal 6
/tmp/pkgbuild-1000/powershell/src/build.sh: line 10:  5908 Aborted                 (core dumped) dotnet run -c Linux
/tmp/pkgbuild-1000/powershell/src/powershell
/tmp/pkgbuild-1000/powershell/src/powershell/src/TypeCatalogGen /tmp/pkgbuild-1000/powershell/src/powershell

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytesOpenSsl(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
proot info: pid 5927: terminated with signal 6
proot info: pid 5926: terminated with signal 6
proot info: pid 5925: terminated with signal 6
proot info: pid 5924: terminated with signal 6
proot info: pid 5923: terminated with signal 6
proot info: pid 5922: terminated with signal 6
proot info: pid 5921: terminated with signal 6
/tmp/pkgbuild-1000/powershell/src/build.sh: line 14:  5921 Aborted                 (core dumped) dotnet run -c Linux ../Microsoft.PowerShell.CoreCLR.AssemblyLoadContext/CorePsTypeCatalog.cs powershell.inc
/tmp/pkgbuild-1000/powershell/src/powershell

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytesOpenSsl(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
proot info: pid 5941: terminated with signal 6
proot info: pid 5940: terminated with signal 6
proot info: pid 5939: terminated with signal 6
proot info: pid 5938: terminated with signal 6
proot info: pid 5937: terminated with signal 6
proot info: pid 5936: terminated with signal 6
proot info: pid 5935: terminated with signal 6
/tmp/pkgbuild-1000/powershell/src/build.sh: line 18:  5935 Aborted                 (core dumped) dotnet build -c Linux

```

Environment data
----------------
Not at that point yet.

Regards,
Alfredo Palhares

**Comment by iSazonov** [comment]
@kylesferrazza Could you please comment the Issue?

**Comment by kylesferrazza** [comment]
Dotnet's most recent AUR pkgbuild has been failing to build with clang 4. I also tried downgrading llvm and clang to 3.5 and it still failed. As soon as I'm able to build dotnet I can fix the Powershell PKGBUILDs.

**Comment by kylesferrazza** [comment]
There is a known issue: https://bbs.archlinux.org/viewtopic.php?id=225790

**Comment by iSazonov** [comment]
@kylesferrazza Thanks! PowerShell repo was moved to .Net Core 2.0. You can asks CoreFX/CoreCLR team to help - I believe they are interested in promoting .Net Core on Unix.
@masterkorp PowerShell team don't support officially ArchLinux so we close the Issue as external.
