### ISSUE TITLE
CredSSP.cs - Unhandled exception in DeleteUserDelegateSettings calling GPO.OpenLocalMachineGPO(1)

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#4784]
Steps to reproduce
------------------
running full CI/FEATURE tests on my server datacenter Selfhost OS.

Expected behavior
-----------------
All tests pass

Actual behavior
---------------
'Disable-WSManCredSSP works' test fails with unhandled COM exception. PowerShell process exits with -532462766 (0xe0434352 EXCEPTION_COMPLUS)

This repro's consistently interactively running Disable-WSManCredSSP -Role Client. The below callstack is reported, a delay occurs, and the process exits.

Unhandled Exception: System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.WSMan.Management.IGroupPolicyObject.OpenLocalMachineGPO(UInt32 dwFlags)
   at Microsoft.WSMan.Management.DisableWSManCredSSPCommand.DeleteUserDelegateSettings() in C:\git\Microsoft\powershell\src\Microsoft.WSMan.Management\CredSSP.cs:line 235
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Environment data
----------------
Server DataCenter 2016

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16357.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16357.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by SteveL-MSFT** [comment]
This isn't repro'ing on
```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.6
OS                             Microsoft Windows 10.0.16350
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
