### ISSUE TITLE
Powershell Crashes whilst using Login-AzureRmAccount Cmdlet on Windows 10

### ISSUE THREAD

**Issue by praveenc** [PowerShell/PowerShell#5018]
Steps to reproduce
------------------

```powershell
PS D:\Program Files\Powershell\6.0.0-beta.7>$Error.Clear()
PS D:\Program Files\Powershell\6.0.0-beta.7>$Error[0] | fl -Force *
PS D:\Program Files\Powershell\6.0.0-beta.7>Login-AzureRmAccount
Login-AzureRmAccount : Could not load type 'System.Drawing.Drawing2D.InterpolationMode' from assembly 'System.Drawing,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxx'.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

PS D:\Program Files\PowerShell\6.0.0-beta.7>
Unhandled Exception: System.TypeLoadException: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()
```

Expected behavior
-----------------

```none
Popup the Azure Login window
```

Actual behavior
---------------

```none
Powershell Crashes with popping up Window "powershell.exe has stopped working"
-> Close the Program
-> Debug the Program
```
![psbeta-loginazure-crash](https://user-images.githubusercontent.com/1090396/31231403-c129988a-a9b4-11e7-8a1f-5fe74ee430b7.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by praveenc** [comment]
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

**Comment by SteveL-MSFT** [comment]
The AzureRM module isn't CoreCLR compatible, you have to use the [AzureRM.NetCore](https://www.powershellgallery.com/packages/AzureRM.Netcore) module.  However, PowerShell shouldn't crash either.

**Comment by praveenc** [comment]
Thanks for the Pointer on AzureRM.NetCore module! 
This may be not the right place but any idea when does `Login-AzureRmAccount` in `AzureRM.NetCore` Module would support certificate based authentication?
I'd appreciate if you could point me to the right forum if this is not

**Comment by SteveL-MSFT** [comment]
@praveenc try https://github.com/Azure/azure-powershell

**Comment by anmenaga** [comment]
Regarding process termination...
I'd say this is expected behavior, not a bug.
Unfortunately in this case the unhandled exception is generated on CoreCLR's finalizer thread.
There is not much we can do about this exception from PS code.
Printing an error and process shutdown is default and normal in this kind of situations.

```
(b68.2ee0): CLR exception - code e0434352 (!!! second chance !!!)
CLR exception type: System.TypeLoadException
    "Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."
KERNELBASE!RaiseException+0x68:
00007ffc`11187788 488b8c24c0000000 mov     rcx,qword ptr [rsp+0C0h] ss:0000003b`a75fa8c0=00009bfd7519a47d
0:003> kn
 # Call Site
00 KERNELBASE!RaiseException+0x68 [d:\rs1\minkernel\kernelbase\xcpt.c @ 904] 
01 coreclr!__RethrowException+0x13 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 1274] 
02 coreclr!__CxxCallCatchBlock+0x151 [f:\dd\vctools\crt\vcruntime\src\eh\frame.cpp @ 1342] 
03 ntdll!RcFrameConsolidation+0x3 [d:\rs1\minkernel\ntos\rtl\amd64\capture.asm @ 596] 
04 coreclr!MethodDesc::MakeJitWorker+0x312 [e:\a\_work\308\s\src\vm\prestub.cpp @ 497] 
05 coreclr!MethodDesc::DoPrestub+0xaa9 [e:\a\_work\308\s\src\vm\prestub.cpp @ 1537] 
06 coreclr!PreStubWorker+0x3c1 [e:\a\_work\308\s\src\vm\prestub.cpp @ 1121] 
07 coreclr!ThePreStub+0x55 [E:\A\_work\308\s\src\vm\amd64\ThePreStubAMD64.asm @ 22] 
08 System_ComponentModel_Primitives!System.ComponentModel.Component.Finalize()+0x13 [E:\A\_work\774\s\corefx\src\System.ComponentModel.Primitives\src\System\ComponentModel\Component.cs @ 31] 
09 coreclr!FastCallFinalizeWorker+0x6 [E:\A\_work\308\s\src\vm\amd64\CallDescrWorkerAMD64.asm @ 27] 
0a coreclr!MethodTable::CallFinalizer+0x94 [e:\a\_work\308\s\src\vm\methodtable.cpp @ 3935] 
0b coreclr!CallFinalizer+0x48 [e:\a\_work\308\s\src\vm\finalizerthread.cpp @ 108] 
0c coreclr!FinalizerThread::DoOneFinalization+0x9c [e:\a\_work\308\s\src\vm\finalizerthread.cpp @ 187] 
0d coreclr!FinalizerThread::FinalizeAllObjects+0x89 [e:\a\_work\308\s\src\vm\finalizerthread.cpp @ 284] 
0e coreclr!FinalizerThread::FinalizerThreadWorker+0xca [e:\a\_work\308\s\src\vm\finalizerthread.cpp @ 642] 
0f coreclr!ManagedThreadBase_DispatchInner+0x43 [e:\a\_work\308\s\src\vm\threads.cpp @ 9204] 
10 coreclr!ManagedThreadBase_DispatchMiddle+0x82 [e:\a\_work\308\s\src\vm\threads.cpp @ 9253] 
11 coreclr!ManagedThreadBase_DispatchOuter+0xb4 [e:\a\_work\308\s\src\vm\threads.cpp @ 9492] 
12 coreclr!ManagedThreadBase_NoADTransition+0x41 [e:\a\_work\308\s\src\vm\threads.cpp @ 9575] 
13 coreclr!ManagedThreadBase::FinalizerBase+0x41 [e:\a\_work\308\s\src\vm\threads.cpp @ 9601] 
14 coreclr!FinalizerThread::FinalizerThreadStart+0x9c [e:\a\_work\308\s\src\vm\finalizerthread.cpp @ 774] 
15 coreclr!Thread::intermediateThreadProc+0x8b [e:\a\_work\308\s\src\vm\threads.cpp @ 2594] 
16 KERNEL32!BaseThreadInitThunk+0x14 [d:\rs1\base\win32\client\thread.c @ 64] 
17 ntdll!RtlUserThreadStart+0x21 [d:\rs1\minkernel\ntdll\rtlstrt.c @ 997] 
```

**Comment by praveenc** [comment]
Wow .. I can't believe that if a "type" is not found it would terminate and shutdown the whole process? 
Would this be the case for all unsupported types by CoreCLR then? 
If so, do you guys have a list of these unsupported types by CoreCLR somewhere?

**Comment by anmenaga** [comment]
1: Yes, but the exact exception type does not really matter: it can be TypeLoadException or InvalidArgumentException or any other exception type...
What matters is if the thread, on which exception is generated, has any handlers for it.
Powershell engine code has exception handlers on its threads; that is why most cmdlets/scripts don't shutdown PS process even if they generate unexpected exceptions (for example unexpected division by zero while doing some math in a cmdlet/script). But in this case the unhandled exception happens on .NET thread that PS has no control of, so the process is getting shut down.

2: Same as 1; it depends on where (on which thread) exception/error happens.

3: [CoreFX Github page](https://github.com/dotnet/corefx) points to this [.NET Core API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0).

**Comment by vkvikaskmr** [comment]
We have a module that is using Windows.Forms which does not seem to work in powershell 6.0.1. Is there an alternative?

**Comment by SteveL-MSFT** [comment]
@vkvikaskmr corefx doesn't support WinForms and I believe they have no plans to support it since it's not cross-platform compatible.  You can add your feedback to their issue here: https://github.com/dotnet/corefx/issues/21803
