### ISSUE TITLE
PowerShell Core AppImage breaks networking on Ubuntu, Debian, CentOS, and RedHat

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/PowerShell#5053]
### System Details

I've tested / reproduced this issue on all of the the following systems:

 - Operating System: Ubuntu 16.04.2 LTS
Kernel: Linux 4.10.0-35-generic

- Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64

- Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-3-amd64

- Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-514.16.1.el7.x86_64

PowerShell Core Version tested:

- PowerShell-6.0.0-beta.8

- PowerShell-6.0.0-beta.7

### Sample Output from Ubuntu 16.04
NOTE: Output is very similar on all other Distros mentioned above, with notable exception CentOS, which forcibly kicks me out of PowerShell if I use Invoke-WebRequest.

```
pdadmin@Ubuntu16VM:~/Downloads$ chmod a+x PowerShell-6.0.0-beta.8-x86_64.AppImage

pdadmin@Ubuntu16VM:~/Downloads$ sudo ./PowerShell-6.0.0-beta.8-x86_64.AppImage
[sudo] password for pdadmin:
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_3ViStr/usr/bin/powershell.wrapper from within an AppImage.
PowerShell v6.0.0-beta.8
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/pdadmin/Downloads> iwr google.com
iwr : Couldn't resolve host name
At line:1 char:1
+ iwr google.com
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Invo
   keWebRequestCommand

PS /home/pdadmin/Downloads> ping google.com
ping: unknown host google.com

PS /home/pdadmin/Downloads> exit

pdadmin@Ubuntu16VM:~/Downloads$ ping google.com
PING google.com (172.217.8.14) 56(84) bytes of data.
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=1 ttl=56 time=12.2 ms
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=2 ttl=56 time=15.6 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 12.255/13.971/15.687/1.716 ms

pdadmin@Ubuntu16VM:~/Downloads$ ./PowerShell-6.0.0-beta.8-x86_64.AppImage
PowerShell v6.0.0-beta.8
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/pdadmin/Downloads> iwr google.com
iwr : Couldn't resolve host name
At line:1 char:1
+ iwr google.com
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Invo
   keWebRequestCommand

PS /home/pdadmin/Downloads> ping google.com
PING google.com (172.217.8.14) 56(84) bytes of data.
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=1 ttl=56 time=7.15 ms
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=2 ttl=56 time=10.4 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 7.151/8.798/10.446/1.650 ms

PS /home/pdadmin/Downloads> exit
```

### Issue Description

Networking breaks when using PowerShell Core AppImage. Not sure how it's broken exactly, but I can't resolve anything with PowerShell cmdlets or with Linux utilities like ping or curl.

### Attached Logs

Reproduced by and additional testing done by @markekraus 
(see: https://www.reddit.com/r/PowerShell/comments/74u837/sanity_check_powershell_core_appimage_breaks/)

(FYI, I'm /u/fourierswager on reddit)

**Comment by markekraus** [comment]
I was able to repro this in both `PowerShell-6.0.0-beta.7-x86_64.AppImage` and `PowerShell-6.0.0-beta.8-x86_64.AppImage`

There appears to be an issue with DNS resolution in some instances. assuming the appimage is run as a normal user, ping works, but curl and nslookup do not. ping is unable to resolve if you run appimage as sudo. 

The impact is that the web cmdlets are also unable to resolve hostnames (as it relies on curl) and thus error on any call. I can also repro this with the underlying .NET calls

Steps to reproduce
------------------

```bash
./PowerShell-6.0.0-beta.8-x86_64.AppImage
```
```powershell
nslookup google.com

(Invoke-WebRequest http://google.com).StatusCode

curl google.com

$handler = [System.Net.Http.HttpClientHandler]::new()
$HttpClient = [System.Net.Http.HttpClient]::New($handler)
$HttpClient.GetAsync("http://www.contoso.com/").GetAwaiter().GetResult().StatusCode
```

Expected behavior
-----------------

```none
Server:         209.18.47.61
Address:        209.18.47.61#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.9.142


200

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

OK
```

Actual behavior
---------------

```none
/usr/bin/nslookup: /tmp/.mount_81bJrR/usr/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.55)

Invoke-WebRequest : Couldn't resolve host name
At line:1 char:2
+ (Invoke-WebRequest http://google.com).StatusCode
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

curl: (6) Could not resolve host: google.com

Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
At line:1 char:1
+ $HttpClient.GetAsync("http://www.contoso.com/").GetAwaiter().GetResul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : HttpRequestException
```

more details on the last error:

```none
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred
                        while sending the request." ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. --->
                        System.Net.Http.CurlException: Couldn't resolve host name
                           at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
                           at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
                           --- End of inner exception stack trace ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                           at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow,
                        String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : HttpRequestException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Environment data
----------------

```none
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@probonopd can you help with this?

**Comment by pldmgg** [comment]
Guys sorry, I didn't realize my original erroneous issue post over at vscode-powershell was moved here as #5054, (I opened up #5053 right before #5054 was created via the move).  So they're the same thing.

I'm just gonna put the keyboard down for a while :(

Let me know if I can help

**Comment by probonopd** [comment]
`/usr/bin/nslookup: /tmp/.mount_81bJrR/usr/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.55)` means that `/usr/bin/nslookup` on your system is invoked, and it loads `/tmp/.mount_81bJrR/usr/lib/libstdc++.so.6` from within the AppImage since `LD_LIBRARY_PATH` is set. But that version does not have CXXABI version 1.3.8 that your local `/usr/bin/nslookup` needs.

Multiple possible solutions, roughly in my order of preference:
* Remove the need to bundle `libstdc++.so.6` inside the AppImage (if it ever existed - not sure our first AppImage builds had this bundled), need to check
* Do away with `LD_LIBRARY_PATH` and instead set an rpath relative to `$ORIGIN`, e.g., using https://nixos.org/patchelf.html (let me know if I should elaborate). This way, what is inside the AppImage can use the bundled `libstdc++.so.6` while what is outside can use the host `libstdc++.so.6`. Also see https://gms.tf/ld_library_path-considered-harmful.html#use-origin
* Use [appimage-exec-wrapper](https://github.com/AppImage/AppImageKit/issues/396)

**Comment by SteveL-MSFT** [comment]
@probonopd can you submit a PR to fix based on your best judgement?

**Comment by probonopd** [comment]
Just to verify the hypothesis, can someone who has this issue please run, inside PowerShell:

```
(the command that fails)
# Should print an error

unset LD_LIBRARY_PATH
(the command that fails)
# Should NOT give an error
```

Can you confirm?

**Comment by markekraus** [comment]
@probonopd unset doesn't seem to work,  (` The term 'unset' is not recognized as the name of a cmdlet`...) but using

```powershell
[Environment]::SetEnvironmentVariable('LD_LIBRARY_PATH',$null)
```

successfully removes `LD_LIBRARY_PATH`. However, it has no effect on the commands. ☹️

**Comment by probonopd** [comment]
> However, it has no effect on the commands

That is strage... are the commands still trying to load libraries from within the AppImage? (Why?)

**Comment by markekraus** [comment]
Hmm I take that back (helps if I run all the commands from the repro). After removing `LD_LIBRARY_PATH`, the native binaries (`curl` and `nslookup`) work, but `Invoke-WebRequest`, `Invoke-RestMethod` , and `System.Net.Http.HttpClient` all still fail. That's odd because `HttpClient` is basically a wrapper for `libcurl `.

**Comment by probonopd** [comment]
So PowerShell loads additional libraries with something loke `dlopen()` when certain commands are invoked? Do we know which ones, and when?

**Comment by markekraus** [comment]
Well, CoreFX does. `Invoke-WebRequest` is a wrapper for CoreFX's `System.Net.Http.HttpClient`. The PowerShell commandlets are not directly calling libcurl, but the underlying CoreFX is.

This is what the stack looks like when calling `Invoke-WebRequest http://httpbin.org/get/` inside the AppImage

```none
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't resolve host name
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean stripAuthorization)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

**Comment by pldmgg** [comment]
I just found something interesting (result is the same running the AppImage with or without sudo):

    PS /home/pdadmin/Downloads> nslookup google.com
    /usr/bin/nslookup: /tmp/.mount_qo4lVC/usr/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicui18n.so.57)
    /usr/bin/nslookup: /tmp/.mount_qo4lVC/usr/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.57)
    
    PS /home/pdadmin/Downloads> sudo nslookup google.com
    Server:         192.168.2.18
    Address:        192.168.2.18#53

    Non-authoritative answer:
    Name:   google.com
    Address: 172.217.8.14

    PS /home/pdadmin/Downloads>

So, from within the PowerShell AppImage, if you "sudo nslookup", then it can find /tmp/.mount_qo4lVC/usr/lib/libstdc++.so.6 .

Could this be a permissions thing? Everything in the AppImage mount is root:root ... but AppImages are still a bit of a mystery to me.

**Comment by probonopd** [comment]
Not familiar with the inner workings of PowerShell, but could it be that invoking `sudo nslookup google.com` from within NS runs `nslookup` without the environment variables that were exported by the script in the AppImage that launches PowerShell?

**Comment by markekraus** [comment]
@probonopd That's exactly why sudo works. `sudo strace -v nslookup google.com` is lacking `LD_LIBRARY_PATH` environment variabe, but `strace -v nslookup google.com`  it is present.

**Comment by probonopd** [comment]
Is there a way to launch PowerShell with a script that runs initially after PowerScript being launched? And is there a way in PowerShell to unset an environment variable for everything that gets launched from within PowerShell?

If not, then we need to do either of the solutions from https://github.com/PowerShell/PowerShell/issues/5053#issuecomment-335271038 but I currently don't have the time to do it and would appreciate if someone could look into this.

**Comment by markekraus** [comment]
@probonopd There are 2 seperate problems here. 

1. The `LD_LIBRARY_PATH` causing native binaries to use the AppImage `libstdc++.so.`. 
2. Even with `LD_LIBRARY_PATH` out of the picture, `Invoke-WebRequest` and `Invoke-RestMethod` are still unable to resolve hostnames.

I'm guessing 1 is somewhat easy to deal with by having AppImage not set ``LD_LIBRARY_PATH` or remove ``LD_LIBRARY_PATH`. I have no clue how the AppImage is even packaged and my attempts to create the AppImage manual constantly fail, so I could be wrong on how easy that is.

For 2, on the other hand, we haven't discovered the root cause of.

**Comment by pldmgg** [comment]
Cool, I'm with you guys now on the LD_LIBRARY_PATH issue:

PS /home/pdadmin/Downloads> $env:LD_LIBRARY_PATH = $null
    PS /home/pdadmin/Downloads> nslookup google.com
    Server:         192.168.2.18
    Address:        192.168.2.18#53

    Non-authoritative answer:
    Name:   google.com
    Address: 172.217.8.14

So, the environment variable is being set by /tmp/.mount_qo4lVC/AppRun -

    #!/bin/bash
    HERE=$(dirname $(readlink -f "${0}"))
    export PATH="${HERE}/usr/bin/":$PATH
    export LD_LIBRARY_PATH="${HERE}/usr/lib/":$LD_LIBRARY_PATH
    exec "${HERE}/usr/bin/powershell.wrapper" "$@"

And that seems fine I guess - 

    pdadmin@Debian9:/tmp/.mount_qo4lVC$ ls -la usr/lib/libstdc++.so.6
    lrwxrwxrwx 1 root root 19 Apr  5  2014 usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.19
    pdadmin@Debian9:/tmp/.mount_qo4lVC$ ls -la usr/lib/libstdc++.so.6.0.19
    -rw-r--r-- 1 root root 979056 Apr  5  2014 usr/lib/libstdc++.so.6.0.19
    pdadmin@Debian9:/tmp/.mount_qo4lVC$

Why wouldn't the native binaries be okay with using the AppImage's libstdc++.so.6?

For the cmdlets, I guess I have to look at System.Net.Http.dll.

**Comment by markekraus** [comment]
@pldmgg it's not so much `libstdc++.so.6` as it is the included `libstdc++.so.6`'s dependency on `CXXABI_1.3.8` which is not included in the AppImage. The missing lib is what causes the native binaries to fail.

Completely different issue with `irm` and `iwr`.

**Comment by pldmgg** [comment]
@markekraus Roger that on the `CXXABI_1.3.8` not being in the AppImage...So I guess the natural question does anything inherently PowerShell-related need that environment variable? Is it just there to attempt to replicate how the user has things set in bash? If the latter, maybe we should just have the AppRun bash script pull in environment variables from the user's bash environment

For `irm` and `iwr`, is System.Net.Http.dll the thing to look at?

**Comment by markekraus** [comment]
@pldmgg heh.. it's hard to say.. an astonishing amount of tests already fail in the AppImage., but I'm guessing `Start-PSPester` was never really designed to work with it. But, you could run the tests, record the pass/fail/skip/pending numbers, close out and reopen appiage, remove the env var and then run the tests again and see if they improve or get worse.

> For irm and iwr, is System.Net.Http.dll

yea... pretty much. that and the libcurl libraries in the AppImage.

**Comment by markekraus** [comment]
@pldmgg I don't see any difference in test results without the environment variable set so it's possible removing it will have no affect on PowerShell.

**Comment by SteveL-MSFT** [comment]
If we can't get some help to get this working, we may have to consider not having appimage support for 6.0.0 release and revisiting this for 6.1.0.

**Comment by probonopd** [comment]
`AppRun` currently does:

```
export LD_LIBRARY_PATH="${HERE}/usr/lib/":$LD_LIBRARY_PATH
```

This results in the binaries contained within the AppImage to use the bundled libraries, which is intended. But it also has the unintended side effect that whenever binaries are launched from PowerShell that are not inside the AppImage but on the host system, then they inherit the `LD_LIBRARY_PATH`, which makes them also load the libraries from the AppImage. This is undesired and may be causing the issue described.

There are at least two options to solve this:
1. Do not export `LD_LIBRARY_PATH` but instead modify the `rpath` using [patchelf](https://nixos.org/patchelf.html)
2. Use something like [appimage-exec-wrapper](https://cgit.kde.org/scratch/brauch/appimage-exec-wrapper.git/) 

Detailed version from https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#environment-variables:

By default, AppRun sets some variables such as `LD_LIBRARY_PATH` before executing the payload application. While this is sufficient in most cases, it may lead to issues if the payload application launches other applications that reside in the base system, that is, outside of the AppImage. KDevelop is an example of such an application. In these cases, the [appimage-exec-wrapper](https://cgit.kde.org/scratch/brauch/appimage-exec-wrapper.git/) library can be used together with the AppImage distribution mechanism. Place the library somewhere in your AppImage and point `LD_PRELOAD` to it before launching your application. Whenever your application invokes a child process through `execv()` or `execve()`, this wrapper will intercept the call and see if the child process lies outside of the bundled appdir. If it does, the wrapper will attempt to undo any changes done to environment variables before launching the process, since you probably did not intend to launch it with e.g. the `LD_LIBRARY_PATH` you previously set for your application. [linuxdeployqt](https://github.com/probonopd/linuxdeployqt), on the other hand, does entirely without setting `LD_LIBRARY_PATH` by [setting the RPATH in libraries and executables relative to $ORIGIN](https://nixos.org/patchelf.html).

**Comment by SteveL-MSFT** [comment]
Unfortunately, this isn't something we'll be able to look at for RC2 which means it won't be in for 6.0.0.

**Comment by lavahot** [comment]
Can confirm. This exists in the latest docker image as well. I hope you guys get this fixed soon.
