### ISSUE TITLE
PowerShell Core AppImage breaks networking on Ubuntu, Debian, CentOS, and RedHat

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShell#5054]
_From @pldmgg on October 7, 2017 14:5_

### System Details

I've tested / reproduced this issue on all of the the following systems:

 - Operating System: Ubuntu 16.04.2 LTS
Kernel: Linux 4.10.0-35-generic

- Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64

- Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-3-amd64

- Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-514.16.1.el7.x86_64

PowerShell Core Version tested:

- PowerShell-6.0.0-beta.8

- PowerShell-6.0.0-beta.7

### Sample Output from Ubuntu 16.04
NOTE: Output is very similar on all other Distros mentioned above, with notable exception CentOS, which forcibly kicks me out of PowerShell if I use Invoke-WebRequest.

```
pdadmin@Ubuntu16VM:~/Downloads$ chmod a+x PowerShell-6.0.0-beta.8-x86_64.AppImage

pdadmin@Ubuntu16VM:~/Downloads$ sudo ./PowerShell-6.0.0-beta.8-x86_64.AppImage
[sudo] password for pdadmin:
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_3ViStr/usr/bin/powershell.wrapper from within an AppImage.
PowerShell v6.0.0-beta.8
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/pdadmin/Downloads> iwr google.com
iwr : Couldn't resolve host name
At line:1 char:1
+ iwr google.com
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Invo
   keWebRequestCommand

PS /home/pdadmin/Downloads> ping google.com
ping: unknown host google.com

PS /home/pdadmin/Downloads> exit

pdadmin@Ubuntu16VM:~/Downloads$ ping google.com
PING google.com (172.217.8.14) 56(84) bytes of data.
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=1 ttl=56 time=12.2 ms
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=2 ttl=56 time=15.6 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 12.255/13.971/15.687/1.716 ms

pdadmin@Ubuntu16VM:~/Downloads$ ./PowerShell-6.0.0-beta.8-x86_64.AppImage
PowerShell v6.0.0-beta.8
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/pdadmin/Downloads> iwr google.com
iwr : Couldn't resolve host name
At line:1 char:1
+ iwr google.com
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Invo
   keWebRequestCommand

PS /home/pdadmin/Downloads> ping google.com
PING google.com (172.217.8.14) 56(84) bytes of data.
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=1 ttl=56 time=7.15 ms
64 bytes from iad23s59-in-f14.1e100.net (172.217.8.14): icmp_seq=2 ttl=56 time=10.4 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 7.151/8.798/10.446/1.650 ms

PS /home/pdadmin/Downloads> exit
```

### Issue Description

Networking breaks when using PowerShell Core AppImage. Not sure how it's broken exactly, but I can't resolve anything with PowerShell cmdlets or with Linux utilities like ping or curl.

### Attached Logs

Reproduced by and additional testing done by @markekraus 
(see: https://www.reddit.com/r/PowerShell/comments/74u837/sanity_check_powershell_core_appimage_breaks/)

(FYI, I'm /u/fourierswager on reddit)

_Copied from original issue: PowerShell/vscode-powershell#1047_

**Comment by daviwil** [comment]
_From @markekraus on October 7, 2017 14:9_

I was able to repro this in both `PowerShell-6.0.0-beta.7-x86_64.AppImage` and `PowerShell-6.0.0-beta.8-x86_64.AppImage`

There appears to be an issue with DNS resolution in some instances. assuming the appimage is run as a normal user, ping works, but curl and nslookup do not. ping is unable to resolve if you run appimage as sudo. 

The impact is that the web cmdlets are also unable to resolve hostnames (as it relies on curl) and thus error on any call. I can also repro this with the underlying .NET calls

Steps to reproduce
------------------

```bash
./PowerShell-6.0.0-beta.8-x86_64.AppImage
```
```powershell
nslookup google.com

(Invoke-WebRequest http://google.com).StatusCode

curl google.com

$handler = [System.Net.Http.HttpClientHandler]::new()
$HttpClient = [System.Net.Http.HttpClient]::New($handler)
$HttpClient.GetAsync("http://www.contoso.com/").GetAwaiter().GetResult().StatusCode
```

Expected behavior
-----------------

```none
Server:         209.18.47.61
Address:        209.18.47.61#53

Non-authoritative answer:
Name:   google.com
Address: 172.217.9.142


200

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

OK
```

Actual behavior
---------------

```none
/usr/bin/nslookup: /tmp/.mount_81bJrR/usr/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.55)

Invoke-WebRequest : Couldn't resolve host name
At line:1 char:2
+ (Invoke-WebRequest http://google.com).StatusCode
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.0.0
}:HttpRequestMessage) [Invoke-WebRequest], HttpRequestException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

curl: (6) Could not resolve host: google.com

Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
At line:1 char:1
+ $HttpClient.GetAsync("http://www.contoso.com/").GetAwaiter().GetResul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : HttpRequestException
```

more details on the last error:

```none
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred
                        while sending the request." ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. --->
                        System.Net.Http.CurlException: Couldn't resolve host name
                           at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
                           at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
                           --- End of inner exception stack trace ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                           at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at CallSite.Target(Closure , CallSite , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow,
                        String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : HttpRequestException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Environment data
----------------

```none
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daviwil** [comment]
Seems like this issue should be filed at the PowerShell/PowerShell repo? I can move it there for you if you think it's not related to the PowerShell extension for VS Code.

**Comment by daviwil** [comment]
_From @markekraus on October 7, 2017 14:16_

ye.. woops.. wrong repo... https://github.com/PowerShell/PowerShell/issues

**Comment by daviwil** [comment]
Not a problem :)

**Comment by pldmgg** [comment]
Guys sorry, I didn't realize you moved this one already, I opened up #5053 right before #5054 was created.  So they're the same thing.

I'm just gonna put the keyboard down for a while :(

Let me know if I can help
