### ISSUE TITLE
StaticParameterBinder.BindCommand throws NullReferenceException when command name cannot be resolved

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#5736]
Steps to reproduce
------------------

```powershell
$commandAst = { . {} }.Ast.Find({
    $args[0] -is [System.Management.Automation.Language.CommandAst]
}, $true)

[System.Management.Automation.Language.StaticParameterBinder]::BindCommand($commandAst)
```

Expected behavior
-----------------

```none
BoundParameters BindingExceptions
--------------- -----------------
{}              {}
```

Actual behavior
---------------

```none
Exception calling "BindCommand" with "1" argument(s): "Object reference not set to an instance of an object."
At line:1 char:1
+ [System.Management.Automation.Language.StaticParameterBinder]::BindCo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NullReferenceException

> $Error[0].Exception.InnerException | Format-List * -Force
Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException :
TargetSite     : System.Management.Automation.CommandProcessorBase
                 LookupCommandProcessor(System.Management.Automation.CommandInfo,
                 System.Management.Automation.CommandOrigin, System.Nullable`1[System.Boolean],
                 System.Management.Automation.SessionStateInternal)
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at
                 System.Management.Automation.Language.PseudoParameterBinder.PrepareCommandElements(ExecutionContext
                 context)
                    at System.Management.Automation.Language.PseudoParameterBinder.DoPseudoParameterBinding(CommandAst
                 command, Type pipeArgumentType, CommandParameterAst paramAstAtCursor, BindingType bindingType)
                    at System.Management.Automation.Language.StaticParameterBinder.BindCommand(CommandAst commandAst,
                 Boolean resolve, String[] desiredParameters)
                    at CallSite.Target(Closure , CallSite , Type , Object )
HelpLink       :
Source         : System.Management.Automation
HResult        : -2147467261
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

It's worth noting that it also fails in Windows PowerShell 5.1, but it throws an `ArgumentNullException` instead and has a much different stack trace.  Here's the full exception from 5.1

```none
> $Error[0].Exception.InnerException | Format-List * -Force

Message        : Value cannot be null.
                 Parameter name: key
ParamName      : key
Data           : {}
InnerException :
TargetSite     : Void ThrowArgumentNullException(System.ExceptionArgument)
StackTrace     :    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
                    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
                    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
                    at System.Management.Automation.Language.PseudoParameterBinder.PrepareFromAst(ExecutionContext
                 context, String& resolvedCommandName)
                    at
                 System.Management.Automation.Language.PseudoParameterBinder.PrepareCommandElements(ExecutionContext
                 context)
                    at System.Management.Automation.Language.PseudoParameterBinder.DoPseudoParameterBinding(CommandAst
                 command, Type pipeArgumentType, CommandParameterAst paramAstAtCursor, BindingType bindingType)
                    at System.Management.Automation.Language.StaticParameterBinder.BindCommand(CommandAst commandAst,
                 Boolean resolve, String[] desiredParameters)
                    at CallSite.Target(Closure , CallSite , Type , Object )
HelpLink       :
Source         : mscorlib
HResult        : -2147467261
```

**Comment by SeeminglyScience** [comment]
Can no longer reproduce
