### ISSUE TITLE
Crash during daily run on MacOS in WebCmdLets

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#5775]
Steps to reproduce
------------------
https://travis-ci.org/PowerShell/PowerShell/jobs/320938186#L3155
```powershell
Describing Invoke-WebRequest tests
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Net.HttpEndPointListener.ProcessAccept(SocketAsyncEventArgs args)
   at System.Net.HttpEndPointListener.OnAccept(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.AcceptCompletionCallback(IntPtr acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressSize, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback()
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<>c.<TryCompleteOrAbortAsync>b__14_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Execution of {& $powershell -noprofile -c $Command} failed with exit code 134
At /Users/travis/build/PowerShell/PowerShell/build.psm1:2011 char:13
+             throw "Execution of {$sb} failed with exit code $LASTEXIT ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Execution of {&...h exit code 134:String) [], RuntimeException
+ FullyQualifiedErrorId : Execution of {& $powershell -noprofile -c $Command} failed with exit code 134
```

Expected behavior
-----------------
should not crash

Actual behavior
---------------

crashed

Environment data
----------------

Daily test on master between rc2 and GA
https://travis-ci.org/PowerShell/PowerShell/jobs/320938186

**Comment by markekraus** [comment]
This is consistent with random failures I have seen when starting the older HttpListener on macOS. It seems to be fragile when run inside psl-pester on macOS.

**Comment by TravisEz13** [comment]
@markekraus is there an issue already open to move those tests to the newer pattern?

**Comment by markekraus** [comment]
Yes.  #5464

**Comment by TravisEz13** [comment]
I don't think we need both issues opened to track this.
