### ISSUE TITLE
Possible Bug: Mapping "-Persist" drives with New-PSDrive using WINRM sessions

### ISSUE THREAD

**Issue by miguelantonio** [PowerShell/PowerShell#5868]
I am trying to map persistent drives using New-PSDrive on a remote winrm session with -Persist, but when I opened a new session the mapping driver got the status of "Unavailable". I am using CREDSSP

Steps to reproduce
------------------

#Session A creating the mapping
```powershell
$credentials = Get-Credential user 
$session = New-PSSession -ComputerName Server1 -Credential $credentials -Authentication CredSSP
$computername = "Server2" 
Invoke-Command -Session $session -ScriptBlock { 
param($computername) 
New-PSDrive -PSProvider FileSystem -Name "X" -Root "\\$computername\scripts" -Persist -Verbose -Scope Global 
} -ArgumentList $computername 

```

#Session B checking the mapping
```powershell
$credentials = Get-Credential user 
$session = New-PSSession -ComputerName Server1 -Credential $credentials -Authentication CredSSP
$computername = "Server2"

Invoke-Command -Session $session -ScriptBlock { 
get-PSDrive 
net use 
}
```

Actual behavior
---------------

Session B returns:
Status Local Remote Network 
------------------------------------------------------------------------------- 
Unavailable X: \\Server2\scripts Microsoft Windows Network 
The command completed successfully.

Expected behavior
-----------------

The drive X: \\Server2\scripts Microsoft Windows Network being available on Session B

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18773
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

```

**Comment by markekraus** [comment]
Hi @miguelantonio ! I'm sorry to hear you are having trouble. However, this repository is only for PowerShell Core issues (6.0.0 and newer). For Windows PowerShell issues (5.1 and older) you can open a Uservoice to report a bug https://windowsserver.uservoice.com/forums/301869-powershell or you can try one of the many internet communities for PowerShell Support.  I will close this issue. However, if you can reproduce the issue in PowerShell Core we can re-open the issue.

**Comment by miguelantonio** [comment]
Hi @markekraus, I reproduced the same behavior on 6.0.0, could you re-open this?, this is my PSVersion:

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by miguelantonio** [comment]
Hi, could you see this issue? 

Thank you in advance!!

**Comment by brwilkinson** [comment]
@miguelantonio 

This appears to just be a double hop issue . . which is well known and documented.
- you need to setup CredSSP (delegate to/from) correctly for this to work or else provide creds for the 2nd hop.

This workaround is likely the easiest . . pass in the cred to the session...

$cred = get-credential user
Invoke-Command -Session $session -ScriptBlock { 
New-PSDrive -PSProvider FileSystem -Name "X" -Root "\\$using:computername\scripts" -Persist -Verbose -Scope Global -Credential $using:Cred
dir x:\
}

**Comment by brwilkinson** [comment]
okay I have been able to get a similar issue...

I can connect 'only' the first time, however after that I get the following error.. I am connecting to an Azure File Share.

````powershell
$cred = get-credential stagecus1
$root = '\\stagecus1.file.core.windows.net\source'
$pso = New-PSSessionOption -OpenTimeout 30000 -OperationTimeout 20000 -cancelTimeout 10000 
# Test against PC 7 preview 6 . . works fine only the first time.
$psSessionEndPoint7 = "PowerShell.7-preview"
$s7 = New-PSSession -ComputerName AZC1ADFS1SQL03 -SessionOption $pso -ErrorAction SilentlyContinue -ConfigurationName $psSessionEndPoint7
$s7

icm -Session $s7 -ScriptBlock {

    function foo
    {
    param ($root,$c)
        hostname
        $PSVersionTable
        if (-not(get-psdrive -name source -ErrorAction SilentlyContinue))
        {
            New-PSDrive -name source -Root $root -PSProvider FileSystem -Credential $c
        }
        $error[0] | select *
        dir source:\ -ErrorAction SilentlyContinue
    }
    $using:root
    foo -root $using:root -c $using:cred
    get-psdrive -name source -ea 0 | remove-psdrive

}
````

This is the output

````error
A specified logon session does not exist. It may already have been terminated.
    + CategoryInfo          : InvalidOperation: (source:PSDriveInfo) [New-PSDrive], Win32Exception
    + FullyQualifiedErrorId : CouldNotMapNetworkDrive,Microsoft.PowerShell.Commands.NewPSDriveCommand
    + PSComputerName        : AZC1ADFS1SQL03
 ````

````exception
PSMessageDetails      : 
Exception             : System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Drive name must be a root directory (i.e. 'C:\') or a drive letter ('C'). (Parameter 'driveName')"
                         ---> System.ArgumentException: Drive name must be a root directory (i.e. 'C:\') or a drive letter ('C'). (Parameter 'driveName')
                           at System.IO.DriveInfoInternal.NormalizeDriveName(String driveName)
                           at System.IO.DriveInfo..ctor(String driveName)
                           at CallSite.Target(Closure , CallSite , Type , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior 
                        errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, 
                        Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
                           at System.Management.Automation.PSScriptProperty.InvokeGetter(Object scriptThis)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ArgumentException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 5
                        at foo, <No file>: line 10
                        at <ScriptBlock>, <No file>: line 16
PipelineIterationInfo : {}
PSComputerName        : AZC1ADFS1SQL03
RunspaceId            : 8e662156-c259-4d30-b81a-5d9f9be698ae
````

**Comment by brwilkinson** [comment]
I seem to be able to consistently connect by setting the psdrive scope to local.

@miguelantonio you may want to test with this as well.

New-PSDrive -name P -Root $using:root -PSProvider FileSystem -Credential $using:cred -Scope local -Persist

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
