### ISSUE TITLE
Bug: Calling Get-CimInstance with Invoke-Command results in error: Unable to load DLL 'libmi.so'

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#5950]
### Symptom

```
PS /Users/tsulli> $SessionList = @()
PS /Users/tsulli> $SessionList += New-PSSession -SSHTransport .... .... .... ....
PS /Users/tsulli> Invoke-Command -Session $SessionList -ScriptBlock { Get-CimInstance -ClassName Win32_OperatingSystem }
Unable to load DLL 'libmi.so': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
```

### Expected Result

CIM instances are returned from remote PowerShell sessions.

### Actual Result

Error is returned.

### Environment

```
PS /Users/tsulli> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0
PSEdition                      Core
GitCommitId                    v6.0.0
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Cheers,
Trevor Sullivan

**Comment by daxian-dbw** [comment]
@pcgeek86 Thanks for the report! I presume that the remote session is not a loopback, right?
Could you please share the stack trace?

**Comment by pcgeek86** [comment]
@daxian-dbw Yep, that's correct. Does this help?

```
PS /Users/tsulli> $StackTrace
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at System.Management.Automation.RemoteDebugger.set_UnhandledBreakpointMode(UnhandledBreakpointProcessingMode value)
   at Microsoft.PowerShell.Commands.ExecutionCmdletHelper.ConfigureRunspaceDebugging(Runspace runspace)
   at Microsoft.PowerShell.Commands.ExecutionCmdletHelperRunspace.StartOperation()
   at System.Management.Automation.Remoting.ThrottleManager.StartOneOperationFromQueue()
   at System.Management.Automation.Remoting.ThrottleManager.StartOperationsFromQueue()
   at System.Management.Automation.Remoting.ThrottleManager.SubmitOperations(List`1 operations)
   at System.Management.Automation.PSInvokeExpressionSyncJob.StartOperations(List`1 operations)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.CreateAndRunSyncJob()
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by daxian-dbw** [comment]
@pcgeek86 Thanks!
@PaulHigin can you please take a look?

**Comment by SteveL-MSFT** [comment]
The problem is that the pwsh client relies on libmi to deserialize a CIM instance to a PSObject.  It seems that the nupkg for mmi.dll doesn't include a macOS runtime, only a generic `unix` runtime which is really Linux (libmi.so).  Fix would be to publish new version of mmi.dll with proper runtime for `osx-x64`.
