### ISSUE TITLE
DscTimer on LCM on client nodes enters 10 minute loop and keep sending empty reports to DSCPull server

### ISSUE THREAD

**Issue by idelix** [PowerShell/PowerShell#6412]
DscTimer on LCM on client nodes enters 10 minute loop when it tries to send some report and generate following errors, at the end the empty reports are being send all the time to pull server every 10 minutes.

It creates empty 1KB report sin inside Windows/Sstem32/Configurations 

Not sure what it happens every 10 minutes as my frequencies setup on client LCM are following:
ConfigurationModeFrequencyMins 60
RefreshFrequencyMins 120

OS: 2012 and 2016
PsVersion: 5.1.14409

The DscTimer is going to start the timer to create task for sending pending report for the first time with value 10 minutes.

The DscTimer successfully created the timer to create task for sending pending report.

The DscTimer has successfully run LCM method PerformRequiredConfigurationChecks with flag 2.

The local configuration manager was shut down.

The DscTimer is running LCM method PerformRequiredConfigurationChecks with the flag set to 8.

The local configuration manager started.

Job {44C35850-292C-11E8-80C5-0050569E104B} : 
Operation Consistency Check or Pull started by user sid S-1-5-20 from computer NULL.

Job {44C35850-292C-11E8-80C5-0050569E104B} : Details logging started to C:\Windows\System32\Configuration\ConfigurationStatus\{44C35850-292C-11E8-80C5-0050569E104B}-0.details.json.

Job {44C35850-292C-11E8-80C5-0050569E104B} : 
Message Year, Month, and Day parameters describe an un-representable DateTime. 
HResult -2146233086 
StackTrack    at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   at System.Globalization.GregorianCalendar.ToDateTime(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond, Int32 era)
   at System.Globalization.Calendar.ToDateTime(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond, Calendar calendar, DateTimeKind kind)
   at Microsoft.Management.Infrastructure.Native.InstanceMethods.ConvertMiDateTimeToManagedObject(_MI_Datetime* pmiValue)
   at Microsoft.Management.Infrastructure.Native.InstanceMethods.GetElementAt_GetValue(InstanceHandle handle, Int32 index, Object& value)
   at Microsoft.Management.Infrastructure.Internal.Data.CimPropertyOfInstance.get_Value()
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.ConvertCimInstanceToHashTable(CimInstance cimInstance, Boolean bWrap)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.ConvertCimInstanceToHashTable(CimInstance cimInstance, Boolean bWrap)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.ConvertCimInstanceToHashTable(CimInstance cimInstance, Boolean bWrap)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.GetJsonStringArrayStatusValue(Object value, IntPtr& statusInstanceHandle, UInt32& getActionStatusCode)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.AddSendStatusParametersFromStatusInformation(PowerShell powershell, IntPtr statusInformationPtr, UInt32 reportType, IntPtr& errorInstanceHandle, UInt32& getActionStatusCode)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DownloadManagerBase.SendStatusReport(IntPtr metaConfigHandle, IntPtr& errorInstanceHandle, IntPtr statusInformation, UInt32 reportType, UInt32& getActionStatusCode)

Job {44C35850-292C-11E8-80C5-0050569E104B} : 
MIResult: 1
Error Message: 
Message ID: 
Error Category: 0
Error Code: 1
Error Type: 

Job {44C35850-292C-11E8-80C5-0050569E104B} : 
MIResult: 1
Error Message: NULL
Message ID: NULL
Error Category: 0
Error Code: 0
Error Type: NULL

**Comment by daxian-dbw** [comment]
@nitinbps Could you please redirect @idelix to the proper channel for reporting DSC issues?

**Comment by kwirkykat** [comment]
@idelix The best place to open issues on DSC right now is on User Voice [here](https://windowsserver.uservoice.com/forums/301869-powershell/category/148047-desired-state-configuration-dsc)
What is the culture/system locale of your machine?

**Comment by idelix** [comment]
Thanks will relocate this

**Comment by vivekgrover2** [comment]
@rhollins @iSazonov @kwirkykat @daxian-dbw: I am facing the exact same issue. I know it's an old thread. Please help.

**Comment by ThomasNieto** [comment]
@vivekgrover2 the LCM isn't in this repository.

**Comment by vivekgrover2** [comment]
> @vivekgrover2 the LCM isn't in this repository.

Can you please explain what that means and how to resolve it? Any help will be appreciated

**Comment by ThomasNieto** [comment]
It's a built-in windows component so you'd need to submit the issue in feedback hub.
