### ISSUE TITLE
Help cmdlet fails in PS 6.1.0-preview.1 when StrictMode is enabled 

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#6497]
Steps to reproduce
------------------

```powershell
Set-StrictMode -Version Latest
help
```
or

```powershell
Set-StrictMode -Version Latest
man
```

Expected behavior
-----------------

```powershell
TOPIC                                                    
    PowerShell Help System                               
                                                         
SHORT DESCRIPTION                                        
    Displays help about PowerShell cmdlets and concepts. 
...
```

Actual behavior
---------------

```powershell
PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: The variable '$moreArgs' cannot be retrieved because it has not been set.
                           at System.Management.Automation.VariableOps.GetVariableValue(VariablePath variablePath, ExecutionContext executionContext, VariableExpressionAst varAst)
                           at System.Management.Automation.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : moreArgs
CategoryInfo          : InvalidOperation: (moreArgs:String) [], RuntimeException
FullyQualifiedErrorId : VariableIsUndefined
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 24
                        at <ScriptBlock>, <No file>: line 69
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is seem related with `more` function.

**Comment by mklement0** [comment]
On a meta note: Implementation of [RFC0003-Lexical-Strict-Mode.md](
https://github.com/PowerShell/PowerShell-RFC/blob/aa58c098cd78453c70ed51b521dd0ad14d17217a/1-Draft/RFC0003-Lexical-Strict-Mode.md) would presumably make such problems go away.

**Comment by kborowinski** [comment]
@iSazonov Works as expected on latest nightly build **v6.1.0-preview.9301** on **Windows 10.0.17134.1 x64**

**Comment by iSazonov** [comment]
@kborowinski Thanks for confirmation and contribution!
