### ISSUE TITLE
2 calls to New-PSSession hang pwsh at exit 

### ISSUE THREAD

**Issue by mikeplavsky** [PowerShell/PowerShell#6825]
Steps to reproduce
------------------

```bash
docker run -ti -v $(pwd):/test --cap-add SYS_PTRACE microsoft/powershell:ubuntu16.04 bash
>> cd test
>> pwsh test.ps > res.txt 
```

```powershell
$PSVersionTable
Set-PSDebug -Trace 2 -Strict

$ErrorActionPreference = "Stop"

$opts = [System.Management.Automation.Remoting.PSSessionOption]::new()
$opts.OutputBufferingMode="Drop"

$adm = "***"
$pwd = "***" | ConvertTo-SecureString -AsPlainText -Force

$creds = New-Object `
    -TypeName System.Management.Automation.PSCredential $adm, $pwd

function start {

    $session = New-PSSession -ConfigurationName Microsoft.Exchange `
        -SessionOption @opts `
        -ConnectionUri "https://outlook.office365.com/powershell-liveid/" `
        -Credential $creds  `
        -Authentication Basic -AllowRedirection

    $session
}

start
start

$all = Get-PSSession
$all | %{ Remove-PSSession $_}
```

Expected behavior
-----------------

```none
running  `pwsh test.ps > res.txt`
it should run and exit
```

Actual behavior
---------------

```none
it just hangs after executing
```

```none
last lines from res.txt
DEBUG:   29+  >>>> $all = Get-PSSession

DEBUG:     ! SET $all = '[PSSession]WinRM1 [PSSession]WinRM2'.
DEBUG:   30+  >>>> $all | %{ Remove-PSSession $_}

DEBUG:   30+ $all | % >>>> { Remove-PSSession $_}

DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   30+ $all | %{  >>>> Remove-PSSession $_}

DEBUG:   30+ $all | %{ Remove-PSSession $_ >>>> }

DEBUG:   30+ $all | % >>>> { Remove-PSSession $_}

DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   30+ $all | %{  >>>> Remove-PSSession $_}
```

``` 
gdb pwsh
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f4bee1a8142 in CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) () from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#2  0x00007f4bee1a7d84 in CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) () from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#3  0x00007f4bee1acba1 in CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int) ()
   from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#4  0x00007f4bede00b90 in Thread::DoAppropriateWaitWorker(int, void**, int, unsigned int, WaitMode) () from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#5  0x00007f4beddfb5b0 in Thread::DoAppropriateWait(int, void**, int, unsigned int, WaitMode, PendingSync*) ()
   from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#6  0x00007f4bede50830 in WaitHandleNative::CorWaitOneNative(SafeHandle*, int, bool, bool) () from /opt/microsoft/powershell/6.0.2/libcoreclr.so
#7  0x00007f4b74773b2d in ?? ()
#8  0x00007ffccb7673c0 in ?? ()
#9  0x0000000000000000 in ?? ()
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.9.87-linuxkit-aufs #1 SMP Fri Mar 16 ...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by KKomarov** [comment]
Confirm on 6.0.2
On 6.0.3 got a different error
Works fine since 6.0.4

**Comment by SteveL-MSFT** [comment]
Looks like something was fixed in .NET Core.  If someone still repros this, we can reopen.
