### ISSUE TITLE
Assertion failure in master: "new Cmdlet added to System.Management.Automation.dll - update InitializeCoreCmdletsAndProviders"

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#6886]
Running PowerShell from `master` on Ubuntu 18.04.

Looks like a new cmdlet has been added to PowerShell and [InitializeCoreCmdletsAndProviders](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/System.Management.Automation/engine/InitialSessionState.cs#L5334) has not been updated?

Not sure if this is just me -- may need someone else to reproduce this...

Steps to reproduce
------------------
1. Clone master (commit `4e3db1bb93b17228752de9e3e99f89defbdc01b0`) on a supported UNIX-like.
1. Build in `Debug` configuration.
1. Execute the generated PowerShell binary.

Expected behavior
-----------------
PowerShell starts and presents a prompt.

Actual behavior
---------------

```none
PS /home/rob/Documents/Dev/Microsoft/PowerShell> ./src/powershell-unix/bin/Debug/netcoreapp2.1/linux-x64/publish/pwsh                                                                                     
Assertion Failed
new Cmdlet added to System.Management.Automation.dll - update InitializeCoreCmdletsAndProviders

   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen, String detailMessage) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/utils/assert.cs:line 195
   at System.Management.Automation.Diagnostics.Assert(Boolean condition, String whyThisShouldNeverHappen) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/utils/assert.cs:line 130
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 5113
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 3766
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCorePSSnapIn() in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 3691
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2() in /home/rob/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 1609
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs:line 62
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args) in /home/rob/Documents/Dev/Microsoft/PowerShell/src/powershell/Program.cs:line 22
```
(Failing assertion is [here](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/System.Management.Automation/engine/InitialSessionState.cs#L5113))

Environment data
----------------

```
PS /home/rob/Documents/Dev/Microsoft/PowerShell> uname -a                                            
Linux hyperion 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PS /home/rob/Documents/Dev/Microsoft/PowerShell> cat /etc/os-release                                 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by rjmholt** [comment]
These cmdlets are in `cmdletsCheck` and not `cmdlets` where the assertion is failing:
```
Connect-PSSession
Register-PSSessionConfiguration
Unregister-PSSessionConfiguration
Get-PSSessionConfiguration
Set-PSSessionConfiguration
Enable-PSSessionConfiguration
Disable-PSSessionConfiguration
Enable-PSRemoting
Disable-PSRemoting
Get-PSSessionCapability
Disconnect-PSSession
Enter-PSHostProcess
Exit-PSHostProcess
Get-PSHostProcessInfo
New-PSSessionConfigurationFile
New-PSSessionOption
Receive-PSSession
Test-PSSessionConfigurationFile
```

**Comment by rjmholt** [comment]
Aha! Looks like deleting [an `#if !UNIX`](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/System.Management.Automation/engine/InitialSessionState.cs#L5345) solve this.

I'm assuming the remoting cmdlets were added to UNIX and this was missed (easy to do)...

I'll open a PR.

**Comment by rjmholt** [comment]
Sadly none of this helps the fact that the reason I built master in the first place was because I didn't seem to get the `-CompilerOptions` parameter on `Add-Type` in 6.0.2.

The docs claim that [`Add-Type` has the `-CompilerParameters` parameter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-6) in PowerShell 6.

The actual code shows [`Add-Type` has a parameter called `-CompilerOptions`](https://github.com/PowerShell/PowerShell/blob/4e3db1bb93b17228752de9e3e99f89defbdc01b0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L461).

But on my Ubuntu 18.04 machine I've only got the following:
```powershell
> (Get-Command Add-Type).Parameters

Key                  Value
---                  -----
TypeDefinition       System.Management.Automation.ParameterMetadata
Name                 System.Management.Automation.ParameterMetadata
MemberDefinition     System.Management.Automation.ParameterMetadata
Namespace            System.Management.Automation.ParameterMetadata
UsingNamespace       System.Management.Automation.ParameterMetadata
Path                 System.Management.Automation.ParameterMetadata
LiteralPath          System.Management.Automation.ParameterMetadata
AssemblyName         System.Management.Automation.ParameterMetadata
Language             System.Management.Automation.ParameterMetadata
ReferencedAssemblies System.Management.Automation.ParameterMetadata
OutputAssembly       System.Management.Automation.ParameterMetadata
OutputType           System.Management.Automation.ParameterMetadata
PassThru             System.Management.Automation.ParameterMetadata
IgnoreWarnings       System.Management.Automation.ParameterMetadata
Verbose              System.Management.Automation.ParameterMetadata
Debug                System.Management.Automation.ParameterMetadata
ErrorAction          System.Management.Automation.ParameterMetadata
WarningAction        System.Management.Automation.ParameterMetadata
InformationAction    System.Management.Automation.ParameterMetadata
ErrorVariable        System.Management.Automation.ParameterMetadata
WarningVariable      System.Management.Automation.ParameterMetadata
InformationVariable  System.Management.Automation.ParameterMetadata
OutVariable          System.Management.Automation.ParameterMetadata
OutBuffer            System.Management.Automation.ParameterMetadata
PipelineVariable     System.Management.Automation.ParameterMetadata
```

This is with:
```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It seems these cmdlets are not supported on Unix. I guess a fix is in another place.
