### ISSUE TITLE
Get-LocalGroupMember -Group Administrators bug

### ISSUE THREAD

**Issue by amazoko** [PowerShell/PowerShell#7105]
we stumbled on the following bug.

I think there is the problem, that a non existing SID is in this group, and it cannot be skipped.

PS C:\Windows\system32> Get-LocalGroupMember -Group Administrators

Get-LocalGroupMember : Failed to compare two elements in the array.

At line:1 char:1

+ Get-LocalGroupMember -Group Administrators

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException

    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

PS C:\Windows\system32> $error[0] | fl * -force

writeErrorStream      : True

PSMessageDetails      :

Exception             : System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an

                        instance of an object.

                           at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.<>c.<ProcessesMembership>b__20_0(LocalPrincipal p1, LocalPrincipal p2)

                           at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)

                           at System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] keys, Int32 left, Int32 right, IComparer`1 comparer, Int32 depthLimit)

                           at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

                           --- End of inner exception stack trace ---

                           at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

                           at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)

                           at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)

                           at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.ProcessesMembership(IEnumerable`1 membership)

                           at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.ProcessRecord()

TargetObject          :

CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException

FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

ErrorDetails          :

InvocationInfo        : System.Management.Automation.InvocationInfo

ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

PipelineIterationInfo : {0, 1}

**Comment by mklement0** [comment]
Since the `Get-LocalGroupMember` is not part of PowerShell _Core_ (at least yet), please report this issue on the Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) forum instead.

On a side note, re formatting here on GitHub: Please use either fenced code blocks or indentation to highlight code and output - it makes it much easier to see what's going on - see https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by iSazonov** [comment]
@amazoko  Thanks for your report!

Dup #2996.

**Comment by mklement0** [comment]
@iSazonov: 

Thanks for finding the duplicate. 

To ensure that I don't point others to the wrong place in the future: 

* I now see that the _source code_ for `Get-LocalGroupMember` is in the PS Core repo, but it appears not to be _available at runtime_ - a comment of yours on the linked issue suggests that is _disabled_ on purpose.

   * Short of testing the availability of a command in a console window, is there an easy way to tell from the source code what commands are currently disabled?

* What's the policy in this scenario on reporting issues that - by definition - surface in _Windows PowerShell_ only, but _potentially_ affect PS Core should the code be activated in the future?  

  * I guess it makes sense to report such issues in this repo [too], but that won't happen unless the reporter has gone out of their way to look for inactive code in the Core repo that relates to the problem they're seeing in Windows PowerShell.

**Comment by treestryder** [comment]
@flanagansshenanigans Your script would remove the two SSIDs added to the Administrators group of an Azure AD joined PC. Which, as these are the only accounts/groups in the administrators group besides the default %ComputerName%\Administrator account, they must be what are causing me to see the aforementioned error.
