### ISSUE TITLE
PowerShell v6.1.0-preview.4: Non-GAC DLLs Not Found

### ISSUE THREAD

**Issue by rockerinthelocker** [PowerShell/PowerShell#7326]
This bug is still not resolved (see #7076 for further details).

```
$GeoIpDbPath = 'C:\GeoIP\'
$GeoIpLibrary = $GeoIpDbPath + 'MaxMind.GeoIP2.dll'
$GeoIpDbLibrary = $GeoIpDbPath + 'MaxMind.Db.dll'
$GeoIpNewtonJson = $GeoIpDbPath + 'Newtonsoft.Json.dll'
$GeoIpAsnDb = $GeoIpDbPath + 'GeoLite2-ASN.mmdb'

[System.Reflection.Assembly]::LoadFile($GeoIpLibrary)
[System.Reflection.Assembly]::LoadFile($GeoIpDbLibrary)
[System.Reflection.Assembly]::LoadFile($GeoIpNewtonJson)

$asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
```

The code above works as expected with all PowerShell versions but 6.1.0-preview.3 and 6.1.0-preview.4. The last two preview versions throw

```
Could not load file or assembly 'MaxMind.Db, Version=2.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'. The system cannot find the file specified.
At line:1 char:1
+ $asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException
```

Without support for non-GAC assemblies, PowerShell Core is pretty much useless.

**Comment by daxian-dbw** [comment]
@rockerinthelocker Can you please provide a simpler repro? That would be very helpful. Or, please add instructions about how to set up to reproduce with the `MaxMind` assemblies.

**Comment by iSazonov** [comment]
I can load an assembly from local folder without problem. I guess the issue is only with MaxMind assemblies.

**Comment by rockerinthelocker** [comment]
@daxian-dbw @adityapatwardhan @iSazonov
The setup is quite simple and takes just a couple of minutes.

1) Open a command prompt, create folder C:\GeoIP, and cd to it.

2) Install the MaxMind GeoIP2 package (available at https://www.nuget.org/packages/MaxMind.GeoIP2/) via nuget.exe (https://www.nuget.org/downloads) like so:

```
nuget install MaxMind.GeoIP2 -Version 3.0.0
```

3) For testing purposes, the .NET flavor (net45, netstandard 2.0, etc.) of the DLLs included in the packages does not matter so simply grab

```
C:\GeoIP\MaxMind.GeoIP2.3.0.0\lib\netstandard2.0\MaxMind.GeoIP2.dll
C:\GeoIP\MaxMind.Db.2.4.0\lib\netstandard2.0\MaxMind.Db.dll
C:\GeoIP\Newtonsoft.Json.11.0.2\lib\netstandard2.0\Newtonsoft.Json.dll
```

and copy to C:\GeoIP.

4) Download the GeoLite2 ASN database from http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz and unpack 'GeoLite2-ASN.mmdb' included in the archive to C:\GeoIP.

Now, there should be

```
GeoLite2-ASN.mmdb
MaxMind.Db.dll
MaxMind.GeoIP2.dll
Newtonsoft.Json.dll
```

in C:\GeoIP and all is set.

5) Finally, execute

```
$GeoIpDbPath = 'C:\GeoIP\'
$GeoIpLibrary = $GeoIpDbPath + 'MaxMind.GeoIP2.dll'
$GeoIpDbLibrary = $GeoIpDbPath + 'MaxMind.Db.dll'
$GeoIpNewtonJson = $GeoIpDbPath + 'Newtonsoft.Json.dll'
$GeoIpAsnDb = $GeoIpDbPath + 'GeoLite2-ASN.mmdb'

[System.Reflection.Assembly]::LoadFile($GeoIpLibrary)
[System.Reflection.Assembly]::LoadFile($GeoIpDbLibrary)
[System.Reflection.Assembly]::LoadFile($GeoIpNewtonJson)

$asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
```


Thank you!

**Comment by iSazonov** [comment]
I can repo. I got the error after `[MaxMind.GeoIP2.DatabaseReader]::new` (without parameter and brackets):
```powershell
$error[0].Exception | fl -Force


ErrorRecord                 : The following exception occurred while retrieving member "New": "Could not load file or
                              assembly 'MaxMind.Db, Version=2.0.0.0, Culture=neutral,
                              PublicKeyToken=66afa4cc5ae853ac'. The system cannot find the file specified."
WasThrownFromThrowStatement : False
Message                     : The following exception occurred while retrieving member "New": "Could not load file or
                              assembly 'MaxMind.Db, Version=2.0.0.0, Culture=neutral,
                              PublicKeyToken=66afa4cc5ae853ac'. The system cannot find the file specified."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.IO.FileNotFoundException: Could not load file or assembly 'MaxMind.Db,
                              Version=2.0.0.0, Culture=neutral, PublicKeyToken=66afa4cc5ae853ac'. The system cannot
                              find the file specified.
                              File name: 'MaxMind.Db, Version=2.0.0.0, Culture=neutral,
                              PublicKeyToken=66afa4cc5ae853ac' ---> System.IO.FileNotFoundException: Could not load
                              the specified file.
                              File name: 'MaxMind.Db'
                                 at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName
                              assemblyName)
                                 at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr
                              gchManagedAssemblyLoadContext, AssemblyName assemblyName)
                                 at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig,
                              RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType
                              declaringType)
                                 at System.Reflection.RuntimeConstructorInfo.get_Signature()
                                 at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
                                 at System.Reflection.RuntimeConstructorInfo.GetParameters()
                                 at System.Management.Automation.MethodInformation..ctor(MethodBase method, Int32
                              parametersToIgnore) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Manag
                              ement.Automation\engine\CoreAdapter.cs:line 1876
                                 at System.Management.Automation.DotNetAdapter.GetMethodInformationArray(MethodBase[]
                              methods) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Autom
                              ation\engine\CoreAdapter.cs:line 3869
                                 at System.Management.Automation.DotNetAdapter.MethodCacheEntry..ctor(MethodBase[]
                              methods) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Autom
                              ation\engine\CoreAdapter.cs:line 2347
                                 at System.Management.Automation.DotNetAdapter.PopulateMethodReflectionTable(Type
                              type, CacheTable typeMethods, BindingFlags bindingFlags) in C:\Users\sie\Documents\GitHub
                              \iSazonov\PowerShell\src\System.Management.Automation\engine\CoreAdapter.cs:line 2882
                                 at System.Management.Automation.DotNetAdapter.GetStaticMethodReflectionTable(Type
                              type) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automati
                              on\engine\CoreAdapter.cs:line 3179
                                 at System.Management.Automation.DotNetAdapter.GetDotNetMethod[T](Object obj, String
                              methodName) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Au
                              tomation\engine\CoreAdapter.cs:line 3353
                                 at System.Management.Automation.DotNetAdapter.GetMember[T](Object obj, String
                              memberName) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Au
                              tomation\engine\CoreAdapter.cs:line 3542
                                 at System.Management.Automation.Adapter.BaseGetMember[T](Object obj, String
                              memberName) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Au
                              tomation\engine\CoreAdapter.cs:line 375


TargetSite                  : T BaseGetMember[T](System.Object, System.String)
StackTrace                  :    at System.Management.Automation.Adapter.BaseGetMember[T](Object obj, String
                              memberName) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Au
                              tomation\engine\CoreAdapter.cs:line 380
                                 at System.Management.Automation.PSObject.GetStaticCLRMember(Object obj, String
                              methodName) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Au
                              tomation\engine\MshObject.cs:line 1014
                                 at System.Management.Automation.Language.PSGetMemberBinder.GetPSMemberInfo(DynamicMeta
                              Object target, BindingRestrictions& restrictions, Boolean& canOptimize, Type&
                              aliasConversionType, MemberTypes memberTypeToOperateOn, HashSet`1 aliases, List`1
                              aliasRestrictions) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Manage
                              ment.Automation\engine\runtime\Binding\Binders.cs:line 5446
                                 at System.Management.Automation.Language.PSGetMemberBinder.FallbackGetMember(DynamicMe
                              taObject target, DynamicMetaObject errorSuggestion) in C:\Users\sie\Documents\GitHub\iSaz
                              onov\PowerShell\src\System.Management.Automation\engine\runtime\Binding\Binders.cs:line
                              5055
                                 at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
                                 at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[]
                              args)
                                 at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1
                              parameters, LabelTarget returnLabel)
                                 at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site,
                              Object[] args)
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame
                              frame) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Automat
                              ion\engine\interpreter\DynamicInstructions.Generated.cs:line 139
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Managem
                              ent.Automation\engine\interpreter\ControlFlowInstructions.cs:line 356
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

```

**Comment by rockerinthelocker** [comment]
@iSazonov , Thanks for taking the time and providing further details!

@daxian-dbw , It seems you're right and it's a .NET Core 2.1 issue.

@coolcsh  , Looks like something related to loading non-GAC DLLs is broken in .NET Core 2.1. Maybe you can get someone looking into this? Thank you!

**Comment by SteveL-MSFT** [comment]
@rockerinthelocker can you open an issue in the coreclr repo?  Will get more immediate attention I think.

**Comment by vitek-karas** [comment]
To make this work simply change the `[System.Reflection.Assembly]::LoadFile` to `[System.Reflection.Assembly]::LoadFrom`. With that your repro works on the 6.1.0-preview.4.

The reason this fails with `LoadFile` is that `LoadFile` loads the specified assembly into its own `AssemblyLoadContext` (ALC) and thus the 3 files are loaded into different ALCs and don't "see each other". Unlike on desktop, the .NET Core runtime will not look for assemblies "next-to" the one it's currently using, so the one loaded by `LoadFile` also doesn't see the files on disk right next to it.
`LoadFrom` is different, it loads the assemblies into the Default ALC so basically to the same set as everything else (namely PS in this case). It also implements a file based lookup, so it will load files "next to". The downside of this approach is that you can't load the same assembly twice into the Default ALC. So if there's a version collision between PS and your "plugin" (GeoIP), then it won't work.

With 6.1.0-preview.4 PS happens to use the same version of Newtonsoft.Json as the GeoIP v3.0.0, so it works. I also tried this on 6.0.3 PS and there it fails because PS uses older version of Newtonsoft.Json.

@daxian-dbw I don't see how this behavior changed in .NET Core. The above behavior of `LoadFile` versus `LoadFrom` is the same in .NET Core 2.0 and 2.1. If you do have a version where this used to work and now it doesn't I would be very interesting in it.

We are working on providing actually working and easy to use solution for scenarios like this for .NET Core 3. In .NET Core 2.1, it is possible to make it work, but it requires an implementation of a custom `AssemblyLoadContext`. While possible to code this up in PS, it's definitely not "simple".

**Comment by jkotas** [comment]
> Unlike on desktop, the .NET Core runtime will not look for assemblies "next-to" the one it's currently using, so the one loaded by LoadFile also doesn't see the files on disk right next to it.

`LoadFile` on desktop does not look "next-to" for dependencies either. The behavior of LoadFile is the same between desktop and .NET Core in this regard.

**Comment by daxian-dbw** [comment]
@vitek-karas and @jkotas, thank you for the clarification, it's very helpful!

**Comment by jkotas** [comment]
> Could not load type 'System.IO.MemoryMappedFiles.MemoryMappedFileSecurity

The assembly you are trying to run is not compatible with .NET Core.

This type does not exist in .NET Core today. It is tracked by https://github.com/dotnet/corefx/issues/29546

**Comment by rockerinthelocker** [comment]
@jkotas, Glad you figured that LoadFile no longer works with PowerShell v6.1.0-preview.3+.

**Comment by jkotas** [comment]
@rockerinthelocker This assembly could have never worked well on .NET Core properly. It is referencing types that never existed in .NET Core.

**Comment by rockerinthelocker** [comment]
@jkotas , Not sure what assembly you're referring to, but the MaxMind GeoIP assemblies work just fine with PowerShell v6.1.0-preview.2 and previous PowerShell Core versions. Apparently, some breaking change was made in PowerShell v6.1.0-preview.3 or .NET Core 2.1; and it would be great if you guys figure out so existing PowerShell scripts continue to work as expected before PowerShell Core 6.1 gets released.

**Comment by jkotas** [comment]
@rockerinthelocker I have tried the steps in https://github.com/PowerShell/PowerShell/issues/7326#issuecomment-406883555 to reproduce this. It works fine for me (w/ LoadFile replace with LoadFrom):

![image](https://user-images.githubusercontent.com/6668460/43857116-3e547d34-9aff-11e8-8931-94447df24d43.png)

**Comment by rockerinthelocker** [comment]
@jkotas , Thank you for taking the time! It's indeed strange, because the above throws here (see https://github.com/dotnet/coreclr/issue_comments#issuecomment-411633010). Thank you!

**Comment by rockerinthelocker** [comment]
@jkotas , Back to the topic. All PowerShell versions, except 6.1.0 previews 3 and 4, have no issues with LoadFile. PowerShell 6.1.0 preview 3 and 4 (targeting .NET Core 2.1 instead of .NET 2.0), however, ignore the path specified and just search for the assemblies in the GAC.

**Comment by jkotas** [comment]
> All PowerShell versions, except 6.1.0 previews 3 and 4, have no issues with LoadFile

Not what I see. I have tried steps from https://github.com/PowerShell/PowerShell/issues/7326#issuecomment-406883555 on PowerShell-6.0.3-win-x64 .  It is the stable version from https://github.com/PowerShell/PowerShell#get-powershell . It fails the same way as PowerShell 6.1.0 preview 4.

![image](https://user-images.githubusercontent.com/6668460/43926737-1d8d4978-9be0-11e8-9649-4339f538afa8.png)

**Comment by rockerinthelocker** [comment]
@jkotas , Maybe that version includes the bug as well. Anyway, this thread is about PowerShell 6.1.0.

**Comment by jkotas** [comment]
The exception is expected. LoadFile is working as speced and documented. It worked this way for last 15+ years since .NET Framework 1.0. There is no bug as far as .NET Core runtime is concerned.

If it somehow worked differently for you in a particular version of powershell, please point us to the exact version and repro steps. We will be happy to take a look.
