### ISSUE TITLE
Getting exception while Get-LocalGroupMember -Name "Group Name"

### ISSUE THREAD

**Issue by ankurvi** [PowerShell/PowerShell#7442]
Steps to reproduce
------------------

Execute following command on PowerShell command line or through PowerShell script
Get-LocalGroupMember -Name "\<Group Name\>"

There should be one invalid user in the group. I am able to add that user using 
Add-LocalGroupMember -Group "\<Group Name\>" -Member "\<SID\>"

But not able to get it thorugh Get-LocalGroupMember

Expected behavior
-----------------

Should return list of members in the group or I should able to skip it.

Actual behavior
---------------

Getting Exception: While executing through PowerShell script.
-------------------
G:\Ankur\NewPopulateLocalAD.ps1 : 
Caught Exception: System.InvalidOperationException: Failed to compare two elements
in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.<>c.<ProcessesMembership>b__20_0(LocalPrincipal p1,
LocalPrincipal p2)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] keys, Int32 left, Int32 right,
IComparer`1 comparer, Int32 depthLimit)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.ProcessesMembership(IEnumerable`1 membership)
   at Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand.ProcessRecord() #at At
G:\Ankur\NewPopulateLocalAD.ps1:63 char:28
+ ... pmembers1 = Get-LocalGroupMember -Name $LocalGroupName -ErrorAction S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\NewPopulateLocalAD.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,NewPopulateLocalAD.ps1

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Dup #7105 and #2996

**Comment by iSazonov** [comment]
Leave a comment
