### ISSUE TITLE
Test-Connection.Tests.ps1 - Ping Fake host fails due to different InnerException.ErrorCode on Centos7

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#7590]
On non-Windows, 'Ping Fake host' expects an error code of 6 in the error.Exception.InnerException.ErrorCode.  On CentOS, the ErrorCode is 11 (Resource temporarily unavailable).

Steps to reproduce
------------------

```powershell
Start-PSPester -Path ./test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
```

Expected behavior
-----------------
All Tests pass.

Actual behavior
---------------
The InnerException reports ErrorCode 11 when 6 was expected.

```
PSMessageDetails      :
Exception             : System.Net.NetworkInformation.PingException: Testing connection to computer 'fakeHost' failed: Cannot resolve
                        the target name. ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Resource temporarily
                        unavailable
                           at System.Net.Dns.InternalGetHostByName(String hostName)
                           at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
                           at Microsoft.PowerShell.Commands.TestConnectionCommand.InitProcessPing(String targetNameOrAddress, String&
                        resolvedTargetName, IPAddress& targetAddress) in /home/dantra/powershell/src/Microsoft.PowerShell.Commands.Manag
                        ement/commands/management/TestConnectionCommand.cs:line 835
                           --- End of inner exception stack trace ---
TargetObject          : fakeHost
CategoryInfo          : ResourceUnavailable: (fakeHost:String) [Test-Connection], PingException
FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

InnerException:

Message         : Resource temporarily unavailable
SocketErrorCode : TryAgain
ErrorCode       : 11
NativeErrorCode : 11
Data            : {}
InnerException  :
TargetSite      : System.Net.IPHostEntry InternalGetHostByName(System.String)
StackTrace      :    at System.Net.Dns.InternalGetHostByName(String hostName)
                     at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
                     at Microsoft.PowerShell.Commands.TestConnectionCommand.InitProcessPing(String targetNameOrAddress, String&
                  resolvedTargetName, IPAddress& targetAddress) in /home/dantra/powershell/src/Microsoft.PowerShell.Commands.Management/
                  commands/management/TestConnectionCommand.cs:line 835
HelpLink        :
Source          : System.Net.NameResolution
HResult         : 1
```

**Comment by iSazonov** [comment]
@dantraMSFT The API have unpredictable behavior on Unixes. I opened a issue https://github.com/dotnet/corefx/issues/28934 without progress.
