### ISSUE TITLE
SSH connection fails ssh command look up without default runspace

### ISSUE THREAD

**Issue by arahja** [PowerShell/PowerShell#7763]
This issue happens when hosting SMA.dll.

I am attempting to write a C# core program using the powershell core SDK to run powershell scripts on remote Linux systems. Running on .net core is a requirement for this project. I am trying to loosely follow a guide I found on [CodeProject](https://www.codeproject.com/Articles/773685/Enable-Remote-PowerShell-Execution-in-Csharp).

Steps to reproduce
------------------
This is my code:

```
using System;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {

            SSHConnectionInfo connectionInfo = new SSHConnectionInfo(userName: "user", computerName: "server", keyFilePath: "id_rsa");


            using (Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo))
            {
                runspace.Open(); // The program errors out here
                runspace.Close();

            }

        }
    }
}
```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

This is the error I am receiving:

```
Unhandled Exception: System.Management.Automation.Remoting.PSRemotingDataStructureException: An error has occurred which PowerShell cannot handle. A remote session might have ended. ---> System.ArgumentException: The path is not of a legal form.
Parameter name: path
   at System.IO.Path.GetDirectoryName(String path)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
   at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler`1 eventHandler, Object sender, T eventArgs)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at ConsoleApp1.Program.Main(String[] args) in C:\ConsoleApp1\ConsoleApp1\Program.cs:line 18
Press any key to continue . . .
```
and
```
{System.Management.Automation.Remoting.PSRemotingDataStructureException: An error has occurred which PowerShell cannot handle. A remote session might have ended. ---> System.InvalidOperationException: Failed to start the SSH client process needed for the remoting connection with error: The filename, directory name, or volume label syntax is incorrect. ---> System.ComponentModel.Win32Exception: The filename, directory name, or volume label syntax is incorrect
   at System.Management.Automation.Runspaces.SSHConnectionInfo.CreateProcessWithRedirectedStd(ProcessStartInfo startInfo, SafePipeHandle& stdInPipeServer, SafePipeHandle& stdOutPipeServer, SafePipeHandle& stdErrPipeServer)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcessImpl(ProcessStartInfo startInfo, StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcessImpl(ProcessStartInfo startInfo, StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Runspaces.SSHConnectionInfo.StartSSHProcess(StreamWriter& stdInWriterVar, StreamReader& stdOutReaderVar, StreamReader& stdErrReaderVar)
   at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CreateAsync()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.SendNegotiationAsync(RemoteSessionState sessionState)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.HandleStateChanged(Object sender, RemoteSessionStateEventArgs arg)
   at System.Management.Automation.ExtensionMethods.SafeInvoke[T](EventHandler``1 eventHandler, Object sender, T eventArgs)
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.RaiseStateMachineEvents()
   at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerStateMachine.ProcessEvents()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.RemoteRunspace.Open()
   at remote_powershell.Program.Main(String[] args) in C:\Users\arahja\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 17}	System.Management.Automation.Remoting.PSRemotingDataStructureException
```

It appears that my C# program is [unable to find the openssh executable](https://github.com/PowerShell/PowerShell/blob/3cc9d26bc26aeab81137a8a54b9b510b4525abe7/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2032).

Environment data
----------------

Installed Software:
- PowerShell Core 6.0.2
	- Version: 6.0.2
	- Environment Path: C:\Program Files\PowerShell\6.0.2\
- .net Core 2 SDK
	- Version: 2.1.201
	- Environment Path: C:\Program Files\dotnet\
- OpenSSH
	- Version: OpenSSH_for_Windows_7.6p1 and LibreSSL 2.6.4
	- Environment Path: C:\Program Files\OpenSSH\

[NuGet Packages](https://powershell.myget.org/F/powershell-core/api/v3/index.json):
- Microsoft.PowerShell.SDK
	- Version: 6.0.2
- System.Management.Automation
	- Version: 6.0.2

----------------

**Comment by SteveL-MSFT** [comment]
PSRP over SSH depends on ssh.exe being in the path

**Comment by SteveL-MSFT** [comment]
Just saw the discussion on the related issue.  Seems that @PaulHigin understands the issue and will work on this.

**Comment by iSazonov** [comment]
I think we should classify the Issue as a bug because the scenario doesn't work as expected.
