### ISSUE TITLE
Build from latest master branch does not exit cleanly

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#7900]
NOTE: This is *not* present in the release version of 6.1 and seems to have been introduced since.

Steps to reproduce
------------------

1. Build pwsh from latest master branch on win10
2. Attempt to close the window with the `X` button on the title bar

Expected behavior
-----------------

*pwsh exits cleanly*

Actual behavior
---------------

Error is displayed (in white text, _not_ red) and window remains open for a handful of seconds before exiting.
```none
PS> Assertion Failed
AMSI should have been uninitialized.

   at System.Management.Automation.AmsiUtils.VerifyAmsiUninitializeCalled() in <ReposorityLocation>\src\System.Management.Automation\security\SecuritySupport.cs:line 1694
   at System.Management.Automation.AMsiUtils.CurrentDomain_ProcessExit(Object sender, EventArgs e) in <RepositoryLocation>\src\System.Management.Automation\security\SecuritySupport.cs:line 1618
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1-126-g98cf44cdecd72ffc328c3b7ca216fae20a08f1e4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Dup #6862. And I'm annoyed too.
