### ISSUE TITLE
wmisearcher - The type initializer for 'System.Management.ManagementPath' threw an exception

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#7943]
After we added reference to Windows Compatibility Pack we enable `[wmisearcher]` without any test - and it doesn't work.

Steps to reproduce
------------------

```powershell
 $a=[wmisearcher]"SELECT * FROM Win32_Process"
```

Expected behavior
-----------------
```none
No exception
```

Actual behavior
---------------

```
Cannot convert value "SELECT CommandLine FROM Win32_Process" to type "System.Management.ManagementObjectSearcher". Error: "The type initializer for 'System.Management.ManagementPath' threw an exception."
At line:1 char:1
+ $a=[wmisearcher]"SELECT CommandLine FROM Win32_Process"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvalidCastToWMISearcher


$error[0].Exception | fl -Force


ErrorRecord                 : Cannot convert value "SELECT * FROM Win32_Process" to type
                              "System.Management.ManagementObjectSearcher". Error: "The type initializer for
                              'System.Management.ManagementPath' threw an exception."
WasThrownFromThrowStatement : False
Message                     : Cannot convert value "SELECT * FROM Win32_Process" to type
                              "System.Management.ManagementObjectSearcher". Error: "The type initializer for
                              'System.Management.ManagementPath' threw an exception."
Data                        : {}
InnerException              : System.Management.Automation.PSInvalidCastException: Cannot convert value
                              "SELECT * FROM Win32_Process" to type
                              "System.Management.ManagementObjectSearcher". Error: "The type initializer for
                              'System.Management.ManagementPath' threw an exception." --->
                              System.TypeInitializationException: The type initializer for
                              'System.Management.ManagementPath' threw an exception. --->
                              System.TypeInitializationException: The type initializer for
                              'System.Management.WmiNetUtilsHelper' threw an exception. --->
                              System.ArgumentNullException: Value cannot be null.
                              Parameter name: ptr
                                 at
                              System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr
                              ptr, Type t)
                                 at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDele
                              gate](IntPtr ptr)
                                 at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate&
                              delegate_f, IntPtr hModule, String procName)
                                 at System.Management.WmiNetUtilsHelper..cctor()
                                 --- End of inner exception stack trace ---
                                 at System.Management.MTAHelper.IsNoContextMTA()
                                 at System.Management.MTAHelper.CreateInMTA(Type type)
                                 at System.Management.ManagementPath.CreateWbemPath(String path)
                                 at System.Management.ManagementPath..ctor(String path)
                                 at System.Management.ManagementPath..cctor()
                                 --- End of inner exception stack trace ---
                                 at System.Management.ManagementScope._Clone(ManagementScope scope,
                              IdentifierChangedEventHandler handler)
                                 at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope,
                              ObjectQuery query, EnumerationOptions options)
                                 at
                              System.Management.Automation.LanguagePrimitives.ConvertToWMISearcher(Object
                              valueToConvert, Type resultType, Boolean recursion, PSObject
                              originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                              in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Autom
                              ation\engine\LanguagePrimitives.cs:line 2340
                                 --- End of inner exception stack trace ---
                                 at
                              System.Management.Automation.LanguagePrimitives.ConvertToWMISearcher(Object
                              valueToConvert, Type resultType, Boolean recursion, PSObject
                              originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                              in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.Management.Autom
                              ation\engine\LanguagePrimitives.cs:line 2346
                                 at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site,
                              T0 arg0)
                                 at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(Interpre
                              tedFrame frame) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\src\System.
                              Management.Automation\engine\interpreter\DynamicInstructions.Generated.cs:line
                              139
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.R
                              un(InterpretedFrame frame) in C:\Users\sie\Documents\GitHub\iSazonov\PowerShell\
                              src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:l
                              ine 356
TargetSite                  :
StackTrace                  :
HelpLink                    :
Source                      :
HResult                     : -2146233087

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0-92-gb941e62def5b0d74979c22fa01690ed68a454a8d
OS                             Microsoft Windows 10.0.10240
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Another repo

Steps to reproduce
------------------

```powershell
[System.Management.ManagementPath]::DefaultPath
```

Expected behavior
-----------------
```none
No exception
```

Actual behavior
---------------

```
The type initializer for 'System.Management.ManagementPath' threw an exception.
At line:1 char:1
+ [System.Management.ManagementPath]::DefaultPath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException

 $error[0].Exception | fl -Force


TypeName       : System.Management.ManagementPath
Message        : The type initializer for 'System.Management.ManagementPath' threw an exception.
Data           : {}
InnerException : System.TypeInitializationException: The type initializer for
                 'System.Management.WmiNetUtilsHelper' threw an exception. ---> System.ArgumentNullException:
                 Value cannot be null.
                 Parameter name: ptr
                    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type
                 t)
                    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr
                 ptr)
                    at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate& delegate_f,
                 IntPtr hModule, String procName)
                    at System.Management.WmiNetUtilsHelper..cctor()
                    --- End of inner exception stack trace ---
                    at System.Management.MTAHelper.IsNoContextMTA()
                    at System.Management.MTAHelper.CreateInMTA(Type type)
                    at System.Management.ManagementPath.CreateWbemPath(String path)
                    at System.Management.ManagementPath..ctor(String path)
                    at System.Management.ManagementPath..cctor()
TargetSite     : System.Management.ManagementScope _Clone(System.Management.ManagementScope,
                 System.Management.IdentifierChangedEventHandler)
StackTrace     :    at System.Management.ManagementScope._Clone(ManagementScope scope,
                 IdentifierChangedEventHandler handler)
                    at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope, ObjectQuery
                 query, EnumerationOptions options)
                    at Microsoft.PowerShell.Commands.GetProcessCommand.RetrieveProcessCommandLine(Process
                 process) in Process.cs:line 865
                    at Microsoft.PowerShell.Commands.GetProcessCommand.AddCommandLineToProcess(Process
                 process) in Process.cs:line 843
                    at Microsoft.PowerShell.Commands.GetProcessCommand.ProcessRecord() in Process.cs:line 696
                    at System.Management.Automation.Cmdlet.DoProcessRecord() in cmdlet.cs:line 170
                    at System.Management.Automation.CommandProcessor.ProcessRecord() in CommandProcessor.cs:line
                 346
HelpLink       :
Source         : System.Management
HResult        : -2146233036



PS > $error[0].Exception.InnerException | fl -Force


TypeName       : System.Management.WmiNetUtilsHelper
Message        : The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
Data           : {}
InnerException : System.ArgumentNullException: Value cannot be null.
                 Parameter name: ptr
                    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type
                 t)
                    at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr
                 ptr)
                    at System.Management.WmiNetUtilsHelper.LoadDelegate[TDelegate](TDelegate& delegate_f,
                 IntPtr hModule, String procName)
                    at System.Management.WmiNetUtilsHelper..cctor()
TargetSite     : Boolean IsNoContextMTA()
StackTrace     :    at System.Management.MTAHelper.IsNoContextMTA()
                    at System.Management.MTAHelper.CreateInMTA(Type type)
                    at System.Management.ManagementPath.CreateWbemPath(String path)
                    at System.Management.ManagementPath..ctor(String path)
                    at System.Management.ManagementPath..cctor()
HelpLink       :
Source         : System.Management
HResult        : -2146233036

```

**Comment by iSazonov** [comment]
Seems root problem is in internal CoreFX method `System.Management.WmiNetUtilsHelper..cctor()`

@SteveL-MSFT @daxian-dbw Can you confirm that the issue is not PowerShell issue. If so I'll open new issue in CoreFX repo.

**Comment by RichardSiddaway** [comment]
I just got this 

```
PS>  $query = [wmisearcher]"SELECT * FROM Win32_process WHERE Name LIKE 'p%'"
PS>  $query.get()

```
to work

also got these to work


 ```
  $query = [wmisearcher]"SELECT Commandline FROM Win32_process WHERE Name LIKE 'p%'"
   $query.get()
  
  $query = [wmisearcher]"SELECT Commandline FROM Win32_process"
 $query.get()


```
Your original code

```
$query = [wmisearcher]"SELECT * FROM Win32_process"
$query.get()


```
Also worked for me


I can't reproduce your error

```
PS>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@RichardSiddaway Thanks! My system is Microsoft Windows _10.0.10240_ - maybe it matters.

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks! I'll close the issue. If the problem only with 10.0.10240 we can reopen.
