### ISSUE TITLE
Unhandled exception in ConsolePal.ReadKey

### ISSUE THREAD

**Issue by edyoung** [PowerShell/PowerShell#7996]
Steps to reproduce
------------------
I don't have a consistent repro, sorry. See version details below. Typed c d<backspace><backspace>, pwsh hung for about 10 seconds then produced error below and exited

```powershell
PS C:\onebranch> c
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

Expected behavior
-----------------
Don't crash

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
We need repo.

**Comment by SteveL-MSFT** [comment]
Can you open this in the PSReadLine repo?  `PSConsoleReadLine` is coming from PSReadLine

**Comment by iSazonov** [comment]
@daxian-dbw Could you please make a conclusion about the issue while you is on the wave?
