### ISSUE TITLE
OpenSUSE Tumbleweed - Couldn't find a valid ICU package

### ISSUE THREAD

**Issue by savornicesei** [PowerShell/PowerShell#8198]
Hi all,

I have installed powershell 6.1.0 from MS official repository on my OpenSUSE Tumbleweed.
When I want to run powershell (>pwsh) I get:
ailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)

This has been fixed in [dotnet core setup](https://github.com/dotnet/core-setup/issues/4413) so I hope it can be ported into PS.

Thanks.

**Comment by iSazonov** [comment]
@savornicesei Thanks for your report! PowerShell Core doesn't directly depend on ICU - it is CoreFX dependency. We get the CoreFX fix with servicing updates. You can check with latest PowerShell Core builds (6.20 Preview1 or night builds).

**Comment by savornicesei** [comment]
@iSazonov Thank you. It's good to know the fix will come from upstream and no additional changes in powershell are required.
