### ISSUE TITLE
Error while using "ctrl-l"

### ISSUE THREAD

**Issue by abhi18av** [PowerShell/PowerShell#8342]
Hi Powershell team,

I recently updated my `powershell` on mac to `v6.1.x` and I've started to come across the following error on pressing `ctrl-l`.

```
PS /Users/eklavya>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 30 Keys:

 Ctrl+l Ctrl+l Ctrl+l Enter
 Enter
 Enter
 Enter
 Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Enter
 Enter
 Ctrl+l Enter
 Enter
 Enter
 Enter
 Ctrl+l Enter
 Ctrl+l l s Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l


Exception:

System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

```

Here's my `$PSVersionTable` output

```
PS /Users/eklavya> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Darwin 17.5.0 Darwin Kernel V...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



```

**Comment by kvprasoon** [comment]
As mentioned, please report it in [PSReadLine](https://github.com/lzybkr/PSReadLine/issues/new) repo.

**Comment by lzybkr** [comment]
Closing as a duplicate of https://github.com/lzybkr/PSReadLine/issues/654.

**Comment by abhi18av** [comment]
I understand and thanks for the quick response.
