### ISSUE TITLE
ParameterBindingArgumentTransformationException When using Copy-Item -ToSession

### ISSUE THREAD

**Issue by tdaniely** [PowerShell/PowerShell#8480]
# Steps to reproduce

Running this script.

```powershell
$servers = "IP1", "IP2"

$sessions = New-PSSession -HostName $servers -UserName Administrator

Invoke-Command $sessions {
    Remove-Item -Force -Recurse "C:\EdgeDriver" -ErrorAction SilentlyContinue
    New-Item -ItemType Directory "C:\EdgeDriver" | Out-Null
}

foreach ($session in $sessions) {
    Copy-Item "C:/Users/redacted/Downloads/MicrosoftWebDriver.exe" "C:\EdgeDriver\MicrosoftWebDriver.exe" -ToSession $session
}

Get-PSSession | Remove-PSSession

```

The target servers are running:
- Windows Server 2016 14393.2580
- OpenSSH v7.7.2.0p1-Beta   (sshd is running on desktop, these are automated testing nodes)
- PowerShellCore 6.2.0-preview.1 (MSI package)

# Expected behavior

File is copied with no errors.

# Actual behavior

File **is copied** but the following error shows for every session.

```none
Copy-Item : Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
At C:\Users\redacted\Desktop\webdriver.ps1:9 char:5
+     Copy-Item "C:/Users/redacted/Downloads/MicrosoftWebDriver.exe" "C ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], ParameterBindin...mationException
+ FullyQualifiedErrorId : System.Management.Automation.ParameterBindingArgumentTransformationException,PSCopyFileAlternateStreamToRemoteSession

Copy-Item : Failed to copy file C:\Users\redacted\Downloads\MicrosoftWebDriver.exe to remote target destination.
At C:\Users\redacted\Desktop\webdriver.ps1:9 char:5
+     Copy-Item "C:/Users/redacted/Downloads/MicrosoftWebDriver.exe" "C ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (C:\Users\redact...ftWebDriver.exe:String) [Copy-Item], IOException
+ FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand
```

# Environment data

Version on the workstation.

```none
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Are you sure you are connecting to PowerShell Core endpoint (not Windows PowerShell endpoint)?

**Comment by tdaniely** [comment]
Yes, from sshd_config
`Subsystem	powershell	c:/PowerShell/6-preview/pwsh.exe -sshs -NoLogo -NoProfile`

**Comment by tdaniely** [comment]
Note, I could easily reproduce this on my home PC.

```
PS C:\Users\user\Desktop> $s = New-PSSession -HostName localhost -UserName user
PS C:\Users\user\Desktop> $s

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
  2 Runspace1       SSH       localhost       RemoteMachine   Opened        DefaultShell             Available


PS C:\Users\user\Desktop> Copy-Item '.\file.doc' "C:\test.doc" -ToSession $s
Copy-Item : Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
At line:1 char:1
+ Copy-Item '.\file.doc' "C:\test.doc" -ToSession ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], ParameterBindin...mationException
+ FullyQualifiedErrorId : System.Management.Automation.ParameterBindingArgumentTransformationException,PSCopyFileAlternateStreamToRemoteSession

Copy-Item : Failed to copy file C:\Users\user\Desktop\file.doc to remote target destination.
At line:1 char:1
+ Copy-Item '.\file.doc' "C:\test.doc" -ToSession ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (C:\Users\user\...file.doc:String) [Copy-Item], IOException
+ FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand

PS C:\Users\user\Desktop>
```

**Comment by edwardskrod** [comment]
I'm hitting this on a GitHub Build machine in my CI pipeline in my GitHub repo:

Set-Content : Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

You can see it in the "Decode the .pfx" step.
https://github.com/edwardskrod/devops-for-windows-apps/pull/11/checks?check_run_id=355565392

This works fine on my dev box.   Can anyone help me get this working?

$pfx_cert = Get-Content '.\EdwardSkrodDeveloper_password.pfx' -Encoding Byte
$base64 = [System.Convert]::ToBase64String($pfx_cert)
$pfx_cert_byte = [System.Convert]::FromBase64String($base64) 
Set-Content -Path '.\SigningCertificate.pfx' -Value "$pfx_cert_byte" -Encoding Byte

The idea is that I want to encode my signing certificate so that I can store it in in GitHub Secrets.   Then I want to decode it back to the original .pfx.    On my dev machine, setting -Encoding to Byte works great.   But it doesn't work on the GitHub machine.

**Comment by iSazonov** [comment]
@edwardskrod In PowerShell Core you should use -AsByteStream instead of -Encoding Byte.

**Comment by mattcargile** [comment]
I just ran into this copying from a _7.3.0_ local "session" to a remote _PSSession_ on _7.2.6_. I resolved the issue by copying to the `microsoft.powershell` endpoint found in output from `Get-PSSessionConfiguration`. This is the _5.1_ endpoint.

**Comment by speed2048** [comment]
I ran into this when I put -Recurse in the command line,

Copy-Item "E:\temp\*" -Destination "C:\e:\temp"  -ToSession $session -Force -Recurse

The interesting thing to add is that the files to copy to the destination.

**Comment by dkaszews** [comment]
Same thing, unable to copy anything that is not a text file. Why does `Copy-Item` care about encoding at all?!

**Comment by a-stankevich** [comment]
Same here. How do we get this reopened and fixed? Or should a new issue be created instead? @iSazonov

**Comment by kilasuit** [comment]
Just ran into this myself in 7.6.0-preview.4 trying to copy a file either from or to another session & the files were mp4 files.


<details>
<summary> info from get-error</summary>

```powershell

Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.ArgumentException: 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                     at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                                     at System.Text.EncodingTable.GetCodePageFromName(String name)
                                     at System.Text.Encoding.GetEncoding(String name)
                                     at System.Management.Automation.ArgumentToEncodingTransformationAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
                                     at System.Management.Automation.ArgumentTransformationAttribute.TransformInternal(EngineIntrinsics engineIntrinsics, Object inputData, Boolean trackDataInputSource)
                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.ArgumentException: 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                             at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                                             at System.Text.EncodingTable.GetCodePageFromName(String name)
                                             at System.Text.Encoding.GetEncoding(String name)
                                             at System.Management.Automation.ArgumentToEncodingTransformationAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
                                             at System.Management.Automation.ArgumentTransformationAttribute.TransformInternal(EngineIntrinsics engineIntrinsics, Object inputData, Boolean trackDataInputSource)
                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.ArgumentException: 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                                     at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                                                     at System.Text.EncodingTable.GetCodePageFromName(String name)
                                                     at System.Text.Encoding.GetEncoding(String name)
                                                     at System.Management.Automation.ArgumentToEncodingTransformationAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
                                                     at System.Management.Automation.ArgumentTransformationAttribute.TransformInternal(EngineIntrinsics engineIntrinsics, Object inputData, Boolean trackDataInputSource)
                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.ArgumentException: 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                                             at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                                                             at System.Text.EncodingTable.GetCodePageFromName(String name)
                                                             at System.Text.Encoding.GetEncoding(String name)
                                                             at System.Management.Automation.ArgumentToEncodingTransformationAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
                                                             at System.Management.Automation.ArgumentTransformationAttribute.TransformInternal(EngineIntrinsics engineIntrinsics, Object inputData, Boolean trackDataInputSource)
                                                             at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.ArgumentException: 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                                                     at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                                                                     at System.Text.EncodingTable.GetCodePageFromName(String name)
                                                                     at System.Text.Encoding.GetEncoding(String name)
                                                                     at System.Management.Automation.ArgumentToEncodingTransformationAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData)
                                                                     at System.Management.Automation.ArgumentTransformationAttribute.TransformInternal(EngineIntrinsics engineIntrinsics, Object inputData, Boolean trackDataInputSource)
                                                                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                                    HResult                        : -2146233087
                                CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
                                FullyQualifiedErrorId : System.ArgumentException,WriteException
                                InvocationInfo        : 
                                    MyCommand        : Copy-Item
                                    ScriptLineNumber : 1
                                    OffsetInLine     : 1
                                    HistoryId        : 15
                                    Line             : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                                    Statement        : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                                    PositionMessage  : At line:1 char:1
                                                       + copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                                                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    InvocationName   : copy-item
                                    CommandOrigin    : Internal
                                ScriptStackTrace      : at WriteException, <No file>: line 139
                                                        at PSCopyFileFromRemoteSession, <No file>: line 218
                                                        at PSCopyFromSessionHelper, <No file>: line 449
                                PipelineIterationInfo : 
                                                                      0
                                                                      1
                            Message                        : 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                            HResult                        : -2146233087
                        CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
                        FullyQualifiedErrorId : System.ArgumentException,WriteException
                        InvocationInfo        : 
                            MyCommand        : Copy-Item
                            ScriptLineNumber : 1
                            OffsetInLine     : 1
                            HistoryId        : 15
                            Line             : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                            Statement        : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                            PositionMessage  : At line:1 char:1
                                               + copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            InvocationName   : copy-item
                            CommandOrigin    : Internal
                        ScriptStackTrace      : at WriteException, <No file>: line 139
                                                at PSCopyFileFromRemoteSession, <No file>: line 218
                                                at PSCopyFromSessionHelper, <No file>: line 449
                        PipelineIterationInfo : 
                                                      0
                                                      1
                    Message                        : 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                    HResult                        : -2146233087
                CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
                FullyQualifiedErrorId : System.ArgumentException,WriteException
                InvocationInfo        : 
                    MyCommand        : Copy-Item
                    ScriptLineNumber : 1
                    OffsetInLine     : 1
                    HistoryId        : 15
                    Line             : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                    Statement        : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                    PositionMessage  : At line:1 char:1
                                       + copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    InvocationName   : copy-item
                    CommandOrigin    : Internal
                ScriptStackTrace      : at WriteException, <No file>: line 139
                                        at PSCopyFileFromRemoteSession, <No file>: line 218
                                        at PSCopyFromSessionHelper, <No file>: line 449
                PipelineIterationInfo : 
                                      0
                                      1
            Message                        : 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
            HResult                        : -2146233087
        CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
        FullyQualifiedErrorId : System.ArgumentException,WriteException
        InvocationInfo        : 
            MyCommand        : Copy-Item
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 15
            Line             : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
            Statement        : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
            PositionMessage  : At line:1 char:1
                               + copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            InvocationName   : copy-item
            CommandOrigin    : Internal
        ScriptStackTrace      : at WriteException, <No file>: line 139
                                at PSCopyFileFromRemoteSession, <No file>: line 218
                                at PSCopyFromSessionHelper, <No file>: line 449
        PipelineIterationInfo : 
                      0
                      1
    Message                        : 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
    HResult                        : -2146233087
CategoryInfo          : NotSpecified: (:) [Write-Error], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,WriteException
InvocationInfo        : 
    MyCommand        : Copy-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 15
    Line             : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
    Statement        : copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
    PositionMessage  : At line:1 char:1
                       + copy-item $file -Destination C:\Tmp\ -Force -FromSession $SGO
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : copy-item
    CommandOrigin    : Internal
ScriptStackTrace      : at WriteException, <No file>: line 139
                        at PSCopyFileFromRemoteSession, <No file>: line 218
                        at PSCopyFromSessionHelper, <No file>: line 449
PipelineIterationInfo : 
      0
      1

```
</details>

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets investigated this.  It appears that the injected functions over PSRP has a bug that is using the WinPS version of the Content cmdlets is using the old `-Encoding Byte` instead of `-AsByteStream` only in the case where the file has an alternate stream.  The bug appears in two places: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L8579 and https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L8951.  The change itself is simple, but adding tests will require a file that has an alternate stream (can be done using `Set-Content -Stream`.  We would recommend fixing this bug.  We also recommend using dedicated file copy utils like scp, robocopy, etc..., however, sometimes all you have is a PSSession so this bug will prevent some cases from working.

<blockquote><img src="https://repository-images.githubusercontent.com/49609581/aad0ad80-cdec-11ea-8248-a37bc0571bfd" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs">PowerShell/src/System.Management.Automation/namespaces/FileSystemProvider.cs at master · PowerShell/PowerShell</a></strong></div><div>PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/49609581/aad0ad80-cdec-11ea-8248-a37bc0571bfd" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs">PowerShell/src/System.Management.Automation/namespaces/FileSystemProvider.cs at master · PowerShell/PowerShell</a></strong></div><div>PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.</div></blockquote>

**Comment by John0King** [comment]
any fix or workround for this ?   I can confirm that  7.6.6 <--> 7.6.6  still has this issue
