### ISSUE TITLE
Invoke-RestMethod should support more encoding

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#8510]
There is a GBK coding site here, http://ip138.com

Invoke-WebRequest can return content normally,
I hope to Invoke-RestMethod support it.

Steps to reproduce
------------------
```powershell
Invoke-WebRequest ip138.com #normal

Invoke-RestMethod ip138.com
Invoke-RestMethod : No data is available for encoding 936. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
At line:1 char:1
+ Invoke-RestMethod ip138.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotImplemented: (:) [Invoke-RestMethod], NotSupportedException
+ FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
```

Environment data
----------------
centos76 + ps v6.1.1  

centos76 + ps 6.2.0-preview.3  

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by markekraus** [comment]
@chuanjiao10 I can't seem to replicate this in 6.1.2 and centos7.

if I do

```powershell
[System.Text.Encoding]::GetEncoding(936)
````

I see the CP is there for simplified Chinese. 

Using a VPN through Hong Kong (http://ip138.com does not appear to be reachable from the US) I can do 

```powershell
$result = Invoke-WebRequest ip138.com
$result.Content -split "`r`n" | select -first 10
$result.Encoding
````

Result:

```none
<html>                                                                                                                          <head>
                <meta charset="gb2312">
                <meta name="mobile-agent" content="format=html5; url=http://m.ip138.com/">
                <title>IP地址查询--手机号码查询归属地 | 邮政编码查询 | 长途电话区号 | 身份证号码验证在线查询网</title>
                <meta name="keywords" content="ip,IP查询,IP地址查询,ip138"/>
                <meta name="description" content="ip,IP查询,IP地址查询,ip138"/>
                <script type="text/javascript">
                        <!--
Preamble          :
BodyName          :
EncodingName      : Chinese Simplified (GB2312)
HeaderName        :
WebName           : gb2312
WindowsCodePage   :
IsBrowserDisplay  :
IsBrowserSave     :
IsMailNewsDisplay :
IsMailNewsSave    :
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936
```

**Comment by chuanjiao10** [comment]
**Invoke-WebRequest** ip138.com #normal

**Invoke-RestMethod**       ip138.com
Invoke-RestMethod : No data is available for encoding 936. 

i just test again, powershell core 6.1.2 on centos7 has tis problem

**Comment by markekraus** [comment]
@chuanjiao10 My apologies, I missed that it was just with Invoke-RestMethod. I get the same thing on Windows.

I'm labeling this a bug as we should be able to parse this in IRM if it works in IWR.

more details on the exception for future troubleshooting:

```none
Message        : No data is available for encoding 936. For information on defining a custom encoding, see the
                 documentation for the Encoding.RegisterProvider method.
Data           : {}
InnerException :
TargetSite     : Void GetDataItem()
StackTrace     :    at System.Text.Encoding.GetDataItem()
                    at System.Text.Encoding.get_HeaderName()
                    at Microsoft.PowerShell.Commands.InvokeRestMethodCommand.ProcessResponse(HttpResponseMessage
                 response)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       :
Source         : System.Private.CoreLib
HResult        : -2146233067
```

**Comment by chuanjiao10** [comment]
en, thanks for confirm.
