### ISSUE TITLE
Using AutomationNull as a method argument for value type parameter throws incorrect exception

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#8661]
# Steps to reproduce

```powershell
$emptyResult = $null | ForEach-Object { }
[Math]::Round($emptyResult)
```

# Expected behavior

* Follows normal conversion rules and uses the default value for `int` in place of `$emptyResult`.

* **Or** at the very least catch the exception from `Expression.Constant` and rethrow as a `nullToObjectInvalidCast` similar to this:

```
> [System.Reflection.Metadata.MethodDefinitionHandle]$null
Cannot convert null to type "System.Reflection.Metadata.MethodDefinitionHandle".
At line:1 char:1
+ [System.Reflection.Metadata.MethodDefinitionHandle]$null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : nullToObjectInvalidCast
```

# Actual behavior

```none
Argument types do not match
At line:1 char:1
+ [Math]::Round($emptyResult)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Other details

```powershell
> $Error[0].Exception.GetBaseException() | Format-List * -Force

Message        : Argument types do not match
ParamName      :
Data           : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException :
TargetSite     : System.Linq.Expressions.ConstantExpression Constant(System.Object, System.Type)
StackTrace     :    at System.Linq.Expressions.Expression.Constant(Object value, Type type)
                    at System.Management.Automation.Language.DynamicMetaObjectExtensions.CastOrConvertMethodArgument(Dy
                 namicMetaObject target, Type parameterType, String parameterName, String methodName, List`1 temps,
                 List`1 initTemps)
                    at System.Management.Automation.Language.PSInvokeMemberBinder.InvokeMethod(MethodBase mi,
                 DynamicMetaObject target, DynamicMetaObject[] args, Boolean expandParameters, MethodInvocationType
                 invocationInvocationType)
                    at System.Management.Automation.Language.PSInvokeMemberBinder.InvokeDotNetMethod(CallInfo
                 callInfo, String name, PSMethodInvocationConstraints psMethodInvocationConstraints,
                 MethodInvocationType methodInvocationType, DynamicMetaObject target, DynamicMetaObject[] args,
                 BindingRestrictions restrictions, MethodInformation[] mi, Type errorExceptionType)
                    at
                 System.Management.Automation.Language.PSInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject
                 target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)
                    at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder,
                 DynamicMetaObject[] args)
                    at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters,
                 LabelTarget returnLabel)
                    at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
HelpLink       :
Source         : System.Core
HResult        : -2147024809

```

This also reproduces in Windows PowerShell 5.1

**Comment by BrucePay** [comment]
@SeeminglyScience Interestingly it does work properly in version 2:
```powershell
PS[2] (4) > $emptyResult = $null | ForEach-Object { }
PS[2] (5) > [Math]::Round($emptyResult)
0
```
The original intent was that `AutomationNull` should never end up in a variable. It's supposed to be converted to `$null` during the assignment. V2 works properly so it might have been broken in the move to the DLR but it's such an obscure thing no one ever noticed.

**Comment by SeeminglyScience** [comment]
> V2 works properly so it might have been broken in the move to the DLR but it's such an obscure thing no one ever noticed.

Ah yes, that would make sense since it throws here:

https://github.com/PowerShell/PowerShell/blob/1be3f4cc0e465ae11ad8e59e9060f5a59e4762eb/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L254-L257

It's not *immediately* apparent that `Expression.Constant` could throw there, very easy to miss.

That said, I'm not sure what the desired behavior is exactly.  My first instinct is it should throw follow conversion rules for `$null`, *but* `AutomationNull` does handle value types a little differently in conversions.

```powershell
# $null throws without a specific conversion rule (e.g. null to int)
> [System.Reflection.Metadata.MethodDefinitionHandle]$null
Cannot convert null to type "System.Reflection.Metadata.MethodDefinitionHandle".
At line:1 char:1
+ [System.Reflection.Metadata.MethodDefinitionHandle]$null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : nullToObjectInvalidCast

# AutomationNull seems to use Expression.Default(type)
> [System.Reflection.Metadata.MethodDefinitionHandle][System.Management.Automation.Internal.AutomationNull]::Value
IsNil
-----
 True

**Comment by BrucePay** [comment]
`AutomationNull` represents the absence of a value which really only makes sense in a stream (pipeline). In a value context, `AutomationNull` is intended to become a `null`. Now `null` in a numeric value context becomes 0 so I assume that the converter for `AutomationNull` skips the intermediate step and is going to the default value for the target type. IIRC we also (but I guess inconsistently) use `default()` for `null` conversion too so there may be a bug in the actual null conversions. @lzybkr might know more.
