### ISSUE TITLE
Invoke-WebRequest resolves host names (URIs without http:// or https://) inconsistently

### ISSUE THREAD

**Issue by burkasaurusrex** [PowerShell/PowerShell#8935]
# Steps to reproduce

```powershell
IWR "unifiedpowerusa.com"
```

# Expected behavior

```
IWR "http://unifiedpowerusa.com"
```

# Actual behavior

```
IWR : Specified argument was out of the range of valid values.
Parameter name: baseUri
At line:1 char:1
+ iwr "unifiedpowerusa.com"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], ArgumentOutOfRangeException
+ FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by markekraus** [comment]
It looks like this has to do with the `Link` header that `https://unifiedpowerusa.com` returns

```none
Link: <https://unifiedpowerusa.com/wp-json/>; rel="https://api.w.org/", <https://unifiedpowerusa.com/>; rel=shortlink
```

is some how hitting

https://github.com/PowerShell/PowerShell/blob/ff3edaa2e38d715b287bbb7046fd75a5ba5d1061/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1824

and blowing up but only when it is redirected to. There is obviously a bug in here somewhere as going directly to https://unifiedpowerusa.com/ works fine.

```none
Message        : Specified argument was out of the range of valid values.
                 Parameter name: baseUri
ActualValue    :
ParamName      : baseUri
Data           : {}
InnerException :
TargetSite     : Void .ctor(System.Uri, System.String)
StackTrace     :    at System.Uri..ctor(Uri baseUri, String relativeUri)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ParseLinkHeader(HttpResponseMessage response, Uri requestUri)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink       :
Source         : System.Private.Uri
HResult        : -2146233086
```

**Comment by markekraus** [comment]
diging deeper.. we are using the value provided un the `-Uri` parameter to build the relative URI for links. This fails when the URI does not include a schema. A good work around is to ignore the user provided uri and use the URI resolved in `response.RequestMessage.RequestUri` which should have the absolute URI with the correct schema as determined by `HttpClient`
