### ISSUE TITLE
Unable to load DLL 'api-ms-win-core-job'

### ISSUE THREAD

**Issue by wizofe** [PowerShell/PowerShell#9465]
# Steps to reproduce

```powershell
PS C:\Users\xxx\AppData\Local\Thinkbox\Deadline10\temp> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=========================================================================================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.PowerShell.Commands.NativeMethods.CreateJobObject(IntPtr lpJobAttributes, String lpName)
   at Microsoft.PowerShell.Commands.ProcessCollection..ctor()
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
Failed to extract files from D:\dev\scoop\apps\7zip\19.00\7z1900-x64.msi.
Log file:
  D:\dev\scoop\apps\7zip\19.00\msi.log
```

# Expected behavior

```none
Install the git using scoop.
```

# Actual behavior

```none
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.PowerShell.Commands.NativeMethods.CreateJobObject(IntPtr lpJobAttributes, String lpName)
   at Microsoft.PowerShell.Commands.ProcessCollection..ctor()
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0-rc.1
PSEdition                      Core
GitCommitId                    6.2.0-rc.1
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fmichaleczek** [comment]
@wizofe The command you are executing is not in this repository, you should open an issue in scoop's repository instead.

**Comment by iSazonov** [comment]
It is dup #6561 (and #5981).
