### ISSUE TITLE
Cannot launch pwsh via Visual Studio or bin folder (i.e. not publish folder) any more

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#9810]
# Steps to reproduce

Pre-build PowerShell on the command line
```powershell
Import-Module build.psm1; Start-PSBuild -Clean; Invoke-Item PowerShell.sln
```
Then press `F5` in `Visual studio` with `powershell-win-core` being the startup project

# Expected behavior

Works

# Actual behavior

Crashes:

```
FailFast:
Common Language Runtime detected an invalid program.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

Exception details:
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.PowerShell.ConsoleControl.WriteConsole(SafeFileHandle consoleHandle, ReadOnlySpan`1 output, Boolean newLine)
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteToConsole(ReadOnlySpan`1 value, Boolean transcribeResult, Boolean newLine) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 584
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteLineToConsole(ReadOnlySpan`1 value, Boolean transcribeResult) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 643
   at Microsoft.PowerShell.ConsoleTextWriter.WriteLine(String value) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleTextWriter.cs:line 57
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteImpl(String value, Boolean newLine) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 722
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteLine(String value) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 818
   at Microsoft.PowerShell.CommandLineParameterParser.DisplayBanner() in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 657
   at Microsoft.PowerShell.CommandLineParameterParser.ParseHelper(String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 1028
   at Microsoft.PowerShell.CommandLineParameterParser.Parse(String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 699
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 166
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleShell.cs:line 29
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ManagedEntrance.cs:line 73

C:\Users\cberg\git\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp3.0\pwsh.exe (process 14660) exited with code -2146232797.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

# Environment data

- .Net Core 3 Preview 5 installed
- Latest Visual  Studio 16.2.0-Preview1 (with preview .net sdk option enabled)
- Win10 1809 (10.0.17763)
- Latest commit on master: `83708a4242befaae0e26d7f33e7ebe2f0091db08`

**Comment by bergmeister** [comment]
P.S. I get the same error when launching `pwsh.exe` from the `bin` folder (instead of from the `publish`) folder.
Also: When using the `Start-DevPowerShell` function, PowerShell get's nearly unusable as every command finishes after typing more than 2 characters, which might be a PSReadline issue or my prompt  modules (`posh-git`)

**Comment by rjmholt** [comment]
Ah maybe VS is trying to launch from the build folder. That hasn't worked in some time (can't find the issue though), but it hasn't been prioritised since that's never used.

> Also: When using the Start-DevPowerShell function, PowerShell get's nearly unusable as every command finishes after typing more than 2 characters, which might be a PSReadline issue or my prompt modules (posh-git)

`Start-DevPowerShell` doesn't load the profile I don't think, and it clears the module path. So that sounds like a proper bug. Haven't seen it myself yet though

**Comment by TravisEz13** [comment]
I cannot repro the issue with `start-DevPowerShell` and the solution has never started a viable version of PowerShell for me.   Talking to to Visual Studio, this is a feature they are not planning on adding.

**Comment by bergmeister** [comment]
Yes, I think the issue in general is that Vs launches from the `bin\Debug\netcoreapp3.0` folder and not `bin\Debug\netcoreapp3.0\publish`. This used to work fine in .Net Core 2.1. Maybe the best solution is to add a property to the solution or project to define the entry point to be in `bin\$(Configuration)\$(Framework)\publish`.
Today the issue with `Start-DevPowerShell` somehow went away btw (must've been something corrupt that got fixed by a reboot)

**Comment by bergmeister** [comment]
I created a `launchsettings.json` file in `powershell-win-core\Properties` to make it point to the `win7-x64\publish` folder and I found on startup I had to make it skip a ton of load exceptions but it worked at the end (apart from unicode characters by posh-git that cannot be displayed in the console).
It would be great if we could configure this file in such a way that it does not have a personal, hard-coded path in it any more.
```
{
  "profiles": {
    "powershell-win-core": {
      "commandName": "Executable",
      "executablePath": "C:\\Users\\cberg\\git\\PowerShell\\src\\powershell-win-core\\bin\\Debug\\netcoreapp3.0\\win7-x64\\publish\\pwsh.exe"
    }
  }
}
```
