### ISSUE TITLE
7.0.0-preview1: AutoCompleteStringCollection throws System.InvalidCastException: Interface not registered

### ISSUE THREAD

**Issue by ptytb** [PowerShell/PowerShell#9832]
# Steps to reproduce

```powershell
[System.Reflection.Assembly]::LoadWithPartialName('system.windows.forms')

$Form            = New-Object system.Windows.Forms.Form
$Form.ClientSize = New-Object System.Drawing.Size 100,100

$ac = New-Object System.Windows.Forms.AutoCompleteStringCollection
$null = $ac.AddRange(@('aaa', 'bbb', 'ccc'))

$tb = [System.Windows.Forms.TextBox]::new()
$tb.AutoCompleteMode = [System.Windows.Forms.AutoCompleteMode]::Suggest
$tb.AutoCompleteSource = [System.Windows.Forms.AutoCompleteSource]::CustomSource
$tb.AutoCompleteCustomSource = $ac

$null = $Form.controls.AddRange( @($tb) )

$Form.ShowDialog()
```

# Expected behavior

A working form with auto-completion, the code works in 5.1.

# Actual behavior

```none
************** Exception Text **************
System.InvalidCastException: Interface not registered

Failed to find proxy registration for IID: {EAC04BC0-3791-11D2-BB95-0060977B464C}.
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.StringSource..ctor(String[] strings)
   at System.Windows.Forms.TextBox.SetAutoComplete(Boolean reset)
   at System.Windows.Forms.TextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Details 

The CLSID stands for `IAutoComplete2` COM interface.

I've found that the following code on 5.1 gives a different result from PS 6.0 or 7.0:

```powershell
$obj = [type]::GetTypeFromCLSID('{EAC04BC0-3791-11D2-BB95-0060977B464C}')
$type = $obj.gettype()
$type.GetInterfaces()
```

`_MemberInfo`, `_Type` are missing on both 6.0 and 7.0

**Comment by iSazonov** [comment]
This works with 7.0-RC2.
