### ISSUE TITLE
Errors when pressing page up or page down in Powershell 7 Preview 1, Ubuntu on Windows 

### ISSUE THREAD

**Issue by ricmik** [PowerShell/PowerShell#9897]
# Steps to reproduce

```none
Running Powershell 7 Preview 1 in Ubuntu on windows:

Press Page Up or Page Down on the keyboard.
```

# Expected behavior

```none
Nothing should happen, or actual page up or page down scrolling should happen.
```

# Actual behavior

```none
\### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.1
OS: Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019
Last 2 Keys
\```
 PageUp PageDown
\```

\### Exception
\```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
\```
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please check without PSReadline.

**Comment by ricmik** [comment]
It works without PSReadline, but without PSReadline you also lose going through history by arrow up, arrow down, tab completion etc.

**Comment by iSazonov** [comment]
Please report the issue in https://github.com/PowerShell/PSReadLine

**Comment by ricmik** [comment]
Sure!
