### ISSUE TITLE
CreateElevatedEntry()

### ISSUE THREAD

**Issue by joshuatee** [PowerShell/PowerShell#9961]
what tat could be? for some reason ps6/7 keeps crashing with

> Internal CLR error. (0x80131506)
   at Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
   at Microsoft.PowerShell.ConsoleHost+<>c.<Start>b__4_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

PS
upon starting the console

**Comment by iSazonov** [comment]
@joshuatee Thanks for your report!

It is dup #9295 and fixed in #9928
